### ISSUE TITLE
How to collect data from a remote server?

### ISSUE THREAD

**Issue by neeraj9818** [graphite-project/graphite-web#1011]
Hi,

I want to collect data from remote server but don't want to install any tool, is it possible can graphite monitor a server and collect data without installing any tool on remote server, if yes which tool we can use?

**Comment by clohtd** [comment]
If the remote server is linux, you can send it with bash scripts and netcat.  Netcat is a standalone binary that you can copy over to the remote server.  Then just pipe your data to netcat.  Here's an example:

echo "1000" | gawk '{print "test.test1 " $1 " " systime()}' | /usr/local/bin/netcat 192.168.1.1 2003
