### ISSUE TITLE
Removed fam icons from extjs breaks images in dashboard

### ISSUE THREAD

**Issue by ssgelm** [graphite-project/graphite-web#1012]
It looks like the fam icons removed in #280 break the icons in the dashboard.  See: https://dl.dropbox.com/s/dfkbwoxizvd6ice/Screenshot%202014-10-31%2011.03.53.png?dl=0

**Comment by obfuscurity** [comment]
@ssgelm Can you elaborate on "looks like this is a problem in the current git HEAD"? Which version are you claiming is broken. As @brutasse points out, the links to the images are there, and the assets all exist in https://github.com/graphite-project/graphite-web/tree/master/webapp/content/js/ext/resources/icons/fam. Closing this out for now but if you're still having issues please let me know and we can reopen.

**Comment by ssgelm** [comment]
@obfuscurity Closing this seems totally reasonable.  It's been a while but at this point my best guess is that I was just mistaken.  If I manage to figure anything out I'll reopen.

**Comment by obfuscurity** [comment]
:heart:
