### ISSUE TITLE
Double timezone conversion in events

### ISSUE THREAD

**Issue by beevee** [graphite-project/graphite-web#1028]
I'm running current master branch of graphite-web with default sqlite database and django 1.5. Timezone is set to 'Europe/Moscow' in local_settings.py. That's UTC+3.

When I send an event without `when` parameter, it gets stored in sqlite in UTC time zone (3 hours earlier than my local time).

In standard web interface (http://graphite/events/) time is shown correctly in local timezone. But in /events/get_data all timestamps are in UTC-3. If I set timezone to UTC+5, all timestamps become UTC-5, but are still shown correctly on web page. Seems like timezone correction is applied twice only for json output.

I don't know what behaviour is intended (should time be stored in local timezone or in UTC), but it is obviously a bug.

**Comment by Leobaillard** [comment]
As mentioned in the last referenced issue from grafana, I'm still experiencing this problem in 0.9.13. Any ideas? My timezone is set as "Europe/Paris".

**Comment by deniszh** [comment]
Correspodent fix for 0.9.x is not merged yet - https://github.com/graphite-project/graphite-web/pull/1034
because tests are failing. Will try to check / fix that.

**Comment by Leobaillard** [comment]
Okay, my bad. I'll wait :smile:

**Comment by deniszh** [comment]
No, my bad - completely forgot about it from Nov. 2014 ;)
