### ISSUE TITLE
movingSum

### ISSUE THREAD

**Issue by aronatkins** [graphite-project/graphite-web#1036]
I have a metric counting events per minute. It would be nice to see the trailing sum of those events over the last day. This is different than `summarize` because the `summarize` function collapses 1440 minutes of data points (a day) into a single data point and results in graphs that are very discontinuous.

I would like to have a `movingSum` function which is similar to the `movingAverage` and `movingMedian` functions.

Bonus points for a general-purpose `movingWindow` function which takes one of a set of supported aggregation functions. `sum`, `avg`, `max`, `min`, `max`, and `median` all come to mind.

**Comment by MartinNowak** [comment]
Wouldn't a movingAverage of summarize fit your needs?

**Comment by aronatkins** [comment]
No, because it loses the granularity that you would have with a true moving sum.

**Comment by kevin-lin** [comment]
+1. I've also been looking for a way to have a moving version of the `Summarize` function so I can graph a `movingMin`.

If you are only looking for movingSum, you can use `movingAverage(timeInterval)` * (number of data points in `timeInterval`) to achieve that functionality.
