### ISSUE TITLE
Where is my metrics?

### ISSUE THREAD

**Issue by fote** [graphite-project/graphite-web#1039]
Hello.

I have an issue about graphite-web. I installed graphite-web in default location and started carbon-daemon. Carbon writing metrics in /opt/graphite/storage/ceres/. And there is a ceres metic files in folders.
But i can't select metrics in web interface. I see folders, but there is no metrics in it. Screenshot - https://dl.dropboxusercontent.com/u/65480202/screen_graphite.png

I checked dependencies and it's ok.

Can you help me please?

**Comment by clohtd** [comment]
Did you resolve this?  It looks like your metric has a "." following it so that instead of it being stored as a metric, it is stored as a subfolder.

**Comment by fote** [comment]
Yes, i resolved it by edit STORAGE_FINDERS in settings.py:
STORAGE_FINDERS = (
    'graphite.finders.ceres.CeresFinder',
)
