### ISSUE TITLE
Problem with the function holtWintersAberration

### ISSUE THREAD

**Issue by ashachar** [graphite-project/graphite-web#1047]
The holtWintersAberration function gives the following error:
TypeError at /render/
unsupported operand type(s) for -: 'float' and 'NoneType'

**Comment by obfuscurity** [comment]
I suspect this is related to #1341 and not a `holtWintersAberration`-specific bug, but there's really not enough detail here to be sure. Closing this as resolved but please let us know if this isn't the case.
