### ISSUE TITLE
Performance of queries that return large number of metrics

### ISSUE THREAD

**Issue by JarleB** [graphite-project/graphite-web#1058]
Lately I've been building some custom graphs that fetches a larger than usual (for me anyway) subset of metrics in our graphite cluster. I'm observing huge difference in time to retrieve about 1500 metrics if I go through the frontend graphite server, or if I go directly on the backend graphite server that I know the same data is located. 

An example to illustrate: 

```
jb@watershed ~ $ /usr/bin/time --format=%E curl -s 'http://frontend-server.uio.no/render/?target=collectd.*.ping.ping.*.uio.no.ping&format=raw&from=-2min' |wc -l
0:53.25
1678
jb@watershed ~ $

jb@watershed ~ $ /usr/bin/time --format=%E curl -s 'http://backend-server.uio.no/render/?target=collectd.*.ping.ping.*.uio.no.ping&format=raw&from=-2min' |wc -l
0:04.90
1678
jb@watershed ~ $
```

What happens is the following:

When the query is sent through the front end it hits the metric cache (same query was run just before, so cache is containing all metric locations) and instantly starts asking for single metrics from the back end server and when the backend has served up all 1678 requests, the front end returns the data to the client. 

When querying the back end directly all work is done locally, which takes considerably shorter time, and replies with the same data in less than 1/10 of the time. 

I wonder what would be the better approach to handle this? I'm thinking that a better approach would be to pass the unmodified urls with regexes to all backends, and collect and merge the returned data..

**Comment by JarleB** [comment]
For the record,  I can can confirm that 0.9.13-pre1 (includes  #1010 + #1026 ) completely eliminates this described slow behavior.

**Comment by obfuscurity** [comment]
@JarleB Awesome, thanks for the update.

**Comment by toni-moreno** [comment]
Hi @obfuscurity. I'm working with current master  branch.

Are these two parches medged on the current master branch ?

**Comment by bmhatfield** [comment]
@toni-moreno - not yet. Master is sufficiently different that simply cross-merging won't do it, they need to be rewritten :-(
