### ISSUE TITLE
Add instructions for contributing to documentation

### ISSUE THREAD

**Issue by ryan-williams** [graphite-project/graphite-web#1089]
Can PRs be filed here against the `docs` directory that will result in updates to the readthedocs.org site? Is the latter every re-published? Can it be?

I was reading through the docs again and wanted to suggest some improvements but wasn't sure that the above process is allowed/recommended; please advise!

**Comment by obfuscurity** [comment]
Yes, readthedocs regenerates automatically based on the content in this repo. I don't think we need specific instructions in the docs for improving the docs.

**Comment by ryan-williams** [comment]
heh, I also just noticed the "Edit on Github" badges on the upper-right of every page. fair enough!
