### ISSUE TITLE
Trailing parentheses in legend

### ISSUE THREAD

**Issue by bkeepers** [graphite-project/graphite-web#1101]
The labels have a trailing paren when using `groupByNode` and `keepLastValue`. Here is my target:

`?target=groupByNode(keepLastValue(hosts.splunk*.disk-*.disk_time.*),4,"sumSeries")`

![graph_editor](https://cloud.githubusercontent.com/assets/173/5706741/3a10d716-9a51-11e4-921d-da41fa293fe6.png)

Adding `substr(…, 0)` is enough to drop the trailing paren.

/cc @aroben

**Comment by jimpriest** [comment]
FYI - I get this with movingAverage inside groupByNode as well.

**Comment by obfuscurity** [comment]
related: #236

**Comment by AndrewStickler** [comment]
I get this with aliasByNode(keepLastValue(<metric>,100)).
