### ISSUE TITLE
vhost example references nonexistent django-admin.py script

### ISSUE THREAD

**Issue by ryan-williams** [graphite-project/graphite-web#1103]
https://github.com/graphite-project/graphite-web/blob/cda34860709eaf7bb41b887a3701968f851010cf/examples/example-graphite-vhost.conf#L42

```
        # XXX You need to generate this directory by running:
        # django-admin.py collectstatic --noinput --settings=graphite.settings
```

Did this script used to exist? Is it somewhere I'm no looking? I don't see it in any of the graphite repos.

**Comment by SEJeff** [comment]
django-admin.py is installed with django. If you used pip to install graphite, synthesize, or operating system packages it should be available. Feel free to send a pull request making the documentation more clear but since this isn't an issue, I'm going to go ahead and close it.

**Comment by obfuscurity** [comment]
Actually, Synthesize still installs Graphite 0.9.x + Django 1.4 (per requirements.txt) which doesn't use the collectstatic command.
