### ISSUE TITLE
multiplySeriesWithWildcards problem

### ISSUE THREAD

**Issue by senkrad76** [graphite-project/graphite-web#1104]
I'm attempting to create a graph representing Memory Usage Percentages.

I have a server naming convention similar to

```
Zenoss.zencollector0[1-3].Devices.[[silo]]Servername[[iteration]].DATAPOINT.ds0
```

I'm using Grafana, and have `[[silo]]` and `[[iteration]]` as templated values and the zencollector wildcarded as `zencollector*`.

I'm using two values `memAvailReal` and `memTotalReal` retrieved from JMX as datapoints.

In order to get the percentage i'm doing an invert on the `memTotalReal`.

Single instances work fine:

```
multiplySeries(Zenoss.zencollector*.Devices.p1server01.memAvailReal.ds0,invert(Zenoss.zencollector*.Devices.p1server01.memTotalReal.ds0))
```

However when I try to wildcard using either the template values for Grafana, or just using the wildcard I don't get the desired result.

The example shows:

```
multiplySeriesWithWildcards([web.host-[0-7].avg-response.value, web.host-[0-7].total-request.value], 2,3)
```

When I try to format like this I get no datapoints:

```
multiplySeriesWithWildcards([Zenoss.zencollector02.devices.p4SERVER[0-9].memAvailReal.ds0,invert(Zenoss.zencollector02.devices.p4SERVER[0-9].memTotalReal.ds0)],5,6)
```

When I remove the "[ ]" from the two values:

```
multiplySeriesWithWildcards(Zenoss.zencollector02.devices.p4SERVER[0-9].memAvailReal.ds0,invert(Zenoss.zencollector02.devices.p4SERVER[0-9].memTotalReal.ds0),5,6)
```

I get whichever value is first in the function call.

In the end I'd like to be able to utilize the templating function in Grafana and have a metric such as:

```
multiplySeriesWithWildcards([Zenoss.zencollector'*'.Devices.[[silo]]SERVER[[iteration]].memAvailReal.ds0,invert(Zenoss.zencollector'*'.Devices.[[silo]]SERVER[[iteration]].memTotalReal.ds0)],5,6)
```

Which would perform:

```
target=multiplySeries(Zenoss.zencollector01.Devices.p4SERVER01.memAvailReal.ds0,invert(Zenoss.zencollector01.Devices.p4SERVER01.memTotalReal.ds0)&target=multiplySeries(Zenoss.zencollector02.Devices.p2SERVER01.memAvailReal.ds0,invert(Zenoss.zencollector02.Devices.p2SERVER01.memTotalReal.ds0)&target=etc.
```

I'm I missing something and utilizing the function wrong? or is this an actual issue?

**Comment by obfuscurity** [comment]
Reformatted your original question so it's more legible.

**Comment by obfuscurity** [comment]
It would be helpful if you could narrow down the scope of your question to the bare minimum, e.g. "this basic Graphite query isn't working as expected". I've re-read your description numerous times and I can't wrap my head around the real issue because you have some Grafana-isms mixed in; I don't use Grafana so it's causing additional confusion.

I'd like to help but your queries are really awkward for me to parse. Maybe I just need more sleep. :)

I *did* notice that some of your examples use `5, 6` as index arguments to `multiplySeriesWithWildcards()`, but you only have six nodes (zero-indexed).

/cc @torkelo in the hopes that he might be able to translate some of the Grafana stuff.

**Comment by torkelo** [comment]
Not sure either,  probably the node index out of bounds

**Comment by g76r** [comment]
Selecting series with * or event with {used,total} does not guarantee any order. Moreover Selecting series like server.*.cpu.{used,total} does not guarantee that servers won't be mixed.

This is exactly why a coworker of mine created a non-merged "callbackToNode" method seen in #661.

However the way the function was coded/documented is not acceptable as is for merging and I did not yet take time to rewrite it.

If it can help you this works nice for us with asPercent() and diffSeries(). It is likely to work with multiplication or division either.

**Comment by senkrad76** [comment]
Sorry for the confusion... let me see if I can rephrase without the 'Grafana-isms' and maybe provide some clarity.

I'll start with the naming conventions:
`Zenoss.collector[0-3].devices.[0-5]server[0-9].memAvail.value`
&
`Zenoss.collector[0-3].devices.[0-5]server[0-9].memTotal.value`

What I'm trying to do is invert the `memTotal`'s and multiply them by the corresponding `memAvail`'s

There are two wildcards in the `server` node: one designates its silo, one designate the iteration.
We also have different collectors for Zenoss. (all the servers would most likely be on the same collector, but the wildcard is there to catch ones that aren't)

What would be the correct syntax to achieve:
```
target=multiplySeries(Zenoss.collector2.devices.1server1.memAvail.value,invert(Zenoss.collector2.devices.1server1.memTotal.value))&
target=multiplySeries(Zenoss.collector2.devices.1server2.memAvail.value,invert(Zenoss.collector2.devices.1server2.memTotal.value))&
target=multiplySeries(Zenoss.collector2.devices.2server1.memAvail.value,invert(Zenoss.collector2.devices.2server1.memTotal.value))& 
target=multiplySeries(Zenoss.collector3.devices.3server1.memAvail.value,invert(Zenoss.collector3.devices.2server1.memTotal.value))& etc
```
Is a problem occurring because of the two wildcards in the same node?

**Comment by tomekit** [comment]
I am facing the similar problem. I would like to multiple a list of series by another series.
Added the Grafana issue: https://github.com/grafana/grafana/issues/7106 
Obviously it's been closed, as it's really a Graphite problem.
