### ISSUE TITLE
isNonNull function not found

### ISSUE THREAD

**Issue by ryan-williams** [graphite-project/graphite-web#1121]
I'm seeing an error when trying to use the `isNonNull` function:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 122, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 27, in evaluateTokens
    func = SeriesFunctions[tokens.call.func]
KeyError: u'isNonNull'
```

Viewable [here](https://104.236.105.97/render/?width=586&height=308&target=isNonNull(local-1420327706967.%3Cdriver%3E.BlockManager.disk.diskSpaceUsed_MB)) on a graphite that I set up using the Synthesize/DO method, so presumably it's not a configuration problem on my end.

That same metric renders fine (it's empty but that's working as intended) if I drop the `isNonNull()` wrapping, e.g. [here](https://104.236.105.97/render/?width=586&height=308&target=local-1420327706967.%3Cdriver%3E.BlockManager.disk.diskSpaceUsed_MB).

Am I attempting to use `isNonNull` incorrectly, or what could the issue be?

**Comment by obfuscurity** [comment]
That function was only added to the `master` branch. Many of the `0.9.*` releases have been cut from the `0.9.x` branch. After the upcoming `0.9.13` release we'll be focusing on cutting new releases from `master` once again.

If you really need that function you can patch it manually; it was submitted in https://github.com/graphite-project/graphite-web/pull/365.
