### ISSUE TITLE
Zero gets rounded to -1.38778e-17

### ISSUE THREAD

**Issue by piotr1212** [graphite-project/graphite-web#1124]
on 0.9.13 pre1 0 gets wrongly rounded

![zero_rounding_error](https://cloud.githubusercontent.com/assets/2911066/5915384/951a0f64-a605-11e4-82d4-a2b650065ba2.png)

**Comment by piotr1212** [comment]
This happens on Fedora 21 and RHEL6.

**Comment by obfuscurity** [comment]
Are you certain this is a regression with 0.9.13? Did you run a previous version of Graphite in these same operating environments?

**Comment by obfuscurity** [comment]
Also, can you report the output of the following?

```
$ python
>>> import sys
>>> sys.float_info.epsilon
```

**Comment by piotr1212** [comment]
I've copied the wsp to a 0.9.12 rhel6 system and it shows the same error...

**Comment by piotr1212** [comment]
Python 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.float_info.epsilon
2.2204460492503131e-16
>>>

**Comment by piotr1212** [comment]
That was on rhel6,

f21 gives:
Python 2.7.8 (default, Nov 10 2014, 08:19:18) 
[GCC 4.9.2 20141101 (Red Hat 4.9.2-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.float_info.epsilon
2.220446049250313e-16
>>>

**Comment by obfuscurity** [comment]
I feel confident this has nothing to do with Graphite directly but I'm not sure which of the dependencies might be causing this discrepancy. I'm unable to reproduce this on any of my systems. Can you upload the wsp file somewhere I can download it?

**Comment by piotr1212** [comment]
https://piotrp.fedorapeople.org/graphite/cpuUsage.wsp

**Comment by piotr1212** [comment]
btw, this is carbon's cpuUsage metric. It starting at -0.25 is probably a (minor) bug too.

**Comment by obfuscurity** [comment]
I don't think this scale value is a bug per se but a product of the precision, possibly compounded by the fact we're looking at `None` values preceding it. I wonder if someone like @MathYourLife might be able to explain this.

**Comment by brutasse** [comment]
Whisper uses floats internally, so this isn't particularly surprising.

**Comment by MathYourLife** [comment]
whisper-dump would seem to to indicate the stored values are not rounded.
```
$ pip freeze
argparse==1.2.1
whisper==0.9.12
wsgiref==0.1.2
$ whisper-dump.py cpuUsage.wsp | grep -F -A 10 -B 4 "1422343380"
65894: 0,          0
65895: 0,          0
65896: 0,          0
65897: 0,          0
65898: 1422343380, -0.2259152934616708574555588029397768
65899: 1422343440, 0.014113819984270315963104103218483942
65900: 1422343500, 0.014294421680595659554513510158813006
65901: 1422343560, 0.011067390164903840449328598083411634
65902: 1422343620, 0.008860985979784796739977537072263658
65903: 1422343680, 0.012301582784986258428672201148401655
65904: 1422343740, 0.01002157782340001336562895772885895
65905: 1422343800, 0.0070676991639336602529786190984850691
65906: 1422343860, 0.007873066854831694758032334391373297
65907: 1422343920, 0.008597852064861463000644548060336092
65908: 1422343980, 0.0073200056138081805862105611026890983
```

```
$ epoch 1422343380
2015-01-27 07:23:00	1422343380.0
```

**Comment by obfuscurity** [comment]
@brutasse Agreed, I'm just surprised it hasn't surfaced (or at least, *been reported*) before.

**Comment by obfuscurity** [comment]
To clarify, my surprise is not that it's reporting in notation at times, but rather that it *only* does it when the range includes `None` values. If you change the range (and adjust the yMin and yStep accordingly), zero reports as 0.
