### ISSUE TITLE
/events/get_data fails with DatabaseError: too many SQL variables

### ISSUE THREAD

**Issue by rbroemeling** [graphite-project/graphite-web#1127]
We use graphite events to track deploys across multiple environments.  Thus a staging deploy will be tagged with "deploy staging" and a production deploy will be tagged with "deploy production".  Then we use those events to display annotations on a grafana dashboard.  It all worked well up until a month or so ago, when we started having problems -- Grafana reports an "Annotations Error" and that it cannot load annotations.  It is important to note that this _used_ to work, it is only more recently that it started failing, without any obvious cause.  We are using Grafana 1.8.1 (recently upgraded to Grafana 1.9.1; the problem persists -- reasonably sure that the problem isn't Grafana anyway, given that I can replicate the issue with a simple web-request to Graphite) and Graphite 0.9.12.

Our event log (at https://{graphite host}/events/) looks like this (the below has been sanitized, a little -- note that we have data back to 2012; I am only showing the latest exemplars):

| When | What | Tags |
| --- | --- | --- |
| 14:24:57 Wed 28 Jan 2015 | Branch master (at xxxxxxx) deployed as release 20150128142144 by C | deploy production |
| 14:28:57 Wed 28 Jan 2015 | Branch staging (at yyyyyyy) deployed as release 20150128142532 by C | deploy staging |
| 22:23:58 Wed 28 Jan 2015 | Branch master (at zzzzzzz) deployed as release 20150128222009 by K | deploy production |
| 00:23:27 Thu 29 Jan 2015 | Branch staging (at wwwwwww) deployed as release 20150129002020 by D | deploy staging |
| 01:16:29 Thu 29 Jan 2015 | Branch master (at vvvvvvv) deployed as release 20150129011316 by R | deploy production |

I've spent some time tracking it down, and I've found the problem to lie with the query that fetches data from our graphite instance.

The query looks like this: https://{graphite host}/events/get_data?from=-24h&until=now&tags=deploy%20production

This query fails with a stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/events/views.py", line 71, in get_data
    json.dumps(fetch(request), cls=EventEncoder),
  File "/opt/graphite/webapp/graphite/events/views.py", line 99, in fetch
    models.Event.find_events(time_from, time_until, tags=tags)]
  File "/opt/graphite/webapp/graphite/events/models.py", line 42, in find_events
    result = list(query.order_by("when"))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 87, in __len__
    self._result_cache.extend(self._iter)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: too many SQL variables
```

What is particularly interesting is that the following queries all work (i.e. they return a normal result set of JSON-encoded event data):
- https://{graphite host}/events/get_data?from=-24h&until=now&tags=deploy
- https://{graphite host}/events/get_data?from=-24h&until=now&tags=production
- https://{graphite host}/events/get_data?from=-24h&until=now&tags=deploy%20staging

It is only the tags query that combines "production" with "deploy" that fails (I've tried both "production deploy" and "deploy production").

Frankly, I'm at a loss as to what the next steps are.  Is there any diagnostic data that I can pass on to you that would help to solve this issue?

**Comment by obfuscurity** [comment]
You're hitting a [limitation within SQLite](http://stackoverflow.com/questions/7106016/too-many-sql-variables-error-in-django-witih-sqlite3), not Graphite. My suggestion would be to move to a real RDBMS.

* http://obfuscurity.com/2013/12/Why-You-Shouldnt-use-SQLite-with-Graphite
* http://obfuscurity.com/2013/12/Migrating-Graphite-from-SQLite-to-PostgreSQL

**Comment by rbroemeling** [comment]
@obfuscurity I thought about that, but it doesn't make any sense (I believe that you are referring to the number of rows returned by "production deploy", correct?)  Specifically the rows that match both "production" AND "deploy" will be strictly smaller than the number of rows that match "production" OR "deploy".  As such, if "production" alone works (which it does), then so should "production" AND "deploy".  It doesn't make any sense for the larger set ("production" alone) to work and then the more specific set ("production" AND "deploy") to fail.

**Comment by logikal** [comment]
I don't think this was your issue, since you could replicate with a regular query to your graphite server, but searching for my issue led me here. This is for those internet friends:

We ran into this issue, but it turned out someone had enabled the "Proxy" setting for the graphite datasource in our grafana settings, unintentionally. We had not configured graphite to allow requests like that, which resulted in the 500s we saw. Setting it back to "direct" resolved the issue for us.

**Comment by lilydjwg** [comment]
I've found in my case, django-tagging is generating SQLs like this:

```
SELECT "events_event"."id", "events_event"."when", "events_event"."what", "events_event"."data", "events_event"."tags" FROM "events_event" WHERE ("events_event"."id" IN (%s, ....
```

There are a lot of `%s` there, no wonder it hits SQLite's limit. I don't understand why it can't / doesn't use a list instead. It seems it's a bug in django-tagging (0.4.1) however.
