### ISSUE TITLE
Graphite-web's local_settings.py should live outside of the installed source

### ISSUE THREAD

**Issue by tomprince** [graphite-project/graphite-web#114]
local_settings.py should be locatable outside of the installed python source which could be read-only or within a virtualenv. /opt/graphite/conf would be the most obvious default. Additionally, it should be named less generically (graphite_settings.py? graphite.py? graphite_webapp.py?)
## Original description
# There should be a way to run graphite-web from a read-only directory.

`graphite.settings` looks for `graphite.local_settings` explicitly, so it is impossible to configure without hacking `local_settings.py` into the python path somehow.

**Comment by obfuscurity** [comment]
Outside of this issue, I've never heard anyone suggest this or complain about the current approach. Can you elaborate on why this is a problem?
