### ISSUE TITLE
Graphite derivative & scale

### ISSUE THREAD

**Issue by Sineos** [graphite-project/graphite-web#1143]
I have learned that I have to use the scale function with respect to the sample-rate / time-intervals of a given series to produce correct results from the derivative function.
IMHO this is creating a lot of pitfalls especially if you data source is not sending in absolute homogeneous intervals.
May I suggest improving this essential function to be self-learning the calculation intervals.

**Comment by obfuscurity** [comment]
`scaleToSeconds()` doesn't work for you?

**Comment by Sineos** [comment]
Works, thnx for the pointer
