### ISSUE TITLE
Incorrect CactiStyle display when using with Stacked

### ISSUE THREAD

**Issue by manasg** [graphite-project/graphite-web#115]
I am trying to plot the following scenario - 

**Metrics**
Server1 - Requests Served
Server2 - Requests Served
Total (Server1 + Server2) - Requests Served

**Desired Plot**
Server1 and Server2 are stacked.
Total is displayed as a line.
Legend - CactiStyle for all three metrics

I use the stacked function to stack individual servers. I notice that CactiStyle legend for the second server displays incorrect stats. It shows the stats as they are on Y-Axis (which is higher because of the stack)

/render?
target=cactiStyle(alias(stacked(derivative(serv1.requests)),'server1'))
&target=cactiStyle(alias(stacked(derivative(serv2.requests)),'server2'))
&target=cactiStyle(alias(derivative(sumSeries(*.requests)),'total'))

This may be an issue with using CactiStyle with the stacked function.

Or maybe I am just taking the wrong approach for the plot.

I can email the image of the graph if required.

**Comment by obfuscurity** [comment]
Confirmed this is still an issue in master.

<img width="585" alt="screen shot 2016-08-23 at 8 41 21 pm" src="https://cloud.githubusercontent.com/assets/494338/17914658/00ea0a88-6972-11e6-9dca-9bb8f1cc9b59.png">
<img width="586" alt="screen shot 2016-08-23 at 8 41 28 pm" src="https://cloud.githubusercontent.com/assets/494338/17914664/06cf020a-6972-11e6-891b-77873c9c5735.png">
