### ISSUE TITLE
graphite-web to query ONLY CLUSTER_SERVERS

### ISSUE THREAD

**Issue by LukaszStrzelecki** [graphite-project/graphite-web#1168]
Hi,

Is it possible to have a graphite-web NOT trying to access local carbon-cache? Just remote web-apps?
Setting the CARBONLINK_HOSTS to empty array, None etc does not seem to help (it generates exceptions in lots of places)
If I put fake ip:port (that I don't listen to) then graphite-web generates a lot of errors in exception.log (which is less than ideal)

Why I need that:

We have a setup with 4 separate instances of:
`relay -> (4 x carbon cache) <- web-app`

And we'd like to have one UBER web-app (deployed on small VM) that will poll all 4 web-apps (to it will just have a CLUSTER_SERVERS poiting to that 4 webapps).

I am not able to configure the UBER web-app to NOT try to poke local carbon-cache.

Thanks for help

**Comment by deniszh** [comment]
Hi Lukasz,

In same situation I configured single carbon instance on rendering server just for that purpose.

**Comment by LukaszStrzelecki** [comment]
That is what I did as well :).

The problem I have with such approach is that it one of the 4cache black box lives on the same physical box as the UBER webapp.
I had to disable change from https://github.com/graphite-project/graphite-web/issues/377 to actually let is connect to different web-app living on the same host.

For some reasons uber-webapp tries to use that tiny additional carbon-cache to read meta data about metrics queried from web-app that live on the same box.

Lets say that my box is called BOX1.

It has `relay -> [4x cache] <- web-app` running.
It has uber web-app running that queries BOX1, BOX2, BOX3, BOX4 via `CLUSTER_SERVERS` and its local fake small carbon cache (for the sake of not erroring constantly).

The gw.service.BOX1.limiting.VDC2.WDC1.poll.max lives on BOX1 in one of the 4 carbon caches. It reaches my uber web-app by CLUSTER_SERVERS. Then uber-webapp tries to read some metadata about that metric using that small carbon cache (and its storege dir) 

Any hints about that?


```
Tue Feb 24 18:02:47 2015 :: Exception Caught
Traceback (most recent call last):
  File "/mnt/disk/home/graphiteweb/graphite-web-1.2.2/graphite/webapp/graphite/render/datalib.py", line 232, in fetchData
    minStep = CarbonLink.get_metadata(dbFile.real_metric, 'minStep')
  File "/mnt/disk/home/graphiteweb/graphite-web-1.2.2/graphite/webapp/graphite/render/datalib.py", line 146, in get_metadata
    results = self.send_request(request)
  File "/mnt/disk/home/graphiteweb/graphite-web-1.2.2/graphite/webapp/graphite/render/datalib.py", line 173, in send_request
    raise CarbonLinkRequestError(result['error'])
CarbonLinkRequestError: Traceback (most recent call last):
  File "/home/graphiteweb/current/graphite/lib/carbon/management.py", line 15, in getMetadata
    archives = whisper.info(wsp_path)['archives']
  File "/home/graphiteweb/current/graphite/lib/whisper.py", line 697, in info
    fh = open(path,'rb')
IOError: [Errno 2] No such file or directory: '/home/graphiteweb/storage/whisper/gw/service/BOX1/limiting/VDC2/WDC1/poll/max.wsp'
```

**Comment by anatolijd** [comment]
what is WHISPER_DIR value for your uber graphite-web local_settings.py ?  
What is LOCAL_DATA_DIR value for carbon-cache at this instance (carbon.conf) ? 
Does directory /home/graphiteweb/storage/whisper/ exist ?

**Comment by LukaszStrzelecki** [comment]
Hi,
Actually I found the problem last night.
It was due to fix we did long time ago to workaround issue described here: https://github.com/graphite-project/graphite-web/issues/832

The initial workaround was: (We have not published it because it is probably not the way it should be fixed)

```python
--- a/src/main/graphite/webapp/graphite/render/datalib.py
+++ b/src/main/graphite/webapp/graphite/render/datalib.py
@@ -225,13 +225,21 @@ def fetchData(requestContext, pathExpr):
     store = STORE
 
   for dbFile in store.find(pathExpr):
     log.metric_access(dbFile.metric_path)
     dbResults = dbFile.fetch( timestamp(startTime), timestamp(endTime) )
+
     try:
-      cachedResults = CarbonLink.query(dbFile.real_metric)
-      results = mergeResults(dbResults, cachedResults)
+      minStep = CarbonLink.get_metadata(dbFile.real_metric, 'minStep')
+      step = dbResults[0][2]
+      if step > minStep:
+        log.cache("Step %s is larger than min step %s, not using cache" % (step, minStep))
+        results = dbResults      
+      else:
+        log.cache("Step %s is equal to min step %s, using cache" % (step, minStep))
+        cachedResults = CarbonLink.query(dbFile.real_metric)
+        results = mergeResults(dbResults, cachedResults)
     except:
       log.exception()
       results = dbResults
 
     if not results:
```

In summary, our fix did not work in distributed environment.

So we can close this issue. The conclustion is that for now you always have to have a local cache running, even if it is completely dummy one that one writes to.

Thanks!
Lukasz
