### ISSUE TITLE
Feature Request: add custom GRAPHITE_WEB_LOG_DIR for rendering/cache/info/exception logs

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/graphite-web#1179]
Hi @guys.

As explained in this question 

https://answers.launchpad.net/graphite/+question/263195

There is no simple way to change de default log location to a custom directory.

So could be good to add a new GRAPHITE_WEB_LOG_DIR setting in the local_settings.py

**Comment by steve-dave** [comment]
Have I misunderstood your question?  I think the config option you are asking for already exists as LOG_DIR...

https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/local_settings.py.example#L86
https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/local_settings.py.example#L78

**Comment by toni-moreno** [comment]
Yes !!! 

Sorry @steve-dave I didn't see before. 

I've changed and now it is logging in the correct place.

**Comment by steve-dave** [comment]
:+1:
