### ISSUE TITLE
Graphite Datapoint value resets to zero

### ISSUE THREAD

**Issue by vikas22** [graphite-project/graphite-web#1190]
Hi, datapoint value resets to zero after some time.
initially
[0, 1426770240] 
[449.968673, 1426770300] 
later
[0, 1426770240] 
[0, 1426770300] 
[0, 1426770360]

retentions are 10s:7d,5m:30d,15m:5y

Please Help me I'm new to this. tried searching it but didn't find any helpful resource.

**Comment by obfuscurity** [comment]
Those timestamps are 60s apart. Your schema doesn't specify any retentions with that precision. That wouldn't explain why your values are changing, but it feels like you're leaving out some important details (or you don't know your own system).

The likeliest answer is that something is overwriting your data with zeroes. I can't tell anything else based on the information you've provided.

**Comment by vikas22** [comment]
Hi, 
  As you said  I'm new to the system, and the person who configured it is also not available right now, 
 I sent some 40000000 requests, in this the data seems to be fine but if i send some 1000 requests the same problem what i mentioned above is happening. So can you please let me know what all the configuration files required for you to cross check. (I think its expecting continuous data )

**Comment by obfuscurity** [comment]
Closing. The most likely conclusion (since no one else has reported this) is that the data was being overwritten. No additional information has been provided.
