### ISSUE TITLE
Font size is huge

### ISSUE THREAD

**Issue by atroschinetz-rmn** [graphite-project/graphite-web#1191]
Operating System: OS X 10.10.2

Here's what I did to install/configure graphite et al.

```
$ sudo pip install Django==1.5
[...]
Successfully installed Django
Cleaning up...
$ sudo pip install django-tagging
[...]
Successfully installed django-tagging
Cleaning up...
$ sudo pip install whisper
[...]
Successfully installed whisper
Cleaning up...
$ sudo pip install carbon
[...]
Successfully installed carbon
Cleaning up...
$ sudo pip install graphite-web
[...]
Successfully installed graphite-web
Cleaning up...
$ sudo pip install Twisted==11.1.0
[...]
Successfully installed Twisted
Cleaning up...
$ sudo chown -R $(whoami):staff /opt/graphite
$ cp /opt/graphite/conf/carbon.conf{.example,}
$ cp /opt/graphite/conf/storage-schemas.conf{.example,}
$ cd /opt/graphite/webapp/graphite
$ python manage.py syncdb
$ cp /opt/graphite/webapp/graphite/local_settings.py{.example,}
$ perl -pi -e 's/#DEBUG/DEBUG/g' /opt/graphite/webapp/graphite/local_settings.py
$ /opt/graphite/bin/carbon-cache.py start
$ cd /opt/graphite
$ ./bin/run-graphite-devel-server.py --port 8081 --libs=`pwd`/webapp/ /opt/graphite/
Adding /opt/graphite/webapp/ to your PYTHONPATH
Running Graphite from /opt/graphite/ under django development server

/usr/local/bin/django-admin.py runserver --pythonpath /opt/graphite/webapp --settings graphite.settings 0.0.0.0:8081
/opt/graphite/webapp/graphite/settings.py:244: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
/opt/graphite/webapp/graphite/settings.py:244: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
Validating models...

0 errors found
March 20, 2015 - 15:26:28
Django version 1.5, using settings 'graphite.settings'
Development server is running at http://0.0.0.0:8081/
Quit the server with CONTROL-C.
/Library/Python/2.7/site-packages/django/conf/urls/defaults.py:3: DeprecationWarning: django.conf.urls.defaults is deprecated; use django.conf.urls instead
  DeprecationWarning)

[20/Mar/2015 15:30:33] "GET / HTTP/1.1" 200 542
[20/Mar/2015 15:30:33] "GET /browser/header/ HTTP/1.1" 200 1018
[20/Mar/2015 15:30:33] "GET /composer/? HTTP/1.1" 200 1631
No handlers could be found for logger "cache"
[20/Mar/2015 15:30:34] "GET /render/?width=588&height=311&_salt=1426865433.945 HTTP/1.1" 200 3655
```

Then going to `127.0.0.1:8081` in my browser gives me this:

![screen shot 2015-03-20 at 10 30 04 am](https://cloud.githubusercontent.com/assets/7365313/6754722/54523d98-ceec-11e4-8ed2-f45d0a540669.png)

The red blob in the middle there is the word "No Data" in red, but the font size is huge and the text overlaps itself. No idea what's going on here. Are there any other logs I can provide to help diagnose this issue?

**Comment by clhynfield** [comment]
Exact same symptoms here, on OS X 10.10.2, having followed nearly the same installation and configuration procedures. I didn't specify a version for Django, taking the default 1.7.7 version. I also had to `brew install cairo py2cairo` as documented in gist [relaxdiego/graphite.md](https://gist.github.com/relaxdiego/7539911), as graphs weren't rendering initially. 

![screen shot 2015-03-20 at 11 33 34 pm](https://cloud.githubusercontent.com/assets/148868/6763594/92fc6074-cf59-11e4-9c0f-ab3f0ee45f14.png)

**Comment by tonyghita** [comment]
I have the same issue, with the same environment. Any updates @atroschinetz-rmn @clhynfield ?

**Comment by calebmadrigal** [comment]
Same problem here. I followed these setup directions: <https://gist.github.com/relaxdiego/7539911>

**Comment by tonyghita** [comment]
FWIW that's also what I did @calebmadrigal

**Comment by PanzaSancho** [comment]
same problem

**Comment by ryanricard** [comment]
A solution in the discussion thread at the bottom of the gist (https://gist.github.com/relaxdiego/7539911) resolved this issue for me. Apparently the most recent version of Cairo has a bug.

If you are using Homebrew, unlink or uninstall Cairo. Then install an older version. Cairo 1.12.6 is working for me on Yosemite. 

```shell
// unlink current installation of Cairo
$ brew unlink cairo

// install Cairo 1.12.16
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew/26d5775494b3535820c48442c23af44f72974880/Library/Formula/cairo.rb
```

**Comment by wiml** [comment]
I had the same issue (using the cairocffi bindings on OSX 10.9.5) and ryanricard's fix worked perfectly for me. But, does anyone have a link to the bug that this is working around? I'd like to keep an eye on that so I can upgrade cairo once it's fixed.
