### ISSUE TITLE
holtWintersAberration: list index out of range

### ISSUE THREAD

**Issue by resnostyle** [graphite-project/graphite-web#1198]
The holtWintersAberration function isnt displaying anything on graphite-web. The logs display the following stack trace. 
This is also using a version .10.x using a alternate storage method, cyanite with cassandra backend.

Here's the call I'm making for example: curl 'http://localhost/render/?from=-7days&until=-1minutes&uniq=1426001228492&format=json&target=holtWintersAberration(statsd.processing_time)'

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 111, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 9, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 23, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 38, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 23, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 38, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 23, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 42, in evaluateTokens
    return func(requestContext, *args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 2293, in holtWintersAberration
    lowerBand = confidenceBands[0]
IndexError: list index out of range
```

**Comment by brutasse** [comment]
@resnostyle can you provide the exact URL for this query?

**Comment by qijianbo** [comment]
http://graphite.readthedocs.org/en/latest/you can have a try?






原始邮件
发件人:Bruno Reniénotifications@github.com
收件人:graphite-project/graphite-webgraphite-web@noreply.github.com
发送时间:2015年3月24日(周二) 22:30
主题:Re: [graphite-web] holtWintersAberration: list index out of range(#1198)


@resnostyle can you provide the exact URL for this query?

**Comment by qijianbo** [comment]
http://graphite.readthedocs.org/en/latest/

**Comment by resnostyle** [comment]
@brutasse curl 'http://localhost/render/?from=-7days&until=-1minutes&uniq=1426001228492&format=json&target=holtWintersAberration(statsd.processing_time)'

**Comment by mkrb** [comment]
Think graphite needs full filled and aligned time series for this. Modifying cyanite.py (graphite-cyanite) as follows could be helpful (fetch_multi is another beast):

     def fetch(self, start_time, end_time):
        data = requests.get(urls.metrics, params={'path': self.path,
                                                  'from': start_time,
                                                  'to': end_time}).json()

        if len(data['series']) == 0 or 'error' in data:
            data['from'] = end_time / data['step'] * data['step']
            data['to'] = data['from']
            data['series'][self.path] = []

        while (data['from'] - data['step']) >= start_time :
            data['from'] = data['from'] - data['step']
            data['series'].get(self.path, []).insert(0, None)

        while (data['to'] + data['step']) <= end_time :
            data['to'] = data['to'] + data['step']
            data['series'].get(self.path, []).append(None)

        time_info = data['from'], data['to'], data['step']
        return time_info, data['series'].get(self.path, [])
