### ISSUE TITLE
Clarifications on Cluster documentation and no-data errors

### ISSUE THREAD

**Issue by coredump** [graphite-project/graphite-web#1200]
So I am dealing with clustering graphite for a week now. It mostly works, but I would like to check some stuff that between blog posts/documentation/issues in GH is a little confusing.
This is my setup at the moment, using graphite `pip` installed from master tarball as of last week:

![current situation](https://i.imgur.com/cbtjHtG.png)

The frontend server has server 1 and 2 on `DESTINATIONS` and using consistent hashing. There's also a nginx that only load balances requests to port 80 to the graphite web interfaces on server 1 and server 2.

Servers 1 and 2 are configured the same way: 1 carbon relay also using consistent-hashing to 3 carbon caches running on different ports and `127.0.0.1`. 

The web apps on servers 1 and 2 are configured with `DATA_DIRS` pointing to the whisper and rrd paths (RRDs are not used, the path is just there). They also have `CLUSTER_SERVERS` set to include server 1 and 2,  and `CARBONLINK_HOSTS` set to the localhost carbon caches, matching the order on the relay `DESTINATIONS`. Each server also has a `MEMCACHE_HOSTS` configured with only a localhost memcached server.

Now the main problem I have is "no data" errors on both graphite-web dashboards/graphs, Grafana graphs and on nagios tests using `check_graphite`. Usually they only stand for a few seconds, where no data is sent (on json output, that means `[]`), and they the data appears again, with no interruption or anything, the data is there, it's just not served.

Those are the things I have tried, based on blog posts, documentation and  github issues:
- First setup used a graphite-web with `CLUSTER_SERVERS` configured to point to all 3 web apps (server 1, server 2 and frontend). I got a lot more missing data and weird errors. Also `DATA_DIRS` and `CARBONLINK_HOSTS` made no sense in this context for the frontend web app, but graphite would not start without them configured. Read somewhere that you have to get a carbon cache instance on the frontend that receives no data and add it to `CARBONLINK_HOSTS`, but that sounded a little crazy.
- Tried many `CLUSTER_SERVERS` options, but between blog posts, issues and documentation I could not ever figure out if you are supposed to have all servers on this list, or all servers except for local host, or not to include the frontend web app.
- Gave up on the frontend web app, started using nginx as a load balancer between server 1 and server 2 webapps. This worked a little better. `CLUSTER_SERVERS` confusion still though. Tried to have only 'the other' server on each `CLUSTER_SERVERS`. ATM I have both servers there.
- `MEMCACHE_HOSTS` is another point of confusion. In #1102 @obfuscurity mentions not using memcached on backend hosts, what I tried and generated horrible load on the servers. Using the same list of memcache hosts on both servers also didn't help with the no-data issue. ATM I am running each web app with a `127.0.0.1` memcached.

So my question is really about clarifications and how to actually configure the cluster on the _RIGHT WAY_, specially if I should continue doing the nginx load balancing or to go back to a frontend web app, and in this case, what are the correct values for `CLUSTER_SERVERS`, `DATA_DIRS` and `CARBONLINK_HOSTS`. If someone has a working cluster and want to share some config files, I would be grateful.

**Comment by pizjix** [comment]
Maybe these will help you if it's still relevant:
http://www.slideshare.net/AnatolijDobrosynets/graphite-cluster-setup-blueprint
https://answers.launchpad.net/graphite/+question/228472

**Comment by coredump** [comment]
Yes this still a problem. I will try some more fiddling this week.

**Comment by gwaldo** [comment]
Apologies for the late reply.  There is a lot of documentation work to be done, and I simply have not had time to contribute much lately.

There are a few excellent blog posts out there (sadly more of lesser quality) that I use as reference for whisper-based graphite clustering:

* [BitProphet's "Clustering Graphite"](http://bitprophet.org/blog/2013/03/07/graphite/)
* [Richard Crowley's "Federated Graphite"](http://rcrowley.org/articles/federated-graphite.html)
* [The Architecture of Clustering Graphite](https://grey-boundary.io/the-architecture-of-clustering-graphite/)

**Comment by manivannan-g** [comment]
@coredump do you have any sample for the cluster configurations of carbon.conf, relay-rules.conf, local-settings.py. I've tried creating a two node graphite cluster but not successful. Here's my config looks like:

I have two machines dedicated for graphite 10.0.1.52 and 10.0.1.27 in this I wanted to use 52 as the main host.

**local_settings.py**
```
CLUSTER_SERVERS = ["10.0.1.52:80", "10.0.1.27:80"]
CARBONLINK_HOSTS = ["10.0.1.52:7002:a", "10.0.1.27:7102:b"]
```

**carbon.conf**
```
[cache]
GRAPHITE_STORAGE_DIR = /opt/graphite/storage/
LOCAL_DATA_DIR = /opt/graphite/storage/whisper/
LOG_DIR        = /var/log/carbon/
ENABLE_LOGROTATION = True
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 1000
MAX_CREATES_PER_MINUTE = 5000

LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2003

ENABLE_UDP_LISTENER = False
UDP_RECEIVER_INTERFACE = 0.0.0.0
UDP_RECEIVER_PORT = 2003

PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2004

USE_INSECURE_UNPICKLER = False
CACHE_QUERY_INTERFACE = 0.0.0.0
CACHE_QUERY_PORT = 7002
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CACHE_HITS = False
CACHE_WRITE_STRATEGY = sorted
WHISPER_AUTOFLUSH = False


[relay]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2013
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2014

RELAY_METHOD = consistent-hashing
REPLICATION_FACTOR = 2

DESTINATIONS = 10.0.1.52:2004:a, 10.0.1.27:2004:b

MAX_QUEUE_SIZE = 10000
MAX_DATAPOINTS_PER_MESSAGE = 1000
QUEUE_LOW_WATERMARK_PCT = 0.8
TIME_TO_DEFER_SENDING = 0.0001
USE_FLOW_CONTROL = True
USE_RATIO_RESET=False
MIN_RESET_STAT_FLOW=1000
MIN_RESET_RATIO=0.9
MIN_RESET_INTERVAL=121


[aggregator]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2023

PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2024
DESTINATIONS = 10.0.1.52:2004:a, 10.0.1.27:2004:b

REPLICATION_FACTOR = 1
MAX_QUEUE_SIZE = 10000
USE_FLOW_CONTROL = True
MAX_DATAPOINTS_PER_MESSAGE = 5000
MAX_AGGREGATION_INTERVALS = 5
```

**relay-rules.con**
```
[default]
default = true
destinations = 10.0.1.52:2004:a, 10.0.1.27:2004

```

Now when I try to test by creating a metric in 10.0.1.52, the same is not replicating in 10.0.1.27.

As a newbie tried and couldn't get through, requesting you to help me :-)

**Comment by ashokrajar** [comment]
From your config relay is running on port 2013. But you are sending the metrics to port 2003 directly to the carbon cache process which will not replicate and store locally.

Also since you are running just one carbon-cache per node you don't have to specify :a or :b

**Comment by manivannan-g** [comment]
@ashokrajar thanks for rightly pointing :-) `echo "test.metric.a.count 25 1465480800" | nc 10.0.1.52 2013` is working very well !
