### ISSUE TITLE
0.9.13 release date (or 0.10.x will get released sooner)?

### ISSUE THREAD

**Issue by bydga** [graphite-project/graphite-web#1202]
Hi, is there any chance a 0.9.13 version will get "officially" released - not only the pre-version? Last "stable" version 0.9.12 is year and a half old.

Or is your plan to release 0.10.x and stop working on 0.9.x branch?

**Comment by obfuscurity** [comment]
I would love to see 0.9.13 out ASAP but I've personally been overwhelmed with other work and projects. Hoping someone else will step up and help bring us to the finish line.

Related: https://github.com/graphite-project/graphite-web/issues/677
