### ISSUE TITLE
movingAverage broken for first N data points when using wildcards

### ISSUE THREAD

**Issue by seven1m** [graphite-project/graphite-web#121]
If you use `movingAverage` with a wildcard, e.g. `movingAverage(web.*.html,20)`, the first N (20) data points are plotted incorrectly.

Here is an example without movingAverage:

![regular plot](http://i.imgur.com/0u47L.png)

This is what the graph looks like using movingAverage:

![regular plot](http://i.imgur.com/D1Gqh.png)

As you can see, the first 20 data points are somehow averaged _together_.

16a6868444c6100bd2c780613959e4ca48e5e97c seems to be the culprit. If I roll back to the commit just before, this bug goes away, and the first 20 data points are null.

**Comment by Krinkle** [comment]
When will this be released? I'm still experiencing this bug quite often. It also affects Grafana customers.

It's especially odd if the point to which all data points were aggregated is later excluded through `exclude()` or `highestCurrent()`, in which case there will be a single data point way off the chart (virtually speaking), causing making the resulting graph to be far less useful as it may force the scale to be expanded.

**Comment by obfuscurity** [comment]
@Krinkle When will **what** be released? What version are you running? Does it include the [aforementioned fix](https://github.com/graphite-project/graphite-web/commit/7f649535d02c21a527e8aa555876999d82d4d94e)? I encourage anyone experiencing problems with 0.9.12 or older to try installing from HEAD of the [0.9.x](https://github.com/graphite-project/graphite-web/tree/0.9.x) branch.

**Comment by Krinkle** [comment]
@obfuscurity What => The bug fix for movingAverage discussed in this issue.

Wikimedia upgraded to graphite-web 0.9.13+debian-1, but this bug still exists in that version.

See also <https://phabricator.wikimedia.org/T104536#1448881>.

**Comment by obfuscurity** [comment]
Unless you can verify that the 0.9.x branch (which the next release will be tagged from) does not contain a working fix, I'd suggest opening a bug report with the Debian Graphite team. It's unclear to me what their 0.9.13+debian-1 package represents, particularly since they're [actively removing upstream patches](https://launchpad.net/ubuntu/+source/graphite-web/0.9.13+debian-1).

**Comment by brutasse** [comment]
@obfuscurity which upstream patches are being removed?

**Comment by obfuscurity** [comment]
I don't have specific links, but from their changelog:

```
* patches removed, included by upstream:
    - add_maximum_returned_datapoints.patch
    - remove_graphlot.patch
    - django17.patch
    - django1.6_compatibility.patch
```

**Comment by brutasse** [comment]
I read it the same way as you did but it is only poor wording for "patches made redundant by upstream changes". Apparently these patches were applied to their 0.9.12 package and are not required anymore with 0.9.13.

Current list of patches: https://sources.debian.net/src/graphite-web/0.9.13%2Bdebian-1/debian/patches/
Patches applied to 0.9.12: https://sources.debian.net/src/graphite-web/0.9.12%2Bdebian-6/debian/patches/
