### ISSUE TITLE
event get_data return all events when tags are combined from not existing and existing ones.

### ISSUE THREAD

**Issue by nihn** [graphite-project/graphite-web#1210]
For example when I make query like:
`/events/get_data?from=-7d&until=now&tags=foo` i got nothing, but:
`/events/get_data?from=-7d&until=now&tags=existing_tag%20foo` returns multiple results.
I think that expected behaviour would be also returning nothing.

**Comment by scosist** [comment]
This sounds like the same problem when using existing and non-existing tags with the `events` [function](https://graphite.readthedocs.io/en/0.9.10/functions.html#graphite.render.functions.events) as described here: https://github.com/grafana/grafana/issues/1474#issuecomment-136417967

**Comment by scosist** [comment]
Perhaps we could take a page from [odoo domain filters](http://stackoverflow.com/questions/18998921/understanding-openerp-domain-filter) for added flexibility in tag matching events?

**Comment by obfuscurity** [comment]
I've dug into django-tagging to better understand what's going on here. Sadly, it looks like both [`with_any()`](https://github.com/Fantomas42/django-tagging/blob/develop/tagging/managers.py#L46) and [`with_all()`](https://github.com/Fantomas42/django-tagging/blob/develop/tagging/managers.py#L40) (what graphite-web uses) behave similarly, returning only unions. What we really need is something that returns an intersection, e.g. [`get_intersection_by_model()`](http://django-tagging.readthedocs.io/en/develop/#id3). We may have to monkey patch django-tagging to make this work intuitively.

**Comment by obfuscurity** [comment]
From the freshly updated [events](http://graphite.readthedocs.io/en/latest/events.html#querying-events) doc:

'The `set` parameter accepts an optional `union` or `intersection` argument to determine the behavior for filtering sets of tags (i.e. inclusive or exclusive). By default, Graphite uses a “lazy union” that will return any matching events for a given tag in a list of tags. This behavior is not intuitive and will therefore be deprecated in a future release.'

**Comment by elsmorian** [comment]
How can you add the set argument within graphite-web dashboards? Have tried adding `drawAsInfinite(events('tag1','2',set='union'))` and other combination but I'm afraid my understanding of the target functions etc is a bit limited!
