### ISSUE TITLE
django authorization required when posting/reading events?

### ISSUE THREAD

**Issue by dnotivol** [graphite-project/graphite-web#1215]
Hello, 

I'm trying to post and read events in graphite, but I'm having some problems to do it from the CLI (the idea is to do it from a script).

From the web http://localhost:8000/events/, I can read and post the events, but it requires me to log in the admin interface (the django administration). I guess this can be the reason why I can not make it works with curl.

Is there a way to disable this django authentication? Or is simply I am making anything wrong...
I didn't find much information about it in the docs, and I have zero knowledge of django.

Below you can find what I get posting and getting the events from curl.

Thanks a lot in advance.

    # curl -X GET http://localhost:8000/events/
    <html>
      <head>
        <title>Events</title>
        <link rel="stylesheet" type="text/css" href="../content/css/table.css" />
        <style type="text/css">
        body {
            font-family: sans-serif;
            font-size: 16px;
            margin: 50px;
            max-width: 1200px;
        }
        </style>
    
    
        </head>
        <body>
            <div id="title" style="text-align:center">
                <h1>graphite events</h1>
            </div>
            <div class="graphite">
                <div id="main" >
                  
                    <table class="styledtable" width=100%>
                      <tr><th>when</th><th>what</th><th>tags</th></tr>
                      
                          <tr>
                              <td>10:00:00 Fri 24 Apr 2015</td>
                              <td><a href="/events/2/">Event - backup</a></td>
                              <td>backup</td>
                          </tr>
                      
                  
                  </table>
                </div>
            </div>
        </body>
    </html>

    # curl -X POST "http://localhost:8000/events" -d '{"what": "Event - backup", "tags": "backup", "when":"1429866988"}'
    
    
    
    
    <html>
      <head>
        <title>Graphite Browser</title>
      </head>
            
    
    <frameset rows="60,*" frameborder="1" border="1">
      <frame src="/browser/header/" name="Header" id='header' scrolling="no" noresize="true" />
      
        <frame src="/composer/?" name="content" id="composerFrame"/>
      
      </frameset>
    </html>

**Comment by obfuscurity** [comment]
You shouldn't need to authenticate to view events, only to manage them in the /admin/ section. And your POST should work as expected, not return HTML. It sounds like *maybe* your web configuration (Apache?) is messed up.

Either way, it would help if you provided more information about your system (distro, release), which version of Graphite you're running, and how you installed it. Oh, and your actual web config.

To contrast, these activities work as expected for me with a fresh Synthesize install. You can see the configurations here:

**Comment by dnotivol** [comment]
Thanks a lot for your assistance. I already have it working. I was tweaking some Apache configuration to leave it simpler and easier to debug. 
But at last, I think the error was the silliest on earth... I forgot the trailing slash in the URI when posting the event. When using http://localhost:8000/events/ ending in a slash, everything works fine.

Sorry to disturb you with such a silly thing (I don't know how many times I checked everything before posting, and I didn't see it...).
