### ISSUE TITLE
Cannot post events to Graphite WebApp

### ISSUE THREAD

**Issue by jiminoc** [graphite-project/graphite-web#1216]
Trying to post a simple example event into graphite-web after a new install. I can manually add events through the UI just fine and I can see them in my database, however trying to post to the /events handler seems to fail. 

Using the debian package:
ii  graphite-web                     0.9.12+debian-3

Example of webui showing events after using the GUI admin tool
https://www.dropbox.com/s/j00s1mu9yv3tfz3/Screenshot%202015-04-27%2009.43.06.png?dl=0

jim@localhost: /Users
➺ curl -X POST "http://10.0.0.1/events/" -d '{"what": "Event - deploy", "tags": "deploy", "data": "deploy of master branch happened at Fri Jan  3 22:34:41 UTC 2014"}'
<body style="background-color: #666666; color: black;">
<center>
<h2 style='font-family: "Arial"'>
<p>Graphite encountered an unexpected error while handling your request.</p>
<p>Please contact your site administrator if the problem persists.</p>
</h2>
<br/>
<div style="width: 50%; text-align: center; font-family: monospace; background-color: black; font-weight: bold; color: #ff4422;">

</div>

<div style="width: 70%; text-align: left; background-color: black; color: #44ff22; border: thin solid gray;">
<pre>
Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/dist-packages/django/core/handlers/base.py&quot;, line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File &quot;/usr/lib/python2.7/dist-packages/graphite/events/views.py&quot;, line 33, in view_events
    return post_event(request)
  File &quot;/usr/lib/python2.7/dist-packages/graphite/events/views.py&quot;, line 45, in post_event
    event = json.loads(request.raw_post_data)
AttributeError: &#39;WSGIRequest&#39; object has no attribute &#39;raw_post_data&#39;

</pre>
</div>

</center>

**Comment by obfuscurity** [comment]
Based on [this](http://stackoverflow.com/a/22368223/2275058) it looks like you're running Django > 1.3. The method `raw_post_data` was changed to `body` in Django 1.4. You can upgrade your Graphite to `0.9.13rc1`, although I suspect it'll be easier for you to just downgrade Django.

**Comment by aaronrl** [comment]
I had installed Graphite from instructions on Digital Ocean's Community Tutorials (https://www.digitalocean.com/community/tutorials/how-to-install-and-use-graphite-on-an-ubuntu-14-04-server) for Ubuntu 14.04 and ran into this issue also.  The graphite-web package that it advises you to install also installs Django 1.6.1.  I decided not to try to yank out that package and install Django with pip as I didn't feel comfortable creating a potentially hellish dependency nightmare for myself.

Instead, I opted to edit the file that the traceback mentions ("/usr/lib/python2.7/dist-packages/graphite/events/views.py", line 45) to the following (changed 'raw_post_data' to 'body'):

```python
def post_event(request):
    if request.method == 'POST':
        event = json.loads(request.body)
        assert isinstance(event, dict)

        values = {}
        values["what"] = event["what"]
        values["tags"] = event.get("tags", None)
        values["when"] = datetime.datetime.fromtimestamp(
            event.get("when", time.time()))
        if "data" in event:
            values["data"] = event["data"]

        e = models.Event(**values)
        e.save()

        return HttpResponse(status=200)
    else:
        return HttpResponse(status=405)
```

I deleted the views.pyc file and restarted Apache and everything was good to go!  Hopefully that helps as a workaround.
