### ISSUE TITLE
graph is inconsistent in GUI

### ISSUE THREAD

**Issue by Mano-Sundaram** [graphite-project/graphite-web#1226]
I have configured statsd to send datat to graphite for testing my application performance. When I send data to graphite, for e.g., 100, the graph shows only 40 or 50 etc., They are highly inconsistent. Sometimes, the graph disappears on refreshing it. What could be the cause of this issue?

**Comment by obfuscurity** [comment]
There could be any number of things causing this, including a misunderstanding of the storage schema. Please include more details if you're still experiencing an issue, including sample graph output, the query you're running, and the retention policy for the affected series.

Closing this out for now but will reopen if you're still having this issue.
