### ISSUE TITLE
svg rendering broken on 0.9.13 (xml tag mismatch)

### ISSUE THREAD

**Issue by grobian** [graphite-project/graphite-web#1227]
using:

graphite-web-0.9.13
pycairo-1.10.0
cairo-1.12.18 or cairo-1.12.14
(This is on CentOS and Gentoo)

svg rendering gives me:
```XML Parsing Error: mismatched tag. Expected: </svg>.
</g><script>
--^```

I don't fully comprehend what the code is doing, but this dirty hack seems to fix it for me:
```
--- graphite-web/webapp/graphite/render/glyph.py
+++ graphite-web/webapp/graphite/render/glyph.py
@@ -497,7 +497,7 @@
       svgData = re.sub(r'<path.+?d="M -88 -88 (.+?)"/>', onHeaderPath, svgData)
 
       # Replace the first </g><g> with <g>, and close out the last </g> at the end
-      svgData = svgData.replace('</g><g data-header','<g data-header',1) + "</g>"
+      svgData = svgData.replace('</g><g data-header','<g data-header',1)
       svgData = svgData.replace(' data-header="true"','')
 
```

**Comment by aniketbhatnagar** [comment]
+1

I ran into this issue as well

**Comment by deejay1** [comment]
Same here :/

**Comment by obfuscurity** [comment]
Agreed, this appears to fix the issue. I suspect the reason for this hack was fixed upstream and is no longer necessary (part of it, anyways).
