### ISSUE TITLE
not able to retrieve exact match

### ISSUE THREAD

**Issue by gsaray101** [graphite-project/graphite-web#1229]
I am using graphite version: 0.10.0-alpha, when select servers j2kweb01 and j2kweb02, it also picks j2kweb011, j2kweb0111 etc.

Is this a bug or how could I search for the exact match?

**Comment by obfuscurity** [comment]
I proposed an answer to your(?) similar question over on Launchpad.  https://answers.launchpad.net/graphite/+question/267173

**Comment by gsaray101** [comment]
Hi Jason,

When are you going release the latest version of graphite web?
