### ISSUE TITLE
Is there way to remove metrics over api?

### ISSUE THREAD

**Issue by adubkov** [graphite-project/graphite-web#1238]
We have distributed graphite cluster, and tons of test boxes, and I trying to figure out how to make cleanup destroyed boxes from graphite. 
Is there way to remove metrics from whisper over graphite-web api?

**Comment by steve-dave** [comment]
@blacked check out https://github.com/Kixeye/graphite-web/tree/0.9.x-deletemetrics if you're running 0.9.x... Not sure if it's still a clean merge but pretty sure it was working just not QA'd.
