### ISSUE TITLE
required Twisted version different between graphite-web and carbon 

### ISSUE THREAD

**Issue by nixon** [graphite-project/graphite-web#1242]
The requirements.txt file for graphite-web has:

```
Twisted==11.1.0
```

but the one for carbon has:

```
Twisted>=13.2.0
```

A similar discrepancy was reported in #35.

**Comment by brutasse** [comment]
Graphite-web doesn't even need twisted. Only carbon uses it. The entry in requirements.txt is only here for convenience for people who run carbon and graphite-web on the same machine.

I'd be in favor of letting carbon deal with the twisted dependency and remove everything twisted-related from graphite-web (requirements.txt, check-dependencies.py etc.)

**Comment by deniszh** [comment]
:+1: for that @brutasse said.

**Comment by piotr1212** [comment]
fixed  in  https://github.com/graphite-project/graphite-web/pull/1343
