### ISSUE TITLE
New release with Django 1.8 Support?

### ISSUE THREAD

**Issue by brd** [graphite-project/graphite-web#1243]

**Comment by joshmyers** [comment]
Bump. There is a recent Django vuln [here](http://www.ubuntu.com/usn/usn-2816-1/). 

Graphite-web doesn't look to currently support django 1.8.7. It would be nice if it did.

**Comment by brutasse** [comment]
I don't think graphite-web is affected by this Django vulnerability. In any case Django 1.7.11 addresses the issue and is supported. Django 1.8 is supported in master and it might just work with 0.9.x (I haven't tried).

**Comment by cclauss** [comment]
This issue can be closed?

**Comment by deniszh** [comment]
Yes, Django 1.8 - 1.11 are supported in current codebase.
