### ISSUE TITLE
Error in django-tagging version ?

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/graphite-web#1253]
When executing pip install -r requirements.txt I got this error.
```` 

Could not find a version that satisfies the requirement django-tagging==0.3.5 (from -r requirements.txt (line 5)) (from versions: 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.6, 0.4)
```
I have fixed by changing django-tagging==0.3.5 to django-tagging==0.3.6

**Comment by languitar** [comment]
Same here

**Comment by brutasse** [comment]
Yeah 0.3.5 seems to have disappeared from PyPI. We probably need 0.3.6 instead, but dependencies are looking more and more like a matrix with python/django version combinations (django-tagging 0.4 requires a more modern Django than 1.4 for instance).

**Comment by toni-moreno** [comment]
Thanks for the PR (https://github.com/graphite-project/graphite-web/pull/1256) after reinstall it seems to be working ok!
