### ISSUE TITLE
0.9.10 & django 1.6.1 problem

### ISSUE THREAD

**Issue by damian1976** [graphite-project/graphite-web#1255]
When installing graphite 0.9.10 and python-django (1.6.1) package in Ubuntu and trying to start django there's an error that needs a small fix in one of the files in import section:
from 
from django.contrib.contenttypes.fields import GenericForeignKey
to
from django.contrib.contenttypes.generic import GenericForeignKey

Otherwise it won't start.

**Comment by brutasse** [comment]
What version of django-tagging do you have? It looks like django-tagging 0.4 broke compatibility with Django<1.7. You probably need to install django-tagging 0.3.6.

**Comment by damian1976** [comment]
Yes, it may be the case. I have django-tagging==0.4

**Comment by obfuscurity** [comment]
This report is old enough that it's probably not relevant anymore but I wanted to at least comment here before closing it out. Although we'd love to support "version foo" of Django, django-tagging, etc., the reality is that this continues to get harder with each release (especially with Django). Your older version of 0.9.10 was pinned to Django 1.3. Graphite 0.9.15 (stable) is pinned to Django 1.4. Bleeding-edge Graphite `master` is pinned to 1.9. Each of these versions has their own incompatibilities which makes an already challenging situation with Python software dependencies that much more painful.

I know this doesn't help you much and I imagine you already fixed your installation months ago by downgrading your django-tagging, but I figured I'd take the opportunity to vent a bit about Django before closing this out. :wink:
