### ISSUE TITLE
Graphite web unable to import error

### ISSUE THREAD

**Issue by gsaray101** [graphite-project/graphite-web#1258]
I am receiving "import error" when I try to bring up the graphite site. Here is the whole debug output. Can somebody tell me what is wrong here, please?

ImportError at /render
No module named finder
Request Method:	GET
Request URL:	http://192.68.1.2:8090/render
Django Version:	1.6.8
Exception Type:	ImportError
Exception Value:	
No module named finder
Exception Location:	build/bdist.linux-x86_64/egg/importlib/__init__.py in import_module, line 37
Python Executable:	/usr/bin/python
Python Version:	2.6.9
Python Path:	
['/usr/local/lib64/python2.6/site-packages/setuptools-16.0-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/six-1.9.0-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/gitversion-2.1.3-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/celery-3.1.18-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/kombu-3.0.26-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/billiard-3.3.0.20-py2.6-linux-x86_64.egg',
 '/usr/local/lib64/python2.6/site-packages/ordereddict-1.1-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/importlib-1.0.3-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/amqp-1.4.6-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/anyjson-0.3.3-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/requests-2.7.0-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/txAMQP-0.6.2-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/django_cacheback-0.8-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/django_celery-3.1.16-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/pip-7.0.1-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/whitenoise-1.0.6-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages/python_memcached-1.53-py2.6.egg',
 '/usr/local/lib64/python2.6/site-packages',
 '/home/ceylanh/graphite-opentsdb-finder',
 '/usr/lib/python26.zip',
 '/usr/lib64/python2.6',
 '/usr/lib64/python2.6/plat-linux2',
 '/usr/lib64/python2.6/lib-tk',
 '/usr/lib64/python2.6/lib-old',
 '/usr/lib64/python2.6/lib-dynload',
 '/usr/lib64/python2.6/site-packages',
 '/usr/lib64/python2.6/site-packages/Numeric',
 '/usr/lib64/python2.6/site-packages/gtk-2.0',
 '/opt/graphite/webapp']
Server time:	Fri, 19 Jun 2015 13:10:08 -0400
Traceback Switch to copy-and-paste view

/usr/local/lib64/python2.6/site-packages/django/core/handlers/base.py in get_response
                resolver_match = resolver.resolve(request.path_info) ...
▶ Local vars
/usr/local/lib64/python2.6/site-packages/django/core/urlresolvers.py in resolve
            for pattern in self.url_patterns: ...
▶ Local vars
/usr/local/lib64/python2.6/site-packages/django/core/urlresolvers.py in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module) ...
▶ Local vars
/usr/local/lib64/python2.6/site-packages/django/core/urlresolvers.py in urlconf_module
            self._urlconf_module = import_module(self.urlconf_name) ...
▶ Local vars
/usr/local/lib64/python2.6/site-packages/django/utils/importlib.py in import_module
        __import__(name) ...
▶ Local vars
/opt/graphite/webapp/graphite/urls.py in <module>
    ('^render/?', include('graphite.render.urls')), ...
▶ Local vars
/usr/local/lib64/python2.6/site-packages/django/conf/urls/__init__.py in include
        urlconf_module = import_module(urlconf_module) ...
▶ Local vars
/usr/local/lib64/python2.6/site-packages/django/utils/importlib.py in import_module
        __import__(name) ...
▶ Local vars
/opt/graphite/webapp/graphite/render/urls.py in <module>
from . import views ...
▶ Local vars
/opt/graphite/webapp/graphite/render/views.py in <module>
from graphite.render.evaluator import evaluateTarget ...
▶ Local vars
/opt/graphite/webapp/graphite/render/evaluator.py in <module>
from graphite.render.datalib import fetchData, TimeSeries ...
▶ Local vars
/opt/graphite/webapp/graphite/render/datalib.py in <module>
from graphite.storage import STORE ...
▶ Local vars
/opt/graphite/webapp/graphite/storage.py in <module>
STORE = Store() ...
▶ Local vars
/opt/graphite/webapp/graphite/storage.py in __init__
                 for finder_path in settings.STORAGE_FINDERS] ...
▶ Local vars
/opt/graphite/webapp/graphite/storage.py in get_finder
  module = import_module(module_name) ...
▶ Local vars
build/bdist.linux-x86_64/egg/importlib/__init__.py in import_module
    __import__(name) ...
▶ Local vars
Request information

GET
No GET data
POST
No POST data
FILES
No FILES data
COOKIES
Variable	Value
grafana_user	
'admin'
grafana_sess	
'11de3c09f8659069'
grafana_remember	
'ce4ebcaf591621be4375de318a88846f97eee619858c7737'
META
Variable	Value
mod_wsgi.listener_port	
'8090'
HTTP_COOKIE	
'grafana_sess=11de3c09f8659069; grafana_user=admin; grafana_remember=ce4ebcaf591621be4375de318a88846f97eee619858c7737'
mod_wsgi.listener_host	
''
SERVER_SOFTWARE	
'Apache/2.2.12 (Linux/SUSE)'
SCRIPT_NAME	
u''
mod_wsgi.enable_sendfile	
'0'
mod_wsgi.handler_script	
''
SERVER_SIGNATURE	
'<address>Apache/2.2.12 (Linux/SUSE) Server at 192.68.1.2 Port 8090</address>\n'
REQUEST_METHOD	
'GET'
PATH_INFO	
u'/render'
SERVER_PROTOCOL	
'HTTP/1.1'
QUERY_STRING	
''
HTTP_USER_AGENT	
'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36'
HTTP_CONNECTION	
'keep-alive'
SERVER_NAME	
'192.68.1.2'
REMOTE_ADDR	
'29.0.14.79'
mod_wsgi.queue_start	
'1434733808574245'
mod_wsgi.request_handler	
'wsgi-script'
apache.version	
(2, 2, 12)
wsgi.url_scheme	
'http'
PATH_TRANSLATED	
'/opt/graphite/conf/graphite.wsgi/render'
SERVER_PORT	
'8090'
wsgi.multiprocess	
True
mod_wsgi.input_chunked	
'0'
SERVER_ADDR	
'192.68.1.2'
DOCUMENT_ROOT	
'/opt/graphite/webapp'
mod_wsgi.process_group	
'graphite'
mod_wsgi.daemon_connects	
'1'
SCRIPT_FILENAME	
'/opt/graphite/conf/graphite.wsgi'
SERVER_ADMIN	
'[no address given]'
wsgi.input	
<mod_wsgi.Input object at 0x7f26a6e09070>
HTTP_HOST	
'192.68.1.2:8090'
mod_wsgi.daemon_start	
'1434733808574642'
wsgi.multithread	
True
mod_wsgi.callable_object	
'application'
mod_wsgi.daemon_restarts	
'0'
REQUEST_URI	
'/render'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
wsgi.file_wrapper	
''
wsgi.version	
(1, 0)
GATEWAY_INTERFACE	
'CGI/1.1'
wsgi.run_once	
False
wsgi.errors	
<mod_wsgi.Log object at 0x7f26a6025cd8>
REMOTE_PORT	
'62246'
HTTP_ACCEPT_LANGUAGE	
'en-US,en;q=0.8'
mod_wsgi.version	
(4, 3, 0)
mod_wsgi.script_start	
'1434733808574725'
mod_wsgi.application_group	
''
mod_wsgi.script_reloading	
'1'
mod_wsgi.request_start	
'1434733808574011'
HTTP_ACCEPT_ENCODING	
'gzip, deflate, sdch'
Settings
Using settings module graphite.settings
Setting	Value
REMOTE_RENDERING	
False
REMOTE_FETCH_TIMEOUT	
6.0
EMAIL_USE_TLS	
False
TIME_ZONE	
'America/New_York'
DOCUMENTATION_URL	
'http://graphite.readthedocs.org/'
CSRF_COOKIE_SECURE	
False
LDAP_URI	
None
LANGUAGE_CODE	
'en-us'
ROOT_URLCONF	
'graphite.urls'
MANAGERS	
()
CARBONLINK_TIMEOUT	
1.0
GRAPHITE_ROOT	
'/opt/graphite'
CLUSTER_SERVERS	
[]
DEFAULT_CHARSET	
'utf-8'
WEBAPP_DIR	
'/opt/graphite/webapp'
SESSION_SERIALIZER	
'django.contrib.sessions.serializers.JSONSerializer'
STATIC_ROOT	
'/opt/graphite/static'
CARBONLINK_RETRY_DELAY	
15
LOG_ROTATE	
True
ALLOWED_HOSTS	
['*']
REMOTE_RENDER_CONNECT_TIMEOUT	
1.0
MESSAGE_STORAGE	
'django.contrib.messages.storage.fallback.FallbackStorage'
WSGI_APPLICATION	
None
EMAIL_SUBJECT_PREFIX	
'[Django] '
SEND_BROKEN_LINK_EMAILS	
False
CONF_DIR	
'/opt/graphite/conf'
SESSION_CACHE_ALIAS	
'default'
SESSION_COOKIE_DOMAIN	
None
SESSION_COOKIE_NAME	
'sessionid'
LDAP_BASE_USER	
''
REMOTE_READER_CACHE_SIZE_LIMIT	
1000
ADMIN_FOR	
()
TIME_INPUT_FORMATS	
('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')
REPLICATION_FACTOR	
1
DATABASES	
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.sqlite3',
             'HOST': '',
             'NAME': '/opt/graphite/storage/graphite.db',
             'OPTIONS': {},
             'PASSWORD': u'********************',
             'PORT': '',
             'TEST_CHARSET': None,
             'TEST_COLLATION': None,
             'TEST_MIRROR': None,
             'TEST_NAME': None,
             'TIME_ZONE': 'UTC',
             'USER': ''}}
LDAP_USE_TLS	
False
FILE_UPLOAD_PERMISSIONS	
None
FILE_UPLOAD_HANDLERS	
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
LOG_CACHE_PERFORMANCE	
False
DEFAULT_CONTENT_TYPE	
'text/html'
TEST_RUNNER	
'django.test.runner.DiscoverRunner'
APPEND_SLASH	
False
FIRST_DAY_OF_WEEK	
0
DATABASE_ROUTERS	
[]
REMOTE_USER_BACKEND	
''
CARBONLINK_HOSTS	
['127.0.0.1:7002']
MAX_FETCH_RETRIES	
2
YEAR_MONTH_FORMAT	
'F Y'
STATICFILES_STORAGE	
'django.contrib.staticfiles.storage.StaticFilesStorage'
INDEX_FILE	
'/opt/graphite/storage/index'
STORAGE_DIR	
'/opt/graphite/storage'
LEGEND_MAX_ITEMS	
10
SERVER_EMAIL	
'root@localhost'
SESSION_COOKIE_PATH	
'/'
FIND_TOLERANCE	
600
MIDDLEWARE_CLASSES	
('graphite.middleware.LogExceptionsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.gzip.GZipMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.cache.UpdateCacheMiddleware',
 'django.middleware.cache.FetchFromCacheMiddleware')
USE_I18N	
True
LDAP_USER_QUERY	
''
SECRET_KEY	
u'********************'
LANGUAGE_COOKIE_NAME	
'django_language'
USE_REMOTE_USER_AUTHENTICATION	
False
FILE_UPLOAD_TEMP_DIR	
None
OPENTSDB_URI	
'http://192.68.1.3:4242/api/v1/'
LDAP_SEARCH_BASE	
''
TRANSACTIONS_MANAGED	
False
LOGGING_CONFIG	
'django.utils.log.dictConfig'
TEMPLATE_LOADERS	
('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')
LOG_DIR	
'/opt/graphite/storage/log/webapp'
TEMPLATE_DEBUG	
False
X_FRAME_OPTIONS	
'SAMEORIGIN'
CSRF_COOKIE_NAME	
'csrftoken'
FORCE_SCRIPT_NAME	
None
USE_X_FORWARDED_HOST	
False
DASHBOARD_REQUIRE_AUTHENTICATION	
False
LDAP_PORT	
389
SIGNING_BACKEND	
'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE	
False
LDAP_BASE_PASS	
u'********************'
JAVASCRIPT_DEBUG	
False
CSRF_COOKIE_DOMAIN	
None
FILE_CHARSET	
'utf-8'
DEBUG	
True
CERES_DIR	
'/opt/graphite/storage/ceres/'
SESSION_FILE_PATH	
None
REMOTE_EXCLUDE_LOCAL	
False
DEFAULT_FILE_STORAGE	
'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS	
('graphite.metrics',
 'graphite.render',
 'graphite.browser',
 'graphite.composer',
 'graphite.account',
 'graphite.dashboard',
 'graphite.whitelist',
 'graphite.events',
 'graphite.url_shortener',
 'django.contrib.auth',
 'django.contrib.sessions',
 'django.contrib.admin',
 'django.contrib.contenttypes',
 'django.contrib.staticfiles',
 'tagging',
 'graphite_opentsdb',
 'cacheback')
LANGUAGES	
(('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy-nl', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-tw', 'Traditional Chinese'))
USE_L10N	
False
COMMENTS_ALLOW_PROFANITIES	
False
STATICFILES_DIRS	
('/opt/graphite/webapp/content',)
PREPEND_WWW	
False
SECURE_PROXY_SSL_HEADER	
None
SESSION_COOKIE_HTTPONLY	
True
DEBUG_PROPAGATE_EXCEPTIONS	
False
CACHES	
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
URL_PREFIX	
''
MONTH_DAY_FORMAT	
'F j'
STORAGE_FINDERS	
('graphite_opentsdb.finder.OpenTSDBFinder',)
LOGIN_URL	
<django.utils.functional.__proxy__ object at 0x7f26a6f1bf50>
SESSION_EXPIRE_AT_BROWSER_CLOSE	
False
STANDARD_DIRS	
['/opt/graphite/storage/whisper/']
LDAP_SERVER	
''
TIME_FORMAT	
'P'
MEMCACHE_HOSTS	
[]
AUTH_USER_MODEL	
'auth.User'
DATE_INPUT_FORMATS	
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
GRAPHITE_WEB_APP_SETTINGS_LOADED	
True
AUTHENTICATION_BACKENDS	
['django.contrib.auth.backends.ModelBackend']
EMAIL_HOST_PASSWORD	
u'********************'
CARBONLINK_HASHING_KEYFUNC	
u'********************'
PASSWORD_RESET_TIMEOUT_DAYS	
u'********************'
CACHE_MIDDLEWARE_ALIAS	
'default'
SESSION_SAVE_EVERY_REQUEST	
False
NUMBER_GROUPING	
0
SESSION_ENGINE	
'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW	
'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH	
'/'
LOGIN_REDIRECT_URL	
'/accounts/profile/'
OPENTSDB_TREE	
1
FLUSHRRDCACHED	
''
DECIMAL_SEPARATOR	
'.'
FIND_CACHE_DURATION	
300
IGNORABLE_404_URLS	
()
LOCALE_PATHS	
()
WHITELIST_FILE	
'/opt/graphite/storage/lists/whitelist'
TEMPLATE_STRING_IF_INVALID	
''
LOGOUT_URL	
'/accounts/logout/'
DASHBOARD_CONF	
'/opt/graphite/conf/dashboard.conf'
TEMPLATE_DIRS	
('/opt/graphite/webapp/graphite/templates',)
RRD_DIR	
'/opt/graphite/storage/rrd/'
FIXTURE_DIRS	
()
EMAIL_HOST	
'localhost'
DATE_FORMAT	
'N j, Y'
MEDIA_ROOT	
''
CARBON_METRIC_PREFIX	
'carbon'
DEFAULT_EXCEPTION_REPORTER_FILTER	
'django.views.debug.SafeExceptionReporterFilter'
ADMINS	
()
LOG_METRIC_ACCESS	
False
FORMAT_MODULE_PATH	
None
DEFAULT_FROM_EMAIL	
'webmaster@localhost'
THOUSAND_SEPARATOR	
','
WEB_DIR	
'/opt/graphite/webapp/graphite'
MEDIA_URL	
''
DATETIME_FORMAT	
'N j, Y, P'
MEMCACHE_KEY_PREFIX	
u'********************'
REMOTE_FIND_TIMEOUT	
3.0
DISALLOWED_USER_AGENTS	
()
ALLOWED_INCLUDE_ROOTS	
()
USE_THOUSAND_SEPARATOR	
False
USE_LDAP_AUTH	
False
LOGGING	
{}
SHORT_DATE_FORMAT	
'm/d/Y'
RRD_CF	
'AVERAGE'
WEBAPP_VERSION	
'0.10.0-alpha'
STATICFILES_FINDERS	
('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder')
CACHE_MIDDLEWARE_KEY_PREFIX	
u'********************'
SMTP_SERVER	
'localhost'
FILE_UPLOAD_MAX_MEMORY_SIZE	
2621440
WHISPER_DIR	
'/opt/graphite/storage/whisper/'
EMAIL_BACKEND	
'django.core.mail.backends.smtp.EmailBackend'
CSRF_COOKIE_HTTPONLY	
False
DEFAULT_TABLESPACE	
''
TEMPLATE_CONTEXT_PROCESSORS	
('django.contrib.auth.context_processors.auth',
 'django.core.context_processors.debug',
 'django.core.context_processors.i18n',
 'django.core.context_processors.media',
 'django.core.context_processors.static',
 'django.core.context_processors.tz',
 'django.contrib.messages.context_processors.messages')
RENDERING_HOSTS	
[]
ALLOW_ANONYMOUS_CLI	
True
SESSION_COOKIE_AGE	
1209600
SETTINGS_MODULE	
'graphite.settings'
USE_ETAGS	
False
DEFAULT_CACHE_DURATION	
60
LANGUAGES_BIDI	
('he', 'ar', 'fa', 'ur')
DEFAULT_INDEX_TABLESPACE	
''
INTERNAL_IPS	
()
STATIC_URL	
'/static/'
EMAIL_PORT	
25
LOG_RENDERING_PERFORMANCE	
False
DASHBOARD_REQUIRE_EDIT_GROUP	
None
USE_TZ	
True
SHORT_DATETIME_FORMAT	
'm/d/Y P'
PASSWORD_HASHERS	
u'********************'
REMOTE_RETRY_DELAY	
60.0
ABSOLUTE_URL_OVERRIDES	
{}
CACHE_MIDDLEWARE_SECONDS	
600
DASHBOARD_REQUIRE_PERMISSIONS	
False
DATETIME_INPUT_FORMATS	
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
GRAPHTEMPLATES_CONF	
'/opt/graphite/conf/graphTemplates.conf'
EMAIL_HOST_USER	
''
PROFANITIES_LIST	
u'********************'
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page.

**Comment by brutasse** [comment]
Your graphite installation is unable to import the opentsdb finder. How did you install it?

https://pypi.python.org/pypi/graphite-opentsdb
