### ISSUE TITLE
wrong version number inside the graphite-web-0.9.13.tar.gz  bundle

### ISSUE THREAD

**Issue by sergedu** [graphite-project/graphite-web#1271]
Hi,
I was thinking to submit a pull request, but I see there is 0.10 alpha already.  It is just to let you know that I've been upgrading from 0.9.12  to 0.9.13 (the latest stable) then after the upgrade was surprised that my
http://graphite.xxxxx.net/version/
- still shows  0.9.12  which gives enough confusion by making me and probably other people thinking that there was something wrong with the upgrade.  Then I spent some time to find out what is wrong, finally decided to download the 
  wget https://pypi.python.org/packages/source/g/graphite-web/graphite-web-0.9.13.tar.gz
  - unpacked it and checked the version:
  
  grep '0.9.' ./graphite-web-0.9.13/webapp/graphite/settings.py
  - which gives the result: 

WEBAPP_VERSION = '0.9.12'

   Please fix it to read '0.9.13' then re-create the bundle.  

Thank you.

**Comment by deniszh** [comment]
Hi @sergedu,
0.10-alpha is version of master branch, and WEBAPP_VERSION = '0.9.13' is already fixed in 0.9.x branch - https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/settings.py
0.9.13 will be released soon :tm: from that branch.

**Comment by Thermatix** [comment]
So it **is** version '0.9.13', just that the version number hasn't been bumped?

**Comment by deniszh** [comment]
It was not bumped when 0.9.13-rc1 was packed. Now it's bumped, (so, no need for PR), and WEBAPP_VERSION = '0.9.13' will be present in 0.9.13 when it will be finally released soon. :tm:
