### ISSUE TITLE
Feature Request: Add a function to subtract series element wise

### ISSUE THREAD

**Issue by mdesnoyer-neon** [graphite-project/graphite-web#1280]
I just ran into a challenge where I have every increasing counters of specific errors on each of my machines. I wanted to create a graphite metric which is akin to "number of errors in the last t minutes" on each machine. You can do this easily with a single machine like:

diffSeries(system.neonisp0.isp.neon_updater_http_fetch_fail), timeShift(system.neonisp0.isp.neon_updater_http_fetch_fail,"10min"))

But the wildcard equivalent doesn't work because diffSeries subtracts series 1:end by series 0. i.e. the following fails:
diffSeries(system.neonisp[0-9]_.isp.neon_updater_http_fetch_fail, timeShift(system.neonisp[0-9]_.isp.neon_updater_http_fetch_fail,"10min"))

I've found a workaround to get what I want, but it is nasty and relies on how timeStack names things:

groupByNode(aliasSub(timeStack(system.neonisp[0-9]-usw.isp.neon_updater_http_fetch_fail, "10min", 0, 2), "^._(system.[^,]+)._([0-9]))$", "\1.\2"),1,"diffSeries") 

So, it would be nice to have a function that lets you subtract (or divide, multiply, etc) elementwise. Or even just have diffSeries etc.. identify that two entries expand out to the same number of series, then just apply the operation on a per element basis.

**Comment by zhangela** [comment]
Just had the same issue. Would love to have this feature as well!

**Comment by nnuss** [comment]
This may be a potential alternative in this specific case of counters over time:
`nonNegativeDerivative(movingSum(system.neonisp[0-9].isp.neon_updater_http_fetch_fail,"10min","last"))`

If you're not running latest graphite this still works well with wildcards (++) but lowers resolution (--): `nonNegativeDerivative(summarize(system.neonisp[0-9].isp.neon_updater_http_fetch_fail,"10min","last"))`
