### ISSUE TITLE
How many metric paths can graphite support?

### ISSUE THREAD

**Issue by ittayd** [graphite-project/graphite-web#1286]
(couldn't find a forum to ask this)

**Comment by SEJeff** [comment]
It depends on the backend in use, if you're using the default whisper backend, it would depend on your filesystem and how many files can be stored in a single directory.

The metric foo.bar.baz would come out to:

$GRAPHITE_STORAGE_DIR/foo/bar/baz.wsp

But it really depends on the storage backend. Some of them use Cassandra, Riak, or OpenTSDB and can hold quite a few sets.

If this didn't answer your question feel free to reopen it
