### ISSUE TITLE
Unable to add metric with a name that contains % symbol to a dashboard

### ISSUE THREAD

**Issue by LeonidVasilyev** [graphite-project/graphite-web#1294]
I'm using Graphite version 0.9.12 hosted on Ubuntu Server 14.04.
Metric example: `vstest_executionengine_x86.System.CPU_Usage-%`
Following error is logged to a console: 

```
Uncaught URIError: URI malformed
    (anonymous function) @ ext-base.js:7
    Ext.apply.each @ ext-base.js:7
    Ext.apply.urlDecode @ ext-base.js:7
    graphAreaToggle @ dashboard.js:918
    Ext.grid.GridPanel.listeners.rowclick @ dashboard.js:304
    h.Event.fire @ ext-all.js:7
    h.Observable.fireEvent @ ext-all.js:7
    Ext.grid.GridView.Ext.extend.processEvent @ ext-all.js:11
    Ext.grid.GridPanel.Ext.extend.processEvent @ ext-all.js:11
    Ext.grid.GridPanel.Ext.extend.onClick @ ext-all.js:11
    J @ ext-all.js:7
```

**Comment by obfuscurity** [comment]
That's an invalid character for metric names. Better to use something like `pct`.

**Comment by LeonidVasilyev** [comment]
@obfuscurity strange that it works fine in Graph Composer. Is it documented somewhere which characters are valid and which are not? 
I use [Metrics.NET](https://github.com/etishor/Metrics.NET) library, it use this notation by default

**Comment by obfuscurity** [comment]
Hmm, that's unexpected. Sorry, I'll reopen this so we can investigate further.
