### ISSUE TITLE
darkred and red colors are swaped

### ISSUE THREAD

**Issue by Civil** [graphite-project/graphite-web#1310]
https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/glyph.py#L59
https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/glyph.py#L44

They are actually swaped. Red is darker than darkred.

**Comment by Civil** [comment]
@deniszh this is still happens in recent 1.1 :)

**Comment by Civil** [comment]
same thing is also true for green <-> darkgreen, blue <-> darkblue,

**Comment by deniszh** [comment]
Agreed, will make PR. Thanks!
