### ISSUE TITLE
graphite-web vs carbon.* metrics

### ISSUE THREAD

**Issue by rlueckl** [graphite-project/graphite-web#1311]
Hi,

this is not really an issue, but I need to clarify it: I've discovered, that graphite-web asks the wrong carbon-caches for "hot" data if I'm querying a metric which starts with carbon.*

This would makes sense, since the metrics written under carbon.* are "generated" by the carbon-caches themselves and are *not hashed* / relayed, just plainly written by the cache in their own LOCAL_DATA_DIR.

But when asking for the metric, graphite-web doesn't (can't?) take this into account and hashes the metric, therefore asking the wrong CARBONLINK_HOST most of the time. The result is, that all metrics which begin with carbon.* are "lagging" behind a few minutes (because the newest result are not yet written to file, but still in RAM). The other metrics are up-to-date since DESTINATIONS == CARBONLINK_HOSTS and graphite-web can ask the cache "responsible" for given hashed metric.

Is this normal behaviour? Will it be addressed in later versions? (Can this be addressed?)

I'm using carbon 0.9.13 (via pip) and graphite-web 0.9.13 (also via pip).

Thanks,
Roland

**Comment by deniszh** [comment]
Yep, your'e right - 'carbon' metrics not cached at all (not sure if because of wrong CARBONLINK request or because of no cache request even being made) and it's not fixed yet.

**Comment by rlueckl** [comment]
Hi @deniszh,

thanks for the fast answer. Unfortunately I don't really understand what you write, because that's the exact opposite. If the cached wouldn't cache the 'carbon' metrics, then all would be good. The latest metrics would always be available on the disk and graphite would show them "up-to-date".

But the 'carbon' metrics are cached (in the cache). The problem is that graphite ask the **wrong** cache (because it doesn't know that 'carbon' metrics are "localized" to the cache).

An example:

carbon-relay, DESTINATIONS = ['127.0.0.1:2004:a','127.0.0.1:2104:b','127.0.0.1:2204:c']
graphite-web, CARBONLINK_HOSTS = ['127.0.0.1:7004:a','127.0.0.1:7104:b','127.0.0.1:7204:c']

carbon-cache:a writes metric 'carbon.agents.server1-a.memUsage' to his own LOCAL_DATA_DIR.

graphite-web wants to query 'carbon.agents.server1-a.memUsage', therefore graphite-web _hashes_ the metric and discovers that he has to ask carbon-cache:c for the metric. But carbon-cache:c doesn't have the metric, because it's generated "locally" in carbon-cache:a.

Am I making sense? :)

**Comment by deniszh** [comment]
Hi @rlueckl,
If "latest metrics would always be available on the disk and graphite would show them 'up-to-date'" - why we need carbonlink and cache then?
No, that's a problem exactly - metrics on disk are delayed, because disk is slow, and carbon daemon flushes its cache periodically. In my case it finish flush cycle for 30-40 minutes, so carbon metrics for last hour are inconsistent. If I turn off cache completely - all my metrics will be delayed.

**Comment by deniszh** [comment]
And BTW problem lies somewhere in carbon daemon - graphite-web doesn't know nothing about CARBON_METRIC_PREFIX before https://github.com/graphite-project/graphite-web/commit/48bbfbe073df7852625b9462907ac56f9d65a297

**Comment by rlueckl** [comment]
Hi @deniszh,

thanks, 48bbfbe was exactly what I was looking for. I see that the change was merged on Feb 28, 2014, but I don't see it in the Dec 31, 2014 release of 0.9.13?

Do you know when we can expect this "feature"? Will it be in the next release and if yes, when is the next release coming?

**Comment by deniszh** [comment]
As I found just now this commit was never backported to 0.9.x branch, so, it's not exist in 0.9.13 yet. 
But I have this patch backported to my own branch and I still have same problems as you describe - so, I do not think that's solution for that problem. Real problem lies somewhere in carbon daemon, and I'm almost migrated to https://github.com/lomik/go-carbon which doesn't have this problem...

**Comment by deniszh** [comment]
PS: I migrated not because of this issue - it seems that issue or not relevant for majority of users (and nobody cares) or maybe code in master branch really fixes that...

**Comment by rlueckl** [comment]
Thanks for all the information! My company is currently staying with carbon 0.9.13, so we will have to live with this "issue". :smile:
