### ISSUE TITLE
Graphite 0.9.13

### ISSUE THREAD

**Issue by ravibhooshan** [graphite-project/graphite-web#1313]
I am new to Graphite and Github, please help me if this question is not relevant for this forum.
Currently I am running Graphite 0.9.12 but having time gap issue while rendering graph using API.
But I have not seen this issue in 0.9.13. But i am not finding 0.9.13 code on github while it was available earlier.
It is a stable version and can i use it in production.
Thanks
Ravi

**Comment by dforste** [comment]
Graphite 0.9.13 is bata but it is the version you get if you do a pip install. I hit issues when I was using it. I have since reverted to 0.9.12 in production but this brings other issues.

**Comment by Krinkle** [comment]
See also #677.

**Comment by obfuscurity** [comment]
The "0.9.13" from pip is a release candidate, not the final version. You didn't specify what sort of "time gap issues" you're having, but there were two recent PRs merged that address time issues. See https://github.com/graphite-project/graphite-web/pull/1157 and https://github.com/graphite-project/graphite-web/pull/1034 for details.

**Comment by ravibhooshan** [comment]
Thanks for all reply and sorry for very late in reply.
I am having issue in rendered graph. When I render a graphite graph in our application for last 20 minutes, it doesn't show any data but when we change the time in rendered link 1hour behind it starts showing correct data.
For example - If my rendered link is showing start time - 10:15 end time 10:35. Graph will not show any data (assuming i am running it at 10:35) but when I will change start time to and end time to 9:15 and 9:35 respectively it will start showing data from 10:15 to 10:35.

I have not noticed this i n 0.9.13.

**Comment by obfuscurity** [comment]
@ravibhooshan As mentioned in my previous comment, there were some fixes that went into the 0.9.x branch to address time issues. If you're able, please try the 0.9.x branch. If not, it should be fixed in the next stable release.
