### ISSUE TITLE
Error 500 - Internal Server Error

### ISSUE THREAD

**Issue by halysan** [graphite-project/graphite-web#1317]
Hi !

I install graphite-carbon 0.9.12 and graphite-web with repository on Derbian Jessie.
On the web interface I've error 500 "Internal Server Error".

My log apache:
<code>
[Wed Sep 09 04:27:20.954934 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]   File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 731, in _do_insert
[Wed Sep 09 04:27:20.954967 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]     using=using, raw=raw)
[Wed Sep 09 04:27:20.954982 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]   File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
[Wed Sep 09 04:27:20.955070 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Wed Sep 09 04:27:20.955085 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]   File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 921, in _insert
[Wed Sep 09 04:27:20.955442 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]     return query.get_compiler(using=using).execute_sql(return_id)
[Wed Sep 09 04:27:20.955456 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]   File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
[Wed Sep 09 04:27:20.955717 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]     cursor.execute(sql, params)
[Wed Sep 09 04:27:20.955730 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]   File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
[Wed Sep 09 04:27:20.955808 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]     return self.cursor.execute(sql, params)
[Wed Sep 09 04:27:20.955823 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]   File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
[Wed Sep 09 04:27:20.955919 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[Wed Sep 09 04:27:20.955932 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]   File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
[Wed Sep 09 04:27:20.955948 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]     return self.cursor.execute(sql, params)
[Wed Sep 09 04:27:20.955960 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]   File "/usr/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 485, in execute
[Wed Sep 09 04:27:20.956100 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512]     return Database.Cursor.execute(self, query, params)
[Wed Sep 09 04:27:20.956145 2015] [wsgi:error] [pid 3932:tid 140310950643456] [remote 172.24.23.6:512] OperationalError: attempt to write a readonly database
</code>

You have an idea? 
Thks,
Best regards,

**Comment by ashokrajar** [comment]
Answer to your question is in the error itself. Look at your last line.

3932:tid 140310950643456] [remote 172.24.23.6:512] OperationalError: attempt to write a readonly database

Make sure graphite installation folder and the sqlitedb file is writable by apache process.

**Comment by halysan** [comment]
Hi !
Thks for you answer,

Yes I had observed this error.
But my folder "/var/lib/graphite" is "www-data:www-data"..
And my file "graphite.db" is "www-data:www-data"...

I don't understand very well...
I just made a normal installation with "aptitude"...

**Comment by halysan** [comment]
OK.... I changed permission and handed the default
and it works..

Strange...
Thanks for your help

**Comment by linuxzaman** [comment]
could you please let me know what changes you did. i am having same issue

**Comment by ashokrajar** [comment]
@linuxzaman check if the graphite installation folder and the sqlitedb file is writable by apache process.

**Comment by linuxzaman** [comment]
i do have under _graphite ownership. still having issue

**Comment by mookie-** [comment]
Just in case someone finds this issue (as I did).
For using SQLite the database file itself and *also* the directory in which the database file is located have to be writable.
