### ISSUE TITLE
Sawtooth metrics while summarizing over series

### ISSUE THREAD

**Issue by schancel** [graphite-project/graphite-web#1321]
On graphite `0.9.12+debian-3`, I'm seeing the following behavior sporadically.  The 5 minute averages are going to zero due to the transformNull() operation.  However, a few seconds later they will go back to normal when the data is refreshed.

Any insight would be appreciated.  

![screen shot 2015-09-22 at 5 13 14 pm](https://cloud.githubusercontent.com/assets/213740/10036230/5f8209be-6159-11e5-8688-bd95c20d4907.png)

**Comment by obfuscurity** [comment]
It would be helpful to see the actual data. Can you upload a copy of your Whisper file somewhere?

**Comment by schancel** [comment]
Sure, thank you.  The attached file is a sample of what would be there -- I don't have the particular wsp file that produced the image.  This is the series that would produce such an image though.

https://s3-us-west-1.amazonaws.com/shammah/disk_used.wsp

**Comment by obfuscurity** [comment]
@schancel Would you mind testing with the 0.9.x branch (HEAD) and let me know if you're still seeing this? We've had some recent fixes that affect merging of CarbonLink and Whisper archives which I think may be related to your issue.

**Comment by schancel** [comment]
@obfuscurity Sorry for the delay.  Looks like I'll be able to test 0.9.15 soon.   I'll post here once I find out if that resolved the issue.  Thanks for looking into it.
