### ISSUE TITLE
Round values to 0.5

### ISSUE THREAD

**Issue by eliabieri** [graphite-project/graphite-web#1346]
Is there function to round values to a given precisions?
I want all my values(temperatures) to be rounded to 0.5
Thank you!

**Comment by breml** [comment]
Today I was missing this function as well. It would be nice to have a rounding function for timeseries.

**Comment by hau21um** [comment]
Would help to have round and trim functions..

**Comment by monsdar** [comment]
Is this implemented now? Why has this been closed?

**Comment by deniszh** [comment]
No, it was not implemented. Not sure why @eliabieri closed it.
Newer Graphite versions have support for custom functions - see [docs](https://graphite.readthedocs.io/en/1.1.1/functions.html#function-plugins).
You can also open PR and we'll include function in next release (but in that case it should also have tests, documentation etc)

**Comment by deniszh** [comment]
@monsdar : you can also check my example for custom function - https://github.com/deniszh/graphite_asap

**Comment by piotr1212** [comment]
This could be harder to implement correctly than it looks as Graphite uses floats internally. I don't know if this will be an issue in practice but it could lead to unexpected results.
