### ISSUE TITLE
Adding event to graphite - using CURL - results into Authorization Required

### ISSUE THREAD

**Issue by softwareklinic** [graphite-project/graphite-web#1347]
Hi,

I'm trying to add event to graphite server using the CURL Command i keep getting 401 authorization required... How do i pass the username/password to the CURL request?

**Comment by deniszh** [comment]
http://bfy.tw/29Kp -

"Use the -u flag to include a username, and curl will prompt for a password:

curl -u username http://example.com

You can also include the password in the command, but then your password will be visible in bash history:

curl -u username:password http://example.com"
