### ISSUE TITLE
Incorrect data is fetched from graphite intermittently.

### ISSUE THREAD

**Issue by rajatwy** [graphite-project/graphite-web#1354]
I am facing an issue such that the data returned from graphite is totally different and unexpected, sometimes. This leads to false alarms, and what not.

Later when I check the data again for the same query it is correct, this is happening intermittently.

#### Cluster Info ####
We are running graphite as a cluster of 5 nodes.

* Node [A] does not store any data locally, it replicates [replication factor = 2] it into two different nodes [B, C]. It's webapp fetches data from Node [D] and [E]. We send and retrieve the data from this node.

* Node [A] also runs statsd, which pushes data to node [A]'s relay. 

* Node [B] runs relay, cache and stores all the data it gets locally and serves this via the webapp, this is our backup server.

* Node [C] runs relay, and doesn't store any data locally and forwards the data it gets (consitent-hashing), to two nodes [D, E].

* Node [D, E] are nodes who run relay and cache, and store the data they get, and serve them via the webapp. 

We have recently moved to this new clustered architecture, earlier we only had the single node [B].

#### Versions ####
* whisper : 0.9.10
* carbon : 0.9.12
* webapp : 0.9.12

Any help will be greatly appreciated. Thanks.

**Comment by obfuscurity** [comment]
First, you should **never** run mismatched versions of Graphite components. Second, there have been a lot of fixes for this type of behavior in the 0.9.x branch leading up to our next release. You should try the 0.9.x branch and please let us know if that doesn't fix your issues.

**Comment by rajatwy** [comment]
I have upgraded my cluster to  0.9.x and the issue has disappeared.
Thanks @obfuscurity!

**Comment by rajatwy** [comment]
Facing this issue again. I have seen two false alerts (got empty data from graphite for both).
Later when I queried for the same time period, it gives me non-empty data.
