### ISSUE TITLE
Time unit parsing is very loose

### ISSUE THREAD

**Issue by ddlatham** [graphite-project/graphite-web#1357]
If I share a query like
from=-2decades&until=-1decades
people may be surprised when they execute it and it is actually  the same as
from=-2days&until=-1days

**Comment by obfuscurity** [comment]
It's very unrealistic that someone will use `decade` as a time unit. The Graphite project hasn't even been around for one decade. Statistically, the likelihood of someone trying that is virtually zero, so I have no concerns with trying to support that literal unit. If someone really wants to query "20 years" they can use the year time unit.

**Comment by ddlatham** [comment]
I'm sorry I didn't explain that well as it was misunderstood.  That was purely an example.  Currently it appears any values that appear to begin with the same letters or prefixes as the supported time units.  This could cause confusion, accidentally or maliciously.  

from=-2whales&until=-1deadlydragons

**Comment by obfuscurity** [comment]
People can type any nonsense in there but it doesn't make it any more valid. See, I can type `from=-2shits`, which will render seconds and just so happens to represent exactly how many things I don't give about this issue. :wink:

Point being, yes, you are expected to use the product as intended. If you choose to insert nonsense time units, then be prepared to be disappointed.
