### ISSUE TITLE
Graphs missing legends

### ISSUE THREAD

**Issue by avneradania** [graphite-project/graphite-web#1360]
![empty_legends](https://cloud.githubusercontent.com/assets/15194484/10576613/5b991e86-766d-11e5-9375-4cd25508bcdf.png)
Hi,

There is a problem with my Graphite running on CentOS 6.6.
Grapes are needed with data, but no values in Y and X axises.
Also legends are not shown as well.
Is someone familiar with it?

**Comment by obfuscurity** [comment]
Is it possible your theme is using a white font against a white background?

**Comment by avneradania** [comment]
Thanks for quick response, obfuscurity.
I found the problem. In 6.5 there was no issues, but after upgrading to 6.6, there is fonts related RPM missing, dejavu-sans-fonts.
When i changed font to courier, i saw legends and values.
I installed dejavu-sans-fonts and graphs look great with sans(font).

Thanks,
Avner

**Comment by obfuscurity** [comment]
Awesome, glad to hear it. I suspected it might have been a fonts issue (this seems to be common with Red Hat systems) but I figured we'd start with the easy stuff. :wink:
