### ISSUE TITLE
Graphite Search 

### ISSUE THREAD

**Issue by bigdataquestions** [graphite-project/graphite-web#1362]
Hi,

We are running a deployment of Graphite (version 0.9.12). This is running well, but the search for metrics function seems to be unavailable. The box appears but no results are returned. 

Is there documentation on how to operate this feature?
Does this feature need to be enabled? - If so, how?
Are there any known limitations to this feature?
Are there any prerequisites for search to work?

Kind Regards

**Comment by obfuscurity** [comment]
The browser search functionality relies on the index db existing. There should be a [build-index.sh](https://github.com/graphite-project/graphite-web/blob/0.9.12/bin/build-index.sh) script (typically in `/opt/graphite/bin`) that can be cron'd to rebuild your index file. HTH.
