### ISSUE TITLE
Moving average Winter time change

### ISSUE THREAD

**Issue by floppy84** [graphite-project/graphite-web#1374]
Hi,

I open this ticket because i got an issue or a misunderstanding on how to.

So i graph a value during time on first query.
On second query i graph the same data but with a timeshift of 7d 14d 21d 28d ::

![image](https://cloud.githubusercontent.com/assets/3499449/10790311/cf2416e6-7d82-11e5-98e2-a9b9be175291.png)

Until this week end all worked fine. but until the change of time (French Hour), i got a gap on my graphe like you see at the end of graphe ::

![image](https://cloud.githubusercontent.com/assets/3499449/10790293/ba6f9c5c-7d82-11e5-8777-e148dd894fdc.png)

My question is, is there a way to manage this change of time.

Thanks
regards

**Comment by deniszh** [comment]
Similar issue - https://github.com/graphite-project/graphite-web/issues/1024
Not much to add here, at least from my side.

**Comment by obfuscurity** [comment]
What happens if you use a timeshift in terms of minutely units, e.g. 10080 mins instead of 7d?

**Comment by floppy84** [comment]
Hi thank you for your answer, i got the same issue if i set timeshift in minute ::

![image](https://cloud.githubusercontent.com/assets/3499449/10819581/2776905a-7e49-11e5-83f2-c9a08395305f.png)

**Comment by deniszh** [comment]
Unfortunately no good solution exist for that bug currently - except running your servers in UTC (which is easy if you doing that from start, but quite hard if you need to migrate there).
Even if we (over)complicate [timeOffset()](https://github.com/graphite-project/graphite-web/blob/c542449047d53e7c05d4cc43cfd0e36f9718ca44/webapp/graphite/render/attime.py#L120) function to check DST boundaries it will work only when both ("from" and "to") boundaries is after or before switch time. 
I see no way how we can fix graph above - timeShift() value must be the same for all graph values, it can't be 10080m before DST moment, and 10020 / 10140 after, on same graph....

**Comment by floppy84** [comment]
I don't need to mgrate data, i will set my server in UTC , and next time change in summer i will not have same issue.
 Thanks for your help

**Comment by peterstory** [comment]
Would it be possible to add another argument to timeShift, toggling whether DST-compensation is applied? It seems like a common use case: using timeShift(-1w) to compare metric values at 7am this week to values at 7am last week... not values at 7am to values at 6am. 

I've written an application which analyzes trends in metrics, week-over-week (using an arbitrary number of historic weeks). I expect to write some gnarly work-around code for this, but it would be nice if timeShift could save others from the issue!

**Comment by peterstory** [comment]
I'm thinking it would be a shortcut for +/- 1 hour to the time shift. It would only take affect if the from and until times were both in DST, and the timeShift-ed time was outside DST (and vice-versa). 

Example: a graph showing a metric from 8am-8pm, on November 1st. Currently, if you add a 1 day/week timeShift-ed version of the metric, it will be actually be showing 9am-7pm. 

    my.great.metric.count
    timeShift(my.great.metric.count,"-1w")

But with the DST-compensation, both graphs would show from 8am-8pm. 

    my.great.metric.count
    timeShift(my.great.metric.count,"-1w",dst=true)

equivalent to 

    timeShift(my.great.metric.count,"-167h")

**Comment by peterstory** [comment]
I'm working on a patch for myself, though if you're interested in integrating it into the main project, that would be great, too. Unfortunately, my changes don't seem to be having an effect. Any thoughts? 

```diff
diff --git a/webapp/graphite/render/functions.py b/webapp/graphite/render/functions.py
index 1908273..d9b8b1c 100644
--- a/webapp/graphite/render/functions.py
+++ b/webapp/graphite/render/functions.py
@@ -2465,7 +2465,7 @@ def timeStack(requestContext, seriesList, timeShiftUnit, timeShiftStart, timeShi
 
   return results
 
-def timeShift(requestContext, seriesList, timeShift, resetEnd=True):
+def timeShift(requestContext, seriesList, timeShift, resetEnd=True, dstTweak=True):
   """
   Takes one metric or a wildcard seriesList, followed by a quoted string with the
   length of time (See ``from / until`` in the render\_api_ for examples of time formats).
@@ -2499,6 +2499,21 @@ def timeShift(requestContext, seriesList, timeShift, resetEnd=True):
   myContext = requestContext.copy()
   myContext['startTime'] = requestContext['startTime'] + delta
   myContext['endTime'] = requestContext['endTime'] + delta
+
+  if dstTweak:
+    one_hour = 60 * 60
+    # If the requestContext is entirely in DST, and the timeshifted range is
+    # entirely NOT in DST
+    if ((requestContext['startTime'].dst() and requestContext['endTime'].dst()) and (not myContext['startTime'].dst() and not myContext['endTime'].dst())):
+        myContext['startTime'] - one_hour
+        myContext['endTime'] - one_hour
+    # Or if the requestContext is entirely NOT in DST, and the timeshifted
+    # range is entirely in DST
+    elif ((not requestContext['startTime'].dst() and not requestContext['endTime'].dst()) and (myContext['startTime'].dst() and myContext['endTime'].dst())):
+        myContext['startTime'] + one_hour
+        myContext['endTime'] + one_hour
+    # Otherwise, we don't do anything, because it would be visually confusing
+
   results = []
   if len(seriesList) > 0:
     # if len(seriesList) > 1, they will all have the same pathExpression, which is all we care about.
```

**Comment by peterstory** [comment]
Looks like the ``.dst()`` method wasn't doing what I thought. Instead, I need to use something like this: 
```python
now = requestContext['startTime']
time.localtime(time.mktime(now.timetuple())).tm_isdst
```
However, that's not very readable. Is there a better (and probably safer) way to check whether DST was in effect at a given ``datetime``?

**Comment by peterstory** [comment]
I did some digging, and I guess the hack described above is the only way to do this, since it basically is a hack (since we're applying our local time zone info to something that originally didn't have time zone info)! 

Anyway, here is a final, working version: 
```diff
diff --git a/webapp/graphite/render/functions.py b/webapp/graphite/render/functions.py
index 1908273..c3891ff 100644
--- a/webapp/graphite/render/functions.py
+++ b/webapp/graphite/render/functions.py
@@ -2465,7 +2465,7 @@ def timeStack(requestContext, seriesList, timeShiftUnit, timeShiftStart, timeShi
 
   return results
 
-def timeShift(requestContext, seriesList, timeShift, resetEnd=True):
+def timeShift(requestContext, seriesList, timeShift, resetEnd=True, dstTweak=True):
   """
   Takes one metric or a wildcard seriesList, followed by a quoted string with the
   length of time (See ``from / until`` in the render\_api_ for examples of time formats).
@@ -2499,6 +2499,27 @@ def timeShift(requestContext, seriesList, timeShift, resetEnd=True):
   myContext = requestContext.copy()
   myContext['startTime'] = requestContext['startTime'] + delta
   myContext['endTime'] = requestContext['endTime'] + delta
+
+  def localDST(dt):
+    return time.localtime(time.mktime(dt.timetuple())).tm_isdst
+
+  reqStartDST = localDST(requestContext['startTime'])
+  reqEndDST   = localDST(requestContext['endTime'])
+  myStartDST  = localDST(myContext['startTime'])
+  myEndDST    = localDST(myContext['endTime'])
+
+  dstOffset = timedelta(hours=0)
+  if dstTweak:
+    # If the requestContext is entirely in DST, and we are entirely NOT in DST
+    if ((reqStartDST and reqEndDST) and (not myStartDST and not myEndDST)):
+        dstOffset = timedelta(hours=1)
+    # Or if the requestContext is entirely NOT in DST, and we are entirely in DST
+    elif ((not reqStartDST and not reqEndDST) and (myStartDST and myEndDST)):
+        dstOffset = timedelta(hours=-1)
+    # Otherwise, we don't do anything, because it would be visually confusing
+    myContext['startTime'] += dstOffset
+    myContext['endTime'] += dstOffset
+
   results = []
   if len(seriesList) > 0:
     # if len(seriesList) > 1, they will all have the same pathExpression, which is all we care about.
```

**Comment by deniszh** [comment]
I think it's need to be rewritten like this to not bring any overhead where dstTweak=false. And maybe make it false by default....
```python
  if dstTweak:
	def localDST(dt):
	  return time.localtime(time.mktime(dt.timetuple())).tm_isdst

	reqStartDST = localDST(requestContext['startTime'])
	reqEndDST   = localDST(requestContext['endTime'])
	myStartDST  = localDST(myContext['startTime'])
	myEndDST    = localDST(myContext['endTime'])

	dstOffset = timedelta(hours=0)
	# If the requestContext is entirely in DST, and we are entirely NOT in DST
	if ((reqStartDST and reqEndDST) and (not myStartDST and not myEndDST)):
	    dstOffset = timedelta(hours=1)
	# Or if the requestContext is entirely NOT in DST, and we are entirely in DST
	elif ((not reqStartDST and not reqEndDST) and (myStartDST and myEndDST)):
	    dstOffset = timedelta(hours=-1)
	# Otherwise, we don't do anything, because it would be visually confusing
	myContext['startTime'] += dstOffset
	myContext['endTime'] += dstOffset
```

**Comment by peterstory** [comment]
Good idea! Yes, it is funky, potentially unexpected behavior, so it does make sense to leave it disabled by default. If you'd like to integrate this into the project, just let me know, since I made my change in a local Git repo. 

A revised diff:
```diff
diff --git a/webapp/graphite/render/functions.py b/webapp/graphite/render/functions.py
index 1908273..d66ad72 100644
--- a/webapp/graphite/render/functions.py
+++ b/webapp/graphite/render/functions.py
@@ -2465,7 +2465,7 @@ def timeStack(requestContext, seriesList, timeShiftUnit, timeShiftStart, timeShi
 
   return results
 
-def timeShift(requestContext, seriesList, timeShift, resetEnd=True):
+def timeShift(requestContext, seriesList, timeShift, resetEnd=True, alignDST=False):
   """
   Takes one metric or a wildcard seriesList, followed by a quoted string with the
   length of time (See ``from / until`` in the render\_api_ for examples of time formats).
@@ -2480,6 +2480,10 @@ def timeShift(requestContext, seriesList, timeShift, resetEnd=True):
   ending at the current time. If resetEnd is False, will instead draw full range including
   future time.
 
+  Because time is shifted by a fixed number of seconds, comparing a time period with DST to
+  a time period without DST, and vice-versa, will result in an apparent misalignment. For
+  example, 8am might be overlaid with 7am. To compensate for this, use the alignDST option.
+
   Useful for comparing a metric against itself at a past periods or correcting data
   stored at an offset.
 
@@ -2499,6 +2503,27 @@ def timeShift(requestContext, seriesList, timeShift, resetEnd=True):
   myContext = requestContext.copy()
   myContext['startTime'] = requestContext['startTime'] + delta
   myContext['endTime'] = requestContext['endTime'] + delta
+
+  if alignDST:
+    def localDST(dt):
+      return time.localtime(time.mktime(dt.timetuple())).tm_isdst
+
+    reqStartDST = localDST(requestContext['startTime'])
+    reqEndDST   = localDST(requestContext['endTime'])
+    myStartDST  = localDST(myContext['startTime'])
+    myEndDST    = localDST(myContext['endTime'])
+
+    dstOffset = timedelta(hours=0)
+    # If the requestContext is entirely in DST, and we are entirely NOT in DST
+    if ((reqStartDST and reqEndDST) and (not myStartDST and not myEndDST)):
+        dstOffset = timedelta(hours=1)
+    # Or if the requestContext is entirely NOT in DST, and we are entirely in DST
+    elif ((not reqStartDST and not reqEndDST) and (myStartDST and myEndDST)):
+        dstOffset = timedelta(hours=-1)
+    # Otherwise, we don't do anything, because it would be visually confusing
+    myContext['startTime'] += dstOffset
+    myContext['endTime'] += dstOffset
+
   results = []
   if len(seriesList) > 0:
     # if len(seriesList) > 1, they will all have the same pathExpression, which is all we care about.
```

**Comment by deniszh** [comment]
Of course, why not? It's a nice addition and best fix of DST timeShift problem so far.
Please create PR for that - https://help.github.com/articles/creating-a-pull-request/
Then project owners and collaborator can review and merge your patch easy.
