### ISSUE TITLE
Very slow response time on a graphite when working as proxy 

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/graphite-web#1375]
Hi guys.

I have a big platform with 5 graphites . 4 working as backend (graphite02, graphite03, graphite05, graphite07) and the other working as proxy (graphproxy01).

![image](https://cloud.githubusercontent.com/assets/5883405/10843964/7f3887b8-7efc-11e5-9276-9e9326c64f9f.png)

we have this in our local_settings.py in

```
CLUSTER_SERVERS = ["graphite02", "graphite03", "graphite05" , "graphite07"]
```

we are parsing apache logs and graphing response time and these are the results.

![image](https://cloud.githubusercontent.com/assets/5883405/10843523/cb4b67ae-7ef9-11e5-818f-dbb19e7e2a74.png)

As you can see the response time on the graphproxy01 are greater than the sum of the backend graphites, ( in average the response time is 20 times the sum of all backends ) , 900 ms vs (21ms+10ms+10ms+10ms). This big difference makes me think that could be a bug in the code.

We are working with master version commit 8710ff76f0b4571481d295d997a83e4c895dd092
- There is any fix to this problem?
- There is any workaround ( configuration in my local_settings/apache/system)  that can mitigate this behavior.

**Comment by deniszh** [comment]
How do you calculate "graphite response time" graph? I mean, where these data come from?

**Comment by toni-moreno** [comment]
Hi  @deniszh , we are working with  response time in apache log as the data origin (%D in microseconds)
 
```
       LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %D" combined
       CustomLog /var/log/graphite/webapp/access.log combined
```

**Comment by deniszh** [comment]
Graphite nodes also have ```CLUSTER_SERVERS = ["graphite02", "graphite03", "graphite05" , "graphite07"]``` in local_settings.py ?

**Comment by deniszh** [comment]
Do you use Grafana only of PNG rendering too? In your setup only proxy node will run rendering, graphite nodes will run only pickles' rendering.

**Comment by toni-moreno** [comment]
@deniszh graphiteXX nodes doesn't have CLUSTER_SERVER configured.
We are only rendering with grafana (flot) not direct png from graphite.

**Comment by deniszh** [comment]
Then it's quite logical though - proxy need to ask all 4 nodes one by one to get all metrics first, then run all functions and give result to user - and graphite nodes only get simple "gimme-that-metric-from-disk" task.
0.9.14 has "parallel fetch" patch, still need to be ported to master. But in general I see no problem here - 'proxy' node is more (and differently) loaded than normal nodes.

**Comment by toni-moreno** [comment]
@deniszh : I think 50 times slower than the sum of all other times , are too much . 

Anyway I would like to test the "parallel fech" patch in master . There is any plans to merge in master branch also?

Note (off topic): I was pretty sure than 0.9.13 had been the last version previous to 0.10 ( from master) , Is a bad news to me and this make me difficult manage updates from a stable release. :(

**Comment by deniszh** [comment]
@toni-moreno: it depends. I think only 50 times slower is even quite optimistic.
Unfortunately master and 0.9.x is quite different, so, it's quite hard to port that functionality to master. That's a issue for tracking that - https://github.com/graphite-project/graphite-web/issues/1063

And I'm not sure that I understand your note. You are using master already - how stopping of 0.9.x will affect you and "make me difficult manage updates from a stable release"?

**Comment by toni-moreno** [comment]
sorry @deniszh. I meant that the best improvements done in last months seems have been built in the 0.9.X branch before than the master branch. ( https://github.com/graphite-project/graphite-web/pull/1026#issuecomment-66033224) 

Anyway thank you for the fast response:

I will be waiting anxiously this merge

In the meanwhile I would like to tune as fine as I can to mitigate this strange behavior.

* There is any way to limit response time if REMOTE_READER_CACHE_SIZE_LIMIT is set to 0 ?
* There is any way to change order to query first CLUSTER_SERVERS and after local CARBONLINK_HOSTS ?
* what kind of tunning could be done to improve the response time?
