### ISSUE TITLE
Incorrect epoch time returned for graphite events

### ISSUE THREAD

**Issue by danielladd** [graphite-project/graphite-web#1383]
I have been playing with graphite events and having them appear in grafana but ran into a weird issue where the graphite/events/get_data calls are returning future epoch times.

I am submitting the event as 

{"what": "Sync Graphiteprod-c02 to Graphiteprod-c01", "tags": "test", "when":1446651976.0}

When I look at the event in the graphite event interface it is showing the correct date/time:

![image](https://cloud.githubusercontent.com/assets/8699208/10946486/80101c94-82f0-11e5-9d9b-3997fb88c8a0.png)

But when grafana makes calls to the event API it is returning a future date/time:

[
  {
    data: "",
    what: "Sync Graphiteprod-c02 to Graphiteprod-c01",
    when: 1446669976,
    id: 15,
    tags: "test"
    }
]

This is causing grafana to put annotations in the incorrect place.

**Comment by gwaldo** [comment]
What timezone is your server set to?

**Comment by danielladd** [comment]
Both the graphite web server and grafana are set to EST, local_settings.py has the following attribute : TIME_ZONE = 'America/New_York'

**Comment by gwaldo** [comment]
What about your clients?

If you run `date +%s` on the graphite cluster machines, and on your emitter's machines, do they have the same idea of what time it is?

**Comment by danielladd** [comment]
The metrics data within graphite that is being returned to grafana has the correct timestamp, I can verify this by viewing the raw data. It seems to only be for the calls to retrieve events. I also verified that all of the cluster machines have the same idea of what time it is. 

Also, I hope your enjoying Florida.
-Dan Ladd

**Comment by danielladd** [comment]
It looks like this may have been taken care of in a commit last year : 72099b17490a772043d0974d823ec4956759f427

**Comment by deniszh** [comment]
Yep, fixed in  master and upcoming 0.9.14 too

**Comment by danielladd** [comment]
Great! Is there a timeline for the pre-release of 0.9.14 that anyone knows of?

**Comment by gwaldo** [comment]
We don't have a solid time, but here are a couple recent blog posts:

http://obfuscurity.com/2015/10/Graphite-the-Phoenix-Release
and
http://obfuscurity.com/2015/11/Graphite-0.9.14-the-Highlights

P.S. I'm glad that some time and effort has been put into improving what was there, Mr. Ladd.

**Comment by gwaldo** [comment]
@danielladd 0.9.14 is released

http://graphite.readthedocs.org/en/0.9.x/releases/0_9_14.html
