### ISSUE TITLE
Pull docs into their own repo

### ISSUE THREAD

**Issue by obfuscurity** [graphite-project/graphite-web#1387]
It would be lovely to decouple the docs from graphite-web. Every release it seems like I miss something relevant in the docs (release date, version, etc) that forces us to re-tag and re-release. I would :heart: to be able to iterate on the docs without having to roll a new release each time.

I don't know if this is even possible or practical given that the functions doc is built from functions.py. Could this be sourced externally? Looking for expert opinions here.

/cc @graphite-project/committers

**Comment by obfuscurity** [comment]
Although now that I think about it, the real problem tends to be the release notes. Maybe once the website is up we can just move them over there.

**Comment by bitprophet** [comment]
FWIW, while you can never fully escape the "docs/changelogs want to exist in some form in released tarballs" problem, I've found having the canonical versions of that data be the Web-accessible versions helps me care less about minor oopses in the packaged copies.

E.g. http://paramiko.org/changelog.html happens to be generated from https://raw.githubusercontent.com/paramiko/paramiko/master/sites/www/changelog.rst but I routinely find minor mistakes and just patch them so they end up online (and subsequent releases, like a bugfix).

Similarly, I've ended up posting my docs in per-release-line 'versions' such as "the docs for 1.2.x" ([example](http://docs.fabfile.org/en/1.8/) - an older release line that can still sometimes get updates) so I don't have to worry as much about version 1.2.3's docs having some stupid inaccuracy for all time.

(This approach works best when paired with said reliable, canonical changelog, plus remembering to use `.. versionadded::` / `.. versionchanged::` directives [no, I don't always myself, sigh] so a user can quickly figure out if 1.2.3 has that bugfix he's after or if it was added in 1.2.5, etc.)
