### ISSUE TITLE
graphite.wsgi.example no longer adds installation to the sys.path

### ISSUE THREAD

**Issue by movermeyer** [graphite-project/graphite-web#1388]
On. 0.9.x branch:

While trying to set up a graphite using the default configs:

  1. [conf/graphite.wsgi.example](https://github.com/graphite-project/graphite-web/blob/0.9.x/conf/graphite.wsgi.example)
  1. [examples/example-graphite-vhost.conf](https://github.com/graphite-project/graphite-web/blob/0.9.x/examples/example-graphite-vhost.conf)

I get an error, as the code is unable to find the Graphite files:

    [Mon Nov 09 19:27:27 2015] [error] ImportError: No module named graphite.logger
    [Mon Nov 09 19:27:27 2015] [error] mod_wsgi (pid=336): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
    [Mon Nov 09 19:27:27 2015] [error] mod_wsgi (pid=336): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
    [Mon Nov 09 19:27:27 2015] [error] Traceback (most recent call last):
    [Mon Nov 09 19:27:27 2015] [error]   File "/opt/graphite/conf/graphite.wsgi", line 13, in <module>
    [Mon Nov 09 19:27:27 2015] [error]     from graphite.logger import log
    [Mon Nov 09 19:27:27 2015] [error] ImportError: No module named graphite.logger

This seems to be a result of [this change](https://github.com/graphite-project/graphite-web/commit/adfd8022f08eb7aeae3a852fb77a5888f3fa05c4#diff-23abe09633cc08ec065ca87688ad2ca2) by @deniszh which removed the line:

    sys.path.append('/opt/graphite/webapp')

Is this an expected behaviour, or perhaps through some magic (broken in my environment?) it is supposed to locate the installation directory?

**Comment by deniszh** [comment]
Hmm... I just copied example from master branch, IIRC it's working there w/o problems...
Is adding line above helps with running graphite successfully?

**Comment by movermeyer** [comment]
Just to be clear, I'm using the [0.9.x branch](https://github.com/graphite-project/graphite-web/tree/0.9.x)

Adding in the line:

    sys.path.append('/opt/graphite/webapp')

allows it to work.

I still seem to have other issues, so there might be some confounding issue with my environment.

However, it's not obvious to me how it's expected to find the source in /opt/graphite/webapp without that line.

**Comment by roeezab** [comment]
I got the same error, and adding the line "sys.path.append('/opt/graphite/webapp')" also helped in my case.

**Comment by deniszh** [comment]
Yep, looks like master do not require installation to /opt/graphite, so, that's why it was excluded there. I can do PR but IIRC 0.9.14 is latest 0.9.x release... 
Can we release 0.9.14.1 or 0.9.15 (damn you, semver!) or ...?
@obfuscurity @brutasse ?

**Comment by obfuscurity** [comment]
We can fix it in 0.9.x, but we have no plans to cut a new release from that branch.

**Comment by obfuscurity** [comment]
Marking fixed by #1390.

**Comment by gretel** [comment]
just today i got this issue, but on the `master` branch. seems like no dependency gets loaded at all.
