### ISSUE TITLE
Log message "CarbonLink cache-query for <metric> returned <amount> datapoints" always says "1 datapoints"

### ISSUE THREAD

**Issue by Minnozz** [graphite-project/graphite-web#1392]
While debugging another issue, I noticed that the log message in the title always says "1 datapoints", but I'm pretty sure more datapoints are being returned from carbon-cache. Is the len() here correct?

https://github.com/graphite-project/graphite-web/blob/c542449047d53e7c05d4cc43cfd0e36f9718ca44/webapp/graphite/carbonlink.py#L91

**Comment by obfuscurity** [comment]
I don't see anything wrong with that code. It's easy enough to verify for yourself, just add a print statement to dump `results['datapoints']` or `len(results['datapoints'])`.

**Comment by Minnozz** [comment]
I did not realise we were running an older version of graphite-web (0.9.12). That version indeed has an incorrect log statement: https://github.com/graphite-project/graphite-web/blob/0.9.12/webapp/graphite/render/datalib.py#L141

But this seems to be fixed in HEAD.
