### ISSUE TITLE
IndexError on removeAbovePercentile

### ISSUE THREAD

**Issue by toote** [graphite-project/graphite-web#1394]
I am running the following query: `smartSummarize(removeAbovePercentile(category.subcategory.*.metric, 95), '10min', 'avg')`

It so happens that some of the series from the list, don't have data for every 10 minute timespan which causes the following error:

```html
Traceback (most recent call last):
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 110, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return func(requestContext, *args)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 1466, in removeAbovePercentile
    percentile = nPercentile(requestContext, [s], n)[0][0]
IndexError: list index out of range
```

**Comment by toote** [comment]
From what I can see, this will also happen with the `removeBelowPercentile` function

**Comment by toote** [comment]
Patch to solve the issue:

```patch
1466c1466,1469
<     percentile = nPercentile(requestContext, [s], n)[0][0]
---
>     try:
>       percentile = nPercentile(requestContext, [s], n)[0][0]
>     except IndexError:
>       continue
1495c1498,1501
<     percentile = nPercentile(requestContext, [s], n)[0][0]
---
>     try:
>       percentile = nPercentile(requestContext, [s], n)[0][0]
>     except IndexError:
>       continue
```

**Comment by obfuscurity** [comment]
This will happen for any function that attempts to call an array item explicitly. See https://github.com/graphite-project/graphite-web/issues/1389. There's nothing we can do there to prevent bad data, but it's one of my goals to improve the exception handling / logging.

**Comment by obfuscurity** [comment]
I don't see how `continue` helps here. It's giving you bad data.

**Comment by obfuscurity** [comment]
@toote Sorry if my response was abbreviated. `continue` will certainly bypass the error, but it's my opinion that failing and logging a useful message is more helpful than silently continuing and returning bad data. I'm open to suggestions.

**Comment by toote** [comment]
As far as I know the 95-percentile of an empty set of data is an empty set of data. The `continue` actually implements that behaviour. I would completely agree with the current behaviour (and with your assessment of the `continue` not helping) if there were a way to remove empty series from a seriesList so as to be able to just weed out empty series if one actually wanted that.

**Comment by toote** [comment]
@obfuscurity and I really appreciate how quickly you replied :)

**Comment by obfuscurity** [comment]
Yeah, that's a valid point. Reopening.
