### ISSUE TITLE
Problem pulling metrics from graphite clusters (CLUSTER_SERVERS)

### ISSUE THREAD

**Issue by nicholaskuechler** [graphite-project/graphite-web#1406]
grahpite-web version: 0.9.12

I have graphite clusters in multiple datacenters (aka "regions"), and I'd like to present a unified view of all metrics in a "global" level graphite-web (aka "global").

Architecturally, it looks like this: ![http://i.imgur.com/OCbwnKC.png](http://i.imgur.com/OCbwnKC.png)

Config wise the regional graphite-web nodes look like this: 

``` python
# datacenter 1 (aka a "regional" cluster)
# there is a load balancer in front of the graphite-web nodes,
# with vip: 10.1.1.1
# regional graphite-web node local_settings.py:
CLUSTER_SERVERS = ["10.1.1.10:80", "10.1.1.20:80"]
```

And the "global" graphite-web node:

``` python
# "global" graphite-web local_settings.py, using the IP address of the
# load balancer vip for the "regional" clusters
CLUSTER_SERVERS = ['10.1.1.1:80', '10.2.2.1:80']
```

Note: I'm not running carbon on any of the graphite-web nodes so the CARBONLINK_HOSTS is commented out.

The regional cluster's graphite-web pulls metrics from carbon-cache fine, but the global graphite-web is unable to pull metrics. I see global graphite-web making connections to the cluster's graphite-web with this query: "GET /metrics/find/?local=1&format=pickle&query=infrastructure.%2A" but that query returns 0 results.

When I run that query against one of the carbon-cache nodes in the regional cluster, the query works fine.

It seems like the regional graphite-web nodes are not honoring CLUSTER_SERVERS for the query above.

I would expect the cluster-level graphite-web nodes to query the CLUSTER_SERVERS on query "GET /metrics/find/?local=1&format=pickle&query=whatever" but it appears to only be looking locally, and since there are no local metrics on the grahpite-web nodes, it's seeing 0 results.

**Comment by deniszh** [comment]
That's true, when server makes queries to CLUSTER_SERVERS it will always add "local=1" to query, to make local requests only, for avoiding loops. AFAIK it's mandatory and can't be changed. 
But I'm still not really understand your setup and why you need "recursive" cluster requests...

**Comment by bmhatfield** [comment]
It took me a moment to understand this, but yes: graphite-web is only designed to be at most a 2-tier system (the "query node" and the "cluster nodes"), not a 3-tier system ("query" aka your global view, "regional" aka mid-tier query-node, "cluster" aka your storage-only nodes).

As a stop-gap, I believe Grafana can query multiple graphite clusters, but I am not sure: http://docs.grafana.org/datasources/graphite/

**Comment by nicholaskuechler** [comment]
A bit behind the reasoning: I have a number of regions, some of which are quite large in terms of the number of nodes in the region, and we're collecting a lot of metrics, which is the reason for multiple regional graphite clusters. We have a lot of tooling that dumps metrics in or pulls metrics out, such as diamond, nagios plugins, custom tools, etc. The number of nodes and the amount of metrics, as well as not having a lot of data traverse between regions, has necessitated creating graphite clusters in each region.

We have some dashboards we use for a global view and some other tools that operate on global metrics. The "easy mode" would be to set up a graphite-web node that's able to present the unified view of metrics from all regions.

As a work-around, I can add the regional level carbon-cache nodes to my "global" graphite-web, and that works, but I'm not sure it's an ideal solution. For example, config management becomes more difficult when I add / remove carbon-cache nodes, it's a little bit more difficult to take advantage of the memcached the regional graphite-web nodes are using, I lose the advantages of the load balancer, etc.

It might be nice if local=1 was a configurable setting. In my case, my regional graphite clusters will never have a different region configured in CLUSTER_SERVERS, so the recursive requests would be avoided.

**Comment by ravibhooshan** [comment]
I have similar setup and achieved unified web console using Grafana.

**Comment by obfuscurity** [comment]
While working on the book, I remembered this issue and tested/verified the behavior for myself. I feel strongly that we should add a flag to allow the user to override this behavior from the layer performing the remote fetch. It seems like an easy addition; I'll take a stab as time permits unless someone beats me to it.

**Comment by obfuscurity** [comment]
oh and @tomc603, sorry Tom. :wink:

**Comment by xneo64** [comment]
For what it's worth, we needed this same requirement, and got around it by using this config in the apache graphite configuration:

```
  #Rewrite any query local=1 to local=0 and resend to url matching engine ([PT])
  RewriteEngine on
  RewriteCond %{QUERY_STRING} ^(.*)local=1(.*)$
  RewriteRule ^/(.*) /$1?%1local=0%2 [PT]
```

@obfuscurity certainly support implementing this as a configurable parameter.

**Comment by kalebwalton** [comment]
Any chance of this being implemented? Although it gives central, unified access to data - Grafana does not allow for federated querying across 'regions'.

**Comment by xyntrix** [comment]
For what it's worth, I have a hack for Graphite 0.9.16 (and 0.9.15) that turns a graphite-web installation into a federated render node, allowing for a multi-region  / mutilple-tier cluster approach.

This enables one to have a setup where federated1 will fetch concurrently data from datacenter1 and datacenter2, without additional changes to datacenter1/datacenter2.

The patch:

https://gist.github.com/xyntrix/93d536089d0e992fddf8a9ec9233a074

I have not explored this feature for Graphite 1.0 yet.. and there's several design improvements that could be made (such as a configurable enabled/disable flag).

We use this today by dropping a graphite-web + memcached install along-side each Grafana server, that allows for a universal Grafana configuration to federate n-many graphite clusters.  

One huge benefit of this approach is migrating graphite metrics storage from one cluster to another, without having to modify caller queries or dashboards (as long as the metric paths do not change).

**Comment by DanCech** [comment]
The only real change here is to not pass the local=1 flag when dispatching remote find and fetch requests, 1.x will handle this with nothing more than addition of a config flag to toggle the local param to 0 in the remote finder and reader.

The config flag is needed to avoid creating potential loops in a scenario where cluster servers might refer to each other (eg if you have an http load balancer in front of a cluster where host a has CLUSTER_SERVERS=b,c, b has a,c and c has a,b).

**Comment by xyntrix** [comment]
Probably doesn't matter for 1.x, but in 0.9.x, I couldn't pass local=0 and have it be pickleformat with some of the endpoints -- can't remember if this was /find or /expand or which..  but not all the endpoints supported pickle + local=0, so where jsontree + local=0 did work, I used that and aligned with some of the jsontree key names.

**Comment by xneo64** [comment]
@DanCech has this config flag for letting local=1 or local=0 been implemented in 1.0.x? Couldn't find it anywhere in the sample config.. 
Is there any plan to implement this in the near future?

**Comment by DanCech** [comment]
It hasn't been implemented, I can maybe look at it next week.

**Comment by deniszh** [comment]
Do you still have time to check it, @DanCech, or should I move to post-1.1 improvements?

**Comment by DanCech** [comment]
I'm working on a patch to add support for msgpack as an alternative to pickle (since my testing shows it's up to 10x faster for large payloads), and should be able to roll a local toggle into that also since I have to add the capability to specify that msgpack should be used instead of pickle.  I'm hoping to have that ready for review tomorrow, made some good headway today but still have some more work to do.

**Comment by deniszh** [comment]
Cool, closing this.
Thanks, @DanCech! 
@xneo64 - you can check the latest master - or wait to 1.1.0, which should be released soon.
