### ISSUE TITLE
I haven't bought you a beer.

### ISSUE THREAD

**Issue by ChrisHeerschap** [graphite-project/graphite-web#1419]
Just wanted to say that Graphite is so damn good. Every time I think "I'll bet I can't do _____" I read through the docs, experiment, and find that I can. This has resulted in some hellacious target= lines, but with one exception I've figured out how to do _everything_ I've wanted. Very few software packages do that - I'm fussy.

So, the only issue I have with Graphite is that I haven't bought you a beer to say thank you.

**Comment by obfuscurity** [comment]
:beers::heart::beers:

**Comment by ChrisHeerschap** [comment]
Seriously, if you find yourself in the Philly area, lemme know. Offer stands.
