### ISSUE TITLE
Functions page not being rendered in RTD

### ISSUE THREAD

**Issue by gwaldo** [graphite-project/graphite-web#1428]
[Functions Docs page](http://graphite.readthedocs.org/en/latest/functions.html) is not rendering properly.  The doc page is in `/docs/functions.rst`, which should pull in the doc info from `webapp/graphite/render/functions.py`, but that is not rendering

**Comment by ChrisHeerschap** [comment]
Saw the same thing this morning. I live on this page, constantly referring to it, and shared it with coworkers today only to discover the functions weren't there. I know they were on Friday!

**Comment by gwaldo** [comment]
Thanks, @chrisheerscap, that information is actually helpful. We didn't know when it had stopped working.

**Comment by ChrisHeerschap** [comment]
Well, I was working on perfecting my Graphite graphs until about 4pm EST on Friday (12/4/15), if that helps narrow it down more. I noticed it missing around 9-10am EST this morning.

**Comment by bergquist** [comment]
I miss this wonderful page! Full of knowledge and inspiration!

**Comment by AnthonySteele** [comment]
List of functions as per here docs/functions.rst and at http://graphite.readthedocs.org/en/latest/functions.html#list-of-functions is empty.

**Comment by obfuscurity** [comment]
@AnthonySteele Was it not clear that's the whole point of this issue? :stuck_out_tongue_closed_eyes:

**Comment by AnthonySteele** [comment]
@obfuscurity was it not clear, that's just a +1 on the issue?

**Comment by brutasse** [comment]
It's back! http://graphite.readthedocs.org/en/latest/functions.html

**Comment by obfuscurity** [comment]
:boom::heart::sparkles::bow:

**Comment by gwaldo** [comment]
:heart:

**Comment by JeanFred** [comment]
Yay!

**Comment by ChrisHeerschap** [comment]
Thank you!
