### ISSUE TITLE
proxy apache2 to render on icingaweb2

### ISSUE THREAD

**Issue by claenjoy** [graphite-project/graphite-web#1438]
the message I get is "The server refused the connection."
icinga2 - 2.4.1-1~debmon80+1
graphite-web : 0.9.12+debian-6

etc/icingaweb2/modules/graphite/config.ini

"[graphite]
metric_prefix = icinga
base_url = http://localhost:8000/render?"

localhost:8000 works fine !

How can I setup a proxy on apache2 ?

**Comment by obfuscurity** [comment]
Sorry, but we don't have the resources or expertise to support Icinga's particular configuration of Graphite. Please contact Icinga support.
