### ISSUE TITLE
javascript for opening the tree in a specific folder

### ISSUE THREAD

**Issue by roeezab** [graphite-project/graphite-web#1440]
Hi,
Is there a javascript code for opening the metrics tree in a specific folder?
For example:
Tree.goTo("metrics.all_servers.server1")

Thanks,
Roee.

**Comment by obfuscurity** [comment]
No, there's nothing built-in that I'm aware of. There _may_ be something in ExtJS to help with this, but it's more likely that you'll need to construct the JS manually.

**Comment by roeezab** [comment]
I'll check it out. Thanks!

**Comment by roeezab** [comment]
In case someone will need it, I wrote this piece of code that goes into [webapp/content/js/browser.js](https://github.com/graphite-project/graphite-web/blob/master/webapp/content/js/browser.js):
```javascript
function openTree (currentPlaceInTree, path) {
    if (path.indexOf(".") != -1) {
      var nextPlaceInTree = currentPlaceInTree.findChild('text',path.substr(0,path.indexOf(".")));
      nextPlaceInTree.ensureVisible();
      nextPlaceInTree.expand(false, true, function(){openTree(nextPlaceInTree, path.substr(path.indexOf(".") + 1));});
    } else {
      var nextPlaceInTree = currentPlaceInTree.findChild('text',path);
      nextPlaceInTree.ensureVisible();
      nextPlaceInTree.expand();
    }
}

function gotoPath (path) {
  Browser.panel.activate(0);
  Browser.trees.graphite.expand(false, true, function(){openTree(Browser.trees.graphite, path);});
}
```

In order to open the tree, the gotoPath function should be used like that:
```javascript
gotoPath('dc1.all_servers.serverX');
```
In my case, I replaced the search in Graphite to go to the tree, instead of showing the metric in the composer. So in the handleSearchResponse function I replaced the following line:
```javascript
li.innerHTML = "<a href=\"javascript: Composer.toggleTarget('" + item + "');\">" + item + "</a>";
```
with this one:
```javascript
li.innerHTML = "<a href=\"javascript:void(0)\" onclick=\"gotoPath('" + item + "');\">" + item + "</a>";
```
