### ISSUE TITLE
HoltWinters forecast does not forecast.

### ISSUE THREAD

**Issue by fuqqer** [graphite-project/graphite-web#1445]
The holtWinters forecast function does not show predictive values. It only shows "would have forecast values" for already existing time periods. It should display the predicted value (X seconds into the future) based on the size of the sample selected.

**Comment by obfuscurity** [comment]
Graphite does not support datapoints in the future.

**Comment by drawks** [comment]
Yeah the typical usecase for the holtwinters stuff is to run it against past periods and use it to draw a trend line over the current period so you can see over/undershoot

**Comment by fuqqer** [comment]
Well then it shouldn't be called a "forecast"?

Maybe this should be a feature request to display the predicted (at the current time) over/under of the forecast given a window of past data?

**Comment by drawks** [comment]
the semantic argument is silly, it is called forecast because that is the name of the mathematical model used.

**Comment by anayrat** [comment]
:+1:
