### ISSUE TITLE
graphite-web shows no data and no saved graphs

### ISSUE THREAD

**Issue by puddean** [graphite-project/graphite-web#1448]
i just installed graphite and statsd to monitoring the linux server
but i don't know why when i go to the address i got nothing in the page.

here are some of my config files
/opt/graphite/webapp/graphite/local_settings.py: (just sentences i added)

DATABASES = {
    'default': {
        'NAME': 'graphite',
       	'ENGINE': 'django.db.backends.mysql',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '192.168.**.*',
        'PORT': '3306'
    }
}

i don't change carbon.conf

and i'm sure i run the carbon-cache.py successfully.

can somebody find where's the problem?please help me !T T

**Comment by ravibhooshan** [comment]
'HOST': '192.168.*.', - is it correct.

I am not sure about statsd config , are you running carbon-relay.
Also please check whetehr you have whisper directory created or not. carbon user should own this directory.

**Comment by puddean** [comment]
thanks!
i've figured that out last week.
The problem is that i forgot to edit /etc/graphite-web/local_settings.py. Under #Filesystem Paths# part the Data directory was not right.
thanks for noticing and answering my question~^^
