### ISSUE TITLE
Issue in data

### ISSUE THREAD

**Issue by ravibhooshan** [graphite-project/graphite-web#1451]
HI,
I am using below storage schema for most of my incoming data.
10s:25h,1m:8d,5m:35d,1h:390d,1d:7y

One of my application is sending data at irregular interval and getting processed without any issue. But one data point in Archive-3  is having a scientific value and this is not letting us to draw a graph beyond that time point.

Can anyone please point me what is wrong I am doing or is it a bug. I am using Graphite 0.9.12.

I have many other application which are sending data at irregular time but never had this type of problem.

I tried to update the value using whisper-update(), but didn't work.

Any help suggestions are welcome.

Thanks,
Ravi Bhushan

**Comment by obfuscurity** [comment]
What do you mean by `one data point in Archive-3 is having a scientific value`?

**Comment by ravibhooshan** [comment]
Belos is result from whisper-dump. See the value for 3rd datapoint.

230: 1450440000, 15.047333333333332561210227140691131
231: 1450443600, 13.88779166666666675666874652961269
232: 1450447200, -1.0000000000000000438458430450761974e+47
233: 1450450800, 17.735624999999998863131622783839703
