### ISSUE TITLE
remote_storage.FindRequest harmfully swallows exceptions

### ISSUE THREAD

**Issue by drawks** [graphite-project/graphite-web#1454]
It looks like remote_storage.FindRequest swallows exceptions by design. While troubleshooting some remote rendering stuff that I thought should work I found and removed the exception eating behavior:

https://github.com/graphite-project/graphite-web/blob/0.9.15/webapp/graphite/remote_storage.py#L36

Which then opened the door to a few underlying bugs, the 0.9.15 version doesn't have "graphite.intervals" which makes the unpickler barf:

https://github.com/graphite-project/graphite-web/blob/0.9.15/webapp/graphite/util.py#L104
https://github.com/graphite-project/graphite-web/blob/0.9.15/webapp/graphite/util.py#L130

In my case I was trying to get 0.9.15 to talk to some older instances for federation so missing exceptions also masked that the returned storage objects had some of their key names changes between versions. "is_leaf" became "isLeaf" and "path" became "metric_path".

I suppose I shouldn't expect cross version compatibility here, although it is kind of bogus to break apis in minor revisions; but the main point is that we should not eat unhandled exceptions.

**Comment by obfuscurity** [comment]
I assume you mean _should **not** eat_? :smile:

**Comment by drawks** [comment]
#1455 Should address this issue...

**Comment by mleinart** [comment]
I'm a bit confused.. Are you sure youre running 0.9.15 across the board? It sounds like you have a version running master branch trying to talk to 0.9.x branch. afaik the is_leaf=>isLeave et al changes have always only been between 0.9.x and master

**Comment by drawks** [comment]
I am using cross version nodes, however the compatibility between versions was trivial to implement AND the pattern by which the exception was silently swallowed is bad practice. So, two birds with one stone. This PR corrects for the exception handling and opens the door for cross version metrics/find which allows for arbitrary federation between dissimilar versions.
