### ISSUE TITLE
Attempting to unpickle unsafe module collections

### ISSUE THREAD

**Issue by mrh666** [graphite-project/graphite-web#1456]
Hi there,

I've got this exception, actually a lot of them (similar to #608 ) with graphite-web 0.9.15:

```
Wed Jan 20 23:33:19 2016 :: Exception Caught
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 231, in fetchData

  File "/opt/graphite/webapp/graphite/render/datalib.py", line 140, in query
    return connection
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 166, in send_request
    serialized_request = pickle.dumps(request, protocol=-1)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 181, in recv_response
    else:
  File "/opt/graphite/webapp/graphite/util.py", line 108, in loads

  File "/opt/graphite/webapp/graphite/util.py", line 97, in find_class
    # http://nadiana.com/python-pickle-insecure
UnpicklingError: Attempting to unpickle unsafe module collections
```

Any ideas?

**Comment by deniszh** [comment]
As you can see in https://github.com/graphite-project/graphite-web/blob/fe04c9e64d53057877a25cbc78edd70dc8127759/webapp/graphite/util.py#L161-L167 collections class is included in PICKLE_SAFE variable, so, it should unpickle safely.
So, my idea is that you're not running 0.9.15
Could you please check your local webapp/graphite/util.py file - does it looks similar?

**Comment by mrh666** [comment]
No it doesn't looks similar!

pip output is:

```
[root@graphitecarbon-172 graphite]# pip list | grep graphite-web
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
graphite-web (0.9.15)
```
But file webapp/graphite/util.py is different:

```
  try:
    defaultProfile = Profile.objects.get(user=defaultUser)
  except Profile.DoesNotExist:
    log.info("Default profile does not exist, creating it...")
    defaultProfile = Profile(user=defaultUser)
    defaultProfile.save()

# This whole song & dance is due to pickle being insecure
# The SafeUnpickler classes were largely derived from
# http://nadiana.com/python-pickle-insecure
# This code also lives in carbon.util
if USING_CPICKLE:
  class SafeUnpickler(object):
    PICKLE_SAFE = {
      'copy_reg': set(['_reconstructor']),
      '__builtin__': set(['object', 'list']),
      'graphite.intervals': set(['Interval', 'IntervalSet']),
      'graphite.render.datalib': set(['TimeSeries']),
      'collections': set(['deque']),
    }

    @classmethod
    def find_class(cls, module, name):
      if not module in cls.PICKLE_SAFE:
        raise pickle.UnpicklingError('Attempting to unpickle unsafe module %s' % module)
      __import__(module)
      mod = sys.modules[module]
      if not name in cls.PICKLE_SAFE[module]:
        raise pickle.UnpicklingError('Attempting to unpickle unsafe class %s' % name)
      return getattr(mod, name)
```

Is there is any chance I still have old files during the upgrade (pip install upgrade graphite-web)?
How can I properly upgrade or fully remove it and install it again?

**Comment by deniszh** [comment]
Please show output of 
```
pip show -f graphite-web
```

**Comment by mrh666** [comment]
https://gist.github.com/mrh666/0ea1eb1f195d94bac2ad

**Comment by deniszh** [comment]
```Location: /usr/lib/python2.6/site-packages```
So, it's in under /usr/lib/python2.6/site-packages and not in /opt/graphite
Try to reinstall it in /opt/graphite:
```
pip uninstall graphite-web
pip install graphite-web --install-option="--prefix=/opt/graphite" --install-option="--install-lib=/opt/graphite/webapp"
```
Maybe you need to do the same for carbon and whisper too.

**Comment by mrh666** [comment]
deniszh, thank you!
"pip uninstall graphite-web" <- sure doesn't delete files under  /opt/graphite/webapp, so I removed them manually. 
Then "pip install graphite-web --install-option="--prefix=/opt/graphite" --install-option="--install-lib=/opt/graphite/webapp" did the clean install. All those exceptions are gone after "service httpd restart".

**Comment by deniszh** [comment]
yw
Not sure why default install not going to /opt/graphite
pip is odd sometimes, and developing quite fast, though.
