### ISSUE TITLE
value list sorting is inconsistent with shell brace expansion

### ISSUE THREAD

**Issue by ChrisHeerschap** [graphite-project/graphite-web#1457]
Using brace expansion in the shell, the order of the provided arguments is preserved:

```
$ echo {b,c,a} 
b c a
```

Combining this with wildcards does not change the order:

```
$ echo *-{b,c,a}
1-b 1-c 1-a
```

In 0.9.12, this was honored by Graphite-web, but in 0.9.15, sorting is applied to all wildcarded metrics, including value lists, making the value list function inconsistently with shell brace expansion. This could lead to confusion as they look identical, so many users will expect them to act identically - which they did until 0.9.15.

In 0.9.12, wildcards sorted as expected:

```
servers.host.cpu-*.percent-*
```

would expand sorted by CPU, then by the metrics matching percent-*. This remains unchanged in 0.9.15. However using list expansion:

```
servers.host.cpu-*.percent-{user,idle,system}
```

would expand to:

```
servers.host.cpu-0.percent-user
servers.host.cpu-0.percent-idle
servers.host.cpu-0.percent-system
servers.host.cpu-1.percent-user
servers.host.cpu-1.percent-idle
...
```

This preserved the order specified in the value list, user, idle, system. This was consistent and predictable.

In 0.9.15, however, this has been changed so that all of the metrics are sorted, and it now returns:

```
servers.host.cpu-0.percent-idle
servers.host.cpu-0.percent-system
servers.host.cpu-0.percent-user
servers.host.cpu-1.percent-idle
servers.host.cpu-1.percent-system
...
```

Using the order of values inside a value list to control the way they display is something I've been using and relying on for a while, but the most recent application is creating stacked graphs of CPU usage:

```
aliasSub(aliasByNode(stacked(servers.host.cpu-*.percent-{system,nice,steal,interrupt,softirq,wait,user,idle}),3),'percent-',' ')
```

This returns a stacked graph of the CPU percentages for each CPU on the system, and by assigning consistent colors, it's easy to see differentiate different CPU activity types by color. This allows me to view all the stats for all the CPUs installed in a system from one graph.

**One CPU showing heavy user activity with a spike of wait at midnight**
![one-cpu](https://cloud.githubusercontent.com/assets/3670938/12494543/cce8c462-c058-11e5-8dd2-608ba26cc3ba.png)

**Two CPU system showing mostly idle with a small spike in user and system activity around 1:30am**
![two-cpu](https://cloud.githubusercontent.com/assets/3670938/12494560/eac74d00-c058-11e5-8853-325162567b53.png)

With the default sorting changed to include value lists in 0.9.15, this is now broken, and I can't specify the order any way other than not using value lists, and manually generating the list of targets, which is something that would have to be scripted with an outside tool, something I've not had to do previously.

I have found a workaround for this particular challenge in 0.9.15 - but it's just a matter of luck as CPU idle is alphabetically first, resulting in "inverted" CPU graphs:

**Four cpu system mostly idle, inverted graphs.**
![localhost](https://cloud.githubusercontent.com/assets/3670938/12494981/184890de-c05b-11e5-904a-5968bf804c66.png)

This graph relies on the lucky result of "idle" being alphabetically first, and if there was a way to reverse the order of metric sorting, it would be possible to get the original graphs back, but I don't see any way to control sort order in the [documentation on sort functions](https://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.sortByMaxima)

I would make the argument that the old method of sorting was more consistent and predictable than the new method, since the new method results in no control over the sorting. Since new sort features have been added at the same time that could be used to get the same functionality, I don't agree with making the sorting mandatory. If the sorting is mandatory, I'd like to request more options to control it. Still, ignoring the consistency with how the shell handles brace expansion in the visually identical value lists will likely cause confusion for any users familiar with that function in the shell.

**Comment by ChrisHeerschap** [comment]
The [current documentation on value lists](http://graphite.readthedocs.org/en/latest/render_api.html#paths-and-wildcards) infers the old usage, as well, listing {user,system,iowait} which would now be returned as "iowait system user".

**Comment by deniszh** [comment]
IIRC graphite never guaranteed any metric order. It's really hard to say from where sorting came out suddenly in 0.9.15, code change between 0.9.12 and 0.9.15 is really huge...

**Comment by lildude** [comment]
We encountered this same issue when upgrading from 0.9.12 to 0.9.15.

Today I did a lot of digging into this and found what I believe to be the cause. 

Things were all tickety-boo in 0.9.x until https://github.com/graphite-project/graphite-web/pull/1026 which made its way into 0.9.13-pre1.  The pertinent change here is https://github.com/graphite-project/graphite-web/commit/5519e5903c3e148d5d86b129dfd668613011cd87 which sorts the final data passed to `fetchData()`.

Things were then refactored and changes made to handle multiple `TimeSeries` data after a cluster partition in https://github.com/graphite-project/graphite-web/pull/1352 which involved changing the `seriesList` from a list (which retains order) to a dictionary (which does not retain order) in https://github.com/graphite-project/graphite-web/commit/3a7e1a88cae0a7af5e850bbf4153d237428cd8cb, which is also sorted on return as it was in 0.9.13-pre1.

Removing the sorting on the return value at https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/datalib.py#L478 isn't sufficient to solve the issue as dictionaries don't preserve order.

In order to preserve order, whilst still retaining the benefits of using the dictionary, the `sorted` at https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/datalib.py#L478 needs to be removed and then rely on something like `collections.OrderedDict()` to retain the order of elements as they're added.

The simple solution I found which does the trick for us is:

```
--- a/webapp/graphite/render/datalib.py
+++ b/webapp/graphite/render/datalib.py
@@ -17,6 +17,7 @@ import struct
 import time
 import threading
 import Queue
+import collections
 from django.conf import settings
 from graphite.logger import log
 from graphite.storage import STORE, LOCAL_STORE
@@ -365,7 +366,7 @@ def fetchRemoteData(requestContext, pathExpr, usePrefetchCache=settings.REMOTE_P
 
 # Data retrieval API
 def fetchData(requestContext, pathExpr):
-  seriesList = {}
+  seriesList = collections.OrderedDict()
   (startTime, endTime, now) = _timebounds(requestContext)
 
   dbFiles = [dbFile for dbFile in LOCAL_STORE.find(pathExpr)]
@@ -475,7 +476,7 @@ def fetchData(requestContext, pathExpr):
 
   # Stabilize the order of the results by ordering the resulting series by name.
   # This returns the result ordering to the behavior observed pre PR#1010.
-  return [ seriesList[k] for k in sorted(seriesList) ]
+  return [ seriesList[k] for k in seriesList ]
 
 
 def mergeResults(dbResults, cacheResults, lowest_step):
```

This takes us from the "inverted" graphs we see with 0.9.15:

![what](https://cloud.githubusercontent.com/assets/65057/21676103/b4c089ca-d334-11e6-82af-74a02b237853.png)

... to the correct graphs we see with 0.9.12 ...

![screen shot 2017-03-21 at 11 16 05](https://cloud.githubusercontent.com/assets/627280/24145159/d87fb768-0e27-11e7-8623-29d2434c3226.png)

My 2c: if sorting is desired, I think it should probably be at the user's request using the [`sortByName`](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.sortByName) function rather than being implemented somewhere that they can't override. 

I've not opened a PR for this yet as I may be missing something obvious. Let me know if I'm not and if not, if you want a PR for this.

**Comment by deniszh** [comment]
As a comment above said sort is needed because 'Stabilize the order of the results by ordering the resulting series by name. This returns the result ordering to the behavior observed pre PR#1010'. 
Without sort, results will be inconsistent during refreshes.
Am I right, @bmhatfield ?

**Comment by lildude** [comment]
From what I can see, there wasn't any sorting _before_ https://github.com/graphite-project/graphite-web/pull/1010 either, though I've not dug that far back. The function itself was using a list at the time so any order provided would have been honoured.

> As a comment above says sort is needed because 'Stabilize the order of the results by ordering the resulting series by name. This returns the result ordering to the behavior observed pre PR#1010'.

Without any context about why that comment was added and what the behaviour was before, this sounds like a perfect candidate for `sortByName()` 😉

**Comment by deniszh** [comment]
@lildude :
`sortByName()` will not solve the problem if you need to wrap every graph on it. :)
I'm suspecting that sort is connected with getting a consistent list of metrics during parallel fetches. So, if I should choose - sorted and consistent list and unsorted inconsistent - I'll choose first. It's a pity that we're changed sort behavior in 0.9.15, but I do not think that we need to change it back. 
If you find an optional way how to enable previous behavior (with some config variable in local_settings.py) then we can include that in upcoming 1.0.0 (maybe in 0.9.16 too, but I'm still not sure that we should release it, maybe just left it as a patched `0.9.x` branch on Github)

**Comment by ChrisHeerschap** [comment]
Having the ability to sort is good, having the ability to control the sorting is wonderful, and being able to pass an arbitrary order (as happens with brace expansion in the shell) and have it be preserved would be divine. Especially when dealing with stacked graphs, I doubt any type of sorting would work for all instances, so having the ability to preserve an arbitrary ordering (the functionality in 0.9.12) is kinda key.

**Comment by deniszh** [comment]
Hello @ChrisHeerschap and @lildude ,
I'm understanding your concerns, but as I said before we're not going to revert to old behavior and I mostly interested in good performance and stable clustering more. We can include some code which can _optionally_ revert to old behavior, not sure if it's possible though.

**Comment by lildude** [comment]
I hear you @deniszh and it makes good sense.

With your comments in mind, do you have a suggestion on how people would go about getting the old desired appearance from deliberately ordered keys when creating stacked graphs that results in an intuitive graph as seen in 0.9.12 with 0.9.15 and later?

I think if we can come up with a good method then nothing really needs to change from a graphite perspective just how the user "configures" the graph.

I also think it's worth documenting that graphite doesn't guarantee an order, or that it does now order regardless of whether you use the `sortByName()` function or not, else we'll be back here in the future if it's decided sorting isn't the best approach.

**Comment by lildude** [comment]
@deniszh Thinking about this further...

> As a comment above says sort is needed because 'Stabilize the order of the results by ordering the resulting series by name. This returns the result ordering to the behavior observed pre PR#1010'.
> Without sort, results will be inconsistent during refreshes.

If you configure the graph using an explicit order, whether clustered or not, it is _already_ "sorted" - you did it manually yourself rather than relying on a computer to do it - so further sorting shouldn't be needed.

Wouldn't switching to using an ordered dictionary so order in == order out negate the need for additional sorting and thus things would work consistently with parallel cluster fetches too? (I don't have a cluster setup so can't test this myself).

**Comment by ChrisHeerschap** [comment]
> If you configure the graph using an explicit order, whether clustered or not, it is already "sorted" - you did it manually yourself rather than relying on a computer to do it - so further sorting shouldn't be needed.

If I configured the graph with a bunch of individual metrics, sure... but this defeats the entire point of using wildcards and brace expansion in targets.

As it stands in 0.9.12, I can create a stacked graph in the order that I want using just one target and the braces. In the case of a stacked CPU graph on a 16 core box, that's still just one target. To do it the way you're saying and make an explicit target for each metric would require 128 individual targets, unless there's some other way I haven't figured out. I've spent a whole bunch of time reading through the 0.9.15 docs to figure out how to create the graphs I want in the order I want without resorting to an individual graph for each metric and so far have been unsuccessful.

This is one target in 0.9.12 and impossible in 0.9.15 without 192 individual targets.
![screen shot 2017-03-28 at 10 47 22 am](https://cloud.githubusercontent.com/assets/3670938/24411466/fb0cd172-13a3-11e7-8cab-d7d308cb219a.png)

If there's something I'm missing that would make that possible in 0.9.15, I'd love to know.

**Comment by ChrisHeerschap** [comment]
> If you configure the graph using an explicit order, whether clustered or not, it is already "sorted" - you did it manually yourself rather than relying on a computer to do it - so further sorting shouldn't be needed.

If I configured the graph with a bunch of individual metrics, sure... but this defeats the entire point of using wildcards and brace expansion in targets.

As it stands in 0.9.12, I can create a stacked graph in the order that I want using just one target and the braces. In the case of a stacked CPU graph on a 16 core box, that's still just one target. To do it the way you're saying and make an explicit target for each metric would require 128 individual targets, unless there's some other way I haven't figured out. I've spent a whole bunch of time reading through the 0.9.15 docs to figure out how to create the graphs I want in the order I want without resorting to an individual graph for each metric and so far have been unsuccessful.

This is one target in 0.9.12 and impossible in 0.9.15 without 192 individual targets.
![screen shot 2017-03-28 at 10 47 22 am](https://cloud.githubusercontent.com/assets/3670938/24411754/9e5b7824-13a4-11e7-89ea-e986e93a5f9a.png)

If there's something I'm missing that would make that possible in 0.9.15, I'd love to know.

**Comment by lildude** [comment]
> If I configured the graph with a bunch of individual metrics, sure... but this defeats the entire point of using wildcards and brace expansion in targets.

Oooo, and there's something I didn't consider: mixing both a wildcard and an explicit braces list. That said, I'd be interested to know if the graphs display properly if you apply my [patch](https://github.com/graphite-project/graphite-web/issues/1457#issuecomment-288130519) to 0.9.15.

> If there's something I'm missing that would make that possible in 0.9.15, I'd love to know.

[Ditto](https://github.com/graphite-project/graphite-web/issues/1457#issuecomment-289383850).
