### ISSUE TITLE
Ability to add/delete metric to a merged dashboard graph

### ISSUE THREAD

**Issue by nhooey** [graphite-project/graphite-web#146]
Currently you can only replace an existing metric from a Graphite Dashboard graph.

You should be able to easily add/delete metrics from the context menu.

If you want to add one, you have to make a new graph and merge it with an existing one. Deleting a graph is way more difficult, requiring breakup of a graph and then merging of only the metrics you want. 

Doing a graph breakout pegs the CPU in Google Chrome indefinitely on my machine, so the current solution doesn't work.

**Comment by markhu** [comment]
Is this even possible? 
> it's silly that the basic operations of adding and removing lines from a graph is so roundabout and undiscoverable.

**Comment by deniszh** [comment]
It seems that everybody using alternative dashboards, and nobody really care enough to provide that functionality. As far as I understand, good amount of code needs to be written. For simple dashboards it's not needed too, so...

**Comment by garrettwilkin** [comment]
:+1: I would love to have this feature while exploring my data.

**Comment by SEJeff** [comment]
Unfortunately I don't think this is a graphite change so much as a big carbon change. Also, it would require backend changes to both carbon's pluggable back ends and graphite-web's pluggsble back ends.

I suspect that for this to be merged, someone will have to implement it and send us a pull request. Not trying to be a dick but I'm going to close this. If you'd like to start a serious conversation about this functionality, open a bull request with code to add it and we can go from there!

**Comment by cryptographrix** [comment]
Wait, a UI change to this box is a "big carbon change"? https://www.dropbox.com/s/unp8075orhy3fcv/Screenshot%202015-06-26%2015.19.13.png?dl=0

We're talking about adding a button to support removal of metrics in graphs under /dashboard/...

**Comment by obfuscurity** [comment]
Graphite does not typically run with permissions to delete files on the local filesystem. I think what @SEJeff was getting at is that since Carbon does the writes, Carbon would be the most likely place to add the requested functionality, since it already has the necessary permissions.

**Comment by cryptographrix** [comment]
We're talking about adding and removing metrics from the graph definitions that are stored in the sqlite DB.

As per your own "readthedocs" documentation, "Graphite uses n SQLite database file located at STORAGE_DIR/graphite.db".

Indeed, a "select * from dashboard_dashboard;" from within sqlite client of that file produces a list of all of the dashboards in question complete with the json definitions of their contents.

```# ls -lah /opt/graphite/
total 14M
drwxr-xr-x  6 apache apache 4.0K Jun 26 01:07 .
drwxr-xr-x  9 apache apache 4.0K Dec 21  2013 ..
-rw-r--r--  1 root   root      4 Oct 22  2014 carbon-cache-a.pid
-rw-r--r--  1 apache apache 118K Dec  5  2014 graphite.db```

This is not a carbon change.  

This is stored within the django-based SQLite DB and would be a UI change, likely within ext-all.js (which is absolutely impossible to work on because it's a single-line JSON...and no, I'm not putting it into a formatter - your project has obviously obfuscated it for *some* reason).

**Comment by cryptographrix** [comment]
sqlite> select * from dashboard_dashboard where name='network';
    network|{"name": "network", "defaultGraphParams": {"width": "300", "from": "-12hours", "until": "now", "height": "230"}, "refreshConfig": {"interval": 60000, "enabled": false}, "graphs": [["target=pings.*.*.*.*.duration", {"from": "-12hours", "target": ["pings.*.*.*.*.duration"], "until": "now"}, "/render?width=300&from=-12hours&until=now&height=230&target=pings.*.*.*.*.duration&_uniq=0.8197899542283267&title=pings.*.*.*.*.duration"], ["target=pings.*.*.*.*.returned", {"areaMode": "stacked", "from": "-12hours", "target": ["pings.*.*.*.*.returned"], "until": "now"}, "/render?width=300&from=-12hours&until=now&height=230&areaMode=stacked&target=pings.*.*.*.*.returned&_uniq=0.9330033755395561&title=pings.*.*.*.*.returned"], ["target=scale(derivative(snmp.10.0.0.1.eth2.ifBytesIn)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.eth2.ifBytesOut)%2C0.016667)", {"areaMode": "all", "until": "now", "from": "-12hours", "target": ["scale(derivative(snmp.10.0.0.1.eth2.ifBytesIn),0.016667)", "scale(derivative(snmp.10.0.0.1.eth2.ifBytesOut),0.016667)"], "title": "Internal: Default"}, "/render?width=300&from=-12hours&until=now&height=230&areaMode=all&title=Internal%3A%20Default&target=scale(derivative(snmp.10.0.0.1.eth2.ifBytesIn)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.eth2.ifBytesOut)%2C0.016667)&_uniq=0.9130394915118814"], ["target=scale(derivative(snmp.10.0.0.1.eth2.30.ifBytesIn)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.eth2.30.ifBytesOut)%2C0.016667)", {"areaMode": "all", "until": "now", "from": "-12hours", "target": ["scale(derivative(snmp.10.0.0.1.eth2.30.ifBytesIn),0.016667)", "scale(derivative(snmp.10.0.0.1.eth2.30.ifBytesOut),0.016667)"], "title": "Internal: DMZ"}, "/render?width=300&from=-12hours&until=now&height=230&areaMode=all&title=Internal%3A%20DMZ&target=scale(derivative(snmp.10.0.0.1.eth2.30.ifBytesIn)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.eth2.30.ifBytesOut)%2C0.016667)&_uniq=0.9641848232131451"], ["target=scale(derivative(snmp.10.0.0.1.eth2.20.ifBytesIn)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.eth2.20.ifBytesOut)%2C0.016667)", {"areaMode": "all", "until": "now", "from": "-12hours", "target": ["scale(derivative(snmp.10.0.0.1.eth2.20.ifBytesIn),0.016667)", "scale(derivative(snmp.10.0.0.1.eth2.20.ifBytesOut),0.016667)"], "title": "Internal: Public"}, "/render?width=300&from=-12hours&until=now&height=230&areaMode=all&title=Internal%3A%20Public&target=scale(derivative(snmp.10.0.0.1.eth2.20.ifBytesIn)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.eth2.20.ifBytesOut)%2C0.016667)&_uniq=0.5761637438554317"], ["target=scale(derivative(snmp.10.0.0.1.eth2.60.ifBytesIn)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.eth2.60.ifBytesOut)%2C0.016667)", {"until": "now", "from": "-12hours", "target": ["scale(derivative(snmp.10.0.0.1.eth2.60.ifBytesIn),0.016667)", "scale(derivative(snmp.10.0.0.1.eth2.60.ifBytesOut),0.016667)"], "title": "Internal: Nick's"}, "/render?width=300&from=-12hours&until=now&height=230&title=Internal%3A%20Nick's&target=scale(derivative(snmp.10.0.0.1.eth2.60.ifBytesIn)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.eth2.60.ifBytesOut)%2C0.016667)&_uniq=0.3786822578404099"], ["target=scale(derivative(snmp.10.0.0.1.eth1.ifBytesOut)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.eth1.ifBytesIn)%2C0.016667)", {"areaMode": "all", "until": "now", "from": "-12hours", "target": ["scale(derivative(snmp.10.0.0.1.eth1.ifBytesOut),0.016667)", "scale(derivative(snmp.10.0.0.1.eth1.ifBytesIn),0.016667)"], "title": "External: FiOS"}, "/render?width=300&from=-12hours&until=now&height=230&areaMode=all&title=External%3A%20FiOS&target=scale(derivative(snmp.10.0.0.1.eth1.ifBytesOut)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.eth1.ifBytesIn)%2C0.016667)&_uniq=0.732207843568176"], ["target=scale(derivative(snmp.10.0.0.1.tun0.ifBytesOut)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.tun0.ifBytesIn)%2C0.016667)", {"areaMode": "all", "until": "now", "from": "-12hours", "target": ["scale(derivative(snmp.10.0.0.1.tun0.ifBytesOut),0.016667)", "scale(derivative(snmp.10.0.0.1.tun0.ifBytesIn),0.016667)"], "title": "External: IPV6"}, "/render?width=300&from=-12hours&until=now&height=230&areaMode=all&title=External%3A%20IPV6&target=scale(derivative(snmp.10.0.0.1.tun0.ifBytesOut)%2C0.016667)&target=scale(derivative(snmp.10.0.0.1.tun0.ifBytesIn)%2C0.016667)&_uniq=0.46815102454274893"]], "timeConfig": {"startDate": "2014-10-18T23:27:16", "endTime": "5:00 PM", "endDate": "2014-10-18T23:27:16", "relativeStartQuantity": "12", "relativeUntilQuantity": "", "startTime": "9:00 AM", "relativeStartUnits": "hours", "type": "relative", "relativeUntilUnits": "now"}, "graphSize": {"width": "300", "height": "230"}}

**Comment by cryptographrix** [comment]
What we're talking about is the ability to remove a metric from graphs in the dashboard definition located at - for instance - https://graphitesystem.host.com/dashboard/#main.

Adding is easy - drag and drop, or merge, or rename...but there is no way to *remove* a metric from the graph except by destroying the graph and recreating it without that metric.

When you're working on complex graphs that may contain many different transformations, that's the last thing you want to do.

**Comment by cryptographrix** [comment]
![image of graph]
(https://www.dropbox.com/s/u8my6hnjvo30dkf/Screenshot%202015-06-26%2016.18.47.png?dl=0)

**Comment by cryptographrix** [comment]
Ah, the "send a PR" response that's quickly becoming the inverse of "Let me Google that for you" on Github.

Sure - as someone that has absolutely no direct experience with the codebase you've built or the Django framework, we'll get right on that.

Got a "donate" link we could put money into to prioritize this change instead?

**Comment by obfuscurity** [comment]
Nice attitude, thanks for your contributions to this thread.

**Comment by cryptographrix** [comment]
same.

**Comment by kovyrin** [comment]
So, how exactly was it a valid decision to close the totally legitimate feature request issue? Especially when it was based on absolutely invalid understanding of the request.

**Comment by steve-dave** [comment]
@cryptographrix I wish it was as easy as a donate box, but unfortunately that's a whole can of worms in its own right...  How much needs to be donated before the feature gets done and what if there is a disagreement about that between the donors and developer(s)?  Which developer(s) actually implements, do they need to be from the core team or can anyone do it?  Who holds the funds in trust and who decides when they should be paid out?  You have to remember that if there is not a company/organization (or managers with delegation powers) behind a project then the project collaborators quite likely have never met in person and are physically distributed all over the globe.

I feel your pain.  I, and I'm sure some of the others, would likely happily implement the feature if we had the time.  I have not even been able to work on my own list of wanted features for quite some time...  The only thing I could suggest is advertising on a freelancers board or something like that, there's nothing stopping you (or a group) from independently hiring a developer to implement features for open source projects.

**Comment by cryptographrix** [comment]
I think what I mean to suggest are alternative support models for distributed org/corp-less projects like Graphite that target enterprises.

I feel the contributor's pain too - How do issues get prioritized, by technical merit or issue advocacy/demand? Which issues are more important than others? Why should "advocated issue 357" get prioritized over "big technical issue 3"?

In enterprise-support world, there's a customer support/account rep that handles this prioritization.

This is a two+ year old issue that looks ("looks") like a relatively "easy" fix within the UI for somebody that knows Django and the graphite-web codebase...and it really makes graphite-web *look* abandoned for it not to have been fixed in the time it was open.

But to have it closed after two years...

If it really did require a carbon change etc - sure, I totally would've let it drop there.

But my 10 minutes of investigation showed that it didn't (above).

@kovyrin asked the important question without my attitude.

**Comment by kayvonr** [comment]
+1000000
