### ISSUE TITLE
Recent metric data not displayed until flushed to disk

### ISSUE THREAD

**Issue by DazWorrall** [graphite-project/graphite-web#1460]
I wasn't sure if I should file this against graphite-web or carbon, so apologies if I've chosen poorly.

We have a carbon-relay instance fronting 4 x carbon-cache instances, no aggregation in the stack, but when building graphs or fetching data via the api the most recent metric values are not immediately available. If we wait long enough they do appear (typically 5-30 minutes, we're always starved for IOPS), so I thought the query cache lookups from graphite-web were failing, but I see successful cache lookups logged in the cache instances:

```
29/01/2016 11:28:48 :: [query] [127.0.0.1:37758] cache query bulk for "32" metrics returned 2025 values
```

A bit of debug logging and tcpdump'ing shows the metric updates coming into the relay and passing straight through to the cache instances, so there's no delay getting the data into the cache processes - we just cant seem to get the data out until (I assume) they're flushed to disk. These are not new metrics, the whisper files were created long ago.

You can find config files and log snippets in this [gist](https://gist.github.com/DazWorrall/72aa75d844c588027cf0), if anyone can see if we're missing something that would be very much appreciated. Or if I'm totally wrong about how this is supposed to work and we just need more IOPS you can tell me that too :)

**Comment by toni-moreno** [comment]
Hi I'm experiencing the same behavior, while carbon cache instances are queuing data graphite doesn't return recent metrics , we have 6x carbon-cache instances (200k metrics/minute aprox)

As you can see in this queue graph , we have this error frequently.

![image](https://cloud.githubusercontent.com/assets/5883405/12675702/713dc7d6-c68c-11e5-9e5f-0a085fb3babd.png)

the problem persists until data queues disappear, usually 10/15 minutes  ( sometimes 20/30 minutes)

**Comment by DazWorrall** [comment]
Should also say the carbon and graphite-web version is 0.9.15 on python 2.7.3 on Ubuntu 12.04

**Comment by deniszh** [comment]
@DazWorrall - something is definitely wrong with your cache, but config looks perfectly fine. Try to disable CARBONLINK_QUERY_BULK  - but I'm just 'shooting in the dark'.

**Comment by DazWorrall** [comment]
Thanks for the suggestion @deniszh but no joy I'm afraid - I can see the queries come in for individual metrics so the change took affect but [we're still seeing gaps][0] :(

[0]: http://s3.dwuk.net/scrn/2016/1/e544a20003774c3ca61a38ef4ba847b7.png

**Comment by toni-moreno** [comment]
@DazWorrall @deniszh , we have noticed exactly the same behavior but in our case we are working with git master versions 

-  graphite-web:   ( commit 8710ff76f0b4571481d295d997a83e4c895dd092) from june 2015.  Which has not implemented CARBONLINK_QUERY_BULK option yet.

- carbon: ( commit https://github.com/graphite-project/carbon/commit/b80ce915a5e420b46e6972512801491e536db1b6 ) from April 2015.

We have only last values when carbon instances can flush all data to disk.

**Comment by deniszh** [comment]
Nah, CARBONLINK_QUERY_BULK was just a guess. In both cases the reason is the same - cache is not working and graphite reads data from disk, and that's slow. But what's an issue - hard to say. :(

**Comment by deniszh** [comment]
@toni-moreno: You can try to set DIVERSE_REPLICAS=False for your carbon (if your version has DIVERSE_REPLICAS implemented) - if you have more than one host and REPLICATION_FACTOR >1

**Comment by toni-moreno** [comment]
sorry @deniszh I have not implemented DIVERSE_REPLICAS option. :(

If there is any way to "force"/"simulate"  data queue growing  , we could update to the last master version in a testing box and debug anything you need to fix this error.

How can simulate it?

**Comment by deniszh** [comment]
@toni-moreno: That's fine - DIVERSE_REPLICAS  can interfere with cache behaviour, but if you don't have it - then you have nothing to worry about.
And if your problem is not persistent and happening only when queue grows  - then, I'm afraid, your installation just can't keep up with load.

**Comment by toni-moreno** [comment]
@deniszh . I'm not sure about that. 

I Think there is some error when queue grows , as a example we have already opened an issue (https://github.com/graphite-project/graphite-web/issues/1399) ( carbon  metrics query crashes), this happens only when queue grows and only with carbon metrics, all other metrics queries are working but only until last flush to disk.

**Comment by toni-moreno** [comment]
Hi @deniszh , @DazWorrall we have increased in 6Gb RAM and 2 cpu's our resources in a graphite node ( a VMware VM), and restarted the machine after that at 6:00 ( aprox). 

NOTE: This machine has 210K metrics /minute.

![image](https://cloud.githubusercontent.com/assets/5883405/13045159/1fa1c9e2-d3d2-11e5-8b5a-648456b7f412.png)

As you can see in our queue graph all all cache instances wr07x have been caching for 3 hours , while this happens  graphite-web query's response contains only data until 6:00 am.graphite-web response time is really good here.

Once all data is cached on memory  ( at 9:30 aprox) it seems like carbon-caches begin to flush all data to disk.. cpu wait time disappears and graphite-web query's responses contains all previous data. ( no data lost seems to happen).

In all this process the only problem is he have been working 3 hours without recent data. If graphite-web is running ok, it have enough cpu why carbon-cache are not sending queued data? and only  disk data?

**Comment by zdenekpizl** [comment]
I noticed if there is huge in-memory cache and the physical file is not update often (let's say modify time of wsp is more than 2 hours ago) such file is not taken into account when returning data. It is probably configurable by some option. 

Could it be this case?

**Comment by deniszh** [comment]
@FractalizeR : That's a slightly different issue - metric will not be visible until whisper file will be created on disk. That's also known, but unfortunately quite hard to fix in the current codebase.

**Comment by FractalizeR** [comment]
@deniszh I see, thanks!
