### ISSUE TITLE
Config Parameters should be described

### ISSUE THREAD

**Issue by gwaldo** [graphite-project/graphite-web#1461]
Config parameters (such as carbon.conf) should be explained.

For instance, is MAX_UPDATES_PER_SECOND apply to the carbon-cache process, or is that the max per-second per-metric?

Describe the behavior/impact of "LOG_UPDATES".

And so on.

They don't need to be hugely detailed.

**Comment by drawks** [comment]
Sounds like you're talking about carbon not graphite-web. Please file issue with appropriate project.

https://github.com/graphite-project/carbon/issues

**Comment by gwaldo** [comment]
It's a documentation ticket.  Docs live in this repo.

**Comment by gwaldo** [comment]
Sorry, I don't mean to sound like an ass, @drawks; It's just stupid busy here, and I noticed a gap in the docs, and wanted to record the problem as quickly as possible.

**Comment by obfuscurity** [comment]
It's fine gentlemen, the issue is filed with the correct project. Let's move on. :heart:

**Comment by drawks** [comment]
mea culpa!
