### ISSUE TITLE
Missing information in config-database-setup.rst

### ISSUE THREAD

**Issue by bartgrantham** [graphite-project/graphite-web#1465]
The documentation on config-database-setup.rst is confusing and seems to be missing information.  It appears to be cut-and-pasted from config-local-settings.rst, but makes no sense out of context.

For example, "The following configures the Django database settings." but there is no command or configuration instruction after that.

Also, there is a reminder to run `django-admin.py`, which isn't installed when using pip on Ubuntu.  At least, it wasn't for me.  I'm using a fresh install of Graphite on Ubuntu 14.04 with the following (as root):

```
pip install https://github.com/graphite-project/ceres/tarball/master
pip install whisper
pip install carbon
pip install graphite-web
export GRAPHITE_ROOT=/opt/graphite/
```

**Comment by daks** [comment]
I have the same problem: I installed with pip (either from master or from released versions) and I got stuck at the 'Webapp Database Setup' step. I thought Django will be installed as a requirement to graphite-web but it's not the case.
I wonder if installing Django is sufficient or if other deps will be missing? And which Django version is needed?
