### ISSUE TITLE
WSGIRequest.REQUEST is deprecated in Django 1.7 and removed in Django 1.9

### ISSUE THREAD

**Issue by SalmonMode** [graphite-project/graphite-web#1467]
I ran into this bug while trying to set up graphite for a personal project. It looks like you are already aware that [Django 1.9 is a problem for graphite](https://github.com/graphite-project/graphite-web/commit/48f22e4826063e008f52542b33bf27eb35ed70b8), but it looks like (as far as I can tell), that it's just the result of [`WSGIRequest.REQUEST` being removed from Django 1.9](https://docs.djangoproject.com/en/1.9/releases/1.7/#merging-of-post-and-get-arguments-into-wsgirequest-request) in favor of using the `WSGIRequest.POST`and `WSGIRequest.GET` properties because they are more explicit. I figure, even if you are already aware of the issue, and maybe even the exact cause, it can't hurt to have an issue opened up to track it.

After messing around with it a little bit, it looks like just swapping out `REQUEST` for either `POST` or `GET` (depending on what's being used), is all that's needed to fix the problem.

**Comment by deniszh** [comment]
Looks like fixed for master branch in https://github.com/graphite-project/graphite-web/pull/1471
