### ISSUE TITLE
SVG rendering broken in 0.9.x

### ISSUE THREAD

**Issue by squarebracket** [graphite-project/graphite-web#1473]
The fix for #1227 is causing malformed SVG for me. Reverting the fix (i.e. adding back the `+ "</g>"`) makes SVG rendering work again.

I'm using CentOS 6.5, python 2.6.6, pycairo 1.8.6.

**Comment by squarebracket** [comment]
I can submit a PR for this, but I don't know if this is a problem due to my old versions or what. A fix which may handle both cases is something like this:
```
...
open_g = svgData.count('<g')
close_g = svgData.count('</g')
while close_g < open_g:
  svgData += "</g>"

fileObj.write(svgData)
...
```

**Comment by bmhatfield** [comment]
I can +1 this. I am not sure what version of what is breaking things - I am taking a look now.

**Comment by bmhatfield** [comment]
Alright - it took me a little while, but I determined that the behavior here is different on more recent versions of Cairo, and SVG rendering no longer returns an error.
