### ISSUE TITLE
Selecting time Period above 1 Week

### ISSUE THREAD

**Issue by aquastern** [graphite-project/graphite-web#1481]
Hi,

I have a problem when selecting a time period of more then 1 week. When pressing the 1 month or 1 year option the 1 week graph appears. I already posted about this in the monitoring-portal.org and someone else seems to have the same issue. Does anyone know what I could do to fix this ?

I have this Problem in graphite-web and also in icingaweb graphite Plugin.

Can maybe someone help me?

**Comment by toopa2002** [comment]
Are you setting 1 week for retention period?  Check this -> https://github.com/graphite-project/whisper/issues/166#issuecomment-243713438
