### ISSUE TITLE
Intermittent internal server errors

### ISSUE THREAD

**Issue by virtualdxs** [graphite-project/graphite-web#1484]
About 1 in every 2-3 times I load a Graphite page I get an internal server error. Graphite error log is empty, and nothing new appears in main.

**Comment by jblaine** [comment]
Are you using https? I had the same problem ~2 years ago and never could figure it out. The suspicion was that there was intermittently not enough entropy for the SSL connections' encryption.

**Comment by obfuscurity** [comment]
@virtualdxs Which version of Graphite? Can you reproduce with the master branch?

**Comment by virtualdxs** [comment]
I haven't used Graphite in awhile as I've moved away from doing monitoring stuff. I'll go ahead and close this issue.
