### ISSUE TITLE
Problems running graphite behind reverse proxy

### ISSUE THREAD

**Issue by RomanKisilenko** [graphite-project/graphite-web#1486]
I'm trying to run a graphite (from master) behind a nginx reverse proxy. I configured URL_PREFIX='/graphite/'.

Graphite UI opens fine, authentication works. 
However, I'm not able to logout or edit account - the links are missing /graphite/ prefix I configured, they lead to /account/logout/ and /account/edit/ correspondingly.

Hopefully this issue can be fixed.

**Comment by brutasse** [comment]
Thanks for the report! Fix incoming in #1487
