### ISSUE TITLE
Query Wildcard issue

### ISSUE THREAD

**Issue by sraupach** [graphite-project/graphite-web#1488]
Hi,

when grafana calls this url "http://<someip>/metrics/find/?query=*" i got an interal server error

> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/opt/graphite/webapp/graphite/metrics/views.py", line 179, in find_view
>     content = tree_json(matches, base_path, wildcards=profile.advancedUI or wildcards, contexts=contexts)
> NameError: global name 'contexts' is not defined

Any idea?

Thanks in advance

**Comment by brutasse** [comment]
Which version are you running? I don't see how this would happen with latest `master` or `0.9.x`.

**Comment by sraupach** [comment]
Sorry for that late reply. I reinstalled it from scratch and it's working right now.
