### ISSUE TITLE
Timeout long queries

### ISSUE THREAD

**Issue by linar-jether** [graphite-project/graphite-web#1491]
Is there a way to have graphite-web kill long running queries after a certain timeout?
If a user requests a high resolution metric for a very large time span(several years), the server can choke and stop processing other requests (or takes a long time to process them).

**Comment by mechairoi** [comment]
You're probably looking for the `harakiri` option, if using uWSGI.

**Comment by linar-jether** [comment]
Solved using apache's `request-timeout` option
