### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by JeanFred** [graphite-project/graphite-web#1496]
It’s been 5 months since the release of 0.9.14 & 0.9.15 (see #677 for the process). Quite a lot of features have been added since then! :-)

Do we want to cut a 0.10 release out of master at some point? What’s holding us? I had a look at the 1.0.0 milestone but not sure how relevant it is.

Also, do we want to address the divergence between 0.9.x and master somehow? I don’t know much about it unfortunately so I can’t tell how much « 584 commits ahead, 1354 commits behind » is actual divergence vs. patches applied to both?

**Comment by obfuscurity** [comment]
@JeanFred Can you elaborate on what you've done in the past day or so? It looks like you added "GitHub releases" to the 0.9.14 and 0.9.15 tags from last year. Just want to clarify that you didn't push anything on top of the 0.9.x releases by accident.

**Comment by obfuscurity** [comment]
Note: I temporarily revoked your committer status until we grok what has changed.

**Comment by obfuscurity** [comment]
P.S. To answer your original question, we definitely want to do a 0.10 or 1.0 release based on master. I don't have an ETA but I'd love to see this within the next month or so.

**Comment by JeanFred** [comment]
> Can you elaborate on what you've done in the past day or so? It looks like you added "GitHub releases" to the 0.9.14 and 0.9.15 tags from last year. Just want to clarify that you didn't push anything on top of the 0.9.x releases by accident.

Sure thing. I did not commit nor pushed anything. It is my understanding that « Github releases » are merely a UI thing around tags. I simply found it weird that someone navigating to https://github.com/graphite-project/graphite-web/releases would be prominently invited to download the pre-release 0.9.13 (which was not labelled as such either) while we had two releases since then.

I thought this uncontroversial (since there was one for 0.9.13 ; but it seems you deleted that as well) and just went bold on this. I was evidently mistaken and I apologize if I caused any turmoil.

> Deleted those releases. FWIW we don't typically do "GitHub informational releases" there, just tags. We use the formal documentation to provide release notes.

Noted.

> Note: I temporarily revoked your committer status until we grok what has changed.

Noted.

**Comment by obfuscurity** [comment]
Yeah it's fine, it just caused a bit of kerfuffle. Some folks saw the "new release" and got confused. Yes, I've deleted all "releases" since they're generally unused within the project. We tag releases and ship them to PyPI, and [document the release notes](http://graphite.readthedocs.org/en/latest/releases.html) accordingly.

I'm totally :+1: on taking charge and being forward-thinking, but just keep in mind that operating "rogue", especially when you haven't done much administratively with the project, may cause some raised eyebrows. Best to open an issue first (as you've done here) or discuss with folks in IRC before making any non-code type changes (as a committing team member).

**Comment by obfuscurity** [comment]
P.S. Added you back to the committers team.

**Comment by JeanFred** [comment]
> I'm totally :+1: on taking charge and being forward-thinking, but just keep in mind that operating "rogue", especially when you haven't done much administratively with the project, may cause some raised eyebrows. Best to open an issue first (as you've done here) or discuss with folks in IRC before making any non-code type changes (as a committing team member).

Noted, will keep that in mind − will come to IRC first next time I’m being too enthusiastic. :)

I appreciate the time taken to explain things and the renewed trust with the committer status.
