### ISSUE TITLE
Write Contributing Guidelines document

### ISSUE THREAD

**Issue by gwaldo** [graphite-project/graphite-web#1497]
Write guidelines for contributing to the project.

Look at some Chef Cookbooks and http://dokku.viewdocs.io/dokku/development/release-process/ for some ideas

**Comment by gwaldo** [comment]
"If you're going to do something directly on the main repo, other people should probably know about it.  When in doubt, check with obfuscurity or mleinart."

**Comment by obfuscurity** [comment]
I agree with the sentiment.

**Comment by gwaldo** [comment]
Didn't mean to, but this got rolled into https://github.com/graphite-project/graphite-web/pull/1501

Note to self: This is what Branches are for.

Would @graphite-project/committers have a look, comment, etc

**Comment by deniszh** [comment]
BTW. Maybe need to create separate issue for that...
Maybe we need some merging policy too? E.g. 
- how much reviewers need to check new PR?
- do we need review from specific "elder" person to press merge?
etc.

**Comment by bitprophet** [comment]
Shameless plug that http://contribution-guide.org might also be worth linking to or cribbing off of.

**Comment by cclauss** [comment]
Is this issue closed?

**Comment by deniszh** [comment]
More/less - https://github.com/graphite-project/graphite-web/blob/master/CONTRIBUTING.md
