### ISSUE TITLE
I got stuck when installing graphite component from source

### ISSUE THREAD

**Issue by thinhduckhoi** [graphite-project/graphite-web#1517]
Hi guys,
Here's the step i used to install graphite from source.
```
cd /tmp
git clone https://github.com/graphite-project/graphite-web.git
git clone https://github.com/graphite-project/carbon.git
git clone https://github.com/graphite-project/whisper.git
cd whisper; git checkout 0.9.13-pre1; python setup.py install
cd ../carbon; git checkout 0.9.13-pre1; python setup.py install
cd ../graphite-web; **python check-dependencies.py; git checkout 0.9.13-pre1; python setup.py
install**

```

The point is after executing the python check-dependencies command, the error appeard.

[WARNING]
Unable to import the 'ldap' module, do you have python-ldap installed for python 2.7.5?
Without python-ldap, you will not be able to use LDAP authentication in the graphite webapp.

[WARNING]
Unable to import the 'txamqp' module, this is required if you want to use AMQP.
Note that txamqp requires python 2.5 or greater.
All necessary dependencies are met.
2 optional dependencies not met. Please consider the warning messages before proceeding.

I installed python-ldap but it still said the same error. Can some one tell me how to fix it, please?

**Comment by deniszh** [comment]
Hi @thinhduckhoi,
1. Please do not use 0.9.13-pre1 branch, use 0.9.15 or 0.9.x instead
2. It's just WARNINGS, you can safely proceed.

**Comment by thinhduckhoi** [comment]
@deniszh Thank you, i'll try it!

**Comment by thinhduckhoi** [comment]
Ah, i tried to use 0.9.15  and saw this.
[Optional] Unable to import the 'python-rrdtool' module, this is required for reading RRD.
[Optional] Unable to import the 'whitenoise' module. This is useful for serving static file/
And the same error "ldap-python"  and txamqp. Should i process?

**Comment by deniszh** [comment]
Yep, it's optional components.
