### ISSUE TITLE
Graphite does not render graphs and throws Http error 500 on render call

### ISSUE THREAD

**Issue by skilledmonster** [graphite-project/graphite-web#1519]
I deployed graphite application in Centos 7 and I see the following error as  Trackback - 

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 56, in renderView
    (graphOptions, requestOptions) = parseOptions(request)
  File "/opt/graphite/webapp/graphite/render/views.py", line 241, in parseOptions
    graphType = queryParams.get('graphType','line')
AttributeError: 'WSGIRequest' object has no attribute 'get'

```

I am using the following versions - 

Django (1.5.12)
whisper (0.9.15)
django-tagging (0.3.6)
Pythong(2.7)
Graphite-Web(0.9.15)
Carbon(0.9.15)

Any ideas?

**Comment by skilledmonster** [comment]
I also made sure to install all the required dependencies - 

```
[root@server graphite]# ./check_dependency.py
[OPTIONAL] Unable to import the 'python-rrdtool' module, this is required for reading RRD.
[OPTIONAL] Unable to import the 'whitenoise' module. This is useful for serving static files.
2 optional dependencies not met. Please consider the optional items before proceeding.
All necessary dependencies are met.

```

**Comment by rlewkowicz** [comment]
Unable to import the 'python-rrdtool' module, this is required for reading RRD.

This is required for the rendering of rrd files. pip install python-rrd. You need a slew of deps related to cario. It's quite the trek to get them all.

**Comment by obfuscurity** [comment]
I don't believe rrdtool has anything to do with the original exception. @skilledmonster are you still running into this issue? Apologies for the slow response.

**Comment by eddawley** [comment]
I ran into a similar issue installing graphite-web into a virtualenv on centos6.  Downgrading to django==1.8.15 fixes it for me.

`[root@localhost vagrant]# /opt/graphite/bin/pip freeze
cairocffi==0.7.2
carbon==0.9.15
cffi==1.8.3
Django==1.9.10
django-tagging==0.4.3
graphite-web==0.9.15
pycparser==2.14
pytz==2016.7
Twisted==16.4.1
txAMQP==0.6.2
uWSGI==2.0.14
whisper==0.9.15
zope.interface==4.3.2

[root@localhost vagrant]# curl "http://127.0.0.1:80/render/"
<body style="background-color: #666666; color: black;">
<center>
<h2 style='font-family: "Arial"'>
<p>Graphite encountered an unexpected error while handling your request.</p>
<p>Please contact your site administrator if the problem persists.</p>
</h2>
<br/>
<div style="width: 50%; text-align: center; font-family: monospace; background-color: black; font-weight: bold; color: #ff4422;">

</div>

<div style="width: 70%; text-align: left; background-color: black; color: #44ff22; border: thin solid gray;">
<pre>
Traceback (most recent call last):
  File &quot;/opt/graphite/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File &quot;/opt/graphite/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File &quot;/opt/graphite/webapp/graphite/render/views.py&quot;, line 56, in renderView
    (graphOptions, requestOptions) = parseOptions(request)
  File &quot;/opt/graphite/webapp/graphite/render/views.py&quot;, line 236, in parseOptions
    queryParams = request.REQUEST
AttributeError: &#39;WSGIRequest&#39; object has no attribute &#39;REQUEST&#39;

</pre>
</div>

</center>
`

**Comment by howdoicomputer** [comment]
I'm getting this problem as well.

**Comment by obfuscurity** [comment]
Graphite-web 0.9.15 is [intended to be run with Django 1.4](https://github.com/graphite-project/graphite-web/blob/0.9.15/requirements.txt#L32). Please try that version and report back.

**Comment by howdoicomputer** [comment]
Works fine with 1.4. Chef cookbook I was using was setting the Django version at 1.9.

**Comment by obfuscurity** [comment]
Cool. I'm going to close this issue since it appears to be a dependency versioning issue.
