### ISSUE TITLE
Is there any function can convert [ ] to some metrics so seyren can process it

### ISSUE THREAD

**Issue by 1337newbee** [graphite-project/graphite-web#1535]
I was using countSeries, trying to filter out the Null series by using currentAbove() function. However, the return value is not 0 thus my seyren server is not being triggered successfully.

I'm wondering is that a bug or I should use a different function?

`countSeries(currentAbove(transformNull(*.abc.*.uptime.uptime,-1),0))`

**Comment by obfuscurity** [comment]
Hi @1337newbee, I'm trying to understand your use case but I'm not a Seyren user so I'm not sure where the problem lies. Can you explain what sort of series you *need* for your Seyren trigger to fire as intended?

**Comment by 1337newbee** [comment]
my series is the basic one with uptime

countSeries(currentAbove(container_name.uptime.uptime,0))

**Comment by obfuscurity** [comment]
@1337newbee I'd love to help you out but you're not really giving me enough information to work with. It would help to know what sort of data you're storing, and what you **want** Graphite to convert it to.

**Comment by 1337newbee** [comment]
the data I store here is from plugin uptime, so typically it will give the time length that the container is up and running. https://collectd.org/wiki/index.php/Plugin:Uptime
What I want to capture is when my containers are all down, this metric will give me NULL, then I convert NULL to 0, transformNull, then I want my target to return me 0. But currently, it return empty. Let me know if that makes sense.

**Comment by obfuscurity** [comment]
That's precisely what `transformNull()` is for, not sure what else you're looking for.
