### ISSUE TITLE
Question regarding master branch releases

### ISSUE THREAD

**Issue by svenmueller** [graphite-project/graphite-web#1536]
Hi,

We are currently using version `0.9.15` which misses functions like `reduceSeries`. Those functions are only added to the master branch. But there is no release from the master branch available. How does the current release plan look like? Will there be a release from the master branch available?

Cheers Sven

**Comment by obfuscurity** [comment]
Long story short, I've been distracted by my work at a commercial monitoring company the last couple years, not to mention the other usual stuff (family, writing a book, etc). I don't want to make grand promises I can't keep, but Graphite is becoming a big focus for me again. I want to get a new release cut from master within the next 2-3 months.

**Comment by svenmueller** [comment]
Thx for the answer!
