### ISSUE TITLE
Which version to use?

### ISSUE THREAD

**Issue by jbergler** [graphite-project/graphite-web#1543]
Hey Graphite Team,

We're running 0.9.15 as our production graphite instance. I'm finding though that some features like (sortByTotal) are missing from the 0.9.x release even though these features were merged to master several years ago.

I found graphite-project/carbon#312 which discusses a similar issue where master and 0.9.x are diverged and there doesn't seem to be anything (at least that I've found) which indicates what a way forward is here.

So, my questions are, specifically with regards to graphite-web:
* is 0.10.x stable enough to be running in production?
* is it safe to run different versions of carbon and graphite-web?
* are there any obvious things that are missing in 0.10.x from 0.9.x 

Thanks!

-- Jonas

**Comment by obfuscurity** [comment]
Hi @jbergler! Rest assured we will make sure there is a reasonable path forward for 0.9.x -> 1.0 users when 1.0 is considered ready for general consumption. That is to say, when it's fully documented and the warts are fully understood/acknowledged.

Good news, Graphite development has been picking up recently but it's about to get a full-on boost of my time. I'm starting employment at [raintank](http://raintank.io/) next week. They're huge fans of Graphite and intend to continue investing in the Graphite ecosystem, in particular with my time working on the project.

P.S. Thank you for your PR bringing in `sortByTotal` to 0.9.x.
