### ISSUE TITLE
Adding metrics with different storage using sumSeries

### ISSUE THREAD

**Issue by brunorey** [graphite-project/graphite-web#1562]
I have two metrics, one stored for a day and one stored for one year.

If I try to add the two using sumSeries() it works fine if I query for 24h, but if I query for more than that the results from the metric stored for only the last day are displayed at the beginning of the larger metric instead of at the end

``` bash
root@graphite-test-lab:~# 
root@graphite-test-lab:~# grep daily /opt/graphite/conf/storage-schemas.conf -A 7
[daily]
pattern = \.today$
retentions = 1s:1d

[local]
pattern = ^local.*
retentions = 1s:1y

root@graphite-test-lab:~# 
root@graphite-test-lab:~# echo "local.random.sumseries.bug.today 10 `date +%s`" | nc 127.0.0.1 2003 -q0
root@graphite-test-lab:~# 
root@graphite-test-lab:~# echo "local.random.sumseries.bug.today 8 `date +%s --date='1 hour ago'`" | nc 127.0.0.1 2003 -q0
root@graphite-test-lab:~# 
root@graphite-test-lab:~# echo "local.random.sumseries.bug.lastweek 2 `date +%s --date='a week ago'`" | nc 127.0.0.1 2003 -q0
root@graphite-test-lab:~# 
```

**Actual result:** The line with the points loaded for today is shown one week ago
![graph3](https://cloud.githubusercontent.com/assets/10224603/16392460/6c90b196-3c82-11e6-9be6-6f39d8407fef.png)

**Expected result:** The line should show the point with the value 2 last week and the other two points today.

**Versions:**
Graphite 0.9.12

``` bash
root@graphite-test-lab:~# 
root@graphite-test-lab:~# uname -a
Linux graphite-test-lab 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u2 x86_64 GNU/Linux
root@graphite-test-lab:~# cat /etc/debian_version 
7.7
root@graphite-test-lab:~# python --version
Python 2.7.3
root@graphite-test-lab:~# django-admin --version
1.4.5
root@graphite-test-lab:~# 
root@graphite-test-lab:~#
```

**Comment by brunorey** [comment]
For the record, this is how my actual use case is shown: (metrics name deleted)
![sumseries-different-storage-schema](https://cloud.githubusercontent.com/assets/10224603/16395155/ef5fbc6e-3c8e-11e6-8cf0-6df34bc6b46c.png)

My workaround was to just use the same storage for both metrics

**Comment by obfuscurity** [comment]
@brunorey Would it be possible for you to try the same query on a newer Graphite, e.g. 0.9.15 (or the 0.9.x branch)? I know there were some fixes in the code path for combining series of different precision levels. Alternatively, could you upload your Whisper files somewhere that I could test against 0.9.15?
