### ISSUE TITLE
How to create a custom function?

### ISSUE THREAD

**Issue by stefanosala** [graphite-project/graphite-web#1575]
Hi there!
We're happy users of Graphite :)

I created a custom function hacking `functions.py` and besides being a bit hacky, it's working for our purpose. It's basically a `summarizeToMonth` function which aggregates all the datapoints of one month into the first day of the month so that we can create graphs with stats per-month. It's hacky, otherwise I would have created a PR ;)

Anyway, I'd like to clean the code a bit and add the function without touching the code `functions.py` file. Is that possible in any way? How?

Thanks!
Stefano

**Comment by obfuscurity** [comment]
Hi @stefanosala! Unfortunately we don't currently support "pluggable functions". Coincidentally, we recently merged support for [integralByInterval()](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.integralByInterval) which sounds like it does the same thing. 😸

**Comment by stefanosala** [comment]
Oh, interesting, thanks a lot!
