### ISSUE TITLE
Configurable limit or raise the limit of targets requested beyond 25?

### ISSUE THREAD

**Issue by nathanbower** [graphite-project/graphite-web#1582]
What is the likelihood that we could raise the limit of requested targets beyond 25 or possibly make this a configurable value?

**Comment by obfuscurity** [comment]
@nathanbower Can you elaborate on this "limit" you're hitting? I'm not aware of any fixed limit on the number of targets that can be returned. Here's a sample graph I just threw together showing 34 different metrics using wildcards, and then again with distinct targets (clicking one at a time).

<img width="981" alt="screen shot 2016-07-08 at 2 27 43 pm" src="https://cloud.githubusercontent.com/assets/494338/16697612/840453f2-4518-11e6-9265-1bbf2dcfadef.png">

**Comment by nathanbower** [comment]
Thanks @obfuscurity ! Glad to hear there isn't a fixed limit.  Running the query again is now working...a bit perplexed because we don't know what changed.

I've confirmed when misspelling some target names within an existing successful query that the api does seem robust to respond with known target values despite errant target names submitted.  Probably something we're missing that had broken our query.  I'll respond back if we identify the cause.

**Comment by obfuscurity** [comment]
Glad to hear it. Definitely let us know if something seems weird again. Closing.
