### ISSUE TITLE
Transform/OffsetToZero function

### ISSUE THREAD

**Issue by klaffke** [graphite-project/graphite-web#1606]
Would it be possible to offer/implement **Transform/OffsetToZero** `http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.offsetToZero`?

https://github.com/grafana/grafana/issues/5230

**Comment by obfuscurity** [comment]
I assume you mean in the 0.9.x branch. In that case, no. If you need it I encourage you to try running from the master branch instead. It's actually quite stable and our current focus is preparing a 1.0 release.

**Comment by klaffke** [comment]
Ahh, thanks for the information! It confuses me that when I follow the link to the documentation

http://graphite.readthedocs.io/

that per default the documentation of an unreleased version is displayed. Usually such a link redirects to the latest stable release version instead.

Another idea would be to note the version number next to the descriptions of the funktions under /functions.html (e.g. "since 0.10.0 – UNDER DEVELOPMENT", "since 0.9.15")
