### ISSUE TITLE
mysterious spike rendered when format is not supplied

### ISSUE THREAD

**Issue by wjaspers** [graphite-project/graphite-web#1609]
I suspect that this has something to do with libcairo, not necessarily graphite-web.
Or, is there a possibility that graphite-web discarded a metric because it deviated too far from the y-max of other metrics in the series?

## potentially related issues
- #1184 : missing/invalid results with moving average over wildcard aggregation
- #433 : downsamping doesnt work as expected

Unfortunately, i don't have whisper data to share with this bug.

## expected result
- no spike is rendered in the final PNG
- the format parameter can be omitted and default to PNG without rendering differently than when the parameter is supplied.

## system details 
rhel/6.0
python/2.x
django/unknown
graphite-web/0.9.1

#### altering the render URI by dimensions:
spike appears with `width=945&height=245&from=-24h`
spike vanishes with `width=945&height=244&from=-24h`

#### altering the render URI by bgcolor
spike appears with `bgcolor=00000000&width=945&height=245&from=-24h`
spike vanishes with 'bgcolor=000000FF&width=945&height=245&from=-24h`

our spike appeared under several different cases, but was only consistently resolved by ensuring the `format=png` parameter was supplied.

Here's a sample query string where the spike mysteriously appeared
```
/render?width=945&height=245&from=-24h&bgcolor=00000000&target=alias(sumSeries(my.metric.path-*.*.errors),'errors')&target=alias(sumSeries(my.metric.path-*.*.success),'success')
```

**Comment by obfuscurity** [comment]
I'd love to help debug this but we really need more information. Starting with the Graphite version you're running, but ideally I'd also like to see your actual request/response headers and the same responses as raw or json output to see if it's happening there as well.

**Comment by wjaspers** [comment]
as was reported to me this morning, the spike was the result of memcached not evicting keys as expected (or possibly caching something forever). someone did mention that an upgrade of graphite-web may have occurred and memcached was not restarted. the resulting changes to our request URI just so happened to produce a new image.

since this isn't necessarily a graphite-web issue, ill close this.
