### ISSUE TITLE
Port timeseries read-merge functionality to master

### ISSUE THREAD

**Issue by obfuscurity** [graphite-project/graphite-web#1617]
The timeseries merge functionality that was developed by @jjneely and released in 0.9.14 needs to be ported to master.

/cc @deniszh 
refs https://github.com/graphite-project/graphite-web/pull/1352

**Comment by cbowman0** [comment]
If I'm reading the code in master accurately, it is not doing any choosing of duplicate series beyond removing duplicate empty ones.  Does that read accurately?  If so, is the expectation that in [this block](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/datalib.py#L139) code similar to the 0.9.x branch would be added to perform the merging?

**Comment by deniszh** [comment]
Looks you're right, @cbowman0 
Will try to dive into that on the weekend, maybe it will work w/o backporting of additional patches.

**Comment by cbowman0** [comment]
Additionally, I think this may exist in MultiReader already...

**Comment by deniszh** [comment]
I have a progress:
<img width="1194" alt="screen shot 2016-08-21 at 01 54 20" src="https://cloud.githubusercontent.com/assets/1227222/17834477/4743749c-6742-11e6-8761-e6d64e37f090.png">
it's a quick hack, will finish it tomorrow. :)

**Comment by obfuscurity** [comment]
Awesome!

**Comment by deniszh** [comment]
PR is done, let me check couple of other things.

**Comment by deniszh** [comment]
Yep, works with local merges too, ready to merge. :)

**Comment by iksaif** [comment]
We deployed that in preprod recently, and it looks like there was a huge increase in latency since we merge this. I'll try to do a bisection next week to see if it's really related to this change.

I also believe the change would have been cleaner if implemented with MultiReader() instead of duplicating the logic in fetchData().

**Comment by deniszh** [comment]
It's because of nature of this patch, though. As you can see in the code, if merging is enabled - I'm disabling calculation minimal node set completely - https://github.com/deniszh/graphite-web/blob/bc18f9730b102cd5ab3ba1409b6760471f4b43ea/webapp/graphite/storage.py#L83
So, it will ask all leaf nodes for potential data to merging. I see no other way how we can decide which node can contain valuable data.
If someone has ideas how to do so - will glad to fix it.

**Comment by iksaif** [comment]
With 3 nodes and a replication factor of 2, even if it fetches from all replicas, it should only double the traffic, true ?

**Comment by iksaif** [comment]
Responding to my own comment: this is deduplicated by `get_inflight_requests` because the url is the same.

**Comment by deniszh** [comment]
Unfortunately, I'm not running master on any significant load. I could test it on some artificial load, though.

**Comment by iksaif** [comment]
I'll try to debug the issue next week. I suspect this happens we you hit a graphite-web on a cache with a global query.

**Comment by iksaif** [comment]
Ok, that's because the bulk request finishes while we send the request to the second replica, and thus is removed from the inflight requests. Because of that we do the bulk_request multiple times. I'll try to come up with a patch

**Comment by deniszh** [comment]
@iksaif - cool, thanks a lot!
Is `del self.inflight_requests[url]` good as a permanent fix? Or we need  a better solution?

**Comment by iksaif** [comment]
No, it isn't good as a permanent fix because it will leak memory. My patch simple use the cache with a small TTL. I'll hopefully be able to validate that it works tomorrow and send a merge request.

**Comment by deniszh** [comment]
@iksaif 
Thanks a lot! Let me know if I can help with something.

**Comment by iksaif** [comment]
https://github.com/iksaif/graphite-web/commit/c98f246c4ec466c07de661216bcbab1af6ce15b4 seems to work for us. I'll leave it running this afternoon and send a PR tomorrow.

**Comment by deniszh** [comment]
Thanks, @iksaif !
Maybe we need to disable cache explicitly when REMOTE_STORE_MERGE_RESULTS disabled?

**Comment by iksaif** [comment]
I don't think the cache is harmful and it also helps cases were the sub-queries are not done in the right order (which might happen even without REMOTE_STORE_MERGE_RESULTS)

**Comment by deniszh** [comment]
Ah, right, cool then!

**Comment by iksaif** [comment]
I don't think it's worth it, and this cache is probably useful even when this setting is disabled.

**Comment by iksaif** [comment]
Make a must better and simpler fix in https://github.com/graphite-project/graphite-web/pull/1666
