### ISSUE TITLE
Grafana last 5 minutes not showing correctly

### ISSUE THREAD

**Issue by hostingwalk** [graphite-project/graphite-web#1667]
I use Grafana with Graphite but it not showing good on short time-frames like 5 or 15 minutes (misses some times.)

Screenshot:
![352cbfe14cb5427ca918c894471d829a](https://cloud.githubusercontent.com/assets/9915051/18090799/be20a504-6ec6-11e6-9d41-6a3b9933ecd7.png)

anyone know where maybe the problem can be ?  if i select 30 minutes or 1 hours or 1 week/month it just showing everything.

**Comment by obfuscurity** [comment]
Sounds like your Graphite-Web isn't able to retrieve "hot" metrics from the Carbon cache(s). Check your `local_settings.py` to make sure `CARBONLINK_HOSTS` is set properly.

**Comment by hostingwalk** [comment]
```
CARBONLINK_HOSTS = ["127.0.0.1:7002:a"]
CARBONLINK_TIMEOUT = 1.0
```
i have set it like this, or can this maybe the problem:
`[carbon]
pattern = ^carbon\.
retentions = 1s:1d,1m:7d,10m:1y`

**Comment by obfuscurity** [comment]
It looks like your clients aren't sending at regular intervals. This can cause gaps like that, especially if your retention policy doesn't match. Note that the `[carbon]` retention policy you pasted above only covers Carbon's internal reporting stats; it wouldn't affect the `servers.*` metrics you're showing in these graphs.

Things to check:

* First, make sure that your `CARBONLINK_HOSTS` setting above matches the `[cache]` definition(s) in your `carbon.conf`. If it doesn't, then Graphite-Web (the rendering API) will be unable to pull those "hot metrics" from cache memory.
* You should have a schema in your `storage-schemas.conf` for the affected `servers.*` metrics (or just the `[default]` schema), what does it look like?
* Note that for the time being, you can at least "bandaid" your graphs by turning on Graphite's `lineMode=connected`. I don't recall where this setting resides in Graphite but it shouldn't be too hard to find.

**Comment by hostingwalk** [comment]
* I dont not have a  [cache]  you have a example for that ?
`[servers]
pattern = ^servers.*
retentions = 1s:1d,1m:7d,10m:1y,5m:1d
`
*  i cannot find anything for `lineMode=connected`  local_settings.py  it is not here.

**Comment by obfuscurity** [comment]
Paste your `carbon.conf` here so we can help you identify what your `CARBONLINK_HOSTS` setting should be.

The `lineMode=connected` comment refers to the [lineMode](http://graphite.readthedocs.io/en/latest/render_api.html#linemode) feature of Graphite's render API. This will be exposed somewhere within the Grafana UI but I don't know where offhand.

**Comment by hostingwalk** [comment]
`CARBON_METRIC_PREFIX = carbon
CARBON_METRIC_INTERVAL = 60
STORAGE_DIR    = /var/lib/graphite/
CONF_DIR       = /etc/carbon/
LOG_DIR        = /var/log/carbon/
PID_DIR        = /var/run/
LOCAL_DATA_DIR = /var/lib/graphite/whisper/
CACHE_QUERY_INTERFACE = 0.0.0.0
CACHE_QUERY_PORT = 7002
`
i can post full carbon.conf but much are just default from installation and much just information.

**Comment by obfuscurity** [comment]
Your `[cache]` block starts right there at the top. Looks like a standard configuration, so your `CARBONLINK_HOSTS` should be fine. Your retention policy looks fine. So it just seems like your clients are sending `servers.*` metrics at infrequent intervals. They need to send them at 1s intervals or you're going to end up with gaps (based on your current `1s:1d` precision).

**Comment by hostingwalk** [comment]
The problem was the sending clients(servers) yeah, In Diamond.conf:   
# Default Poll Interval (seconds)
i# nterval = 300
i uncommented # and change it to 10 or 30 and now it works yeah, thank you!
