### ISSUE TITLE
Something is misidentifying my host as an old name from a different server,when I have removed all references

### ISSUE THREAD

**Issue by dantate** [graphite-project/graphite-web#1676]
something, somewhere is misidentifying my server as a legacy DNS entry that doesn't exist anywhere anymore?  The server was never named "monitor" but it briefly had a CNAME for it.  When I enter the source i use the proper hostname, iCinga.mydomain.com, but when i try to execute it, i get this in the log:

template Endpoint "iCinga" {
    host = "monitor.mydomain.com"
    port = "5665"
    log_duration = 1d
}

where the host should equal icinga.mydomain.com, which i enter, but it gets changed.

**Comment by dantate** [comment]
Just found this:

 [debug] util_ldap.c(2089): LDAP merging Shared Cache conf: shm=0x7f9fc1b460b8 rmm=0x7f9fc1b46110 for VHOST: monitor.pallino.com

which is odd, since I don't use LDAP

**Comment by deniszh** [comment]
Sorry, @dantate - but your question is not related to Graphite. If it's Icinga related - it's better to check Icinga page for support - https://www.icinga.org/community/ .
If it's general Linux question - it's better to ask that on general Linux forums, on [Stackoverflow](http://stackoverflow.com/) / [Serverfault](http://serverfault.com/).
