### ISSUE TITLE
maxValue only limits when counter wraps

### ISSUE THREAD

**Issue by jonkerj** [graphite-project/graphite-web#1677]
I am having trouble with spikes due aggregation boundaries, and hoped to dirty fix this using the `maxValue` in `perSecond`. It is, however, not implemented in such a way that `maxValue` is always the maximum value.

```python
def perSecond(requestContext, seriesList, maxValue=None):
# skip comments
  results = []
  for series in seriesList:
    newValues = []
    prev = None
    for val in series:
      step = series.step
      if None in (prev,val):
        newValues.append(None)
        prev = val
        continue

      diff = val - prev
      if diff >= 0:
        newValues.append(diff / step)
      elif maxValue is not None and maxValue >= val:
        newValues.append( ((maxValue - prev) + val  + 1) / step )
      else:
        newValues.append(None)

      prev = val
    newName = "perSecond(%s)" % series.name
    newSeries = TimeSeries(newName, series.start, series.end, series.step, newValues)
    newSeries.pathExpression = newName
    results.append(newSeries)
  return results
```

From the description I would guess it works like this: `min(maxValue, diff/step)`. The code suggests `maxValue` is only used when the value is less than the previous (ie, counter wraps), which is not the case in my situation.

To solve my specific problem using graphite-web, I could do two things: improve `perSecond`, or implement a new function which clips a series.

**Comment by obfuscurity** [comment]
If I understand your problem, why not just filter out the spikes with [removeAbovePercentile()](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.removeAbovePercentile) or [removeAboveValue()](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.removeAboveValue)?

**Comment by jonkerj** [comment]
Ok, somehow I managed to miss these functions. A big thanks, these fix my problem. On the risk of being pendant: I still think the name of this parameter is misleading, as it only adjust pure counter wraps, and does not enforce a maximum value. But this may be a matter of taste/opinion :-)

**Comment by obfuscurity** [comment]
@jonkerj Agreed, I can see how this may be a little confusing. I'd consider changes to this but I'd like to ensure it doesn't break expectations for existing users of this function.
