### ISSUE TITLE
Can't query metric

### ISSUE THREAD

**Issue by toopa2002** [graphite-project/graphite-web#1678]
I have 2 following metrics
- test.count
- test.count.max

Whisper files are stored corectly with 2 whisper files.
- /opt/graphite/whisper/test/count.wsp
- /opt/graphite/whisper/test/count/max.wsp

Can I query both metric in this way.

**Comment by obfuscurity** [comment]
You should be able to query it just fine (i.e. the render API) but the composer will not support browsing them in the metrics tree. There's a long-standing bug around this that would not be resolved without a complete redesign.

Jason Dixon

**Comment by toopa2002** [comment]
Strange,  the render api cannot query test.count. Is there any know issue or setting I should consider?

**Comment by obfuscurity** [comment]
Not offhand. Are you getting any server errors or exceptions?

Jason Dixon

**Comment by toopa2002** [comment]
I will re-check the log file. 
Is this issue fixed? - > https://github.com/graphite-project/graphite-web/issues/193#thread-subscription-status

**Comment by deniszh** [comment]
@toopa2002 - no, and that's exactly what @obfuscurity talking about.
You will not get `test.count` in browser tree, but can get results using render api.
Try to create graph of `test.count.max` metric, then edit metric name manually - you will get graph for `test.count`

**Comment by toopa2002** [comment]
The problem that I found is on render api . It is not consistent some time I can retrieve "xxx.count", some time i can't.   I have checked whisper file and they are not corrupted.
The graphite-web version is 0.9.12.

* call api -> xxx.count
```
curl 'http://localhost/render/?target=env.dc.bd.eth.eth_ws.veth-ppws04.eth-ws.CreateEbd.req.count&format=json'
[]
```

* call api -> xxx.count.max
```
curl 'http://localhost/render/?target=env.dc.bd.eth.eth_wveth-ppws04.eth-ws.CreateEbd.req.count.max&format=json'
100 27470  100 27470 [{"target": "env.dc.bd.eth.eth_ws.veth-ppws04.eth-ws.CreateEbd.req.count.max", "datapoints": [[0.0, 1473144180], [0.0, 1473144240], [0.0, 1473144300], [0.0, 1473144360
   0     0  6], [0.0, 1473144420], [0.0, 1473144480], [0.0, 1473144540], [0.0, 1473144600], [0.0, 1473144660], [0.0, 1473144720], [0.0, 1473144780], [0.0, 1473144840], [0.0, 1473144900], [0.0, 1
```

*Whisper file are store on 2 machines
  * machine A
```
ls -l /opt/graphite/whisper/env/dc/bd/eth/eth_ws/veth-ppws02/eth-ws/CreateEbd/req
total 340
-rw-r--r-- 1 carbon carbon 344812 Sep  7 06:45 count.wsp
```
  * machine B
```
ls -l /opt/graphite/whisper/env/dc/bd/eth/eth_ws/veth-ppws02/eth-ws/CreateEbd/req/
total 4
drwxr-xr-x 2 carbon carbon 4096 Aug 15 15:34 count

ls -l /eikonmonnas/graphite/whisper/env/dc/bd/eth/eth_ws/veth-ppws02/eth-ws/CreateEbd/req/count/
total 340
-rw-r--r-- 1 carbon carbon 344812 Sep  7 06:48 max.wsp
```

**Comment by obfuscurity** [comment]
@toopa2002 I hate to say it, but 0.9.12 is way too old. Please upgrade to a supported version (0.9.15 or from the `master` branch) and let us know if you still encounter this issue.
