### ISSUE TITLE
Metrics filter - ignore hierarchy (dots)

### ISSUE THREAD

**Issue by tomerpeled** [graphite-project/graphite-web#168]
Is there any way to filter metrics while ignoring the hierarchy?

For example: Say I have the following metrics:

stats_count.A.B.TestMetric 
stats_count.A.TestMetric
stats.A.B.TestMetric
stats.A.B.TestMetric

How can I sum TestMetric under stats_count only?

I tried the followings with no success:

stats_counts.*.*.TestMetric - obviously this won't work...
sumSeriesWithWildcards(stats_counts.[A-Z\.]*[A-Z]*.TestMetric,1)
sumSeriesWithWildcards(stats_counts.[A-Z]*[.]*[A-Z]*.TestMetric,1)

Is it possible at all? If not I think that will be nice feature...

**Comment by cbowman0** [comment]
Merged into master via #1639.
