### ISSUE TITLE
Missing data from carbonlink cache when request crosses retention boundaries

### ISSUE THREAD

**Issue by cbowman0** [graphite-project/graphite-web#1701]
A request for a graph that starts before the lowest retention period has lines that end randomly, which looks bad.  Also data extraction for any automated data analysis ends in many Nones (in my case it's upwards of 20-40 minutes), which isn't good for data analysis.

Example:  Current time was 14:50.  Data is/was available in the caches.
![image](https://cloud.githubusercontent.com/assets/1764481/18590078/73f4888c-7bfb-11e6-9df8-5783bd1fc2f0.png)

This is a by-product of #1002.  The WhisperReader is explicitly not querying CarbonLink.  I believe this is NOT what we want, but can we gather a list of the conditions that we do need to handle?

**Comment by deniszh** [comment]
👍
Looks plausible.

**Comment by cbowman0** [comment]
If someone else has the time to work through this, then please go ahead.

Right now this is what I'm thinking are conditions that need to be considered for merging the cached values in:
1. How to determine what the step or interval is for the cached values?
2. What if the step or interval of the cached values differs from the lowest retention period?
  a. If it's smaller, I'm not exactly sure what whisper does, but I *think* the it chooses the most recent value within the interval and stores that. 
  b. If it's bigger, but aligns with a multiple of the step or interval, do we just use xFilesFactor and run it through the aggregations?
3. The metadata for whisper gives the aggregation methods, but what do we do with Ceres?

Assuming we know the answers above, just run the data through the aggregation method for each retention interval until we reach the appropriate one.
