### ISSUE TITLE
Dashboards throw 'invalid theme' in 0.10.0

### ISSUE THREAD

**Issue by reyjrar** [graphite-project/graphite-web#1702]
I've tried, believe me, I've tried, every combination of graphite or django setting in the local_settings.py, but after upgrading to master, all my dashboards throw:

"Invalid theme: 'default'" on every load.  They still look fine, but I can't make the message stop, I've tried:

STATIC_ROOT
CONTENT_DIR <- appears to be replaced
STATICFILES_DIRS = [ STATIC_ROOT ]
WEBAPP_DIR

I'm out of options, it's probably a simple config tweak, but the documentation isn't clear.  FWIW, I wasn't doing anything fancy, everything was using the default theme in 0.9.15 and it just worked.

**Comment by reyjrar** [comment]
Side note: Apache is serving the static content, why bother with this check at all?

**Comment by reyjrar** [comment]
Solved:

From 0.9.15 -> 0.10.0 the WEBAPP_DIR setting needs to be set for this to work, the automatic lookup doesn't work.

**Comment by obfuscurity** [comment]
@reyjrar Can you elaborate on your comment? It sounds like you're saying the existing implementation in `settings.py` is broken... but then you closed your issue?

**Comment by reyjrar** [comment]
I'm building for RedHat, and package the webapp bits into /usr/share/graphite.  Previously, that meant setting CONTENT_DIR=/usr/share/graphite/webapp/content.

There's some logic in settings.py to figure out where WEBAPP_DIR is, and that is used to determine where to look for static content (which again, I don't understand why that's even necessary).

When using the standard RH model, settings.py is installed in %{pythong_sitelib}/graphite/settings.py, but the web app lands in the /usr/share/graphite path.  So, it's necessary for users packaging according to this setup: https://github.com/dcarley/graphite-rpms  (fwiw, the first hit for "graphite rpm" on teh Googles) to manually set WEBAPP_DIR to /usr/share/graphite/webapp.

I think it's a documentation issue, which, btw, when I have some time, I'm going to submit a patch for because the upgrade process for me has been "Read the source code to figure out which switches to try flipping" :)
