### ISSUE TITLE
X-Label tick

### ISSUE THREAD

**Issue by ksaihtam** [graphite-project/graphite-web#1703]
Hello,

is there an option to change the x-label tick? As example, i show data from one day and my xFormat is "%H" to show me only the hours as x labels. The problem now, it will only show every second hour and not every hour. Is it possible to change this behaviour?

Thanks.

**Comment by obfuscurity** [comment]
Have you seen [minXStep](http://graphite.readthedocs.io/en/latest/render_api.html#minxstep)?

**Comment by ksaihtam** [comment]
I mean this option is only for the graph and not for the x axis labels. It doesn't change anything except the graph.

**Comment by obfuscurity** [comment]
Sorry, misunderstood your question. No, there is currently no way to override this via the render API. You could change to `labelStep=1` [here](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/glyph.py#L105) to achieve the desired effect.

It would be nice to expose `labelStep` in the render API.
