### ISSUE TITLE
Setting local_settings.py URL_PREFIX causes any request to 404

### ISSUE THREAD

**Issue by piotr1212** [graphite-project/graphite-web#1712]
I'm trying to run graphite-web with a prefixed path but when setting a `URL_PREFIX` every request I try results in a 404. There is no apparent error log entry.
I found out that setting `STATIC_URL` to `/graphite/static/` does achieve what I want.

Is `URL_PREFIX` deprecated? Is this caused by some change in Django? Has this something to do with whitenoise? Am I doing something wrong?

If `URL_PREFIX` is deprecated I'm happy to write patch to clean it up from code and update the examples to use `STATIC_URL`.
 
I'm running on:
Fedora 24
graphite-web master branch
Django 1.9.8
whitenoise 2.0.6
httpd 2.4
mod_wsgi 4.4.8
WSGIScriptAlias /graphite /path_to_wsgi

**Comment by obfuscurity** [comment]
I see no reason why `URL_PREFIX` shouldn't continue to work [as intended](https://github.com/graphite-project/graphite-web/pull/797). Note that this is a Graphite-only setting developed specifically to support non-root URLs.

Conversely, `STATIC_URL` is a [Django setting](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-STATIC_URL) which has more to do with how the URL is interpolated within templates.

**Comment by piotr1212** [comment]
Ok, but why am I getting 404's on any request I do when setting URL_PREFIX? And also why am I getting prefixed urls with only setting WSGIScriptAlias and no URL_PREFIX. Is this an issue with my system?

**Comment by obfuscurity** [comment]
Can't say without you providing more details, e.g. the actual 404 log entry (which URLs is it trying to load), what your wsgi configuration looks like, etc.

**Comment by piotr1212** [comment]
Looking at it again it got me even more confused. 

When configuring:
`WSGIScriptAlias / /usr/share/graphite/graphite-web.wsgi`
`URL_PREFIX = '/graphite'`

Graphite works when requesting http://localhost/graphite/ (only with trailing slash)

With:
`WSGIScriptAlias /graphite /usr/share/graphite/graphite-web.wsgi`
`URL_PREFIX = '/'`

Graphite also works when requesting http://localhost/graphite (works without trailing slash)

But when I configure both settings, as suggested here https://github.com/graphite-project/graphite-web/blob/master/examples/example-graphite-vhost.conf#L48-L58
`WSGIScriptAlias /graphite /usr/share/graphite/graphite-web.wsgi`
`URL_PREFIX = '/graphite'`

I get 404's I can get access to the webinterface on http://localhost/graphite/graphite/ but the static content is not served.

httpd config https://paste.fedoraproject.org/442760/55295581
local_settings.py https://paste.fedoraproject.org/442761/29603147
access log https://paste.fedoraproject.org/442762/29716147

**Comment by brutasse** [comment]
I'm not sure how this is supposed to work with Apache. I developed this patch with proxy setups in mind, with a dedicated WSGI server like gunicorn. Typically this would be an nginx+gunicorn deployment.

When setting URL_PREFIX, STATIC_URL is updated accordingly: https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/settings.py#L208-L210

If setting WSGIScriptAlias+STATIC_URL and not URL_PREFIX works, the Apache documentation needs to be updated accordingly. This is a perfectly valid approach. URL_PREFIX needs to stay for proxy deployments.

**Comment by piotr1212** [comment]
@brutasse thank you for commenting. It all makes sense to me now ;)
