### ISSUE TITLE
How can I install Graphite in Windows?

### ISSUE THREAD

**Issue by mayooran99** [graphite-project/graphite-web#1714]
How can I install Graphite in Windows and how can I connect my JVM instance to be monitored in a Windows machine? Would much appreciate it if someone can help with the steps.

**Comment by obfuscurity** [comment]
As per the [official docs](http://graphite.readthedocs.io/en/latest/install.html#windows-users), Graphite is not supported natively on Windows. However, you can run Graphite in a virtual machine on Windows. The Graphite website has a [quickstart guide](http://graphiteapp.org/quick-start-guides/synthesize.html) for doing precisely this using the Synthesize project.
