### ISSUE TITLE
ImportError: No module named django.utils.importlib 

### ISSUE THREAD

**Issue by KarnG** [graphite-project/graphite-web#1718]
hello experts, 
While trying to install graphite , i came across a issue with django import, I'm using django version 1.7.
When i start my http service i could see below errors in log file...

[Tue Oct 11 02:33:33 2016] [error] mod_wsgi (pid=14618): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Tue Oct 11 02:33:33 2016] [error] mod_wsgi (pid=14618): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Tue Oct 11 02:33:33 2016] [error] Traceback (most recent call last):
[Tue Oct 11 02:33:33 2016] [error]   File "/opt/graphite/conf/graphite.wsgi", line 4, in <module>
[Tue Oct 11 02:33:33 2016] [error]     from graphite.wsgi import application
[Tue Oct 11 02:33:33 2016] [error]   File "/opt/graphite/webapp/graphite/wsgi.py", line 8, in <module>
[Tue Oct 11 02:33:33 2016] [error]     from django.utils.importlib import import_module
[Tue Oct 11 02:33:33 2016] [error] ImportError: No module named django.utils.importlib

-- I looked around the google and github but did not get any solution.

**Comment by deniszh** [comment]
Strange, Django 1.7 should have `django.utils.importlib` - according to https://stackoverflow.com/questions/32761566/django-1-9-importerror-for-import-module
Please note that Django 1.7 dropped python 2.6 support. Do you have python 2.6 or 2.7?

**Comment by KarnG** [comment]
@deniszh .. I have python 2.7.10

**Comment by KarnG** [comment]
While I am starting the httpd service it throws this error on the log file

**Comment by deniszh** [comment]
On 2.7 and Django 1.7 it should work. Or you running Django 1.7 on python 2.6 or Django version is different.
Try to downgrade Django to 1.6

**Comment by KarnG** [comment]
I,m using python 2.7.10 and django 1.7 ..though I installed python 2.7 into /opt on centos 6.5 and exported the path for new installed python and it's running good. I,ll downgrade the django and will see then

**Comment by KarnG** [comment]
After downgrading still the same issue.. It Does not looks to be version issue..

```
[Tue Oct 11 18:22:25 2016] [error]     from django.utils.importlib import import_module
[Tue Oct 11 18:22:25 2016] [error] ImportError: No module named django.utils.importlib
[Tue Oct 11 18:22:25 2016] [error] mod_wsgi (pid=22631): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Tue Oct 11 18:22:25 2016] [error] mod_wsgi (pid=22631): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Tue Oct 11 18:22:25 2016] [error] Traceback (most recent call last):
[Tue Oct 11 18:22:25 2016] [error]   File "/opt/graphite/conf/graphite.wsgi", line 4, in <module>
[Tue Oct 11 18:22:25 2016] [error]     from graphite.wsgi import application
[Tue Oct 11 18:22:25 2016] [error]   File "/opt/graphite/webapp/graphite/wsgi.py", line 8, in <module>
[Tue Oct 11 18:22:25 2016] [error]     from django.utils.importlib import import_module
[Tue Oct 11 18:22:25 2016] [error] ImportEror: No module named django.utils.importlib

```

**Comment by brutasse** [comment]
There must be a duplicate Django installation somewhere in your path that takes higher priority. `django.utils.importlib` exists in Django up to 1.8 (included).

Where/how did you install Django and the other dependencies?

**Comment by KarnG** [comment]
@brutasse .. I have downgraded the django as per @deniszh to 1.6 but didnt get it resolved so i did upgraded it to the 1.8 now. I using "pip install" for this installation..
Below are the Installed pks via pip..
```
# pip freeze
cairocffi==0.7.2
cffi==1.8.3
Django==1.7
django-socketio==0.3.9
django-tagging==0.4.3
mod-wsgi-httpd==2.4.23.1
pycparser==2.14
pyparsing==2.1.10
Python-fontconfig==0.5.1
python-ldap==2.4.27
python-memcached==1.58
pytz==2016.7
six==1.10.0
Twisted==16.4.1
txAMQP==0.6.2
whisper==0.10.0rc1
zope.interface==4.3.2
When i check manual import , it works good..
```
  
[root@noi-dcgrafana ~]# python
Python 2.7.10 (default, Oct 10 2016, 16:23:05)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.version_info)
sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)
>>> print(sys.prefix)
/opt/python
>>>
>>> import django
>>> print django.__file__
/opt/python/lib/python2.7/site-packages/django/__init__.pyc

```

**Comment by KarnG** [comment]
Just for attention : 
1) I have default python is 2.6 
2) I installed python 2.7.10 Under "/opt/python"
3) So, everything installed under /opt/ including graphite Installation

This is all Running Under OS CenyOs Version 6.5.

**Comment by deniszh** [comment]
Looks like your Django install running on Python 2.6, which is a default for centos 6.5 and installing python to /opt/python is not enough.

**Comment by KarnG** [comment]
@deniszh .. Nt Sure if thats the case here..

**Comment by KarnG** [comment]
Can anyone tell me the Standard Set of pkgs for graphite install  on RedHat 6.5 with custom install python 2.7 as RHEL 6 comes default with 2.6 python

**Comment by str4d** [comment]
Possible hint: I have an import issue with my Twisted plugin, where it works fine with Twisted 16.3 but fails with 16.4: https://travis-ci.org/str4d/txi2p/builds/169930132
