### ISSUE TITLE
Can't create initial django db schema, missing import

### ISSUE THREAD

**Issue by spektre1** [graphite-project/graphite-web#1727]
When trying to execute:
```
 PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb

Traceback (most recent call last):
  File "/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/events/models.py", line 4, in <module>
    from tagging.models import Tag
  File "/usr/lib/python2.7/site-packages/tagging/models.py", line 10, in <module>
    from django.contrib.contenttypes import generic
ImportError: cannot import name generic
```
I've pip installed the files and have all latest versions:
```
pip show django whipser carbon graphite-web
[Edited for concision]
Name: Django
Version: 1.10.2
---
Name: carbon
Version: 0.10.0rc1
---
Name: graphite-web
Version: 0.10.0rc1
---
Name: whisper
whisper==0.10.0-rc1
```
This is on CentOS: cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core)

Not sure what to try here, as I'm not familiar enough with the Django framework to start debugging. Any thoughts?

**Comment by brutasse** [comment]
Your Django version is too new… django.contrib.contenttypes.generic was removed in Django 1.9, so you need Django 1.8.x max. It can be installed with `pip install "Django>=1.8,<1.9"`

**Comment by spektre1** [comment]
Thanks for the suggestion. Yah, I saw that with someone else's issue thread, so I already tried changing versions a bunch of times to see if any work. I haven't had much luck so far. Here's what happens on your rec'd version:

[root@monitor graphite]# pip install "Django>=1.8,<1.9"
Collecting Django<1.9,>=1.8
  Downloading Django-1.8.15-py2.py3-none-any.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 149kB/s 
Installing collected packages: Django
  Found existing installation: Django 1.10.2
    Uninstalling Django-1.10.2:
      Successfully uninstalled Django-1.10.2
Successfully installed Django-1.8.15

[root@monitor graphite]# PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb
/usr/lib/python2.7/site-packages/tagging/models.py:10: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

Traceback (most recent call last):
  File "/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/tagging/admin.py", line 3, in <module>
    from tagging.forms import TagAdminForm
  File "/usr/lib/python2.7/site-packages/tagging/forms.py", line 11, in <module>
    class TagAdminForm(forms.ModelForm):
  File "/usr/lib/python2.7/site-packages/django/forms/models.py", line 274, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TagAdminForm needs updating.

**Comment by spektre1** [comment]
Bump? I'm kind of lost here.The docs aren't holding up with the pip install method. Is there a recommended platform and build versions? 
I'm going to try from source today and see where I can get. Thanks in advance for any help.

**Comment by deniszh** [comment]
According to https://github.com/graphite-project/graphite-web/blob/master/requirements.txt - Django should be strictly 1.9.
Please try to ```
pip uninstall Django
pip install "Django>=1.9,<1.9.99
```

**Comment by spektre1** [comment]
For the record, I got this debugged. I had permissions errors on the log files that graphite was trying to write to, so it was failing to execute the wsgi. I had to insert a try/catch into the code to actually get an accurate enough error response to resolve this. This suggests that better error handling may be a good idea here.
The actual root cause was SELinux contexts were not setup correctly on those log directories; once I disabled SELinux entirely, it works. I should've realized that, I've run into that problem dozens of times with CentOS which has it enabled by default.
Apologies for wasting time, I'm closing this. Perhaps if I have some time I'll submit and error handling patch.

**Comment by shahmaulikn** [comment]
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of these two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected. 
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted 


it is disable then also observing same issue, please do needful

**Comment by deniszh** [comment]
@shahmaulikn - what's you r Django version? Should be 1.9.x

**Comment by deniszh** [comment]
@spektre1 - could you please share details what's exactly should be patched?

**Comment by shahmaulikn** [comment]
[root@localhost bose]# pip show django whipser carbon graphite-web
---
Metadata-Version: 2.0
Name: Django
Version: 1.9.13
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: http://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
Installer: pip
License: BSD
Location: /usr/lib/python2.7/site-packages
Requires: 
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Web Environment
  Framework :: Django
  Intended Audience :: Developers
  License :: OSI Approved :: BSD License
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Internet :: WWW/HTTP
  Topic :: Internet :: WWW/HTTP :: Dynamic Content
  Topic :: Internet :: WWW/HTTP :: WSGI
  Topic :: Software Development :: Libraries :: Application Frameworks
  Topic :: Software Development :: Libraries :: Python Modules
Entry-points:
  [console_scripts]
  django-admin = django.core.management:execute_from_command_line


This is what I am getting for pip show django whipser carbon graphite-web
