### ISSUE TITLE
Support querying remote servers using non-pickle formats

### ISSUE THREAD

**Issue by bodgit** [graphite-project/graphite-web#1735]
I'm building a 2-tier Graphite architecture where I have a number of machines running carbon-cache/relay, etc. with the graphite-web part running separately and aggregating across the machines. Given I didn't really care about having a UI on each individual machine, I thought I could get away with just running [Graphite API](https://github.com/brutasse/graphite-api) there and only running the full-blown graphite-web piece on the aggregating machine.

However graphite-web insists on always using pickle format when querying the remote `CLUSTER_SERVERS` according to [this line](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/remote_storage.py#L69); I only got as far as debugging the `/metrics/find/` which returned no metrics so I couldn't try rendering any graphs, I'm guessing the rendering is also affected. Graphite API doesn't support the pickle format and only returns JSON.

Would it make sense to allow JSON format too for interoperability? At least it seems to be a case of not adding the `format=pickle` query parameter and then handling JSON-formatted results instead of pickled ones.

**Comment by obfuscurity** [comment]
It would be far better to support protobufs or something similarly efficient. JSON is far too inefficient for inter-node data transfer imho. See https://github.com/graphite-project/carbon/issues/275 and https://github.com/graphite-project/carbon/pull/601 for related discussions.

**Comment by bodgit** [comment]
Those tickets seemed more towards changing the line receiver/pickle protocol used  for metric ingestion/relaying. I was talking about the interaction between clusters/hierarchies of frontend apps.

Currently I can use Graphite API which doesn't know how to talk to other instances of itself or Graphite web, but it's currently impossible to mix them as neither can agree on a compatible format.

I've worked around it by just running Graphite web everywhere but it's probably overkill on the machines that don't need it.

**Comment by obfuscurity** [comment]
Yes, I was just giving that as an example. JSON is a horribly inefficient format for exchanging data between nodes.

**Comment by obfuscurity** [comment]
Don't get me wrong, I'm not a JSON hater. I just don't think it's appropriate for this use case.

**Comment by obfuscurity** [comment]
That said, if someone wants to add JSON support and show benchmarks to support its inclusion, I'd be happy to consider the related PRs.

**Comment by bodgit** [comment]
> I just don't think it's appropriate for this use case.

It's how every other (non-Python) dashboard/frontend talks to Graphite :wink: Graphite web serves JSON content fine, it just won't ever request it from a peer.

I'll see what I can do.

**Comment by obfuscurity** [comment]
Yeah but that's a 1:1 query. We're talking backend clusters which are by nature one-to-many.
