### ISSUE TITLE
None ascii characters cause alias function exception?

### ISSUE THREAD

**Issue by eagleliang** [graphite-project/graphite-web#1737]
If use Chinese characters as alias of matrix, it will cause following error:
Graphite encountered an unexpected error while handling your request.

Please contact your site administrator if the problem persists.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 71, in renderView
    requestKey = hashRequest(request)
  File "/opt/graphite/webapp/graphite/render/hashing.py", line 33, in hashRequest
    return compactHash(normalizedParams)
  File "/opt/graphite/webapp/graphite/render/hashing.py", line 46, in compactHash
    hash.update(string)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 178-179: ordinal not in range(128)

**Comment by pfctgeorge** [comment]
@eagleliang 

you can simply do these 2 things to resolve:

1. import smart_str
```
from django.utils.encoding import smart_str
```

2. edit this line from `hash.update(string)` to `hash.update(smart_str(string))`

**Comment by eagleliang** [comment]
@deniszh the change mentioned by @pfctgeorge is OK to pull request?

**Comment by DanCech** [comment]
This is quite out of date now since the updates to add python 3.x support.

**Comment by deniszh** [comment]
`smart_str()` will work both, for python3 and python2. You can create PR, we need to test it how it works with different combinations of pythons/djangos etc

**Comment by eagleliang** [comment]
Yes， it's out of date. It's resolved now. Sorry about that. Just close this issue.
