### ISSUE TITLE
Local find requests returning no match when data is available and in carbon cache

### ISSUE THREAD

**Issue by cbowman0** [graphite-project/graphite-web#1739]
I deployed Master as of today and ran into a scenario where /render requests for the last 5-10 minutes worth of data would return No Data.  I tracked it down to the /metrics/find would generally return no matches.

The cache flush cycle on our carbon instances is long (like...30-60minutes long), so we have the following settings in Graphite:

```
FIND_CACHE_DURATION = 600
FIND_TOLERANCE = 12 * FIND_CACHE_DURATION
```

I turned off `REMOTE_STORE_MERGE_RESULTS` and the problem went away.  I suspect #1674 is related since turning off `REMOTE_STORE_MERGE_RESULTS` made the situation go away.  I'll investigate more when I have time, but until then maybe someone else is available.

**Comment by deniszh** [comment]
Yes, `REMOTE_STORE_MERGE_RESULTS=True` removing all `FIND_TOLERANCE` logic completely. Not sure how it can cause 'No data' situation, because it should make more requests but get data anyway. 
We also have a long flush cycle in carbon, but TBH I see no sense in such big cache / tolerance window (7200 is 2 hours, right?).

**Comment by cbowman0** [comment]
It was doing the opposite, though.

I suspect there is a big misunderstanding on what the FIND_TOLERANCE actually does.  How would you describe the purpose of it?

**Comment by deniszh** [comment]
Indeed. I have no good knowledge how find() in master branch works and why `FIND_TOLERANCE` is there at all. 0.9.x doesn't have that.

**Comment by deniszh** [comment]
I mean, It will be great if you explain master's find() logic here, I'm
really not sure that I read source right :)

>

**Comment by cbowman0** [comment]
Ah.  We are in the same boat.

My understanding is that the purpose was to pad the latest time of the data found on disk by the tolerance window.  This would compensate for the cached/unwritten data.

At this point I feel the need to put some logging in to confirm what the code is actually doing.  I'm hoping I have the time to do it soon.

**Comment by deniszh** [comment]
It will ask data through normal Graphite API, so, for existing (on disk) metrics it will return data, and for non-existing - it will return nothing. I see no sense to check something in past for such logic (and FAULT_TOLERANCE describes tolerance window in past: `tolerance_window = now - settings.FIND_TOLERANCE` ).
My understanding of FIND_TOLERANCE logic - we could have different find results for a different time interval. The current code of master trying to optimize merging of all these intervals and in a case of `REMOTE_STORE_MERGE_RESULTS` we can safely bypass all these optimizations.
But maybe I'm completely wrong. :)

**Comment by cbowman0** [comment]
I read through the code and feel that I have an understanding of the logic.  I will attempt to walk through it and we can decide how the `REMOTE_STORE_MERGE_RESULTS` should interact with it.

Let's assume `settings.FIND_TOLERANCE` is set to 10 minutes.

This is a tad bit simplified, but here goes: 
1. Build up a list of nodes, local and remote, and store in `nodes_remaining`.  This is effectively the list of `CLUSTER_SERVERS` and any local Finders defined in settings.

2. For each local node in `nodes_remaining`, if the data is found on disk then add to `minimal_node_set` and remove from `nodes_remaining`.

3. For each node in `nodes_remaining`:
  a. Compute how many intervals of data this node can provide, but this time ignore any intervals that reside in between now-`FIND_TOLERANCE` and now.
  b. Add each node that has any data to the `minimal_node_set`

4. If `minimal_node_set` is empty (no remote nodes had data and the local finder had NO data on disk), then choose the node where the difference between the node's most recent data and the start time of the query is less than the value of `FIND_TOLERANCE`.

I question the need for the ignoring of intervals within the `FIND_TOLERANCE` window, but that can be discussed later somewhere else if needed.

I have a few questions:
1. Why do we need REMOTE_STORE_MERGE_RESULTS to even touch anything in the find logic IF the logic already there in step 3 will merge in multiple remote nodes have any relevant data?

2. If you still think we do, then the base case (step 4) needs to be moved outside of the `if settings.REMOTE_STORE_MERGE_RESULTS` as a catch-all for when the requested interval is newer than data written to disk and the local host is the one that *probably* has it unwritten in carbon's cache.

3. Before, with REMOTE_STORE_MERGE_RESULTS, there was a claim that it affected render times if all `leaf_nodes` were added.  Was that substantiated?

**Comment by deniszh** [comment]
>Why do we need REMOTE_STORE_MERGE_RESULTS to even touch anything in the find logic IF the logic already there in step 3 will merge in multiple remote nodes have any relevant data?

I think I already tried to remove all tolerance find_logic from remote merge in https://github.com/graphite-project/graphite-web/commit/bc18f9730b102cd5ab3ba1409b6760471f4b43ea#diff-57c0c4ffa18833a2e2ea55aab4309ffc - and a result was terrible.
Maybe I did it wrong. :)

> If you still think we do, then the base case (step 4) needs to be moved outside of the if settings.REMOTE_STORE_MERGE_RESULTS as a catch-all for when the requested interval is newer than data written to disk and the local host is the one that probably has it unwritten in carbon's cache.

Yes, maybe we need to try that first.

>Before, with REMOTE_STORE_MERGE_RESULTS, there was a claim that it affected render times if all leaf_nodes were added. Was that substantiated?

IIRC I tried to fix that with https://github.com/graphite-project/graphite-web/commit/71cfdac927465497581756ddedf23a13b6fadba0

**Comment by deniszh** [comment]
Fixed in master, I think
