### ISSUE TITLE
How can I create user in graphite 0.10

### ISSUE THREAD

**Issue by emnvn** [graphite-project/graphite-web#1741]
Dear All,

I have installed graphite 0.10 on my CentOS 7, but I don't know how to login. I don't want to use LDAP and Remote User Login, I setup with local login.

I have searched on google, I found one way to create user by sung manage.py script in /opt/graphite/webapp but I can not see this script in my installation.

I don't know what is the problem.

Hope that someone will help me.

Thanks.

**Comment by gardenmwm** [comment]
You need to add the manage.py from the .9x branch and change the settings to graphite.settings. I'll add a pull request
