### ISSUE TITLE
metric value changed from int into double ?

### ISSUE THREAD

**Issue by howfree** [graphite-project/graphite-web#1764]
Hi all.
I try to send a metric Integer value 4 to Graphite by the following java code, 
but it appear 4.00 in Graphite web。
==================================================================

	public void sendMetrics(Map<String, Number> metrics, long timeStamp) {
		try {
			Socket socket = createSocket();
			OutputStream s = socket.getOutputStream();
			PrintWriter out = new PrintWriter(s, true);
			for (Map.Entry<String, Number> metric: metrics.entrySet()) {
				out.printf("%s %s %d%n", metric.getKey(), metric.getValue(), timeStamp);	
			}			
			out.close();
			socket.close();
		} catch (UnknownHostException e) {
			throw new GraphiteException("Unknown host: " + graphiteHost);
		} catch (IOException e) {
			throw new GraphiteException("Error while writing data to graphite: " + e.getMessage(), e);
		}
	}

===================================================================

how can I keep its origin data type?

Thanks.

**Comment by obfuscurity** [comment]
@howfree All metrics are recorded as floats in Graphite. There are no additional storage formats for numbers.
