### ISSUE TITLE
when installing to custom location via instructions django versions are inconsistent

### ISSUE THREAD

**Issue by deltaskelta** [graphite-project/graphite-web#1772]
When I went by the docs and installed to a custom location with 

`pip install carbon --install-option="--prefix=/srv/graphite" --install-option="--install-lib=/srv/graphite/lib"`

It installed a version that was incompatible with django==1.9 which is that the docs were telling me was the requirement.

**Comment by obfuscurity** [comment]
Can you please provide more details? At the very least, a link to the incorrect documentation?

**Comment by deltaskelta** [comment]
yeah I just did a quick PR #1773

**Comment by deniszh** [comment]
PR is merged
