### ISSUE TITLE
[Feature request] Multiply multiple wildcard series just by another series, don't multiply all of them

### ISSUE THREAD

**Issue by tomekit** [graphite-project/graphite-web#1783]
Imagine you have multiple series specified using wildcard.
Now you would like to multiple each individual series by another series.
Example usage: You have few metrics which provide a value of something in EUR currency #A. You would like to multiple each metric by the currency exchange rate #B to transform the currency to e.g. PLN.
![currency_multiply](https://cloud.githubusercontent.com/assets/7759113/21589717/fc574ec8-d0f4-11e6-9724-6470e272798f.png)

I was trying to address this problem using `multiplySeries`. 
Unfortunately it multiplies all of the metrics from all series lists together.

I was trying to use `multiplySeriesWithWildcard` function, however this function does not accept multiple series lists as a parameter. 

Is there any way to achieve it or custom function needs to be written?

Similar issue: https://github.com/graphite-project/graphite-web/issues/1104

This have been posted initially on Grafana board: https://github.com/grafana/grafana/issues/7106 but this is a Graphite issue really.

**Comment by vbichov** [comment]
+1
