### ISSUE TITLE
Graphite Web UI not responding when CLUSTER_SERVERS member is unavailable

### ISSUE THREAD

**Issue by ofirhoff** [graphite-project/graphite-web#1791]
Hi,
we're using graphite 0.15 and CentOS 6.7.
also using carbon-c-relay.
when any member from the cluster is down our web UI is loading slowly and we can't open the Metrics tree.
are we doing anything wrong?

local_settings.py conf :
#Cluster Configuration

CLUSTER_SERVERS = ['server_dns1:8080',''server_dns2:8080',''server_dns3:8080',''server_dns4:8080',''server_dns5:8080']

REMOTE_STORE_FETCH_TIMEOUT = 30   # Timeout to fetch series data
#REMOTE_STORE_FIND_TIMEOUT = 2.5  # Timeout for metric find requests
#REMOTE_STORE_RETRY_DELAY = 60    # Time before retrying a failed remote webapp
#REMOTE_FIND_CACHE_DURATION = 300 # Time to cache remote metric find results

##Remote rendering settings
#Set to True to enable rendering of Graphs on a remote webapp
#REMOTE_RENDERING = True
#List of IP (and optionally port) of the webapp on each remote server that
#will be used for rendering. Note that each rendering host should have local
#access to metric data or should have CLUSTER_SERVERS configured
#RENDERING_HOSTS = []
#REMOTE_RENDER_CONNECT_TIMEOUT = 1.0

**Comment by deniszh** [comment]
It's a known issue in graphite 0.9.x and it fixed in master now - https://github.com/graphite-project/graphite-web/commit/c6cf8244862ec15bf25b4cb4b01a29e45f59e2eb
Not sure if possible to backport that to 0.9.x because of a codebase in the master is quite different.

**Comment by Pita123** [comment]
Any idea why next release [1.0] will be published?

**Comment by deniszh** [comment]
When it will be ready, @Pita123 
Now we still have major issues with it, unfortunately - https://github.com/graphite-project/graphite-web/milestone/2

**Comment by deniszh** [comment]
BTW 1.0.0 is at RC-phase now, please test it, if you want, @Pita123

**Comment by Pita123** [comment]
Thank you, we will test it soon
