### ISSUE TITLE
settings.py logs to stderr instead of using the logger

### ISSUE THREAD

**Issue by dothebart** [graphite-project/graphite-web#1794]
when issued through the wsgi module, the first warning will get lost into nirvana:
```
## Load our local_settings
try:
  from local_settings import *
except ImportError as x:
  print >> sys.stderr, "Could not import graphite.local_settings, using defaults!"
  warn("Could not import graphite.local_settings, using defaults!: %s - %s" % (x.message, sys.path))
```
the later will output it into the apache error log.

Most probably a hint whether its readable or not would be good, since that was my error.

**Comment by drawks** [comment]
settings.py contains settings for configuring logging, presumably if your local_settings are meant to configure logging AND cause an exception there is no gurantee about the state of your logging config. It would be a real pickle to raise an error about your logging config using a broken logger. When in doubt fail back to the lowest common denominator. Just my .02, perhaps I'm missing something here.

**Comment by dothebart** [comment]
well, the final error you will get is logged the same way as I suggested:
if SECRET_KEY == 'UNSAFE_DEFAULT':
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')

Imho in most cases where you can't load the local_settings.py you won't be able to do anything  usefull in first place, and will get all sorts of permission and path errors.
So, if not change the way the message is printed above, attach it to all other errors or warnings below.

**Comment by dothebart** [comment]
unless something changed, I guess this will still be relevant to others.

**Comment by dothebart** [comment]
unless something changed, I guess this will still be relevant to others.

**Comment by dothebart** [comment]
unless something changed, I guess this will still be relevant to others.

**Comment by piotr1212** [comment]
Not sure if I get the problem. stderr should end up in the apache httpd log.

**Comment by dothebart** [comment]
as described in the original post, it does later on. but not yet in the early stage.

**Comment by deniszh** [comment]
I can add "pinned" flag to this issue to tame stale bot - but TBH I'm with @piotr1212 here, unfortunately - I still do not understand what'sproblem here, hence could not fix it. :(

**Comment by dothebart** [comment]
Try adding syntax errors or value errors to the configuration. I only remember this vaguely after all that time. 
At least I remember having had a hard time to find my original problem because of the error disappearing.
