### ISSUE TITLE
ImportError: cannot import name match_entries

### ISSUE THREAD

**Issue by cbl21c** [graphite-project/graphite-web#1795]
Hi,

After installing graphite, the webapp failed to run and I found the following in my httpd error_log:

<pre>
[Mon Jan 23 22:12:34.557231 2017] [wsgi:error] [pid 2608] [client 192.168.56.1:52176] mod_wsgi (pid=2608): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Mon Jan 23 22:12:34.557257 2017] [wsgi:error] [pid 2608] [client 192.168.56.1:52176] mod_wsgi (pid=2608): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Mon Jan 23 22:12:34.557273 2017] [wsgi:error] [pid 2608] [client 192.168.56.1:52176] Traceback (most recent call last):
[Mon Jan 23 22:12:34.557288 2017] [wsgi:error] [pid 2608] [client 192.168.56.1:52176]   File "/opt/graphite/conf/graphite.wsgi", line 17, in <module>
[Mon Jan 23 22:12:34.557331 2017] [wsgi:error] [pid 2608] [client 192.168.56.1:52176]     import graphite.metrics.search
[Mon Jan 23 22:12:34.557356 2017] [wsgi:error] [pid 2608] [client 192.168.56.1:52176]   File "/opt/graphite/webapp/graphite/metrics/search.py", line 6, in <module>
[Mon Jan 23 22:12:34.557396 2017] [wsgi:error] [pid 2608] [client 192.168.56.1:52176]     from graphite.storage import is_pattern, match_entries
[Mon Jan 23 22:12:34.557410 2017] [wsgi:error] [pid 2608] [client 192.168.56.1:52176] ImportError: cannot import name match_entries
</pre>

Looking at graphite/metrics/search.py, there is a line:

<pre>
from graphite.storage import is_pattern, match_entries
</pre>

but match_entries is not in graphite.storage. I found match_entries in graphite.finders.standard so I modified search.py to read:

<pre>
from graphite.storage import is_pattern
from graphite.finders.standard import match_entries
</pre>

After this change, the webapp ran successfully. My environment:

CentOS 7.0
Apache 2.4
Python 2.7.5
Django 1.10.5
graphite with hash 3213dc6a18d6ec01e1f14b3125751cb9e9cea0c1 cloned from github

**Comment by deniszh** [comment]
Maybe you mixed up `master` and `0.9.x` branches a bit. Search functionality was quite crappy and was completely removed from `master` branch. So, https://github.com/graphite-project/graphite-web/commit/3213dc6a18d6ec01e1f14b3125751cb9e9cea0c1 does not contain `search.py` at all.
But for 0.9.x you're right. Not sure do we need to fix it though...

**Comment by idnorton** [comment]
Fixed this by removing the following from conf/wsgi.py:
```
log.info("graphite.wsgi - pid %d - reloading search index" % os.getpid())
import graphite.metrics.search
```

Might be helpful to someone else, thanks for the pointer in the right direction @deniszh :)
