### ISSUE TITLE
Data received from certain source application (collectd) not display >24 hours of data

### ISSUE THREAD

**Issue by thecityofguanyu** [graphite-project/graphite-web#1800]
I have come across an issue with my Graphite deployment. First of all, versions:

```
carbon           0.9.15
Django           1.7.11
django-tagging   0.4.5
graphite-web     0.9.15
whisper          0.9.15
```

The issue I'm seeing is that the Graphite-web dashboard will not display any data on graphs set to greater than 24 hours. This issue is independent of which host the data comes from. With that said, it does seem to only impact the graphing of Whipser files containing data sent from a `collectd` source. Whisper files created from `netdata` data, and all of those files seem to graph without issue regardless of how the graphs are zoomed.

At first, I suspected that it was due to a typo or misconfigured pattern or retention in my `storage-schemas.conf`. In response, I modified the `collectd` pattern and default pattern to mirror the netdata pattern (that functions as expected). File below:

```
# Carbon's internal metrics. This entry should match what is specified in
# CARBON_METRIC_PREFIX and CARBON_METRIC_INTERVAL settings

[collectd]
pattern = ^collectd\.
retentions = 10s:1d,1m:7d,10m:1y

[netdata]
pattern = ^netdata.*
retentions = 10s:1d,1m:7d,10m:1y

[default_1min_for_1day]
pattern = .*
retentions = 10s:1d,1m:7d,10m:1y
```
I then removed the collectd Whisper files and let them get re-created. I confirmed via `whisper-info` that they now showed the retention details that I expected.

```
~> whisper-info /var/lib/graphite/whisper/collectd/sunjian/interface-eth0/if_packets/rx.wsp
maxRetention: 31536000
xFilesFactor: 0.5
aggregationMethod: average
fileSize: 855412

Archive 0
retention: 86400
secondsPerPoint: 10
points: 8640
size: 103680
offset: 52

Archive 1
retention: 604800
secondsPerPoint: 60
points: 10080
size: 120960
offset: 103732

Archive 2
retention: 31536000
secondsPerPoint: 600
points: 52560
size: 630720
offset: 224692
```

Still, the graphs are completely empty when you zoom out to a greater span that 24 hours.

24 hours:
![24 hours](http://i.imgur.com/Kwi17kA.png)

48 hours:
![48 hours](http://i.imgur.com/fKoBvjq.png)

Chrome network inspect output from both:
![chrome](http://i.imgur.com/KDwtgX3.png)

Is there anything else obvious I should be looking for when troubleshooting this? I Googled a bit, but kept finding answers related to modifying the `storage-schemas.conf` file.

Any input is appreciated!

**Comment by obfuscurity** [comment]
Are you sure that your collectd metrics are being emitted every 10s? For example, if they're only being emitted every 60s, they would not fulfill your `xFilesFactor` ratio and hence be rolled up to nulls in the second archive.

I explain it a bit more in [this blog post](http://obfuscurity.com/2012/04/Unhelpful-Graphite-Tip-9).

**Comment by thecityofguanyu** [comment]
@obfuscurity thanks for the info! I'll give that blog post a read and probably modify that ratio for the `collectd` data. I'll close the issue if that ends up resolving it.

**Comment by thecityofguanyu** [comment]
@obfuscurity Looks like this was indeed my problem. Guess I need to RTFM a little more carefully next time. Thank you!

**Comment by obfuscurity** [comment]
Glad to hear it, no problem! :heart:
