### ISSUE TITLE
Expected next release date

### ISSUE THREAD

**Issue by rewolf** [graphite-project/graphite-web#1802]
There don't seem to have been any releases in 2016 and I don't see any obvious indication of a planned next release.
Is there an expected date for a 0.10.0, or 1.0.0 release?
Looking at the [1.0.0 milestone](https://github.com/graphite-project/graphite-web/milestone/2), it seems there are two remaining issues?

Please excuse me if I'm asking in the wrong place or asking about things that I should have read somewhere. If so please point to the correct location for such information.

Love the software by the way and am interested in contributing

**Comment by rewolf** [comment]
I just saw issue #1782 
So I realize that #1690 is the blocker for 0.10.0.  Is 0.10.0 the same as 1.0.0 ?

**Comment by deniszh** [comment]
Yes, graphite developers are agreed to release 0.10.0 branch as graphite 1.0.0, when it will be ready to release. And, indeed, #1690 is the main blocker now.
