### ISSUE TITLE
"index out of range" when JSON format consolates series from movingAverage() and friends 

### ISSUE THREAD

**Issue by benbc** [graphite-project/graphite-web#1814]
Hello.

I see an error with all the `moving*()` functions when getting JSON-format data and specifying `maxDataPoints`.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 154, in renderView
    del series[0]
IndexError: list assignment index out of range
```

The problematic query (generated by Grafana) looks like this:

```
/render/?from=-24hours&target=movingAverage(*.some.metric%2C"10day")&maxDataPoints=462&format=json
```

The problem does not happen all of the time. It occasionally works, but usually doesn't.

It looks like the consolidation is trying to remove more data points from a series than are really there. That leads me to believe that the logic around that is probably flawed.

One of the series that I'm returning is empty and it's sufficient to trigger the error to include that series and one other non-empty one (but not the empty one on its own).

As well as coming and going over time it comes and goes when I tweak the `from`, `maxDataPoints` and `windowSize` parameters in the query. That leads me to believe that there is some edge case in the logic causing the problem (for example where something is an exact multiple of something else).

I can avoid the problem by modifying `renderView` to check that the series is non-empty before doing the `del`, but I'm pretty sure that there is a deeper logic problem than that, so I'm reluctant to submit a PR with that "fix" until someone else has had a go at understanding what's going on. I've spent the day staring at it and I'm out of clues.

**Comment by DanCech** [comment]
Interesting.  The issue is in the code that handles maxDataPoints, and from the sounds of things it's somehow coming up with a number of points to be removed that's greater than the number of points in one of the returned series.

**Comment by AlexZzz** [comment]
Hi! This is an annoying bug. I see the same errors.
In my case request looks like: ```target=groupByNodes(collectd.host*_{region}*.some_*.metric-opWLat,'average',1)&from=-1hour&until=now&format=json```
Will it be fixed in near future or maybe it's not so bad to add ```if series:``` before ```del series[0]```?
