### ISSUE TITLE
currentAbove doesn't take the value at the end of the series

### ISSUE THREAD

**Issue by guyisra** [graphite-project/graphite-web#1825]
I might misinterpret the docs but its says

> 
Takes one metric or a wildcard seriesList followed by an integer N. Out of all metrics passed, draws only the metrics whose value is above N at the end of the time period specified.

but from what really happens is that it checks whether any value in the time period specific was above N, and not at the "end of the time period" 

So either the docs should be fixed or the implementation

If the implementation is correct, this is a bit problematic since it takes the entire period, meaning I can't plot changes over a large time period when using CurrentAbove. Perhaps it should be renamed to AboveinRange or something similar

**Comment by deniszh** [comment]
According to [code](https://github.com/graphite-project/graphite-web/blob/7d0e0778138b5a5cb8652b6d822480fd632e8cb8/webapp/graphite/render/functions.py#L1905) it should work as expected.

**Comment by guyisra** [comment]
Ah so I think I understand what is happening

I'm trying to get series that are non-zero, but some series are Null/None in the last recorded value, so currentAbove grabs the last recorded non None value of the series in the time period. 

Is there alternative way to filter out series based on the actual current value? (or to map None to 0 in graphite? its possible to do it in grafana but its too late for the query)

**Comment by deniszh** [comment]
You can use [`transformNull(..,0)`](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.transformNull) to transform `None`s to 0.
