### ISSUE TITLE
Dependencies requirement not honored if not using setuptools

### ISSUE THREAD

**Issue by ybizeul** [graphite-project/graphite-web#1828]
When installing graphite-web, the following warning appears :

```
$ python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
```

As an effect, the requirements like pyparsing < 2.10 are not honored, and the system one used if found in any version.

If the `USE_SETUPTOOLS` is not defined, then distutils is found and does not understand that keyword, as implemented in `setup.py` :
```
     45 if os.environ.get('USE_SETUPTOOLS'):
     46   from setuptools import setup
     47   setup_kwargs = dict(zip_safe=0)
     48 
     49 else:
     50   from distutils.core import setup
     51   setup_kwargs = dict()
```

If `USE_SETUPTOOLS` is set, the install completely fails with the following error :

```
+ python setup.py install
/usr/local/lib/python2.7/dist-packages/setuptools/dist.py:333: UserWarning: Normalizing '0.10.0-rc1' to '0.10.0rc1'
  normalized_version,
running install
Checking .pth file support in /opt/graphite/webapp/
/usr/bin/python -E -c pass
TEST FAILED: /opt/graphite/webapp/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /opt/graphite/webapp/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
```

**Comment by iksaif** [comment]
Would it work to only use setuptools and to patch PYTHONPATH at the beggining of the file to contain /opt/graphite/ (when GRAPHITE_NO_PREFIX is not set) ?

**Comment by ybizeul** [comment]
Not sure I did correctly what you're saying.

Basically I set PYTHONPATH to /opt/graphite and exported it. I don't think GRAPHITE_NO_PREFIX is set, and I get the same error, it shows PYTHONPATH is set accordingly :

```
Checking .pth file support in /opt/graphite/webapp/
/usr/bin/python -E -c pass
TEST FAILED: /opt/graphite/webapp/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /opt/graphite/webapp/

and your PYTHONPATH environment variable currently contains:

    '/opt/graphite'

```

**Comment by deniszh** [comment]
That's a really strange issue. Which python version do you use? 
Graphite Synthesize has master support and it works fine - https://github.com/obfuscurity/synthesize/blob/feature/graphite-master/install

**Comment by ybizeul** [comment]
That's Python 2.7

**Comment by ybizeul** [comment]
Synthesize is using requirements.txt file. Installing "pyparsing" so not honoring pinning requirements if I understand correctly.

Note that you would find much of an issue, the only problem I have so far is if you end up using pyparsing 2.10, then randomly panel load will error when reloading full pages.

Bottomline, I don't think Synthesize would give me pyparsing according to install_require defined in setup.py, would it?

**Comment by deniszh** [comment]
Using `requirements.txt` is a documented way of installing Graphite IIRC. We should pin pyparsing version in `requirements.txt` too.
But in general, my knowledge of python packaging is vague. I should carefully read https://stackoverflow.com/questions/8295644/pypi-userwarning-unknown-distribution-option-install-requires and http://python-notes.curiousefficiency.org/en/latest/pep_ideas/core_packaging_api.html ¯\_(ツ)_/¯
If someone from @graphite-project/committers knows how to fix that properly - please speak up.

**Comment by ybizeul** [comment]
Same here, I don't know much about it. What I know is that pyparsing 2.10 is broken, unless we finally merge #1810, and I don't think using requirements.txt will fix this.

In the end, it depends on what version of pyparsing is found. If the distribution, debina 8.7 for example, provides pyparsing 2.0, you're all set. But if you install setuptools (for example) and it comes with 2.10 as a dependency, you break graphite, silently.

**Comment by DanCech** [comment]
@ybizeul can you answer my question on #1810 about packrat?

**Comment by deniszh** [comment]
Yes, that's a known issue in Python world, you should use `virtualenv` to create a separate environment for installing Graphite together with other python software. Graphite has strong Django version requirements (>=1.9,<1.9.99), but you do not worry if some software brings Django 1.6 or 1.10, right? We can pin `pyparsing` version in a same way.
In the modern world, when we're using Docker and VMs we're usually installing every piece of software separately...

**Comment by deniszh** [comment]
Maybe I'm wrong, but as far as I inderstand `install_requires` is setuptools options anyway and it's not possible to pin dependencies in setup.py w/o using setuptools.
So, I think we should merge #1810 or pin pyparsing version in `requirements.txt`.

**Comment by ybizeul** [comment]
Got it. Everything is on track to merge #1810 I suppose.

I should look into virtualenv then for my installs. But it's still confusing that a bare environment and simply running `setup.py` leads into dependencies not being honored.
