### ISSUE TITLE
See graph of 7 days older metric

### ISSUE THREAD

**Issue by fauzankhanak** [graphite-project/graphite-web#1834]
I am not able to set retention policy to see graph of 7 days older metric, how to set policy to see historical data.

**Comment by ybizeul** [comment]
That would be in `storage-schema.conf` for carbon, explained [here ](http://graphite.readthedocs.io/en/latest/config-carbon.html#storage-schemas-conf).

The sample one provided with the standard installation, that you can see [here](https://github.com/graphite-project/carbon/blob/master/conf/storage-schemas.conf.example) defines the following :
```
[carbon]
pattern = ^carbon\.
retentions = 60:90d

[default_1min_for_1day]
pattern = .*
retentions = 60s:1d
```

I'm actually surprised it's not more than that. How is yours configured?

**Comment by deniszh** [comment]
@fauzankhanak - after updating storage schema you should delete old metrics and recreate wsp files.
