### ISSUE TITLE
too many values to unpack error when querying Graphite for a Metric that has values only in the cache

### ISSUE THREAD

**Issue by NetaNir** [graphite-project/graphite-web#1836]
#### Scenario
When querying Graphite for a Metric that has values in the cache and no values in the DB it produce a "too many values to unpack error".

This can happen when:
1.  The query is on time span which has yet to be flushed from the cache to the db
2. The Metric is alive (meanning it's getting data points and thus has data in the cache ) and the query is on time spane **before the start time defined in the retention**

The above scenarios results in a state where there are cached results but no db results, the logic in https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/datalib.py in the fetchData funcion calls the mergeResults function when there are cahce results even if there are no db results to merge with, relying on the following logic in mergeResults function:
 ```
 def mergeResults(dbResults, cacheResults, lowest_step):
  cacheResults = list(cacheResults)

  if not dbResults:
    return cacheResults
# 
# rest of method
#
 ```
 
 Which simply suppose to return the cache results when there are no db results.
 Returning the cached results is incorrect since it doesn't take into consideration the **requested** start time and end time but simply returns the cache that can be in any time span.
 
 In addition, in this scenario the returned data structure is incorrect, it returns a list instead of a tuple of size 2 which cause the too many values error to be thrown.
 ```
 dbResults = mergeResults(dbResults, cachedResults, lowest_step)
# for clarity I have removed the exception handeling from this code

# dbResults here are the list(cachedResults) returned from the mergeResults function and thus not None
if not dbResults:
  continue

 
(timeInfo,values) = dbResults # Exception thrown here since dbResults is a list(cachedResults) and can not be assigned to the tuple 
 ```

**Comment by deniszh** [comment]
@NetaNir - I'm agreed that's a bug, but i'm not sure is it applicable to master branch and upcoming 1.0.0 release. 0.9.x is (almost) legacy now.

**Comment by iliapolo** [comment]
@deniszh why do you say its legacy? isn't 0.9.15 the latest stable version?

**Comment by deniszh** [comment]
Because we're not going to release 0.9.x versions anymore, next version will be 1.0.0, released from a current master branch. I think it will be soon, we almost ready to testing RC.
We could release 0.9.16 as a final ("bugfix") release of 0.9.x branch, though.
