### ISSUE TITLE
Considering current interval value in integral and consolidateBy

### ISSUE THREAD

**Issue by ybizeul** [graphite-project/graphite-web#1842]
I have a problem that I'm pretty sure I did to myself and is due to poor design of my whisper database, but anyways :

I'm graphing Watts values in a 1 minute interval consolidated as avg. Then this rolls up to the following retention schema :

```
retentions = 1min:15d,10min:1800d
```

I didn't set it up, I should have, this is just the default retention provided by that docker image.

Anyway, now my issue is that I send Watts values at a regular interval, supposed to represent the instant current consumption., they are avg aggregate in a 1mn sample.

I have no problem graphing the sum as long as I'm showing less than 15 days, I sum the values, then divide by 60 to get a Wh value.

Now, the problem is that I would need to do a different math for > 15 days because the aggregation is 10mn avg, so I would need to set my scale to `x/6` instead of 'x/60` but I keep thinking there must be a way to do that in graphite, as it knows the sample size the values are based of.

As an example, let's say that I get a steady 2000W for 20 days :

__<15d__
Using `consolidateBy()` I can force a `sum` function and divide by 60 to get Wh that, with `integral()` would start at 0 and be 33.33 for the first minute, then 2000 at the end of the first hour and so on.

__>15d__
If I do the same thing, I end up dividing by 60 a sum of 6 values instead of 60, and that doesn't work anymore.
I then need to start at 0, then get 333.33 for the first 10mn, 2000 at the end of the hour and so on, consistant result.

Does this makes sense to anyone?

**Comment by DanCech** [comment]
What I'd suggest is to use `summarize(summarize(<series>, '1h', 'avg'), '10y', 'sum')` which will give you a single value that is the total Wh for the period you're looking at.

This works by first taking an average W for each hour, which will be the Wh for that hour, then summing them up to get the total for the period.

**Comment by ybizeul** [comment]
Awesome, many thanks Dan, I was also able to use the integral to trace kWh for the different sensors!

Closing the issue!
