### ISSUE TITLE
grahite-web is very slow in 0.9.14

### ISSUE THREAD

**Issue by raju-divakaran** [graphite-project/graphite-web#1846]
Hello,

I upgraded graphite version from 0.9.13 to 0.9.14. Soon after the upgrade I can see both graphite-web and grafana is very very slow. I am using grafana 4.1.2. 

I see from the docs that while upgrading to 0.9.14 graphite's SQLite database needs to be upgraded. 

But in the PYTHONPATH=/opt/graphite/webapp, I am not having django-admin.py present there. Please share any ideas ? I must be missing something which someone has already come across of.

Thanks,
Raju.

**Comment by deniszh** [comment]
Hello Raju,

What's exactly became slow in your Graphite installation?
You can try database upgrade using 'python manage.py syncdb', but I'm doubt that it helps.

**Comment by raju-divakaran** [comment]
Hello, 

I am trying to find this. Both grafana and graphite web is slow. It was actually slow before the upgrade and the was the reason I tried the upgrade. But after upgrade it became very slow.

For me it looks the carbon cache is slow in responding to graphite webapp requests.

**Comment by raju-divakaran** [comment]
I am having these from webapp error log

[Mon Mar 06 17:14:48.178399 2017] [:error] [pid 47261] [remote 10.99.25.22:10944] mod_wsgi (pid=47261): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Mon Mar 06 17:14:48.178452 2017] [:error] [pid 47261] [remote 10.99.25.22:10944] IOError: failed to write data
[Mon Mar 06 17:14:48.985024 2017] [:error] [pid 47265] [remote 10.99.25.22:180] mod_wsgi (pid=47265): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Mon Mar 06 17:14:48.985671 2017] [:error] [pid 47265] [remote 10.99.25.22:180] IOError: failed to write data

[Mon Mar 06 17:14:50.262234 2017] [:error] [pid 3333] [remote X.X.X.X:4646] mod_wsgi (pid=47260): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Mon Mar 06 17:14:50.262554 2017] [:error] [pid 3333] [remote X.X.X.X:4646] IOError: failed to write data
[Mon Mar 06 17:14:50.598324 2017] [:error] [pid 3333] [remote X.X.X.X:4646] mod_wsgi (pid=47262): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Mon Mar 06 17:14:50.598446 2017] [:error] [pid 3333] [remote X.X.X.X:6363] IOError: failed to write data

I have masked the IP address and ports in above logs.

There are near to 3000 GET or POST requests against the grahite webapp.

Thanks

**Comment by deniszh** [comment]
It's hard to say from this error, maybe your instance is just overloaded. What's your hardware, which load average do you have, how many metrics are you processing?
