### ISSUE TITLE
python module tagging (deprecated)

### ISSUE THREAD

**Issue by pasanm** [graphite-project/graphite-web#1848]
Hi Guys,

I have upgraded my graphite installation os to latest debian version (9) stretch. After upgrading I found that graphite web app isn't working and it looks like your code is using a deprecated module 'tagging'
Its not available anymore in stretch and its being replaced  by a module called taggit.

would you please make a patch to deal with this ? 

[wsgi:error] [pid 4819:tid 140010429519040] ImportError: No module named tagging

new pkg ->  python-django-taggit. 
old pkg -> python-django-tagging

**Comment by deniszh** [comment]
Yes, we should migrate to taggit, but unfortunately it's not drop-in replacement, we should migrate there.
For now installing `django-tagging` is only way to make this work.

**Comment by pasanm** [comment]
Its cool. I got the package build for stretch :)

**Comment by jcharaoui** [comment]
Could you explain in more detail how you solved it?

**Comment by pasanm** [comment]
@jcharaoui  I got the python-django-tagging built for debian stretch and I also needed scandir to get the site back in working state.
python-django-tagging - Generic tagging application for Django projects (Python 2)
python-scandir - Backport of the "scandir" stdlib module (Python 2)
