### ISSUE TITLE
consolidateBy sum in v0.9.15 loses data as maxDataPoints decreases

### ISSUE THREAD

**Issue by jstangroome** [graphite-project/graphite-web#1849]
Given 100 consecutive data points in a single Whisper file with the integer values 1 through to 100.

Query the metric with `consolidateBy(..., 'sum')` and `target=json` and sum the values returned and the result is, correctly, 5050.

Add `maxDataPoints=101` to the query and the value is still, correctly, 5050.

Repeatedly reduce the value for `maxDataPoints` by 1 and requery. All the values returned continue to correctly sum to 5050 while `maxDataPoints` >= 50.

Once `maxDataPoints` is reduced to less than 50, ie less than half the total number of real data points, the sum of the returned values is incorrectly less than 5050. Eight different incorrect totals have been seen. Only ~11 values for `maxDataPoints`  under 50 returned the correct total of 5050 when the output was summed.

Is this expected behaviour that I am misunderstanding?

The attached script reproduces the scenario on a clean VM from running `vagrant up` using the `Vagrantfile` from https://github.com/obfuscurity/synthesize:

[consolidateByTest.txt](https://github.com/graphite-project/graphite-web/files/837612/consolidateByTest.txt)

**Comment by deniszh** [comment]
Hello @jstangroome,
Ah, I know what's going on. According to [code](https://github.com/graphite-project/graphite-web/blob/ed0f080f5fbc7b41b2296ea97f69c8141dd1c63b/webapp/graphite/render/views.py#L146-L164) if you have less then 100 datapoints - it should enable consolidation function - and by default timeseries have 'avg' as consolidation function. 
But if you have maxDataPoints >=50 [valuesPerPoint](https://github.com/graphite-project/graphite-web/blob/ed0f080f5fbc7b41b2296ea97f69c8141dd1c63b/webapp/graphite/render/views.py#L150) is rounded to 1,  so, making no consolidation.
So, consolidation starts working only when valuesPerPoint becoming less then 50, and consolidation is always "average".

**Comment by deniszh** [comment]
I'm not sure should we fix that (and how to do so w/o keeping compatibility)

**Comment by jstangroome** [comment]
@deniszh How can consolidation always be using 'avg'?

1. My test queries `target=consolidateBy(metric, 'sum')`
1. The `consolidateBy` function sets the `series.consolidationFunc`: https://github.com/graphite-project/graphite-web/blob/0.9.15/webapp/graphite/render/functions.py#L794
1. When `format == 'json'` and `maxDataPoints < numberOfDataPoints` then `series.consolidate(valuesPerPoint)` is called: https://github.com/graphite-project/graphite-web/blob/0.9.15/webapp/graphite/render/views.py#L163 
1. The series iterator checks `valuesPerPoint` and `consolidationFunc` to apply the chosen `sum` aggregation to produce the returned data: https://github.com/graphite-project/graphite-web/blob/0.9.15/webapp/graphite/render/datalib.py#L77

**Comment by jstangroome** [comment]
Also, `numberOfDataPoints` == 100 and the consolidation works correctly for all values of `maxDataPoints` from 50 to 101 inclusive. Only when `maxDataPoints` <= 49 do incorrect results occur.

I've just repeated the test with a seed Whisper file containing only 10 data points and I'm fairly sure the problem is due to the "nudge" deleting the first data points: https://github.com/graphite-project/graphite-web/blob/0.9.15/webapp/graphite/render/views.py#L156-L162

The [original commit introducing the nudge logic](https://github.com/graphite-project/graphite-web/pull/170/commits/4b8cac3f1b7289c899b7a513d9c28254bd6abf4a) doesn't seem to add much insight beyond the comment "removing 'jitter' seen when refreshing" which in my mind would mostly be  applicable when the requested time range is relative to the wall clock and time is passing between queries.

I wonder whether the ability to disable the nudge logic would be a useful render query parameter, especially for JSON queries where the results are often used for purposes other than drawing line charts.

Details of test output with only 10 real data points: [output10.txt](https://github.com/graphite-project/graphite-web/files/840102/output10.txt)

**Comment by deniszh** [comment]
> The series iterator checks valuesPerPoint and consolidationFunc to apply the chosen sum aggregation to produce the returned data: https://github.com/graphite-project/graphite-web/blob/0.9.15/webapp/graphite/render/datalib.py#L77

Yes, it checks. But I do not see code where consolidation funcion propagates. By default it's 'avg'.
Maybe I wrong, @Dieterbe also [mentioned](https://grafana.com/blog/2016/03/03/25-graphite-grafana-and-statsd-gotchas/#runtime.consolidation) that runtime consolidation should obey to consolidateBy but I do not see that in the code, at least for maxDataPoints.

> Also, numberOfDataPoints == 100 and the consolidation works correctly for all values of maxDataPoints from 50 to 101 inclusive. Only when maxDataPoints <= 49 do incorrect results occur.

Maybe, you're right. maxDataPoints <= 49 triggering change of valuesPerPoint from 2 to 3 and it can affect nudge logic.

>I wonder whether the ability to disable the nudge logic would be a useful render query parameter, especially for JSON queries where the results are often used for purposes other than drawing line charts.

If it helps - sure, why not. Try to comment out [line 159](https://github.com/graphite-project/graphite-web/blob/0.9.15/webapp/graphite/render/views.py#L159) and check
