### ISSUE TITLE
Question: feed data in graphite

### ISSUE THREAD

**Issue by Himanshu-pupneja** [graphite-project/graphite-web#1851]
Hi,

I just wanted a suggestion.
I have 50k metric to feed in every 5 minutes. can you suggest the best way to achieve this?
In the current situation i have 1 server with 2 cpu and 8GB memory, if i push data in one go there are chances of data loss.
Your response will be really appreciated.

Thanks,
Himanshu

**Comment by deniszh** [comment]
Hi @Himanshu-pupneja ,
You can use [pickle protocol](https://graphite.readthedocs.io/en/latest/feeding-carbon.html#the-pickle-protocol) or [AMQP](https://graphite.readthedocs.io/en/latest/feeding-carbon.html#using-amqp)

**Comment by Himanshu-pupneja** [comment]
Hi @deniszh ,
I tried that a long back but didn't work well.
i will get it another try and see how it goes.

Thanks for your time and suggestion.
-Himanshu
