### ISSUE TITLE
ModuleNotFoundError: No module named 'ConfigParser'

### ISSUE THREAD

**Issue by shuiiiiiimu** [graphite-project/graphite-web#1853]
```bash
Collecting whisper (from -r requirements.txt (line 7))
Collecting carbon (from -r requirements.txt (line 8))
Collecting configparser (from -r requirements.txt (line 9))
  Using cached configparser-3.5.0.tar.gz
Collecting graphite-web (from -r requirements.txt (line 11))
  Using cached graphite-web-0.9.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hw/sj17hcqn2zg0wrlq73fnpvs40000gn/T/pip-build-i_ejqz4a/graphite-web/setup.py", line 4, in <module>
        import ConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hw/sj17hcqn2zg0wrlq73fnpvs40000gn/T/pip-build-i_ejqz4a/graphite-web/
```

installed `configparser`, but not working.

how can i slove it?

**Comment by deniszh** [comment]
Are you trying to install Graphite on python 3 ? It will not work, only python 2.7 is supported now

**Comment by deniszh** [comment]
Hello @zhangsm,
Was it really python 3 or other issue?

**Comment by ElsaHuang** [comment]
same issue here...install Graphite also failed.
----------------------
pip install Graphite
Collecting Graphite
  Downloading graphite-0.71.tar.gz (56kB)
    100% |████████████████████████████████| 61kB 221kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mn/fyndsss93cvcj14gjgc81g5w0000gn/T/pip-build-n0rhcr3p/Graphite/setup.py", line 23
        print "EZ_setup"
                       ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mn/fyndsss93cvcj14gjgc81g5w0000gn/T/pip-build-n0rhcr3p/Graphite/

**Comment by brutasse** [comment]
@ElsaHuang you're trying to install Graphite with Python 3, which isn't supported. Can you try with Python 2.7?

**Comment by deniszh** [comment]
It's even worse. @ElsaHuang trying to install https://pypi.python.org/pypi/graphite/0.71 - I do not even know what it is. 
@ElsaHuang - please follow install instruction from https://graphite.readthedocs.io/en/latest/install.html

**Comment by deniszh** [comment]
Does it help, @ElsaHuang ?
@zhangsm ?

**Comment by JZO** [comment]
still no python3 support?

**Comment by DanCech** [comment]
@JZO no-one has had time to port it, if you want to make a start PRs are gladly accepted

**Comment by DanCech** [comment]
Python 3.x is now supported
