### ISSUE TITLE
Refactoring of moving* functions

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#1854]
It looks like the moving* functions share 99% of their code, differing only in the aggregation function applied (safeMin, safeMax, etc) and the name of the new series, so at first glance it seems like it should be possible to create a helper function that takes a seriesList, period, aggregation function and name template that all the moving* functions can use.

**Comment by DanCech** [comment]
I'll see if I can take a crack at this.

**Comment by deniszh** [comment]
I think it's done, @DanCech ?

**Comment by DanCech** [comment]
Yup 👍
