### ISSUE TITLE
Graphite do not have rpm. Please make rpm.

### ISSUE THREAD

**Issue by patsevanton** [graphite-project/graphite-web#1856]
Graphite do not have rpm. Please make rpm.
Thanks

**Comment by deniszh** [comment]
All Graphite packaging are made by corresponding distro's maintainers. We're not making RPM, DEB, PKG or any other packages except python one.
You can use [`fpm`](https://github.com/jordansissel/fpm) to build own RPM if needed, as described e.g. in [this article](http://www.michael-noll.com/blog/2013/06/06/installing-and-running-graphite-via-rpm-and-supervisord/#building-rpms-for-graphite-0910).
