### ISSUE TITLE
Fix changelog before 1.0.0 release

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#1857]
https://github.com/graphite-project/graphite-web/blob/20d443b7158b3e601b0f77279247804ca7b4fc3a/docs/releases/0_10_0.rst should be renamed to 1_0_0.rst and we need to update info there too

**Comment by deniszh** [comment]
PR for 0.9.x https://github.com/graphite-project/graphite-web/pull/1879 is created.
As we should sync docs for both releases let's discuss and fix all issues there first and I port that to master.

**Comment by deniszh** [comment]
Right now I see couple of issues there.
1. We should release carbonate 1.0.0 or exclude it from release
2. We should or exclude Ceres and mark it unsupported or include it in 1.0.0 release

**Comment by iksaif** [comment]
1. Yes we need to tag carbonate can you do that ?
2. I would exclude Ceres

**Comment by deniszh** [comment]
1. Tagged as 1.0.0-pre1 now - https://github.com/graphite-project/carbonate/releases
2. OK

**Comment by deniszh** [comment]
I set April 12 as the release date for 1.0.0 and 0.9.16 and push changes to 0.9.x, 1.0.x and master branches.
