### ISSUE TITLE
Multiple graphs in same svg

### ISSUE THREAD

**Issue by shivagopalan** [graphite-project/graphite-web#1861]
Hello, I am using Graphite Render API to render graphs. I have a couple of questions.
1. I need to display multiple graphs on the same page(same SVG). Is this possible? I tried using "target={metric1}&target={metric2}", but then both metrics are displayed on the same graph. This is not what I want. Please advise how to render separate graphs for separate metrics on the same page(something similar to how the Dashboard displays separate graphs)
2. I would like to use the drawAsInfinite function to mark all events starting from 3 hours ago. I tried this "target=drawAsInfinte(events(*))&from=-3h", but this seems to be unsupported. What is the correct way to use wildcards for events? 
Your help is highly appreciated. 

Thank you

**Comment by obfuscurity** [comment]
@shivagopalan Just use a separate URL for each graph.

**Comment by obfuscurity** [comment]
@shivagopalan The events argument must be a quoted string, e.g. `events('*')`.

**Comment by shivagopalan** [comment]
@obfuscurity Thanks a lot for your response. 
1. I do not understand how I can use two URL's for the same page. Maybe I am misunderstanding your point, could you show me an example of how this works?
2. Thanks, this worked. As a follow up, I would like to assign a separate color to each of the events returned. I tried doing this - "target=drawAsInfinite(events('*'))&colorList=red,yellow,green,purple" , but the colors are not getting assigned to each of the individual events. Instead, all events are getting marked by the same color. What is the right way to do this?

Thank you once again. Appreciate your help

**Comment by deniszh** [comment]
@shivagopalan:
In current codebase, it's not possible to render multiple graphs on the same SVG or PNG image. Please use dashboard software to achieve this, e.g. [Grafana](https://grafana.com/grafana). Grafana also can help you with showing annotations.

**Comment by obfuscurity** [comment]
Let's clarify what we're talking about. It's absolutely possible to render a virtually infinite number of graphs on the same page by sourcing each of them individually, e.g.:

```
<img src="http://graphite/render?target=foo.a" />
<img src="http://graphite/render?target=foo.b" />
<img src="http://graphite/render?target=foo.c" />
```

If you want a dashboard, use a dashboard. But it sounded to me like @shivagopalan was trying to compose a custom web page with multiple graphs.

**Comment by deniszh** [comment]
Sure! I'm not going to downplay your explanation, @obfuscurity. It really depends on the task, maybe for @shivagopalan's task using dashboard, especially such complicated as Grafana could be clear overkill.

**Comment by deniszh** [comment]
And I don't know how you can color `drawAsInfinite()` graph btw.

**Comment by obfuscurity** [comment]
Eh? http://obfuscurity.com/2012/04/Unhelpful-Graphite-Tip-1

**Comment by deniszh** [comment]
I mean, as @shivagopalan wants - with '*' as event and color list.

**Comment by shivagopalan** [comment]
@deniszh Thank you for your response. 
1. I believe I may have to use Grafana eventually for my work, but for now the option @obfuscurity suggested should work just fine. Thank you for that, makes my life simpler :)
2. I am trying to do something like this - "&target=drawAsInfinite(color(events(%27*%27),["red","green"]))&from=18:10_20170317&until=18:30_20170317&format=svg" but not successful so far. @obfuscurity thanks for sharing that link. I went through it but could not find how to assign a colorList to a number of events. Please advise if this functionality is supported.

**Comment by obfuscurity** [comment]
The link was just to demonstrate that you could apply colors to a `drawAsInfinite()` series. It doesn't address your specific use case.

**Comment by shivagopalan** [comment]
@obfuscurity Sure. Thanks for your help. Please let me know if you are aware of this functionality being available. @deniszh Thank you very much. I will continue to look at this usecase.
