### ISSUE TITLE
Prepare for (final) 0.9.16 release

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#1869]
@DanCech @iksaif @obfuscurity - how do you feel about final 0.9.16 release, together with 1.0.0?
It will address some nasty bugs in 0.9.15, like #1868 and a couple of others.
Of course, we should mention that upgrade to 1.0.0 is encouraged, and you shouldn't use 0.9.16 until you have some serious reason to do so, like legacy OS, python etc.

**Comment by deniszh** [comment]
I should fix documentation for 0.9.x (mentioning 1.0.0 and legacy status) and prepare changelog too.
Will try to do that this weekend.

**Comment by DanCech** [comment]
I'm very much in favor of a bugfix release in the 0.9.x branch

**Comment by deniszh** [comment]
PR for 0.9.x https://github.com/graphite-project/graphite-web/pull/1879 is created.
As we should sync docs for both releases let's discuss and fix all issues there first and I port that to master.

**Comment by deniszh** [comment]
I set April 12 as the release date for 1.0.0 and 0.9.16 and push changes to 0.9.x, 1.0.x and master branches.
