### ISSUE TITLE
Official Graphite docker images

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#1874]
Hello!
I'm personally not a great fan of Docker, especially on PROD, but I should admit that's a great packer tool, especially for packages with multiple dependencies.
So, I think we need to create official docker images for 1.0.0 too.
Current issues:
1. I can't add 'graphite' or 'graphiteproject' organization on dockerhub for some reason. Now I created [graphiteapp](https://hub.docker.com/u/graphiteapp/dashboard/). @obfuscurity - did you create one? I can't find it using search, though.
2. Current most popular graphite images which we have on dockerhub:
https://github.com/hopsoft/docker-graphite-statsd
https://github.com/nickstenning/docker-graphite
https://github.com/sitespeedio/docker-graphite-statsd
Should we fork them or create separate one?
3. Should we include statsd? or Grafana?

**Comment by obfuscurity** [comment]
Nope, I've never created anything on dockerhub.

**Comment by iksaif** [comment]
I would include Grafana and statsd or collectd.

**Comment by diceone** [comment]
I would NOT include grafana or statsd/collectd. It would blow up the container image. There is an official grafana image.

**Comment by DanCech** [comment]
I'd propose a small fleet of images that are designed to work together, with carbon and graphite-web as the core, and potentially modified versions of the grafana and/or statsd/collectd images to help people get going quickly.  Once they're published then it would be relatively easy to give people a docker-compose.xml that could fire up a complete stack based on the individual images.

**Comment by iksaif** [comment]
People have been asking me for a BigGraphite image, I'll be happy to base it on top of a Graphite image.

**Comment by ccoenen** [comment]
All of the inofficial docker images are out of date (0.9.x), but I can report that I'm using the hopsoft image succesfully. Basically, I want exactly that but with the current stable ;-)

**Comment by deniszh** [comment]
OK, I just pushed this - https://github.com/graphite-project/docker-graphite-statsd and this - https://hub.docker.com/r/graphiteapp/graphite-statsd/. I asked @hopsoft's permission to reuse his code.
Any suggestions / patches etc. are welcome!

**Comment by deniszh** [comment]
PR for website - https://github.com/graphite-project/graphite-project.github.io/pull/35
Not sure should we push it or mentioning in Install section should be enough.

**Comment by cclauss** [comment]
Is this issue closed?

**Comment by deniszh** [comment]
Yes, we have docker image and it has open repo now - https://github.com/graphite-project/docker-graphite-statsd
