### ISSUE TITLE
Inconsistent Time format render on X-Axis

### ISSUE THREAD

**Issue by mleinart** [graphite-project/graphite-web#188]
#### Imported from https://bugs.launchpad.net/bugs/1005924
|||
|----|----|
|Reported by|[coj-tdchosting](https://launchpad.net/~coj-tdchosting)|
|Date Created|May 29, 2012|
I'm a bit puzzled by the different time formats rendered when you select 

`render?target=servers.someserver.somemetric&from=-10h`

and 

`render?target=servers.someserver.somemetric&from=-1h`

When I render the latter, i shows the time format in 24 hour format (i.e. 16:00, 18:00 etc) but when i render it with the first i show time in AM/PM notation.

At best this is rather inconsistent.. but I'm sure it must be a bug :)

Kind regards,

Carsten O. Jensen

**Comment by ojilles** [comment]
+1

**Comment by ojilles** [comment]
Being European and all, I think @mleinart 's change is a more sensible default and makes due with less precious pixels.

Agreed that his should be a config setting. The easiest way I can think of is some 12/24 hr switch. Would that be good enough? Making all of xAxisConfigs' dict's configurable is overkill in my opinion.

(I could probably make a PR for that).

**Comment by RichieB2B** [comment]
This is very silly. All formats of the xAxisConfig use %H except for the two most often used ones which use %l%p. Until this is configurable @mleinart 's fix should be the default IMHO.

**Comment by taschauer1** [comment]
+1
