### ISSUE TITLE
Fix download page

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#1881]
Current download page is located on launchpad and outdated as hell. We should or 
- refresh it with all new releases (including 1.0.0) 
or 
- create download page on http://graphiteapp.org
or
- remove mentions of download page at all

**Comment by obfuscurity** [comment]
I'd love to see downloads incorporated into the http://graphiteapp.org/ website. /cc @mattttt @bulletfactory @DanCech

**Comment by iksaif** [comment]
Any news from somebody with accessto graphiteapp.org?

**Comment by obfuscurity** [comment]
@iksaif It's the https://github.com/graphite-project/graphite-project.github.io project using GitHub Pages. Everyone in @graphite-project/committers has access.

**Comment by deniszh** [comment]
If I understand correctly it's more about design, right, @obfuscurity ?

**Comment by obfuscurity** [comment]
Not sure I understand your question @deniszh.

**Comment by deniszh** [comment]
Yep, first I also mistakenly decided that only @mattttt @bulletfactory @DanCech have access to graphiteapp.org
Now we know that everybody has access, not sure if everybody has enough experience with web design to put properly looking download page to graphiteapp.org...

**Comment by piotr1212** [comment]
What do you want to have on the download link? Preferred way to install is using `pip install xx` or `docker run xx`.

**Comment by deniszh** [comment]
@piotr1212 : if you google "graphite download" second result will bring you to http://graphite.wikidot.com/downloads, which say "Tarballs for the latest release can be downloaded from https://launchpad.net/graphite/+download"
And https://launchpad.net/graphite/+download has very dated tarballs.
So, initial idea was to put tarballs there.

**Comment by piotr1212** [comment]
Can't we just get rid of the wikidot page. It all seems dated which is only confusing users.

**Comment by piotr1212** [comment]
Launchpad also has a lot of info in answers section. Sometimes people need to download an older version, so not sure if that needs to be removed.

Anyway, I see no point in keeping the wikidot. Who is admin there?

**Comment by piotr1212** [comment]
I see that @mleinart is site admin at wikidot.

**Comment by obfuscurity** [comment]
@mleinart @SEJeff and myself are all wikidot admins for the old Graphite site.

**Comment by obfuscurity** [comment]
@mleinart @SEJeff and myself are all wikidot admins for the old Graphite site.
