### ISSUE TITLE
Graphite 1.0.0-pre1 is leaking memcached connections

### ISSUE THREAD

**Issue by iksaif** [graphite-project/graphite-web#1885]
Using the new version we found out that we maxed out the 30k connection limit for memcached (using 4 graphite-web + 4 memcached). Looks like the new version isn't closing the connections as it was before. That might be linked to the new worker pool thing.

**Comment by iksaif** [comment]
With 9136 being the pid of one of the processes:

{code}
$ sudo netstat -p | grep 9136 | wc -l
408
$ sudo netstat -p | grep 9136 | wc -l
410
$ sudo netstat -p | grep 9136 | wc -l
411
$ sudo netstat -p | grep 9136 | wc -l
417
{code}

**Comment by iksaif** [comment]
Current theory is that the memcached driver will create a set of connection per thread.
- 4 connections per thread
- 10 * 10 + 10 threads per uwsgi worker (=110)
- 440 connections per uwsgi worker
- 70 workers -> bazillions of connections.

I'm pretty sure that the default number of worker is too big since in most situation Graphite will be run with uwsgi or similar which will probably have one process per request.

**Comment by iksaif** [comment]
Drasticaly reducing the number of workers is a valid workaround. I think we should have more sensible defaults.

**Comment by iksaif** [comment]
@DanCech  would you aggree to decrease the number of threads that are set by default to 1 per server and 1 base thread ?

**Comment by DanCech** [comment]
I spoke to @replay and he's going to look into it, reducing the number of worker threads is an option.

**Comment by replay** [comment]
@iksaif is it possible that in your settings you had `USE_WORKER_POOL=True` and `REMOTE_PREFETCH_DATA=False`? 
In that case I think I can see why that's happening. 
Could you try setting `REMOTE_PREFETCH_DATA` to `True` just to see if this fixes it?

**Comment by iksaif** [comment]
Yes, I have `REMOTE_PREFETCH_DATA=False` (which is the default I believe).

In any case, since in most cases people will use graphite with uwsgi or similar, I don't think we should have more than one thread by backend by default (it also uses a lot more memory than before).

**Comment by replay** [comment]
Yes I agree that one thread per backend should be a sensible default setting and should be sufficient for most people.

So i think the reason for the large number of connections is that `To provide thread-safety, a different instance of the cache backend will be returned for each thread.`:
https://docs.djangoproject.com/en/1.10/topics/cache/#accessing-the-cache

It should be relatively easy to wrap the cache with locks and only instantiate it once for each of our thread pools, but if the default setting is to have only one worker per pool then this should probably not be necessary.

**Comment by deniszh** [comment]
Fixed in master and 1.0.x
