### ISSUE TITLE
Importing graphite.carbonlink is hard

### ISSUE THREAD

**Issue by iksaif** [graphite-project/graphite-web#1886]
carbonlink.py does a bunch of stuff in the body of the module, including using settings, which make it very problematic to import in finder/reader plugins. Even worse it's being imported by readers.py

I'm trying to refactor this code to delay the initialization of CarbonLinkPool()

@graphite-project/committers , do you think it would be fine to break the API here, and make carbonlink.CarbonLink a callable instead of an instance ?

**Comment by deniszh** [comment]
I'm not sure that an API officially, and I'm not sure that many people using that out there, so I'm OK with that.
