### ISSUE TITLE
Null data from a specific server

### ISSUE THREAD

**Issue by UKNC** [graphite-project/graphite-web#1892]
Data I send to graphite server from a specific machine have null values inside. 
Let's make test. Here I send data from my home laptop:

`while true; do echo "test4issue $(date +%s) $(date +%s)" | nc ${SERVER} ${PORT} ; sleep 1; done`

And here is what I get on the graphite server:

> /render?width=400&from=-20minutes&until=now&height=250&target=test4issue&title=test4issue&format=json
> 
> [{"target": "test4issue", "datapoints": [[1491395519.0, 1491395460], [1491395579.0, 1491395520], [1491395639.0, 1491395580], [1491395698.0, 1491395640], [1491395759.0, 1491395700], [1491395819.0, 1491395760], [1491395878.0, 1491395820], [1491395939.0, 1491395880], [1491395999.0, 1491395940], [1491396059.0, 1491396000], [1491396119.0, 1491396060], [1491396178.0, 1491396120], [1491396239.0, 1491396180], [1491396298.0, 1491396240], [1491396359.0, 1491396300], [1491396418.0, 1491396360], [1491396479.0, 1491396420], [1491396539.0, 1491396480], [1491396599.0, 1491396540], [1491396648.0, 1491396600]]}]
> 

Now, let's do it from the problematic server:

`[root@front ~]# while true; do echo "test4issueProblem $(date +%s) $(date +%s)" | nc ${SERVER} ${PORT} ; sleep 1; done
`
And here is the data I read on graphite:

> /render?width=400&from=-20minutes&until=now&height=250&target=test4issueProblem&title=test4issueProblem&format=json
> 
> [{"target": "test4issueProblem", "datapoints": [[null, 1491395820], [null, 1491395880], [null, 1491395940], [null, 1491396000], [null, 1491396060], [null, 1491396120], [null, 1491396180], [null, 1491396240], [null, 1491396300], [null, 1491396360], [null, 1491396420], [null, 1491396480], [null, 1491396540], [null, 1491396600], [null, 1491396660], [null, 1491396720], [null, 1491396780], [null, 1491396840], [null, 1491396900], [null, 1491396960]]}]

This is the only server of many I have that has such strange behavior. What can it be?

**Comment by deniszh** [comment]
Hi @UKNC ,
Could you please elaborate what you mean when saying "server"? Is it separate instance of Carbon and Graphite-web, right? Or something else?

**Comment by UKNC** [comment]
I have graphite and carbon instance running on CentOS6. Graphite runs on 8080.

> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name   
> tcp        0      0 0.0.0.0:20000               0.0.0.0:*                   LISTEN      28047/node /home/mi 
> tcp        0      0 0.0.0.0:20001               0.0.0.0:*                   LISTEN      28041/node /home/mi 
> tcp        0      0 0.0.0.0:10050               0.0.0.0:*                   LISTEN      21823/zabbix_agentd 
> tcp        0      0 127.0.0.1:27017             0.0.0.0:*                   LISTEN      2911/mongod         
> tcp        0      0 0.0.0.0:3306                0.0.0.0:*                   LISTEN      12439/mysqld        
> tcp        0      0 0.0.0.0:8080                0.0.0.0:*                   LISTEN      10139/httpd         
> tcp        0      0 0.0.0.0:80                  0.0.0.0:*                   LISTEN      12699/nginx         
> tcp        0      0 0.0.0.0:2003                0.0.0.0:*                   LISTEN      30151/python        
> tcp        0      0 0.0.0.0:2004                0.0.0.0:*                   LISTEN      30151/python        
> tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      7405/sshd           
> tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN      8197/master         
> tcp        0      0 0.0.0.0:7002                0.0.0.0:*                   LISTEN      30151/python

**Comment by deniszh** [comment]
Ah, it's a problem with graphite 'client' not server. I can imagine firewall or something like that. You can use `tcpdump` or `ngrep` on graphite server to check is really data coming from the problematic server. That's a good article about solving that type of issues - https://theholyjava.wordpress.com/2014/05/05/graphite-shows-metrics-but-no-data-troubleshooting/

**Comment by UKNC** [comment]
Great thanks for the link which mentioned `whisper-dump.py`. After looking at time stamps  it turned out the server's `hwclock` and `date` were incorrect. 
Thanks again!
