### ISSUE TITLE
Performance penalty when using more than 100 Wildcards in a query path

### ISSUE THREAD

**Issue by zivillian** [graphite-project/graphite-web#1897]
### Description
I observed a huge performance hit when using more than 100 Wildcards - the query time dropped from around 10 seconds for 100 Wildcards to over 60 seconds for 101 Wildcards. I have only tested this on [0.9.15](https://github.com/graphite-project/graphite-web/blob/449e33fe99d64dc5f2514ca3324ac606a27763ac/webapp/graphite/storage.py#L265), but from the code this issue seems to be still present in [master](https://github.com/graphite-project/graphite-web/blob/64698ce9c0f123008ab78290499e77871b3dbc94/webapp/graphite/finders/__init__.py#L51).

I traced the issue down to the [fnmatch](https://hg.python.org/cpython/file/2.7/Lib/fnmatch.py#l54) module, which has an internal cache for compiled regexes which is cleared after 100 entries. Using more than 100 wildcards defeats the whole cache, so the regular expressions are recompiled each time. (For Python 3 the limit seems to be [a bit higher](https://github.com/python/cpython/blob/bd48d27944453ad83d3ce37b2c867fa0d59a1c15/Lib/fnmatch.py#L38))

In my scenario I'm using a large value list like this:
`prefix.{2,4,6,...,198,200}.component.*.value`
but as far as I can tell, this will also occur if there is any combination of more than 100 wildcards.

From my opinion, there are two possible solutions:

#### 1. try to prevent fnmatch.filter
fnmatch is only needed if the pattern contains any special char ( * ? [ ). If the variant or pattern does not contain any of them, fnmatch could be skipped and a simple string comparison can be used. In this case the case sensitivity should depend on the os (like with [fnmatch](https://hg.python.org/cpython/file/2.7/Lib/fnmatch.py#l58))

#### 2. workaround in client
In my case the targets are combined using an aggregation function (sum), so I could use a query which calls sum() with multiple series (each having less than 100 wildcards) instead of a single series with all values.
In this case the documentation should be extended to clearly state that many wildcards will effect the performance.

Simply increasing fnmatch._MAXCACHE will only move the limit (which in my case may be up to 3000 wildcards/values).

### Version
- graphite-web v0.9.15 (with #505)
- python 2.7.12
- ubuntu 16.04.1 LTS

**Comment by zivillian** [comment]
The example target may be misleading - there is an additional wildcard before the value list:

`prefix.*.{2,4,6,...,198,200}.component.*.value`

This wildcard is matching some hundred folders, so the regular expressions are recompiled for each match for the first star. Without this first wildcard, the performance impact may be negligible.

**Comment by iksaif** [comment]
Using tons of wildcard in Graphite is an anti-pattern IMHO.
That being said, did you try changing  fnmatch._MAXCACHE in local_settings.py ?

I also wonder if https://github.com/criteo/biggraphite/blob/master/biggraphite/glob_utils.py is affect or not.

**Comment by zivillian** [comment]
I agree, that many wildcards may seem like an anti pattern. I'll try to illustrate my usecase - maybe there is a more elegant way to query the result.

We are using graphite to store usage metrics from our customers over time. The metrics are grouped by metric type - not by customer. The reference to our customer is stored in a different database. This way we can dynamically change the customer reference for any metric or exclude a single metric without deleting it from graphite.
The metrics are mostly stored using immutable guids, so my the structure in this scenario is something like this:

- usage
  - iaas
    - b057671c-90d4-4081-ada4-31eb346edc72
      - cpu
      - ram
      - disks
        - 06a58854-4a28-4de8-94a8-36b38ea2fd44
          - total
          - used
    - 375a06f6-b5e5-4b21-803f-efa969b11300
      - ... (1500 more)
    - ...

the graphite query then looks like this:

`alias(sumSeries(usage.iaas.*.disks.{06a58854-4a28-4de8-94a8-36b38ea2fd44,...}.used), 'Disk Size')`

I am able to remove the first wildcard an send a value list containing all the guids, but this will not help, since the value list is also matched via fnmatch. Another approach my be to specify multiple targets for sumSeries without any value list or wildcard - this is what I meant by "workaround in client".

Disclaimer: I'm not a python developer

I tried your suggestion to set the _MAXCACHE in local_settings.py and this solved the performance issue. My concern is, that this may inttroduce a memory constraint for large queries and I guess that I need to set this to a very high value like 3000.

As far as I can tell, the biggraphite implementation will not work out of the box, since this creates a single regex for the whole target, which will noch work with the recursive directory traversal currently implemented.

**Comment by iksaif** [comment]
Could you trying measuring the effects of raising _MAXCACHE ? If it doesn't change the memory consumption much and improve performances, that's probably good enough.

Regarding the way of storing things, when you end up aggregating a lot of metrics, you should some time consider sotring also the pre-aggregated value to make read queries lighter. Not sure it applies to your usecase.

**Comment by zivillian** [comment]
I measured 5 to 10 requests for the above request with 243 values in the value list and 1543 matches for the first wildcard.

#### _MAXCACHE = 3000
- Response Time: 5,55s avg (may be limited by IO)

#### _MAXCACHE = 300
- Response Time: 7,08s avg (may be limited by IO)

#### _MAXCACHE = 100
- Response Time: 280s avg

I tried to also measure the memory usage, but was unable to find any memory metric which shows reasonable difference. Also the wsgi processes seem to be recycled regularly after some time, so the largest difference I saw in `ps aux` was 850MB vs. 580 MB (VSZ).

I will set _MAXCACHE to 3000 for now and look weather any memory problems arise.

**Comment by zivillian** [comment]
We've tested the workaround over the last few weeks and had no problems until now. I guess this can be closed for now.
