### ISSUE TITLE
CARBONLINK_HOSTS + REPLICATION_FACTOR issue

### ISSUE THREAD

**Issue by blafrisch** [graphite-project/graphite-web#1905]
I'm trying to wrap my head around CARBONLINK_HOSTS and REPLICATION_FACTOR as something doesn't appear to be correct in either the code or the documentation. Say I have 3x hosts with 2x carbon caches each and I wanted a replication factor of 3 I'd have these example DESTINATIONS in carbon relay:
['10.0.0.1:2003:a', '10.0.0.1:2103:b',
'10.0.0.2:2003:a', '10.0.0.2:2103:b',
'10.0.0.3:2003:a', '10.0.0.3:2103:b']

According to the documentation each graphite-web server would have CLUSTER_SERVERS set to the other servers that are not itself, so 10.0.0.1 would have ['10.0.0.2:80', '10.0.0.3:80'] which makes sense. But graphite-web will not start on 10.0.0.1 if REPLICATION_FACTOR=3 and CARBONLINK_HOSTS=['10.0.0.1:7002:a', '10.0.0.1:7102:b'] because of an exception in CarbonLinkPool that len(CARBONLINK_HOSTS) cannot be < REPLICATION_FACTOR.

Everything would make sense if CARBONLINK_HOSTS were meant to be == DESTINATIONS. Am I missing something? Is the documentation wrong? Is the code with the exception incorrect?

I'm trying this out with the latest carbon and graphite-web, 1.0.0. I'm using django 1.9.13.

**Comment by cbowman0** [comment]
I understand the code to need to know all of the cache instances in order to properly perform the consistent hashing that carbon relays does.  So, set the value of `CARBONLINK_HOSTS` to include the same set of cache hosts as the relay but with the ports changed to match the cache configs.  Based on your example, if I didn't mess it up, it would be `CARBONLINK_HOSTS=['10.0.0.1:7002:a', '10.0.0.1:7102:b', '10.0.0.2:7002:a', '10.0.0.2:7102:b', '10.0.0.3:7002:a', '10.0.0.3:7102:b']`

If I'm wrong, I'm sure it will be pointed out quickly.

**Comment by blafrisch** [comment]
That's why I raised the question because the documentation around CARBONLINK_HOSTS says "If multiple carbon-caches are running on this machine, each should be listed here so that the Graphite webapp may query the caches for data that has not yet been persisted. Remote carbon-cache instances in a multi-host clustered setup should not be listed here." If the documentation is to be believed then CARBONLINK_HOSTS should not contain 10.0.0.2 and 10.0.0.3 in 10.0.0.1's local_settings.

**Comment by deniszh** [comment]
Graphite is not designed to use remote CARBONLINK connections, it's an anti-pattern. You should install carbon-caches only on localhost, and include 'em in local_settings.py, and then include remote _graphite-web_ in CLUSTER_SERVERS (and not remote carbon daemons).
So, include only _local_ CARBONLINK_HOSTS to each local_settings.py (in same order as in relay), and include all other graphite-web servers (except local) to CLUSTER_SERVERS (in any order).

**Comment by blafrisch** [comment]
Okay, so the exception on line 40 of carbonlink.py is erroneous. This is what I was thinking. There's no other way that CARBONLINK_HOSTS can be local and have a RF > 1 with more than 1 host.

**Comment by deniszh** [comment]
Sorry, @blafrisch, but I'm not getting your way of thinking or your setup. Could you please elaborate it a little bit more?

**Comment by deniszh** [comment]
REPLICATION_FACTOR should be defined for picking a right instance of carbon-cache.

**Comment by blafrisch** [comment]
3x hosts: 10.0.0.1, 10.0.0.2, and 10.0.0.3 for simplicity.
2x carbon caches per host: instance 'a' bound to port 2003 for LINE_RECEIVER_PORT and port 7002 for CACHE_QUERY_PORT; instance 'b' bound to port 2103 for LINE_RECEIVER_PORT and port 7102 for CACHE_QUERY_PORT

Carbon relay configured with the following 
DESTINATIONS = ['10.0.0.1:2003:a', '10.0.0.1:2103:b', '10.0.0.2:2003:a', '10.0.0.2:2103:b', '10.0.0.3:2003:a', '10.0.0.3:2103:b']
REPLICATION_FACTOR = 3
DISTINCT_REPLICAS = True

Example graphite-web config on 10.0.0.1:
CLUSTER_SERVERS = ['10.0.0.2:80', '10.0.0.3:80']
CARBONLINK_HOSTS = ['10.0.0.1:7002:a', '10.0.0.1:7102:b']
REPLICATION_FACTOR = 3

A graphite-web server cannot start with this configuration due to len(CARBONLINK_HOSTS) < REPLICATION_FACTOR.

**Comment by deniszh** [comment]
I got your idea, but Graphite just not designed to work that way, unfortunately.
Even if you remove line 40 your graphite-web will not able to match caches properly, effectively disabling them. Your DESTINATIONS should match with CARBONLINK_HOSTS for all servers (port should be different, ofc). You can try that, but then you need to comment out CLUSTER_SERVERS. If your ping between nodes is low - that could work.

**Comment by deniszh** [comment]
Or you can use reference implementation:
1. Two tier relay - one relay (tier0) send data to 3 hosts, with e.g. RF=2. Second relay (tier1) just taking metrics from tier0 relay and spreading them across 2-4 local caches per host (for scalability).
2. Graphite-web installed on each host, having in CARBONLINK_HOSTS only local caches (from tier1) and 2 other graphite-web in  CLUSTER_SERVERS.

**Comment by blafrisch** [comment]
Thank you for helping me understand the system a bit better. I was trying to avoid the 2-tier relay setup because I was having trouble grasping how I'd rebalance the cluster in that situation using tools like carbonate. It looks like if I did want to do something like that then I'd have to write new tooling to rebalance.

**Comment by deniszh** [comment]
Just use teir0 relay info to config carbonate - it will work, no need to write anything.

**Comment by blafrisch** [comment]
Does that statement remain true if the 2x instances of carbon-cache on each host are writing to unique data directories? i.e. instance 'a' is writing to LOCAL_DATA_DIR=/data1 and instance 'b' is writing to LOCAL_DATA_DIR=/data2?

**Comment by deniszh** [comment]
No, and there's no need to having separate data directories for different instances - hashing should care for that, but you can use locking for whisper files to be sure.

**Comment by blafrisch** [comment]
I was more concerned about having each carbon-relay on a given having its own dedicated drives for performance since I've read that carbon-relay is I/O bound rather than CPU bound. Would it be preferable to RAID 0 the disks and have the carbon caches write to the same directories?

**Comment by deniszh** [comment]
Indeed. You're using multiple hosts for redundancy, right?

**Comment by blafrisch** [comment]
Yep, multiple hosts for redundancy hence the REPLICATION_FACTOR > 1 and the proposed relay setup. I have a lot to look into now including carbonzipper and all of those related components but this has certainly helped get my mind set straight about how to architect the layout.

**Comment by usmanC9** [comment]
> Or you can use reference implementation:
> 
> 1. Two tier relay - one relay (tier0) send data to 3 hosts, with e.g. RF=2. Second relay (tier1) just taking metrics from tier0 relay and spreading them across 2-4 local caches per host (for scalability).
> 2. Graphite-web installed on each host, having in CARBONLINK_HOSTS only local caches (from tier1) and 2 other graphite-web in  CLUSTER_SERVERS.

According to the reference architecture , tier0 relay may cause single point of failure. Actually I am trying to setup an HA architecture. For that I have added another relay on tier0 and add a LB on top of it. Does it makes sense ? or is there any alternate approach to achieve HA on tier0 ?
