### ISSUE TITLE
Combine metric's dtapoint from multiple whisper files

### ISSUE THREAD

**Issue by zdenekpizl** [graphite-project/graphite-web#1914]
Greetings,

 is it even possible to configure Graphite to combine (merge) datapoints for a machine's metric from multiple (two should be fine) files i.e. when asking for time-range  spread across those two files?

Use case: 
* let's imagine metrics for a machine has been archived or copied away from original location and datafiles were recreated as empty empty ones with the same archive settings.
* there is of course possibility to use whisper-merge tool and merge those datapoints together offline
* anyway is it possible to combine i.e. two locations or remote + local datastore or whatever would work?

Thank you, regards .zp.

**Comment by zdenekpizl** [comment]
Hi Dan,

 do you mean to add i.e. two items into CLUSTER_SERVERS of local_settings.py? I am in doubts, because documentation says:

"""
CLUSTER_SERVERS

    Default: []

    The list of IP addresses and ports of remote Graphite webapps in a cluster. Each of these servers should have local access to metric data to serve. The first server to return a match for a query will be used to serve that data. Ex: [“10.0.2.2:80”, “10.0.2.3:80”]
"""

That means, as far as I understand it, there will be data served from ONE of these servers but not both in union. Or am I mistaken?

My expectation is to get data of requested time-range from both servers, because each of them does have part of that time-range.

**Comment by deniszh** [comment]
Starting from 0.9.15 graphite-web supporting `REMOTE_STORE_MERGE_RESULTS` parameter, which will do exactly that - merge results from different cluster nodes.

**Comment by zdenekpizl** [comment]
Awesome, I will try it. This option is not covered in latest documentation at graphite.readthedocs.io/en/latest/config-local-settings.html.

Thank you, with regards, .zp.

**Comment by deniszh** [comment]
Yes, it's only included in config example, but the default is True in latest releases.
