### ISSUE TITLE
Gaps in stored graphs. Data stored comes from Netdata.

### ISSUE THREAD

**Issue by dugajean** [graphite-project/graphite-web#1919]
I have a server sending resource information via Netdata to another server with Graphite. The issue is, that there are gaps in the stored data with high frequency, and I can't figure out why.

When I check Netdata's dashboard itself, the data is continuous and has no gaps, so I'm assuming that this is directly related to Graphite itself.

My only thought on this is that I messed up on the retention policies. This is the section I add right under the `[carbon]` section:

```
[netdata]
pattern = ^netdata\.
retentions = 15s:7d,1m:60d,15m:1y
```

And this is how the graphs look like (null=null):

![screen shot 2017-05-03 at 10 18 19](https://cloud.githubusercontent.com/assets/2448254/25652742/fa363b50-2fe9-11e7-8d05-67b36674b0f6.png)

And this one where I convert the nulls to zeros:
![screen shot 2017-05-03 at 10 18 45](https://cloud.githubusercontent.com/assets/2448254/25652755/09a214f6-2fea-11e7-912d-96edf4cf0247.png)

It is impossible for so many gaps to form in basically ALL charts. What I'm showing you is only the CPU, but the same gaps happen all over the place at the RAM, Disk, IPv4, nginx, redis etc.

Help would be highly appreciated.

**Comment by deniszh** [comment]
It really depends on how often your netdata metrics coming. Retention 15s:7d means that data should come at least every 15 seconds, otherwise you will get null.

**Comment by dugajean** [comment]
Netdata sends data at least every 10 seconds, but it might take more from time to time.

**Comment by deniszh** [comment]
Then you need to have retention = 10s, instead of 15s - this could help. But if "it might take more from time to time" - then you will get nulls anyway - that's how Graphite works.

**Comment by deniszh** [comment]
Maybe we should extend [transformNull()](https://graphite.readthedocs.io/en/1.0.1/functions.html#graphite.render.functions.transformNull) function to remove nulls using previous data, but in general, it is an antipattern.

**Comment by dugajean** [comment]
@deniszh I tried increasing the retention policy to 40s and then lower it to 10s. I still keep getting those gaps for some reason. Isn't there something that can be done now, without extending `transformNull` in order to fix this?
