### ISSUE TITLE
Broken link on page "Quick Start Guide: Getting Metrics into Graphite"

### ISSUE THREAD

**Issue by maidentaiwan** [graphite-project/graphite-web#1922]
The page https://graphiteapp.org/quick-start-guides/feeding-metrics.html has a broken link with the text "language bindings".  The `href `begins with a left parenthesis that shouldn't be present. As a result, the user sees this link:

https://graphiteapp.org/quick-start-guides/(https://github.com/etsy/statsd/wiki#client-implementations

instead of this correct link:

https://github.com/etsy/statsd/wiki#client-implementations

**Comment by deniszh** [comment]
Thanks for reporting!
Fixed
