### ISSUE TITLE
webapp/graphite/settings.py sets WEBAPP_VERSION to "1.0.0-pre1" instead of "1.0.1"

### ISSUE THREAD

**Issue by bascarsija** [graphite-project/graphite-web#1923]
The current (master = bbfab10) version of webapp/graphite/settings.py sets WEBAPP_VERSION to "1.0.0-pre1" instead of "1.0.1"

https://github.com/graphite-project/graphite-web/blob/bbfab10be70d453400256d6fac962cc605abd283/webapp/graphite/settings.py

Is there a set of steps to take to release a new version?  If so, it would be good to include an step to update this value, if that step doesn't already exist.

**Comment by deniszh** [comment]
Fixed
