### ISSUE TITLE
graphite  occasionally return no datapoints

### ISSUE THREAD

**Issue by pengyusong** [graphite-project/graphite-web#1925]
Hi, i got a wierd question, i use "canbon-c-relay + carbon + graphite-web " for data collecting and storing.

I use Seyren to alert when target metric reach to the limit. Seyren checkers occasionally get no data points, so its status turn to Unknow.

The clues as follows:
graphite-web logs that i added :

```
2017-05-05,17:58:52.949 :: one request:
     targets: [u'asPercent(sumSeries(collectd.MONITOR_SERVER.system.memory.{free,buffered,cached,slab_recl}), sumSeries(collectd.MONITOR_SERVER.system.memory.*))']
     cachedDataNone: Cache Data None
     data: 0
```
data is 0, it means no data renturn.

Seyren logs:
```
com.seyren.core.exception.InvalidGraphiteValueException: Could not find a valid datapoint for target: "asPercent(sumSeries(collectd.MONITOR_SERVER.system.memory.{used,slab_unrecl}),8151900160)"
	atcom.seyren.core.service.checker.GraphiteTargetChecker.getLatestValue(GraphiteTargetChecker.java:83) 
	atcom.seyren.core.service.checker.GraphiteTargetChecker.check(GraphiteTargetChecker.java:54)
	atcom.seyren.core.service.schedule.CheckRunner.run(CheckRunner.java:65) 
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
	at java.util.concurrent.FutureTask.run(Unknown Source) 
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) 
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
	at java.lang.Thread.run(Unknown Source) 
```

Seyren logs also show graphite has not return any datapoint.

But, most of the time, it normally return data.

**Comment by pengyusong** [comment]
apache + graphite-web(fnv1a_ch hash)
carbon cache with 3 instances
carbon-c-relay with fnv1a_ch cluster

**Comment by pengyusong** [comment]
i think i have fix this issue, the problem is not about graphite, it about collectd.

when i set collectd read thread num larger than configured read plugins num, it will be easily reproduct the problem.

So, i change the num equal to the num of read plugins, then, the problem disappeared

**Comment by drnarahari** [comment]
Can you explain clearly what do you mean by read thread num and read thread num? What is the value you set to each of them?
