### ISSUE TITLE
Graphite webapp tree browser does not show metrics with leaf names matching intermediate node names

### ISSUE THREAD

**Issue by mleinart** [graphite-project/graphite-web#193]
#### Imported from https://bugs.launchpad.net/bugs/814182

|  |  |
| --- | --- |
| Reported by | [noslowerdna](https://launchpad.net/~noslowerdna) |
| Date Created | Jul 21, 2011 |

On version 0.9.8 I noticed the following behavior in the webapp.

Given two metrics where one metric is a prefix of the other, e.g. stats.test.documents and stats.test.documents.viewable, only the metric with the longer name (e.g. stats.test.documents.viewable) is visible in the tree browser.  The 'documents' leaf is apparently clobbered or hidden by the 'documents' folder.

On the filesystem I can see that the documents directory (containing viewable.wsp) and the documents.wsp file both exist, so it appears that carbon is correctly tracking both metrics.

**Comment by mihneadb** [comment]
Hello, are there any workarounds for this? Thanks.

**Comment by languitar** [comment]
:+1: hit this as well

**Comment by frlinux** [comment]
We hit this too, still present on 0.9.15 from EPEL.

**Comment by obfuscurity** [comment]
Yes, this is a known bug that isn't likely to get fixed without a major redesign of the Composer UI.
