### ISSUE TITLE
Django 1.9.x update breaks django_gunicorn command

### ISSUE THREAD

**Issue by replicat0r** [graphite-project/graphite-web#1930]
I am using supervisor to start the graphite webapp on a docker container. The command 

/usr/bin/gunicorn_django -b127.0.0.1:8000 -w2 graphite/settings.py

actuall doesnt run the app anymore. 

gunicorn recommands that following commands to be used

/usr/bin/gunicorn webapp.wsgi:application -b127.0.0.1:8000 -w2 

however, I cant figure out the name of the app to call wsgi:application on, i tried "webapp", "graphite", "graphite-webapp" , but django would complain with 

ImportError: No module named graphite-web.wsgi

How do I fix this startup command? 

also in the original command, the last argument graphite/settings.py , is that the settings file being loaded in? What does that actually do? the latest stable gunicorn actually doesnt allow that. How do I get around this? 

Thanks!

**Comment by deniszh** [comment]
First, I want to mention that there are a many ways how you can run Graphite - gunicorn is only one option.
But I'm also running Graphite with gunicorn, so, I know an answer. :)
I'm running it like this (with latest Gunicorn):
```
PYTHONPATH=/opt/graphite/webapp
cd /opt/graphite
/usr/local/bin/gunicorn wsgi -b127.0.0.1:8000 -w2 --preload ...
```
