### ISSUE TITLE
aliasByNode is broken when used with certain functions

### ISSUE THREAD

**Issue by leoleovich** [graphite-project/graphite-web#1932]
Hello,
we just upgraded graphite from 0.9.15 to 1.0.1 and now we have problems with existing graphs.
Line numbers are shifted, we have a custom function earlier in code:
```python
2017-05-15,12:05:40.633 :: Exception encountered in <POST https://graphite.../render>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 124, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 8, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 59, in evaluateTokens
    return func(requestContext, *args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 1876, in aliasByNode
    series.name = '.'.join(metric_pieces[n] for n in nodes)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 1876, in <genexpr>
    series.name = '.'.join(metric_pieces[n] for n in nodes)
IndexError: list index out of range
```
Error is happening here: 
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L1855

We get this error only in some cases. For example if before certain function, like `groupByNode`, was used:
`aliasByNode(asPercent(groupByNode(servers.node0*_graphite.system.cpu.{user,iowait,system,irq,softirq,steal},4,'sum')),4)`

If I replace `aliasByNode`s code with the one from 0.9.15, it works:

```python
def aliasByNode(requestContext, seriesList, *nodes):
  """
  Takes a seriesList and applies an alias derived from one or more "node"
  portion/s of the target name. Node indices are 0 indexed.

  .. code-block:: none

    &target=aliasByNode(ganglia.*.cpu.load5,1)

  """
  if type(nodes) is int:
    nodes=[nodes]
  for series in seriesList:
    metric_pieces = re.search('(?:.*\()?(?P<name>[-\w*\.]+)(?:,|\)?.*)?',series.name).groups()[0].split('.')
    series.name = '.'.join(metric_pieces[n] for n in nodes)
  return seriesList
```

**Comment by leoleovich** [comment]
Actually, I think it is even more about `groupByNode`
```
wget "https://graphite.../render/?target=groupByNode(perSecond(servers.node0*_graphite.system.cpu.{user,iowait,system,irq,softirq,steal}),4,'sum')" -O render.png
```
![image](https://cloud.githubusercontent.com/assets/4749052/26054224/168386e2-396c-11e7-88c5-d9faa4198264.png)

As you can see `user)` has closing bracket.

and if I add aliasByNode here it breaks:
```bash
wget "https://graphite.../render/?target=aliasByNode(groupByNode(perSecond(servers.node0*_graphite.system.cpu.{user,iowait,system,irq,softirq,steal}),4,'sum'),4)" -O render.png
HTTP request sent, awaiting response... 502 Bad Gateway
```

**Comment by leoleovich** [comment]
Let me make more investigation please

**Comment by leoleovich** [comment]
Ok, I think I see what is happening:
* Call of `groupByNode` returns already "aliased" version: `[{"target": "iowait", "datapoints": [[5145058.0, 1494763200]...`
* `asPercent` around it transforms it to the "full" path again:
`[{"target": "asPercent(iowait,sumSeries(sumSeries(servers.node0*_graphite.system.cpu.{user,iowait,system,irq,softirq,steal})))", "datapoints": [[0.39007737399918074, 1494763320]...`
* And then magic starts:
  * Old version of `aliasByNode` would work fine with `aliasByNode(<previous_output>,4)`
  * New version of `aliasByNode` requires 0 to be the node in this case. Which kicks out the possibility to use alias by another node, than was returned by `groupByNode`.

Is this a bug or a feature?

**Comment by deniszh** [comment]
Hi @leoleovich,
It happened after https://github.com/graphite-project/graphite-web/commit/b71f0e01b7b8b90f8124fabcc591c1f77e04ffc3 which was made by @natbraun 
Maybe @iksaif knows more.

**Comment by iksaif** [comment]
IMOH it's a bug fix, even if the Graphite syntax makes it hard to do that kind of thing.

* groupByNode() returns `iowait`
* asPercent() returns `asPercent(iowait, bla..)`
* aliasByNode() should work on the first argument of asPercent, which it does by working on `iowait`. And `iowait` happens to contain a single node.

**Comment by leoleovich** [comment]
@iksaif then aliasByNode is getting useless by 70% :(

**Comment by iksaif** [comment]
I'm not sure I understand what you mean, what would you expect the behavior of `aliasByNode(.., 4)` to be in your case ?

**Comment by leoleovich** [comment]
@iksaif 
* `aliasByNode` is used quite often as the last function. For example would be nice to operate with multiple parts of the origin metric, like aliasByNode(1, 4) to see "node01_graphite.iowait" and so on
* It is bit confusing, when you want to call your metric by 4th part, but you have to use 0
* It breaks all existing graphs

**Comment by iksaif** [comment]
The thing is that given `asPercent(iowait,sumSeries(sumSeries(servers.node0*_graphite.system.cpu.{user,iowait,system,irq,softirq,steal})))`, there is no reason to use the second argument of `asPercent` instead as `node` of the first one. I think use the first one makes much more sense.

**Comment by leoleovich** [comment]
@iksaif with this part I agree. It was just very convenient to use `aliasByNode` at the end to fix metric's name.

**Comment by DanCech** [comment]
I do have to agree that this change is confusing.  Part of the issue really is that the way functions produce aliases for their output makes it difficult to say that there's a single "right" way to implement `aliasByNode()`, though the BC break for dashboard does worry me.  In the short term the simplest solution for the OP would be to use `aliasSub()`, but I do think this warrants further discussion.

**Comment by iksaif** [comment]
This thing is that aliasByNode() has been working like this in the 1.0.x for quite somet time already, so changing the behavior again (to something that doesn't really make sense) wouldn't be great

**Comment by leoleovich** [comment]
Ok, then, probably, we should get used to the new behaviour. Thanks.

**Comment by DanCech** [comment]
We're continuing to run into issues with the new aliasByNode, with dashboards that worked on 0.9 failing with parse errors etc.  I'm going to dig deeper.

**Comment by Dieterbe** [comment]
FWIW i've seen a case where a metric that had an empty node (eg `foo.bar..baz`) resulted in "IndexError: list index out of range" when used with aliasByNode

**Comment by DanCech** [comment]
@Dieterbe you need to update to 1.1.1

**Comment by admin-pro** [comment]
Hello, i have the same issue, i was working with 0.9.13 version and i have performed an upgrade to 1.1.1 but the bug still present.

**Comment by deniszh** [comment]
which bug are you referring, @admin-pro ? if what @leoleovich mentioning - yes, and it's not a bug but changed function semantics in 1.0.x

**Comment by admin-pro** [comment]
@deniszh i have updated my comment it is 1.1.0 not 1.1.1 sorry. Yes is that. Oh ok, sorry.
