### ISSUE TITLE
applyByNode has a wrong annotation example below its definition

### ISSUE THREAD

**Issue by wolfzhaoshuai** [graphite-project/graphite-web#1934]
There has  an additional example in the annotation, I don't think it's right. Originally, this example aims at the rate of 5xx's per service, but after 'applyByNode(stats.counts.haproxy.*.*XX, 3, "asPercent(%.2XX, sumSeries(%.*XX))", "%.pct_5XX")',  I get the rate of 2xx's per service. So if you want to get 5xx's rate, the expression should be 'applyByNode(stats.counts.haproxy.*.*XX, 3, "asPercent(%.5XX, sumSeries(%.*XX))", "%.pct_5XX")'.

**Comment by deniszh** [comment]
Fixed. Thanks for reporting!
