### ISSUE TITLE
CLUSTER_SERVERS disregards URL_PREFIX

### ISSUE THREAD

**Issue by erikmack** [graphite-project/graphite-web#1940]
I have a setup with two shards using relay-rules.conf.  All components (carbon, graphite-web, whisper) are pip version 1.0.1

On rick.example.com:

    URL_PREFIX='/graphite'
    CLUSTER_SERVERS=['morty.example.com']

On morty.example.com:

    URL_PREFIX='/graphite'
    CLUSTER_SERVERS=['rick.example.com']

Due to sharding rules, stats under 'test.*' keys end up only on morty.example.com as expected.  I execute a find query for '\*' on both rick.example.com and morty.example.com

Expected:  'test.\*' keys are returned from each server
Actual: 'test.\*' keys are returned only when querying morty (which has them stored locally). 

    erikm@localhost ~ $ curl 'http://rick.example.com/graphite/metrics/find/?_dc=1495553940005&query=*&format=treejson&path=carbon&node=carbon'
    [{"text": "carbon", "expandable": 1, "leaf": 0, "id": "carbon", "allowChildren": 1}]
    erikm@localhost ~ $ curl 'http://morty.example.com/graphite/metrics/find/?_dc=1495553940005&query=*&format=treejson&path=carbon&node=carbon'
    [{"text": "carbon", "expandable": 1, "leaf": 0, "id": "carbon", "allowChildren": 1}, {"text": "test", "expandable": 1, "leaf": 0, "id": "test", "allowChildren": 1}]

Looking at the uwsgi logs on rick.example.com, the RemoteStore query (from morty.example.com) is executed but returns a 404 because URL_PREFIX is not prepended:

    [pid: 13|app: 0|req: 56/62] 100.93.200.16 () {30 vars in 431 bytes} [Tue May 23 15:52:35 2017] GET /metrics/find/?local=1&format=pickle&query=%2A => generated 87 bytes in 1 msecs (HTTP/1.1 404) 1 headers in 51 bytes (1 switches on core 0)

I have found a workaround.  On rick.example.com:

    URL_PREFIX='/graphite'
    CLUSTER_SERVERS=['morty.example.com'+URL_PREFIX]

On morty.example.com:

    URL_PREFIX='/graphite'
    CLUSTER_SERVERS=['rick.example.com'+URL_PREFIX]

But obviously this is a hack that might not work in future versions.  Ideally remote_storage.py would be aware of URL_PREFIX. At the very least, the workaround above should be documented for URL_PREFIX users.

The app is served by uwsgi with nginx in front.

Thanks for graphite!

**Comment by deniszh** [comment]
Hello @erikmack,
Agreed, CLUSTER_SERVERS just silently implies that it contains part of URL, maybe we should make that explicit (e.g. introduce CLUSTER_SERVERS_URLS), but, for now, I think we just need to fix documentation somewhere around CLUSTER_SERVERS and/or URL_PREFIX
Thanks for reporting that!

**Comment by DanCech** [comment]
I have started a patch to support http(s):// as a prefix on the entries to signal whether to use http or https for communication with the backend host, so officially supporting a path also would make sense imhoOn May 23, 2017 1:07 PM, Denis Zhdanov <notifications@github.com> wrote:Hello @erikmack,
Agreed, CLUSTER_SERVERS just silently implies that it contains part of URL, maybe we should make that explicit (e.g. introduce CLUSTER_SERVERS_URLS), but, for now, I think we just need to fix documentation somewhere around CLUSTER_SERVERS and/or URL_PREFIX
Thanks for reporting that!
