### ISSUE TITLE
ASAP smoothing

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#1941]
It will be really nice to have ASAP function in Graphite - https://github.com/wyndhblb/graphite_asap
But it requires `numpy` and we have no pluggable function mechanism yet.
Would be a good idea to include it "as-is", with a nice and sweet error message "please install numpy if you want to use this function" - or we should think for the proper pluggable function mechanism?

/cc @obfuscurity @DanCech @iksaif @graphite-project/committers

**Comment by DanCech** [comment]
You beat me to opening this!  I'm fine with adding a dependency, especially since we could then start looking at places where numpy might be able to speed up existing functions.

**Comment by drawks** [comment]
Historically there has been a decent amount of resistance to adding a dependency on numpy. The general suggestion to feature requests of this nature has been to perhaps build out better capability for making render functions pluggable and allowing plugins to to have various 3rd party dependencies.

I'd personally really like to see maybe a third way, using [setuptools' extras capability](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) to have numpy be an optional dependency and then offer some numpy optimized versions of inbuilt render functions as well as potentially some additional functions which would become enabled only when numpy support is enabled.

**Comment by DanCech** [comment]
Pluggable functions is interesting, and I've been thinking a little about an endpoint to be able to advertise to tools like Grafana which functions are supported by the graphite instance, but there's a lot of work there, and I am concerned about fragmenting the api out into 3rd-party functions that then make moving the core forward more difficult and make it harder for users to find out what functions are out there.

That said, the optional dependency idea seems to be a good one, and looking at the asap codebase it's actually only using the numpy.fft `fft` and `ifft` functions, so it seems like it would be reasonable to add a pure-python implementation of those to use as a fallback if numpy isn't installed.

**Comment by deniszh** [comment]
Quick googling shows that pure python FFT is very slow and/or limited, everybody recommends using `numpy` or `scipy` version.
I'm also concerned about pluggable functions and fragmenting API a bit - but I do not see how you can implement really powerful math w/o something like `numpy`.
I like @drawks idea about setup extras more.

**Comment by drawks** [comment]
-------
Begin tangential discussion
-------

> Pluggable functions is interesting, and I've been thinking a little about an endpoint to be able to advertise to tools like Grafana which functions are supported by the graphite instance.

At this point I think the quality of the code base of graphite-api is such that it would be *my* preference if that became the reference implementation and was pulled under the graphite project and then have graphite-web be skeletonized into a minimal composer/dashboard interface on top of graphite-api.

As a tool for rapidly browsing data and prototyping various shaping/graphing of the data graphite-web's front end has always been a nice feature for me. But, the grafana project has far surpassed it in capabilities for dashboarding.

If the api had an endpoint for enumerating and describing render functions such that the front end layer could be agnostic that would be awesome.

**Comment by DanCech** [comment]
@deniszh yes, I was only suggesting it as a better option than having the function be totally unavailable if we wanted to make numpy/scipy an optional dependency.

@drawks there are a lot of use-cases that graphite-api just doesn't handle, and it doesn't have any of the threading or clustering support that's present in graphite-web 1.0.  I do like the idea of deprecating the ui in favor of Grafana, and am pushing to make that possible by improving the abilities of Grafana as a tool for exploring the metrics hierarchy.

**Comment by iksaif** [comment]
We could start by making the UI optional, and by making part of Graphite more easilly reusable by other tools. Ideally Graphite UI should not have to re-implement the functions or the grammar, but would just import the relevant files.

**Comment by deniszh** [comment]
I'm 👍 for making Graphite UI separate, but 👎 on deprecating it - it still has its userbase, and if you talk about simple browse of metrics tree - it's still VERY useful.
I'm also not sure about graphite-api, I also had an idea to in-source it to Graphite project first - but I'm not sure should we do that and support two codebases separately, because graphite-api lacks so many parts. 
OTOH - maybe periodic copying functions.py and some patches back and forth is not that tremendous effort?

But we're drifting out from my initial topic - should we try to include `numpy` as optional dependency and try to port ASAP smoothing?

**Comment by DanCech** [comment]
@iksaif @deniszh sounds like we're on the same page inre the UI, need to think a bit about the best way to do that without introducing a lot more work.  One thing we could do which would be simple is to take functions.py and break that out into its own package, then graphite-api and similar projects could import and use that if they wanted rather than forking it.

@denish yes, I'm all for getting ASAP smoothing into the codebase.  I would like to see `numpy` as an optional dependency, with a pure-python fft fallback if it isn't installed.  https://gist.github.com/wilem/9824988 might be something to build from there.

**Comment by drawks** [comment]
> Quick googling shows that pure python FFT is very slow and/or limited, everybody recommends using numpy or scipy version.

I just wanted to jump in here and point out that the more typical use case for FFT is for stream processing applications. So the concept of pure python being "very slow" or "limited" may not be entirely applicable when looking at [relatively] small chunks of time series. It could be that a fallback to a pure python implementation is "fast enough" for most typical graphite use cases. And having numpy as an optional dependency may provide more speed for those who need or want it.

**Comment by deniszh** [comment]
I really suspect that pure python fft will be slow even for relatively small chunks of time series.  But agreed that's pure theoretizing, indeed. We can test and fix pure python part later.
If you need help with code or testing, @DanCech - let me know!

**Comment by kexinrong** [comment]
Thanks for your interests! Just want to add that ASAP can also be implemented without FFT. FFT was originally introduced as an optimization to make ASAP run faster. Details for this optimization can be found in Section 4.3 of our [paper](http://www.vldb.org/pvldb/vol10/p1358-rong.pdf). 

[Here](https://github.com/stanford-futuredata/ASAP/blob/master/ASAP-simple.js) is an example implementation that does not involve FFT.

**Comment by deniszh** [comment]
https://github.com/deniszh/graphite_asap
Will try to create a numpy-free version using JS code above, but not sure if it will fast enough for practical usage, probably not.
