### ISSUE TITLE
[bug] grammar.parseString sometimes parse error

### ISSUE THREAD

**Issue by pengyusong** [graphite-project/graphite-web#1952]
I found a really strange question, i use graphite-beacon to alert when something is wrong.
But, graphite-beacon sometimes return "No Data " error.

through review the code, and add log to detail this question, i found it is "grammar parse bug"

in graphite/render/evaluator.py: evaluateTarget funcion
> grammar.parseString(target)

this code sometime parse error

I already change code as follows:
```
def evaluateTarget(requestContext, target):
    log.rendering("----------------------- Target: %s" % (target,))
    tokens = grammar.parseString(target)
    log.rendering("----------------------- Tokens: %s" % (tokens,))
    result = evaluateTokens(requestContext, tokens)
  
    if type(result) is TimeSeries:
      return [result] #we have to return a list of TimeSeries objects
  
    else:
      return result
```

when graphite-beacon return No Data, the log will show as follows:
```
------- Target: alias(asPercent(windows.system.memory.available,windows.system.memory.total), 'XXX')
------- Tokens: [[u'alias']]
```

you will see  Tokens lose in parse results：
**----- Tokens: [[u'alias']]**

this normally will be show as follows:
**----- Tokens:[[[u'alias', [[[u'asPercent', [[u'windows.system.memory.available']],[[u'windows.system.memory.total']]]]], [u"'SACA'"]]]]**

dditional remarks：

- graphite beacon use tornado async http client, when alerts config only one,  it run normally. when i configure more than one alert, it normally get no data about every 30 minutes.

- when graphite beacon get no data, graphite-web grammar.parseString call will fail

**Comment by pengyusong** [comment]
@deniszh

**Comment by deniszh** [comment]
Hello @pengyusong,
Thanks for reporting! I remember this or a similar bug. What's your version of graphite and pyparsing?

**Comment by deniszh** [comment]
Yep, we had similar issues in https://github.com/graphite-project/graphite-web/issues/1806 and it was fixed in https://github.com/graphite-project/graphite-web/pull/1810

**Comment by pengyusong** [comment]
yes, i put one lock in evaluateTarget func, around "grammar.parseString(target)", it seems work, but i think simply add a lock may be influence performance, so have some better solutions?

versions: 
- graphite  v1.0.1
- pyparsing  v2.2.0

**Comment by deniszh** [comment]
Could you please check how pyparsing 2.1 and/or pyparsing 1.5.x working?

**Comment by pengyusong** [comment]
pyparsing not throw a exception, just lose some data, i found [this](https://bytes.com/topic/python/answers/803037-parser-recommendation):

> You can use pyparsing from any thread, and you can create multiple parsers each running in a separate thread, but you cannot concurrently use one parser from two different threads. Some users work around this by instantiating a separate parser per thread using pickle to quickly construct the parser at thread start time.

**Comment by pengyusong** [comment]
OK, i will try it.

**Comment by pengyusong** [comment]
@deniszh  i write a script to test it, this script use graphite's grammar file. but i run it with two thread, no lock. whatever version is, the result still parse fail: lose some parse data. show as follows:
```
version: 1.5.7
thread2 -- [[u'alias']]
thread1 -- [[[u'alias', [[[u'asPercent', [[u'windows.system.memory.available']], [[u'windows.system.memory.total']]]]], [u"'XXX'"]]]]
```
but when i use lock it run normally.

script code as follows:
```
# -*- coding: utf8 -*-
from grammar import grammar

import time
import threading

lock = threading.Lock()


class MyThread(threading.Thread):
    def __init__(self, name):
        threading.Thread.__init__(self)
        self.name = name

    def run(self):
        self.parse()

    def parse(self):
        i = 1
        targets = [
            u"alias(asPercent(windows.system.memory.available, windows.SACA_SERVER_2.system.memory.total), "
            u"'XXX')"
        ]

        while i <= 1000:
            i += 1

            tmp_results = [grammar.parseString(target) for target in targets]

            count = 0
            for result in tmp_results:
                print self.name, '--', result
                # print str(result).find("SERVER")
                # try:
                #     if str(result).find("SERVER") == -1:
                #         print result
                # except:
                #     import traceback
                #     traceback.print_exc()
                count += 1

            time.sleep(10)


if __name__ == "__main__":
    import threading

    thread1 = MyThread('thread1')
    thread2 = MyThread('thread2')
    thread3 = MyThread('thread3')

    threads = []

    thread1.start()
    thread2.start()

    threads.append(thread1)
    threads.append(thread2)

    for t in threads:
        t.join()
    print "Exiting Main Thread"

```

**Comment by pengyusong** [comment]
Obviously, in multi-thread env, pyparsing work not very well

**Comment by pengyusong** [comment]
@deniszh i try the version 2.1.0, this problem still exist. I cannot  install version 1.5.7, so, sorry.

**Comment by deniszh** [comment]
OK, thanks! Then we should fix that, indeed. 
Setting lock around is not an option, right?
Asking for committers opinion here. /cc @iksaif @DanCech @graphite-project/committers

**Comment by pengyusong** [comment]
Thank you very much! 
I just test lock around will be useful, but i doubt performance of this method or else bugs.

**Comment by deniszh** [comment]
@pengyusong : could you please share your locking code? as PR or simple gist? That could be useful.

**Comment by pengyusong** [comment]
I just create an thread lock in the top of "graphite/render/evaluator.py":
then use as follows:
```
....
import threading     <-------
mutex = threading.lock()    <-------
...

def evaluateTarget(requestContext, target):
    mutex.lock()    <-------
    tokens = grammar.parseString(target)
    mutex.release()    <-------
    result = evaluateTokens(requestContext, tokens)
  
    if type(result) is TimeSeries:
      return [result] #we have to return a list of TimeSeries objects
  
    else:
      return result

def

```

**Comment by iksaif** [comment]
I think that is safe and won't really affect performances. Maybe add a comment before the lock to explain why this is needed

**Comment by DanCech** [comment]
Yeah, that seems like the least-invasive way to sideskirt any thread-safety issues in pyparsing.
