### ISSUE TITLE
groupByNodes with optional string concatenation

### ISSUE THREAD

**Issue by jermorse** [graphite-project/graphite-web#1966]
I want to have two separate targets with the same metric. One is a count and the other is a nonNegativeDerivative. I'm using groupByNodes and want to display one legend on y-axis and the other on the x-axis.

With the use of groupByNodes() function the legend values are identical. I'd like to be able to add a text string like "Derivative" or "Rate" to the y-axis to make it clear which is which.

Maybe there is another way to perform this but I haven't figured it out yet. I've tried [[Rate]] etc to no avail.

Thanks

**Comment by DanCech** [comment]
You can use `aliasSub(groupByNodes(some.series, 1), "^.*", "\1 Derivative")`

http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.aliasSub

**Comment by jermorse** [comment]
Thanks I had never known about aliasSub().

Cheers!
