### ISSUE TITLE
What are the reasons we don't support Django 1.8?

### ISSUE THREAD

**Issue by cbowman0** [graphite-project/graphite-web#1967]
I can't find any reasons in prior issues or PRs.

1.8 is one of the LTS releases.  It would make installation on Ubuntu far easier for me personally, since my environment prefers to use the OS packages.

**Comment by deniszh** [comment]
It slipped out between releases - too old for 1.0.x but too new for 0.9.x.
I'm totally 👍 for supporting it but have no idea TBH what need to be done.
Maybe @brutasse knows?

**Comment by piotr1212** [comment]
I'm the Fedora/EPEL Graphite package maintainer. If not too much trouble I would be quite happy with 1.8 support in Graphite. Django packaging is a bit of a pain in EPEL. Supporting 1.8 would make it easier to get Graphite 1.x in EPEL 7.

**Comment by cbowman0** [comment]
Support for Django 1.8 was added to 1.0.x and master branches.  Next release(s) will contain support unless some major issue is found.
