### ISSUE TITLE
Release 1.0.2 

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#1976]
IMO it's time to release 1.0.2 to the public. 
Maybe you know some patches or bugfixes which should be backported from master to 1.0.x before baking 1.0.2?
For whisper I'm going to check @piotr1212 commits for some fixes beside python3 support (I think we need to release py3 a bit later, in 1.1.0)
For carbon - the same. Should we include DYNAMIC_ROUTER support to 1.0.2 ?
/cc @iksaif @DanCech @cbowman0 @drawks 
@graphite-project/committers

**Comment by iksaif** [comment]
Nop, I would not include DYNAMIC_ROUTER in 1.0.2 :)

**Comment by deniszh** [comment]
Release is done, release documentation also updated - https://github.com/graphite-project/graphite-summit/wiki

**Comment by iksaif** [comment]
:+1:
