### ISSUE TITLE
[Bug] UnboundLocalError: local variable 'archive' referenced before assignment

### ISSUE THREAD

**Issue by scraly** [graphite-project/graphite-web#1985]
Hi,

since few days we have a problem with one of our charts on one of our grafana (4.3.2-1) dashboards. We use graphite datasource. The problem appears only in one particular chart, sicne few days, similar charts with other parameters are not impacted.

Here some print screen about the issue.

![headers](https://user-images.githubusercontent.com/2543381/27682290-50a3c2f0-5cc2-11e7-82ca-e1ddf6c5063a.png)

![preview](https://user-images.githubusercontent.com/2543381/27682304-58dac55e-5cc2-11e7-8490-3ab0843cfb48.png)

![response](https://user-images.githubusercontent.com/2543381/27682297-558562f6-5cc2-11e7-866f-54aec8813551.png)

The server have been rebooted (by our hoster) few days ago. I don't know if it's related but maybe it's a useful information. I search for corrupted whisper files, in case of, but didn't find them.

Have you an idea of where I can search to fix the problem?

Thanks.

**Comment by deniszh** [comment]
Hello @scraly ,
What's version of your Graphite?

**Comment by scraly** [comment]
Good question. I use graphite with Grafana so do you know where I can find this version?

Thw.

**Comment by scraly** [comment]
In my graphite repository I've got webapp/graphite-web-0.9.13-py2.7.egg-info repository.
I don't know if it's the version used by last version of Grafana.

**Comment by deniszh** [comment]
Try to ask '/version/' on Graphite URL.
E.g.
```$ curl https://graphite.my.org:8080/version/
0.9.12
```

**Comment by deniszh** [comment]
Grafana is not 'using' Graphite, it's separate dashboard. Somebody installed Graphite on your system and connect Grafana to it, but that's completely separate projects.

**Comment by deniszh** [comment]
You can find Graphite url in Datasources list in Grafana.

**Comment by scraly** [comment]
When I access to the graphite url I am redirected to the graphite web interface.

**Comment by scraly** [comment]
So, the graphite version we use is: 0.9.12

**Comment by deniszh** [comment]
I would say that's broken whisper file.  Please check the size of your whisper files, do you see some really small files, less than 1KB? Maybe disk with whisper file was full some time ago? (it's effectively corrupt whisper files)

**Comment by scraly** [comment]
Hi,
I search for whisper files smaller than 676k (the size of correct files) and I found 0 files ... :-(

We don't have full disk space issue but our sevrer have been rebooted by our hoster, maybe it's the root cause but how to fix the problem?

Have you some ideas ?

Thanks.

**Comment by deniszh** [comment]
Unfortunately, not. According to code it's really looks like broken wsp files, though

**Comment by DanCech** [comment]
Yeah, the whisper file must not have any archive entries in the header.
