### ISSUE TITLE
Invalid interval on old range

### ISSUE THREAD

**Issue by hamshiva** [graphite-project/graphite-web#1986]
Hi,

I discovered a strange behaviour. I have a load metric for which the storage-chema is 60:10080,300:26298,900:175200.

If I try to display a graph showing last month everything is ok. But if I try to display the same graph from 4 months ago I got nothing (graph with no values). I tried to display the graph with the format=raw param and it seems that the metric interval used is wrong. 

For the last month metric interval shown by webapp is 300s which is good. But if I try to display on month range from 4 months ago the webapp shows the same 300s interval and None values. It should use the next rententtion interval which is 900s. 

I suspect that the issue (blank graph) comes from this wrong metric interval.

PS: I can correctly fetch values for the same range from the wsp file using whisper-fetch.py tool.

**Comment by piotr1212** [comment]
Which version of graphite-web and carbon are you using?

You say if you select one month, you get a resolution of 300s. The archive 300:26298, is only 26298/(60*24) = 18,2625 days. This doesn't make sense to me, it should show a 900s interval on one -1month.

**Comment by hamshiva** [comment]
Ok I just upgraded to 1.0.1 and everything is working as expected. My version was quite old (I think it was 0.9.10) :)
