### ISSUE TITLE
Graphite is giving incorrect data sometimes

### ISSUE THREAD

**Issue by rajats105** [graphite-project/graphite-web#1988]
Sometimes graphite is returning incorrect data for metrics.
I am not able to find any reason why this might be happening intermittently.
I have tried looking into various logs could not find anything suspicious.

I am providing with you system details and version of software we are running graphite with.

|Software | Version|
|-|-|
|OS | Amazon Linux AMI release 2014.09|
|Kernel | Linux ip-x-x-x-x 3.14.20-20.44.amzn1.x86_64 #1 SMP Mon Oct 6 22:52:46 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux|
|Python | 2.7.10|
|Django | 1.9.13|
|carbon | 1.0.1|
|whisper | 1.0.1|
|graphite-web | 1.0.1|

Please tell me if you need more data from me.

**Comment by DanCech** [comment]
Can you provide information on the query you're using, the whisper file, the data you're expecting, and the data you're actually receiving?

**Comment by rajats105** [comment]
I am providing you with the incorrect response that was received for the requests.
For those same requests now when I query I am getting correct results.

Request/response under `Queried now` are correct responses, whereas the other one is incorrect response.

Please note that the `Queried now` response are being requested with absolute from/until params, whereas the Queried on 'date' is taken from our logs which are using relative from/until params.
## Case 1

### Queried on `2017-07-05 15:28:43`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-20min&until=-5min&target=scale(divideSeries(collectd.production.hulk.ip-10-0-1-77.processes-cm-ape-vol3.ps_rss,sumSeries(collectd.production.hulk.ip-10-0-1-77.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.hulk.ip-10-0-1-77.processes-cm-ape-vol3.ps_rss,sumSeries(collectd.production.hulk.ip-10-0-1-77.memory.*)),100)", "datapoints": [[970.7317073170732, 1499267400], [491.35802469135797, 1499267700], [723.6363636363636, 1499268000]]}]```

### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=15:08_20170705&until=15:23_20170705&target=scale(divideSeries(collectd.production.hulk.ip-10-0-1-77.processes-cm-ape-vol3.ps_rss,sumSeries(collectd.production.hulk.ip-10-0-1-77.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.hulk.ip-10-0-1-77.processes-cm-ape-vol3.ps_rss,sumSeries(collectd.production.hulk.ip-10-0-1-77.memory.*)),100)", "datapoints": [[0.04125754660651496, 1499267400], [0.04125754660651496, 1499267700], [0.04125754660651496, 1499268000]]}]```



## Case 2

### Queried on `2017-07-05 15:30:40`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-20min&until=-5min&target=scale(divideSeries(collectd.production.jasmine.ip-10-0-8-157.processes-eas.ps_rss,sumSeries(collectd.production.jasmine.ip-10-0-8-157.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.jasmine.ip-10-0-8-157.processes-eas.ps_rss,sumSeries(collectd.production.jasmine.ip-10-0-8-157.memory.*)),100)", "datapoints": [[302.6092710494313, 1499267700], [304.3672651834895, 1499268000], [320.3823592531655, 1499268300]]}]```


### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=15:10_20170705&until=15:25_20170705&target=scale(divideSeries(collectd.production.jasmine.ip-10-0-8-157.processes-eas.ps_rss,sumSeries(collectd.production.jasmine.ip-10-0-8-157.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.jasmine.ip-10-0-8-157.processes-eas.ps_rss,sumSeries(collectd.production.jasmine.ip-10-0-8-157.memory.*)),100)", "datapoints": [[8.274735275663945, 1499267700], [8.32280695577161, 1499268000], [8.760733604158323, 1499268300]]}]```


## Case 3

### Queried on `2017-07-05 15:21:35`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-35min&until=-5min&target=absolute(offset(sumSeriesWithWildcards(collectd.production.antman.ip-10-0-57-73.cpu-*.cpu-{wait,idle},6),-100))&format=json'

Response :: ```json[{"target": "absolute(offset(collectd.production.antman.ip-10-0-57-73.cpu-0,-100))", "datapoints": [[99.956667, 1499266200], [99.973333, 1499266500], [99.966667, 1499266800], [99.966667, 1499267100], [99.963333, 1499267400], [99.966667, 1499267700]]}, {"target": "absolute(offset(collectd.production.antman.ip-10-0-57-73.cpu-1,-100))", "datapoints": [[1.1833349999999996, 1499266200], [1.1299819999999983, 1499266500], [1.356650000000002, 1499266800], [1.3066809999999975, 1499267100], [1.259990000000002, 1499267400], [1.2466689999999971, 1499267700]]}]```


### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=14:46_20170705&until=15:16_20170705&target=absolute(offset(sumSeriesWithWildcards(collectd.production.antman.ip-10-0-57-73.cpu-*.cpu-{wait,idle},6),-100))&format=json'

Response :: ```json[{"target": "absolute(offset(collectd.production.antman.ip-10-0-57-73.cpu-0,-100))", "datapoints": [[0.4200000000000017, 1499266200], [0.4133119999999906, 1499266500], [0.486653000000004, 1499266800], [0.4566810000000032, 1499267100], [0.453322, 1499267400], [0.44000400000000184, 1499267700]]}, {"target": "absolute(offset(collectd.production.antman.ip-10-0-57-73.cpu-1,-100))", "datapoints": [[1.1833349999999996, 1499266200], [1.1299819999999983, 1499266500], [1.356650000000002, 1499266800], [1.3066809999999975, 1499267100], [1.259990000000002, 1499267400], [1.2466689999999971, 1499267700]]}]```


## Case 4


### Queried on `2017-07-05 15:01:08`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-35min&until=-5min&target=scale(divideSeries(collectd.production.medusa.ip-10-0-16-19.memory.memory-used,sumSeries(collectd.production.medusa.ip-10-0-16-19.memory.*)),100)&format=json'


Response :: ```json[{"target": "scale(divideSeries(collectd.production.medusa.ip-10-0-16-19.memory.memory-used,sumSeries(collectd.production.medusa.ip-10-0-16-19.memory.*)),100)", "datapoints": [[98.86561823052527, 1499265000], [98.89608393872908, 1499265300], [98.93428705945156, 1499265600], [99.17636048082642, 1499265900], [99.13713056913697, 1499266200], [99.13348292778778, 1499266500]]}]```

### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=14:26_20170705&until=14:56_20170705&target=scale(divideSeries(collectd.production.medusa.ip-10-0-16-19.memory.memory-used,sumSeries(collectd.production.medusa.ip-10-0-16-19.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.medusa.ip-10-0-16-19.memory.memory-used,sumSeries(collectd.production.medusa.ip-10-0-16-19.memory.*)),100)", "datapoints": [[48.10253867037586, 1499265000], [49.88782937740536, 1499265300], [52.209201267892404, 1499265600], [53.74422946094032, 1499265900], [51.904210641121004, 1499266200], [52.3104898483997, 1499266500]]}]```



## Case 5


### Queried on `2017-07-05 14:57:44`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-20min&until=-5min&target=scale(divideSeries(collectd.production.hulk.ip-10-0-1-77.processes-cm-bee-vol2.ps_rss,sumSeries(collectd.production.hulk.ip-10-0-1-77.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.hulk.ip-10-0-1-77.processes-cm-bee-vol2.ps_rss,sumSeries(collectd.production.hulk.ip-10-0-1-77.memory.*)),100)", "datapoints": [[18368.421052631576, 1499265600], [18209.090909090908, 1499265900], [40085.71428571428, 1499266200]]}]```

### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=14:37_20170705&until=14:52_20170705&target=scale(divideSeries(collectd.production.hulk.ip-10-0-1-77.processes-cm-bee-vol2.ps_rss,sumSeries(collectd.production.hulk.ip-10-0-1-77.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.hulk.ip-10-0-1-77.processes-cm-bee-vol2.ps_rss,sumSeries(collectd.production.hulk.ip-10-0-1-77.memory.*)),100)", "datapoints": [[1.4471239965501228, 1499265600], [1.4534473893717244, 1499265900], [1.454380348968354, 1499266200]]}]```




## Case 6


### Queried on `2017-07-05 14:56:40`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-35min&until=-5min&target=absolute(offset(sumSeriesWithWildcards(collectd.production.goofy.ip-10-0-3-245.cpu-*.cpu-{wait,idle},6),-100))&format=json'

Response :: ```json[{"target": "absolute(offset(collectd.production.goofy.ip-10-0-3-245.cpu-0,-100))", "datapoints": [[99.956667, 1499264700], [99.956667, 1499265000], [99.96, 1499265300], [99.963333, 1499265600], [99.953333, 1499265900], [99.96, 1499266200]]}]```


### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=14:21_20170705&until=14:51_20170705&target=absolute(offset(sumSeriesWithWildcards(collectd.production.goofy.ip-10-0-3-245.cpu-*.cpu-{wait,idle},6),-100))&format=json'

Response :: ```json[{"target": "absolute(offset(collectd.production.goofy.ip-10-0-3-245.cpu-0,-100))", "datapoints": [[1.5966729999999956, 1499264700], [1.6099940000000004, 1499265000], [1.6366639999999961, 1499265300], [1.6333430000000106, 1499265600], [1.7233209999999985, 1499265900], [1.680025999999998, 1499266200]]}]```

**Comment by rajats105** [comment]
I am providing you with the incorrect response that was received for the requests.
For those same requests now when I query I am getting correct results.

Request/response under `Queried now` are correct responses, whereas the other one is incorrect response.

Please note that the `Queried now` response are being requested with absolute from/until params, whereas the Queried on 'date' is taken from our logs which are using relative from/until params.

## Case 1

### Queried on `2017-07-05 15:28:43`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-20min&until=-5min&target=scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-uvwx.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-uvwx.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)", "datapoints": [[970.7317073170732, 1499267400], [491.35802469135797, 1499267700], [723.6363636363636, 1499268000]]}]```

### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=15:08_20170705&until=15:23_20170705&target=scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-uvwx.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-uvwx.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)", "datapoints": [[0.04125754660651496, 1499267400], [0.04125754660651496, 1499267700], [0.04125754660651496, 1499268000]]}]```



## Case 2

### Queried on `2017-07-05 15:30:40`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-20min&until=-5min&target=scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-pqrs.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-pqrs.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)", "datapoints": [[302.6092710494313, 1499267700], [304.3672651834895, 1499268000], [320.3823592531655, 1499268300]]}]```


### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=15:10_20170705&until=15:25_20170705&target=scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-pqrs.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-pqrs.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)", "datapoints": [[8.274735275663945, 1499267700], [8.32280695577161, 1499268000], [8.760733604158323, 1499268300]]}]```


## Case 3

### Queried on `2017-07-05 15:21:35`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-35min&until=-5min&target=absolute(offset(sumSeriesWithWildcards(collectd.production.ec2.ip-w-x-y-z.cpu-*.cpu-{wait,idle},6),-100))&format=json'

Response :: ```json[{"target": "absolute(offset(collectd.production.ec2.ip-w-x-y-z.cpu-0,-100))", "datapoints": [[99.956667, 1499266200], [99.973333, 1499266500], [99.966667, 1499266800], [99.966667, 1499267100], [99.963333, 1499267400], [99.966667, 1499267700]]}, {"target": "absolute(offset(collectd.production.ec2.ip-w-x-y-z.cpu-1,-100))", "datapoints": [[1.1833349999999996, 1499266200], [1.1299819999999983, 1499266500], [1.356650000000002, 1499266800], [1.3066809999999975, 1499267100], [1.259990000000002, 1499267400], [1.2466689999999971, 1499267700]]}]```


### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=14:46_20170705&until=15:16_20170705&target=absolute(offset(sumSeriesWithWildcards(collectd.production.ec2.ip-w-x-y-z.cpu-*.cpu-{wait,idle},6),-100))&format=json'

Response :: ```json[{"target": "absolute(offset(collectd.production.ec2.ip-w-x-y-z.cpu-0,-100))", "datapoints": [[0.4200000000000017, 1499266200], [0.4133119999999906, 1499266500], [0.486653000000004, 1499266800], [0.4566810000000032, 1499267100], [0.453322, 1499267400], [0.44000400000000184, 1499267700]]}, {"target": "absolute(offset(collectd.production.ec2.ip-w-x-y-z.cpu-1,-100))", "datapoints": [[1.1833349999999996, 1499266200], [1.1299819999999983, 1499266500], [1.356650000000002, 1499266800], [1.3066809999999975, 1499267100], [1.259990000000002, 1499267400], [1.2466689999999971, 1499267700]]}]```


## Case 4


### Queried on `2017-07-05 15:01:08`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-35min&until=-5min&target=scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.memory.memory-used,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)&format=json'


Response :: ```json[{"target": "scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.memory.memory-used,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)", "datapoints": [[98.86561823052527, 1499265000], [98.89608393872908, 1499265300], [98.93428705945156, 1499265600], [99.17636048082642, 1499265900], [99.13713056913697, 1499266200], [99.13348292778778, 1499266500]]}]```

### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=14:26_20170705&until=14:56_20170705&target=scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.memory.memory-used,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.memory.memory-used,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)", "datapoints": [[48.10253867037586, 1499265000], [49.88782937740536, 1499265300], [52.209201267892404, 1499265600], [53.74422946094032, 1499265900], [51.904210641121004, 1499266200], [52.3104898483997, 1499266500]]}]```



## Case 5


### Queried on `2017-07-05 14:57:44`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-20min&until=-5min&target=scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-abcd.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-abcd.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)", "datapoints": [[18368.421052631576, 1499265600], [18209.090909090908, 1499265900], [40085.71428571428, 1499266200]]}]```

### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=14:37_20170705&until=14:52_20170705&target=scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-abcd.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)&format=json'

Response :: ```json[{"target": "scale(divideSeries(collectd.production.ec2.ip-w-x-y-z.processes-abcd.ps_rss,sumSeries(collectd.production.ec2.ip-w-x-y-z.memory.*)),100)", "datapoints": [[1.4471239965501228, 1499265600], [1.4534473893717244, 1499265900], [1.454380348968354, 1499266200]]}]```




## Case 6


### Queried on `2017-07-05 14:56:40`

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=-35min&until=-5min&target=absolute(offset(sumSeriesWithWildcards(collectd.production.ec2.ip-w-x-y-z.cpu-*.cpu-{wait,idle},6),-100))&format=json'

Response :: ```json[{"target": "absolute(offset(collectd.production.ec2.ip-w-x-y-z.cpu-0,-100))", "datapoints": [[99.956667, 1499264700], [99.956667, 1499265000], [99.96, 1499265300], [99.963333, 1499265600], [99.953333, 1499265900], [99.96, 1499266200]]}]```


### Queried now

Request :: curl -X GET 'http://webapp.graphite.xyz.com/render?from=14:21_20170705&until=14:51_20170705&target=absolute(offset(sumSeriesWithWildcards(collectd.production.ec2.ip-w-x-y-z.cpu-*.cpu-{wait,idle},6),-100))&format=json'

Response :: ```json[{"target": "absolute(offset(collectd.production.ec2.ip-w-x-y-z.cpu-0,-100))", "datapoints": [[1.5966729999999956, 1499264700], [1.6099940000000004, 1499265000], [1.6366639999999961, 1499265300], [1.6333430000000106, 1499265600], [1.7233209999999985, 1499265900], [1.680025999999998, 1499266200]]}]```

**Comment by deniszh** [comment]
Hello @rajats105,
Could you please show contents of storage-schemas.conf and storage-aggregation.conf ?

**Comment by rajats105** [comment]
### storage-schemas.conf

```
# Schema definitions for Whisper files. Entries are scanned in order,
# and first match wins. This file is scanned for changes every 60 seconds.
#
#  [name]
#  pattern = regex
#  retentions = timePerPoint:timeToStore, timePerPoint:timeToStore, ...
#
# Carbon's internal metrics. This entry should match what is specified in
# CARBON_METRIC_PREFIX and CARBON_METRIC_INTERVAL settings

[collectd]
priority = 120
pattern = ^(collectd)\.
retentions = 300s:60d

[com]
priority = 110
pattern = .*
retentions = 300s:30d

[carbon]
pattern = ^carbon\.
retentions = 300s:60d

[default_1min_for_1day]
pattern = .*
retentions = 60s:1d
```

### storage-aggregation.conf

```
# Aggregation methods for whisper files. Entries are scanned in order,
# and first match wins. This file is scanned for changes every 60 seconds
#
#  [name]
#  pattern = <regex>
#  xFilesFactor = <float between 0 and 1>
#  aggregationMethod = <average|sum|last|max|min>
#
#  name: Arbitrary unique name for the rule
#  pattern: Regex pattern to match against the metric name
#  xFilesFactor: Ratio of valid data points required for aggregation to the next retention to occur
#  aggregationMethod: function to apply to data points for aggregation
#

[counters_fall_here]
pattern = ^(counters)\.(production)
xFilesFactor = 0.0
aggregationMethod = sum

[timers_fall_here]
pattern = .*
xFilesFactor= 0.0
aggregationMethod = average
```

**Comment by deniszh** [comment]
Unfortunately,  I see no easy explanation for this behaviour, having configs above. Did you change retentions and/or storage schemas after creating metrics?
Could you please show output of `whisper-info.py collectd/production/ec2/ip-w-x-y-z/cpu-0.wsp` command?

**Comment by rajats105** [comment]
Actually cpu-0 is not a metric in itself.
```
.
├── cpu-0
│   ├── cpu-idle.wsp
│   ├── cpu-interrupt.wsp
│   ├── cpu-softirq.wsp
│   ├── cpu-steal.wsp
│   └── cpu-user.wsp
├── df-dev
│   ├── df_complex-reserved.wsp
│   ├── df_complex-used.wsp
```

Running whisper-info in all of the metrics mentioned above gives same output.
```whisper-info.py /opt/graphite/storage/whisper/collectd/production/ec2/ip-x-x-x-x/cpu-0/cpu-{xyz}.wsp```
```maxRetention: 5184000
xFilesFactor: 0.0
aggregationMethod: average
fileSize: 207388

Archive 0
retention: 5184000
secondsPerPoint: 300
points: 17280
size: 207360
offset: 28
```

**Comment by deniszh** [comment]
Sorry, then I have no explanation. Maybe we have some bug in sumserieswithwildcards() but I can't reproduce it.

**Comment by reyjrar** [comment]
I was experiencing a similar issue and upgraded to 1.1.1 and the issue is resolved now.
