### ISSUE TITLE
error starting up wsgi

### ISSUE THREAD

**Issue by rpk113** [graphite-project/graphite-web#1991]
[Fri Jul 07 14:26:50.491486 2017] [wsgi:error] [pid 2226:tid 140111068669696]   File "python/common/Django/Django-1.10.2-py2.7.egg/django/conf/__init__.py", line 123, in __init__
[Fri Jul 07 14:26:50.491514 2017] [wsgi:error] [pid 2226:tid 140111068669696]     os.path.exists(os.path.join(zoneinfo_root, *(self.TIME_ZONE.split('/'))))):
[Fri Jul 07 14:26:50.491543 2017] [wsgi:error] [pid 2226:tid 140111068669696] AttributeError: 'America/New_York' object has no attribute 'split'

**Comment by deniszh** [comment]
Which version of Graphite are you using? 1.0.x supports only Django 1.9, not 1.10

**Comment by rpk113** [comment]
tried django 1.9

[Fri Jul 07 18:47:52.718850 2017] [wsgi:error] [pid 28770:tid 140199944910592]   File "/python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 137, in __init__
[Fri Jul 07 18:47:52.718876 2017] [wsgi:error] [pid 28770:tid 140199944910592]     os.path.exists(os.path.join(zoneinfo_root, *(self.TIME_ZONE.split('/'))))):
[Fri Jul 07 18:47:52.718905 2017] [wsgi:error] [pid 28770:tid 140199944910592] AttributeError: 'America/New_York' object has no attribute 'split'

same issue

**Comment by deniszh** [comment]
something wrong with your local_settings.py. Could you please show it (w/o comments).

**Comment by rpk113** [comment]
import sys, os
sys.path.append('mdsinfra/mds_software/collectd/common/scripts')
sys.path.append('python/tzlocal/1.2/common/tzlocal-1.2-py2.7.egg')
import cmf_werks, tzlocal
logdir = cmf_werks.getLogDir()
TIME_ZONE = America/New_York
GRAPHITE_ROOT = '{}graphite'.format(logdir)
CONF_DIR = '{}graphite/conf'.format(logdir)
STORAGE_DIR = '{}carbon/storage'.format(logdir)
STATIC_ROOT = '{}graphite/static'.format(logdir)
LOG_DIR = logdir
DASHBOARD_CONF = '{}/dashboard.conf'.format(CONF_DIR)
GRAPHTEMPLATES_CONF = '{}/conf/graphTemplates.conf'.format(CONF_DIR)
WHISPER_DIR = '{}/whisper'.format(STORAGE_DIR)

**Comment by deniszh** [comment]
Try to put timezone in quotes - 
`TIME_ZONE = 'America/New_York'`
Not sure if related, though - but all strings are quoted in my config.

**Comment by DanCech** [comment]
Yes, that would do it.  The config file is a python script so it needs to be valid python syntax, including string quoting.

**Comment by rpk113** [comment]
Does that include when incorporating it into an httpd server?  
I changed to this TIME_ZONE = 'America/New_York'
but the local.setttings.py doesn't seem to recompile.
So I still get my error

**Comment by rpk113** [comment]
Maybe I'm missing something, here is full error..

[Mon Jul 10 10:51:22.008803 2017] [wsgi:error] [pid 23880:tid 140562645305088] mod_wsgi (pid=23880): Target WSGI script '/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Mon Jul 10 10:51:22.008869 2017] [wsgi:error] [pid 23880:tid 140562645305088] mod_wsgi (pid=23880): Exception occurred processing WSGI script '/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi'.
[Mon Jul 10 10:51:22.008912 2017] [wsgi:error] [pid 23880:tid 140562645305088] Traceback (most recent call last):
[Mon Jul 10 10:51:22.008951 2017] [wsgi:error] [pid 23880:tid 140562645305088]   File "/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi", line 5, in <module>
[Mon Jul 10 10:51:22.009023 2017] [wsgi:error] [pid 23880:tid 140562645305088]     from graphite.wsgi import application
[Mon Jul 10 10:51:22.009056 2017] [wsgi:error] [pid 23880:tid 140562645305088]   File "mdsinfra/amrs/graphite/common/webapp/graphite/wsgi.py", line 16, in <module>
[Mon Jul 10 10:51:22.009149 2017] [wsgi:error] [pid 23880:tid 140562645305088]     application = get_wsgi_application()
[Mon Jul 10 10:51:22.009185 2017] [wsgi:error] [pid 23880:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/core/wsgi.py", line 13, in get_wsgi_application
[Mon Jul 10 10:51:22.009267 2017] [wsgi:error] [pid 23880:tid 140562645305088]     django.setup()
[Mon Jul 10 10:51:22.009382 2017] [wsgi:error] [pid 23880:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/__init__.py", line 17, in setup
[Mon Jul 10 10:51:22.009472 2017] [wsgi:error] [pid 23880:tid 140562645305088]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Mon Jul 10 10:51:22.009507 2017] [wsgi:error] [pid 23880:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 55, in __getattr__
[Mon Jul 10 10:51:22.009634 2017] [wsgi:error] [pid 23880:tid 140562645305088]     self._setup(name)
[Mon Jul 10 10:51:22.009668 2017] [wsgi:error] [pid 23880:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 43, in _setup
[Mon Jul 10 10:51:22.009721 2017] [wsgi:error] [pid 23880:tid 140562645305088]     self._wrapped = Settings(settings_module)
[Mon Jul 10 10:51:22.009751 2017] [wsgi:error] [pid 23880:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 137, in __init__
[Mon Jul 10 10:51:22.009791 2017] [wsgi:error] [pid 23880:tid 140562645305088]     os.path.exists(os.path.join(zoneinfo_root, *(self.TIME_ZONE.split('/'))))):
[Mon Jul 10 10:51:22.009832 2017] [wsgi:error] [pid 23880:tid 140562645305088] AttributeError: 'America/New_York' object has no attribute 'split'
[Mon Jul 10 10:51:22.015776 2017] [wsgi:error] [pid 23882:tid 140562645305088] mod_wsgi (pid=23882): Target WSGI script '/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Mon Jul 10 10:51:22.015805 2017] [wsgi:error] [pid 23882:tid 140562645305088] mod_wsgi (pid=23882): Exception occurred processing WSGI script '/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi'.
[Mon Jul 10 10:51:22.015835 2017] [wsgi:error] [pid 23882:tid 140562645305088] Traceback (most recent call last):
[Mon Jul 10 10:51:22.015860 2017] [wsgi:error] [pid 23882:tid 140562645305088]   File "/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi", line 5, in <module>
[Mon Jul 10 10:51:22.015919 2017] [wsgi:error] [pid 23882:tid 140562645305088]     from graphite.wsgi import application
[Mon Jul 10 10:51:22.015939 2017] [wsgi:error] [pid 23882:tid 140562645305088]   File "mdsinfra/amrs/graphite/common/webapp/graphite/wsgi.py", line 16, in <module>
[Mon Jul 10 10:51:22.016017 2017] [wsgi:error] [pid 23882:tid 140562645305088]     application = get_wsgi_application()
[Mon Jul 10 10:51:22.016044 2017] [wsgi:error] [pid 23882:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/core/wsgi.py", line 13, in get_wsgi_application
[Mon Jul 10 10:51:22.016112 2017] [wsgi:error] [pid 23882:tid 140562645305088]     django.setup()
[Mon Jul 10 10:51:22.016134 2017] [wsgi:error] [pid 23882:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/__init__.py", line 17, in setup
[Mon Jul 10 10:51:22.016199 2017] [wsgi:error] [pid 23882:tid 140562645305088]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Mon Jul 10 10:51:22.016221 2017] [wsgi:error] [pid 23882:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 55, in __getattr__
[Mon Jul 10 10:51:22.016333 2017] [wsgi:error] [pid 23882:tid 140562645305088]     self._setup(name)
[Mon Jul 10 10:51:22.016355 2017] [wsgi:error] [pid 23882:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 43, in _setup
[Mon Jul 10 10:51:22.016387 2017] [wsgi:error] [pid 23882:tid 140562645305088]     self._wrapped = Settings(settings_module)
[Mon Jul 10 10:51:22.016404 2017] [wsgi:error] [pid 23882:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 137, in __init__
[Mon Jul 10 10:51:22.016431 2017] [wsgi:error] [pid 23882:tid 140562645305088]     os.path.exists(os.path.join(zoneinfo_root, *(self.TIME_ZONE.split('/'))))):
[Mon Jul 10 10:51:22.016461 2017] [wsgi:error] [pid 23882:tid 140562645305088] AttributeError: 'America/New_York' object has no attribute 'split'
[Mon Jul 10 10:51:22.028042 2017] [wsgi:error] [pid 23884:tid 140562645305088] mod_wsgi (pid=23884): Target WSGI script '/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Mon Jul 10 10:51:22.028089 2017] [wsgi:error] [pid 23884:tid 140562645305088] mod_wsgi (pid=23884): Exception occurred processing WSGI script '/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi'.
[Mon Jul 10 10:51:22.028130 2017] [wsgi:error] [pid 23884:tid 140562645305088] Traceback (most recent call last):
[Mon Jul 10 10:51:22.028174 2017] [wsgi:error] [pid 23884:tid 140562645305088]   File "/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi", line 5, in <module>
[Mon Jul 10 10:51:22.028244 2017] [wsgi:error] [pid 23884:tid 140562645305088]     from graphite.wsgi import application
[Mon Jul 10 10:51:22.028276 2017] [wsgi:error] [pid 23884:tid 140562645305088]   File "mdsinfra/amrs/graphite/common/webapp/graphite/wsgi.py", line 16, in <module>
[Mon Jul 10 10:51:22.028664 2017] [wsgi:error] [pid 23884:tid 140562645305088]     application = get_wsgi_application()
[Mon Jul 10 10:51:22.028704 2017] [wsgi:error] [pid 23884:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/core/wsgi.py", line 13, in get_wsgi_application
[Mon Jul 10 10:51:22.028786 2017] [wsgi:error] [pid 23884:tid 140562645305088]     django.setup()
[Mon Jul 10 10:51:22.028818 2017] [wsgi:error] [pid 23884:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/__init__.py", line 17, in setup
[Mon Jul 10 10:51:22.028898 2017] [wsgi:error] [pid 23884:tid 140562645305088]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Mon Jul 10 10:51:22.028932 2017] [wsgi:error] [pid 23884:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 55, in __getattr__
[Mon Jul 10 10:51:22.029061 2017] [wsgi:error] [pid 23884:tid 140562645305088]     self._setup(name)
[Mon Jul 10 10:51:22.029094 2017] [wsgi:error] [pid 23884:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 43, in _setup
[Mon Jul 10 10:51:22.029139 2017] [wsgi:error] [pid 23884:tid 140562645305088]     self._wrapped = Settings(settings_module)
[Mon Jul 10 10:51:22.029168 2017] [wsgi:error] [pid 23884:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 137, in __init__
[Mon Jul 10 10:51:22.029209 2017] [wsgi:error] [pid 23884:tid 140562645305088]     os.path.exists(os.path.join(zoneinfo_root, *(self.TIME_ZONE.split('/'))))):
[Mon Jul 10 10:51:22.029250 2017] [wsgi:error] [pid 23884:tid 140562645305088] AttributeError: 'America/New_York' object has no attribute 'split'
[Mon Jul 10 10:51:22.035874 2017] [wsgi:error] [pid 23883:tid 140562645305088] mod_wsgi (pid=23883): Target WSGI script '/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Mon Jul 10 10:51:22.035907 2017] [wsgi:error] [pid 23883:tid 140562645305088] mod_wsgi (pid=23883): Exception occurred processing WSGI script '/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi'.
[Mon Jul 10 10:51:22.035936 2017] [wsgi:error] [pid 23883:tid 140562645305088] Traceback (most recent call last):
[Mon Jul 10 10:51:22.035962 2017] [wsgi:error] [pid 23883:tid 140562645305088]   File "/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi", line 5, in <module>
[Mon Jul 10 10:51:22.036023 2017] [wsgi:error] [pid 23883:tid 140562645305088]     from graphite.wsgi import application
[Mon Jul 10 10:51:22.036047 2017] [wsgi:error] [pid 23883:tid 140562645305088]   File "mdsinfra/amrs/graphite/common/webapp/graphite/wsgi.py", line 16, in <module>
[Mon Jul 10 10:51:22.036128 2017] [wsgi:error] [pid 23883:tid 140562645305088]     application = get_wsgi_application()
[Mon Jul 10 10:51:22.036152 2017] [wsgi:error] [pid 23883:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/core/wsgi.py", line 13, in get_wsgi_application
[Mon Jul 10 10:51:22.036221 2017] [wsgi:error] [pid 23883:tid 140562645305088]     django.setup()
[Mon Jul 10 10:51:22.036243 2017] [wsgi:error] [pid 23883:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/__init__.py", line 17, in setup
[Mon Jul 10 10:51:22.036309 2017] [wsgi:error] [pid 23883:tid 140562645305088]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Mon Jul 10 10:51:22.036380 2017] [wsgi:error] [pid 23883:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 55, in __getattr__
[Mon Jul 10 10:51:22.036511 2017] [wsgi:error] [pid 23883:tid 140562645305088]     self._setup(name)
[Mon Jul 10 10:51:22.036545 2017] [wsgi:error] [pid 23883:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 43, in _setup
[Mon Jul 10 10:51:22.036589 2017] [wsgi:error] [pid 23883:tid 140562645305088]     self._wrapped = Settings(settings_module)
[Mon Jul 10 10:51:22.036620 2017] [wsgi:error] [pid 23883:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 137, in __init__
[Mon Jul 10 10:51:22.036659 2017] [wsgi:error] [pid 23883:tid 140562645305088]     os.path.exists(os.path.join(zoneinfo_root, *(self.TIME_ZONE.split('/'))))):
[Mon Jul 10 10:51:22.036701 2017] [wsgi:error] [pid 23883:tid 140562645305088] AttributeError: 'America/New_York' object has no attribute 'split'
[Mon Jul 10 10:51:22.039782 2017] [wsgi:error] [pid 23881:tid 140562645305088] mod_wsgi (pid=23881): Target WSGI script '/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Mon Jul 10 10:51:22.039807 2017] [wsgi:error] [pid 23881:tid 140562645305088] mod_wsgi (pid=23881): Exception occurred processing WSGI script '/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi'.
[Mon Jul 10 10:51:22.039835 2017] [wsgi:error] [pid 23881:tid 140562645305088] Traceback (most recent call last):
[Mon Jul 10 10:51:22.039859 2017] [wsgi:error] [pid 23881:tid 140562645305088]   File "/data/mktlocal/logs/mktdata/graphite/conf/graphite.wsgi", line 5, in <module>
[Mon Jul 10 10:51:22.039917 2017] [wsgi:error] [pid 23881:tid 140562645305088]     from graphite.wsgi import application
[Mon Jul 10 10:51:22.039936 2017] [wsgi:error] [pid 23881:tid 140562645305088]   File "mdsinfra/amrs/graphite/common/webapp/graphite/wsgi.py", line 16, in <module>
[Mon Jul 10 10:51:22.040014 2017] [wsgi:error] [pid 23881:tid 140562645305088]     application = get_wsgi_application()
[Mon Jul 10 10:51:22.040038 2017] [wsgi:error] [pid 23881:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/core/wsgi.py", line 13, in get_wsgi_application
[Mon Jul 10 10:51:22.040105 2017] [wsgi:error] [pid 23881:tid 140562645305088]     django.setup()
[Mon Jul 10 10:51:22.040126 2017] [wsgi:error] [pid 23881:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/__init__.py", line 17, in setup
[Mon Jul 10 10:51:22.040192 2017] [wsgi:error] [pid 23881:tid 140562645305088]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Mon Jul 10 10:51:22.040214 2017] [wsgi:error] [pid 23881:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 55, in __getattr__
[Mon Jul 10 10:51:22.040338 2017] [wsgi:error] [pid 23881:tid 140562645305088]     self._setup(name)
[Mon Jul 10 10:51:22.040360 2017] [wsgi:error] [pid 23881:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 43, in _setup
[Mon Jul 10 10:51:22.040391 2017] [wsgi:error] [pid 23881:tid 140562645305088]     self._wrapped = Settings(settings_module)
[Mon Jul 10 10:51:22.040409 2017] [wsgi:error] [pid 23881:tid 140562645305088]   File "python/Django/1.9.13/common/2.7/lib/python/Django-1.9.13-py2.7.egg/django/conf/__init__.py", line 137, in __init__
[Mon Jul 10 10:51:22.040434 2017] [wsgi:error] [pid 23881:tid 140562645305088]     os.path.exists(os.path.join(zoneinfo_root, *(self.TIME_ZONE.split('/'))))):
[Mon Jul 10 10:51:22.040463 2017] [wsgi:error] [pid 23881:tid 140562645305088] AttributeError: 'America/New_York' object has no attribute 'split'

**Comment by piotr1212** [comment]
You do actually have that timezone info file installed? On my system it is in:
/usr/share/zoneinfo/America/New_York

**Comment by rpk113** [comment]
yeap..

# ls -lrt |grep New
-rw-r--r--   3 root root 3519 Mar 20 23:45 New_York
# pwd
/usr/share/zoneinfo/America

**Comment by piotr1212** [comment]
> but the local.setttings.py doesn't seem to recompile.

Not sure if this is a typo, but it should be local_settings.py (underscore instead of dot).

Also check if there is an local_settings.pyc or .pyo in the same directory, check if the server user has write access to those files and/or delete them/set correct permissions.

**Comment by rpk113** [comment]
sorry, type, it is local_settings.py

just for giggles I ran the devel web server to force local_settings.py to recompile with what I believe is the proper settings.  Then started up the httpd server with the same error.  Is there any other place that looks for/sets the TIME_ZONE?

**Comment by piotr1212** [comment]
Well to find out, set a completely different TIME_ZONE, and check which error message it will spawn then.

**Comment by rpk113** [comment]
So I changed TIME_ZONE = 'America/Chicago', recompiled with dev server, then ran httpd server
Same error as before:
[Mon Jul 10 12:01:57.978835 2017] [wsgi:error] [pid 23490:tid 140693908838144]     os.path.exists(os.path.join(zoneinfo_root, *(self.TIME_ZONE.split('/'))))):
[Mon Jul 10 12:01:57.978876 2017] [wsgi:error] [pid 23490:tid 140693908838144] AttributeError: 'America/New_York' object has no attribute 'split'

**Comment by piotr1212** [comment]
So it doesn't pick up your local_settings.py

What do you exactly mean with "recompile the server"?

**Comment by rpk113** [comment]
when I start the httpd server local_settings.py doesn't recompile to local_settings.pyc.  so I do it via the devel server.

**Comment by piotr1212** [comment]
Then I think it is looking in a different path for the local_settings.py. You can check if you have more than one local_settings on your system or strace the httpd server to see what it actually opens

**Comment by rpk113** [comment]
ran strace against the httpd process.  I didn't see any logging that opened local_settings.

**Comment by rpk113** [comment]
I think I fixed it.  there was a second file and the time zone was not a string object.  Now if I can just get the website to show
