### ISSUE TITLE
Getting data points outside time range when summarizing the last X hours > greater than the displayed time range

### ISSUE THREAD

**Issue by ibribaliki** [graphite-project/graphite-web#2009]
Hello,
I'm not quite sure whether it's a bug or not, but here's the case:

In the graphite dashboard, I chose "Last 24 hours" to be displayed.
In addition, I took a metric which fires value 0 since yesterday.

the series I'm trying to show in the graph is summarize(ABC, '100h','sum').
I expect to see a flat line of 0 (using also transformNull(..,0) to pad the nulls)

However, I get a "data points outside time range" error. It seems that if I choose a smaller range such as 24, 23, ... the error disappears. Alternatively, if I choose time range of 1/1/1970 to now in the dashboard, I can see the summarize graph even with summation of 2 years or 3.
It means that the problem is that I can't sum values in datapoints which are considerable outside the chosen time range in the dashboard.

How can I fix that without changing the time range of the dash?

Thanks

**Comment by deniszh** [comment]
Are you sure are you using graphite? IIRC "data points outside time range" is influxdb error - e.g.
 https://github.com/grafana/grafana/issues/1913
I never saw similar error in Graphite graphs on Grafana.
