### ISSUE TITLE
info.log have render messages even LOG_RENDERING_PERFORMANCE = False

### ISSUE THREAD

**Issue by IldarMinaev** [graphite-project/graphite-web#2013]
Graphite info log have renderer messages even if I configure LOG_RENDERING_PERFORMANCE = False

Issue in following code line:
https://github.com/graphite-project/graphite-web/blob/3eded1d74fe36facdad606f5e088023dfecfd410/webapp/graphite/util.py#L238
I believe it must be log.rendering

**Comment by deniszh** [comment]
The line above is a part of `logtime` decorator which is calling from many places. But it needs to be fixed, though.
