### ISSUE TITLE
In 1.0.2 the functions movingAverage and timeShift don't work properly, but in master they do

### ISSUE THREAD

**Issue by replay** [graphite-project/graphite-web#2015]
I created a test setup with graphite `1.0.2` and `REMOTE_PREFETCH_DATA = True`. The function `timeShift()` seems to not have any effect at all. `movingAverage()` only works as long as the given time span is not longer than the queried time range.

When i check out `master` or turn off `REMOTE_PREFETCH_DATA` then it all works, so I think there must be a bug related to prefetching which has been fixed between `1.0.2` and `master`.

**Comment by deniszh** [comment]
@replay - https://github.com/graphite-project/graphite-web/commit/e5aa02407f9750fd9962d5b100c47beb5aa556a5 ?

**Comment by deniszh** [comment]
I thought we included it into 1.0.2 though...

**Comment by deniszh** [comment]
No looks like we didn't. *sigh*

**Comment by replay** [comment]
Yeah, appears that this was the fix :)

**Comment by DanCech** [comment]
@deniszh this is the same issue I'm referring to in #1970

**Comment by deniszh** [comment]
Yes, let's release it in 1.1.0 :)
