### ISSUE TITLE
Interactive Question

### ISSUE THREAD

**Issue by pauldavidgilligan** [graphite-project/graphite-web#2016]
I have a use case where a typical systems transactions might fail during processes and there is a URL you could click to retry the transaction. 

Had a good read through the docs but it is not clear how an event sent to graphite could contain a URL that could be "clicked" from the graphite UI and hence re-try the transaction (jumps away from Graphite's windows maybe).

Any thoughts ideas?

**Comment by deniszh** [comment]
IIRC Events API has no support in UI, it provides only API. Grafana has
Events support, but I'm not sure if it renders URLs in info field.
Unfortunately I'm AFK for some time now, but you can test it too.

**Comment by deniszh** [comment]
Yes, according to https://github.com/grafana/grafana/issues/1588 Grafana supporting that now.

**Comment by pauldavidgilligan** [comment]
Thank you great job could come in very handy.

⁣Sent from Blue ​
