### ISSUE TITLE
gunicorn compile error from requirements.txt

### ISSUE THREAD

**Issue by jblaine** [graphite-project/graphite-web#2018]
Perhaps a new gunicorn was released and the lack of a version pin in `requirements.txt` is causing this:

```
...
Installing collected packages: Django, python-memcached, txAMQP, simplejson, django-tagging, gunicorn, pytz, pyparsing, cairocffi, whitenoise, scandir, cffi, pycparser
  Running setup.py install for python-memcached

  Running setup.py install for txAMQP

  Running setup.py install for simplejson
    building 'simplejson._speedups' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c simplejson/_speedups.c -o build/temp.linux-x86_64-2.7/simplejson/_speedups.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/simplejson/_speedups.o -o build/lib.linux-x86_64-2.7/simplejson/_speedups.so

Compiling /tmp/pip_build_root/gunicorn/gunicorn/workers/_gaiohttp.py ...
  File "/tmp/pip_build_root/gunicorn/gunicorn/workers/_gaiohttp.py", line 84
    yield from self.wsgi.close()
             ^
SyntaxError: invalid syntax

  Running setup.py install for cairocffi
    generating cffi module 'build/lib.linux-x86_64-2.7/cairocffi/_ffi.py'
    generating cffi module 'build/lib.linux-x86_64-2.7/cairocffi/_ffi_pixbuf.py'
...
```

**Comment by deniszh** [comment]
`gunicorn` is not part of Graphite stack - why would we pin its version?
Looks like latest `gunicorn` became not compatible with python 2.6 - but latest Graphite requires python 2.7 too...

**Comment by jblaine** [comment]
Hasty close IMO.

`gunicorn` is in the `graphite-web` requirements.txt, so apparently it is part of the graphite stack indirectly.

https://github.com/graphite-project/graphite-web/blob/master/requirements.txt#L45

As you can see above in the output I pasted, the Python I am using is Python 2.7.

So, gunicorn is a dependency of graphite-web right now, is not pinned to any specific version of gunicorn, and gunicorn being fetched without that pin **does not work with Python 2.7** therefore graphite-web has a bug in its overall source/dep-pinning/whatever.

**Comment by deniszh** [comment]
Ugh... Sorry for that. Gunicorn is not a part of stack in any way. Will remove in from requirements asap.

**Comment by deniszh** [comment]
Ah, nvm. It's `pip` problem - https://github.com/benoitc/gunicorn/issues/982
But `gunicorn` should be removed from requirements anyway, though.

**Comment by deniszh** [comment]
After some thinking I would prefer to left it like this - it's a minor cosmetic issue with old pip/gunicorn, not sure if it's worth to spend time on it.
