### ISSUE TITLE
Graphite fails on systems in FIPS mode

### ISSUE THREAD

**Issue by hammondr** [graphite-project/graphite-web#2019]
OpenSSL is not allowed to perform MD5 operations on when the OS is in FIPS-mode.  (See: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Security_Guide-Federal_Standards_And_Regulations-Federal_Information_Processing_Standard.html)

When running graphite-web on such a node, it throws errors like this:

```
Request Method: | GET
-- | --
https://graphite.mydomain.net/metrics/expand?query=myhost.services.I_O_Wait.disk.perfdata.*
1.4.21
ValueError
error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
/usr/lib/python2.6/site-packages/graphite/render/hashing.py in compute_ring_position, line 82
/usr/bin/python
2.6.6
['/usr/lib/python2.6/site-packages',  '/usr/lib/python2.6/site-packages/pystache-0.5.3-py2.6.egg',  '/usr/lib/python2.6/site-packages/requests-1.2.3-py2.6.egg',  '/usr/lib/python2.6/site-packages/python_daemon-1.6-py2.6.egg',  '/usr/lib/python2.6/site-packages/lockfile-0.9.1-py2.6.egg',  '/usr/lib/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg',  '/usr/lib/python2.6/site-packages/ipython-1.2.1-py2.6.egg',  '/usr/lib/python2.6/site-packages/Cython-0.20.1-py2.6-linux-x86_64.egg',  '/usr/lib/python2.6/site-packages/supervisor-3.1.2-py2.6.egg',  '/usr/lib/python2.6/site-packages/meld3-1.0.0-py2.6.egg',  '/usr/lib64/python26.zip',  '/usr/lib64/python2.6',  '/usr/lib64/python2.6/plat-linux2',  '/usr/lib64/python2.6/lib-tk',  '/usr/lib64/python2.6/lib-old',  '/usr/lib64/python2.6/lib-dynload',  '/usr/lib64/python2.6/site-packages',  '/usr/lib64/python2.6/site-packages/gtk-2.0',  '/usr/lib/python2.6/site-packages',  '/usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info',  '/usr/share/graphite/webapp',  '/usr/lib/python2.6/site-packages/graphite/thirdparty']
```

Can the hashing algorithms be modernized or parameterized to allow graphite-web to run on such systems?

**Comment by piotr1212** [comment]
Hashing is not used for security purpose but for distributing metrics to different nodes in a cluster. Just replacing the hashing algorithm will break metrics distribution in relay's (carbon-relay, carbon-c-relay and carbon-relay-ng). Latest graphite-web, carbon, and carbon-c-relay do support fnv1a, you might try to use that (but you will need python 2.7). Or just disable the policy as it doesn't make sense in this context.

**Comment by hammondr** [comment]
Thanks, Piotr.  Are you saying there is a policy I can disable in graphite / carbon?  Or that I should disable the OS's FIPS policy?  (I can't do the latter because many government systems require the OS to operate in FIPS mode, crippling openssl's md5 features.)

**Comment by piotr1212** [comment]
Yes, OS policy. 

If you are on graphite 1.0.2 you can switch from `carbon_ch` md5 based hashing to  `fnv1a_ch`, see: [CARBONLINK_HASHING_TYPE](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/local_settings.py.example#L345-L353). You'll need to update your relay config as well.

**Comment by deniszh** [comment]
Yes, switching to carbon-c-relay and `fnv1a_ch` should help.

**Comment by GowthamShanmugam** [comment]
i have modified CARBONLINK_HASHING_TYPE = 'fnv1a_ch'  in "vi /usr/lib/python2.7/site-packages/graphite/local_settings.py"

do i want to run migrate command again? and without carbon-c-relay is it work?

**Comment by GowthamShanmugam** [comment]
I just modified CARBONLINK_HASHING_TYPE = 'fnv1a_ch' in "vi /usr/lib/python2.7/site-packages/graphite/local_settings.py" and restarted carbon-cache, and grphite gives 500 internel error.

can you please explain step by step what I have to do to make it work in FIPS mode

**Comment by deniszh** [comment]
CARBONLINK_HASHING_TYPE will only change "carbonlink" settings, i.e. how graphite-web looking for  graphite caches. We sharing some code between carbon and graphite-web obviously, but we have no support for fnv1a hash in default (python) version of relay. 
So, fnv1a_ch hashing will work only with "carbon-c-relay" and not with normal relay.

**Comment by deniszh** [comment]
Also please note that "fnv1a_ch" has was introduced in graphite 1.0.0 and it will not work in older versions.

**Comment by deniszh** [comment]
> ok, can you please have a look above traceback, is it Django not working with FIPS ?
> I am seeing this error when I try to run initialization on freshmachine:
>PYTHONPATH=$GRAPHITE_ROOT/webapp/ /usr/lib/python2.7/site-packages/django/bin/django-admin.py migrate --settings=graphite.settings --run-syncdb

Ah, that's completely different issue. This is a part of Django, and not a graphite. Then you probably need to run this command on different server and copy graphite.db file on new server. I traced Django code - `hashlib.md5()` is there for all supported versions.

> is there any document on how to configure carbon-relay

Yes, on carbon-c-realy repo - https://github.com/grobian/carbon-c-relay

**Comment by piotr1212** [comment]
Nothing we can do about it

**Comment by GowthamShanmugam** [comment]
Hi, I have some doubt related to fips mode, I have installed graphite-web and carbon-cache in a single machine and i am not using carbon-relay. I am unable to initialize the graphite-db in this case. need some help.

**Comment by piotr1212** [comment]
FIPS is really Red Hat specific. You might have more luck asking one of your colleagues.

**Comment by GowthamShanmugam** [comment]
Hi @piotr1212,
   I just want to make sure the way I am changing the hash type is correct, that why commented. 
  If the above case has any problem with Django and fips, 
    Then why i graphite is always referring MD5:
  Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/site-packages/django/core/handlers/exception.py&quot;, line 41, in inner
    response = get_response(request)
  File &quot;/usr/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File &quot;/usr/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/views.py&quot;, line 73, in renderView
    requestKey = hashRequest(request)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/hashing.py&quot;, line 62, in hashRequest
    return compactHash(normalizedParams)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/hashing.py&quot;, line 74, in compactHash
    return md5(string.encode(&#39;utf-8&#39;)).hexdigest()
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips  


I have initialized graphite.DB using normal setting and then i have enabled fips and continue with same graphite.db but it gives an error from graphite only.
