### ISSUE TITLE
An exception occurs when the metric path contains Unicode characters

### ISSUE THREAD

**Issue by zasca** [graphite-project/graphite-web#2023]
graphite-web 1.0.2 (0.9.15 not affected)

```
$ find /var/lib/graphite/whisper/app
/var/lib/graphite/whisper/app/
/var/lib/graphite/whisper/app/пример_рф
/var/lib/graphite/whisper/app/пример_рф/m1_rate.wsp
/var/lib/graphite/whisper/app/пример_рф/m15_rate.wsp

$ curl '127.0.0.1:8080/render/?from=-2hours&target=sumSeriesWithWildcards(app.*.m15_rate,%201)&format=json'
  ...
  File &quot;/opt/graphite/webapp/graphite/finders/standard.py&quot;, line 117, in _find_paths
    for match in self._find_paths(absolute_path, patterns):
  File &quot;/opt/graphite/webapp/graphite/finders/standard.py&quot;, line 83, in _find_paths
    entries = [x.name for x in scandir(current_dir)]
UnicodeDecodeError: &#39;ascii&#39; codec can&#39;t decode byte 0xd0 in position 30: ordinal not in range(128)
```

**Comment by zasca** [comment]
patch
```
--- standard.py_orig    2017-08-31 15:09:46.000000000 +0300
+++ standard.py 2017-09-05 11:28:14.000000000 +0300
@@ -90,7 +90,7 @@
     if using_globstar:
         matching_subdirs = map(operator.itemgetter(0), walk(current_dir))
     else:
-        subdirs = [entry for entry in entries if isdir(join(current_dir, entry))]
+        subdirs = [entry for entry in entries if isdir(join(current_dir, str(entry)))]
         matching_subdirs = match_entries(subdirs, pattern)
 
     # if this is a terminal globstar, add a pattern for all files in subdirs
@@ -113,15 +113,15 @@
     if patterns: #we've still got more directories to traverse
       for subdir in matching_subdirs:
 
-        absolute_path = join(current_dir, subdir)
+        absolute_path = join(current_dir, str(subdir))
         for match in self._find_paths(absolute_path, patterns):
           yield match
 
     else: #we've got the last pattern
       if not has_wildcard:
         entries = [ pattern + '.wsp', pattern + '.wsp.gz', pattern + '.rrd' ]
-      files = [entry for entry in entries if isfile(join(current_dir, entry))]
+      files = [entry for entry in entries if isfile(join(current_dir, str(entry)))]
       matching_files = match_entries(files, pattern + '.*')
 
       for base_name in matching_files + matching_subdirs:
-        yield join(current_dir, base_name)
+        yield join(current_dir, str(base_name))
```

**Comment by deniszh** [comment]
Thanks a lot, @zasca !
Could you please maybe make a PR from it?

**Comment by piotr1212** [comment]
I cannot reproduce this specific exception on clean 1.0.2 and master (I do get carbonlink exceptions though). I've recreated your path structure and using the same curl call. Are you using some specific configuration?

**Comment by zasca** [comment]
No, I'm not. I've specially launched a new environment in the docker container now. Base image ubuntu:trusty.

```
# python --version
Python 2.7.6
# pip list
argparse (1.2.1)
attrs (17.2.0)
Automat (0.6.0)
cairocffi (0.8.0)
cffi (1.10.0)
chardet (2.0.1)
colorama (0.2.5)
constantly (15.1.0)
Django (1.9.13)
django-tagging (0.4.3)
html5lib (0.999)
hyperlink (17.3.1)
incremental (17.5.0)
pip (1.5.4)
pycparser (2.18)
pyOpenSSL (17.2.0)
pyparsing (2.2.0)
python-apt (0.9.3.5ubuntu2)
pytz (2017.2)
requests (2.2.1)
scandir (1.5)
setuptools (3.3)
six (1.10.0)
ssh-import-id (3.21)
Twisted (17.5.0)
txAMQP (0.7.0)
urllib3 (1.7.1)
wheel (0.24.0)
whisper (1.0.2)
wsgiref (0.1.2)
zope.interface (4.4.2)
```

local_settings.py
```
LOG_RENDERING_PERFORMANCE = True
LOG_CACHE_PERFORMANCE = True
LOG_METRIC_ACCESS = True
GRAPHITE_ROOT = '/opt/graphite'
STORAGE_DIR = '/var/lib/graphite/whisper'
WHISPER_DIR = '/var/lib/graphite/whisper'
LOG_DIR = '/var/log/graphite'
DATABASES = {
    'default': {
        'NAME': '/var/lib/graphite/graphite.db',
        'ENGINE': 'django.db.backends.sqlite3',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': ''
    }
}
CARBONLINK_HOSTS = ['127.0.0.1:7002:a']
CARBONLINK_TIMEOUT = 1.0
```

dirname in hex:
```
# ls /var/lib/graphite/whisper/app | xxd -pu
d0bfd180d0b8d0bcd0b5d1805fd180d1840a
```

> I do get carbonlink exceptions though
This exception returned on the http request?

**Comment by piotr1212** [comment]
Are you running in apache httpd and mod_wsgi?
If so, could you please check if you get the same error when you add:
`
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
`
to /etc/apache2/envvars

I don't know if casting 'unicode' objects to str is the right thing to do in this case..

**Comment by zasca** [comment]
Yes, I use apache. But setting locale not fix the issue in my environment...
Also, I've tested this case at docker-graphite-statsd container and all work as expecting!

It looks like there really is a problem in the locale. I will continue to investigate.
Thanks, @piotr1212!

**Comment by brutasse** [comment]
> I don't know if casting 'unicode' objects to str is the right thing to do in this case..

In Python 2, 'str' objects are bytes. To convert them to unicode strings, the proper way is to call `.decode('<encoding>')` on them. To convert unicode strings to bytes, the opposite operation is `.encode('<encoding>')`. `str(some_unicode_string)` is bound to lead to a unicode error…

usually the encoding to use is 'utf-8' :)

**Comment by piotr1212** [comment]
> Yes, I use apache. But setting locale not fix the issue in my environment...
> Also, I've tested this case at docker-graphite-statsd container and all work as expecting!

> It looks like there really is a problem in the locale. I will continue to investigate.

Yes I too think it is something with the locale. Just can't figure out what, still cannot reproduce your issue (in ubuntu docker image). You might try adding `lang='en_US.UTF-8' locale='en_US.UTF-8'` to your `WSGIDaemonProcess` directive in your httpd vhost config. 

But remember, even if you get this fixed you will run into other UTF-8 issues. My advise would be to just use ASCII unless you are willing to spend a lot of time fixing issues.

**Comment by zasca** [comment]
>Yes I too think it is something with the locale.

My issue was that `/usr/lib/locale/locale-archive` was missing (this is default state at ubuntu 14.04 docker image, but does not at [phusion/baseimage](https://github.com/phusion/baseimage-docker) wich is used by [official Graphite & Statsd docker image](https://github.com/graphite-project/docker-graphite-statsd)). 

Steps to fix:

1. Create `/etc/locale.gen` and add locales and charsets
2. Run `locale-gen`
3. Ensure locales was added  to `/etc/apache2/envvars`, as [said](https://github.com/graphite-project/graphite-web/issues/2023#issuecomment-327434193) piotr1212 earlier
---
>But remember, even if you get this fixed you will run into other UTF-8 issues.

@piotr1212, you are right.

`127.0.0.1:8080/render/?from=-1y&target=%D0%BF.connections-accepted&format=json` is failing:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 130, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 7, in evaluateTarget
    tokens = grammar.parseString(target)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1632, in parseString
    raise exc
ParseException: Expected {Group:({"template" Suppress:("(") {Group:({W:(ABCD...,ABCD...) ...
```

Looks like the issue is in the `render/grammar.py`. Because, looks like, `pyparsing` [works](https://groups.google.com/d/msg/whoosh/CHl2OAGVvrM/GjeaH9VyytYJ) well with unicode. I tried to fix it, but with no success.

>My advise would be to just use ASCII unless you are willing to spend a lot of time fixing issues.

In some cases it is more convenient to work with Unicode.

**Comment by zasca** [comment]
As said earlier the issue was in the incorrect locale config.

> `127.0.0.1:8080/render/?from=-1y&target=%D0%BF.connections-accepted&format=json` is failing

And this issue looks related more to #2024.

Therefore, I close this.
