### ISSUE TITLE
opentracing support 

### ISSUE THREAD

**Issue by Dieterbe** [graphite-project/graphite-web#2027]
it would be great if graphite supported opentracing.
opentracing is a standardized way of implementing context propagation and submitting trace/span data,
which enables a low-overhead way to diagnose in a detailed way performance issues across different services (e.g. a proxy server, graphite itself, and graphite's backend datastore), provide context-aware logging and so forth. i'm not going to go too indepth, there's plenty of good articles/presentations online that show the value proposition.

it looks like there's already a django module https://github.com/opentracing-contrib/python-django , but basically graphite would have to do two things:
- when a context is passed via an incoming request, pass it on to backend datastores / other graphite peers
- mark spans in a few sensible places (e.g. around code paths that implement an amount of work that may take time)

for me in particular, if graphite-web implemented OT, it would help in tracking down performance issues in our backend, and see how requests are routed from proxy, to graphite-web, to cluster peers, to backend servers.

cc  @DanCech

**Comment by iksaif** [comment]
cc: @geobeau who is trying to do that with zipkin
