### ISSUE TITLE
monthly retention time

### ISSUE THREAD

**Issue by brobeckero** [graphite-project/graphite-web#2031]
hello,

I'm trying the add a kpi with on value per month.

This kpi is calculated on another system and cannot be computed using daily values ( nb of distinct user using the service: one customer can use the services 2 différents days and must be show as 1 customer ).

Is there a way to indicate carbon to keep one value per month ?

BR

**Comment by nnuss** [comment]
> >  Is there a way to indicate carbon to keep one value per month ?
> 
> Yes, you can configure the storage schema accordingly ...

Not exactly no. The size of a [whipser] datapoint must be a fixed multiple of a second (true months are not).
One point per day is a good way to capture this however; in combination with @piotr1212's suggestion to output it [daily]. (Which amounts to just over 4KB per year)

Be aware that in graphite 1 month == 30 days ; 1 year == 365 days (see [graphite/render/attime.py](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/attime.py#L146))

**Comment by brobeckero** [comment]
Hi,

Thx for your answers.

I can'to do that because my "customer" want to have a montly vision.

He wants to know how much customer used the service in january for exemple.

I will propose to compute continuousely one sliding month but it won't
answer to his need.

BR.

2017-09-08 20:15 GMT+04:00 Piotr Popieluch <notifications@github.com>:
