### ISSUE TITLE
Metrics api: get metrics from/until timestamp

### ISSUE THREAD

**Issue by tetianakh** [graphite-project/graphite-web#2036]
Hello,

I am trying to get all metrics from a timestamp, and all metrics until a timestamp, as described in the Metrics API [documentation](http://graphite-api.readthedocs.io/en/latest/api.html#metrics-find). I expect that only metrics created after/until the given timestamp will be returned. However, the `from` and `until` parameters seem to have no effect at the list of returned metrics.

How to use `from` and `until` parameters with `/metrics/find` endpoint?

**Comment by deniszh** [comment]
Unfortunately,  it's not possible in the current codebase. TBH I don't know why `from` and `until` parameters present in `find` call. Theoretically, they can be used in some external finder, but now nor Whisper nor Ceres storage not testing file creation date and not comparing `from` with it. Also, it will be quite hard to calculate `until` date for a particular metric - you need to check all archives and find "data edge" - it's can be quite complicated and resource intensive.
So, for now, I would say - it's only present for external storages, in current code it has no meaning.

**Comment by tetianakh** [comment]
Thank you for quick reply, @deniszh. Do you have an idea on how to get a list of metrics created in the last X minutes?

**Comment by deniszh** [comment]
You can find that info in carbon.log (looks like ' [creates] creating database file /opt/graphite/storage/whisper/blah.wsp (archive=[(60, 525600), (600, 518400)] xff=None agg=None)') and you can use something like https://github.com/eBayClassifiedsGroup/graphite-news to expose this info.

**Comment by tetianakh** [comment]
@deniszh thank you!
