### ISSUE TITLE
Multiple results for same time series from different CLUSTER_SERVERS

### ISSUE THREAD

**Issue by chrbayer84** [graphite-project/graphite-web#2039]
I'm trying to understand two statements from the documentation about cluster servers and behavior with multiple time series returned:
According to the docs, only the first response from a cluster server for a given query will be used

> CLUSTER_SERVERS Default: []  The list of IP addresses and ports of remote Graphite webapps in a cluster. Each of these servers should have local access to metric data to serve. The first server to return a match for a query will be used to serve that data.

On the other hand, this section from the same document suggests that multiple series that were received for a query will be merged with graphite>0.9.14:

> REMOTE_STORE_MERGE_RESULTS Default: True  During a rebalance of a consistent hash cluster, after a partition event on a replication > 1 cluster or in other cases we might receive multiple TimeSeries data for a metric key. Merge them together rather than choosing the “most complete” one (pre-0.9.14 behaviour).

Both statements are from https://graphite.readthedocs.io/en/latest/config-local-settings.html. 
I'm trying to understand what that means. Aren't these two statements a contradiction? To give you some context: I have a sharded setup of multiple cluster servers (carbon-like proprietary storage backend). One cluster server will have the time series data for one interval (-2d to -1d) and another server will have a different interval (say -1d to now). Will these two time series be merged into a single result with a query from -2d to now?

**Comment by deniszh** [comment]
No contradiction, just evolution :)
Seriously speaking it's just how it was implemented - initial implementation picked only first result from remote servers, which make scaling up quite hard. Then new behavior was implemented, but as any breaking change in minor release it was disabled by default in 0.9.14
But in 1.0.0 release this feature is enabled by default (still can be disabled btw) but nobody fixed docs in config file.

**Comment by chrbayer84** [comment]
Awesome, thanks!
