### ISSUE TITLE
InvalidTimeInterval thrown for date range before data present

### ISSUE THREAD

**Issue by mleinart** [graphite-project/graphite-web#204]
#### Imported from https://bugs.launchpad.net/bugs/960031

|  |  |
| --- | --- |
| Reported by | [david-henderson](https://launchpad.net/~david-henderson) |
| Date Created | Mar 20, 2012 |

I have a metric recorded to graphite that I want to produce a historical view for (e.g. the count in 2 months ago, last month and so far this month)

To do this, I am using the URL API with JSON formatting, using a summarise function over a fixed set of dates:

http://127.0.0.1:8804/render?from=20110202&until=20110303&target=summarize(my.metric, "29days")&format=json

This works fine if there is data in the range, but as soon as there isn't, an 500 with an InvalidTimeException is thrown:

Exception Type: InvalidTimeInterval
Exception Value:    Invalid time interval
Exception Location: /usr/local/lib/python2.7/dist-packages/whisper.py in file_fetch, line 659

This appears to originate from this part of file_fetch.py:

oldestTime = now - header['maxRetention']
  if fromTime < oldestTime:
    fromTime = oldestTime

  if not (fromTime < untilTime):
    raise InvalidTimeInterval("Invalid time interval")

The from time appears to be being advanced to a point after the until time, making it invalid.

In this situation, I think a null or zero value should be returned rather than throwing an exception?

**Comment by jgpaiva** [comment]
+1

**Comment by punnie** [comment]
+1
