### ISSUE TITLE
Install from master or stable branch?

### ISSUE THREAD

**Issue by luigiberrettini** [graphite-project/graphite-web#2041]
I saw that [documentation](https://github.com/graphite-project/graphite-web/blob/master/docs/install-pip.rst) says to install from source/pip taking from the master branch

Unfortunately master branch is under development and not released often.

I tried installing from the 1.0.x branch but to make it work I had to manually comment a line in `/opt/graphite/conf/graphite.wsgi`:
```python
#import graphite.metrics.search  # noqa
```

What is the advice for production ready and stable installations: master or 1.0.x?

**Comment by deniszh** [comment]
Stable release is currently 1.0.2, you can use release from Github or 1.0.x branch. You can also use master, it's usually stable enough to use it in production too.
Please note that `graphite.wsgi` [do not contain](https://github.com/graphite-project/graphite-web/blob/1.0.x/conf/graphite.wsgi.example)  `graphite.metrics.search` for long time already (starting 1.0.0 release).

**Comment by luigiberrettini** [comment]
Thanks for the info!

I cloned it from scratch but erroneously removed only the old webapp directory within the installation directory: it was taking my old conf file, sorry 😞
