### ISSUE TITLE
Metrics API: how to find the last (and first) timestamps available for a metric?

### ISSUE THREAD

**Issue by UnitedMarsupials** [graphite-project/graphite-web#2043]
It would appear, that to reliably determine, when a particular metric was last updated (or first created), a remote needs to make multiple requests.

Yet, this is, probably, the easiest thing for the server to determine -- in case of Whisper DB backend, for example, the server does not even need to _open_ the database -- it can respond by looking simply at the timestamps of the database-file(s) or directories (such as `ctime`, `mtime`).

It should be possible to do this reliably with a single API-request -- returning either the requested timestamp (last or first) or an error, if the metric does not exist.

**Comment by DanCech** [comment]
The problem with using ctime to determine timestamps is that they aren't always going to be reliable, but at the same time they should be better than just assuming that the last modified time is now.

**Comment by UnitedMarsupials** [comment]
Using `ctime` was just an example. Yes, a careless _copying_ of the Whisper file-tree or restoring from backup could break things -- though fixing them is easy too.

And the method may not work with other storage-methods. But _some_ way of querying these timestamps ought to be available...

**Comment by deniszh** [comment]
Also not sure if ctime/mtime is reliable enough. I would not rely on that for making requests anyway. If you just need to get this info for analytical purposes you can use what I proposed in https://github.com/graphite-project/graphite-web/issues/2036#issuecomment-329467099

**Comment by UnitedMarsupials** [comment]
> Also not sure if ctime/mtime is reliable enough.

Why? Of course, someone may mess them up either out of malice or incompetence, but the same can be said about all of the Graphite data -- there are no checksums, much less _cryptographic_ signatures of the databases, are there?

But using ctime/mtime was just a suggestion -- a possible implementation of the feature. Whether they are used or not, the functionality is needed.

> If you just need to get this info for analytical purposes [...]

I didn't think, I need to explain my use-case, but here goes... I'm developing a program to feed some already timestamped values (such as web-server logs) into Graphite. The values available may go back for weeks and months, but the program does not know, when its _previous instance_ ran, and so it can not know -- not reliably -- which values have already been submitted and which ones are new.

It would be very useful, if it were possible for the program to query the last timestamp of the value(s) from Graphite to avoid duplication.

**Comment by DanCech** [comment]
The simplest way to do that right now will be to call render on the series you're interested in and walk the result to find the last non-null value.

**Comment by UnitedMarsupials** [comment]
> and walk the result to find the last non-null value.

Yes, thank you. This is exactly what I meant, when I wrote -- in this very ticket -- the following: _to reliably determine, when a particular metric was last updated (or first created), a remote needs to make multiple requests_.
