### ISSUE TITLE
Graphite 1.1.0 release

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#2045]
I think it's time for new major release, with all these beautiful contributions from @DanCech - tags support and piping functions.
Planning to do that upcoming weekend,  let's think maybe we should include something else in the release.

**Comment by DanCech** [comment]
I have a few things still cooking, might ask you to hold off one more week depending on how things go.  Here are a few things that are on the hit list right now:

 - handling the case when all remote reads have failed (and there's no local finder), right now an empty result is returned but it really should be an error
 - middleware to properly format render error responses as JSON when using `format=json`
 - support for matching series by node/tag(s) in `asPercent`
 - an endpoint to return a list of supported functions

**Comment by deniszh** [comment]
@DanCech : sure, looks interesting!

**Comment by deniszh** [comment]
Still wondering when we should 'cut' 1.1.0
You still have something to add, @DanCech, right?

**Comment by DanCech** [comment]
Yeah #2103 is outstanding right now, we can go ahead with the release once that's merged I think. I don't want to hold the release up while I try to find time to finish the error format stuff.

**Comment by deniszh** [comment]
@DanCech : And documentation for new finders, right? 😉 
Thanks!

**Comment by DanCech** [comment]
Haha yeah that too

**Comment by deniszh** [comment]
Just FYI for curious - we're tracking progress to 1.1.0 in corresponding milestone - https://github.com/graphite-project/graphite-web/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.1.0

**Comment by DanCech** [comment]
Given the amount of new stuff in this release, I think we should tag a `1.1.0beta1` or similar release from master ASAP to get as much feedback as possible on the new features etc.

The major outstanding items I have for a 1.1.0 final release are the finder documentation and an update I'm working on to add support for federating the tagdb so we can scale that out across a cluster (Pr coming soon), but there are a handful of other small things I have in various stages of development also.

**Comment by deniszh** [comment]
I can cut 1.1.0-rc1 in Github releases very easy, but I'm not really sure that we need to put it (non-final version, I mean) on pip/documentation page etc. After that, it becomes full-fledged release anyway, not sure why it needs that `-rc` tag then.
Also, documentation is important ofc, but that's a minor thing. Changing compatibility of tag implementation (e.g. after https://github.com/graphite-project/graphite-web/issues/2122 ) - that's completely different story. Implementing federated TagDB - that's a completely new thing again.
IMO we should fully use semver now and make releases more often, incrementing subversion not only for bugfixes, but for some new feature too.
So, 1.1.0 is a major milestone, with tagging and functions chaining, but we can put federated tagdb  to 1.1.1, and handful of other small things - to 1.1.2 etc. Put them to issues and let's have a proper milestone then.
Any thoughts? @iksaif @obfuscurity @cbowman0 ?

**Comment by deniszh** [comment]
Also, for proper release I need to prepare release notes, changelog etc. Will not include that in -pre release yet.

**Comment by DanCech** [comment]
@deniszh I'd like to get it into 1.1.0, it's not going to break any existing interfaces but will make it much easier for folks to upgrade their existing sharded clusters since they'd be able to have each carbon-cache send tags to the corresponding graphite-web vs having to use a single central tagdb.  Let me get the patch finished and open the PR, then we can decide what to do in terms of releases.

**Comment by deniszh** [comment]
I just tagged 1.1.0-pre1 and pushed it to docker hub too.

**Comment by iksaif** [comment]
Would be great to advertise 1.1.0-pre1 a little bit to make sure that people try it before the release.
I'll try to release a version of BigGraphite that works with this (without custom TagDB for now) when we release 1.1.0 .

**Comment by DanCech** [comment]
I just realized that I haven't gotten around to the change from `_` to `_DOT_` in tagged series filenames, I'll get that done really quick then we should drop pre2

**Comment by deniszh** [comment]
OK, will release pre2 today. But I need to compile at least minimal "what's new" to advertise it properly. :)

**Comment by DanCech** [comment]
Some high-level items:
- Tag support
- Updated cluster request handling
- "pipe" function chaining syntax
- xFilesFactor support
- overhauled aggregation functions
- msgpack support

**Comment by deniszh** [comment]
Thanks, Dan, pushed 1.1.0-pre2, let's try to advertise it tomorrow.

**Comment by deniszh** [comment]
Oops, overlooked boo-boo with latest carbon commit in 1.1.0-pre2. Fixed and released 1.1.0-pre3 instead.

**Comment by deniszh** [comment]
1.1.0-rc released as "final release candidate". So, I'm going to 
- prepare release notes / what's new
- fork 1.1.0 as a separate branch
- upgrade component's versions in master
@DanCech - it's a good time to finish plugin dev docs ;)

**Comment by admin-pro** [comment]
Hello all,

Someone can help me about the process to upgrade from graphite source installed version 0.9.13 to the latest please ?

**Comment by deniszh** [comment]
@admin-pro ,
Do you have any specific problems during upgrade or just interest in the process?
It's quite dependant on your current OS and installation type (from packgage or source, using virtualenv or not).

**Comment by admin-pro** [comment]
Hello @deniszh  thank you for your return. To be honest. I have install from source the graphite after git clone : 

git clone https://github.com/graphite-project/graphite-web.git && git clone https://github.com/graphite-project/carbon.git && git clone https://github.
com/graphite-project/whisper.git

cd whisper; git checkout 0.9.13-pre1; python setup.py install
cd ../carbon; git checkout 0.9.13-pre1; python setup.py install
cd ../graphite-web; python check-dependencies.py; git checkout 0.9.13-pre1; python setup.py

By following a guide on the web... But i saw too late that the last version is 1.1.1 of graphite. So now, i want to know the right process to upgrade from my current version to the latest.

Actually my server are in production and received many metrics.

My OS is CentOS 7.4

Thanks a lot

**Comment by deniszh** [comment]
Sorry for not updating this issue btw.
Current status - 1.1.1 release is done, I want to backport some patches from master and release 1.1.2

**Comment by deniszh** [comment]
@admin-pro,
What's your Django version and how it's installed? Graphite 1.1.x requires Django 1.8 or newer. If you do not have it - then you can upgrade only to 0.9.16 and not on 1.0.x/1.1.x unfortuntely

**Comment by admin-pro** [comment]
@deniszh 

Here my Django version : 

![image](https://user-images.githubusercontent.com/19953088/34542112-7866a7c8-f0db-11e7-8d7d-bb010a95510b.png)

So i can't upgrade Graphite ?

But if i upgrade Django first from current version to 1.8 or newer , do you think it is possible ?

Thx a lots again dude

**Comment by deniszh** [comment]
Yes, but if you have Django installed using package upgrade is not trivial - you can't easily replace newer django from source in this case - https://unix.stackexchange.com/questions/278468/should-we-let-python-pip-overwrite-modules-that-were-installed-by-rpm

**Comment by admin-pro** [comment]
Thank you @deniszh 

Yes, is not easy.

I have installed django from "pip install" not from "yum install" as you can see bellow (from my history commands) : 

curl -O https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip install pyparsing
pip install 'Twisted<12.0'
pip install 'django<1.5'
pip install 'django-tagging==0.3.6'

I'm thinking about restarting from scratch on a new server by a "simple" yum install graphite or install from source with the latest version... Then migrate all my wishpers to the new server.

Thank you a lot @deniszh for your help.

**Comment by deniszh** [comment]
@admin-pro,
From the source you can easily upgrade that, indeed. Please note that from yum you will install only v0.9.16 from EPEL repo, newer is only can be installed from source, because of dependencies.

**Comment by Serphentas** [comment]
Not sure if this is the right place to ask, but is there any documentation on how to get this version of Graphite to run behind uWSGI (in case of an nginx setup) ? So far, I've only found bits of information on how to use Apache and nothing else.

**Comment by deniszh** [comment]
I would recommend using Nginx + Gunicorn instead. You can peek how it's done in official Graphite image - https://github.com/graphite-project/docker-graphite-statsd or 3rd paty images, like - https://hub.docker.com/r/yesoreyeram/graphite-nginx-gunicorn/~/dockerfile/.

It's mostly simple proxying Nginx (like https://gist.github.com/bhang/3003978) and gunicorn runner (like https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/etc/service/graphite/run)

But you probably right, we need to collect deployment docs in something like GraphiteAPI has - https://github.com/brutasse/graphite-api/blob/master/docs/deployment.rst

**Comment by admin-pro** [comment]
@deniszh Yes thank you man.

@deniszh Do you know how i can verify exactly the version of graphite installed and used for my metrics please ?

**Comment by deniszh** [comment]
@admin-pro,
Something like `pip freeze | grep graphite` should give you version. Also try go to http://<yourgraphiteurl>/version/

**Comment by admin-pro** [comment]
Yes ! Great ! Thank you @deniszh 

Do you know if i will have a specific impact on my server and metrics received if i upgrade my django and my graphite version from source with following commands please ? 

pip install https://github.com/graphite-project/whisper/tarball/master
pip install https://github.com/graphite-project/carbon/tarball/master
pip install https://github.com/graphite-project/graphite-web/tarball/master

I have tried this on the clone of my production server and i have to installed new packages for install properly the latest version(he uninstall auto the older :+1:  ) but i'm not sure if all it's ok : 

pip freeze list on the clone server after pip install new release : 

carbon==1.2.0
Django==1.11.9
django-tagging==0.3.1
graphite-web==1.2.0
whisper==1.2.0

Here my packages version on the current production server : 

i have only django and whisper installed :rofl:  : 

whisper==0.9.13
django-tagging==0.3.6
Django==1.4.22

**Conclusion, on the clone server i have performed all the following commands** : 

_yum install python-django python-pip python-cffi python-django-tagging python-simplejson python-rrdtool cairo-devel
pip install --upgrade django
export PYTHONPATH="/opt/graphite/lib/:/opt/graphite/webapp/"
pip install https://github.com/graphite-project/whisper/tarball/master
pip install https://github.com/graphite-project/carbon/tarball/master
pip install https://github.com/graphite-project/graphite-web/tarball/master_

Thanks a lot @deniszh

**Comment by deniszh** [comment]
@admin-pro 
Your command looks OK, but of course, not me nor anyone else could give you any guarantees what's happened when you run it on your production server. It probably will run fine, but it can destroy all your config and data or anything else.
Try testing server, make backups and good luck with the upgrade!

**Comment by Serphentas** [comment]
Thanks @deniszh, I got the stack running now.

About that documentation you say, I'm making my own now so I wouldn't mind contributing to that if it's possible.

**Comment by JeanFred** [comment]
>  is there any documentation on how to get this version of Graphite to run behind uWSGI (in case of an nginx setup) ?

@Serphentas In case this helps, here is the Ansible play I use to run Graphite with UWSGI+Nginx. I have not tested it yet against 1.x series but it should mostly work there as well.

**Comment by Serphentas** [comment]
@JeanFred I can't see any file or link. Did you actually include it ?

**Comment by deniszh** [comment]
@Serphentas,
Thanks! Documentation is in the same repo - https://github.com/graphite-project/graphite-web/tree/master/docs

**Comment by JeanFred** [comment]
@Serphentas Arf, forgot the link. Here it is : https://gist.github.com/JeanFred/f9357bb485fd9428d52895951e26875d :)

**Comment by deniszh** [comment]
I'm going to release bugfix 1.1.2 release soon BTW, will open a separate issue for that.
