### ISSUE TITLE
Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module

### ISSUE THREAD

**Issue by blade1989** [graphite-project/graphite-web#2046]
I am trying to install `carbon`, `ceres`, `graphite-web` and `whisper` on a Debian `7.11` system.

I installed everything according to the [Graphite Documentation][1] and `ps auxf` shows all the aforementiond software up and running.

But when I access the Graphite Server, I am greated with an `Internal Server Error` page.

The error logs displays the following message, when accessing the Graphite server.

     mod_wsgi (pid=9951): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
     mod_wsgi (pid=9951): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
     Traceback (most recent call last):
       File "/opt/graphite/conf/graphite.wsgi", line 4, in <module>
         from graphite.wsgi import application
       File "/opt/graphite/webapp/graphite/wsgi.py", line 14, in <module>
         application = get_wsgi_application()
       File "/usr/local/lib/python2.7/dist-packages/Django-1.11.5-py2.7.egg/django/core/wsgi.py", line 13, in get_wsgi_application
         django.setup(set_prefix=False)
       File "/usr/local/lib/python2.7/dist-packages/Django-1.11.5-py2.7.egg/django/__init__.py", line 27, in setup
         apps.populate(settings.INSTALLED_APPS)
       File "/usr/local/lib/python2.7/dist-packages/Django-1.11.5-py2.7.egg/django/apps/registry.py", line 78, in populate
         raise RuntimeError("populate() isn't reentrant")
     RuntimeError: populate() isn't reentrant

What I have tried so far:

 - Installing the proper dependencies: `libapache2-mod-python` `libapache2-mod-wsgi`
 - Making the `graphite.wsgi` excecutable(`chmod +x graphite.wsgi`)
 - Removing the duplicate `LoadModule wsgi_module modules/mod_wsgi.so` from `graphite-vhost.conf`. `wsgi.load` includes the same file.
 - `django` is installed: `python -c "import django; print(django.get_version())"` outputs "`1.11.5`"

  [1]: http://graphite.readthedocs.io/en/latest/

**Comment by deniszh** [comment]
IIRC `populate() isn't reentrant` is not a real problem, it' just a symptom. You can try to use special wsgi file for find proper error - https://stackoverflow.com/a/30968197/1139639

**Comment by deniszh** [comment]
PS: Also this happening when you mixed up Apache and mod_uwsgi versions - they're should be the same.

**Comment by 6d6178** [comment]
The last time this happened to me (yesterday) I have resolved this error with
`systemctl stop httpd`
`systemctl start httpd`

When I used 
`systemctl restart httpd`
it didn't work.
I can imagine it being some parts of mod_wsgi/httpd that aren't fully closed with restart, but that's just a guess. If someone stumbles upon this comment I would greatly appreciate feedback if this resolved the error.

**Comment by izavyalov** [comment]
Got similar issue with

    Django VERSION = (1, 9, 12, 'final', 0)
    graphite VERSION = (1, 1, 5)

At the end issue was about wrong ownership on log files and graphite wouldn't start (misconfigured logrotate that would set non-graphite user on access.log / error.log files).

**Comment by rschitz** [comment]
> Got similar issue with
> 
> ```
> Django VERSION = (1, 9, 12, 'final', 0)
> graphite VERSION = (1, 1, 5)
> ```
> 
> At the end issue was about wrong ownership on log files and graphite wouldn't start (misconfigured logrotate that would set non-graphite user on access.log / error.log files).

got the same issue with logs and db permission issues, thanks for the comment
