### ISSUE TITLE
Issues with tagged series

### ISSUE THREAD

**Issue by iksaif** [graphite-project/graphite-web#2048]
I tried to use the new tagged series  (with the local tag database) but wasn't able to read points back. Looks like the path stored in the tag database doesn't contain the prefix generated by `encode()`, and the finder is not able to find the associated whisper file.

Am I missing anything here ?

cc: @DanCech

**Comment by DanCech** [comment]
The tag index deals with the logical names, the encoded names in the whisper file hierarchy are only used to make sure that we distribute the files properly on the filesystem.

Can you share the list of series you have in the index and the output of `find storage/whisper/_tagged -type f`?

**Comment by iksaif** [comment]
On the filesystem:

{code}
    └── _tagged
        ├── 200
        │   └── 97e
        │       └── tags-diceroll2;foo=bar5;label=value.wsp
        ├── 6d8
        │   └── 5fe
        │       └── tags-diceroll2;foo=bar2;label=value.wsp
        ├── 800
        │   └── a22
        │       └── tags-diceroll;foo=bar;label=value.wsp
        └── d16
            └── 0fa
                └── tags-diceroll2;foo=bar;label=value.wsp
{code}

In the database:

{code}
tags_series:
50|800a22102fd965a88dc9588446cc17838ac77d795f9b845b836dcc2476b0324e|tags.diceroll;foo=bar;label=value
51|d160fae1a6a882cc459d0a456c71958614cebc801b39ece02754ee24daa02ab2|tags.diceroll2;foo=bar;label=value
52|6d85fe9b3066405a43f869d085b914fdabd145ccdb5aff28e04f7c4c8470cd06|tags.diceroll2;foo=bar2;label=value
53|20097e6e32bbddca626bbbfe325e1399367128a05c8764333df08e4362767d54|tags.diceroll2;foo=bar5;label=value
{code}


I tried `seriesByTag('label=value')` and get empty results. I added a `print` in the whisper finder and it seems to try to find these:

```
('find nodes', <FindQuery: tags.diceroll2;foo=bar2;label=value from Wed Oct  4 13:59:39 2017 until Thu Oct  5 13:59:39 2017>)
('find nodes', <FindQuery: tags.diceroll2;foo=bar5;label=value from Wed Oct  4 13:59:39 2017 until Thu Oct  5 13:59:39 2017>)
('find nodes', <FindQuery: tags.diceroll2;foo=bar;label=value from Wed Oct  4 13:59:39 2017 until Thu Oct  5 13:59:39 2017>)
('find nodes', <FindQuery: tags.diceroll;foo=bar;label=value from Wed Oct  4 13:59:39 2017 until Thu Oct  5 13:59:39 2017>)
```

**Comment by DanCech** [comment]
That all looks correct, the whisper finder is responsible for handling the encoding back into the `_tagged` format, since it may be handled differently by different readers.  You can see that happens at https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/finders/standard.py#L33-L37

I wonder if there is some encoding issue that's resulting in a different hash and therefore it can't find the files on disk...

**Comment by DanCech** [comment]
Are you sure you have your whisper finder enabled?

I just did a quick test here:

```
# sha256sum, this should match the file path
$ echo -n 'tags.diceroll2;foo=bar5;label=value' | sha256sum
20097e6e32bbddca626bbbfe325e1399367128a05c8764333df08e4362767d54  -

# send a point to carbon so it creates the whisper file and tagdb entry
$ echo 'tags.diceroll2;foo=bar5;label=value 1 '$(date +%s) | nc localhost 2003

# validate that the whisper file is where we expect it
$ find storage/whisper -type f -name '*diceroll*'
storage/whisper/_tagged/200/97e/tags-diceroll2;foo=bar5;label=value.wsp

# verify that the entry is present in the TagDB
$ curl 'http://localhost:8000/tags/findSeries?expr=label=value'
["tags.diceroll2;foo=bar5;label=value"]

# query the series
$ curl 'http://localhost:8000/render?format=json&target=seriesByTag("label=value")|sortByName()&from=-1min'
[{"datapoints": [[null, 1507214640]], "target": "tags.diceroll2;foo=bar5;label=value", "tags": {"foo": "bar5", "name": "tags.diceroll2", "label": "value"}}]
```

**Comment by iksaif** [comment]
Ok .. my graphite web was pointing to the wrong directory (/tmp/whisper/whisper ..).

Sorry for the noise !

**Comment by DanCech** [comment]
That would explain it ;)
