### ISSUE TITLE
Getting 500 error after the installation of graphite on centos 6.5 

### ISSUE THREAD

**Issue by kthallam** [graphite-project/graphite-web#2049]
Getting 500 error after the installation of graphite on centos 6.5 

ERROR_LOG File : 

mod_wsgi (pid=10854): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/whitenoise/base.py", line 119, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_class = import_by_path(middleware_path)
  File "/usr/lib/python2.6/site-packages/django/utils/module_loading.py", line 31, in import_by_path
    error_prefix, module_path, class_name))
ImproperlyConfigured: Module "django.contrib.auth.middleware" does not define a "SessionAuthenticationMiddleware" attribute/class
mod_wsgi (pid=10851): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/whitenoise/base.py", line 119, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_class = import_by_path(middleware_path)
  File "/usr/lib/python2.6/site-packages/django/utils/module_loading.py", line 31, in import_by_path
    error_prefix, module_path, class_name))
ImproperlyConfigured: Module "django.contrib.auth.middleware" does not define a "SessionAuthenticationMiddleware" attribute/class

PIP Freeze ouput: 

You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
argparse==1.4.0
attrs==17.2.0
Automat==0.6.0
Beaker==1.3.1
cachetools==2.0.1
cairocffi==0.8.0
cas==0.15
cffi==1.11.1
Conch==8.2.0
constantly==15.1.0
decorator==3.0.1
Django==1.6
django-tagging==0.3.2
ethtool==0.6
firstboot==1.110
fpconst==0.7.3
freeipa==2.0.0a0
gunicorn==19.7.1
hyperlink==17.3.1
incremental==17.5.0
iniparse==0.3.1
iotop==0.3.2
ipapython==3.0.0
iwlib==1.0
kerberos==1.0
lxml==2.2.3
Mako==0.3.4
MarkupSafe==0.9.2
matplotlib==0.99.1.1
netaddr==0.7.5
nose==0.10.4
numpy==1.4.1
ordereddict==1.2
paramiko==1.7.5
preupgrade-assistant==0.9.1
pycparser==2.18
pycrypto==2.0.1
pycurl==7.19.0
pygpgme==0.1
pyOpenSSL==0.10
pyparsing==2.2.0
python-dateutil==1.4.1
python-default-encoding==0.1
python-ldap==2.3.10
python-meh==0.11
python-memcached==1.47
python-nss==0.13
pytz===2010h
pyxdg==0.18
PyXML==0.8.4
redhat-upgrade-tool==0.7.22
scandir==1.6
scdate==1.9.60
sckdump==2.0.5
scservices==0.99.45
scservices.dbus==0.99.45
simplejson==2.1.6
six==1.11.0
slip==0.2.20
slip.dbus==0.2.20
slip.gtk==0.2.20
SOAPpy==0.11.6
SSSDConfig==1.9.2
Twisted==13.2.0
Twisted-Core==8.2.0
Twisted-Lore==8.2.0
Twisted-Mail==8.2.0
Twisted-Names==8.2.0
Twisted-News==8.2.0
Twisted-Runner==8.2.0
Twisted-Web==8.2.0
Twisted-Words==8.2.0
txAMQP==0.4
urlgrabber==3.9.1
urllib3==1.22
whisper==1.1.0
whitenoise==2.0.6
yum-metadata-parser==1.1.2
zope.interface==3.6.0

**Comment by deniszh** [comment]
Master Graphite (and current stable release too) support Django 1.8 - 1.11, 1.6 is too old.
