### ISSUE TITLE
Strange characters rendered

### ISSUE THREAD

**Issue by luigiberrettini** [graphite-project/graphite-web#2058]
Just installed Graphite-Web, Carbon and Whisper from the master branch:

![image](https://user-images.githubusercontent.com/4513301/31449230-a745ecec-aea6-11e7-9aaa-2102aae4a317.png)

Do you have any advice on what I can do?

**Comment by deniszh** [comment]
Something is wrong with your fonts. Which OS are you using?

**Comment by luigiberrettini** [comment]
The Graphite suite is installed on a CentOS Linux 7 (Core) VM with Kernel Linux 3.10.0-514.16.1.el7.x86_64

I tried viewing graphs from the latest version of Chrome, Firefox and Internet Explorer on Windows 8.1 and the result is the same.
Graphs rendered by already installed older versions are displayed correctly.

**Comment by luigiberrettini** [comment]
Can it depend from old config files or from file/folder permissions?

**Comment by deniszh** [comment]
Nope, it's only matter of font packages. Please try to install dejavu-sans-fonts & dejavu-serif-fonts packages.

**Comment by deniszh** [comment]
PS: 
> Graphs rendered by already installed older versions are displayed correctly.

Did I understand correctly that old version is installed on another server, right?

**Comment by luigiberrettini** [comment]
Perfect thank you: it works now!
