### ISSUE TITLE
Stream metrics/index.json

### ISSUE THREAD

**Issue by numeralnathan** [graphite-project/graphite-web#2069]
With large numbers of metrics in Graphite, I get a 504 Gateway Timeout when requesting metrics/index.json.  This is because the timeout on the web server is set too small for the amount of time Graphite takes to produce metrics/index.json.  Graphite does not send even 1 byte of the HTTP header back.

Instead, Graphite should send an HTTP header back immediately.  Then as Graphite finds metrics, it should immediately send the metrics back.  For example, in the output below, Graphite would send the HTTP header (not shown) and the first [.  Then as each metric is found it would send a string.  When all metrics have been returned, Graphite would then send the last ].

[
    "collectd.host1.load.longterm",
    "collectd.host1.load.midterm",
    "collectd.host1.load.shortterm"
]

This will keep the web server from timing out and reduce the amount of data Graphite buffers as it scans for metrics.

Perhaps, the sorted requirement needs to be dropped so that Graphite can return metrics faster.

**Comment by deniszh** [comment]
I'm not a big Django expert, but I'm suspecting that it will be quite hard to implement behavior which described above. It's much easier to tune web server for a bigger timeout. @cbowman0 @DanCech ?
