### ISSUE TITLE
[feature request] asPercent taking two series lists

### ISSUE THREAD

**Issue by mleinart** [graphite-project/graphite-web#207]
#### Imported from https://bugs.launchpad.net/bugs/1005366
|||
|----|----|
|Reported by|[harisuthan](https://launchpad.net/~harisuthan)|
|Date Created|May 28, 2012|
Originial Desc:
I have a use case where I need to find the percentage between two series lists like:

asPercent(groupByNode(serieslist1, x, "sumSeries"), groupByNode(serieslist2, y, "sumSeries"))

Is there way to achieve this? If not and if you find this useful may I request a feature addition where, when two series lists with "equal length" are passed as parameters to asPercent, it will return a serieslist with the same length where each series is a percentage of the individual input series?

Michael's Response:
I think asPercent and divideSeries could probably support this - rather
than the 2nd series being required to have a length of 1, it could be
required to have either: a length of 1 (current behavior) or a length
equal to the 1st series (your proposed behavior).

Unfortunately I cant spot a way to do this without having to enumerate
every series out.

If you'd like the new feature to be explored, convert this question to a
bug report and mark it as a feature request so that it can be tracked.

**Comment by jemshad** [comment]
looking forward to this feature! :)

**Comment by obfuscurity** [comment]
`asPercent` now supports multiple divisor series in the `total` parameter, or you can pass the results of `sumSeries(seriesList)`. Closing this one.

**Comment by ericy-jana** [comment]
Thanks @obfuscurity, asPercent works great.  But the original issue description and subsequent comments also included divideSeries, but it looks like only asPercent was actually addressed?  I looked but failed to find a separate issue for divideSeries.  Would it make sense to create one or reopen this?

**Comment by obfuscurity** [comment]
@ericy-jana Correct. Can you elaborate on a user case not covered by the `asPercent()` enhancements?

**Comment by ericy-jana** [comment]
@obfuscurity I am trying to graph I/O latency from stats fed to Graphite by a Sensu check reading /proc/diskstats (https://github.com/sensu-plugins/sensu-plugins-disk-checks/blob/master/bin/metrics-disk.rb).  

I am trying to divide the time spent doing I/O over the sample period by the number of I/O operations during the same time period.  This works ok if I am graphing a single host, but fails when using variables/wildcards to attempt to graph multiple hosts.  This same pattern used to fail in a similar way with `asPercent` prior to .10 but now works great (e.g. for graphing CPU utilization %).  

Below is the `targets` array from the Grafana panel json to further illustrate what I am trying to do.  Apologies if I am missing an obvious solution.  I am new to Graphite.

```
  "targets": [
    {
      "target": "nonNegativeDerivative(linux.io.$cluster.$host.*.ioTime)",
      "hide": true
    },
    {
      "target": "groupByNodes(#A, 'sum', 2,3)",
      "textEditor": true,
      "hide": false
    },
    {
      "target": "nonNegativeDerivative(linux.io.$cluster.$host.*.{reads,writes})",
      "hide": true
    },
    {
      "target": "groupByNodes(#C, 'sum', 2,3)",
      "textEditor": true,
      "hide": false
    },
    {
      "target": "divideSeries(#B,#D)",
      "hide": false,
      "textEditor": true
    }
  ],
 ```
