### ISSUE TITLE
Documentation does not describe maxValue parameter for nonNegativeDerivative function

### ISSUE THREAD

**Issue by creidieki** [graphite-project/graphite-web#2073]
The nonNegativeDerivative function has a parameter "maxValue" which is not described in its documentation.

**Comment by ceven** [comment]
+1

**Comment by deniszh** [comment]
With all respect, +1 will not help to fix the issue, but PR will. Documentation for function is located in the same file - https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L2150-L2163

**Comment by ceven** [comment]
Hi Denis, I was just showing interest in the absence of a 'vote for this issue' button. I would gladly add documentation, however I am also trying to understand what `maxValue` does, hence my need for documentation! 
AFAIS [this doc](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L2150-L2163) is equivalent to https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.nonNegativeDerivative and does not contain information for `maxValue`
Other than that, I think the existing documentation is pretty good and I'm very thankful for it!

**Comment by deniszh** [comment]
Hi Caroline,
Thanks a lot for using Graphite, we're here to help you. :)
`maxValue` was there from start, but for some reason, it was never documented. I'm not aware of it either, need to check code to understand it completely.
