### ISSUE TITLE
whisper reader strange results for counters after merge_with_carbonlink

### ISSUE THREAD

**Issue by olevchyk** [graphite-project/graphite-web#2080]
When we have counter metrics in cache,  and client  reporting interval is less than rendering step (we get when query whisper),  we see abnormal spikes of counters

The only requirement to reproduce this problem is to have some counter metric in CarbonCache, before the points get written to disk/whisper file. 
In our case this discrepancy happens for the small time range, which is relatively  bigger then write delay we have between carbon-cache and whisper db. 

Our default retention starts from: 
retentions = 30s:3d
and that creates this wsp:
``` 
Archive 0
retention: 259200
secondsPerPoint: 30
points: 8640
size: 103680
offset: 64
```
which means whisper writes only one datapoint each 30sec, 
However, the app, that is responsible to report metrics, has 10 seconds reporting interval,  and we don't run any aggregation before carbon-cache, 
CarbonCache is getting - 10 secondsPerPoint   
but whisper is writing - 30 secondsPerPoint 
here is a simple illustration of auto increment counter over time, with `|` split for whisper data and CarbonCache
```
|----------1----------2----------3----------4----------5|CACHE----6----7----8----9>
```
when we fetch the data during rendering, we query CarbonCache using CarbonLink() ,  whisper db and then merge both : 
[readers/whisper.py#L72-L73](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/readers/whisper.py#L72-L73)
```
        values = merge_with_carbonlink(
            self.real_metric_path, start, step, values, aggregation_method)
```
from there the execution goes to 
[readers/utils.py#L124](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/readers/utils.py#L124
) where we apply consolidation function for cached_datapoints depending on aggregationMethod, 
`sum` is default aggregationMethod for counters 
```
    if func:
        consolidated_dict = {}
        for (timestamp, value) in cached_datapoints:
            interval = timestamp - (timestamp % step)
            if interval in consolidated_dict:
                consolidated_dict[interval].append(value)
            else:
                consolidated_dict[interval] = [value]
        for interval in consolidated_dict:
            value = consolidate(func, consolidated_dict[interval])
            consolidated.append((interval, value))
```
where `func` in our case is: 
[readers/utils.py#L133-L134](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/readers/utils.py#L133-L134)
```
        if func == 'sum':
            return sum(usable)
````
And here is what happens to the data: 
before consolidation 
```
|----------1----------2----------3----------4----------5|CACHE---(6-+--7-+--8)---9>
```
after consolidation 
```
|----------1----------2----------3----------4----------5|CACHE--------21----------9>
```
doesn't seems to be right, and this is exactly the behavior we see on the graphs. 
When we have counter metrics in cache,  and client side reporting interval is less than rendering step ,  we see abnormal spikes of counters, that can be correlated by the formula
highest point  ~= counter * (default retention / reporting interval ).

I have also verified that: 
1. the app does not send these spikes, ( tcpdump )
2. wsp file has the correct  datapoints  ( whisper-fetch.py )
3. cache has the correct datapoints 

But why does carbon consolidate these points correctly when writes update to wsp db, while graphite-web doesn't. 
After some investigation(not 100% sure about this ) I found that cache > whisper does not consolidate extra points on write, it simply disregards them: 
first alligns them: [whisper.py#L785-L786](https://github.com/graphite-project/whisper/blob/master/whisper.py#L785-L786)
```
  alignedPoints = [(timestamp - (timestamp % step), value)
                   for (timestamp, value) in points]
```
and then it takes one out of each interval: [whisper.py#L792-L795](https://github.com/graphite-project/whisper/blob/master/whisper.py#L792-L795)
```
  for i in xrange(0, lenAlignedPoints):
    # Take last point in run of points with duplicate intervals
    if i + 1 < lenAlignedPoints and alignedPoints[i][0] == alignedPoints[i + 1][0]:
      continue
    (interval, value) = alignedPoints[i]
```
 
By Looking at the current test, can you imagine how the graph would look like for the data we get from cache ? 
[tests/test_readers_util.py#L54-L85](https://github.com/graphite-project/graphite-web/blob/master/webapp/tests/test_readers_util.py#L54-L85
) we fill the cache by appending cache_results.append((i, 1)), every second, however whisper will write  only single `1` every secondsPerPoint=60,
but we expect consolidated datapoint for every step to be expected_values.append(60)

Please correct if this is wrong and I didn't understand counters/consolidation correctly.

**Comment by DanCech** [comment]
The correct consolidation for counters is `last` not `sum`.  Whisper doesn't perform any aggregation when you send multiple points within the `secondsPerPoint` window, it simply uses the most recent one.

**Comment by olevchyk** [comment]
https://github.com/graphite-project/carbon/blob/master/lib/carbon/tests/data/conf-directory/storage-aggregation.conf#L24-L27
sum has more sense for counters.

**Comment by olevchyk** [comment]
raised the PR https://github.com/graphite-project/graphite-web/pull/2081
Please close if doesn't make sense.

**Comment by DanCech** [comment]
Why do you say that `sum` makes more sense for counters?  The correct aggregation for counters is `last` and should then be used with `perSecond` to give rates for graphing etc.

**Comment by olevchyk** [comment]
In my case this idea comes from default conf example storage-aggregation.conf
https://github.com/graphite-project/carbon/blob/master/conf/storage-aggregation.conf.example#L24-L27

**Comment by DanCech** [comment]
Yeah those are per-period counts not ever-increasing counters.

**Comment by olevchyk** [comment]
in our case metric has "count" ending, which made  it aggregationMethod=sum on creation. :man_facepalming: 
But can you please still check the PR, as it can improve performance for the data we get from cache , in case when reporting interval is smaller than default_retention.

**Comment by DanCech** [comment]
yep, will check out the PR.  We should also maybe think about making that default config clearer, with a `.counter` section and some comments about the difference.

**Comment by olevchyk** [comment]
In our company  we mostly use 2 client libraries: 
go-metrics-graphite/go-metrics for golang and dropwizard for java -  both generate *.count.wsp extension for increasing counters, 
which can be also the part of Meters, and Histograms reporting. 
And with using default config  we now have all .count.wsp files with increasing counters with aggregationMethod=sum. 
For now I'm going to change our storage-aggregation.conf to be like this: 
```
[last]
pattern = \.count$
xFilesFactor = 0
aggregationMethod = last

[sum]
pattern = \.counter$
xFilesFactor = 0
aggregationMethod = sum
```
to fix at least new metrics. 
There seems to be a confusion between the clients: 
http://metrics.dropwizard.io/3.1.0/getting-started/#counters
http://statsd.readthedocs.io/en/v0.5.0/types.html
https://collectd.org/wiki/index.php/Data_source
but it's looks like most of them send both rate and counter as separate metrics.

**Comment by olevchyk** [comment]
PR merged, Thank you @DanCech, 
Closing this for now, I will re-open if happens again after update.
