### ISSUE TITLE
Finders should have access to the entire query

### ISSUE THREAD

**Issue by nickbabcock** [graphite-project/graphite-web#2090]
Currently, `query.pattern` (from `find_nodes`) contains only data being sought. Given a query of `summarize(a.b.c, '1hour', 'sum')` the finder only sees `a.b.c`. This is fine for most use cases, except for the one I encountered recently.

Let's say I have a custom finder that returns the number of unique ants in my ant farm:

- Minute 1: There were 1,000 unique ants
- Minute 2: There were 1,000 unique ants
...
- Minute 60: There were 1,000 unique ants

Also this finder can support a different time step (representing 5 ants were replaced in a single minute):

- Hour 1: There were 1,005 unique ants

If I were to apply the `summarize` function on the minute data, the average would be 1,000 and sum would be 60,000. Neither answers the question "how many unique ants were seen in this hour". If only I could see the `summarize` interval I could pass this to the custom finder for accurate calculations. The quickest way might be to just expose the full query to the finders and have them figure out what's important.

Alternatively, I could have each ant be a series and use a combination of `exclude` and `countSeries`, but I'm going to have a lot of ants, so this is impractical.

I realize that exposing the full query and trying to parse out the `summarize` interval would be easy for any user to poke holes in, but in this environment users don't control the queries. I still feel like this would be a good first step to giving custom finders additional context.

**Comment by DanCech** [comment]
This is an interesting idea, I'm actually working on a refactor of the way that queries are dispatched through the finders (PR coming soon) which should make it possible to expose the complete queries to the finders.

**Comment by deniszh** [comment]
I think it's done now, right, @DanCech ?

**Comment by DanCech** [comment]
It's not available right now, but we could add it to the `requestContext` in `evaluateTarget`

**Comment by deniszh** [comment]
Ah, OK. I just thought its already done in the current implementation.
