### ISSUE TITLE
Documentation link always points to latest version

### ISSUE THREAD

**Issue by wridgers** [graphite-project/graphite-web#2101]
This is confusing. I've had users click "Documentation" and complain to me that functions don't work, only to find out they're newly committed functions that haven't made into a release yet.

It should point to the version that is running.

**Comment by deniszh** [comment]
"Documentation" link goes to http://graphite.readthedocs.io/, which automatically redirects to http://graphite.readthedocs.io/en/latest/ - that's how ReadTheDocs works.
We have current version variable WEBAPP_VERSION in https://github.com/graphite-project/graphite-web/blob/8ba0cb0c96beefbeffe71d5fe792505f837fad2f/webapp/graphite/settings.py#L29
We just need to properly fix DOCUMENTATION_URL in https://github.com/graphite-project/graphite-web/blob/8ba0cb0c96beefbeffe71d5fe792505f837fad2f/webapp/graphite/settings.py#L116 to support "latest" and releases.
