### ISSUE TITLE
Graphite is very slow rendering requests

### ISSUE THREAD

**Issue by davidpsv17** [graphite-project/graphite-web#2105]
Hi all,

The requests to graphite goes very slow.

Graphite-carbon version: 1.0

Configured memcached: 
MEMCACHE_HOSTS = ['127.0.0.1:11211']
DEFAULT_CACHE_DURATION = 600

Example:

time curl -v '127.0.0.1:8888/render/?from=-2hours&
target=sumSeries(newapi.rc.*.request.*.sqlite.*.count)&format=json'

real    2m13.191s
user    0m0.008s
sys     0m0.004s

Could anyone help me?

Thanks!

**Comment by DanCech** [comment]
How many series does that match? Can you paste the log output?

**Comment by davidpsv17** [comment]
Hi @DanCech! Thanks for your reply

You mean the reply of the request?

[{"target": "sumSeries(newapi.rc.*.request.*.sqlite.*.count)", "datapoints": [[1.0, X], [null, X], [null, X], [3.0, X], [null, X], [null, X], [3.0, X], [1.0, X], [1.0, X], [2.0, X], [2.0, X], [1.0, X], [null, X], [null, X], [null, X], [null, X], [1.0, X], [null, X], [1.0, X], [null, X], [3.0, X], [1.0, X], [2.0, X], [3.0, X], [2.0, X], [1.0, X], [1.0, X], [2.0, X], [1.0, X], [2.0, X], [2.0, X], [1.0, X], [2.0, X], [null, X], [null, X], [null, X], [3.0, X], [2.0, X], [1.0, X], [2.0, X], [3.0, X], [2.0, X], [1.0, X], [3.0, X], [2.0, X], [4.0, X], [2.0, X], [1.0, X], [1.0, X], [2.0, X], [1.0, X], [2.0, X], [1.0, X], [5.0, X], [3.0, X], [3.0, X], [3.0, X], [2.0, X], [1.0, X], [3.0, X], [2.0, X], [3.0, X], [1.0, X], [1.0, X], [3.0, X], [null, X], [4.0, X], [1.0, X], [1.0, X], [1.0, X], [2.0, X], [6.0, X], [2.0, X], [4.0, X], [6.0, X], [4.0, X], [4.0, X], [2.0, X], [2.0, X], [3.0, X], [11.0, X], [1.0, X], [3.0, X], [1.0, X], [1.0, X], [2.0, X], [1.0, X], [1.0, X], [1.0, X], [1.0, X], [7.0, X], [2.0, X], [5.0, X], [1.0, X], [7.0, X], [1.0, X], [2.0, X], [4.0, X], [1.0, X], [3.0, X], [5.0, X], [2.0, X], [2.0, X* Connection #0 to host 127.0.0.1 left intact
], [2.0, X], [2.0, X], [1.0, X], [3.0, X], [1.0, X], [2.0, X], [3.0, X], [5.0, X], [2.0, X], [3.0, X], [4.0, X], [9.0, X], [2.0, X], [5.0, X], [1.0, X], [3.0, X], [1.0, X]]}]

I tried another request like:
curl -v '127.0.0.1:8888/render/?from=-2hours&target=averageSeries(newapi.rc.*.request.*.test.*.time)&format=json'

And this was the reply:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>504 Gateway Timeout</title>
</head><body>
<h1>Gateway Timeout</h1>
<p>The gateway did not receive a timely response
from the upstream server or application.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at 127.0.0.1 Port 8888</address>
</body></html>


Thanks!

**Comment by DanCech** [comment]
I mean how many series does the selector `newapi.rc.*.request.*.sqlite.*.count` match?  `sumSeries` is always going to boil down the series you pass into a single result, but that could take a while if there are a huge number of underlying series for it to process.

For logs, you should enable `LOG_RENDERING_PERFORMANCE = True` and `LOG_CACHE_PERFORMANCE = True` in your `local_settings.py`, then look in `/opt/graphite/storage/log/webapp` for entries in `rendering.log`, `cache.log` and `info.log`.

**Comment by davidpsv17** [comment]
Sorry @DanCech 

It has 200 series and in the log you can see something like:

2017-11-08,09:57:43.369 :: Retrieval of highestAverage(groupByNodes(newapi.newapi.test.*.*.*.query.time, 'avg', 4, 5), 10) took 412.889228
2017-11-08,09:57:43.373 :: JSON rendering time 0.001519
2017-11-08,09:57:43.373 :: Total request processing time 412.894376

This is happening with all the queries..

Thanks!

**Comment by deniszh** [comment]
Probably your disk is overloaded if fetching 200 series takes 412 seconds...

**Comment by wangzaiqqhop** [comment]
hello all:
     when i use sumSeries(API.*.QOSController.*.hx_category_Q19_count) to request the data from graphite，it goes very slow；but if i change it to sumSeries(api.*QOSController.A.category_Q19_count,api.*.QOSController.B.category_Q19_count,api.*.QOSController.C.category_Q19_count),the request goes very fast . 
the amount of wsp file under the QOSController folder is about  30 thousand，but i only want to use asterisk to match the A、B、C folder ，i don‘t understand why use the asterisk in the query could be so slowly
      could you help me,thank you!

**Comment by DanCech** [comment]
See #2183 #2185
