### ISSUE TITLE
composer display messy code

### ISSUE THREAD

**Issue by innerx** [graphite-project/graphite-web#2109]
No matter I install from source or by pip on centOS 7, I get the same result.
Can anyone help me?
<img width="598" alt="76dd5ac7-47f2-4578-be85-76b63e16b0ea" src="https://user-images.githubusercontent.com/17538310/32606098-f18cc286-c58e-11e7-99de-bb8ffe285922.png">

**Comment by deniszh** [comment]
Hi @innerx,
Problem is not in python code but in the environment.
What's your OS and `cairo` package version?

**Comment by piotr1212** [comment]
Might be some missing fonts. You could try to `yum install dejavu-sans-fonts dejavu-serif-fonts` to see if that helps.

**Comment by innerx** [comment]
@piotr1212 
great, it works, thanks very much!

**Comment by zhangmeng0426** [comment]
my OS is  CentOS Linux release 7.2.1511 (Core) .    my cairo is cairo-1.14.8-2.el7.x86_6 and my graphite install by pip . but  I get the same result.  what can I do something?
