### ISSUE TITLE
Timestamps count differ from datapoints count.

### ISSUE THREAD

**Issue by xtus** [graphite-project/graphite-web#2113]
Hi,

Using version 1.1.0-dev I encounter an issue in a call to the `aggregate` function, and a successive call to `summarize`(in this case is then `_summarizeValues`).

The test case involve two TimeSeries, for instance:
(a) 'start': 1510324560, 'end': 1510328280, 'valuesPerPoint': 1, 'step': 120
(b) 'start': 1510324620, 'end': 1510328220, 'valuesPerPoint': 1, 'step': 30

In `aggregate`, before the call to `normalize`, the number of datapoints(i.e. `len(list(series)))` ) for the series is:
(a) 31
(b) 120

After the call to `normalize`, the datapoint count for the series is now:
(a) 31 (valuesPerPoint=1)
(b) 30 (valuesPerPoint=4)
and the (start, end, step) output from `normalize` is: (1510324560, 1510328280, 120)

At this point, the` len(values)` generated by the `aggregate` function is 30.

Considering the way that is used in `_summarizeValues` to calculate `timestamps` and `datapoints`, i.e.:

```
  timestamps = range( int(series.start), int(series.end), int(series.step) )
  datapoints = list(series)
```

The TimeSeries output of `aggregate` has:
```
len(timestamps) = 31
len(datapoints) = 30
```

And eventually, when trying to access  in `_summarizeValues` the 31st element in `datapoints` is leading to:
```
  File "/opt/graphite/webapp/graphite/render/functions.py", line 3998, in _summarizeValues
    if timestamps[i] >= timestamp_ and datapoints[i] is not None:
IndexError: list index out of range
```

The exception has the effect to have the WSGI thread to spin and allocate increasing amount of memory, until is killed.

I run the same test case on version 0.9.12, and what I get is that the datapoints count after the `normalize` is for both series as 31, so no exception triggered in this case.

Can you pinpoint the culprit? My guess is `normalize`.

Thanks

**Comment by DanCech** [comment]
That is interesting, I'll have to see if anything has changed in `normalize` between the versions.  Not sure what would be causing the memory allocation, possibly the backtrace.

**Comment by xtus** [comment]
Just to clarify, my guess it that `normalize` should output a (start, end, step) range that guarantee same amount of timestamps and datapoints between the series involved.

And I guess instead that in version 0.9.12 there was a bug with the `__consolidatingGenerator` in `TimeSeries`, that was returning an extra `None`.

I think, probably not correctly, that `normalize` should actually produce in output series that are aligned in terms of timestamp; if can somebody provide some documentation or a comment about the expected behaviour for `normalize` would be great.

**Comment by DanCech** [comment]
Good point, it does seem like that trailing None may have been there to avoid this kind of issue by providing a bogus value if you iterated past the end in a scenario like this.  I'm digging deeper to try and figure out a reasonable solution.

**Comment by DanCech** [comment]
@xtus can you try out that PR and verify that it fixes the issue?

**Comment by xtus** [comment]
@DanCech yep, my quick fix was indeed the `numPoints = min(len(timestamps), len(datapoints))` in `_summarizeValues`.

PR #2114 fix the issue.

Thanks
