### ISSUE TITLE
perSecond and nonNegativeDerivative maxValue handling

### ISSUE THREAD

**Issue by DanCech** [graphite-project/graphite-web#2116]
I did some more digging into the handling of the `maxValue` parameter to `perSecond` and `nonNegativeDerivative` when I realized that with the update in #2115 they are now inconsistent.

The origin of the `+ 1` is https://bugs.launchpad.net/graphite/+bug/660861 and the reason for it is based on how SNMP counter maximum values work.  The idea is that if the maximum value of the counter is the maximum 32bit integer (4294967295) then the counter will reset to 0 when the next packet is received meaning that we need to add 1 to get the correct total.

That is fine, but what it means is that the way we're testing `perSecond` is incorrect but previously the error was concealed by the integer division.  It expects a counter that goes from 240 to 120 with a `step` of 60 and a `maxValue` of 480 to result in a rate of 6, based on `(120 - 240 + 480) / 60`, when is actual fact the result should be `(120 - 240 + 480 + 1) / 60 = 6.016667`.

The other thing I noticed is that when `maxValue` is specified it's only used when the counter decreases, it doesn't do anything special with values that are above the `maxValue` unless the values are decreasing (this is also enshrined in the tests).

My thought is that `perSecond(some.series)` should be functionally equivalent to `scaleToSeconds(nonNegativeDerivative(some.series), 1)`.  The simplest way to achieve that will be to refactor them to use a shared helper.

If `maxValue` is specified it should be treated consistently in both functions and any counter values above the `maxValue` should be discarded altogether.

If anyone has any input I'd love to hear it, right now I'm thinking that I'll go ahead with the refactoring outlined above and update the tests so that they use the "correct" values to test against, as well as verifying that the functions agree with each other.

**Comment by cbowman0** [comment]
I can't argue with your logic or plan.  That's what perSecond is supposed to be.

**Comment by deniszh** [comment]
Same here. Looks like a great plan! 👍

**Comment by DanCech** [comment]
Another wrinkle that has come up as I dig into this; in `perSecond` it tries to "bridge" None values by keeping track of the last-seen value and accumulating step values to try and produce a value when it sees the next non-None value.  There are a few issues with this, and we already had to fix one bug in #2029, but I'd argue that it's still not the right thing to do, since you end up with a graph that shows a value for an interval where we really don't know what happened (since it's based on taking the last "known" value which may have been some time ago and we have no idea if the increase in the counter value happened evenly across the intervening intervals (as the code currently assumes) or if it was not evenly distributed over time.

In addition, though we assume that the rate was constant over that time period we only produce a value for the last interval so the rate produces for intervals during the "unknown" period doesn't reflect that assumption.  Finally, this approach is inconsistent with `nonNegativeDerivative` which does no such "special" handling.

For all those reasons I'm proposing removing this logic from `perSecond`, so that to produce a rate for a given interval it requires 2 consecutive non-None values.  This will make `perSecond(x)` equivalent to `scaleToSeconds(nonNegativeDerivative(x), 1)`.
