### ISSUE TITLE
Tagged whisper & ceres filenames

### ISSUE THREAD

**Issue by DanCech** [graphite-project/graphite-web#2122]
Currently the file system layout for tagged series in whisper & ceres uses sha256 hashes to avoid issues with overly-large directories, and replaces any dots in the series name with underscores to avoid confusion if a tag value contains a dot.

@civil brought up a good point that this mechanism could use a faster hashing algorithm, since it is just being used to shard the files into separate directories.

We also currently use an sha256 hash to deduplicate entries in the tagdb, which could potentially also use a faster hash function.

Finally, the problem with just replacing dots with underscores is that there is no efficient way to reverse the encoding (other than brute force testing each combination against the aforementioned hash). We should consider changing that to use a replacement that can be reversed more easily, one option that comes to mind is `_DOT_` but I am very much open to suggestions.

All 3 of these are breaking changes so we should make decisions and implement any changes before we release 1.1.0

**Comment by deniszh** [comment]
I'm not really sure that you'll get such huge performance gain from changing hash functions.
Also please note that hash function should be available "out of the box" from major python distribution, so, IMO no need to bring some 3rd party module for that, or I doubt that python-only `xxhash` or `murmur3` will be faster than `hashlib.sha256`...

For dot replacement - `_DOT_` looks good enough for me. :)

**Comment by deniszh** [comment]
Discussed that offline with @Civil. IMO ideal solution - configurable hash - sha256 for out-of-the-box solution, ad something very fast  like `cityHash` or `xxHash` for speed.

**Comment by iksaif** [comment]
Do you think wecan close this now ?

**Comment by DanCech** [comment]
Yes, I think so.  We implemented the dot handling change, and can make the hash function configurable later if desired.
