### ISSUE TITLE
Feature request: multiple substitutions with one aliasSub()

### ISSUE THREAD

**Issue by sparr** [graphite-project/graphite-web#2143]
I want to perform half a dozen substitutions on a metric series name. I would much rather do  `aliasSub(series,old1,new1,old2,new2,...` than `aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(series,old1,new1),old2,new2)...`

**Comment by DanCech** [comment]
With the pipe syntax in 1.1 this can be written as `aliasSub(series,old1,new1)|aliasSub(old2,new2)...`
