### ISSUE TITLE
Javascript linting

### ISSUE THREAD

**Issue by cbowman0** [graphite-project/graphite-web#2144]
Few questions:
1. Who's the admin on the Codacy integration?  We should have it ignore the 3rd party javascript libraries, example code and the test scripts.

2. I'd like to set up an ESLint config file for the javascript files in [webapp/content/js](https://github.com/graphite-project/graphite-web/tree/master/webapp/content/js).  Anyone have a problem with that?

3. Anyone have a preference on ESLint settings?  If not, I'll attempt to match the most prevalent choices in the 5 javascript files that exist.

4. I think we can manipulate travis-ci to run the checks via another entry in the matrix options.  Anyone else have experience with multiple languages in the .travis.yml

**Comment by deniszh** [comment]
1. We all three - @iksaif @DanCech and me. I can add you too - give me your (github account) email please. Or give me list of files which we should exclude.
2. Very 👍 . But how you going to run it?
3. Fine for me.
4. My Travis experience is quite limited, but I think it's currently not supported - https://github.com/travis-ci/travis-ci/issues/4090

**Comment by DanCech** [comment]
Once we create an eslint config file codacy will use it

**Comment by cbowman0** [comment]
My email is my github username at gmail.com.

https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages suggests a way to make it work.  At least we can attempt it, but an ESLint config file can be used by Codacy, so it's not useless.

**Comment by DanCech** [comment]
The easiest way is likely just to make another matrix entry that overrides all the defaults, installs node & eslint and runs it

**Comment by deniszh** [comment]
>My email is my github username at gmail.com.

Please check now - https://www.codacy.com/
