### ISSUE TITLE
Graphite Webapp - no module named functions

### ISSUE THREAD

**Issue by chrim5** [graphite-project/graphite-web#2152]
Hi everybody,

I got the following error when trying to install graphite-web via tarball:

Traceback (most recent call last):
  File "/usr/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/urls.py", line 22, in <module>
    url('^render/?', include('graphite.render.urls')),
  File "/usr/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/render/urls.py", line 16, in <module>
    from . import views
  File "/opt/graphite/webapp/graphite/render/views.py", line 30, in <module>
    from graphite.render.evaluator import evaluateTarget
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 5, in <module>
    from graphite.functions import SeriesFunction
ImportError: No module named functions
The command '/bin/sh -c PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb' returned a non-zero code: 1

Any idea?

**Comment by deniszh** [comment]
@chrim5: could you please elaborate which version and how are you trying to install? Thanks!

**Comment by deniszh** [comment]
@DanCech : probably it's related to moving parts of `functions.py` to `functions/__init__.py` ?
Then it should affect other places too:
```[dzhdanov:~/git/graphite-web] master+* ± grep -r 'from graphite.functions import' *
webapp/graphite/functions/views.py:from graphite.functions import SeriesFunctions, SeriesFunction, PieFunctions, PieFunction, functionInfo
webapp/graphite/render/evaluator.py:from graphite.functions import SeriesFunction
webapp/graphite/render/functions.py:from graphite.functions import SeriesFunction, ParamTypes, Param
webapp/graphite/render/views.py:from graphite.functions import loadFunctions, PieFunction
webapp/tests/test_functions.py:from graphite.functions import _SeriesFunctions, loadFunctions```
Or it's something Django related?

**Comment by DanCech** [comment]
Ah, we may need to add the new files to a manifest for packaging, let me check that

**Comment by DanCech** [comment]
c974645d146d1fd07e0c5e32af267328f70f20dd

**Comment by deniszh** [comment]
Ah, completely forgot that. Thanks, @DanCech !
@chrim5 - could you please test now?

**Comment by DanCech** [comment]
I haven't looked into the packaging side of things before, it seems like we could switch to using `find_packages()` to avoid running into this problem in the future.  I'll dig into it a little.

**Comment by DanCech** [comment]
Hmm, `distutils` doesn't provide `find_packages()` so we'd either need to vendor it in or start requiring `setuptools`.  I've forgotten too much about python packaging to know what the best way forward is off-hand, going to have to dig deeper.

**Comment by iksaif** [comment]
`setuptools` is fine imho

**Comment by chrim5** [comment]
Hi everybody,

Build seems to work again:

Step 28 : RUN PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb
 ---> Running in f95acd8c278d
System check identified some issues:

WARNINGS:
?: (urls.W002) Your URL pattern '^/(.+)$' [name='functionDetails'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/(.+)$' [name='tagDetails'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/(?P<event_id>\d+)/?$' [name='events_detail'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/(?P<name>[^/]+)$' [name='dashboard'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/(?P<name>[^/]+)/(?P<val>[^/]+)$' [name='dashboard_template'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/?$' [name='browser'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/?$' [name='composer'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/?$' [name='dashboard'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/?$' [name='events'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/?$' [name='functionList'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/?$' [name='metrics'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/?$' [name='render'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/?$' [name='tagList'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/?$' [name='version_index'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/?$' [name='whitelist_show'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/add$' [name='whitelist_add'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/autoComplete/tags$' [name='tagAutoCompleteTags'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/autoComplete/values$' [name='tagAutoCompleteValues'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/create-temporary/?$' [name='dashboard_create_temporary'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/delSeries$' [name='delSeries'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/delete/(?P<name>[^/]+)$' [name='dashboard_delete'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/delete_template/(?P<name>[^/]+)$' [name='dashboard_delete_template'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/edit/?$' [name='account_edit'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/email$' [name='dashboard_email'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/expand/?$' [name='metrics_expand'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/find/?$' [name='dashboard_find'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/find/?$' [name='metrics_find'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/findSeries$' [name='findSeries'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/find_template/?$' [name='dashboard_find_template'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/get-metadata/?$' [name='metrics_get_metadata'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/get_data?$' [name='events_get_data'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/header/?$' [name='browser_header'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/help/?$' [name='dashboard_help'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/index\.json$' [name='metrics_index'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/load/(?P<name>[^/]+)$' [name='dashboard_load'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/load/(?P<name>[^/]+)/(?P<val>[^/]+)$' [name='dashboard_load_template'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/load_template/(?P<name>[^/]+)/(?P<val>[^/]+)$' [name='dashboard_load_template'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/local/?$' [name='render_local'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/login/?$' [name='account_login'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/login/?$' [name='dashboard_login'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/logout/?$' [name='account_logout'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/logout/?$' [name='dashboard_logout'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/mygraph' [name='composer_mygraph'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/mygraph/?$' [name='browser_my_graph'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/remove$' [name='whitelist_remove'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/save/(?P<name>[^/]+)$' [name='dashboard_save'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/save_template/(?P<name>[^/]+)/(?P<key>[^/]+)$' [name='dashboard_save_template'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/search/?$' [name='browser_search'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/send_email' [name='composer_send_email'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/set-metadata/?$' [name='metrics_set_metadata'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/tagMultiSeries$' [name='tagMultiSeries'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/tagSeries$' [name='tagSeries'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/update/?$' [name='account_update'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/usergraph/?$' [name='browser_usergraph'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
?: (urls.W002) Your URL pattern '^/~(?P<username>[^/]+)/(?P<graphName>[^/]+)/?$' [name='render_my_graph'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
[0mOperations to perform:
  Synchronize unmigrated apps: render, staticfiles, whitelist, metrics, composer, browser
  Apply all migrations: account, sessions, admin, tags, auth, url_shortener, contenttypes, dashboard, events, tagging
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying dashboard.0001_initial... OK
  Applying events.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying tagging.0001_initial... OK
  Applying tagging.0002_on_delete... OK
  Applying tags.0001_initial... OK
  Applying url_shortener.0001_initial... OK

**Comment by DanCech** [comment]
FWIW those django "URL pattern" warnings will go away if you update to 1.11 (which I recommend).
