### ISSUE TITLE
0.9.16 brace expansion bug

### ISSUE THREAD

**Issue by mlausch** [graphite-project/graphite-web#2154]
Metrics with braces like at the following will not "expand" anymore.
foo.{bar}.baz
queries like  foo.{bar1,bar2}.baz  works as intented.

Until Version 0.9.15 The braces around a value without commas are removed and all was fine. But now only if in the braces are two or more comma spparated values this will work correctly.

Since grafana sends queries with single values in braces this functionality is neccessary to work. 

I figured out, that the faulty function is in graphite/storage.py  (function "expand_braces")
I had a look in the 1.0.x branch. There is the functionality moved to graphite/finders/__init__.py In this branch the described bug is fixed.

Is it possible to backport this function to 0.9.x?  
I cannot use Version 1.0.x in my environment caused by the django dependencies.

**Comment by DanCech** [comment]
See #2156

**Comment by deniszh** [comment]
Hello @mlausch,
Please note that we're not going to make any 0.9.x releases. But you can use 0.9.x branch, of course, after merging fix in #2156

**Comment by deniszh** [comment]
@mlausch: Fix is merged, please test.

**Comment by mlausch** [comment]
@deniszh: The Fix works for me.
