### ISSUE TITLE
SNMP Overflow - Huge Peak Graph

### ISSUE THREAD

**Issue by vilalobus** [graphite-project/graphite-web#2155]
Actually, the problem that I'm actually seeing some Huge Peak in the Graphs ( Like a Overflow). My Bandwith is actually 150 Mbps and I have peaks with lot of Gbps. It is random, keep happen in various graphics. Is there a way to discard these High values that exceeds the 150 Mbps ?

**Comment by DanCech** [comment]
You can use the `maxValue` parameter for [nonNegativeDerivative](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.nonNegativeDerivative) to exclude nonsensical values.

**Comment by vilalobus** [comment]
It does not work using this nonNegativeDerivative, shows nothing on the Graph, even if I do not use the MaxValue, it keeps Blank. Is there any other way ?

**Comment by vilalobus** [comment]
![graphite-nonderivative](https://user-images.githubusercontent.com/34543753/34004220-7475ed0c-e0de-11e7-996e-54b9f2fbfb00.JPG)

**Comment by vilalobus** [comment]
Without this nonNegativeDerivative:
![graphite-without-nonderivative](https://user-images.githubusercontent.com/34543753/34004292-a3ca0ab6-e0de-11e7-92e3-aff45c9d2f54.JPG)

**Comment by DanCech** [comment]
Ah, I thought you were graphite raw counters.  Since you're using data that is already a rate you'll want to use [removeAboveValue](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.removeAboveValue) to exclude the spikes.

**Comment by vilalobus** [comment]
Thanks a Lot Dan. Worked !
