### ISSUE TITLE
Unexpected 'u' when formatting event tags as an array

### ISSUE THREAD

**Issue by ahoffpauir** [graphite-project/graphite-web#2184]
When trying to add tags onto an event by way of inserting an array
```
-X POST "http://localhost/events/" -d '{"what":"Event 1", "tags":["hello","world"], "when":1515264187, "data":"deploy of master branch happened"}'
```
The tags appear with a 'u' in from of them in graphite 
```
[ 
  {
      "what" : "Event 1",
      "id" : 36,
      "data" : "deploy of master branch happened",
      "tags" : "[u'hello', u'world']",
      "when" : 1515264187
   }
]
```
Then trying to query the event on the tags returns nothing back.

Is there something I am missing or doing wrong or is this a bug?

I've been stuck on this issue for a few days and realize that I can still use the older method of just a string with white spaces as the delimiter so that will be my work around. I just haven't seen this issue or question out there yet.

**Comment by deniszh** [comment]
That 'u' means representation of Unicode string. Not sure why it's happening only in tags...

**Comment by deniszh** [comment]
@ahoffpauir - try to set up tags as space separated list - does it works that way?

**Comment by ahoffpauir** [comment]
Yeah, the space separated list works! I can query them fine that way too. It is just when putting them in the array that this happens, and it doesn't allow me to query them either.
