### ISSUE TITLE
"All metrics failed for [metric]" exception since upgrading to graphite-web 1.1.1

### ISSUE THREAD

**Issue by wridgers** [graphite-project/graphite-web#2192]
Upgraded yesterday and immediately started seeing this:

```
Traceback (most recent call last):
  File "/opt/graphite/webapp/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 117, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 15, in evaluateTarget
    prefetchData(requestContext, pathExpressions)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 255, in prefetchData
    for result in STORE.fetch(pathExpressions, startTime, endTime, now, requestContext):
  File "/opt/graphite/webapp/graphite/storage.py", line 138, in fetch
    raise Exception('All fetches failed for %s' % (str(patterns)))
Exception: All fetches failed for [u'some.metric.*.*.*.here']
```

**Comment by wridgers** [comment]
Increasing the `REMOTE_FETCH_TIMEOUT` stopped most of these, but afaiu graphite-web isn't doing any remote fetching here...

**Comment by deniszh** [comment]
You not using clustering and `CLUSTER_SERVERS = []` in config?  
Hmm... Does setting USE_WORKER_POOL=False fixing that?

**Comment by wridgers** [comment]
`CLUSTER_SERVER` and `USE_WORKER_POOL` are commented out, so I'd guess they're whatever the default is?

From local_settings.py:

```
#CLUSTER_SERVERS = ["10.0.2.2:80", "10.0.2.3:80"]
#USE_WORKER_POOL = True
```

Should we try setting `CLUSTER_SERVER = []` and `USE_WORKER_POOL=False`?

**Comment by wridgers** [comment]
We have four caches, four aggregators, and two relays all running on the same machine as graphite-web (nginx + gunicorn). Relays are behind haproxy.

**Comment by deniszh** [comment]
`CLUSTER_SERVERS = []` is on settings.py, so, should be fine. Try to set USE_WORKER_POOL=False 
If it helps then we can fix it like
`if settings.USE_WORKER_POOL & len(CLUSTER_SERVERS): ` in https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/storage.py#L86

**Comment by wridgers** [comment]
I will tentatively say this seems to have worked. I'll confirm later today and make a PR fixing the issue.

Thanks @deniszh

**Comment by DanCech** [comment]
We use threads for multiple reasons, if your whisper files can't be read within the timeout period then you'll want to either increase the timeout or tell graphite-web not to use the worker pool via the existing setting.  Switching the worker pool off altogether when not using remote servers isn't a good idea.

**Comment by deniszh** [comment]
@DanCech 
So, `REMOTE_FETCH_TIMEOUT` applying to local fetches too now?  That's new for me. :)
I think we need to introduce a new variable for local fetches then, `REMOTE_FETCH_TIMEOUT` is confusing. And probably local fetch timeout should be much less then remote fetch timeout.

**Comment by DanCech** [comment]
It's a single timeout, we just didn't change the name yet to avoid people having to change their configs.  It's really just a sanity check, so there's no need (and it would be complicated) to have separate local and remote timeouts

**Comment by DanCech** [comment]
#2196
