### ISSUE TITLE
Minor assertion fix for render/datalib.py

### ISSUE THREAD

**Issue by surendarchandra** [graphite-project/graphite-web#2197]
Seeing sporadic asserts (and Internal server error) in this line 'if j is None and series[i] is not None' of '/opt/graphite/webapp/graphite/render/datalib.py' (IndexError: list index out of range). Should be 
'if j is None and I in series and series[i] is not None'. I'm on commit '0456360751' (1.1.1)

**Comment by deniszh** [comment]
@surendarchandra 
Whole code [looks like this](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/datalib.py#L210-L227):
```
      if known_nones > candidate_nones and len(series):
        if settings.REMOTE_STORE_MERGE_RESULTS:
          # This series has potential data that might be missing from
          # earlier series.  Attempt to merge in useful data and update
          # the cache count.
          log.debug("Merging multiple TimeSeries for %s" % known.name)
          for i, j in enumerate(known):
            if j is None and series[i] is not None:
              known[i] = series[i]
              known_nones -= 1
          # Store known_nones in our cache
          series_best_nones[known.name] = known_nones
        else:
          # Not merging data -
          # we've found a series better than what we've already seen. Update
          # the count cache and replace the given series in the array.
          series_best_nones[known.name] = candidate_nones
          seriesList[known.name] = series
```
So, it's part of code which merge duplicate data from different sources. If `series[i]` generating `Index not found` error then it means that two series with same name have different number of datapoints, i.e. usually different step, which shouldn't happening normally. OTOH generating error is not good idea, of course.
We can change it as you proposing, but I think in this case result of data merge will be garbage anyway.  Or we can wrap it with `try... except IndexError: pass`, then we'll return  at least one serie from two. Not sure what result is better.
Ideas? 
@DanCech @iksaif @cbowman0 ?
Thanks!

**Comment by surendarchandra** [comment]
We are rendering *metric* where the matching metrics might be a1-metric and b1-metric (and so there would be different number of data points for each metric). Would that cause this issue? Thanks @deniszh

**Comment by deniszh** [comment]
@surendarchandra:
What do you mean, a1-metric and b1-metric ? Different names? No, this code works only for _merging_ same name metric from different sources, in this case, every storage should return the same amount of data points.

**Comment by deniszh** [comment]
Well, in case of one datasource returns e.g. 600 datapoints and another for some reason returns 601, we can easily ignore the last datapoint, as you proposing. But if one datasource return 600 datapoints and another returns e.g. 3600 datapoints for same metric and time period - it will be quite hard to merge both in this case.

**Comment by DanCech** [comment]
Indeed, and if the lengths aren't the same that may indicate that the resolution of the data is different, in which case trying to merge them would be counter-productive.  The best answer might be to switch to something like:
`if settings.REMOTE_STORE_MERGE_RESULTS and len(series) == len(known):`

**Comment by deniszh** [comment]
Yep, agreed - https://github.com/graphite-project/graphite-web/pull/2198

**Comment by deniszh** [comment]
Merged, will backport to 1.1.x

**Comment by deniszh** [comment]
Backport PR - https://github.com/graphite-project/carbon/pull/732

**Comment by surendarchandra** [comment]
Thanks for the fix!!

**Comment by deniszh** [comment]
Even on localhost it should have same length, right?

**Comment by djkerya** [comment]
Just wanted to say thank you and leave it here :-)
