### ISSUE TITLE
Graphite 1.1.2 release

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#2203]
I'm going to release bugfix 1.1.2 release in a week or so. I backported all current patches to 1.1.x branch, so, that's a last call for adding more before release.

**Comment by wridgers** [comment]
This can probably be closed. :)

Upgraded to 1.1.2 today and it seems much smoother! 

Thanks guys :)

**Comment by deniszh** [comment]
Cool, thanks for testing that, @wridgers !
