### ISSUE TITLE
How to migrate old format to new format

### ISSUE THREAD

**Issue by codexiao** [graphite-project/graphite-web#2211]
Hi,

I have an existing Graphite instance that receiving and storing metric in following format:

measurement.tag1.tag2.tag3.field1 value

Now, due to some reason, my project is going to change the metric format. Let's say the new format is:

measurement.tag4.tag5.field2 value

However, meanwhile we would like to keep the previous historical data. So the question is how to migrate all the metrics in old format to the new format in whisper. 

I did some search but couldn't find a clue. Any guidance is appreciated. 

Thank you

**Comment by DanCech** [comment]
The whisper files just have to be moved to the right location, currently your example file would be `/opt/graphite/storage/whisper/measurement/tag1/tag2/tag3/field1.wsp` and you need to move it to `/opt/graphite/storage/whisper/measurement/tag4/tag5/field2.wsp`

**Comment by codexiao** [comment]
@DanCech  Awesome! Thanks a lot!
