### ISSUE TITLE
Metric not created because filename is too long when using many tags

### ISSUE THREAD

**Issue by t4ko** [graphite-project/graphite-web#2219]
- What I attempted
It tried to insert a new tagged serie with many tags using write_graphite and later manually querying graphite to confirm the issue.

- Expected Result
I expected the metric to be created and available in graphite

- Witnessed Result
I get this error whent trying to create a serie with many tags. The problem is obviously that the filename of the serie is too long because of the tags that are added.

> [console] Error creating SINGLE_SERIE_WITH_LOT_OF_TAGS: [Errno 36] File name too long: ...

- System Details
Linux / Ubuntu 16.04 based docker image (latest version of graphiteapp/graphite-statsd)
Python 2.7.12
Django 1.8.18
Graphite 1.1.1

The error I get is the same with both write_graphite and manual query to graphite so I suppose Graphite or TagDB is at fault.

Is it the expected behaviour to have the tag names in the serie's filename ? 
This is very limiting, even more with write_graphite which automatically add some tags.

**Comment by DanCech** [comment]
Currently the filenames created are in a human-readable format, but it would be possible to add a configuration setting to support using the hash instead which would work around this problem by changing the behavior of `TaggedSeries.encode()`.  That would need to be done in both carbon and graphite-web, and the 2 would need to be kept in sync.

**Comment by DanCech** [comment]
See #2221

**Comment by t4ko** [comment]
Well that was fast and it works! Thank you.
I quickly made this docker image using a Graphite installation made from the new branch including this feature for anyone interested : https://hub.docker.com/r/t4ko/docker-graphite-tags-hash/

**Comment by deniszh** [comment]
Hello @t4ko,
Did you test migration to new schema btw? does it pick up metrics in old format too?

**Comment by twiedenbein** [comment]
The merging functionality seems to work for me.
