### ISSUE TITLE
Series division by aggregateLine

### ISSUE THREAD

**Issue by pinkynrg** [graphite-project/graphite-web#2232]
I have the following aggregateLine:
```
aggregateLine(some.variable,'avg')
```

Now I would like to divide another non-constant series to the aggreateLine above. 
In my head it would be something like this, but it does not work:

``` 
divideSeries(some.other.variable, aggregateLine(some.variable,'avg'))
```

I read in the documentation that divideSeries must not be used to divide series by a constant and I read about using the scale() function. The problem is that I need to calculate the constant as shown in the first step. 

To read the same issue phrased differently follow [link](https://stackoverflow.com/questions/48776161/graphite-series-division-by-aggregateline)

How can I solve this issue?

**Comment by deniszh** [comment]
>In my head it would be something like this, but it does not work

What exactly it's not working?

**Comment by pinkynrg** [comment]
@deniszh: It takes quite a while to process and then it doesn't show any points. 
@DanCech: do you have an idea on how i can solve this issue? Is there a way to either:
- get some single value average so i can use the scale() function?
- get an actual series (with more than 3 points) to use the divideSeries() function?

**Comment by deniszh** [comment]
>The problem is that aggregateLine produces a series with only 3 points, so it's not really going to work for this kind of thing.

Ah, indeed - https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L4071
Probably we can add step as additional parameter to `constantLine()` and `aggregateLine()`

**Comment by pinkynrg** [comment]
That would be an awesome improvement given it will not slow things down terribly

**Comment by DanCech** [comment]
The simplest change may be simply to have aggregateLine produce the same step as the input series, which would be quite a trivial patch.  I'm trying to think of any applications where that change would cause a problem...

**Comment by pinkynrg** [comment]
I love it, this patch would help me out so much, hopefully it will not break anything else!

**Comment by DanCech** [comment]
The one issue I can see right now is that currently `aggregateLine` totally ignores the start and end of the series and instead uses the graph period, which would make the behavior with this change somewhat different when applied to a series where start and end don't match the graph period.  Not sure whether the best solution is to add a flag to control whether you get the legacy or the "new" behavior, that seems like the safest approach.  I have 1/2 a patch here, will see if I can find some time to polish it up tomorrow.

**Comment by pinkynrg** [comment]
Nice man, I'll wait for the merge into master! :) thanks again, that was fast support indeed.

**Comment by pinkynrg** [comment]
I see the merge into master :) I'll update to the new version of graphite, do some testing, and give you feedback. 

Thanks

**Comment by pinkynrg** [comment]
worked like a charm. closing
