### ISSUE TITLE
Step function and minutes count

### ISSUE THREAD

**Issue by pinkynrg** [graphite-project/graphite-web#2235]
I have a curve that has multiple states 0, 1, 2, 4, or 5. 

Is there a way to transform this curve into a step function where all values equal 0 stay 0 and all values grater then 0 become 1?

Is there a way to also know how many minutes the function is greater than 0 in the given time range?

**Comment by DanCech** [comment]
You could use:

`some.series|transformNull(-1)|removeAboveValue(0)||transformNull(1)|removeBelowValue(0)`

That will take your values, assign any null points the value -1, remove all the values above 0 (setting them to null), transform those nulls to 1, then set the -1 values we set earlier back to null.

The total number of minutes above zero will be the sum of the series.

**Comment by pinkynrg** [comment]
Boom! closing :)
