### ISSUE TITLE
Matching metrics with the form collectd.db-shard-$host|*.foo.bar

### ISSUE THREAD

**Issue by Farfaday** [graphite-project/graphite-web#2236]
Hi,
we upgraded today graphite-web from 9.15 to 1.1.2.

$host is an integer between 1 and 100, so we have whisper like  collectd/db-shard-45|stuffs/foo/bar.wsp
Those metrics used to be matched with collectd.db-shard-$host|*.foo.bar in grafana. But they are not matched anymore with 1.1.2

If i remove the "|" char, metrics get matched but when $host has for example value 4, then also 40 to 49 get matched.

Is there something I am missing ? Needs the | to be somehow escaped ?
Many Thanks!
François

**Comment by deniszh** [comment]
'|' has a special meaning now - it's function separator.  Not sure if you can escape it, probably not.
Maybe @DanCech have some ideas?

**Comment by Farfaday** [comment]
Hi,
Okay, thanks for your reply!
Having the possibility to escape it would be great, as this char was allowed in the metric names before.
Many Thanks!
