### ISSUE TITLE
DL4J or other machine learning

### ISSUE THREAD

**Issue by jdbranham** [graphite-project/graphite-web#2242]
I've been working on a library that leverages DL4J to classify Graphite query results.  
The current implementation attempts to take multiple time-series and calculate a postive/negative class label based on examples provided to the learner.  

The learner provides a model that can be used to predict the class on a new example.

Is anyone interested in this, or are there other solutions that maybe I'm not aware of?

https://github.com/savantly-net/graphite-dl4j

**Comment by piotr1212** [comment]
Cool, you can add your tool to: https://github.com/graphite-project/graphite-web/blob/master/docs/tools.rst for extra visibility. 

I know some people doing ML with graphite as source, but that are mostly company internal projects.
