### ISSUE TITLE
List of tags not matched correctly in seriesByTag

### ISSUE THREAD

**Issue by t4ko** [graphite-project/graphite-web#2245]
- What I attempted
I tried to render with a target using seriesByTag containing an expression using a list of values
seriesByTag('tag1={value1,value2}')
http://GRAPHITE/render?format=json&target=seriesByTag(%27tag1={value1,value2}%27)

- Expected Result
The datapoint for all series matching the tags in the list of values
For example all datapoints for the following series in the selected interval :
foo.bar;tag1=value1
foo.bar;tag1=value2

- Witnessed Result
No series are found

- System Details
Linux / Ubuntu 16.04
Python 2.7.12
Django 1.8.18
Graphite 1.1.2

I know I can achieve the same result using the =~ operator and [value1|value2] but I use grafana to query those series and this is not the way a value list is passed to the query editor. The syntax used by grafana is already supported for multiple series querying without tags.
It would be easier to have the tag expression interpreter be able to factorize or convert the {,,,} format

**Comment by DanCech** [comment]
See https://github.com/grafana/grafana/pull/11002
