### ISSUE TITLE
[Question]: How to count percentage of 1 in a [1, 0] series

### ISSUE THREAD

**Issue by hanks** [graphite-project/graphite-web#2246]
Hi,

I have a series with [1, 0] value, how to count percentage of 1 in the whole series in Graphite, I want to get the only one float number of the percentage value like `99.19%` used in Grafana.  And the [1, 0] series is like below: `isNonNull(local.random.diceroll)`.

My basic idea is to:

1. count sum of 1 in the series using `integral(isNonNull(local.random.diceroll))`
2. count the total number of datapoint in the series, **but I can not find a way to do that**
3. use `(number of 1) / (total datapoint number)` to count percentage, **but it is hard to write formula like this**

Thank you for your time.

**Comment by DanCech** [comment]
The percentage of values that are 1 in a series of 1 and 0 will be the average value of the series, so if you're using a singlestat panel in Grafana you can just use `isNonNull(local.random.diceroll)` with `Stat: Average` and `Unit: percent (0.0-1.0)`.  If you don't want/need to show the sparkline you can also set `maxDataPoints: 1` in the query options so the average will be computed in Graphite and a single point sent to Grafana.

**Comment by hanks** [comment]
@DanCech Thank you for your advice, I also noticed that **The percentage of values that are 1 in a series of 1 and 0 will be the average value of the series**, so I use `averageSeries(isNonNull(local.random.diceroll)` to solve this problem

**Comment by DanCech** [comment]
@hanks [averageSeries](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.averageSeries)() returns the average of the values *for each interval*, it is a no-op for you since you only have a single series.
