### ISSUE TITLE
Alias with Umlauts faulty

### ISSUE THREAD

**Issue by laDanz** [graphite-project/graphite-web#2247]
When trying to save a graph with umlauts in its alias there seems to be a faulty behaviour:
Sometimes the saved graph won't show, sometimes even other graphs disappear from the "MyGraphs" section.

One time i had to manually delete the faulty graph from the graphite database, to make my other graphs visible again.

Example:
![image](https://user-images.githubusercontent.com/166216/36717108-0ddbdab2-1b9d-11e8-9958-d41fe1bfa71a.png)
http://GRAPHITE_HOST:8080/render/?target=alias(carbon.agents.xxx.avgUpdateTime%2C%22Umalu%C3%A4%C3%BC%C3%B6%22)

**Comment by piotr1212** [comment]
There are known issues with non-ascii characters in Graphite-web.
