### ISSUE TITLE
Graphite no longer works via wsgi once migrating to 1.1.2

### ISSUE THREAD

**Issue by jdblack** [graphite-project/graphite-web#2248]
Making requests to graphite-web 1.1.2 is timing out and failing to render graphs. I'm able to  get   pages and an empty render from  http://localhost:8080/render/   when running graphite via  manage.py.

It seems as if the /tags/tagMultiSeries requests are causing graphite-web to break when graphite-web is being run under wsgi.

```
_graphite@ip-10-10-1-184:/opt/graphite/webapp/graphite$ PYTHONPATH=/opt/graphite/webapp:$PYTHONPATH python manage.py runserver 0.0.0.0:8080
Performing system checks...

System check identified no issues (55 silenced).
February 28, 2018 - 16:34:00
Django version 1.9.13, using settings 'settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[28/Feb/2018 16:34:02] "POST /tags/tagMultiSeries HTTP/1.1" 200 69
[28/Feb/2018 16:34:03] "POST /tags/tagMultiSeries HTTP/1.1" 200 106
[28/Feb/2018 16:34:03] "POST /tags/tagMultiSeries HTTP/1.1" 200 62
[28/Feb/2018 16:34:07] "GET / HTTP/1.1" 200 963
[28/Feb/2018 16:34:09] "GET / HTTP/1.1" 200 963
[28/Feb/2018 16:34:12] "GET /render/ HTTP/1.1" 200 1472
```

```
Running with gunicorn:
_graphite@ip-10-10-1-184:/opt/graphite/webapp$  /usr/bin/gunicorn --pythonpath . --pid /var/log/graphite/gunicorn.pid --chdir /opt/graphite/webapp --error-logfile /var/log/graphite/error.log -w 1  -b 127.0.0.1:8080 wsgi:application --log-level debug

root@ip-10-10-1-184:/var/log/graphite# cat error.log
[2018-03-01 00:29:33 +0000] [29788] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7ff3190d09b0>
  pythonpath: .
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7ff3190d06e0>
  pre_fork: <function pre_fork at 0x7ff3190d0848>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 118
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: None
  sendfile: None
  pidfile: /var/log/graphite/gunicorn.pid
  umask: 0
  on_reload: <function on_reload at 0x7ff3190d0578>
  pre_exec: <function pre_exec at 0x7ff3190d0f50>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7ff3190d0b18>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7ff3190d5668>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7ff3190d5140>
  post_request: <function post_request at 0x7ff3190d5230>
  user: 114
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7ff3190d0c80>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7ff3190d5398>
  chdir: /opt/graphite/webapp
  paste: None
  default_proc_name: wsgi:application
  errorlog: /var/log/graphite/error.log
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7ff3190d0410>
  worker_abort: <function worker_abort at 0x7ff3190d0de8>
  bind: ['127.0.0.1:8080']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7ff3190d5500>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix:
[2018-03-01 00:29:33 +0000] [29788] [INFO] Starting gunicorn 19.4.5
[2018-03-01 00:29:33 +0000] [29788] [DEBUG] Arbiter booted
[2018-03-01 00:29:33 +0000] [29788] [INFO] Listening at: http://127.0.0.1:8080 (29788)
[2018-03-01 00:29:33 +0000] [29788] [INFO] Using worker: sync
[2018-03-01 00:29:33 +0000] [29792] [INFO] Booting worker with pid: 29792
[2018-03-01 00:29:33 +0000] [29788] [DEBUG] 1 workers
[2018-02-28 16:29:33 +0000] [29792] [DEBUG] POST /tags/tagMultiSeries
[2018-02-28 16:29:36 +0000] [29792] [DEBUG] POST /tags/tagMultiSeries
[2018-02-28 16:29:38 +0000] [29792] [DEBUG] Ignoring EPIPE
[2018-02-28 16:29:38 +0000] [29792] [DEBUG] POST /tags/tagMultiSeries
[2018-02-28 16:29:41 +0000] [29792] [DEBUG] Ignoring EPIPE
[2018-02-28 16:29:41 +0000] [29792] [DEBUG] POST /tags/tagMultiSeries

```

```
Running with uwsgi:
_graphite@ip-10-10-1-184:/opt/graphite/webapp$ uwsgi --chdir=/opt/graphite/webapp   --master  --http 127.0.0.1:8080  --pythonpath /opt/graphite/webapp/graphite --wsgi-file=/opt/graphite/conf/graphite.wsgi.example
*** Starting uWSGI 2.0.17 (64bit) on [Thu Mar  1 00:27:49 2018] ***
compiled with version: 5.4.0 20160609 on 26 February 2018 20:30:02
os: Linux-4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017
nodename: ip-10-10-1-184
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /opt/graphite/webapp
detected binary path: /usr/local/bin/uwsgi
chdir() to /opt/graphite/webapp
your processes number limit is 128623
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8080 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:33511 (port auto-assigned) fd 3
Python version: 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xe9f940
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /opt/graphite/webapp/graphite/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xe9f940 pid: 29448 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 29448)
spawned uWSGI worker 1 (pid: 29451, cores: 1)
spawned uWSGI http 1 (pid: 29452)
[pid: 29451|app: 0|req: 1/1] 127.0.0.1 () {30 vars in 418 bytes} [Wed Feb 28 16:27:49 2018] POST /tags/tagMultiSeries => generated 101 bytes in 2510 msecs (HTTP/1.1 200) 1 headers in 51 bytes (1 switches on core 0)
[pid: 29451|app: 0|req: 2/2] 127.0.0.1 () {30 vars in 418 bytes} [Wed Feb 28 16:27:52 2018] POST /tags/tagMultiSeries => generated 82 bytes in 2441 msecs (HTTP/1.1 200) 1 headers in 51 bytes (1 switches on core 0)
[pid: 29451|app: 0|req: 3/3] 127.0.0.1 () {30 vars in 418 bytes} [Wed Feb 28 16:27:54 2018] POST /tags/tagMultiSeries => generated 66 bytes in 2546 msecs (HTTP/1.1 200) 1 headers in 51 bytes (1 switches on core 0)
[pid: 29451|app: 0|req: 4/4] 127.0.0.1 () {30 vars in 418 bytes} [Wed Feb 28 16:27:57 2018] POST /tags/tagMultiSeries => generated 424 bytes in 12713 msecs (HTTP/1.1 200) 2 headers in 74 bytes (1 switches on core 0)

```

```
root@ip-10-10-1-184:/opt/graphite/webapp# cat wsgi.py
import sys
sys.path.append('/opt/graphite/webapp')

from graphite.wsgi import application
root@ip-10-10-1-184:/opt/graphite/webapp# cat ../conf/graphite.wsgi.example
import sys
sys.path.append('/opt/graphite/webapp')

from graphite.wsgi import application
```

```
python path
_graphite@ip-10-10-1-184:/opt/graphite/webapp/graphite$   python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
>>>
```

```
python verison and  pip list
_graphite@ip-10-10-1-184:/opt/graphite/webapp/graphite$ python --version
Python 2.7.12
_graphite@ip-10-10-1-184:/opt/graphite/webapp/graphite$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.10)
appdirs (1.4.3)
attrs (15.2.0)
awscli (1.11.64)
Babel (2.4.0)
boto (2.46.1)
botocore (1.5.27)
BTrees (4.4.1)
cachetools (2.0.1)
cairocffi (0.8.0)
carbon (1.1.2)
carbonate (1.1.1)
cffi (1.10.0)
chardet (2.3.0)
colorama (0.3.7)
cryptography (1.2.3)
Django (1.9.13)
django-appconf (1.0.2)
django-shortcuts (1.5)
django-staticfiles (1.2.1)
django-tagging (0.4.3)
docutils (0.13.1)
enum34 (1.1.2)
funcsigs (1.0.2)
futures (3.0.5)
gevent (1.1.0)
graphite-web (1.1.2)
greenlet (0.4.9)
gunicorn (19.4.5)
idna (2.0)
imagesize (0.7.1)
ipaddress (1.0.16)
Jinja2 (2.9.6)
jmespath (0.9.2)
MarkupSafe (1.0)
mock (2.0.0)
mocker (1.1.1)
MySQL-python (1.2.5)
ndg-httpsclient (0.4.0)
packaging (16.8)
PAM (0.4.2)
pbr (2.0.0)
persistent (4.2.4.2)
pip (9.0.1)
pyasn1 (0.1.9)
pyasn1-modules (0.0.7)
pycparser (2.18)
Pygments (2.2.0)
pyOpenSSL (0.15.1)
pyparsing (2.2.0)
pyserial (3.0.1)
python-dateutil (2.6.0)
python-gettext (3.0)
python-memcached (1.53)
pytz (2017.2)
PyYAML (3.12)
requests (2.9.1)
rsa (3.4.2)
s3transfer (0.1.10)
scandir (1.5)
service-identity (16.0.0)
setuptools (38.5.1)
simplejson (3.8.1)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.6.3)
sphinx-rtd-theme (0.2.4)
sphinxcontrib-websupport (1.0.1)
sqlparse (0.1.18)
stevedore (1.21.0)
transaction (2.1.2)
trollius (2.1)
Twisted (16.0.0)
txAMQP (0.7.0)
typing (3.6.1)
urllib3 (1.21.1)
uWSGI (2.0.17)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
wheel (0.29.0)
whisper (1.1.2)
whitenoise (3.3.0)
zc.lockfile (1.2.1)
ZConfig (3.2.0)
zdaemon (4.2.0)
```

```
listing of /opt/graphite/webapp
_graphite@ip-10-10-1-184:/opt/graphite/webapp$ ls
content				    graphite_web-1.0.1-py2.7.egg-info  graphite_web-1.1.2-py2.7.egg-info
graphite			    graphite_web-1.1.0-py2.7.egg-info  wsgi.py
graphite_web-0.9.15-py2.7.egg-info  graphite_web-1.1.1-py2.7.egg-info  wsgi.pyc
```

**Comment by jdblack** [comment]
I am also seeing the following errors on rds:
2018-02-28T23:55:05.182387Z 12272 [Note] Aborted connection 12272 to db: 'graphite_dev' user: 'graphite' host: '10.10.1.76' (Got an error reading communication packets)
2018-02-28T23:55:09.185732Z 12282 [Note] Aborted connection 12282 to db: 'graphite_dev' user: 'graphite' host: '10.10.2.86' (Got an error reading communication packets)
2018-02-28T23:55:13.017837Z 12284 [Note] Aborted connection 12284 to db: 'graphite_dev' user: 'graphite' host: '10.10.1.76' (Got an error reading communication packets)
2018-02-28T23:55:17.964528Z 12300 [Note] Aborted connection 12300 to db: 'graphite_dev' user: 'graphite' host: '10.10.2.86' (Got an error reading communication packets)
2018-02-28T23:55:21.054052Z 12302 [Note] Aborted connection 12302 to db: 'graphite_dev' user: 'graphite' host: '10.10.2.90' (Got an error reading communication packets)
2018-02-28T23:55:28.138228Z 12301 [Note] Aborted connection 12301 to db: 'graphite_dev' user: 'graphite' host: '10.10.1.76' (Got an error reading communication packets)
2018-02-28T23:55:34.630480Z 12318 [Note] Aborted connection 12318 to db: 'graphite_dev' user: 'graphite' host: '10.10.2.90' (Got an error reading communication packets)
2018-02-28T23:55:34.715368Z 12316 [Note] Aborted connection 12316 to db: 'graphite_dev' user: 'graphite' host: '10.10.2.86' (Got an error reading communication packets)
2018-02-28T23:55:41.230670Z 12317 [Note] Aborted connection 12317 to db: 'graphite_dev' user: 'graphite' host: '10.10.1.76' (Got an error reading communication packets)

**Comment by deniszh** [comment]
Hmm... No other errors in log file ? I do not see any issues in files above, unfortunately.

**Comment by deniszh** [comment]
Did you upgrade Django when upgrading Graphite to 1.1.2 ? Which was the old version?

**Comment by jdblack** [comment]
I do not think django was upgraded at the time we upgraded graphite 1.1.2,  though we may have upgraded during the process to figure out what's wrong.

**Comment by jdblack** [comment]
I tried upgrading django from 1.9.13 to 1.11.0 with no success.

However, I did find that graphite-web seems to work if I firewall off posts to  /tags/tagMultiSeries:

iptables -A OUTPUT -p tcp -m string --string "POST /tags/tagMultiSeries" --algo kmp -j REJECT

**Comment by deniszh** [comment]
@jdblack :
Very strange. Looks somewhat similar to https://github.com/graphite-project/graphite-web/issues/2243 but totally different call.
Do you have cluster configured? Or it's single node? 
Blocking tags makes it working for uwsgi, right?

Are you using tags btw? If not - you can try to disable it completely, using `TAGDB=None`.

**Comment by jdblack** [comment]
We really, really want to use  tags, but haven't quite put it into place yet.   Switching to using TAGDB=None   has worked for us! (Thanks! configuration via firewall makes my skin crawl).


I'll double check it started working under uswgi too (though I'm sure it will as with TAGDB=None, it works great in gunicorn).

We are in a clustered mode.

**Comment by deniszh** [comment]
@jdblack 
It looks similar to https://github.com/graphite-project/graphite-web/issues/2243
Could you please show how your `CLUSTER_SERVERS` looks like?
If something like
```
CLUSTER_SERVERS=[`x.x.x.x`, `y.y.y.y`]
```
then you need or apply https://github.com/graphite-project/graphite-web/pull/2244 or try
```
CLUSTER_SERVERS=[`http://x.x.x.x?noTags=1`,`http://y.y.y.y?noTags=1`]
```

Pprobably we should release 1.1.3 with PR#2244 and document CLUSTER_SERVERS format, described in https://github.com/graphite-project/graphite-web/pull/2123 and https://github.com/graphite-project/graphite-web/commit/4c5a7c44bb1b12dd3724a50569b4d9c45b85ca20

**Comment by jdblack** [comment]
This is going to sound a little crazy, but we have 4 separate graphite-dev clusters in dev, becuase we're emulating a much larger buildout in prod. We have 3 layers in our graphite-setup;   a relay layer, a cache layer, and a  presentation layer. 


 -  The relay layer is just  carbon-c-relay. 

 - The presentation layer contains grafana and graphite-web
    - grafana is configured to talk to graphite-web on localhost
    - the graphite-web is configured to cluster with all of the other  graphite-webs in our stack and local_settings.py includes the CLUSTER_SERVERS directive that includes all of the graphite-webs from our cache layer
   CLUSTER_SERVERS = ["x.x.x.x:8080", "x.x.x.x:8080", "x.x.x.x:8080", "x.x.x.x:8080"]

 -  The  cache layer  contains carbon-c-relay,  carbon,  and graphite-web. 
    - We have 4 carbon_ch clusters in dev, which I will call 1a-old,  1c-old,   1a-new and 1c-new.
    - Each cluster in dev has a single system in it (again, emulating a much larger stack in prod)
    -  1a-old and 1c-old are meant to be independent redundant clusters
    -  1a-new and 1c-new are meant to be eventual replacements for 1a-old and 1c-old 
    - graphite-web on these systems do not have a CLUSTER_SERVERS directive
   - graphite-web on these systems does have a 
          CARBONLINK_HOSTS = ["127.0.0.1:7012:1", "127.0.0.1:7022:2", "127.0.0.1:7032:3"]

**Comment by jdblack** [comment]
@deniszh  
In our setting,   we have a  graphite-web on two layers;  a   UI layer (for grafana and graphite-web rendering requests) and a cache layer.  On the  UI layer,  graphite-web  has a CLUSTER_SERVERS that includes all of the  graphite-webs on the cache layer.   The  graphite-webs on the cache layer  do not themselves have a  CLUSTERS_SERVERS  configuration

Right now graphite-web on both layers have TAGDB=None.   My understanding is that I should remove that from both layers. Then,  on the UI layer,  I should update  graphite-web on  CLUSTER_SERVERS config to add ?noTags=1. Is this correct?

**Comment by DanCech** [comment]
the `?noTags=1` setting just controls what happens when a query that contains `seriesByTag` calls is received.  By default the `seriesByTag` call is passed through to the cluster servers, with that option it is instead resolved against the local TagDB and the resulting series are requested from the cluster servers.  If you aren't using `seriesByTag` there won't be any difference.

**Comment by jdblack** [comment]
We've set up graphite-web to use the same mysql db across all of the same hosts, so I suppose it makes the most sense for us, then, to tell the UI layer to  ?noTags=1  since it can look up  for itself.

**Comment by DanCech** [comment]
yes if you're using a shared mysql then that will likely be more efficient since you'll just do the tag lookup once on the frontend graphite-web
