### ISSUE TITLE
templating not working with timeStack function

### ISSUE THREAD

**Issue by pinkynrg** [graphite-project/graphite-web#2249]
I would like to say that I am able to use templating, this is one case though where I cannot get it to work.

So the following query executes just fine:

```
timeStack(summarize(portal.ovomec.santa_maria_di_sala.1308756.ovomec_smart_one.food_distributed_today.0,'10minutes','max'),'24h',0,10)
```

no let's say I wrap the function in a template without changing anything in the original function:

```
template(timeStack(summarize(portal.ovomec.santa_maria_di_sala.1308756.ovomec_smart_one.food_distributed_today.0,'10minutes','max'),'24h',0,10))
```

everything works as in the first query, cool that's what I was expecting.

What if now I replace `portal.ovomec.santa_maria_di_sala.1308756.ovomec_smart_one` with a `$prefix` placeholder and I pass it in a `template[prefix]`variable:

```
template(timeStack(summarize($prefix.0,'10minutes','max'),'24h',0,10))&template[prefix]=portal.ovomec.santa_maria_di_sala.1308756.ovomec_smart_one.food_distributed_today
```

This doesn't work anymore and I don't understand why. 

Any help is appreciated. Thanks.

**Comment by deniszh** [comment]
Hi @pinkynrg ,
I can be wrong, but I suspecting that `template` can't contain '.'
Try this:
```
template(timeStack(summarize(portal.ovomec.santa_maria_di_sala.1308756.ovomec_smart_one.$prefix.0,'10minutes','max'),'24h',0,10))&template[prefix]=food_distributed_today
```
(i know that's not what you want to achive, just for trsting this).

BTW, PR for template - https://github.com/graphite-project/graphite-web/pull/1205, it also contain some tests, which are still working fine.

**Comment by pinkynrg** [comment]
> I can be wrong, but I suspecting that template can't contain '.'

Do you mean that `template[prefix]` can't have dots inside the passed string `portal.ovomec.santa_maria_di_sala.1308756.ovomec_smart_one.food_distributed_today`?

If that's what you meant I have used the template functionality by passing string with dots without having issues. 

This particular query used with templating gives me hard time. I'll try as well to pin point the issue so I can give more details.

**Comment by pinkynrg** [comment]
for instance the below query works as expected:
```
http://graphite.net/render?target=template(averageSeries($ctrl.temperature_probe.0))&from=00:00_20180101&until=01:00_20180101&format=json&template[ctrl]=this.is.one.of.my.controllers
```

**Comment by deniszh** [comment]
Ok, got it. Could you please elaborate how exactly it doesn't work?

**Comment by pinkynrg** [comment]
working query:

```
http://graphite.faccousa.net/render?format=json&from=20180215&until=20180301&target=template(timeStack(summarize(portal.ovomec.santa_maria_di_sala.1308756.ovomec_smart_one.food_distributed_today.0,%2710minutes%27,%27max%27),%2724h%27,0,10))
```

result of working query:

```
[{"datapoints": [[596.0, 1518674400], [596.0, 1518675000], [596.0, 1518675600], [596.0, 1518676200], [596.0, 1518676800], [596.0, 1518677400], [596.0, 1518678000], [596.0, 1518678600], [596.0, 1518679200], [596.0, 1518679800], [596.0, 1518680400], [596.0, 1518681000], [596.0, 1518681600], [596.0, 1518682200], [596.0, 1518682800], [596.0, 1518683400], [596.0, 1518684000], [596.0, 1518684600], [596.0, 1518685200], [596.0, 1518685800], [596.0, 1518686400], [596.0, 1518687000], [596.0, 1518687600], [596.0, 1518688200], [596.0, 1518688800], [596.0, 1518689400], [596.0, 1518690000], [596.0, 1518690600], [596.0, 1518691200], [596.0, 1518691800], [596.0, 1518692400], [596.0, 1518693000], [596.0, 1518693600], [596.0, 1518694200], [596.0, 1518694800], [596.0, 1518695400], [596.0, 1518696000], [596.0, 1518696600], [596.0, 1518697200], [596.0, 1518697800], [596.0, 1518698400], [596.0, 1518699000], [596.0, 1518699600], [596.0, 1518700200], [596.0, 1518700800], [596.0, 1518701400], [596.0, 1518702000], [596.0, 1518702600], [596.0, 1518703200], [596.0, 1518703800], [596.0, 1518704400], [596.0, 1518705000], [596.0, 1518705600], [596.0, 1518706200], [596.0, 1518706800], [596.0, 1518707400], [596.0, 1518708000], [596.0, 1518708600], [596.0, 1518709200], [596.0, 1518709800], [596.0, 1518710400], [596.0, 1518711000], [596.0, 1518711600], [596.0, 1518712200], [596.0, 1518712800], [1664.0, 1518713400], [1664.0, 1518714000], [1664.0, 1518714600], [1664.0, 1518715200], [1664.0, 1518715800], [1664.0, 1518716400], [3275.0, 1518717000], [3275.0, 1518717600], [3275.0, 1518718200], [3275.0, 1518718800], [3275.0, 1518719400], [3275.0, 1518720000], [3275.0, 1518720600], [3275.0, 1518721200], [3275.0, 1518721800], [3275.0, 1518722400], [3275.0, 1518723000], [3275.0, 1518723600], [3275.0, 1518724200], [3275.0, 1518724800], [3275.0, 1518725400], [3275.0, 1518726000], [3275.0, 1518726600], [3275.0, 1518727200], [3275.0, 1518727800], [3275.0, 1518728400], [3275.0, 1518729000], [3275.0, 1518729600], [3275.0, 1518730200], [3275.0, 1518730800], [3275.0, 1518731400], [3275.0, 1518732000], [3275.0, 1518732600], [3275.0, 1518733200], [3275.0, 1518733800], [3275.0, 1518734400], [3275.0, 1518735000], [0.0, 1518735600], [0.0, 1518736200], [0.0, 1518736800], [0.0, 1518737400], [0.0, 1518738000], [0.0, 1518738600], [0.0, 1518739200], [0.0, 1518739800], [0.0, 1518740400], [0.0, 1518741000], ...
```

broken query:

```
http://graphite.faccousa.net/render?format=json&from=20180215&until=20180301&target=template(timeStack(summarize($ctrl.food_distributed_today.0,%2710minutes%27,%27max%27),%2724h%27,0,10))&template[ctrl]=portal.ovomec.santa_maria_di_sala.1308756.ovomec_smart_one
```

result of working query:
```
[]
```

**Comment by pinkynrg** [comment]
The problem seems to be related with the timeStack function.

this works: 

```
http://graphite.il.faccousa.net/render?format=json&from=20180215&until=20180301&target=template($ctrl.food_distributed_today.0)&template[ctrl]=this.is.my.controller
```

this does not work:

```
http://graphite.il.faccousa.net/render?format=json&from=20180215&until=20180301&target=template(timeStack($ctrl.food_distributed_today.0,'24h',0,10))&template[ctrl]=this.is.my.controller
```

**Comment by deniszh** [comment]
Sorry for stupid question - but does `timeStack(summarize(...))` working fine w/o templating?

**Comment by pinkynrg** [comment]
Yes it works perfectly

**Comment by DanCech** [comment]
Have you tried moving the template call inside the timeStack?

```
http://graphite.il.faccousa.net/render?format=json&from=20180215&until=20180301&target=timeStack(template($ctrl.food_distributed_today.0),'24h',0,10)&template[ctrl]=this.is.my.controller
```

**Comment by pinkynrg** [comment]
I'm going to try that but that would kind of break the pattern I was trying to follow in my application. Is it known why it behaves that way? 

By the way, I'm definitely committing myself to use Graphite for quite a bit of time in the future so I would love to eventually be more active in its development.

**Comment by DanCech** [comment]
`timeStack` re-evaluates the query passed to it with the context adjusted for the different time periods, so with `template` outside it's evaluating `$ctrl.food_distributed_today.0` not `template($ctrl.food_distributed_today.0)`

**Comment by pinkynrg** [comment]
I wished that the template function worked by str.replacing of $ prefixed string with passed parameter in the url.

**Comment by pinkynrg** [comment]
What I have is a list of formulas with a $ctrl and an $index placeholder.

Since my average user doesn't know how to write a query I want him to select a query and associated it to a controller and an index: this way I can have him select the curve I pre-built for him associated though to the resource he wants.

**Comment by pinkynrg** [comment]
If there is no way that the template function could be improved to handle this particular case I believe we can close the issue.

**Comment by deniszh** [comment]
Well, everything is possible, but I would say in this case effort is not worth the outcome.
IMO it's a clear edge case, and it's should be documented, like 'please use template() as  close do metrics as possible, otherwise it will not work with functions which re-evaluates queries, e.g. `timeStack()`'.

**Comment by pinkynrg** [comment]
I kept thinking about this and I'm thinking that the way I'm using this function is the most intuitive way, the rule is one: "wrap your function with it, that's it". 

I would really like to see it function the way I'm describing above unless, of course, there are side effects I'm not taking into consideration. 

I have not clue how the template function works, but wouldn't be kind of easy to just replace the $placeholders with the parameter `placeholder`? Isn't it just a matter of "string replacing" placeholder with actual values passed in the url?

**Comment by DanCech** [comment]
If you'd like to take a stab at a PR to change the behavior as you're describing I'd be happy to review it.

**Comment by pinkynrg** [comment]
Fantastic I'll try my best to find the time. Any suggestions before I start?
