### ISSUE TITLE
round doesn't seem to work

### ISSUE THREAD

**Issue by pinkynrg** [graphite-project/graphite-web#2250]
the following rounding doesn't seemed to work:

```
round(minSeries(metrics.temperature_probe.{0,1,2}),2)
```

**Comment by DanCech** [comment]
Please give us something to work with. What are the results you are getting vs what you expect? Are you using maxDatapoints?

round is an alias for roundFunction

**Comment by deniszh** [comment]
Yes, some additional info is needed, 'cause testing code is still there and works - https://github.com/graphite-project/graphite-web/blob/53b9f97ef1f393dbc31cde2c681617e55c249dc5/webapp/tests/test_functions.py#L3794-L3816

**Comment by pinkynrg** [comment]
If I use the `roundFunction` i get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 117, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 28, in evaluateTarget
    result = evaluateTokens(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 57, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 84, in evaluateTokens
    func = SeriesFunction(tokens.call.funcname)
  File "/opt/graphite/webapp/graphite/functions/__init__.py", line 77, in SeriesFunction
    raise KeyError('Function "%s" not found' % name)
KeyError: u'Function "roundFunction" not found'
```

I thought I was using the correct version of graphiteWeb considering that I have of the latest change done on this repository due one of my last month requests.

**Comment by deniszh** [comment]
Yes, right name of the function is `round` - https://github.com/graphite-project/graphite-web/blob/53b9f97ef1f393dbc31cde2c681617e55c249dc5/webapp/graphite/render/functions.py#L5368
We should rename it, probably.

**Comment by deniszh** [comment]
@pinkynrg:
Sorry, but it's still not clear what's wrong is with rounding in  `round(minSeries(metrics.temperature_probe.{0,1,2}),2)`
Could you please elaborate?

**Comment by pinkynrg** [comment]
for some reason I cannot get the same result as a few days ago, I'm investigating the history of my past queries. As soon as I'll have them I'll post. Anyway, even though i was wrapping my original query (without the rounding) with `round(...,2)`, the result set was returning as nothing was done.

**Comment by pinkynrg** [comment]
I found out what the problem is, it seems like everything works as expected but when I add the `maxDataPoints` constrain. 

The following works:
`http://blabla.net/render?target=averageSeries(ctrl.temperature_probe.{0,1,2})&from=00:00_20180101&until=01:00_20180101&format=json`

result: 

`
[{"datapoints": [[22.03333333333333, 1514786700], [22.53333333333333, 1514787000], [22.333333333333332, 1514787300], [22.266666666666666, 1514787600], [22.53333333333333, 1514787900], [22.033333333333335, 1514788200], [22.53333333333333, 1514788500], [22.233333333333334, 1514788800], [22.233333333333334, 1514789100], [22.400000000000002, 1514789400], [22.099999999999998, 1514789700], [22.566666666666663, 1514790000]], "target": "averageSeries(ctrl.temperature_probe.{0,1,2})", "tags": {"aggregatedBy": "average", "name": "averageSeries(ctrl.temperature_probe.{0,1,2})"}}]

This doesn't:
`http://blabla.net/render?target=averageSeries(ctrl.temperature_probe.{0,1,2})&from=00:00_20180101&until=01:00_20180101&format=json&maxDataPoints=500`

result:

```
[{"datapoints": [[22.03333333333333, 1514786700], [22.53333333333333, 1514787000], [22.333333333333332, 1514787300], [22.266666666666666, 1514787600], [22.53333333333333, 1514787900], [22.033333333333335, 1514788200], [22.53333333333333, 1514788500], [22.233333333333334, 1514788800], [22.233333333333334, 1514789100], [22.400000000000002, 1514789400], [22.099999999999998, 1514789700], [22.566666666666663, 1514790000]], "target": "averageSeries(ctrl.temperature_probe.{0,1,2})", "tags": {"aggregatedBy": "average", "name": "averageSeries(ctrl.temperature_probe.{0,1,2})"}}]
```

**Comment by deniszh** [comment]
Yes, `maxDatapoints` making another aggregation, after `round()` - that's why @DanCech asked about it too.

**Comment by pinkynrg** [comment]
I see, sorry i didn't read carefully the first response this morning. Is there a way to have this work?

**Comment by deniszh** [comment]
@pinkynrg 
Not sure if it's possible in the current codebase. :( `consolidateBy` have no support for `round`, only ‘sum’, ‘average’, ‘min’, ‘max’, ‘first’ & ‘last’...
But I'm wondering why `maxDataPoints` doing aggregation even if you asking points for 1 hour and limit it to 500. Have you more than 500 points per hour? Because `maxDataPoints` should do nothing if the number of points is less then maxDataPoints...

**Comment by DanCech** [comment]
It may be possible to have `round` set a  value in the request context like the `consolidateBy` function does, so that the `maxDataPoints` code could honor it.

**Comment by pinkynrg** [comment]
would you be so nice to write a pseudo-query in order to avoid misunderstandings?

**Comment by DanCech** [comment]
@pinkynrg I'm describing development work that could be done, it's not supported right now.

**Comment by pinkynrg** [comment]
yeah I understood that, was just trying to understand what you meant
