### ISSUE TITLE
Hitcount not returning computing correct bucket count

### ISSUE THREAD

**Issue by eachirei** [graphite-project/graphite-web#2251]
What you attempted: Query with from=1517443200 until=1519862399 and hitcount interval 2419199s(the difference)
Expected Result: A single datapoint/bucket
Witnessed Result: No datapoints
System Details
OS / Version: Docker container from ubuntu:14.04
Python Version: 2.7.6
Django Version: 1.11.10
Graphite Component Versions: 1.1.2

https://github.com/graphite-project/graphite-web/blob/7ac45869a0f23fcb056b702a3c0aac8e5b0ff3f0/webapp/graphite/render/functions.py#L4851

I'm not very experienced with python, but as I read, the `//` operator is used for integer division.
I think it should be replaced with the `/` floating division operator.

Also, curiously enough, I tested with the at time format from=00:00_20180201 until=23:59_20180228 and it worked just fine; although after replacing the operator, the at time format returned 2 buckets (as expected, since the at format doesn't include seconds, as far as I know,  so` from - until` exceeds the interval).

Still, I do not understand how the timestamps are parsed and why `series.end - series.start` was less than the interval, even if in my query the hitcount interval is computed as ` from - until`.

**Comment by DanCech** [comment]
Yes, it looks like regular division should be used there.
