### ISSUE TITLE
querying system on top of web service

### ISSUE THREAD

**Issue by pinkynrg** [graphite-project/graphite-web#2255]
Is there a reason why the only way to query the Whisper database is using the  graphite web application?

Before digging into this project, i imagined it to be on top of a "query engine" **well separated from the Web service**. 

In order to use the graphite querying system I need to have the whole web package (DJANGO + some other stuff). What if someone wants to query Whisper only locally? Why the need to have a whole web application and not only a service that responds to the queries? I imagine something the user can use with a linux terminal like:

```bash
User@MyComputer: graphite 
> this.is.one.of.my.metrics.0
{ [[1488931200,2.2],[1489017600,3.4]] ... }
> sumSeries(this.is.one.of.my.metrics.*)
{ [[1488931200,7.1],[1489017600,nil]] ... }
```

I see that there are third parties forks of only the core functions (like graphite-api), but I'm wondering why it hasn't been made official yet.

**Comment by deniszh** [comment]
Yes, that was an idea behind `graphite-api`, indeed. But nowadays `graphite-api` become so diverted from rest of the code, so, it's almost impossible to do anything with that.
I do not think that having local API is a good idea - everybody is doing REST or gRPC nowadays.
It's possible to create something like `graphite-api` - rendering core, and convert current dashboard and web interface code to clients of that API - bit scope of this task is quite big, that's "scheduled" for graphite 2.0 or something.

**Comment by piotr1212** [comment]
`graphite-api` is a webservice too which also does rendering. You can use `whisper-fetch` to query whisper files locally.

It could be improved, I think the carbonlink protocol could be extended. But that would introduce some challenges (globbing of metricnames and determining which cache to query).  Just nobody had time to do this, pr's are welcome.
