### ISSUE TITLE
noNullPoints and maxDataPoints shouldn't be exclusive

### ISSUE THREAD

**Issue by scrwr** [graphite-project/graphite-web#2256]
In order to keep data traffic low and to visualize Event like data points (rarely occuring) one would like to retrieve only datapoints with non-Null values. Therefore noNullPoints is available. However in order to limit amount of still responded DataPoints (larger timeframes), one would like to use maxDataPoints as well. But this is not possible, as "webapp/graphite/render/views.py" uses elif to differentiate between the cases and prefers maxDataPoints. 

My expectation would be, that noNullPoints removes null entries from the resultset, independent on whether it was compacted via maxDataPoints before or not.

**Comment by deniszh** [comment]
I can be wrong, but I'm suspecting that maxDataPoints removes Null values when doing any consolidation  - https://github.com/graphite-project/graphite-web/blob/e83977bfa40fb13e226a54031704f814693501cc/webapp/graphite/readers/utils.py#L39-L53
but probably `noNullPoints` can remove nulls if `maxDataPoints` >= `numberOfDataPoints`...

**Comment by scrwr** [comment]
Its not removing it:

```
curl 'https://grafana/api/datasources/proxy/1/render' 
-H 'Cookie: grafana_user=...; grafana_sess=...' 
--data 'target=...&from=-5min&until=-1min&format=json&maxDataPoints=1&noNullPoints=True'

[{"target": "....", "datapoints": [[null, 1520508480]]}, {"target": "....", "datapoints": [[null, 1520508480]]}, {"target": "....", "datapoints": [[null, 1520508480]]},...
```
but:

```
curl 'https://grafana/api/datasources/proxy/1/render' 
-H 'Cookie: grafana_user=...; grafana_sess=...' 
--data 'target=...&from=-5min&until=-1min&format=json&noNullPoints=True' 

[{"target": "...", "datapoints": [[1.0, 1520508720]]}, {"target": "...", "datapoints": [[1.0, 1520508600]]}, {"target": "...", "datapoints": [[1.0, 1520508600]]}, {"target": "...", "datapoints": [[1.0, 1520508660]]}]
```

**Comment by DanCech** [comment]
I had the same thought, it should be a relatively small refactor in the render code.
