### ISSUE TITLE
missing static location for nginx-uwsgi in documentation

### ISSUE THREAD

**Issue by bitfur** [graphite-project/graphite-web#2260]
Hello,
In the document describing setting up nginx-uwsgi:
http://graphite.readthedocs.io/en/latest/config-webapp.html#nginx-uwsgi

the static content configuration is missing. This works:
```
server {
    listen 80;
    location /static/ {
        alias /opt/graphite/webapp/content/;
    }

    location / {
        include uwsgi_params;
        uwsgi_pass localhost:8080;
    }
}
```

**Comment by deniszh** [comment]
Well, uwsgi config is just a stab, compare it to for example config for gunicorn from same link.
It can be extended, of course, and documentation is in the same repo btw - https://github.com/graphite-project/graphite-web/blob/master/docs/config-webapp.rst

**Comment by bitfur** [comment]
Great!
