### ISSUE TITLE
archive 0 does not have data

### ISSUE THREAD

**Issue by littlejiangyuan** [graphite-project/graphite-web#2261]
I had configured like this:
**storage-schemas.conf:**
retentions = 1:60,60:60d

**storage-aggregation.conf:**
  [default_average]
    pattern = .*
    xFilesFactor = 0.5
    aggregationMethod = average

using the command **whisper-dump.py sm_idx-idx.wsp** and the result is 

Meta data:
  aggregation method: average 
  max retention: 5184000 
  xFilesFactor: 0.5

Archive 0 info: 
  offset: 40
  seconds per point: 1
  points: 60
  retention: 60
  size: 720

Archive 1 info: 
  offset: 760
  seconds per point: 60
  points: 86400
  retention: 5184000 
  size: 1036800 

Archive 0 data: 
0: 0,          0       
1: 0,          0       
2: 0,          0       
3: 0,          0       
4: 0,          0       
5: 0,          0       
6: 0,          0       
7: 0,          0       
8: 0,          0       
9: 0,          0       
10: 0,          0       
11: 0,          0       
12: 0,          0       
13: 0,          0       
14: 0,          0
15: 0,          0
16: 0,          0
17: 0,          0
18: 0,          0
19: 0,          0
20: 0,          0
21: 0,          0
22: 0,          0
23: 0,          0
24: 0,          0
25: 0,          0
26: 0,          0
27: 0,          0
 ......

Archive 1 data:
0: 1521097320,          2
1: 1521097380,          1
2: 1521097440,          1
3: 1521097500,          1
4: 1521097560,          4
5: 1521097620,          1
6: 1521097680,          1
7: 1521097740,          4
8: 1521097800,          2
9: 1521097860,         19
10: 1521097920,          1
11: 1521097980,          1
12: 1521098040,          1
13: 1521098100,          2  
14: 1521098160,          2  
......

I am doubt that why Archive 0 does not have data and Archive 1 has data. it  really confuse me.thanks for help.

**Comment by deniszh** [comment]
You have retention 1s with 60 points in archive 0, but sending data every 60 seconds - so, it goes to 2nd archive directly. Works as designed, IMO.
