### ISSUE TITLE
No metrics visible with the latest docker image

### ISSUE THREAD

**Issue by Tushar1983** [graphite-project/graphite-web#2265]
Hi,
I just installed Docker 18.03.0-ce-win59 on my Windows 10 laptop.
And then installed grahite image using:
docker run -d --name graphite --restart=always -v D:\graphiteData:/opt/graphite/storage -p 80:80 -p 2003-2004:2003-2004 -p 2023-2024:2023-2024 -p 8125:8125/udp -p 8126:8126 graphiteapp/graphite-statsd

Now, when I open the web app, I am not able to see any metrics. not even Carbon or Statsd metrics.
Haven't done any configuration changes yet.
running on all default configurations.
-Tushar

![image](https://user-images.githubusercontent.com/31681818/37949411-270f9868-31b2-11e8-8b26-ecd899c34b13.png)

![image](https://user-images.githubusercontent.com/31681818/37949447-5667d62a-31b2-11e8-9db7-cb08c4d0cc31.png)

**Comment by deniszh** [comment]
@Tushar1983,
I think this issue should belong to https://github.com/graphite-project/docker-graphite-statsd repo, but OK.
That's a known issue, probably should be fixed. If you mount the empty directory as storage Graphite creates all data there, but then its need to be restarted to pick up changes. For now, it's better to restart container or create whisper directory and `graphite.db` in advance.

**Comment by Tushar1983** [comment]
@deniszh Thanks! That resolved the issue for me.
