### ISSUE TITLE
graphite-web blank after upgrade from 0.9.15 to 1.0.2

### ISSUE THREAD

**Issue by rgeniesse** [graphite-project/graphite-web#2268]
**What you attempted**: I attempted to upgrade Graphite components from 0.9.15 to 1.0.2
**Expected Result**: graphite web interface would continue to function normally.
**Witnessed Result**: graphite web interface is reachable but the home page body is blank.
**System Details**
**OS / Version**: Centos 7.2.1511
**Python Version**: 2.7.5
**Django Version** (a frequent cause of issues): 1.8.18 (used as I had even more issues with 1.9. release notes said it is supported http://graphite.readthedocs.io/en/latest/releases/1_0_2.html
**Graphite Component Versions**:
carbon==1.0.2
graphite-web==1.0.2
whisper==1.0.2

Things tried: Cleared browser cache, tried Firefox and Chrome, tried 1.1.2. Same issue. I don't see any errors in graphite-web-error.log.

If I revert back to 0.9.15, the web interface works fine. For my graphite.db upgrade I have to use:
`PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings` 

Using the `--run-syncdb` flag gives out:
`django-admin.py migrate: error: unrecognized arguments: --run-syncdb`

Whisper and Carbon appear to be functioning normally.

I do use the puppet-graphite forge module to do the configuration, but not sure where else to look without any errors. Thanks!

**Comment by rgeniesse** [comment]
In order: Events screen, Dashboard Screen, and Home Page

<img width="1440" alt="screen shot 2018-03-28 at 10 11 58 pm" src="https://user-images.githubusercontent.com/19964713/38071243-1824a298-32d5-11e8-8025-808cd9377192.png">
<img width="1433" alt="screen shot 2018-03-28 at 10 11 49 pm" src="https://user-images.githubusercontent.com/19964713/38071245-1843be26-32d5-11e8-8b87-10c44c21e478.png">
<img width="1431" alt="screen shot 2018-03-28 at 10 11 41 pm" src="https://user-images.githubusercontent.com/19964713/38071246-185ae7a4-32d5-11e8-8187-bc362b259af8.png">

**Comment by 6d6178** [comment]
Have you created the static content? Alternatively use Python Whitenoise (see examples/example-graphite-vhost.conf)

`PYTHONPATH=/opt/graphite/webapp/ /usr/lib/python2.7/site-packages/django/bin/django-admin.py collectstatic --noinput --settings=graphite.settings `

The folder /opt/graphite/static has to be accessible by apache.

**Comment by rgeniesse** [comment]
Thank you! I attempted the command, but it didn't work. Ensured permissions were proper on `/opt/graphite/static` for apache to read it. Suspect a config option somewhere isn't set properly to tell Apache to look there.

I ran `pip install whitenoise` based on a comment in `example-graphite-vhost.conf` and now the webpage loads as expected. Appreciate it!

**Comment by 6d6178** [comment]
Just out of interest, is `PYTHONPATH=/opt/graphite/webapp django-admin.py collectstatic --noinput --settings=graphite.settings`?
The command I gave to you specified the location of django to where it would be, if installed with pip. As you used the `django-admin.py` in your question succesfully, it probably will work without a location.

**Comment by rgeniesse** [comment]
Yes, `PYTHONPATH=/opt/graphite/webapp django-admin.py collectstatic --noinput --settings=graphite.settings` works just the same as the one you provided. Creates and populates a folder called `static` in `/opt/graphite`.
