### ISSUE TITLE
from-until selection discrepancy existing series vs generated series

### ISSUE THREAD

**Issue by pinkynrg** [graphite-project/graphite-web#2269]
Considering the following query using a generated timeWalk series with granularity 5 minutes from February 1st to Match 1st:

```
http://graphite.faccousa.net/render?from=00:00_20180201&until=00:00_20180301&format=json&target[]=randomWalk('generated.sieres',300)
```
i get the following output:

```
[{"datapoints": [[0, 1517464800], [-0.2626011173480486, 1517464860], [-0.2215472735869829, 1517464920] ... ] ... }
```

in this case the first timestamp `1517464800` which is `2018-02-01 00:00:00`.

now let's consider  an actual existing metric with granularity 5 minutes, same time range as above:

```
http://graphite.faccousa.net/render?from=00:00_20180201&until=00:00_20180301&format=json&target[]=test.series.0
```

i get the following output:

```
[{"datapoints": [[null, 1517465100], [null, 1517465400], [null, 1517465700], ... ], ... }
```

The first timestamp is `1517465100` which is `2018-02-01 00:05:00` is not what i thought I would get (2018-02-01 00:00:00). 

Is there a reason why the query doesn't include the midnight point in the first case?

**Comment by pinkynrg** [comment]
I can definitely check the code, all I'm asking is if there is a valid and known reason for this to be designed this way.

**Comment by deniszh** [comment]
I'm not aware of any reasoning, looks like it's just "because of historical reasons".

**Comment by MatthewFin** [comment]
Is this setting at all configurable? It seems to be the case that existing metric queries includes the until param but excludes the from param. 

I think that both ends of the from/until query should be inclusive, or at least configurable.

**Comment by piotr1212** [comment]
Think this is a duplicate https://github.com/graphite-project/whisper/issues/230
