### ISSUE TITLE
documentation patch for configuring, administering and using the web app

### ISSUE THREAD

**Issue by mleinart** [graphite-project/graphite-web#227]
#### Imported from https://bugs.launchpad.net/bugs/1061328

|  |  |
| --- | --- |
| Reported by | [atsaloli-tech](https://launchpad.net/~atsaloli-tech) |
| Date Created | Oct 04, 2012 |

hello.  i was merrily working my way through the Graphite 
docs while installing Graphite for first time, when I hit
some white spots in the fine manual.

There are 3 sections missing under Post Install Tasks:

Configuring The Webapp
https://graphite.readthedocs.org/en/latest/config-webapp.html

Administering The Webapp
https://graphite.readthedocs.org/en/latest/admin-webapp.html

Using the Composer
https://graphite.readthedocs.org/en/latest/composer.html

mleinart on IRC gave me enough clues to get Graphite up and 
running and able to take in and display data

I'd like to offer these clues as a patch to the existing 
documentation, please.

"Configuring the Webapp"

The config file is documented in comments.

Make sure you create a storage-aggregation.conf file
to be able to feed data into Graphite and have it show
up in the Composer automatically:

   cp storage-aggregation.conf.example storage-aggregation.conf 

"Administering The Webapp"

To get the web front end up and running, there is an excellent screencast by Jason Dixon on installing Graphite from source, which includes how to configure Graphite and start the Web front end.

http://obfuscurity.com/2012/08/Screencast---Installing-Graphite-from-Source

Jason's screencast assumes you have mod_wsgi installed.  If you don't, we recommend
http://www.danielscottlawrence.com/configuring-mod_wsgi-for-use-with-graphite-web/

Note: on Ubuntu 10.04,  I had to modify 
/etc/apache2/mods-enabled/wsgi.load to add "/usr/lib/apache2/" to the module path
in order to get the httpd to start, otherwise httpd could not find modwsgi.so

Once the Web front end is up and running, administering the webapp is mostly 
Django-specific stuff - go to the Django admin url (/admin/) and continue from there.

"Using the Composer"

Your graphs should automatically appear in the pull down menu in the top left pane of the composer, under "Graphite".
For example, if you feed Graphite random dice rolls using the statistic name "local.random.diceroll", navigate to
Graphite -> random -> diceroll to see the graph for this statistic.

I make this little script, and call it from cron every minute, to generate random data to put on your first graph:

/root/mkdata.sh
--cut here--
# !/bin/sh

echo "local.random.diceroll `perl -e 'print int(rand(6)), "\n"'` `date +%s`" | nc localhost 2003
# 

--cut here--

I suggest a fourth section, "Troubleshooting":

Check /opt/graphite/storage/log/carbon-cache/carbon-cache-a/console.log

**Comment by ryan-williams** [comment]
any updates here? I've been getting quite lost in the various/incomplete pieces of graphite documentation I've found around the web; I've still not successfully run graphite locally after a few days of trying.

**Comment by obfuscurity** [comment]
@ryan-williams This isn't doesn't address the documentation issue, but you might consider https://github.com/obfuscurity/synthesize if you just want to run Graphite locally and learn how the pieces work together. There's a Vagrantfile or you can one-click install to DigitalOcean from the project page.

**Comment by ryan-williams** [comment]
thanks @obfuscurity, that DO recipe worked like a charm.

Can that be added somewhere where newcomers might see it?

Is there a minimal set of commands that would let me run Graphite from source? `bin/carbon-cache.py start` from a `carbon` checkout seems like it would be a member of such a set (and is not documented in the [carbon README.md](https://github.com/graphite-project/carbon)); what command starts the web server? Is there a whisper command that needs to be run as well?

**Comment by obfuscurity** [comment]
Glad to hear that helped out. It actually is mentioned in the official docs now:

http://graphite.readthedocs.org/en/latest/install-synthesize.html
http://graphite.readthedocs.org/en/0.9.x/install-synthesize.html

If you want to run from source, check out the contents of Synthesize's install script or follow the instructions in http://graphite.readthedocs.org/en/latest/install-source.html#installing-in-the-default-location.

**Comment by ryan-williams** [comment]
thanks, I tried to work through the readthedocs site but got to the blank pages around starting up the web server documented in this issue: http://graphite.readthedocs.org/en/latest/admin-webapp.html

**Comment by ryan-williams** [comment]
I've not found any documentation about how to start the web server on this repo, wikidot, readthedocs, or elsewhere on the internet

**Comment by obfuscurity** [comment]
https://github.com/graphite-project/graphite-project.github.io/issues

**Comment by obfuscurity** [comment]
> I've not found any documentation about how to start the web server on this repo, wikidot, readthedocs, or elsewhere on the internet

Yes, that's exactly why this issue was opened in the first place. :smile_cat:

**Comment by ryan-williams** [comment]
Is the link to https://github.com/graphite-project/graphite-project.github.io/issues meant to suggest that it is the place where one should file issues with the readthedocs site?

**Comment by obfuscurity** [comment]
It's meant to convey that many, if not all, of the issues you've brought up here (and in the other issue) are already listed in one or more issues in that repo.

**Comment by ryan-williams** [comment]
Cool, yea I was confused by that repo because I did not see the activity in the issues; it has no commits in >2yrs and a title link to a nonexistent page. 

Is "the new site" that you've referenced a few times the existing-but-incomplete http://graphite.readthedocs.org/en/latest/, or is it a newer site that will live at http://graphite-project.github.io/?
