### ISSUE TITLE
Unexpected timestamps are received

### ISSUE THREAD

**Issue by TaeWoo21** [graphite-project/graphite-web#2280]
I ran the 'Put data code' below and saved data into the Graphite running on the Docker.
And I didn't touch any other configurations.
The problem is when I query, I get the right value but with different timestamp.

I should have gotten the result of **"(1423594000, 123), (1423594200, 456)"**.
But I got **"(1423593600, 123), (1423594200, 456)"** or **"(1423593600, 123), (1423595400, 456)"**

I think this problem is related to the Series step.
Can I change the series step for the return value of a query?
Could this situation be resolved?

### 1. Put data code

<pre>import pickle
import requests
import struct
import socket

test_data_tuple_list = [('test_metric9', (1423594000, 123)), ('test_metric9', (1423594200, 456))]

payload = pickle.dumps(test_data_tuple_list, protocol = 2)

header = struct.pack("!L", len(payload))
message = header + payload

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('localhost', 2004))
s.send(message)</pre>
 
### 2. Query data code

<pre>import requests
import json

start = "1423593000"
end = "1423595000"

#l = 'http://localhost:80/metrics?query=*'
url_1 = 'http://localhost:80/render?target=test_metric9&from='+ start +'&until='+ end +'&format=json'
url_2 = 'http://localhost:80/render?target=test_metric9&from='+ start +'&until='+ end +'&format=raw'

res_1 = requests.get(url_1)
res_2 = requests.get(url_2)

print "[Query period] %s ~ %s" % (start, end)
print "[json data] " + json.dumps(json.loads(res_1.content), ensure_ascii=False, indent=4)
print "[raw data] " + res_2.content</pre>

### Query result
<pre>[Query period] 1423593000 ~ 1423595000
[json data] [
    {
        "tags": {
            "name": "test_metric9"
        }, 
        "target": "test_metric9", 
        "datapoints": [
            [
                123.0, 
                1423593600
            ], 
            [
                456.0, 
                1423594200
            ], 
            [
                null, 
                1423594800
            ]
        ]
    }
]
[raw data] test_metric9,1423593600,1423595400,600|123.0,456.0,None</pre>

**Comment by deniszh** [comment]
1423594000 is Tuesday, February 10, 2015 6:46:40 PM GMT, so, long time in the past. Default graphite from Docker have following schema - https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/opt/graphite/conf/storage-schemas.conf#L26:21
```
retentions = 10s:6h,1m:6d,10m:1800d
```
So, data which is 3 years old will go directly to 3rd archive - `10m:1800d`, which have resolution 10 minutes. That's why your timestamps will be changed.

Also, usually Graphite line protocol is much easier to handle then pickle and it's also have same speed - so, it's recommended to use it and not pickle.

**Comment by TaeWoo21** [comment]
Thank you for your reply @deniszh

Now I understand why the results were returned.

I really appreciate it! :-)

**Comment by TaeWoo21** [comment]
Thank you for your reply @deniszh

Now I understand why the results were returned.

I really appreciate it! :-)
