### ISSUE TITLE
/docs/config-webapp.rst

### ISSUE THREAD

**Issue by vvlier** [graphite-project/graphite-web#2283]
WSGIImportScript /opt/graphite/conf/graphite.wsgi process-group=graphite-api application-group=%{GLOBAL}
should be 
WSGIImportScript /opt/graphite/conf/graphite.wsgi process-group=graphite-web application-group=%{GLOBAL}

**Comment by deniszh** [comment]
Fixed in https://github.com/graphite-project/graphite-web/pull/2284
Thanks!
