### ISSUE TITLE
web has special character

### ISSUE THREAD

**Issue by keyboardfann** [graphite-project/graphite-web#2287]
Hi,
  Does anyone meet the issue, the x and y label become special character.
![image](https://user-images.githubusercontent.com/1110451/39858026-e8a405a4-5467-11e8-8f54-6af83e9574f0.png)

ENV:
RHEL 7

Python Version:
Python 2.7.5

Graphite Version:
0.9.15

PIP list:
ansible (2.0.1.0)
asn1crypto (0.22.0)
attrs (17.2.0)
Babel (0.9.6)
backports.ssl-match-hostname (3.4.0.2)
cairocffi (0.8.0)
certifi (2018.1.18)
cffi (1.11.5)
chardet (3.0.4)
common (0.1.2)
configobj (4.7.2)
constantly (15.1.0)
constants (0.6.0)
cryptography (2.2.2)
decorator (3.4.0)
Django (1.6.11)
django-tagging (0.3.6)
ecdsa (0.13)
enum34 (1.1.6)
ethtool (0.8)
httplib2 (0.7.7)
idna (2.6)
incremental (17.5.0)
iniparse (0.4)
ipaddress (1.0.22)
Jinja2 (2.7.2)
lxml (3.2.1)
M2Crypto (0.21.1)
MarkupSafe (0.11)
MySQL-python (1.2.5)
paramiko (1.15.1)
pciutils (1.7.3)
perf (0.1)
pip (8.1.2)
ply (3.4)
pyasn1 (0.1.6)
pyasn1-modules (0.0.9)
pycairo (1.17.0)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.19.0)
pygobject (3.14.0)
pygpgme (0.3)
pyhash (0.8.2)
pyliblzma (0.5.3)
pyOpenSSL (0.13.1)
python-dateutil (1.5)
python-dmidecode (3.10.13)
python-keyczar (0.71rc0)
python-ldap (3.0.0)
python-memcached (1.59)
pytz (2016.10)
pyudev (0.15)
pyxattr (0.5.1)
PyYAML (3.10)
rhnlib (2.5.65)
rhsm (1.15.4)
service-identity (17.0.0)
setuptools (0.9.8)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
tagging (0.2.1)
Twisted (16.5.0)
txAMQP (0.8.2)
urlgrabber (3.10)
whisper (0.9.15)
yum-metadata-parser (1.1.4)
zope.interface (4.5.0)

**Comment by piotr1212** [comment]
Try: `yum install dejavu-sans-fonts dejavu-serif-fonts`

**Comment by keyboardfann** [comment]
Hi @piotr1212 ,
    Thank you very much and it works. It's wierd that I install graphite-web before and don't install dejavu-sans-fonts dejavu-serif-fonts still works normal. Is it because new version library use it?

Fann

**Comment by keyboardfann** [comment]
HI @piotr1212 ,
    Maybe, It's fine. After installing the package and resolve the issue. Thank you again.

Fann
