### ISSUE TITLE
1.1.3 changes node case sensitive silently

### ISSUE THREAD

**Issue by Kenterfie** [graphite-project/graphite-web#2288]
I have deployed the new version on one of my nodes and some graphs stopped working. After investigating the issue i found, that 1.1.3 is now case sensitive. Why no word of this in the changelog and is this changed wanted?

**Comment by deniszh** [comment]
TBH I was thinking that Graphite always was case-sensitive, at least on case-sensitive filesystems.
I just tested oldest version in docker repo - 1.0.2 - it's case-sensitive as well.

**Comment by Kenterfie** [comment]
Very strange. I noticed it since 1.1.3 and havn't changed anything else. Possible a config default change to force it?

**Comment by piotr1212** [comment]
With "node case sensitive", do you mean the names of the servers in DESTINATIONS in consistent hashing  or the names of the metrics?

**Comment by Kenterfie** [comment]
Names of metricts like "root.yxz.count". Before i changed it i could write "root.yxz.Count" and also "root.yxz.count" both with the same result.
