### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by marcelfischer** [graphite-project/graphite-web#2289]
Hey,

we are using the following call:
curl -u yyy:xxx-i "http://graphite-server/render?target=summarize(keepLastValue(icinga2.icingaclient.host.icmp.perfdata.rta.value),"3minutes",'avg',true)&from=-1h&until=now&format=csv"

And we always get:
Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/views.py&quot;, line 123, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&quot;, line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&quot;, line 31, in evaluateTokens
    return func(requestContext, *args)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/functions.py&quot;, line 2556, in summarize
    bucketInterval = int((timestamp - series.start) / interval)
ZeroDivisionError: integer division or modulo by zero

Its seems that there is a relation to the summarize function.

We are using graphite 0.9.16

Thanks
Marcel

**Comment by deniszh** [comment]
what's your metric interval?

**Comment by marcelfischer** [comment]
One Minute

**Comment by deniszh** [comment]
Ah, got it. Graphite is not accepting "3minutes" as valid interval - https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/attime.py#L159-L167
Try to use "3min" or just 180

**Comment by deniszh** [comment]
That's very strange. Code is very simple here:
1. "integer division or modulo by zero" means that `interval` variable is zero - https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/functions.py#L2555-L2558
2. `interval = delta.seconds + (delta.days * 86400)`, so `delta` should be zero - https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/functions.py#L2546
3. `delta = parseTimeOffset(intervalString)` - https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/functions.py#L2545:3
4. ```
>>> parseTimeOffset("3minutes")
datetime.timedelta(0, 180)
>>> parseTimeOffset("3min")
datetime.timedelta(0, 180)
```
Even "3minutes" should work. 
I'm confused. 😕

**Comment by deniszh** [comment]
You can use Query editor in Grafana to peek how it send request to Graphite btw.

**Comment by marcelfischer** [comment]
Hmm the query in Grafana is the same. In the meantime I think it has something to do with escaping or so. Because I changed to wget and it works...

**Comment by DanCech** [comment]
yes, since you're using `"` to enclose the entire url you need to use `'` around the values because otherwise bash interprets it as 3 strings concatenated together.

**Comment by marcelfischer** [comment]
You're right, thanks! I will close this one.
