### ISSUE TITLE
Graphite Tags Feature with PostgreSQL

### ISSUE THREAD

**Issue by suratovvlad** [graphite-project/graphite-web#2293]
Hi,

I'm using the PostgreSQL to save some data from Graphite webapp. 
The configuration clearly says: "Note that this database is only used to store Django models such as saved graphs, dashboards, user preferences, etc."
However, since 1.1.x version Graphite introduces the new feature for tagging metrics, and with the default configuration it uses the local storage (the PostgreSQL in my case). 

I should say that I was really impressed during test process of my configuration (about 10-20K metrics received per minute) - I've faced with serious perfomance issues (Graphite webapp didn't response), and it was caused by inifinite inseting from Graphite into the tags* tables from Postgres DB. I tried even to tune the PostgreSQL using [this page](https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server), but it didn't help.

I should notice I've found the solution. Thanks to you for the ability to use Redis as Tags database. It became much faster and responsable. However, I have several questions. 
Is it normal that I have such bottleneck between Graphite and Postgres?
Is there any recommendations for current configuration?
Also, I don't use the tags feature at all, is there any ways to disable it?

**Comment by suratovvlad** [comment]
@deniszh 
Thank you so much for the quick response and for the advices about disabling this feature!

**Comment by nook24** [comment]
@deniszh What happens to the tags of Redis crash or on a reboot of the system?

**Comment by DanCech** [comment]
If redis is configured without [persistence](https://redis.io/topics/persistence) then the tagdb will be reconstructed from metrics as they are received by carbon, though in that scenario any series that are no longer being sent will be inaccessible.  We recommend using persistence if storing the tagdb in redis.

**Comment by nook24** [comment]
Make sense thanks
