### ISSUE TITLE
User level access to graphite-web url (:8008)

### ISSUE THREAD

**Issue by surajbora007** [graphite-project/graphite-web#2296]
How to provide user level authentication to graphite-web url for viewing stats.
By default, any one can view stats from graphite-web url without any authentication.
For saving dashboard user needs to login. 
Please provide us way to provide user level authentication.

**Comment by deniszh** [comment]
Hello @surajbora007,
Currently, it's not possible to provide user-level authentication for Graphite. You can put some authentication e.g. to Apache, as described e.g. in https://serverfault.com/a/837031/104117, but it will be global - e.g. it's not possible to limit access to some metric subtree or something.

**Comment by surajbora007** [comment]
Is it possible to stop front end graphite-web if i have already configure grafana for viewing data collected in whisper.

**Comment by 6d6178** [comment]
This is not possible as Grafana is requesting from graphite-web.
The link @deniszh provided in his first response shows you how to add authentication to graphite-web which should work with Grafana if you provide the Credentials in the "Data Source". (Disclaimer: Haven't tried it myself)

You can look at https://github.com/graphite-project/graphite-web/blob/master/README.md for a diagram of the whole system system.

**Comment by deniszh** [comment]
@surajbora007 : You can bind graphite-web to localhost and install Graphana on same server. Or you can limit access to graphite-web (again, using Apache) to allow requests only from Grafana server.
Then you need to ssl or auth for graphite-web itself.

**Comment by surajbora007** [comment]
Thanks all for inputs.

**Comment by JessMarSoriano** [comment]
Is there any way that this will be supported in the next update/release?

**Comment by deniszh** [comment]
@JeKa0111 : unfortunately, no one is working or planning to work to implement this feature. The current workaround is still the same - use 3rd party dashboard tools (e.g. Grafana) for managing dashboards if you need more granular security policy. But please note that even that way will be no limitation for graphite metrics itself - only to dashboards.

**Comment by 6d6178** [comment]
@deniszh @JeKa0111 There is a way to use authentication to some extend. If you set the storage_dir to a subdir of the real storage_dir, you only have access to the whisper files in the subdir. This would require keeping the whisper files in a logical system, that puts all files for a user in one subdir. Or use several carbon-cache with different storage dir.
User-Access can be controlled by Apache utilities like .htaccess as graphite is a vhost.

I considered doing something like this but decided to keep a single carbon-cache (or rather three). After all it's like running serveral stacks on one server. And Grafana Viewers can't see anything they aren't supposed to.
