### ISSUE TITLE
graph composer does not prevent selecting fromTime >= untilTime

### ISSUE THREAD

**Issue by Dieterbe** [graphite-project/graphite-web#23]

**Comment by obfuscurity** [comment]
Closing this as a duplicate of #22. If this is not the case please elaborate. Thanks!

**Comment by Dieterbe** [comment]
#22 is about breakage when your from time is older than your retention. This ticket is about from time > until time, which is an invalid request that needs to be handled.

**Comment by obfuscurity** [comment]
Gotcha, thanks for clarifying.
