### ISSUE TITLE
Which character is valid in tag values

### ISSUE THREAD

**Issue by cyang16** [graphite-project/graphite-web#2305]
Do not found any document about the length limitation and which character could be used in the tag value.
And also no doc about limitation of the metric names and tag names.

Found a piece of code for validation https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/grammar.py#L89.
What kind of chars validation is applied for metric tag?
Is white space supported in the tag value?

It is good to have a document about it for long term supporting (as a standard), or at least a guideline.
I believe many special characters is well supported, but it is not guaranteed they will be well supported in the future.

**Comment by DanCech** [comment]
After getting feedback from users it seems like we should be a bit more prescriptive as far as what characters are supported.  Things like `'` cause problems when trying to query from Grafana, and values that start with ~ are a problem when querying.  The other thing I've been thinking about is support for escaping "special" characters.
