### ISSUE TITLE
Inconsistent display of metrics when using a different resolution

### ISSUE THREAD

**Issue by mwtzzz** [graphite-project/graphite-web#2306]
The following screenshot shows two metrics - a sum_all (the relay layer calculates this as an aggregate), and a sum.* (graphite-web renders this). The screenshot is looking at the past day until now. The two metrics match, as they should:

![screen shot 06-18-18 at 12 45 pm](https://user-images.githubusercontent.com/6799393/41558434-a7297378-72f5-11e8-982b-7827a0229fb7.PNG)

But if I change the time frame to "past two days until now" not only do the metrics no longer match, but the values are not consistent with the numbers in the first screenshot:

![screen shot 06-18-18 at 12 45 pm 001](https://user-images.githubusercontent.com/6799393/41558437-ab313938-72f5-11e8-96d1-316ba14439d1.PNG)

Any thoughts as to what's going on?

**Comment by mwtzzz** [comment]
Since the odd behavior seems to occur beyond a day, maybe it has something to do with my storage schema

[hosts]
pattern = \.sum\.[^\.]+$
retentions = 1m:1d,15m:10d

**Comment by DanCech** [comment]
Can you post your complete schema and aggregation config?

**Comment by mwtzzz** [comment]
@DanCech nvm, I figured it out. it's due to a mismatch in the retentions for "sum" (given above), compared to "sum_all" which has defaults to a different retention schedule.  Making them the same and resizing will fix this. .... Also if we display metrics with `scaleToSeconds` the two different metrics will match.
