### ISSUE TITLE
Feeding data without timestamp

### ISSUE THREAD

**Issue by danutvasc** [graphite-project/graphite-web#2308]
I am working on a IoT device from which I would like to export some data to Graphite but unfortunately it does not have a System Time synchronized with an NTP server.

I was looking for a way to add the timestamp of the Graphite server on each metric when it reaches the server but I couldn't find any option. Is there any option that can add the timestamp on metrics? or any other plugin than can gather data without timestamp, add it then send it to server? Can this be done?

Thank you!

**Comment by piotr1212** [comment]
You can use -1 as timestamp to have it generated at ingestion time.

**Comment by danutvasc** [comment]
Adding -1 as timestamp worked. Somehow I missed that part of documentation, but thank you.

**Comment by piotr1212** [comment]
> Adding -1 as timestamp worked. Somehow I missed that part of documentation, but thank you.

You didn't miss it, it just wasn't documented. ;)

**Comment by deniszh** [comment]
it's documented now
