### ISSUE TITLE
Cleaning up whisper files when tagging is used

### ISSUE THREAD

**Issue by andysworkshop** [graphite-project/graphite-web#2310]
Hi,

The common recommendation for cleaning up old metrics is to search for whisper files and delete those that haven't been touched for a site-defined period.

How does this work with tagging? When we take the decision to delete a whisper file based on age, can we also make some kind of call to graphite-web to delete the associated tags as well?

**Comment by DanCech** [comment]
The problem is that when using hashed filenames it is difficult to determine which entry in the tagdb corresponds to a given whisper file.  Right now the only option would be to go through each tagdb entry and check whether the corresponding whisper file is present and if not then remove the entry.

The `localdatabase` tagdb does store a hash which will correspond to the filename (it is used internally to work around an issue with unique index length in MySQL), but the series cannot currently be looked up or deleted by hash.  We could possibly add support for that, but we would need to also update the redis and http tagdb implementations to support it.

**Comment by andysworkshop** [comment]
For performance reasons we use redis for the tags having very quickly hit the limits of the SQL option. redis solved the performance problem but because redis is in-memory it cannot be allowed to grow forever.

I take it from your response that there's nothing in the `.wsp` file itself that links directly to the entries in tagdb that need to be deleted?

If our delete job on the one hand remembers all the `.wsp` filenames that it's deleted, and on the other hand can query for all keys and values in redis, is there a way to then correlate the two sets and issue delete commands to redis?

**Comment by andysworkshop** [comment]
OK, looks like I can code a usable workaround from that. Do you have a pointer to the code for calculating the hashed filename given the key in redis? Is it a 1:many mapping from a whisper file to keys in redis or 1:1?

Do you recommend using the http api for the delete (slower) or can I just go ahead and delete the key from redis directly (faster).

**Comment by DanCech** [comment]
The hashed filenames are calculated here:

https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/tags/utils.py#L69-L110

The process used to delete a series from redis is here:

https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/tags/redis.py#L242-L259

**Comment by andysworkshop** [comment]
We have now got cleanup jobs working with redis based on the above information.

**Comment by Quentin-M** [comment]
@andysworkshop It would be handy if you'd share the tooling you've been using to perform said cleanup task.

**Comment by andysworkshop** [comment]
> @andysworkshop It would be handy if you'd share with the community the tooling you've been using to perform said cleanup task.

I'd like to but unfortunately it was written for a corporate client and their policy doesn't allow that :(

**Comment by NotSqrt** [comment]
To find the location of the file from the metric name:
```python
import hashlib

metric = "some-metric;tag1=value2;tag2=value-2"
hashed = hashlib.sha256(metric.encode()).hexdigest()
filename = "whisper/_tagged/{}/{}/{}.wsp".format(hashed[:3], hashed[3:6], hashed)
print(filename)
```
