### ISSUE TITLE
Last data point value differs from others when maxDataPoints specified

### ISSUE THREAD

**Issue by zasca** [graphite-project/graphite-web#2311]
### Env
graphite 1.0.2
ubuntu 14.04

### What did I do?
Send request with the specified maxDataPoints:
```
http://127.0.0.1:8080/render/?target=aliasByNode(scale(scale(keepLastValue(Test.Stat.Money.cost), 1.18), 0.000001), -1)&from=-1d&format=json&maxDataPoints=1853
```
### What was the expected result?
```
[{"target": "cost", "datapoints": [[1681.76775734, 1530007050], ..., [1681.76775734, 1530093350], [1681.76775734, 1530093400]]}]
```
![grafana_bug1_2](https://user-images.githubusercontent.com/12932949/41971712-3491d45c-7a31-11e8-8eb6-9d387d8f474e.png)

### What happened instead?
Last data point value differs from others (sometimes only):
```
[{"target": "cost", "datapoints": [[1681.7677573400001, 1530007050], ..., [1681.7677573400001, 1530093350], [1681.76775734, 1530093400]]}]
```
![grafana_bug1](https://user-images.githubusercontent.com/12932949/41970277-02de9288-7a2c-11e8-9755-a4ff0b74d971.png)

But sometimes (less frequently) all looks good except of increasing of all values on 10^−13.

**Comment by DanCech** [comment]
What you're most likely seeing here is that when using `maxDataPoints` what happens is that the underlying points are divided up into groups and aggregated, but when reaching the end of the series the final grouping may not have the same number of points as the rest.

For example if you have a series with values `1,1,1,1,1,1,1` and ask for `maxDataPoints=4` and `consolidateBy('sum')` that will get broken up into `(1,1) (1,1) (1,1) (1)` and consolidate to `2,2,2,1`

If you want to avoid that you can add `|xFilesFactor(1)` to your query and you'll only get values for intervals that have enough points, so instead you'd get `2,2,2,null`

**Comment by piotr1212** [comment]
Are you sure this only happens with `maxDataPoints`? I've seen strange float rounding errors before which I couldn't reproduce. See also this one: https://github.com/graphite-project/graphite-web/issues/1124 (don't know if related).

**Comment by DanCech** [comment]
@piotr1212 yeah, floating point math is another potential source of excitement.  The only ways I know of to get around that would be to use https://docs.python.org/3.6/library/decimal.html (which would slow down all calculations compared to float), or to use the `round` function to truncate to the desired precision and discard any leftover floating point math artifacts.

Right now the math done in the `maxDataPoints` consolidation doesn't have any way to specify the desired precision, but that's something we could look into.

**Comment by zasca** [comment]
@DanCech, your explanation sounds good. Thank you.
But it seems this cannot be get around without an upgrade of graphite 1.0.2.

**Comment by zasca** [comment]
> See also this one: #1124 (don't know if related).

Not related

> If you want to avoid that you can add |xFilesFactor(1) to your query and you'll only get values for intervals that have enough points, so instead you'd get 2,2,2,null

Confirm, it work since 1.1.1 stable version.
