### ISSUE TITLE
Graphite encountered unexpected error while handling your request. Unable to see graphite dashboard

### ISSUE THREAD

**Issue by vinaykumarrao** [graphite-project/graphite-web#2312]
import cairocffi as cairo
ImportError: No module named cairocffi

Please assist so that metrics can be displayed using graphite datasource in grafana dashboard.
![response error](https://user-images.githubusercontent.com/40690932/42088713-047f0064-7b8a-11e8-9c7a-e9d95b4c0444.PNG)
![graphite error](https://user-images.githubusercontent.com/40690932/42088715-04c57e2c-7b8a-11e8-983f-40553e49dd8b.PNG)

**Comment by deniszh** [comment]
You need to install `cairocffi` python module. Which OS are you using and how exactly do you install graphite?

**Comment by vinaykumarrao** [comment]
Using RHEL 7.4 . Installed graphite using cephmetrics-ansible playbook.

**Comment by deniszh** [comment]
Easiest fix then - install `python-cairocffi` package from epel repo - https://centos.pkgs.org/7/epel-x86_64/python-cairocffi-0.5.4-1.el7.noarch.rpm.html
