### ISSUE TITLE
Fetch timing out for large queries on 1.1.2

### ISSUE THREAD

**Issue by JosephFY** [graphite-project/graphite-web#2313]
I am getting the bellow error when doing a large query in our new graphite instance
```
Traceback (most recent call last):
  File &quot;/usr/lib64/python2.7/site-packages/django/core/handlers/base.py&quot;, line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File &quot;/graphite/webapp/graphite/render/views.py&quot;, line 117, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File &quot;/graphite/webapp/graphite/render/evaluator.py&quot;, line 15, in evaluateTarget
    prefetchData(requestContext, pathExpressions)
  File &quot;/graphite/webapp/graphite/render/datalib.py&quot;, line 257, in prefetchData
    for result in STORE.fetch(pathExpressions, startTime, endTime, now, requestContext):
  File &quot;/graphite/webapp/graphite/storage.py&quot;, line 179, in fetch
    &#39;fetch for %s&#39; % str(patterns))
  File &quot;/graphite/webapp/graphite/storage.py&quot;, line 121, in wait_jobs
    raise Exception(message)
Exception: Timed out after 6.000316s for fetch for [u&#39;Devices.USA.*.*.*.*.*.*_device_status&#39;]

</pre>
</div>

</center>
```

This is only happening on 1.1.2 , I have another graphite instances running under 0.9.13 and I can run the query on without any issue, the query returns values for 8k+ metrics.

When eliminating the wildcards to get ~1000 metrics, the query runs smoothly 

tried to increase the ``` CARBONLINK_TIMEOUT ``` to 10 but no luck. 

Any ideas ?

**Comment by deniszh** [comment]
You need to increase fetch timeout instead. In latest Graphite variable named `FETCH_TIMEOUT` but probably in 1.1.2 it's still named `REMOTE_FETCH_TIMEOUT`.

**Comment by DanCech** [comment]
This is interesting work, it's been a while now but I seem to recall doing benchmarking at the time that didn't show anything like a 500x slowdown.  If you can share your benchmarking setup I'd be keen to see if we can figure out what's going on and whether there's a way to have the best of both worlds.

**Comment by JosephFY** [comment]
@deniszh changing that `FETCH_TIMEOUT` to 10 resolved the issue. I started by setting `USE_WORKER_POOL` to False based on #2192 and that solved initially it as well. Had it back to True based on @DanCech recommendations in #2192.

Appreciate the help guys. gonna go ahead and close this one. Issue has been resolved.
