### ISSUE TITLE
Carbon randomly dropping most of data for tcp and udp

### ISSUE THREAD

**Issue by xcycharles** [graphite-project/graphite-web#2315]
We just switched application to send udp packets instead of tcp packets to carbon via api. When sent tcp packets, carbon aggregator listener log is able to get all the tcp packets, but not all the wsp files in database got updated causing grafana  not showing all the data.
When application sent udp packets, i can see the "line" port 2023 got established and tcpdump gets the data on the receiving carbon box. However again carbon drops most of the data. It is more like dropping 99/100 of the data.

Changyang Xu(Charlie)
Thanks

**Comment by deniszh** [comment]
Sorry, I overlooked this question. If you running only single carbon instance then it's probably overloaded, try to add relay and multiple carbon instances (4-8).

**Comment by xcycharles** [comment]
Appreciated Deniszh! We are looking into how to make Carbon more scalable.

**Comment by piotr1212** [comment]
Yes, most likely overloaded carbon process, try running more processes as they don't do multiprocessing.

closing, feel free to reopen if your issue is not resolved.
