### ISSUE TITLE
Graphite doesnt show the metrics at 1s granularity 

### ISSUE THREAD

**Issue by rejkube** [graphite-project/graphite-web#2327]
A Setup with Graphite, whisper db when populated with 1s granular data  ;retention config  for 1s:30d [archive0]. whisper-fetch.py shows the data points recorded ,while the Graphite webapp and dashboard fails to show the metric itself !.The final level of the schema itself is not discovered by webapp .There are no issues for the same setup when fed with 1min granular-data or higher 
Is it that Graphite cant show 1 sec data points ? or Any fine tuning 1 missed ? 

> Django                       1.4.22 
> whisper                      0.9.13 

```
# whisper-fetch.py --from "1533102286" --until "1533102719" key.wsp 
1533102287	73.000000
1533102288	72.000000
1533102289	68.000000
1533102290	71.000000
1533102291	65.000000
1533102292	78.000000
1533102293	79.000000
1533102294	82.000000
1533102295	71.000000
1533102296	73.000000
1533102297	60.000000
1533102298	60.000000
1533102299	53.000000
1533102300	49.000000
1533102301	81.000000
1533102302	86.000000
1533102303	66.000000
1533102304	71.000000
1533102305	68.000000
1533102306	70.000000
1533102307	70.000000
1533102308	76.000000
1533102309	74.000000
1533102310	83.000000
1533102311	80.000000
1533102312	79.000000
1533102313	65.000000
1533102314	77.000000
1533102315	71.000000
1533102316	65.000000
1533102317	81.000000
1533102318	64.000000
1533102319	90.000000
1533102320	74.000000
1533102321	77.000000
1533102322	66.000000
1533102323	60.000000
1533102324	46.000000
1533102325	49.000000
1533102326	56.000000
1533102327	53.000000
1533102328	60.000000
1533102329	57.000000
# whisper-fetch.py --pretty key.wsp |tail
Wed Aug  1 00:55:00 2018	None
Wed Aug  1 00:55:01 2018	None
Wed Aug  1 00:55:02 2018	None
Wed Aug  1 00:55:03 2018	None
Wed Aug  1 00:55:04 2018	None
Wed Aug  1 00:55:05 2018	None
Wed Aug  1 00:55:06 2018	None
Wed Aug  1 00:55:07 2018	None
Wed Aug  1 00:55:08 2018	None
Wed Aug  1 00:55:09 2018	None
# whisper-info.py key.wsp
maxRetention: 2592000
xFilesFactor: 0.0
aggregationMethod: max
fileSize: 31104028

Archive 0
retention: 2592000
secondsPerPoint: 1
points: 2592000
size: 31104000
offset: 28


```

**Comment by rejkube** [comment]
there are values which are present [pls see the ones above]. The `key` itself is not getting detected in graphite-web. expected  `hostname->iops->disks->key`
all but `key` is displayed

**Comment by deniszh** [comment]
Sorry, I see only ‘Nones’ above, and no values. Or you see no metric at all?
Do you have directory named ‘key’ on same level as key.wsp ?

**Comment by rejkube** [comment]
yes there are values in the  `key.wsp` ;that file is inside `[disks]` directory as expected

**Comment by deniszh** [comment]
Sorry, not really understand what the problem here.
Graphite is working with 1s resolution, though.
Not also sure why your `whisper-fetch.py` giving a list of `None`s - are you sure that it really has data in timespan which you asking?
