### ISSUE TITLE
Graph Target incorrectly encoded with "&quot;" when saving to "My Graphs", renders graph unusable/broken

### ISSUE THREAD

**Issue by josiahbryan** [graphite-project/graphite-web#2334]
**What I attempted:**
I created my first graph, putting together a couple stats I'd dumped in, and saved it. The Graph Target items looked like this when I entered them:
`alias(summarize(scale(stats.ncs.dispatch.office.count,10),"1min"),"/office/*")`

I then saved it to My Graphs and closed the composer window, then double-clicked the graph from the tree view to view the saved graph.

**Expected Results**
I expected that when I clicked the graph in the tree view from the "My Graphs" tree that it would open a composer window again with a graph similar to what I had created (black background, some lines, etc)

**Witnessed Result**
Screenshot below:
![image](https://user-images.githubusercontent.com/4821548/44442407-03afbf80-a5a0-11e8-9cba-10e283c4df9f.png)

I boiled it down to the fact that the data ACTUALLY stored in the Graph Target section was this:
`alias(summarize(scale(stats.ncs.dispatch.office.count,10),&quot;1min&quot;),&quot;/office/*&quot;)`

Notice the `&quot` encodings? When I edited that string manually and put them back to regular quotes (e.g. `"`), the graph immediately rendered again. (Notice the "broken image" icon in the screenshot above where the graph should be.)

However, when I opened the graph again from the tree view, still the same result 

This is a show-stopper problem for our organization - if we can't save the graphs, it is a waste of time for us to spend time creating the Graph Targets to view our data over and over again.

**System Details**
This is just the basic docker image, NO customizations or changes done to it - at all. Installed exactly as shown on the github page for the docker image: [https://github.com/hopsoft/docker-graphite-statsd](https://github.com/hopsoft/docker-graphite-statsd)

The `/version` endpoint tells me it's running version `1.1.3`. No sure what the OS/Python/Django/pip versions that the docker image is running - if you need those, let me know, and we'll find a way to get them, I'm sure. 

Otherwise, tips on what I'm doing wrong if it's user error are greatly appreciated! Thanks!

**Comment by deniszh** [comment]
Yes, we have the similar issue - https://github.com/graphite-project/graphite-web/issues/1801
I was thinking that breaking only existing graphs, not the new...
Looks like this issue was introduced after https://github.com/graphite-project/graphite-web/pull/1662 and looks like #1662 not fixing all XSS issues anyway.
Currently, only one workaround exist - use some 3rd party dashboard, like Grafana, for saving graphs.
