### ISSUE TITLE
Unable to bring up graphite UI as expected. Dashboard showing "Drop to Merge".

### ISSUE THREAD

**Issue by dreddynarahari** [graphite-project/graphite-web#2351]
We are trying to bring up Graphite 1.1.3 on Debian 9 stretch node. I have installed all the dependencies that are provided in the documentation page. Using Python 2.7 and Django 1.8 . Using Apache2 2.4 and mod_wsgi for configuration. Let me know if am missing anything.

<img width="1300" alt="screen shot 2018-09-10 at 9 27 19 am" src="https://user-images.githubusercontent.com/25514565/45303668-f3726c80-b4db-11e8-9358-82b03f174809.png">

<img width="1300" alt="screen shot 2018-09-10 at 9 27 33 am" src="https://user-images.githubusercontent.com/25514565/45303648-e5bce700-b4db-11e8-86f7-24969e35943b.png">

We are using carbonzipper to connect to go-carbon.

Below are the configuration files:
 local_settings.py
`## Graphite local_settings.py

SECRET_KEY = '{{ graphite_web.secret_key }}'
ALLOWED_HOSTS = [ '*' ]
TIME_ZONE = 'America/Chicago'
DATE_FORMAT = '%m/%d'
DOCUMENTATION_URL = "http://graphite.readthedocs.io/"

LOG_ROTATION = True
LOG_ROTATION_COUNT = 1
LOG_RENDERING_PERFORMANCE = True
LOG_CACHE_PERFORMANCE = True

LOG_FILE_INFO = 'info.log'
LOG_FILE_EXCEPTION = 'exception.log'
LOG_FILE_CACHE = 'cache.log'
LOG_FILE_RENDERING = 'rendering.log'

DEFAULT_XFILES_FACTOR = 0
MAX_TAG_LENGTH = 100
AUTO_REFRESH_INTERVAL = 60
FIND_TIMEOUT = 10.0  # Timeout for metric find requests
FETCH_TIMEOUT = 10.0  # Timeout to fetch series data
GRAPHITE_ROOT = '/opt/graphite'
CONF_DIR = '/opt/graphite/conf'
STORAGE_DIR = '/opt/graphite/storage'
STATIC_ROOT = '/opt/graphite/static'
LOG_DIR = '/opt/graphite/webapp'
DATABASES = {
    'default': {
        'NAME': '{{graphite_web.db.dbname}}',
        'ENGINE': 'django.db.backends.{{graphite_web.db.backend}}',
        'USER': '{{graphite_web.db.user}}',
        'PASSWORD': '{{graphite_web.db.password}}',
        'HOST': '{{graphite_web.db.host}}',
        'PORT': '{{graphite_web.db.port}}'
    }
}
CLUSTER_SERVERS = ["0.0.0.0:8888"]
USE_WORKER_POOL = True
TAGDB = 'graphite.tags.localdatabase.LocalDatabaseTagDB'
`

graphite.conf
`
WSGISocketPrefix /etc/httpd/wsgi/
<VirtualHost *:80>
        ServerName graphite
        DocumentRoot "/opt/graphite/webapp"
        ErrorLog /opt/graphite/storage/log/webapp/error.log
        CustomLog /opt/graphite/storage/log/webapp/access.log common

        WSGIDaemonProcess graphite processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120    
        WSGIImportScript /opt/graphite/conf/graphite.wsgi process-group=graphite application-group=%{GLOBAL}
        WSGIScriptAlias / /opt/graphite/conf/graphite.wsgi process-group=graphite application-group=%{GLOBAL}

        Alias /content/ /opt/graphite/webapp/content/
        <Location "/content/">
                SetHandler None
                Require all granted
        </Location>
       
        Alias /media/ "@DJANGO_ROOT@/contrib/admin/media/"
        <Location "/media/">
                SetHandler None
                Require all granted
        </Location>
   
        <Directory /opt/graphite/conf/>
                Require all granted
        </Directory>
</VirtualHost>
`
Also created db using these commands:
`- name: django-admin.py - Sync/create database
  command: django-admin.py syncdb --noinput
  environment:
    DJANGO_SETTINGS_MODULE: graphite.settings
    PYTHONPATH: "{{ graphite_web.home }}/webapp/"
  become: yes
  when: result.stdout.find("AccountMygraph") == -1

- name: django-admin.py - Create superuser account
  command: >
    django-admin.py createsuperuser
    --username={{ graphite_admin_username }}
    --email={{ graphite_admin_email }}
    --is_superuser= True
    --is_staff= True
    --noinput
  environment:
    DJANGO_SETTINGS_MODULE: graphite.settings
    PYTHONPATH: "{{ graphite_web.home }}/webapp/"
  become: yes
  ignore_errors: "yes"
  register: superuser_created
  args:
    creates: "{{ graphite_web.home }}/webapp/graphite/.superuser_created"`

**Comment by deniszh** [comment]
You need to populate directory with static files and serve them using Apache.
Please check STATIC_ROOT  in https://graphite.readthedocs.io/en/latest/config-local-settings.html#filesystem-paths

**Comment by dreddynarahari** [comment]
Hi! I have populated the directory as you suggested. The UI still does not show up as expected.

**Comment by dreddynarahari** [comment]
@deniszh I missed to add 
`<Directory /opt/graphite/static/>
         Require all granted
  </Directory>` and it now worked. Thank you.

**Comment by dreddynarahari** [comment]
This is solved now. Closing out.

**Comment by kathpalamit** [comment]
where did you add <Directory /opt/graphite/static/> Require all granted </Directory>

**Comment by MakTaoPerf** [comment]
hey, I want to know "where did you add <Directory /opt/graphite/static/> Require all granted" too
@kathpalamit  @dreddynarahari

**Comment by geradsjo** [comment]
> hey, I want to know "where did you add <Directory /opt/graphite/static/> Require all granted" too
> @kathpalamit @dreddynarahari

I assume this is the apache site config file, e.g. for my system it is
/etc/apache2/sites-available/graphite-web.conf

btw. i could not start apache2 with that specific config... had to use the following:
`        <Directory /opt/graphite/static/>
                <IfVersion < 2.4>
                        Order deny,allow
                        Allow from all
                </IfVersion>
                <IfVersion >= 2.4>
                        Require all granted
                </IfVersion>
        </Directory>`
