### ISSUE TITLE
Error: Table 'graphite.tags_tag' doesn't exist

### ISSUE THREAD

**Issue by dreddynarahari** [graphite-project/graphite-web#2356]
We are using Graphite 1.1.3. I have difficulty using the tags API.

I am trying to view the tags:

curl -s "http://localhost:80/tags?pretty=1"
{
  "error": "(1146, \"Table 'graphite.tags_tag' doesn't exist\")"
}

Add tags:
curl -X POST "http://localhost:80/tags/tagSeries"   --data-urlencode 'path=cache.maxSize;server=ossgmsdataadc0101a;datacenter=adc01;region=rg'
Error:
{"error": "(1146, \"Table 'graphite.tags_series' doesn't exist\")"}

These are the tables created in mysql:
mysql> use graphite;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+----------------------------+
| Tables_in_graphite         |
+----------------------------+
| account_mygraph            |
| account_profile            |
| account_variable           |
| account_view               |
| account_window             |
| auth_group                 |
| auth_group_permissions     |
| auth_permission            |
| auth_user                  |
| auth_user_groups           |
| auth_user_user_permissions |
| dashboard_dashboard        |
| dashboard_dashboard_owners |
| django_admin_log           |
| django_content_type        |
| django_migrations          |
| django_session             |
| events_event               |
| tagging_tag                |
| tagging_taggeditem         |
| url_shortener_link         |
+----------------------------+

Please advice on this.

**Comment by DanCech** [comment]
It looks like you need to run the database migration to create those missing tables.  The exact command will depend on your django version.

**Comment by dreddynarahari** [comment]
@DanCech What is the command for Django 1.8. Currently I am running 
`django-admin.py migrate --noinput --settings=graphite.settings`

**Comment by DanCech** [comment]
That should work, what is the output you get?

The other method you could try would be to use the `manage.py` script bundled with graphite, run `./manage.py migrate`
