### ISSUE TITLE
Webapp as Master server, not sending request to Cluster nodes

### ISSUE THREAD

**Issue by caldavid** [graphite-project/graphite-web#2360]
Hi ,

I was working on the Graphite Clustering setup, trying to set one of the Webapp server as master API endpoint to query data from two carbon-cache nodes which behind one relay server, my config in local-settings.py is as following: 

CLUSTER-SERVERS = [ "node1_IP:80", "node2_IP:80"]

after spinning up the Master server,  i was unable querying any data, nothing returned back.

My two carbon nodes are running fine, data replication works fine as well, as matter of fact, not requests even go to two nodes at all.

Wondering what did miss ? ( I do see the following message in errors.log: "Could not import graphite.local_settings, using defaults!"

Thanks,
David

**Comment by DanCech** [comment]
you need to use an underscore, not a dash.  That will be (one of) the reason(s) that graphite-web can't load your local_settings.py file.

**Comment by caldavid** [comment]
Oh God, i spent half day just because of this underscore!

Thanks a lot!
David

**Comment by caldavid** [comment]
Sorry to shift topic a bit.

Do i need to provide any config in local_settings.py in order to make  "/tags" API call working on Master Webapp?  As of now i can view the __tagged folder on Master UI but when i do "/tags" API i only got local tag data returned.

Best,
David
