### ISSUE TITLE
Graphite Webapp Cluster Master, not supporting tag API ?

### ISSUE THREAD

**Issue by caldavid** [graphite-project/graphite-web#2361]
Hi,

I was setting up the Graphite Cluster with UseTags enabled, the master Graphite webapp with CLUSTER-SERVERS = [ "server1:80", "server2:80"] configured in the local_settings.py.

Do i need to provide any additional config in local_settings.py in order to make "/tags" API call working on Master Webapp? 

As of now,  i can only view the __tagged folder on Master UI,  but when i do "http://server_IP/tags" call only local tag data returned.

Your help is greatly appreciated!
David

**Comment by deniszh** [comment]
According to https://github.com/graphite-project/graphite-web/pull/2128 it should work out of the box. Right, @DanCech ?

**Comment by DanCech** [comment]
Currently the way it works is that the `/tags/autoComplete/tags` and `/tags/autoComplete/values` calls are fanned out across the cluster, but `/tags` and `/tags/:tag` are not.

**Comment by caldavid** [comment]
Thanks for the tips!

David
