### ISSUE TITLE
ImportError: No module named tagging

### ISSUE THREAD

**Issue by dreddynarahari** [graphite-project/graphite-web#2363]
Using Graphite 1.1.3 , Apache 2.24 , Python 2.7 on Debian 9 stretch machine.
I have django-tagging == 0.4.3 installed . I have the below wsgi error.

`mod_wsgi (pid=18358): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Wed Sep 26 11:13:14.661225 2018] [wsgi:error] [pid 18358:tid 139706922583232] Traceback (most recent call last):
[Wed Sep 26 11:13:14.661245 2018] [wsgi:error] [pid 18358:tid 139706922583232]   File "/opt/graphite/conf/graphite.wsgi", line 16, in <module>
[Wed Sep 26 11:13:14.661300 2018] [wsgi:error] [pid 18358:tid 139706922583232]     application = get_wsgi_application()
[Wed Sep 26 11:13:14.661313 2018] [wsgi:error] [pid 18358:tid 139706922583232]   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Wed Sep 26 11:13:14.661345 2018] [wsgi:error] [pid 18358:tid 139706922583232]     django.setup()
[Wed Sep 26 11:13:14.661355 2018] [wsgi:error] [pid 18358:tid 139706922583232]   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
[Wed Sep 26 11:13:14.661387 2018] [wsgi:error] [pid 18358:tid 139706922583232]     apps.populate(settings.INSTALLED_APPS)
[Wed Sep 26 11:13:14.661398 2018] [wsgi:error] [pid 18358:tid 139706922583232]   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
[Wed Sep 26 11:13:14.661508 2018] [wsgi:error] [pid 18358:tid 139706922583232]     app_config = AppConfig.create(entry)
[Wed Sep 26 11:13:14.661519 2018] [wsgi:error] [pid 18358:tid 139706922583232]   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
[Wed Sep 26 11:13:14.661590 2018] [wsgi:error] [pid 18358:tid 139706922583232]     module = import_module(entry)
[Wed Sep 26 11:13:14.661600 2018] [wsgi:error] [pid 18358:tid 139706922583232]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Wed Sep 26 11:13:14.661645 2018] [wsgi:error] [pid 18358:tid 139706922583232]     __import__(name)
[Wed Sep 26 11:13:14.661668 2018] [wsgi:error] [pid 18358:tid 139706922583232] ImportError: No module named tagging`

**Comment by deniszh** [comment]
Hello @dreddynarahari ,
Could you please describe your installation in detail -  
How do you install `django-tagging` module?
What's your Django version? How it's installed?

**Comment by dreddynarahari** [comment]
@deniszh Installed  Django (1.8), django-tagging (0.4.3)

This was installed using pip install command.

**Comment by deniszh** [comment]
Maybe you have more than one python installed and pip is not installing python modules on the same path where is Apache looking for it?

**Comment by dreddynarahari** [comment]
@deniszh We have only one version of Python installed .ie. Python=2.7

**Comment by deniszh** [comment]
Sorry, I'm out of ideas then. Something is broken with your python installation. Graphite-web should be still compatible with Django 1.8
