### ISSUE TITLE
Unable to see multiple metrics on the graph in graphite 1.1.3

### ISSUE THREAD

**Issue by dreddynarahari** [graphite-project/graphite-web#2364]
We are unable to see multiple metrics on a single graph in graphite 1.1.3. We have datapoints available for all metrics in whisper.
I am using the default settings in local_settings.py .  Except Cluster Servers pointing to carbonzipper.

`#  Cluster Configuration

CLUSTER_SERVERS = ["0.0.0.0:8888"]`

<img width="985" alt="screen shot 2018-09-27 at 11 47 35 am" src="https://user-images.githubusercontent.com/25514565/46161514-5dfd0980-c24b-11e8-8877-d825980d4111.png">

**Comment by piotr1212** [comment]
Do you got any info in the logs? Are the metrics in the wsp files or only in cache (check with whisper-dump,  whisper-fetch? What happens when you disable zipper (so that only metrics from disk are being read).

**Comment by dreddynarahari** [comment]
`2018-09-27,12:52:36.980 :: RemoteFinder[0.0.0.0:8888] Error response 500 from http://0.0.0.0:8888/render/?format=pickle&local=1&noCache=1&from=1538069856&until=1538070756&target=stg.mon.UP.rg.mon01.services.kafka.kafka_server.total_lag&now=1538070756
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/readers/remote.py", line 64, in fetch_multi
    timeout=settings.FETCH_TIMEOUT,
  File "/opt/graphite/webapp/graphite/finders/remote.py", line 273, in request
    raise Exception("Error response %d from %s" % (result.status, url_full))
Exception: Error response 500 from http://0.0.0.0:8888/render/?format=pickle&local=1&noCache=1&from=1538069856&until=1538070756&target=stg.mon.UP.rg.mon01.services.kafka.kafka_server.total_lag&now=1538070756
2018-09-27,12:52:36.980 :: Failed after 5 attempts! Root cause:
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/readers/remote.py", line 64, in fetch_multi
    timeout=settings.FETCH_TIMEOUT,
  File "/opt/graphite/webapp/graphite/finders/remote.py", line 273, in request
    raise Exception("Error response %d from %s" % (result.status, url_full))
Exception: Error response 500 from http://0.0.0.0:8888/render/?format=pickle&local=1&noCache=1&from=1538069856&until=1538070756&target=stg.mon.UP.rg.mon01.services.kafka.kafka_server.total_lag&now=1538070756
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/readers/remote.py", line 64, in fetch_multi
    timeout=settings.FETCH_TIMEOUT,
  File "/opt/graphite/webapp/graphite/finders/remote.py", line 273, in request
    raise Exception("Error response %d from %s" % (result.status, url_full))
Exception: Error response 500 from http://0.0.0.0:8888/render/?format=pickle&local=1&noCache=1&from=1538069856&until=1538070756&stg.mon.UP.rg.mon01.services.kafka.kafka_server.total_lag&now=1538070756
`
I see the above logs. The data is present in whisper when I try to use whisper-fetch.

**Comment by dreddynarahari** [comment]
`2018-09-27,12:52:33.904 :: Exception encountered in <GET http://10.141.16.117/render?format=json&from=-15min&until=now&target=asPercent(keepLastValue(stg.mon.UU.rg.mon01.servers.osscmrstg1.df-root.df_complex-used),sumSeries(keepLastValue(stg.mon.UU.rg.mon01.servers.osscmrstg1.df-root.df_complex-%7Bused,free,reserved%7D)))>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 117, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 28, in evaluateTarget
    result = evaluateTokens(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 57, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 93, in evaluateTokens
    return func(requestContext, *args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 913, in asPercent
    raise ValueError("asPercent second argument must be missing, a single digit, reference exactly 1 series or reference the same number of series as the first argument")
ValueError: asPercent second argument must be missing, a single digit, reference exactly 1 series or reference the same number of series as the first argument
`

**Comment by dreddynarahari** [comment]
Any ideas on how to fix this?

**Comment by DanCech** [comment]
The first log entry you posed indicates that the cluster server is returning a 500 (Internal Error) response code, you'll need to debug that, which you can do by trying to load the referenced url `http://0.0.0.0:8888/render/?format=pickle&local=1&noCache=1&from=1538069856&until=1538070756&target=stg.mon.UP.rg.mon01.services.kafka.kafka_server.total_lag&now=1538070756` and checking the logs on that host.

**Comment by deniszh** [comment]
@dreddynarahari : This is because https://github.com/go-graphite/carbonzipper/issues/72
The second error is also probably because of that.
Or rollback Graphite to 1.0.x or upgrade zipper to 1.0.x-alpha.
