### ISSUE TITLE
can graphite retrieving metrics from remote and local carbon-daemon

### ISSUE THREAD

**Issue by caldavid** [graphite-project/graphite-web#2365]
Hi !

I've been working on the graphite clustering recently, and i have tried the CLUSTER_SERVER config which used to collecting metrics from remote graphite hosts. 

However, i started wondering, instead of having a dedicated graphite-web host querying metrics from two carbon-daemons, can i host graphite web on local along with carbon-daemon running, and retrieve metrics not only just from local carbon-daemon but also remote graphite hosts(carbon-daemon running) to combine metrics and to present result?

That way i don't need to maintaining one extra graphite-web layer.

So, my question is, can i use CARBONLINK to listen on remote carbons? ( such as [111.111.111.000:7002 , 127.0.0.1:7002] ) Or, would there be any other way to achieve that?

Your help is greatly appreciated! 👍 

Best,
David

**Comment by deniszh** [comment]
Hello @caldavid,
Unfortunately, it will probably not work. Carbonlink was not designed as clustering protocol. But OTOH you don't need a dedicated rendering server, you can use only two graphite-web instances and point them to each other.

**Comment by caldavid** [comment]
Hi Deniszh,

Thanks for your reply.

That said, I could use CLUSTER_SERVER config to let two graphite-web servers talk to each other? Like this way?

CLUSTER_SERVERS=['127.0.0.1:80', 'xxx.xxx.xxx.xxx:80']

Best,
David

**Comment by deniszh** [comment]
Yes, indeed. You can probably remove local part completely, so, `CLUSTER_SERVERS=['xxx.xxx.xxx.xxx:80']` - local cluster should use carbonlink and direct access to whisper files.

**Comment by caldavid** [comment]
So the CLUSTER_SERVERS and CARBONLINK can be used together? I tried that, but didn't seem worked.

**Comment by deniszh** [comment]
CARBONLINK is for connecting graphite-web to carbon cache, usually localhost and port 700x.
CLUSTER_SERVERS is for clustering graphite-web instances, protocol is http - so they are not interchangeable but ofc can be used together.

**Comment by caldavid** [comment]
gotcha! Thanks a lot!  👍
