### ISSUE TITLE
countSeries() after functions returning no data point

### ISSUE THREAD

**Issue by JosephFY** [graphite-project/graphite-web#2367]
Hello,

We are using 1.1.2 in a one node setup

Using Grafana with graphite as data source and one of our metrics looks like the following
`servers.serverX.status`

The status metric can have 3 values, 0,1,2 each one of these metrics means something to us. have about 10000 servers for this query
I am trying to get counts for every number on a single stat panel in Grafana, for example

`countSeries(currentAbove(servers.*.status, 1.1))` to get us count of servers reporting 2.

This is working just fine when there is some servers reporting 2 but when there is no servers reporting 2, count function seems to have a problem because currentabove is returning no data points so the single stat is giving server error because it's trying to count a "no data point' results

Any thoughts on this ? any work around that I am not aware off? we do a lot of those aggregation functions and in many cases 

Thanks in advance
Thank you

**Comment by deniszh** [comment]
Put Transformnull(x,0) before countseries ?

**Comment by DanCech** [comment]
That is a good question, I have a trivial patch to make countSeries "work" for empty result sets, but a drawback is that it doesn't have an easy way to tell what the output alias should be, due to the internal implementation of series lists in graphite functions not keeping track of the pathExpression for a given list.  It should be possible to fix that problem by implementing a custom `SeriesList` type based on `list` (similar to the existing `TimeSeries` type) so that it could carry `pathExpression` and thus support proper aliasing when empty.

**Comment by DanCech** [comment]
@deniszh that won't help if the seriesList is empty, but it could be done with something like:
```
fallbackSeries(countSeries(currentAbove(servers.*.status, 1.1)), constantLine(0))
```

**Comment by deniszh** [comment]
Yes, you're right, didn't realize that first.


17 окт. 2018 г. 10:18 PM пользователь "Dan Cech" <notifications@github.com>
написал:

@deniszh <https://github.com/deniszh> that won't help if the seriesList is
empty, but it could be done with something like:

fallbackSeries(countSeries(currentAbove(servers.*.status, 1.1)),
constantLine(0))

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/graphite-project/graphite-web/issues/2367#issuecomment-430773434>,
or mute the thread

**Comment by JosephFY** [comment]
Hello guys,

First, big thanks to @DanCech for the nice webinar yesterday, was really helpful. I was the guy asking questions here and there :)

So couple of observations on this. I was mistaken initially of the version. Had done a test today and noticed the following 

Have 2 separate graphite instances, they are stand alone so they are not part of clustering at all but I push data 2 both at the same time, so both have same metrics as far as this is concerned.

Grafana 5.2.3

1. `0.9.13`  The Singlstat throws  `no value` and it shows a Server Internal Error.
2. `1.1.3` The Singlstat throw `no value` BUT it doesn't show the Internal Server Error. But of course putting this in a an actual graph returns no data points

We don't care about the `0.9.13` as we are migrating from it. We also trying to get historical data of those counts, I usually do them in a combination of scale(0) and offest(1) count() functions.

I will be testing the `fallbackSeries` in the next few minutes and get back to you with results.

**Comment by DanCech** [comment]
Hi Joseph,

> First, big thanks to @DanCech for the nice webinar yesterday, was really helpful. I was the guy asking questions here and there :)

Thanks for the kind words 😃 

>     2. `1.1.3` The Singlstat throw `no value` BUT it doesn't show the Internal Server Error. But of course putting this in a an actual graph returns no data points

Yep, that makes sense.

> We don't care about the `0.9.13` as we are migrating from it. We also trying to get historical data of those counts, I usually do them in a combination of scale(0) and offset(1) count() functions.

Also makes sense.

> I will be testing the `fallbackSeries` in the next few minutes and get back to you with results.

Cool.

**Comment by JosephFY** [comment]
@deniszh so couple of notes about the fallback.

The fallbackSeries is working perfectly on a singlestat (assuming 
 the sparkle are not shown) `fallbackSeries(countSeries(currentAbove(servers.*.status, 1.1)),constantLine(0))`

With the fallback, I still cant seem to apply scale(0), offest(1) and sumSeries() i.e. to be able to get the count of series historically .

I really think that a countSeries or a new/similar function should be available to count series across selected period of time, I guess anything besides that will be just non efficient workarounds.

> That is a good question, I have a trivial patch to make countSeries "work" for empty result sets, but a drawback is that it doesn't have an easy way to tell what the output alias should be, due to the internal implementation of series lists in graphite functions not keeping track of the pathExpression for a given list. It should be possible to fix that problem by implementing a custom SeriesList type based on list (similar to the existing TimeSeries type) so that it could carry pathExpression and thus support proper aliasing when empty.

Assuming this can be done as a custom function, I will start trying (with my modest programming skills) to work on a custom function to do this, I haven't done custom functions before but it seems straight forward. I am OK with a function that wont do Alias functions if it cal do the simple alias('') to rename the series. Can test it out if you have the code ready and provide feedback.

we have have plans to do many of count series on the fly with our data which seems so difficult to do so. Aggregating metrics before and is not an option for us as well for many of those

**Comment by DanCech** [comment]
To make this work over time, I would use a different approach:

`transformNull(aggregate(removeAboveValue(removeBelowValue(servers.*.status, 2), 2), 'count'))`

That is going to take each of your series, and for each one replace any values less than 2 or more than 2 with null, then for each interval it'll count the remaining non-null values (the series that had value=2 for that interval), then it'll transform the result for any intervals that didn't have any non-null values from null to 0.
