### ISSUE TITLE
Add nonNegativeDerivative() option to compute the first value after wrap-around starting from 0

### ISSUE THREAD

**Issue by mbarbon** [graphite-project/graphite-web#2374]
Hi,

I have a time series derived from a counted that is reset to 0 on application restart; a typical series looks like:

    [ ..., 1000, 1060, 1120, ... , 1620, /* restart */, 40, 100, 160, ... ] // original
    [ ...,   60,   60,   60,   ... , 80,              None,  60,  60, ... ] // nonNegativeDerivative
    [ ...,   60,   60,   60,   ... , 80,                40,  60,  60, ... ] // desired output

what I would like to achieve is to have the value where the derivative is negative computed as if the previous value were 0. I can't see a way of doing this with the current set of Graphite functions.

If the maintainers think this would be a desirable optional behaviour, I am happy to submit a patch to implement it.

**Comment by deniszh** [comment]
I'm fine with that option, why not. You can implement some optional parameter for that, with default value as false for backward compatibility.
Thanks!

**Comment by piotr1212** [comment]
I always thought that was the actual behaviour. Having an optional parameter would be great.

**Comment by deniszh** [comment]
Merged in 1.1.5
