### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Mohamedghalab** [graphite-project/graphite-web#2376]
:~/Desktop/Blog$ django-admin startproject project .

Traceback (most recent call last):
  File "/usr/bin/django-admin", line 18, in <module>
    from django.core import management
ImportError: No module named django.core

**Comment by deniszh** [comment]
I'm doubting that. If it's related to Django only and not Graphite per se, @Mohamedghalab, please ask support in Django community. For installing Graphite you do not need to run startproject command. Please refer to installation docs - https://graphite.readthedocs.io/en/latest/install.html
