### ISSUE TITLE
whitenoise v3 do not support django1.4

### ISSUE THREAD

**Issue by dengshaochun** [graphite-project/graphite-web#2378]
graphite-web version: 0.9.16

when i use  whitenoise==3.3.1 and Django==1.4, exception found
```
Traceback (most recent call last):
  File "./graphite/wsgi.py", line 31, in <module>
    from whitenoise.django import DjangoWhiteNoise
  File "/usr/lib/python2.7/site-packages/whitenoise/django.py", line 18, in <module>
    from django.utils.six.moves.urllib.parse import urlparse
```

**Comment by deniszh** [comment]
Hello @dengshaochun ,
Please downgrade `whitenoise` to 2.0.6 or lower - newer version doesn't support Django 1.4.
Please also note that 0.9.16 is very old and 0.9.x branch is not supported anymore (i.e. we're not planning to make any 0.9.x releases)

**Comment by dengshaochun** [comment]
@deniszh ok，thanks。but i think you should update requirements.txt of 0.9.16 releases

**Comment by deniszh** [comment]
OK, agreed - https://github.com/graphite-project/graphite-web/pull/2379

**Comment by deniszh** [comment]
Merged
