### ISSUE TITLE
Graphite wsgi consumes 100% CPU

### ISSUE THREAD

**Issue by balasenthil-d** [graphite-project/graphite-web#2385]
I have an instance graphite running along with grafana in the same server. I have a few spring boot applications sending out metrics to graphite host. As soon I start graphite, I see the CPU is about 100%. This continues for ever. I am facing the same issue as mentioned in https://github.com/Microsoft/WSL/issues/2055 except this being in linux.

Am I doing something wrong here ?

To add a bit more information, when I do a strace on the processes consuming high CPU, I see there is continuous lseek and read to graphite.db file.

**Comment by deniszh** [comment]
graphite wsgi is consuming CPU only for read load, not for write load. Do you have some read load? how much? If yes - then wsgi can be just overloaded, you can try to tune number of wsgi threads and workers first - use any general WSGI / Django tuning documentation for that, e.g. https://stackoverflow.com/questions/30794363/how-to-improve-the-performance-of-apache-with-mod-wsgi  or https://serverfault.com/questions/592646/tuning-django-based-site-deployed-using-apache-wsgi-for-better-performance

**Comment by piotr1212** [comment]
> graphite wsgi is consuming CPU only for read load, not for write load

Unless you are using tags. @balasenthil-d are you using tags?

**Comment by deniszh** [comment]
Ah, very good point, @piotr1212 ! You can disable tags in carbon using `ENABLE_TAGS = False` if tags are not used.

**Comment by balasenthil-d** [comment]
Yes I am using tags. I use them to differentiate the services that push the metrics. Like we have spring boot applications and they all push metrics to graphite server. Tags is how I identify them.

**Comment by DanCech** [comment]
Ok, you may want to explore using MySQL or Postgres instead of the sqlite graphite.db.  Another thing you can do is to increase the `TAG_UPDATE_INTERVAL` setting in carbon to reduce how often it sends updates to the TagDB, I'd suggest increasing it to 1000 and seeing whether that makes a difference.

**Comment by balasenthil-d** [comment]
Thanks @DanCech,  I have changed it to 1000 and will wait to see if it makes a difference

**Comment by deniszh** [comment]
sqllite db is not recommended for production usage, but in case of single host and no tagging it's usually working fine. In case of tagging you probably should use Redis / MySQL / Postgres.

**Comment by balasenthil-d** [comment]
Ok thank you @deniszh I will look at migrating to a RDBMS.

**Comment by piotr1212** [comment]
@balasenthil-d did changing to a RDBMS solve your issue?

**Comment by balasenthil-d** [comment]
Actually I am quite happy with the performance ever since changing TAG_UPDATE_INTERVAL. The CPU has been around 3-10% with occasional CPU spikes. I am not planning to use RDBMS unless its really needed.
