### ISSUE TITLE
how to use  the "search" button on the graphite-web

### ISSUE THREAD

**Issue by idling11** [graphite-project/graphite-web#2387]
Hello，This is my first time to use graphite and found it is a very useful  tool。But what bothers me is the  "search" button on the graphite web，the button is useless。can someone tell me how to make the "search"  button be useful ?  appreciate it !

<img width="339" alt="1111" src="https://user-images.githubusercontent.com/8055620/49013870-206c1c80-f1b9-11e8-8b1f-3093d81be7de.png">

**Comment by deniszh** [comment]
IIRC search functionality was VERY ineffective and was disabled before 1.0.0 release.

**Comment by idling11** [comment]
@deniszh thanks for your answer。Since this method is inefficient, is there any other efficient way for me to search on the page?  Or is there any plug-in that can do this?  Because I have too many metrics

**Comment by deniszh** [comment]
Hello @idling11,
Unfortunately, no such functionality currently exists out of box. You can use some suggestions from https://github.com/graphite-project/graphite-web/issues/26, e.g. write some script which will call /metrics/find?query=* url, then walk the tree. Or use `find /opt/graphite/storage/whisper -type f -name *.wsp` locally on Graphite server to get list of metrics.

**Comment by idling11** [comment]
@deniszh Ok , I will have a try.  thank you very much
