### ISSUE TITLE
graphite-web not displaying anything when i use soft-link in carbon whisper files

### ISSUE THREAD

**Issue by GowthamShanmugam** [graphite-project/graphite-web#2390]
I have installed graphite-web-0.9.15-1.el7rhgs.noarch, then i initialized graphite.db after that i updated to graphite-web-1.1.4-1, all migration commands are executed successfully. 

But I am facing an issue like when I create an alias (soft link using some name) for whisper files then nothing is displayed in graphite-web.

All my data is stored in  /var/lib/carbon/whisper/{app_name}/{hostname}/cpu/abc.wsp 
i created soft-link like  
/var/lib/carbon/whisper/{app_name}/some_alias_name ->/var/lib/carbon/whisper/{app_name}/{hostname}

when I open graphite under alias name it should show hostname but I can see everything in terminal but not in graphite-web. Permission also 777 only.

**Comment by GowthamShanmugam** [comment]
I saw this issue lot of times, why I can't use the soft link there if I install web-1.1.4-1 in the fresh machine then I create soft-link then it works fine. but why it is not working in above case

**Comment by piotr1212** [comment]
This has been fixed in https://github.com/graphite-project/graphite-web/issues/2320

**Comment by GowthamShanmugam** [comment]
i am seeing this issue in  graphite-web-1.1.4-1

**Comment by GowthamShanmugam** [comment]
i can see fixed code in my setup but still i am faceing this issue, i removed all packages 

 yum remove graphite-web pythoon-carbon python-whisper python-django 

and then installed again but still i am seeing this issue.

**Comment by deniszh** [comment]
@GowthamShanmugam : 
could you please elaborate which Graphite version do you use and how you trying to install it? 
Thanks!

**Comment by GowthamShanmugam** [comment]
version which i am using is:
 python2-django-1.11.15-1
  graphite-web-1.1.4-1
 python-carbon-1.1.4-1
  python-whisper-1.1.4-1

**Comment by GowthamShanmugam** [comment]
First i installed   
  graphite-web-0.9.15
  python-carbon-0.9.15-2
  python-whisper-0.9.15

after that i ran graphite command to intialize:
  /usr/lib/python2.7/site-packages/graphite/manage.py syncdb --noinput

After intialized i just updated with new graphite-web package which i pasted in above command and then i intialized new version of graphite using a command:

 PYTHONPATH=$GRAPHITE_ROOT/webapp/ django-admin migrate --settings=graphite.settings --run-syncdb

It executed successfully, then i start carbon-cache service:
   service carbon-cache start

Then i created softlink inside /var/lib/carbon/whisper/{app_name}/{soft_link}
(e.g)
[root@tendrl-server graphite_dependency-]# ll /var/lib/carbon/whisper/tendrl/names/e43fcdf8-45b9-4146-909b-fb26b9078e26
lrwxrwxrwx. 1 root root 77 Dec  7 12:49 /var/lib/carbon/whisper/tendrl/names/e43fcdf8-45b9-4146-909b-fb26b9078e26 -> /var/lib/carbon/whisper/tendrl/clusters/e43fcdf8-45b9-4146-909b-fb26b9078e26


the softlink is not displayed in graphite-web, but i can see all directory using softlink in terminal.

**Comment by GowthamShanmugam** [comment]
If i install new version of graphite-web in a fresh machine  then it works fine, i am faceing issue when i try to update to new version from old version.

**Comment by GowthamShanmugam** [comment]
I am constantly reproducing this issue

**Comment by deniszh** [comment]
Then you not really upgrading Graphite on old server and still using 0.9.15. Please note that you can't install graphite with RPMs and then upgrade it with installation from source - probably RPMs using different paths (probably /usr/something), source installation using /opt/graphite.
You can fing Graphite version if check `/version` url. If it's giving 404 - it's less then 1.0.0

**Comment by piotr1212** [comment]
> version which i am using is:
python2-django-1.11.15-1
graphite-web-1.1.4-1
python-carbon-1.1.4-1
python-whisper-1.1.4-1

Where did you get those package from? Did you rebuilt my Fedora specfile or are you using some internal Red Had packages?

**Comment by GowthamShanmugam** [comment]
for RHEL we built it manually, during graphite-web build we figured out dependencies one by one and we build all, then issue which I am facing is once I removed graphite package and reinstalled higher version or same version then a soft link is not working.
I am working in redhat as SE, for our product we are using graphite as time series DB in RHEL

**Comment by GowthamShanmugam** [comment]
One thing is not clear, i removed all graphite related packages and then reinstalled same version then soft-link is not working.
