### ISSUE TITLE
Can I use the site logo in my (company's) presentation?

### ISSUE THREAD

**Issue by pumbaacave** [graphite-project/graphite-web#2394]
I want to use the [logo](https://graphiteapp.org/img/graphite-logo_color.png) in the presentation that talks about my company's infrastructure, where graphite is used to collect metrics.

After searching the site, I found apache license not granting trademark usage.
I will appreciate it someone can tell me whether I can use the logo or not

**Comment by deniszh** [comment]
I'm not a lawyer, but I think fair use of logo, of course, allowed. 
What do you think, @DanCech ?

**Comment by DanCech** [comment]
Yes, that is absolutely fair use, we're always happy for people to talk about how they use Graphite 👍

**Comment by pumbaacave** [comment]
Thank you! Very nice to hear that!
