### ISSUE TITLE
graphite  can't open file

### ISSUE THREAD

**Issue by olegus1** [graphite-project/graphite-web#2396]
I am trying to set up a database for graphite:
/home/adman# python /usr/lib/python2.7/dist-packages/graphite/manage.py migrate auth

gives the following result:
python: can't open file '/usr/lib/python2.7/dist-packages/graphite/manage.py': [Errno 2] No such file or directory

**Comment by piotr1212** [comment]
Probably installed in a different path, `find / -name 'manage.py' 2>/dev/null` if you don't know where. Closing as this doesn't seem an issue. Feel free to reopen if needed.
