### ISSUE TITLE
Graphite is not giving any value when pipe symbol in metrics

### ISSUE THREAD

**Issue by GowthamShanmugam** [graphite-project/graphite-web#2400]
I am using graphite-1.1.X, and I connected this with grafana as a data source.  I saw all the graphs are got populated except where the graph which has pipe symbols in metric.

Initially, I thought it is grafana problem but if I downgrade graphite version to 0.9.X then it works fine. 

I can see all .wsp files are created for that, but I don't know why it is not populating any data.

![image](https://user-images.githubusercontent.com/15073590/50199356-5cd50780-0376-11e9-97c6-5c7f16e6de32.png)

**Comment by GowthamShanmugam** [comment]
other metrics are works fine

![image](https://user-images.githubusercontent.com/15073590/50199445-d836b900-0376-11e9-9927-dd97c089378a.png)

**Comment by GowthamShanmugam** [comment]
if I give \|mnt\|data1\|1 like this then it gives values in a graph, but using this solution I cant use template variables in grafana.  template variables are populated at runtime, so I can't mention it as a hardcoded value with the slash.

**Comment by GowthamShanmugam** [comment]
We used grafana 0.9.x with same metrics for a long time, and recently we moved to grafana 1.1.X, it looks like some problem with pipe symbol in a new version.

**Comment by DanCech** [comment]
In 1.1.x the pipe symbol is now part of the query syntax, so to use it in series names it has to be escaped.

https://graphite.readthedocs.io/en/latest/render_api.html#examples shows how it is used.

**Comment by GowthamShanmugam** [comment]
Escape in the sense does i have to give \| instead of |. But we can give this when we have static query what in the case of a dynamic query which is formed using templates?

How to solve that case?

**Comment by GowthamShanmugam** [comment]
For example

![image](https://user-images.githubusercontent.com/15073590/50201225-39628a80-037f-11e9-82c8-8e743ba6f38f.png)


Actually, I want to know a solution for this scenario

**Comment by GowthamShanmugam** [comment]
is it not possible to use graphite metrics in this way?

**Comment by GowthamShanmugam** [comment]
or graphite have any other function to handle special charactesr in metrics

**Comment by deniszh** [comment]
Graphite has e.g. `aliasSub()` but I just tested - it's not helping in this case, for some reason Grafana not accepting variables from aliasSub() function.

**Comment by GowthamShanmugam** [comment]
Those are only for display purpose I think, it won't do any changes on actual metrics

**Comment by deniszh** [comment]
All Graphite functions are for display purpose, but some functions operate on data values, some - on metric names. aliasSub() operates on metric names, so, theoretically, you can use aliasSub() when providing variable in Grafana, to replace all "|" with "/|" - but for some reason, it's not working _on Grafana_ side (it works on Graphite).

**Comment by DanCech** [comment]
Grafana uses find queries to resolve variables, so it can't use `aliasSub` unfortunately.  The likely solution will be to add support in Grafana for escaping the pipe character, or to use a different separator in the series names.

**Comment by GowthamShanmugam** [comment]
What are all the support symbols in graphite series name?

**Comment by GowthamShanmugam** [comment]
> All Graphite functions are for display purpose, but some functions operate on data values, some - on metric names. aliasSub() operates on metric names, so, theoretically, you can use aliasSub() when providing variable in Grafana, to replace all "|" with "/|" in metric name - but for some reason, it's not working _on Grafana_ side (it works on Graphite).

can you please paste the aliasSub() metric which you tried?

**Comment by GowthamShanmugam** [comment]
What are all the other special character are allowed? any other symbol which won't cause issue?

**Comment by DanCech** [comment]
Right now the spec is overly permissive, which is partly how we got into this situation. I commonly use underscore or dash in this situation as those are definitely safe.
