### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#2405]
Githib Issue templates can simplify issue management and help us with user requests.
We can pick nice example in https://github.com/stevemao/github-issue-templates or in https://github.com/devspace/awesome-github-templates

**Comment by bigpythonimish** [comment]
I can make it more specific, can you please give me a brief about what all needs to be added. Thanks
x

**Comment by bigpythonimish** [comment]
I can make it more specific, can you please give me a brief about what all needs to be added. Thanks
