### ISSUE TITLE
Target WSGI script cannot be loaded as Python module

### ISSUE THREAD

**Issue by senz79** [graphite-project/graphite-web#2406]
Hello 
I am getting the below error. I have followed many solution on the net as it seems to be common, but no success. Please guide

[Wed Dec 26 17:27:25.198103 2018] [:error] [pid 25654] mod_wsgi (pid=25654): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Wed Dec 26 17:27:25.198140 2018] [:error] [pid 25654] mod_wsgi (pid=25654): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Wed Dec 26 17:27:25.198167 2018] [:error] [pid 25654] Traceback (most recent call last):
[Wed Dec 26 17:27:25.198189 2018] [:error] [pid 25654]   File "/opt/graphite/conf/graphite.wsgi", line 7, in <module>
[Wed Dec 26 17:27:25.198254 2018] [:error] [pid 25654]     from graphite.wsgi import application
[Wed Dec 26 17:27:25.198269 2018] [:error] [pid 25654]   File "/opt/graphite/webapp/graphite/wsgi.py", line 15, in <module>
[Wed Dec 26 17:27:25.198326 2018] [:error] [pid 25654]     application = get_wsgi_application()

**Comment by piotr1212** [comment]
Seems like there are some lines missing from the stack trace, quite hard to say what is wrong without them.

Would also be helpful if you would post more info about your environment, os, python version, django version, apache version..
