### ISSUE TITLE
Is there any way to specify a step when generating or retrieving raw data. 

### ISSUE THREAD

**Issue by dumbdonkey** [graphite-project/graphite-web#2410]
we push metrics to grahite every minute. 
while we want to show the metric by an hour, I cannot found a  proper function. 
I can use integralByInterval(a,'1h') to sum metric value over an hour, while there are too many points.  I just need one point one hour

**Comment by JosephFY** [comment]
I guess what you need is [smartSummarize](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.smartSummarize)

This function will apply different calculations per the time interval you specify
