### ISSUE TITLE
Getting IOError: [Errno 13] Permission denied: '/var/log/graphite/info.log'

### ISSUE THREAD

**Issue by aussiearef** [graphite-project/graphite-web#2413]
I have launched an Ubuntu 18.04 on AWS, and I have connected to it via ssh using the default AWS user "Ubuntu".

I have followed the instructions on [HERE ](https://computingforgeeks.com/how-to-install-and-configure-graphite-on-ubuntu-18-04/)to install Graphite on Ubuntu (with mysql).

After the installation when I go to http:// I get HTTP 500 error. Loogin at the /var/log/apache2/graphite-web_error.log I see this error message:

mod_wsgi (pid=5835): Exception occurred processing WSGI script '/usr/share/graphite-web/graphite.wsgi'.

IOError: [Errno 13] Permission denied: '/var/log/graphite/info.log'

I have tried both:

sudo chmod www-data:www-data /var/log/graphite/info.log

and sudo chmod ubuntu /var/log/graphite.info

I also have tried chmod:

sudo chmod o+r /var/log/graphite/info.log

Then I have reloaded apache2, but I still get the same error.

This has already wasted two days of my time. I have tried almost every link I found on Google. I am sure there is another problem but the module fails to write the error message into the log file so I need to get the permission problem fixed first. Please help!

**Comment by aussiearef** [comment]
Thanks @deniszh 
No offense. I have been a Windows user for 20 years hence struggling with Ubuntu. I would like to install Graphite myself rather than using Docker for some reasons so please bear with me.
I will try your solution, but I am pretty sure I granted permissions to /var as well. 

One question. Is it the Apache user that runs carbon-cache or is it the user who started the service?

**Comment by piotr1212** [comment]
You confused chmod with chown.

**Comment by piotr1212** [comment]
> One question. Is it the Apache user that runs carbon-cache or is it the user who started the service?

Really depends on how you started it, just run `ps -ef | grep carbon`

**Comment by deniszh** [comment]
Hello @aussiearef 
> I have been a Windows user for 20 years hence struggling with Ubuntu

Is it separate Ubuntu or you trying to install Graphite in WSL?

>  Is it the Apache user that runs carbon-cache or is it the user who started the service?

As @piotr1212 said - it depends on the installation. But if it's coming from graphite.wsgi - it probably not carbon but graphite-web, trying to write logs.

**Comment by aussiearef** [comment]
Also :

I executed 
"ps -ef | grep carbon"

Which reported:
_graphi+  1458     1  0 22:50 ?        00:00:00 /usr/bin/python /usr/bin/carbon-cache --config=/etc/carbon/carbon.conf --pidfile=/var/run/carbon-cache.pid --logdir=/var/log/carbon/ start
ubuntu    1625  1357  0 23:00 pts/1    00:00:00 grep --color=auto carbon

I have a user called "ubuntu" which is the default user in AWS Ubuntu . But there is no user called "_graphite". Is this user created by Graphite??  Do I have to create it?!!

**Comment by deniszh** [comment]
@aussiearef 
>Using chown and chomod then rebooting the whole machine I will get rid of the permission denied error.

Reboot is not needed, `sudo systemctl stop apache2 + sudo systemctl start apache2` should be enough.

>But then after that I always have this:
>File "/usr/share/graphite-web/graphite.wsgi", line 14, in 
>application = get_wsgi_application()
>File "/usr/lib/python2.7/dist-packages/django/init.py", line 27, in setup
>apps.populate(settings.INSTALLED_APPS)

Unfortunately, it's a truncated error message, could you post the whole error message here?

>But there is no user called "_graphite". Is this user created by Graphite?? Do I have to create it?!!

Probably, debian packages doing that during install. We're not packing Graphite for Ubuntu or Redhat, package maintainers doing that.

**Comment by aussiearef** [comment]
[GraphiteErrors.txt](https://github.com/graphite-project/graphite-web/files/2794061/GraphiteErrors.txt)

Log file is attached

**Comment by aussiearef** [comment]
Also this is my virtual host file (apache2-graphite.conf) file:

<VirtualHost *:80>

        WSGIDaemonProcess _graphite processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120 user=_graphite group=_graphite
        WSGIProcessGroup _graphite
        WSGIImportScript /usr/share/graphite-web/graphite.wsgi process-group=_graphite application-group=%{GLOBAL}
        WSGIScriptAlias / /usr/share/graphite-web/graphite.wsgi

        Alias /static/ /usr/share/graphite-web/static/
        <Location "/static/">
                SetHandler None
        </Location>

        ErrorLog ${APACHE_LOG_DIR}/graphite-web_error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel info

        CustomLog ${APACHE_LOG_DIR}/graphite-web_access.log combined

</VirtualHost>

**Comment by aussiearef** [comment]
@deniszh 
So I have made some progress:
1- The problem was that the user "_graphite" had to have access to info.log and exception.log and now www-data user. So I granted access and then I could see some proper errors in the logs.

2- There is an exception raised by Django saying "context must be dict not Context". It is because "Context is deprecated but it is used in views.py file. I edited this file and removed the Context and so this error went away too.

3- Now I get this error although I have run "sudo graphite-manage migrate auth" command.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/graphite/composer/views.py", line 35, in composer
    profile = getProfile(request)
  File "/usr/lib/python2.7/dist-packages/graphite/user_util.py", line 25, in getProfile
    return default_profile()
  File "/usr/lib/python2.7/dist-packages/graphite/user_util.py", line 44, in default_profile
    profile, created = Profile.objects.get_or_create(user=user)
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: (1146, u"Table 'graphite.account_profile' doesn't exist")

**Comment by aussiearef** [comment]
Never mind I fixed it
Just so if anyone else faces this problem, the main issue is that for a new db setup  you need to run:

PYTHONPATH=$GRAPHITE_ROOT/webapp
cd /usr/bin 
sudo django-admin migrate --settings=graphite.settings --run-syncdb
 
This is explained [HERE](https://graphite.readthedocs.io/en/latest/config-local-settings.html)

I did not run syncdb and only run migrate because almost everywhere in the Internet it is said that since the deprecation of syncdb, migrate will do the database migration!

**Comment by deniszh** [comment]
Hello @aussiearef ,

>1- The problem was that the user "_graphite" had to have access to info.log and exception.log and now www-data user. So I granted access and then I could see some proper errors in the logs.

Well, as I said before, we're not packing Graphite in packages, maintainers of distros doing that. IMHO it's not a good idea to have same file for logging from carbon and graphite-web - but looks like maintainers think differently.
It's a quite hard problem with the distribution of complex software products, it's hard to solve it without some generic distribution mechanism, like e.g. Docker ;)

>2- There is an exception raised by Django saying "context must be dict not Context". It is because "Context is deprecated but it is used in views.py file. I edited this file and removed the Context and so this error went away too. (I see that this is already fixed in master

Yes, that's because of Django 1.11, it was [fixed](https://github.com/graphite-project/graphite-web/commit/b602664916c0529be0414f441d207562381179e7) not only in master but in 1.1.0 and newer versions. Again, dependencies are another complex issue.

**Comment by piotr1212** [comment]
@aussiearef The permission issue and and the version incompatibility are packaging issues and should be reported to the package maintainer downstream so they can fix it. Reporting issues with Ubuntu packages can be done at: https://bugs.launchpad.net/ubuntu
