### ISSUE TITLE
Finding version one is running

### ISSUE THREAD

**Issue by montanaman2017** [graphite-project/graphite-web#2414]
I can't believe I'm asking this, but I've looked and no go.
   I inherited a graphite/grafana setup (due to other admin leaving) and we can not figure out how in the world to find the version of graphite this is running.  
a listing of the graphite version directory shows:

-rw-r--r-- 1 hms nonpriv   0 Dec 20  2016 __init__.py
-rw-r--r-- 1 hms nonpriv 137 Dec 20  2016 __init__.pyc
-rw-r--r-- 1 hms nonpriv 724 Dec 20  2016 urls.py
-rw-r--r-- 1 hms nonpriv 957 Dec 20  2016 urls.pyc
-rw-r--r-- 1 hms nonpriv 212 Dec 20  2016 views.py
-rw-r--r-- 1 hms nonpriv 515 Dec 20  2016 views.pyc

but even grepping thru those for version does not give me anything.  How can one tell what version they are on?

**Comment by piotr1212** [comment]
I'm assuming this answered your question thus closing this issue, feel free to reopen if it is still not clear.
