### ISSUE TITLE
Memory Utilization from Graphite 

### ISSUE THREAD

**Issue by vaibhavpujari89** [graphite-project/graphite-web#2419]
I want to download server wise memory utilization from Graphite.
What is metric name to get the memory utilization value.

**Comment by piotr1212** [comment]
That fully depends on how you named it. Graphite is "just" a database for metrics, it has the names which you put into it.

**Comment by deniszh** [comment]
@vaibhavpujari89 
You need to install metric collector on target host, and point it to Graphite input (usually port 2003).
Good collectors - [Collectd](https://collectd.org/) or [Diamond](https://github.com/python-diamond/Diamond).
