### ISSUE TITLE
what's the default user and password to login graphite-web?

### ISSUE THREAD

**Issue by dumbdonkey** [graphite-project/graphite-web#2420]
I've installed graphite-web according to official documentation. 
when I try to login graphite-web so that I can save my own graph, it needs a username and password.

where can I find them? I've searched the documentation however found nothing.

**Comment by deniszh** [comment]
If you using [official Docker image](https://github.com/graphite-project/docker-graphite-statsd) - it have admin user root/root.
But if you just have a fresh install of Graphite - it will not have any users. Create admin user by using command `django-admin.py createsuperuser`.

**Comment by deniszh** [comment]
Or you can use 3rd party dashboards app, like [Grafana](https://grafana.com/) for storing dashboards / graphs.

**Comment by primal100** [comment]
Django-admin has no createsuperuser option in Django 2.2.6.

Why is there no manage.py file?

**Comment by deniszh** [comment]
Hi @primal100,

>Django-admin has no createsuperuser option in Django 2.2.6.

I do not see that change in release notes or changelog. Documentation says that it should be there - https://docs.djangoproject.com/en/2.2/ref/django-admin/#createsuperuser

**Comment by primal100** [comment]
It;s actually required to add the PYTHONPATH (like in the migrate option in the docs):

PYTHONPATH=/opt/graphite/webapp django-admin.py createsuperuser --settings=graphite.settings

Copying the default manage.py takes care of this automatically
