### ISSUE TITLE
Type of "value" for useSeriesAbove should be Integer, not string

### ISSUE THREAD

**Issue by Civil** [graphite-project/graphite-web#2422]
https://github.com/graphite-project/graphite-web/blob/b6d6d93665a4fd11c347a8e966b51fec6520fc33/webapp/graphite/render/functions.py#L3526

According to the function's code, it's used in numeric comparisons, so it should be Integer, not "string".

**Comment by Civil** [comment]
https://github.com/graphite-project/graphite-web/blob/b6d6d93665a4fd11c347a8e966b51fec6520fc33/webapp/graphite/render/functions.py#L3510-L3513

This is the place where the 'value' is used. For a reference point.

Plus here's the quote from the description, where it's also clear that it should be "integer":
https://github.com/graphite-project/graphite-web/blob/b6d6d93665a4fd11c347a8e966b51fec6520fc33/webapp/graphite/render/functions.py#L3506

**Comment by DanCech** [comment]
Good catch.  I'm thinking that integer is actually not accurate either for a lot of these params, and that it should actually be float.

**Comment by deniszh** [comment]
It’s quite easy to fix, indeed
