### ISSUE TITLE
ImportError: No module named django.core

### ISSUE THREAD

**Issue by shirishkale** [graphite-project/graphite-web#2428]
When I am trying to start the graphite server using the following command

PYTHONPATH=`pwd`/storage/whisper ./bin/run-graphite-devel-server.py --port=80 --libs=`pwd`/webapp /data/graphite 1>/data/graphite/storage/log/webapp/process.log 2>&1 &

I am getting the following error

File "./bin/run-graphite-devel-server.py", line 6, in <module>
  from django.core import management
ImportError: No module named django.core.

Previously this used to work when I had installed carbon, whisper and graphite-web using  python setup.py.

On attempting a reinstall I started getting error "Whisper module could not be loaded". As a result I installed all these 3 using pip and I have started getting the error.

**Comment by shirishkale** [comment]
This is related to issue #2427

**Comment by piotr1212** [comment]
make sure you have django installed, it is a supported version and that it is in your pythonpath.

**Comment by shirishkale** [comment]
Installing Django again versio 1.11.20 ran the graphite server but the error log file still has

WARNING: whisper module could not be loaded, whisper support disabled

and no metrics is getting displayed in graphite-web.

**Comment by piotr1212** [comment]
Did you try installing whisper?

**Comment by shirishkale** [comment]
Yes. No use. Still the same error message

**Comment by deniszh** [comment]
@shirishkale : something is really wrong with your PYTHONPATH. I'm not sure how properly detect that problem or fix it. It's far beyond Graphite per se, it's a generic python problem.
How do you trying to install Graphite? From source or packages? Do you use virtualenv?

**Comment by shirishkale** [comment]
All components of graphite were installed 3 times.

First Round

1. All Carbon, Whisper and Graphite were installed using the downloaded zip files version 1.1.5.
2. Using python setup.py install --prefix=  --install-lib=
3. It installed fine except django-admin.py was not under /data/graphite directory where the install were done but in /usr/lib/python2.7/site-packages/Django-1.11.16-py2.7.egg/django/bin/
4. Neo4j metrics was captured and graphs were correctly displayed.

I uninstalled everything and followed the same procedure to have a repeatable process

Second Round

1. Install went fine. All components loaded correctly
2. The error for Not able load Whisper started and no metrics or graphs were displayed
3. I went ahead and uninstalled anything

To fix the issue of not having django-admin.py under PYTHONPATH all the three components were reinstalled using a different method.

Round Three 

1. Install Carbon, Whisper and Graphite-web using "pip install https://github.com/graphite-project/graphite-web/tarball/master" --prefix=  --install-lib=
2. Install went ok but ran into issues with Django
3. REinstalled Django. Noe django -admin.py is under "/data/graphite" where graphite is installed
4. Still the same error

Hence I am not sure why it worked the first time and will not work the last two times.
All this while my python binaries are under "/usr/bin/python".

Hence can Graphite be installed under any custom directory or has to be under "/usr/bin/python"
path somewhere?

If the install worked the first time then what could create issues for Python suddenly?

**Comment by shirishkale** [comment]
The following line complains about not able to load whisper module

django-admin.py runserver --pythonpath /data/graphite/webapp --settings graphite.settings 0.0.0.0:80

What could be wrong with pythonpath when this command explicitly mentions the PYTHONPATH?

**Comment by piotr1212** [comment]
is your whisper module installed in `/data/graphite/webapp`?

**Comment by shirishkale** [comment]
No. Whisper module is installed in "/data/graphite" libraries in "/data/graphite/lib".
Graphite web is installed in "/data/graphite" libraries in "/data/graphite/webapp"

When I try to start the graphite-web, then the runserver commands of graphite web complains that it can not load whisper module.

**Comment by piotr1212** [comment]
If your modules are installed in `/data/graphite/lib` why are you specifying `/data/graphite/webapp` as your `pythonpath`?

**Comment by shirishkale** [comment]
Only whisper and carbon are installed in /data/graphite/lib. Graphite-Web is in webapp? Should I change the install location for graphite-web also to "/data/graphite/lib"?

**Comment by piotr1212** [comment]
Well, you installed your modules in a location which is not known by Python. Now Python cannot find them.

**Comment by shirishkale** [comment]
Does that mean graphite-web will not work correctly if I install it into a non-default location? Because even if I install everything in /data/graphite even then graphite-web complains that Whisper module can not be loaded. Which means there is no option but to install it in /opt/graphite. Is that so?

**Comment by piotr1212** [comment]
you'll need to tell Python where to find its modules. [hint](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH)

**Comment by shirishkale** [comment]
Any Path I use its the same message can not load whisper module? Where exactly it is looking for Whisper module?

**Comment by piotr1212** [comment]
Python searches **exactly** the paths specified in its **PYTHONPATH** for modules. You can run `python -c 'import sys; print(sys.path)'` to find out the specified path. If using a custom path it would look something like `PYTHONPATH=/tmp/foo/bar python -c 'import sys; print(sys.path)'`. see https://docs.python.org/3.7/library/sys.html#sys.path and https://docs.python.org/3.7/using/cmdline.html#envvar-PYTHONPATH for more info.

Anyway, I've closed this as this is not an issue. I think I gave you enough pointers to figure it out yourself. I can't help you any further.
