### ISSUE TITLE
How to calculate ratio of multiple series list with different length ?

### ISSUE THREAD

**Issue by dumbdonkey** [graphite-project/graphite-web#2429]
I have a metrics like following:

someprefix.host=\*.age=\*.unreaded

first asterisk part stands for a different host.

second asterisk part stands for people with different ages.

What I want to get is the ratio of current metric value to metric value of same time yesterday.  The metric value should be calculated as the summary of all hosts in every 5 minutes by every age group.

I find a solution to use expression  'divideSeriesLists(summarize(groupByNode(someprefix.host=\*.age=\*.unreaded,2,"sum"),'5minutes'),summarize(timeShift(groupByNode(someprefix.host=\*.age=\*.unreaded,2,'sum'),'1d'),'5minutes'))'.

this would be ok if yesterday series lists have the same length as today one. what if they have different lengths, I want to find a robust method. 

Hope I've made myself clear. thanks a lot. 

By the way. I'm poor at English. I guess I've made a lot of grammar mistakes. if you can help me point it out, it would be very nice.

**Comment by deniszh** [comment]
Hi @dumbdonkey ,

Sorry, I'm not really sure what you trying to achieve in general.
E.g., dividing two series of same length makes sense - divide [1,1,1] to [2,2,2] will give you [0.5,0.5,0.5]
But how you can divide two series of different length?
What you're expecting when trying to delete [1,1,1,1] to [2,2] ? Graphite has not matrix or vector operations...

Also, all your asterisks are gone, so, it's quite hard to understand your original question. Maybe dividing different series list is not even needed...

**Comment by DanCech** [comment]
You should check out https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.asPercent 

By passing the nodes you want to aggregate on it will handle the situation where there are series missing.

**Comment by dumbdonkey** [comment]
> Hi @dumbdonkey ,
> 
> Sorry, I'm not really sure what you trying to achieve in general.
> E.g., dividing two series of same length makes sense - divide [1,1,1] to [2,2,2] will give you [0.5,0.5,0.5]
> But how you can divide two series of different length?
> What you're expecting when trying to delete [1,1,1,1] to [2,2] ? Graphite has not matrix or vector operations...
> 
> Also, all your asterisks are gone, so, it's quite hard to understand your original question. Maybe dividing different series list is not even needed...

I have re-edited my question, hope it is clear now.

**Comment by dumbdonkey** [comment]
hi @deniszh , I've re-edited my question, hope that is clear now.

**Comment by dumbdonkey** [comment]
@deniszh

**Comment by dumbdonkey** [comment]
@deniszh  most of the time,  yesterday series has the same length as current ones. what if we lost some ages in yesterday series, but they do exist in current ones.  then they have different length, divideSeriesLists will give a wrong answer.

eg:

yesteday:  age=0  [10], age=30 [50], age=50 [60]

current:     age=0  [10], age=10 [20], age=30 [50]

since we lost "age=10" in yesterday, divideSeriesLists will try to divide "age=10" by "age=30", which is not expected.
