### ISSUE TITLE
how to calculate difference of series with tags?

### ISSUE THREAD

**Issue by dumbdonkey** [graphite-project/graphite-web#2430]
my metric is like this, 
```
realtime.evaluation.freq=*.unreaded

freq has some different values like 0,1,2,3 etc.
```

I want to calculate the difference of every freq between current hour and last hour . how can I achieve it? thanks!

**Comment by DanCech** [comment]
You'll want to take your series and a time-shifted copy, then take the difference of each pair grouped by the freq (node 2 since you aren't actually using tags).
```
groupByNodes(group(realtime.evaluation.freq=*.unreaded, timeShift(realtime.evaluation.freq=*.unreaded, "-1h")), "diff", 2)
```

**Comment by dumbdonkey** [comment]
@DanCech thanks for your reply. I still need to summarize the data into interval bucket of 1 hour. 

I try to write an expression refer yours, well it didn't work. 

the expression is following:

```
groupByNodes(group(summarize(realtime.evaluation.freq=*.unreaded,'1h'), summarize(timeShift(realtime.evaluation.freq=*.unreaded, "-1h"),'1h')), "diff", 2)

```

**Comment by DanCech** [comment]
I would suggest putting the `summarize()` call inside the `timeShift()`:
```
groupByNodes(group(summarize(realtime.evaluation.freq=*.unreaded,'1h'), timeShift(summarize(realtime.evaluation.freq=*.unreaded,'1h'), "-1h")), "diff", 2)
```
