### ISSUE TITLE
functions order affect final result?

### ISSUE THREAD

**Issue by dumbdonkey** [graphite-project/graphite-web#2434]
I have a complicated metric like following

```
tags.realtime.evaluation.*.freq=*.unreaded

the asterisk stands for there are  different values
```

What I want to get is the difference value between current hour and previous hour of every freq label. (metric interval is 60s.)

According to #2430 I've made two expressions like following:

the one show correct answer:

```
groupByNodes(group(groupByNodes(summarize(tags.realtime.evaluation.*.freq=*.unreaded,'1h'),'sum',4),groupByNodes(summarize(timeShift(tags.realtime.evaluation.*.freq=*.unreaded,'1h'),'1h'),'sum',4)), "diff", 0)

```
 
the one show wrong answer:

```
groupByNodes(group(summarize(groupByNodes(tags.realtime.evaluation.*.freq=*.unreaded,'sum',4),'1h'),summarize(groupByNodes(timeShift(tags.realtime.evaluation.*.freq=*.unreaded,'1h'),'sum',4),'1h')), "diff", 0)

```

I've tried to debug second expression (the wrong one) and found the issue is function aggKey in 'render/functions.py' didn't give the right key.

![image](https://user-images.githubusercontent.com/16414369/55222385-bd61c380-5246-11e9-850e-1c20fe764ffa.png)

I will change my metric so I won't need to write such a complicated graphite expression,  before that I guess it would be better if I report this problem to you

**Comment by deniszh** [comment]
Hi @dumbdonkey ,
Thanks for your report. Yes, Graphite functions are quite complex and not always idempotent (i.e. function order matter) - that's a known thing. For example, you should have derivatives to be close to data source as possible otherwise you will have nasty spikes.
But this one can be treated as a bug, probably.
