### ISSUE TITLE
ImportError after updating icinga2 and graphite-web

### ISSUE THREAD

**Issue by Kulturserver** [graphite-project/graphite-web#2435]
We've installed the latest versions of icinga2 and graphite-web from the debian 9 backports. After that we weren't able to access the graphs of graphite-web anymore. The following error is shown:

[wsgi:error] [pid 9729] [remote
2001:16b8:4009:1e00:b6b5:2fff:fece:5239:33630] ImportError: cannot import name
smart_text

Anybody got a hint what might be the problem? Thanks!

We use the following:

Debian 9.8
icinga 2.6.2.
python 2.7.13 & 3.5.3
Graphite-web: 1.0.2
python-django: 1.10.7
python-whisper: 1.0.2

**Comment by piotr1212** [comment]
I'm expecting some Django incompatibility. Have you already contacted the package maintainers?

**Comment by deniszh** [comment]
According to https://github.com/graphite-project/graphite-web/issues/1252#issuecomment-113198137 it's because of django-tagging module. Please downgrade it to 0.4.6

**Comment by Kulturserver** [comment]
The current django-tagging version had been 0.3.1. We've updated it via the Debian 9 backports, but only 0.4.5 seems to be available. With this version, it unfortunately still doesn't work.

**Comment by deniszh** [comment]
Sorry, only 0.4.6 will work.

**Comment by piotr1212** [comment]
I would recommend you to use virtualenv or conda so that you can install all dependencies isolated from your os.
