### ISSUE TITLE
Getting read timeout from webserver

### ISSUE THREAD

**Issue by ceastman-ibm** [graphite-project/graphite-web#2437]
I am deploying graphite into an kubernetes container based upon this helm chart: https://github.com/kiwigrid/helm-charts/tree/master/charts/graphite 

We are sending data into it but are seeing these in the console output:
HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=5)

i have increased the following environment variables to these current levels which seems to have helped decrease the frequency of the time outs but they are still there:

        - name: GRAPHITE_WSGI_PROCESSES
          value: "8"
          value: "64"
        - name: GRAPHITE_WSGI_THREADS
          value: "4"
          value: "16"
        - name: GRAPHITE_WSGI_REQUEST_TIMEOUT
          value: "130"
          value: "1200"
        - name: GRAPHITE_WSGI_MAX_REQUESTS
          value: "10000"
          value: "100000"

**Comment by ceastman-ibm** [comment]
[graphite-0] 05/04/2019 22:51:22 :: [tagdb] Error tagging metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.pagexray.contentTypes.html.contentSize, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.pagexray.contentTypes.html.transferSize, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.domContentLoadedTime.p99, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.domContentLoadedTime.p90, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.domContentLoadedTime.p10, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.domContentLoadedTime.min, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.domContentLoadedTime.stddev, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.domContentLoadedTime.mdev, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.domContentLoadedTime.mean, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.domContentLoadedTime.median, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.backEndTime.max, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.backEndTime.p99, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.backEndTime.p90, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.backEndTime.p10, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.backEndTime.min, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.backEndTime.stddev, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.backEndTime.mdev, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.backEndTime.mean, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.backEndTime.median, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.favicon.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.documentRedirect.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.cssSize.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.connectionKeepAlive.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.compressAssets.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.cacheHeadersLong.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.cacheHeaders.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.assetsRedirects.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.thirdPartyAsyncJs.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.spof.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.jquery.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.inlineCss.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.googletagmanager.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.fastRender.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.cssPrint.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.avoidScalingImages.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.score, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.visualMetrics.VisualReadiness.p99, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.userTimings.measures.bluemix_mark_header_initialize_measure.p90, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.pagexray.thirdParty.contentTypes.image.transferSize, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.info.thirdparty.newrelic, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.browsertime.statistics.timings.pageTimings.pageDownloadTime.mdev, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.pageSummary.cloud_ibm_com._catalog_infrastructure_bare-metal.chrome.cable.coach.advice.performance.adviceList.cacheHeaders.score, carbon.agents.graphite-0-a.activeConnections, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.summary.cloud_ibm_com.chrome.cable.pagexray.contentTypes.json.contentSize.min, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.summary.cloud_ibm_com.chrome.cable.browsertime.userTimings.measures.catalog-styles-ready-measure.median, metrics1.ibm.env5_global.ace.perf.production.sitespeed4.authenticated.us-south-austin-1.repeatView.summary.cloud_ibm_com.chrome.cable.browsertime.pageTimings.frontEndTime.min, stats.timers.view.graphite.tags.views.POST.sum_squares_90: Error requesting http://127.0.0.1:8080/tags/tagMultiSeries: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=5)

**Comment by deniszh** [comment]
Hello @ceastman-ibm,
If I understand the issue correctly it's related to Graphite configuration, so, it's probably better to ask the author of helm chart.

**Comment by Stephan3555** [comment]
Hi @ceastman-ibm,
we are running in the same behavior lately. You ever figured out why this is happening?

**Comment by max-schmidt54321** [comment]
Same here. Did you figure it out?
