### ISSUE TITLE
All files of the System

### ISSUE THREAD

**Issue by Siddhu1096** [graphite-project/graphite-web#2438]
Hi Team,

How to add all the folders and sub-folders of the system on graphite?

Thanks,
Siddharth

**Comment by deniszh** [comment]
Hello,

Could you please elaborate your question a bit? It’s not clear tbh what you
mean

**Comment by Siddhu1096** [comment]
Yes, I want to see all the folders and sub folders on the particular users account when they log in.
I have integrated Graphite with Grafana.

**Comment by piotr1212** [comment]
Could you please be more specific?

**Comment by Siddhu1096** [comment]
![123](https://user-images.githubusercontent.com/22325249/55716759-6cf02000-5a15-11e9-9ef7-294301a98d5d.PNG)
I can only see a single folder on each server, My requirement is to see all the folders in each server,

**Comment by Siddhu1096** [comment]
![123](https://user-images.githubusercontent.com/22325249/55716759-6cf02000-5a15-11e9-9ef7-294301a98d5d.PNG)
I can only see a single folder on each server, My requirement is to see all the folders in each server,

**Comment by piotr1212** [comment]
Are you sending the data you want to see to Graphite? 

Please note that Graphite is "just" a database, it does not collect data, it can only show you data which you send it.

**Comment by Siddhu1096** [comment]
Okay. So which tool should I install to see all files of my PC through graphite?

**Comment by piotr1212** [comment]
If you want help from others it helps by explaining exactly what you want to achieve and be specific about it. I still have no clue what you are asking.

**Comment by Siddhu1096** [comment]
Okay. So we have many folders residing in my machine. For example, you see nciwin folder on above photo right? Like that I've folder called energy, drive1 etc. inside the servers. But it's displaying only nciwin folder.
I want to list all the folders, That's my aim. @piotr1212

**Comment by piotr1212** [comment]
Your answer just raises more questions to me. I'm sorry can't help you.
