### ISSUE TITLE
Change y-axis labels to % for line chart

### ISSUE THREAD

**Issue by philliprognerud** [graphite-project/graphite-web#2441]
It doesn’t seem like graphite supports changing the y-axis labels to percentages on **line charts**, but they support it on pie charts, oddly enough: https://graphite.readthedocs.io/en/latest/render_api.html?highlight=y-axis#valuelabels

I looked at the meta data from an svg formatted image. Surely enough they have a `y.labels` array for y-axis, but you can’t modify it through their Render URL API as a parameter??

```
"y": {
        "labelValues": [0, 0.25, 0.5, 0.75, 1.0],
        "labels": ["0 ", "0.25 ", "0.50 ", "0.75 ", "1.00  "],
        "step": 0.25
      }
```
Here's what I currently have: 

`/render?target=asPercent(node.load_avg.one,1)&format=png&yMax=100&yStep=25`

This takes the node load average and return percentages. For example, if a value was 0.75 it would convert it to 75. However, the y-axis does not display "%" character next to the ySteps. A small thing, but it would be nice if I could make it say 75% instead of 75...

Here's what I want:

```
"y": {
        "labelValues": [0, 25, 50, 75, 100],
        "labels": ["0%", "25%", "50%", "75%", "100%"],
        "step": 25
      }
```

It would be nice if we could change the y-axis labels through the Render URL API. The documentation doesn't specify a way to do so from what I'm reading. If there is a way, please reply :)!

**Comment by piotr1212** [comment]
I just commented on your SO question. Anyway I think it is easy doable by adding a 'unit' parameter. It is already implemented in https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/glyph.py#L1947 but that is never called with an actual value

**Comment by deniszh** [comment]
According to code -  https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/glyph.py#L1759-L1761 - `valuelabels` parameter applying only to piecharts, indeed.
So, currently, it's not supported for any other chart.

**Comment by deniszh** [comment]
Yep, what @piotr1212 said.

**Comment by piotr1212** [comment]
You could also just set a % in the vtitle..

**Comment by philliprognerud** [comment]
> You could also just set a % in the vtitle..

That will probably be the backup plan if we can't customize the y-axis labels :). It may be a good idea for future users to have custom x,y axis labels though.
