### ISSUE TITLE
Availability KPI 

### ISSUE THREAD

**Issue by iakovgan** [graphite-project/graphite-web#2453]
I wonder if there is a possibility to easily calculate availability kpi? 

let's say we have a metric that is:
 * 1 when service is up and
*   0 when service is down. 

Is there a way to measure on given interval what was the percent of service availability? Sum of 1-s divided by a total number of points in the interval?

**Comment by DanCech** [comment]
You can just take the average, if you want a single value the simplest way is to use consolidateBy('average') and maxDataPoints=1
