### ISSUE TITLE
How to hide webapp from unauthorized users?

### ISSUE THREAD

**Issue by sevaTechoPark** [graphite-project/graphite-web#2455]
I wanna require authorize to view metrics.
Thank you

**Comment by deniszh** [comment]
Graphite itself does not provide that feature, unfortunately. You can install Apache or Nginx in front of graphite-web for doing that.
E.g. https://christianfei.com/posts/setup-nginx-as-a-reverse-proxy-with-basic-auth-for-an-upstream/
