### ISSUE TITLE
aggregation functions

### ISSUE THREAD

**Issue by sevaTechoPark** [graphite-project/graphite-web#2456]
In [docs about functions](https://graphite.readthedocs.io/en/latest/functions.html) we can often read this:
> This function can be used with aggregation functions average, median, sum, min, max, diff, stddev, count, range, multiply & last.

but there is not description about this functions.
I used trial and error method and figure out how to work `count` and `last` (`average`, `median`, `min`, `max`, `sum` - is obviously)

- [x] average
- [x] median
- [x] sum
- [x] min
- [x] max
- [ ] diff
- [ ] stddev
- [x] count
- [ ] range
- [ ] multiply
- [x] last

so can you explain me: how to work this function or give me link to doc

----
I have counter of request count and I wanna see the count of reqest at some range.
I try to use [summarize](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.summarize) function but I did not understand how to do it.
please help me

**Comment by deniszh** [comment]
Well, we had an issue somewhere for documenting aggregate functions. 
Currently, looking in the code is the only option - https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L261-L274
All `safeX` functions code is also in the same file.
`range` is float(max(series)) - float(min(series)), not sure if it is what you looking for...

**Comment by sevaTechoPark** [comment]
okay may be you can tell me how can I solve my popular case?
> I have counter of request count and I wanna see the count of reqest at some range.

**Comment by deniszh** [comment]
Not sure if I understand your question, could you elaborate it a bit?

**Comment by sevaTechoPark** [comment]
I have the graph that only increase

![image](https://user-images.githubusercontent.com/28502082/60032844-10b1a980-96b0-11e9-9766-d3f4b7112b52.png)

but I wanna pick range (for example: last 3 hours) and see request count by this range

**Comment by piotr1212** [comment]
Not sure what you mean but wouldn't derivative() work for you?

**Comment by deniszh** [comment]
@sevaTechoPark : you probably looking for [summarize()](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.summarize) function

**Comment by sevaTechoPark** [comment]
@deniszh
> @sevaTechoPark : you probably looking for [summarize()](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.summarize) function

yes and I have written it
> I try to use summarize function but I did not understand how to do it.

Could you write me how to use this function for my case

**Comment by deniszh** [comment]
@sevaTechoPark: maybe it will be better explain what are you doing, what are you expecting, and what you getting instead, and what exactly not working for you?
Instead of me citing documentation.
Thanks!

**Comment by sevaTechoPark** [comment]
I have a counter `http_request_count` for each API method.
for example:
`user.get.http_request_count.value 5595655469`
`user.signUp.http_request_count.value 2344`
I need to see http_request_count from 23.06.2019 to 24.06.2019
Not total. Only for 1 day.

**Comment by sevaTechoPark** [comment]
@piotr1212 
Unfortunately, it is not that
and you sent us your `email_token`

**Comment by piotr1212** [comment]
> I need to see http_request_count from 23.06.2019 to 24.06.2019

https://graphite.readthedocs.io/en/latest/render_api.html#from-until

**Comment by sevaTechoPark** [comment]
@piotr1212 
And I will see total `http_request_count` to 24.06.2019
not from 23.06.2019 from start

**Comment by piotr1212** [comment]
@sevaTechoPark I'm sorry but I do not understand your question.

**Comment by deniszh** [comment]
`smartSummarize(user.get.http_request_count.value, '1d', func='sum')` is not working  for you?

**Comment by deniszh** [comment]
or just `summarize($server_name.$disk.df_complex-used, '1d', 'sum', True)`

**Comment by sevaTechoPark** [comment]
https://github.com/graphite-project/graphite-web/issues/2456#issuecomment-506316447
This does not work as I need

**Comment by deniszh** [comment]
@sevaTechoPark : could you please explain why does not work as you need and what do you need then?

**Comment by deniszh** [comment]
Try also `hitcount(user.get.http_request_count.value, '1d', True)`. But it's hard to guess without know why `summarize()` is not working for you

**Comment by sevaTechoPark** [comment]
@deniszh 
because it shows the wrong numbers
I have a total query counter, which is only growing. And there is a need to see the number of requests in a certain period of time. For example, in 4 hours of the last day. Or in the last 15 minutes.
The problem is that I see the value of the counter at this point in time, and not the number of requests in this interval.
With the help of utitlity ab, I generated a certain traffic. Therefore, I know how to check functions. I have generated 30,000 requests, and your functions show millions.
Essentially, I need a difference between the largest and the smallest value in a given time interval.

**Comment by deniszh** [comment]
Strange. `hitcount()` should do exactly what you want. Check e.g. this article - https://medium.com/socialbakers-engineering/usage-and-performance-monitoring-with-graphite-ce7919732c03

**Comment by DanCech** [comment]
@sevaTechoPark I think I understand, you have a counter that has say value 4 at time t1, and value 7 at time t2, and you want to be able to calculate that the counter increased by 3 during that interval?

The best way to do this (which will handle things like counter reset gracefully) is to use [nonNegativeDerivative](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.nonNegativeDerivative) which will translate each value in the series from the raw counter value to the amount that the counter changed during that interval.

If you then want to get only a single value back from Graphite that represents the total change, I would use `maxDataPoints=1` and `consolidateBy("sum")`.

So your final query would look like `user.get.http_request_count.value | nonNegativeDerivative() | consolidateBy("sum")`

In Grafana you can set `maxDataPoints=1` in the query options.

**Comment by sevaTechoPark** [comment]
@DanCech 
yes, you have understood :heart_eyes: :tada:

**Comment by sevaTechoPark** [comment]
![image](https://user-images.githubusercontent.com/28502082/60279272-67fe8680-9909-11e9-9ed6-de5d5ea6cad4.png)
total should be `69046 - 20329 = 48717`
but with `nonNegativeDerivative() | consolidateBy("sum")`
![image](https://user-images.githubusercontent.com/28502082/60279508-d80d0c80-9909-11e9-88cc-a4c5a59ec23d.png)
but total `47577`
difference: `1140` 
fault: `(|47577 - 48717|) / 48717 * 100 = 2.34%`

Is it okay?

**Comment by DanCech** [comment]
You may have an issue with missing data points, if you have `1, null, 3, 4` then the nonNegativeDerivative is going to return `null, null, null, 1` instead of `null, null, 2, 1`.

Try adding `keepLastValue()` before the `nonNegativeDerivative` and see whether that improves things.

It will translate `1, null, 3, 4` to `1, 1, 3, 4` so `nonNegativeDerivative` would then yield `null, 0, 2, 1` giving the correct total.

**Comment by sevaTechoPark** [comment]
![image](https://user-images.githubusercontent.com/28502082/60281331-70f15700-990d-11e9-8eb3-dce4d7dcfb52.png)

**Comment by sevaTechoPark** [comment]
thank you very much
