### ISSUE TITLE
Graphite server crash due to memory leak

### ISSUE THREAD

**Issue by usmanC9** [graphite-project/graphite-web#2457]
Hi,

Graphite node continuously crashes after some queries due to memory leak. My configuration include 1 carbon-relay instance and 2 carbon-caches. I have increased the FETCH_TIMEOUT and FIND_TIMEOUT in local_settings.py to 600 and 300 sec respectively. 
VM specs are 6vcpus and 8GB RAM.

Some of the sample queries are:
aliasSub(summarize(nPercentile(icinga2.\*.services.interface\*.\*interface\*.perfdata.\*_out_bps.value,90), '1y', 'max', 'false'), '(.\*)icinga2.(.\*).services.*.perfdata.(.\*)_(in|out)_bps.\*', 'Node  (\2) Interface (\3)')

aliasSub(highestCurrent(summarize(icinga2.\*.services.interface\*.interface-dual.perfdata.\*in_prct.value, '1y', 'average', 'true'), 25) , '(.\*)icinga2.(.\*).services.\*.perfdata.(.\*)_in_prct.\*', 'Node (\2) Interface (\3)')

![graphite-usage](https://user-images.githubusercontent.com/17683147/60033449-07c9d380-96c2-11e9-90dd-169766aed249.PNG)

Any help would be appreciated.

Thanks,

**Comment by piotr1212** [comment]
Are you sure it is a `leak`, not just using a lot of memory?

**Comment by deniszh** [comment]
That's probably not a leak, Graphite requires RAM to cache data. You can limit cache size in `carbon.conf`, by default, it's `Inf`. 
On the other hand, that probably will increase disk load even more. Unfortunately, you  need to make some experiments to properly tune it.
Maybe you need just bigger server or you can try to replace `carbon-relay` and 2 `carbon-caches` with single [go-carbon](https://github.com/lomik/go-carbon) instance - but usually, it does not help with RAM consumption, but with CPU load.

**Comment by usmanC9** [comment]
I have increased the RAM from 8GB to 16GB, now memory issue is resolved but all CPUs are showing 100% utilization when i query the graphite server.

![graphite-cpu](https://user-images.githubusercontent.com/17683147/60249314-0c6ad380-98de-11e9-8d31-9dee39bf6e2f.PNG)

**Comment by piotr1212** [comment]
If you want to improve your performance I can suggest you to tune your storage-schemas.conf. You summarize with interval "1y", so you could use a wide grained archive. Storing less metrics can improves retrieval performance a lot. Less data needs to be fetched, less memory needed and less cpu cycles for processing the data. The downside is that storing the metrics will be heavier. Don't forget to resize existing wsp files after you change storage-schames.conf.

Other than that "100% CPU usage" does not have to be a bad thing, at least you are using your hardware ;)
