### ISSUE TITLE
Graphite Start Up Error

### ISSUE THREAD

**Issue by gregorywolf** [graphite-project/graphite-web#2459]
Hello - 
I am starting up graphite using a docker image )graphiteapp/graphite-statsd:1.1.5-12). If I do not specify any options other than -p 2003:2003 and -p8080:8080 everything works fine. I examine the various logs and they look clean. However as soon as I add the following 2 docker options:

-v $PWD/graphite/configs:/opt/graphite/conf \
-v $PWD/graphite/data:/opt/graphite/storage \

The carbon.log generates the following error:
Traceback (most recent call last):
  File "/opt/graphite/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/graphite/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/graphite/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/graphite/lib/carbon/writer.py", line 189, in writeForever
    writeCachedDataPoints()
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/writer.py", line 142, in writeCachedDataPoints
    state.database.create(metric, archiveConfig, xFilesFactor, aggregationMethod)
  File "/opt/graphite/lib/carbon/database.py", line 145, in create
    self.sparse_create, self.fallocate_create)
  File "/opt/graphite/lib/python3.7/site-packages/whisper.py", line 528, in create
    fallocate(fh, headerSize, remaining)
  File "/opt/graphite/lib/python3.7/site-packages/whisper.py", line 93, in _py_fallocate
    raise IOError(res, 'fallocate')
builtins.OSError: [Errno 95] fallocate

Not sure what I am doing wrong. Can anyone tell me how to fix the error condition? I am also attaching the full log as well.

Thank you!!

[carbon.log](https://github.com/graphite-project/graphite-web/files/3343350/carbon.log)

**Comment by ploxiln** [comment]
My initial guess is that it's a permissions error - probably the uid used in the container is now allowed to write (or create files in) to `$PWD/graphite/data/`

**Comment by gregorywolf** [comment]
I checked the permissions of the data folder and it is 755. As a test I changed the permissions to 777 for all subfolders. Unfortunately I am still getting the error. Assuming it is a permissions issue, is there a way to change the permissions of the target folder of the external mount point to allow the container UID the correct permissions to write?

**Comment by ploxiln** [comment]
... in that case, maybe it is the fallocate operation itself, maybe this is because of the filesystem type or something. You can disable fallocate in carbon.conf, see https://github.com/graphite-project/carbon/blob/1.1.5/conf/carbon.conf.example#L208

**Comment by deniszh** [comment]
@gregorywolf : Your underlying FS not supporting FALLOCATE. `WHISPER_FALLOCATE_CREATE = False` should fix the problem - https://github.com/graphite-project/docker-graphite-statsd/issues/78
I was thinking even to disable it by default in Docker image, but IMO it's a bit overkill.

**Comment by gregorywolf** [comment]
Hello - 
Thank you for the help!! Setting WHISPER_FALLOCATE_CREATE = False in carbon.log fixed the problem!!!
