### ISSUE TITLE
Graphite Web Nginx + Gunicorn setup failure

### ISSUE THREAD

**Issue by caldavid** [graphite-project/graphite-web#2460]
Hi !

I've been following the documentation at here:

 https://graphite.readthedocs.io/en/latest/config-webapp.html 

to setup the nginx+gunicorn for graphite-web, and encountered following issue:

> [2019-07-02 17:36:09 +0000] [13713] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named graphite_wsgi
[2019-07-02 17:36:09 +0000] [13713] [INFO] Worker exiting (pid: 13713)
[2019-07-02 17:36:09 +0000] [13668] [INFO] Shutting down: Master
[2019-07-02 17:36:09 +0000] [13668] [INFO] Reason: Worker failed to boot.

All i did that isn't on the doc was copied the graphite.wsgi file from **conf** folder to **webapp/graphite/**

Would you please help to point out the root cause?

Thanks a lot!
David

**Comment by deniszh** [comment]
Hi @caldavid ,
You can try solution from Stackoverflow - https://stackoverflow.com/questions/22158635/graphite-and-gunicorn-config-issue-or-path-issue

**Comment by caldavid** [comment]
Hi @deniszh

Thanks for the hint, that worked!

But i've got stuck at Nginx layer, it seems that the Nginx is showing default page instead of the graphite.

Here is what I have so far:

Got Gunicorn running, bind to gunicorn.sock, tested with curl local gunicorn socket, got following response  `curl --unix-socket /run/gunicorn.sock 0.0.0.0`:

> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
> 
> 
> <html>
>   <head>
>     <title>Graphite Browser</title>
>   </head>
> 
> 
> <frameset rows="80,*" frameborder="1" border="1">
>   <frame src="/browser/header" name="Header" id='header' scrolling="no" noresize="true" />
>   
>     <frame src="/composer?" name="content" id="composerFrame"/>
>   
> </frameset>
> </html>


My Gunicorn service file looks like this:

> [Unit]
> Description=gunicorn daemon
> After=network.target
> 
> [Service]
> User=root
> Group=apache
> WorkingDirectory=/opt/graphite/webapp
> ExecStart=/usr/bin/gunicorn wsgi --workers=4 --bind=unix:/run/gunicorn.sock --log-file=/var/log/gunicorn.log --preload --pythonpath=/opt/graphite/webapp/graphite
> 
> [Install]
> WantedBy=multi-user.target


My nginx site-available/graphite looks like this:

> server {
>     listen 80 default_server;
>     server_name "**my_ip**";
> 
>     graphite /opt/graphite/webapp;
> 
>     access_log /var/log/nginx/graphite.access.log;
>     error_log  /var/log/nginx/graphite.error.log;
> 
>     location = /favicon.ico {
>         return 204;
>     }
> 
>     # serve static content from the "content" directory
>     location /static {
>         alias /opt/graphite/webapp/content;
>         expires max;
>     }
> 
>     location / {
>         #try_files $uri @graphite;
>         include proxy_params;
>         proxy_pass http://unix:/run/gunicorn.sock;
>     }
> 
>     location @graphite {
>         proxy_pass_header Server;
>         proxy_set_header Host $http_host;
>         proxy_redirect off;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Scheme $scheme;
>         proxy_connect_timeout 10;
>         proxy_read_timeout 10;
>         proxy_pass http://graphite;
>     }
> 

I have been checking around, but didn't find useful solution to me. Please help~

**Comment by deniszh** [comment]
Just remove 
`server_name "my_ip";`
line from config above and restart Nginx.

**Comment by caldavid** [comment]
still no luck, default page shown.
should i touch my nginx.conf?

`user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;
        #include /etc/nginx/sites-enabled/*;
        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
}`

**Comment by deniszh** [comment]
Uncomment sites-enabled line

**Comment by ploxiln** [comment]
This server block is what's showing the nginx default page:

```
    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;
        #include /etc/nginx/sites-enabled/*;
        location / {
        }
```

I'm not sure if that sites-enabled line is in the right place - I think these "sites" configs usually have a server block, and I don't think you can put a server block inside a server block.

It's arbitrary anyway. I'd just remove that entire server block, and include your nginx-graphite config in its stead (e.g. replace that whole server block with `include /etc/nginx/sites-available/graphite;` or whatever).

**Comment by caldavid** [comment]
@ploxiln @deniszh  That did the trick !!!!  
And I also removed `include proxy_params;` which causing the trouble.

Thank so much you guys!  Happy 4th~
