### ISSUE TITLE
New transform functions: power, exponential

### ISSUE THREAD

**Issue by avorozhtsov** [graphite-project/graphite-web#2465]
Now we have two transform functions -  scale and log.
I would like to have some more:
* exponential:  alpha^series, alpha is constant  argument, default is E
* power: series^alpha, where alpha is constant argument
* sigmoid:  1/(1 + exp(-series)) 
* logit: log(1 / (1 - series))
* add: series + alpha, where alpha is constant  argument

**Comment by deniszh** [comment]
Hi @avorozhtsov ,
`power` is already there - https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.pow
`add` can be done with `sumSeries(series, constantLine(constant))`.
Same for `exponential` - `powSeries(constantLine(constant), series)`.
Rest are quite easy to implement, e.g. using [pow()](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L1459-L1485) source as reference.

**Comment by piotr1212** [comment]
@avorozhtsov any chance you could test https://github.com/graphite-project/graphite-web/pull/2466

**Comment by piotr1212** [comment]
@avorozhtsov Could you please test #2466 ?

**Comment by avorozhtsov** [comment]
It works, thanks

**Comment by deniszh** [comment]
#2466 merged to master
