### ISSUE TITLE
Carbon Installation Failing Using PIP

### ISSUE THREAD

**Issue by gregorywolf** [graphite-project/graphite-web#2469]
Hi - I am trying to install the latest versions of graphite-web, whisper and carbon. I am working on a CentOS VM. I have used the following commands successfully:

`sudo yum -y install gcc openssl-devel bzip2-devel libffi libffi-devel`
`sudo pip install --upgrade setuptools --user python`
`sudo pip install graphite-web`
`sudo pip install whisper`

However, when I use
`sudo pip install carbon`
It starts out fine but then fails:
`Collecting carbon
  Using cached https://files.pythonhosted.org/packages/aa/8e/f46551cd1a6ad212fe956249406a491dd866ed7c271839da828a94e7bd67/carbon-1.1.5.
tar.gz
Collecting Twisted (from carbon)
  Using cached https://files.pythonhosted.org/packages/79/59/035de19362320e632301ed7bbde23e4c8cd6fc5e2f1cf8d354cdba857854/Twisted-19.2.
1.tar.bz2
Collecting txAMQP (from carbon)
  Using cached https://files.pythonhosted.org/packages/c6/a0/7c18f4a3805af57e2be19a6502c1946f5dac51c8b1ed19368968a46a2f07/txAMQP-0.8.2.
tar.gz
Collecting cachetools (from carbon)
  Using cached https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.
1.1-py2.py3-none-any.whl
Requirement already satisfied: urllib3 in /usr/lib/python2.7/site-packages (from carbon) (1.10.2)
Requirement already satisfied: zope.interface>=4.4.2 in /usr/lib64/python2.7/site-packages (from Twisted->carbon) (4.6.0)
Requirement already satisfied: constantly>=15.1 in /usr/lib/python2.7/site-packages (from Twisted->carbon) (15.1.0)
Requirement already satisfied: incremental>=16.10.1 in /usr/lib/python2.7/site-packages (from Twisted->carbon) (17.5.0)
Requirement already satisfied: Automat>=0.3.0 in /usr/lib/python2.7/site-packages (from Twisted->carbon) (0.7.0)
Requirement already satisfied: hyperlink>=17.1.1 in /usr/lib/python2.7/site-packages (from Twisted->carbon) (19.0.0)
Requirement already satisfied: PyHamcrest>=1.9.0 in /usr/lib/python2.7/site-packages (from Twisted->carbon) (1.9.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python2.7/site-packages (from Twisted->carbon) (19.1.0)
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from txAMQP->carbon) (1.9.0)
Requirement already satisfied: setuptools in /root/.local/lib/python2.7/site-packages (from zope.interface>=4.4.2->Twisted->carbon) (41
.0.1)
Requirement already satisfied: idna>=2.5 in /usr/lib/python2.7/site-packages (from hyperlink>=17.1.1->Twisted->carbon) (2.8)
Installing collected packages: Twisted, txAMQP, cachetools, carbon
  Running setup.py install for Twisted ... error
    ERROR: Complete output from command /usr/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-JC7Z1x/Twist
ed/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec
(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-OyAolK/install-record.txt --single-version-externally-manag
ed --compile:
    ERROR: running install
    running build
    running build_py`

The RED error messages continue for quite some time.
I also tried installing using the following:

`sudo wget https://files.pythonhosted.org/packages/aa/8e/f46551cd1a6ad212fe956249406a491dd866ed7c271839da828a94e7bd67/carbon-1.1.5.ta
r.gz'

Then tar'ing it and running 
'sudo python setup.py install`

This appears to work but the service carbon-cache doe snot get installed which leads me to believe that it is really not working. 

Any help would be much appreciated. Thank you.

**Comment by ploxiln** [comment]
When quoting terminal output, please use "fenced code blocks" so that newlines are preserved, like so:

    ```
    past output here
    the triple-backticks are on their own separate lines
    ```

-------

> sudo pip install --upgrade setuptools --user python

That is suspicious and confusing. You would not generally use `sudo` and `--user` at the same time, and what is that `python` argument, in that command line it would be a package name ...

-----

Installing from pip will never install a system service (e.g. systemd or upstart service unit/config). It will give you a the executable binary or script, and you'll have to create the service config, and put a config file in the correct place. To run carbon-cache in the foreground (and logging to stdout) for my service manager, I configure it to run with the command : `carbon-cache.py --debug start`

**Comment by gregorywolf** [comment]
Hi - Thank you for the ``` guidance!! I have been able to get carbon installed and running.
