### ISSUE TITLE
mod_wsgi (pid=20598): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module

### ISSUE THREAD

**Issue by gregorywolf** [graphite-project/graphite-web#2472]
Hello - I apologize for creating this issue since I have seen "similar" ones. The problem is that I cannot find the solution.

I am trying to stand up Graphite. I am using the following to download all software components:

```
sudo yum -y update
sudo yum -y install tree
sudo yum -y install git
sudo yum -y install wget
sudo yum -y install python-pip
sudo yum -y install gcc
sudo yum -y install httpd mod_wsgi
sudo yum -y install python-devel cairo-devel libffi-devel
sudo pip install --upgrade pip
sudo pip install twisted
sudo pip install cairocffi
sudo pip install Django
sudo pip install django-tagging
sudo pip install scandir
sudo pip install pyparsing
sudo git clone https://github.com/graphite-project/graphite-web.git graphite
sudo git clone https://github.com/graphite-project/carbon.git carbon
sudo git clone https://github.com/graphite-project/whisper.git whisper
``` 
After running through the setup.py in each of the folder I check the dependencies and everything looks good.
```
python check-dependencies.py 
[OPTIONAL] Unable to import the 'memcache' module, do you have python-memcached installed for python 2? This feature is not required but greatly improves performance.
[OPTIONAL] Unable to import the 'ldap' module, do you have python-ldap installed for python 2? Without python-ldap, you will not be able to use LDAP authentication in the graphite webapp.
[OPTIONAL] Unable to import the 'txamqp' module, this is required if you want to use AMQP as an input to Carbon. Note that txamqp requires python 2.5 or greater.
[OPTIONAL] Unable to import the 'python-rrdtool' module, this is required for reading RRD.
[OPTIONAL] Unable to import the 'whitenoise' module. This is useful for serving static files.
[OPTIONAL] Unable to import the 'pyhash' module. This is useful for fnv1_ch hashing support.
6 optional dependencies not met. Please consider the optional items before proceeding.
All necessary dependencies are met.
```
I modify all of the key files for carbon and start the service successfully. I also initialize the graphite database using the following which appears to be successful:

```
sudo PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb
Operations to perform:
  Synchronize unmigrated apps: browser, composer, functions, messages, metrics, render, staticfiles, whitelist
  Apply all migrations: account, admin, auth, contenttypes, dashboard, events, sessions, tagging, tags, url_shortener
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying dashboard.0001_initial... OK
  Applying events.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying tagging.0001_initial... OK
  Applying tagging.0002_on_delete... OK
  Applying tagging.0003_adapt_max_tag_length... OK
  Applying tags.0001_initial... OK
  Applying url_shortener.0001_initial... OK    
```
My graphite root is default - /opt/graphite. My WSGI files resides in /opt/graphite/conf and is a copy of the example provided with the installation. I also modified the local_settings.py by uncommenting the SECRET_KEY and TIME_ZONE.

However, when I start Apache (service httpd start) with /etc/httpd/conf.d/graphite-vhost.conf in place I am getting error log entries, which in turn is preventing my Graphite application to appear in my browser.

```
[Tue Jul 23 21:29:43.450763 2019] [core:notice] [pid 20593] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Tue Jul 23 21:29:43.451663 2019] [suexec:notice] [pid 20593] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Jul 23 21:29:43.462670 2019] [so:warn] [pid 20593] AH01574: module wsgi_module is already loaded, skipping
[Tue Jul 23 21:29:43.464182 2019] [auth_digest:notice] [pid 20593] AH01757: generating secret for digest authentication ...
[Tue Jul 23 21:29:43.465125 2019] [lbmethod_heartbeat:notice] [pid 20593] AH02282: No slotmem from mod_heartmonitor
[Tue Jul 23 21:29:43.467951 2019] [mpm_prefork:notice] [pid 20593] AH00163: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Tue Jul 23 21:29:43.467989 2019] [core:notice] [pid 20593] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Tue Jul 23 17:29:44.630490 2019] [:error] [pid 20598] mod_wsgi (pid=20598): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Tue Jul 23 17:29:44.630550 2019] [:error] [pid 20598] mod_wsgi (pid=20598): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Tue Jul 23 17:29:44.630592 2019] [:error] [pid 20598] Traceback (most recent call last):
[Tue Jul 23 17:29:44.630622 2019] [:error] [pid 20598]   File "/opt/graphite/conf/graphite.wsgi", line 7, in <module>
[Tue Jul 23 17:29:44.630696 2019] [:error] [pid 20598]     from graphite.wsgi import application
[Tue Jul 23 17:29:44.630704 2019] [:error] [pid 20598]   File "/opt/graphite/webapp/graphite/wsgi.py", line 15, in <module>
[Tue Jul 23 17:29:44.630743 2019] [:error] [pid 20598]     application = get_wsgi_application()
[Tue Jul 23 17:29:44.630752 2019] [:error] [pid 20598]   File "/usr/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Tue Jul 23 17:29:44.630790 2019] [:error] [pid 20598]     django.setup(set_prefix=False)
[Tue Jul 23 17:29:44.630798 2019] [:error] [pid 20598]   File "/usr/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
[Tue Jul 23 17:29:44.630851 2019] [:error] [pid 20598]     apps.populate(settings.INSTALLED_APPS)
[Tue Jul 23 17:29:44.630866 2019] [:error] [pid 20598]   File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
[Tue Jul 23 17:29:44.630994 2019] [:error] [pid 20598]     app_config = AppConfig.create(entry)
[Tue Jul 23 17:29:44.631005 2019] [:error] [pid 20598]   File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
[Tue Jul 23 17:29:44.631086 2019] [:error] [pid 20598]     module = import_module(entry)
[Tue Jul 23 17:29:44.631094 2019] [:error] [pid 20598]   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
[Tue Jul 23 17:29:44.631134 2019] [:error] [pid 20598]     __import__(name)
[Tue Jul 23 17:29:44.631139 2019] [:error] [pid 20598]   File "/opt/graphite/webapp/graphite/functions/__init__.py", line 10, in <module>
[Tue Jul 23 17:29:44.631180 2019] [:error] [pid 20598]     from graphite.logger import log
[Tue Jul 23 17:29:44.631185 2019] [:error] [pid 20598]   File "/opt/graphite/webapp/graphite/logger.py", line 106, in <module>
[Tue Jul 23 17:29:44.631232 2019] [:error] [pid 20598]     log = GraphiteLogger() # import-shared logger instance
[Tue Jul 23 17:29:44.631238 2019] [:error] [pid 20598]   File "/opt/graphite/webapp/graphite/logger.py", line 39, in __init__
[Tue Jul 23 17:29:44.631249 2019] [:error] [pid 20598]     level = logging.DEBUG if settings.DEBUG else logging.INFO,
[Tue Jul 23 17:29:44.631254 2019] [:error] [pid 20598]   File "/opt/graphite/webapp/graphite/logger.py", line 78, in _config_logger
[Tue Jul 23 17:29:44.631263 2019] [:error] [pid 20598]     handler = Rotater(log_file, when=when, backupCount=backupCount)
[Tue Jul 23 17:29:44.631270 2019] [:error] [pid 20598]   File "/usr/lib64/python2.7/logging/handlers.py", line 169, in __init__
[Tue Jul 23 17:29:44.631533 2019] [:error] [pid 20598]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Tue Jul 23 17:29:44.631554 2019] [:error] [pid 20598]   File "/usr/lib64/python2.7/logging/handlers.py", line 64, in __init__
[Tue Jul 23 17:29:44.631574 2019] [:error] [pid 20598]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Tue Jul 23 17:29:44.631583 2019] [:error] [pid 20598]   File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__
[Tue Jul 23 17:29:44.631948 2019] [:error] [pid 20598]     StreamHandler.__init__(self, self._open())
[Tue Jul 23 17:29:44.631963 2019] [:error] [pid 20598]   File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
[Tue Jul 23 17:29:44.631976 2019] [:error] [pid 20598]     stream = open(self.baseFilename, self.mode)
[Tue Jul 23 17:29:44.632003 2019] [:error] [pid 20598] IOError: [Errno 13] Permission denied: '/opt/graphite/storage/log/webapp/info.log'
```
As you can see from the log I am running Apache 2.4, mod_wsgi 3.4 and Python 2.7. I am not sure how to resolve the fact that mod_wsgi cannot be loaded as a Python module. 

The other issue I am running into is a permissions issue
```
Permission denied: '/opt/graphite/storage/log/webapp/info.log'
```
I am not sure who should own this directory and what the permissions should be set to.

I want to be careful not to flood this post with too much info. However, I can provide whatever additional info necessary that will help resolve this issue.

Any and all help would be much appreciated!! Thank you

**Comment by ploxiln** [comment]
I think that "Target WSGI script cannot be loaded" _because_ of the "Permission denied" exception for the log file. You could `chown` the log folder `/opt/graphite/storage/log/webapp/` to the user that apache httpd runs as (on ubuntu/debian the user is `www-data`, on redhat/centos I'm not sure). (You could also configure the log to go somewhere else.)

**Comment by gregorywolf** [comment]
Hi @ploxiln Thank you for the input. I tried changing the ownership of the log folder to apache:apache and it still does not work. I think the bigger problem is that I may have a conflict of versions...not sure. The IO permission issue I think is also a problem. Not sure if these are related.

**Comment by gregorywolf** [comment]
Hello @deniszh I have seen your name on a number of posts providing excellent guidance. By any chance could you review my issue and perhaps point me in the right direction to get this problem resolved?

**Comment by cbowman0** [comment]
Are you still seeing the permission error on files in /opt/graphite/storage/log/webapp/?

**Comment by gregorywolf** [comment]
Yes

**Comment by cbowman0** [comment]
Yes.  That would be a blocker.

It could be another directory in the path that is too restrictive and needs perms adjusted.

Try becoming the apache user (`su - apache`, probably) and check if it can ls /opt/graphite/storage/ and the `log` and `whisper` subdirs.

**Comment by gregorywolf** [comment]
Ok. I will try your suggestion. Question. Would it be safest to simply change the ownership of /opt/graphite to apache:Apache along with all of its sub folders?

**Comment by cbowman0** [comment]
I would ok, but maybe a little heavy handed.  Since it made it to the point that the issue is writing to the log files, the conf and webapp dirs have acceptable permissions.  I'd focus on the perms of storage and dirs under it.

Carbon also needs to read/write to the storage dir, so keep that in mind with the ownership or perm changes.

**Comment by cbowman0** [comment]
I can't guarantee that you won't have an issues with something else before this is working 100%.  The permission issue is the current blocker so let's solve it first.

**Comment by gregorywolf** [comment]
I have changed ```chown apache:apache -R /opt/graphite/storage``` and ```chmod 777 -R /opt/graphite/storage``` just to be crazy permissive. Still getting the same log errors.

**Comment by piotr1212** [comment]
Selinux is probably preventing it

**Comment by gregorywolf** [comment]
Hi. How would I get around Selinux? I have been using Centos 7.

**Comment by piotr1212** [comment]
First check if  the full path `/opt/graphite/storage/log/webapp/` exists, if not create it and set correct permissions. Check if all upper paths have the correct permissions, you can set correct permissions to `/opt/graphite/storage` but if `/opt` is not accessible it won't work anyway.

About selinux, if you don't know how to configure it you'd probably better disable it. Otherwise I'd suggest you take the time to properly learn about it, it will bite you a few more times in the future.

Anyway, first verify if you are running selinux with `getenforce`. If it says `enforcing` check your `/var/log/audit/audit.log` if there are some permission denied entries on that directory.

**Comment by gregorywolf** [comment]
Ahhh....Based on your help I am making some progress into the issue. THANK YOU!!! ```/opt/graphite/storage/log/webapp``` exists but ```info.log``` is empty!! Turns out that ```getenforce``` shows ```Enforcing```

As a result when I ```service httpd restart``` that results in the following entry in ```/var/log/audit/audit.log```

```
type=AVC msg=audit(1563976104.012:4932): avc:  denied  { append } for  pid=4807 comm="httpd" name="info.log" dev="sda1" ino=17772591 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:usr_t:s0 tclass=file permissive=0
```
So......based on your advice I need to set the getenforce policy to be either permissive or disabled. Would you agree? The other question I have is in regards to permissions. I have read a lot of conflicting information with regards to who should own and what the permissions should be for the /opt/graphite directories. By default it is owned by root:root. Can you tell which directories should be owned by apache:apache or some other mixture and what the actual permissions should be set to?

Again THANK YOU for the help!!!!!

**Comment by piotr1212** [comment]
It should be owned by the user you are running apache in. On RHEL/Fedora based systems the default is `apache`.

wrt to selinux it depends on your security policy. If you don't care at all, just disable it. Otherwise set it in permissive so it allows everything but logs violations. 

Or you can run Graphite with selinux enabled, there are some directories for graphite included in the default policy, if you use those as storage locations it will work with selinux enabled:
```
$ sudo semanage fcontext -l | grep graphite
/var/lib/graphite-web(/.*)?                        all files          system_u:object_r:httpd_sys_rw_content_t:s0 
/var/log/graphite-web(/.*)?                        all files          system_u:object_r:httpd_log_t:s0 
```
And you'll have to give apache httpd some extra permissions:
```
  # /sbin/setsebool httpd_can_network_connect on
  # /sbin/setsebool httpd_execmem on
```

**Comment by gregorywolf** [comment]
Hello @piotr1212 Thank you so much for your help!! After disabling SELINUX policy enforcement I was able to bring up graphite web successfully!!!
