### ISSUE TITLE
Curly braces in mertics currently do not show up

### ISSUE THREAD

**Issue by lofidellity** [graphite-project/graphite-web#2473]
https://github.com/graphite-project/graphite-web/blob/0c9e41960b7c9dbf3a4a44aec480ab97b5133914/webapp/graphite/finders/__init__.py#L74

I'll open a PR if wanted with a fix, but since I'm not sure if this is an intentional change or just a bug I figured I'd open an issue.

Right now if a metric contains curly braces graphite is unable to find that metric. Changing the expand_braces function seems to solve it and allow for mistaken curly brace entry as well as intentional curly brace entry by changing the else from 
```
        else:
            res.extend(expand_braces(
                s[:open_brace] + remove_outer_braces(sub) + s[close_brace:]))
```

to 
```
        else:
            res.extend(expand_braces(
                s[:open_brace] + remove_outer_braces(sub) + s[close_brace:]))
            res.append(s)
```

**Comment by DanCech** [comment]
Curly braces are special characters in the query syntax (along with square brackets, asterisk & question mark), so they should not be used in metric names.

**Comment by lofidellity** [comment]
Was it mentioned in any release notes that it should no longer be used, it was previously allowed in 0.9.X (out of curiosity, just want to point the development team that was using that feature at those notes)

**Comment by deniszh** [comment]
Hi @lofidellity,
Unfortunately, curly braces became a special character after introducing tags in 1.1.0. And it was didn't mention in release notes too, sorry for that.
IMO it will be quite hard to implement curly brace support back,  but we would greatly appreciate PR for that. Not sure if we will have enough time to work on that feature.
