### ISSUE TITLE
Accumulating metrics in a series over a given range

### ISSUE THREAD

**Issue by teran-mckinney** [graphite-project/graphite-web#2475]
This is a stupid question, I'm sure it's something basic that I'm missing.

I have a statsd gauge that shows how many cents I was paid in a particular transaction. We can call this metric payment_cents.

In payment cents, the data should look like this: `[50, 100, 25]`, etc.

I'd like to see this accumulated at those points over whatever range I'm working with. So that would turn into. [50, 150, 175]. So depending on my "zoom"/range level, I can see how much I was paid in total that hour, day, month, etc.

I've been playing with sumSeries and other functions. Have had absolutely no luck.

I'm sorry for such a simple question, have been going after this for a while and haven't a clue.

Thank you for your time.

-Teran

**Comment by ploxiln** [comment]
Try the `integral()` function.

**Comment by teran-mckinney** [comment]
Thank you! That does sound like it from the description. However, it seems that integralByInterval() is what I need and may not be in my graphite version. I'll keep looking into this.
