### ISSUE TITLE
offsetting time is causing null data points 

### ISSUE THREAD

**Issue by kbrownebcit** [graphite-project/graphite-web#2476]
Hi there, 

I am currently running into an issue in which I have some dummy data I am sending in for roughly 2 years every hour and I am running into some issues.
for context.
this is my **storage-aggregation.conf** file 
[min]
pattern = \.min$
xFilesFactor = 0.0
aggregationMethod = min

[max]
pattern = \.max$
xFilesFactor = 0.0
aggregationMethod = max

[sum]
pattern = \.count$
xFilesFactor = 0.0
aggregationMethod = sum

[default]
pattern = .*
xFilesFactor = 0.0
aggregationMethod = average

and my **storage-schema.conf**:
[carbon]
pattern = ^carbon\.
retentions = 60:90d

[sitespeed]
pattern = ^sitespeed_io\.
retentions = 10m:60d,30m:90d

[cath_them_all]
pattern = .*
retentions = 1h:7d,2h:30d,4h:60d,8h:120d,16h:240d,32h:480d

I can see the data fine when I query on grafana: eg now-480d
<img width="1278" alt="Screenshot 2019-08-01 09 51 48" src="https://user-images.githubusercontent.com/43010688/62312086-2a2dda00-b442-11e9-83a4-dfbfcddce8b6.png">

but whenever I set custom time stamps I get null data pointt eg 2018-10-01 00:00:00 to 2018-10-31 00:00:00
<img width="1279" alt="Screenshot 2019-08-01 09 55 14" src="https://user-images.githubusercontent.com/43010688/62312245-8abd1700-b442-11e9-9357-ef1439640c67.png">

in the first query, I see data points are there for the month of Otober 2018. In the second query all the data points get converted to null when I set it for that specific interval. I understand that graphite will try to use the best aggregation it can so since its 1 month, it will do 2h:30d, but why is data disappearing?    

Any help would be appreciated!

**Comment by piotr1212** [comment]
> I understand that graphite will try to use the best aggregation it can so since its 1 month, it will do 2h:30d, but why is data disappearing?

That date is more than 240d ago, so it will select the largest archive, 32h:480d.

I have no clue why your data is missing.

Besides that, do you really want so much different retentions in one file? That costs a lot of write performance.

**Comment by kbrownebcit** [comment]
> > I understand that graphite will try to use the best aggregation it can so since its 1 month, it will do 2h:30d, but why is data disappearing?
> 
> That date is more than 240d ago, so it will select the largest archive, 32h:480d.
> 
> I have no clue why your data is missing.
> 
> Besides that, do you really want so much different retentions in one file? That costs a lot of write performance.

for now, yes. But when I look at the data points returned for 2018-10-01 00:00:00 to 2018-10-31 00:00:00: 
<img width="1268" alt="Screenshot 2019-08-01 13 31 58" src="https://user-images.githubusercontent.com/43010688/62325567-c8309d00-b460-11e9-9298-7068176b32fa.png">

0:Array[null,1538380800000]Monday, October 1, 2018 8:00:00 AM
1:Array[null,1538388000000]Monday, October 1, 2018 10:00:00 AM
2:Array[null,1538395200000]Monday, October 1, 2018 12:00:00 PM
are the first 3 data points returned 
these data points are 2 hours apart so it must be falling under 2h:30d archive is it not?

**Comment by kbrownebcit** [comment]
Some more information if it helps: 
this is the output when I run whisper-info.py on the .wsp file:
maxRetention: 41472000
xFilesFactor: 0.0
aggregationMethod: average
fileSize: 23704

Archive 0
retention: 604800
secondsPerPoint: 3600
points: 168
size: 2016
offset: 88

Archive 1
retention: 2592000
secondsPerPoint: 7200
points: 360
size: 4320
offset: 2104

Archive 2
retention: 5184000
secondsPerPoint: 14400
points: 360
size: 4320
offset: 6424

Archive 3
retention: 10368000
secondsPerPoint: 28800
points: 360
size: 4320
offset: 10744

Archive 4
retention: 20736000
secondsPerPoint: 57600
points: 360
size: 4320
offset: 15064

Archive 5
retention: 41472000
secondsPerPoint: 115200
points: 360
size: 4320
offset: 19384
