### ISSUE TITLE
Read time out in graphite-web

### ISSUE THREAD

**Issue by vedaprasad-j** [graphite-project/graphite-web#2477]
I have graphite web in cluster mode. This queries a remote graphite web. i get read time out's very often. 

MaxRetryError: HTTPConnectionPool(host='10.202.43.15', port=80): Max retries exceeded with url: /metrics/find/?local=1&format=pickle&query=prod-sms%2A.statsd.counters.powerpack.GET-powerpack.%2A&from=1565167369&until=1565169289 (Caused by ReadTimeoutError("HTTPConnectionPool(host='10.202.43.15', port=80): Read timed out. (read timeout=3.0)",))

Both the hosts are in the same network, not sure why it would time-out.

Below is relevant graphite-web config.

FETCH_TIMEOUT = 60
MAX_FETCH_RETRIES = 15
CLUSTER_SERVERS = ["10.202.41.26:80","10.202.43.15:80"]

Any fix or recommend setting would be very helpful.

**Comment by deniszh** [comment]
@vedaprasad-j : 
Looks like your graphite-web instance is overloaded. If you running Graphite 1.1 and newer and not using tags you can disable tags (`ENABLE_TAGS = False`) in [carbon.conf](https://github.com/graphite-project/carbon/blob/master/conf/carbon.conf.example#L316), which should remove some load from graphite-web.
Or you need to tune your webserver / WSGI settings, which is quite broad topic, please give more details - what webserver do you use, what's config etc

**Comment by vedaprasad-j** [comment]
@deniszh : i am using Nginx + Gunicorn and please note these are running inside a container. Below are the relevant nginx configs. please let me know if you need any more information.

worker_processes 1;
worker_connections 1024;
sendfile on;
tcp_nopush on;
tcp_nodelay on;
keepalive_timeout 65;
types_hash_max_size 2048;
server_tokens off;
client_header_buffer_size 64k;
large_client_header_buffers 4 64k;
server_names_hash_bucket_size 32;
gzip on;
gzip_disable "msie6";
client_max_body_size       10m;
client_body_buffer_size    128k;
proxy_connect_timeout      90;
proxy_send_timeout         90;
proxy_read_timeout         90;
proxy_buffer_size          4k;
proxy_buffers              4 32k;
proxy_busy_buffers_size    64k;
proxy_temp_file_write_size 64k;

Thanks,
Ved
