### ISSUE TITLE
Question: maxDataPoints in requestContext

### ISSUE THREAD

**Issue by Felixoid** [graphite-project/graphite-web#2478]
Hello. I'm currently on the patching of graphouse finder for graphite and aware if it's usable to pass maxDataPoints from uri arguments into there to fetch not all points and reduce them after, but fetch only the necessary amount of points from clickhouse.

What do you think? I see the patch as trivial and could make a PR, but is it usable?

**Comment by deniszh** [comment]
@Felixoid : well, that probably have sense. But please note, that will probably break `consolidateBy()` support for maxDataPoints - see [docs](https://graphite.readthedocs.io/en/latest/render_api.html?highlight=maxDataPoints#maxdatapoints)
According to the code, `maxDataPoints` doing [runtime consolidation](https://github.com/graphite-project/graphite-web/blob/0c9e41960b7c9dbf3a4a44aec480ab97b5133914/webapp/graphite/render/views.py#L217), and consolidation controlled by [consolidateBy](https://github.com/graphite-project/graphite-web/blob/8dca4f3d28a4b7b9d438e141cdeb3b138586818c/webapp/graphite/render/functions.py#L1996) function, which is not propagated to requestContext IIRC.
But if it have sense for Graphouse - you can try.

**Comment by Felixoid** [comment]
Thank you. I've taken a rough look to the code as well and seen the same. `consolidateBy` won't work with it, but if Finder will support `maxDataPonts`, then it has to take care of the consolidation as well.

I'll make a pool request soon then.
