### ISSUE TITLE
how to fix "ImportError: No module named ..."

### ISSUE THREAD

**Issue by TinajaLabs** [graphite-project/graphite-web#2480]
I've spent too long trying to get graphite installed.  I think it might be something simple like referencing a directory with an environment error.

I've tied this on a raspberry pi and i am able to run an ansible playbook (includes nsg.graphite role) and finish with graphite and grafana running.

The last few days at work I've been trying to install on centos 7.  I have now switched to ubuntu 18.04 because I thought it would work like the debian (raspbian) version that did so well.

It seems no matter what I do, I always get to some variant of the `ImportError: No module named`.

I'm using the default version of python that is already installed:
* Python 2.7.15+ on Ubuntu 18.04
* Python 2.7.5 on Centos 7

Encoded in the ansible role is this list of pip installs:
1.1.3:
    - attrs==17.4.0
    - Automat==0.6.0
    - cachetools==2.0.1
    - cairocffi==0.8.0
    - carbon==1.1.3
    - constantly==15.1.0
    - Django==1.11.17
    - django-tagging==0.4.3
    - graphite-web==1.1.3
    - hyperlink==18.0.0
    - idna==2.6
    - incremental==17.5.0
    - scandir==1.7
    - six==1.11.0
    - urllib3==1.22
    - whisper==1.1.3
    - mod_wsgi==4.6.5

$ echo $PYTHONPATH
/opt/graphite/lib:/opt/graphite/webapp

Currently, on the Ubuntu install It's breaking down on the `django-admin` command.
```
# whereis django-admin
django-admin: /usr/local/bin/django-admin.pyc /usr/local/bin/django-admin /usr/local/bin/django-admin.py
```
Typical error from ansible:
```
    "stderr_lines": [
        "Traceback (most recent call last):",
        "  File \"/usr/local/bin/django-admin.py\", line 5, in <module>",
        "    management.execute_from_command_line()",
        "  File \"/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line",
        "    utility.execute()",
        "  File \"/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py\", line 308, in execute",
        "    settings.INSTALLED_APPS",
        "  File \"/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py\", line 56, in __getattr__",
        "    self._setup(name)",
        "  File \"/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py\", line 41, in _setup",
        "    self._wrapped = Settings(settings_module)",
        "  File \"/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py\", line 110, in __init__",
        "    mod = importlib.import_module(self.SETTINGS_MODULE)",
        "  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module",
        "    __import__(name)",
        "ImportError: No module named graphite.settings"
    ],
```

I have not set up a `virtualenv` because this instance will only be running graphite/grafana.

I've done this also directly, but the results have been the same.  I was hoping to make it repeatable in ansible.

I have the carbon and whisper components running but it requires the web services from graphite to provide the data stream to grafana.  It's killing me that I can't get this installed more easily.  

Any tips and advice would be much appreciated.  

Thanks you,
Chris.

**Comment by TinajaLabs** [comment]
Other import errors received over the last few days.  Some were corrected by installing the appropriate pip modules.  wsgi was particularly onerous.  
```
ImportError: No module named wsgi
ImportError: cannot import name settings
ImportError: cannot import name custom_sql_for_model
ImportError: cannot import name Constraint
ImportError: No module named util
ImportError: No module named six
ImportError: No module named carbon.util 
```
I still don't understand:
```
No module named graphite.settings
```

**Comment by deniszh** [comment]
Hello @TinajaLabs ,

Sorry, I can't say anything about Graphite ansible installation, it's not maintaned by us. Maybe I can help if you point me to its repo or where I can find it.

**Comment by piotr1212** [comment]
> No module named graphite.settings

Your PYTHONPATH is probably incorrect.
