### ISSUE TITLE
Problem returning x axis timeseries data in desired format: javascript timestamp

### ISSUE THREAD

**Issue by NucleaPeon** [graphite-project/graphite-web#2484]
I'm writing a web application that pulls data from graphite and puts it into a d3.js graph.

Javascript as you probably know has a timestamp format with milliseconds, whereas python does not. I'm hoping to have the graphite data return the x axis time series with milliseconds (basically multiplying all x series data points by 1000) using some function or similar parameter. I thought this would be an easy task, but I'm encountering some trouble. I asked a friend who is more familiar with graphite and she did not find an answer for me, so I'm filing this issue for help.

I've looked into `scale()` and `group()` functions, but I don't think they are what I want. 
What confounds me is that in the `render api` portion of the docs mentions different `format` options and the `dygraph` example in particular returns timeseries with the desirable time format, but shows no indication of how to toggle just that. So I think the functionality is there, but am unable to access it. 

The workaround is to manually multiply all x axis values by 1000.

If this is indeed an issue and a solution is proposed or an existing solution is provided, I will gladly contribute documentation. If I am blind and it already exists, I sincerely apologize.

**Comment by cbowman0** [comment]
What format are you requesting the data from Graphite in?

Assuming you are querying Graphite like https://hostname/render/?from=-1hour&until=now&target=my.key, you can also pass the format=dygraph parameter and it'll return in the data in the dygraph format.

**Comment by NucleaPeon** [comment]
I call graphite with `from` -24hour and `until` now. Format is in json, I get back an object/dict with `{series_name: [[y0,x0], [y1, x1], ... [yN,xN]]}` for each series specified (usually 4-8)
I do not want to use `dygraph`'s formatting, but json format is returning timestamps like `1567629300` instead of `1567629300000`

From the render format documentation here: https://graphite.readthedocs.io/en/latest/render_api.html#format

The `json` format example has [y,x] like `[1.0, 1311836008]`
The `dygraph` format example has [x,y] like `[1468791890000, 0.0]`

**Comment by DanCech** [comment]
The simplest solution will likely be to process the data in javascript before you feed it to d3 by multiplying each timestamp by 1000.  The timestamp representation is a function of the output format and the json formatter represents timestamps as "normal" unix epoch timestamps (in seconds).

**Comment by NucleaPeon** [comment]
@DanCech That is our current workaround. Seeing as graphite can return both timestamp formats, I thought that there would be an user accessible option to toggle between the two. Or if there is an internal graphite check, it would be easy to implement a feature/option to manually override it.
