### ISSUE TITLE
Aggregate function behaviour for series with differing start dates

### ISSUE THREAD

**Issue by prsephton** [graphite-project/graphite-web#2485]
Apparently the aggregate function uses izip_longest on the series list to return tuples which it then passes to the individual aggregators, eg. 'diff'.

Consider two series a, b of identical periodicity (step value) where a starts after b.  The first time izip_longest function is called, will simply build a tuple using the first values of a & b, for which the dates may not match at all.  The 'diff' therefore compares values which do not relate to each other in any way.  This is illogical.

The normalize() function might be expected to ensure that, for example, all series start dates are the same, and that the period (or step value) for all series are the same by padding with nulls as appropriate.  It doesn't seem to be doing that, but only returns the minimum start date and maximum end date.

What one might expect is that the difference between series subtracts the subsequent series from the first where the dates match, or if a subsequent series has a null value for a given point, the preceding non-null value is used.  For example, consider:
```
     a[1,2,3,None] - b[1,2,None,4]       with a step value of 60 where a & b start at the same time.
     a - b  might be expected to be 
          a[ 1, 2,     3, None] 
        - b[ 1, 2, None,     4]
      =    [ 0, 0,     1, None]   (1-1, 2-2, 3-2, None-4)
```
Now assume (b) starts a minute after (a);  This effectively shifts (b) by step=60 to the right so we should have:
``` 
    b[None,1,2,None,4]
    a[1,2,3,None] - b[None,1,2,None,4] = 
        a[   1,    2,     3, None,  None] -
 -      b[None,    1,     2, None,     4]
 =       [None,    1,     1, None,  None]
```
Instead of the above, we currently do:  agg_fn(zip(a[1,2,3,None], b[1,2,None,4]))  and don't care when a series starts.  Afterwards we set start to min(start of all series) and end to max(end of all series), but the calculation may be suspect.

**Comment by DanCech** [comment]
Interesting, is there a real-world situation where you are encountering this problem?

**Comment by prsephton** [comment]
aggregate(movingaverage(x,10), x, 'diff')

movingaverage shortens x by 10 points, and if we then subtract x from the moving average,  the subtraction begins at the start of both series (in theory).

Although having said that, graphite may be doing the right thing for some reason or another, and I may be completely wrong about this being an issue.
