### ISSUE TITLE
 No module named 'graphite'

### ISSUE THREAD

**Issue by werowe** [graphite-project/graphite-web#2486]
Would someone look at this error as I have seen it asked twice on StackOverflow with no response.  It's an installation issue:

https://stackoverflow.com/questions/57932901/graphite-django-admin-py-raise-improperlyconfiguredthe-secret-key-setting-must

**Comment by deniszh** [comment]
Hello @werowe,
0.9.10 is *very* old version (May 2012, over 7 years ago) and it's not supporting Python 3.
if you want install it from sources please try latest release (1.1.5) instead.
But you can also install it from packages (although bit older version). We're avoiding specific distros in installation manual, but you can use more specific manual [written by community](https://www.google.com/search?q=graphite-web+ubuntu+16.04). E.g. https://www.scaleway.com/en/docs/install-and-configure-graphite-on-ubuntu/ or https://www.vultr.com/docs/how-to-install-and-configure-graphite-on-ubuntu-16-04
You can also try [Graphite in Docker](https://graphite.readthedocs.io/en/latest/install.html#docker) - it's quick and convenient way of running latest version with minimal hassle.

**Comment by werowe** [comment]
Too complicated.  Will use Docker.  But if I was having to install it
across a cluster or with memcached I probably would have to work my way
through this error.  I got this error on the first try from those
instructions:

Job for carbon-cache.service failed because the control process exited with
error code. See "systemctl status carbon-cache.service" and "journalctl
-xe" for details.

invoke-rc.d: initscript carbon-cache, action "start" failed.

*●* carbon-cache.service - Graphite Carbon Cache

   Loaded: loaded (/lib/systemd/system/carbon-cache.service; enabled;
vendor preset: enabled)

   Active: *failed* (Result: exit-code) since Wed 2019-09-18 11:30:02 UTC;
5ms ago

  Process: 9228 ExecStart=/usr/bin/carbon-cache
--config=/etc/carbon/carbon.conf --pidfile=/var/run/carbon-cache.pid
--logdir=/var/log/carbon/ start *(code=exited, status=1/FAILURE)*


Sep 18 11:30:02 paris2 carbon-cache[9228]:
self.subOptions.parseOptions(rest)

Sep 18 11:30:02 paris2 carbon-cache[9228]:   File
"/usr/lib/python2.7/dist-packages/twisted/python/usage.p...ions

Sep 18 11:30:02 paris2 carbon-cache[9228]:     self.postOptions()

Sep 18 11:30:02 paris2 carbon-cache[9228]:   File
"/usr/lib/python2.7/dist-packages/carbon/conf.py", line ...ions

Sep 18 11:30:02 paris2 carbon-cache[9228]:     if whisper.CAN_FALLOCATE:

Sep 18 11:30:02 paris2 carbon-cache[9228]: AttributeError: 'module' object
has no attribute 'CAN_FALLOCATE'

Sep 18 11:30:02 paris2 systemd[1]: *carbon-cache.service: Control process
exited, code=exited status=1*

Sep 18 11:30:02 paris2 systemd[1]: *Failed to start Graphite Carbon Cache.*

Sep 18 11:30:02 paris2 systemd[1]: *carbon-cache.service: Unit entered
failed state.*

Sep 18 11:30:02 paris2 systemd[1]: *carbon-cache.service: Failed with
result 'exit-cod*

**Comment by deniszh** [comment]
Strange. CAN_FALLOCATE should be initialized that way or another. 
Try to disable it using `WHISPER_FALLOCATE_CREATE = False` in carbon.conf
