### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [graphite-project/graphite-web#2491]
https://github.com/graphite-project/graphite-web/security/advisories

**Comment by deniszh** [comment]
Hello Jonathan,
Could you please elaborate please?

**Comment by JLLeitschuh** [comment]
I'd like to report a security vulnerability, (that is technically already public) but I'd like to have a private conversation with the devs about it so you can get a CVE issued for this vulnerability.

**Comment by JLLeitschuh** [comment]
Never mind, no need. This is actually publicly disclosed here:

https://github.com/graphite-project/graphite-web/issues/2008

I'll move the discussion there.
