### ISSUE TITLE
groupByNodes support "avg" as alias for "average"?

### ISSUE THREAD

**Issue by Dieterbe** [graphite-project/graphite-web#2494]
today i enabled GRAPHITE_ENFORCE_INPUT_VALIDATION and found out that queries like `groupByNode(..., 6, 'avg')` lead to:

```
HTTP 400
Bad Request: Invalid option specified for function "groupByNodes" parameter "callback"
```
note that this used to work fine before. can we add "avg" as a supported alias?

**Comment by DanCech** [comment]
This is definitely an overreach of the validation code, the aliases in `aggFuncAliases` should all be supported.

**Comment by Dieterbe** [comment]
ok. i'll see tomorrow if i can supply a patch.
