### ISSUE TITLE
Image rendering leaves a lot of empty space under long legend

### ISSUE THREAD

**Issue by skaurus** [graphite-project/graphite-web#2498]
**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

Wnen using Graphite render to image api, Graphite leaves empty space below legend - the longer legend is, the bigger empty space. When there is just one metric, the distance between legend and lower border of the image is about 5px. When there is five metrics, it is about 13px. And for twenty three, about 108px. At this point this empty space takes more height than the graph itself in my scenario.
Images: https://i.imgur.com/qcGX338.png https://i.imgur.com/OC8nLxg.png https://i.imgur.com/E8kcExx.png

**Expected behavior:**

I would expect that empty space will not grow with metrics count.

**Steps to reproduce:**

I believe there are no some special steps. Just `/render?width=460&from=-60minutes&until=-&height=500&hideLegend=false&target=some.avg.metric.*`

**Comment by deniszh** [comment]
Sorry, @skaurus , can't reproduce on latest release (1.1.5), also in 1.1.6. I see no difference on distance between text and image edge for 4 or 10 metrics:
<img width="590" alt="Screenshot 2019-10-11 at 17 38 55" src="https://user-images.githubusercontent.com/1227222/66665113-27bfdb80-ec4e-11e9-8947-ef87be785616.png">
<img width="588" alt="Screenshot 2019-10-11 at 17 38 43" src="https://user-images.githubusercontent.com/1227222/66665127-2db5bc80-ec4e-11e9-87fb-1517ce757965.png">


Which graphite version do you use?

**Comment by deniszh** [comment]
Issue similar to https://github.com/graphite-project/graphite-web/issues/253, which was fixed in 2013.

**Comment by deniszh** [comment]
Probably in 0.9.12 and newer releases.

**Comment by skaurus** [comment]
I tried to find the version, but couldn't. Where do I look?

#253 looking promising indeed... Did we really not updated for so long...

**Comment by skaurus** [comment]
Lol. /version/ says that we use 0.10.0-alpha 🤦‍♂
Usually we keep our soft updated, obviously, with Graphite this is not the case.

Thanks!

**Comment by deniszh** [comment]
`0.10.0-alpha` means old `master`, before 1.0 release. Can be really old. You can apply only patch above if full upgrade is not desireable.
