### ISSUE TITLE
sending different values with same timestamp

### ISSUE THREAD

**Issue by mashal1996** [graphite-project/graphite-web#2509]
Hi 
I am trying to send different values with same timestamp:
for example,
my.useful.metric 322   1414516234 
my.useful.metric 522   1414516234
my.useful.metric 26     1414516234
my.useful.metric 222   1414516234
my.useful.metric 3256 1414516234

the problem, graphite will display the last value 3256, but I want to aggregate all of them to get 4348

Regards

**Comment by ploxiln** [comment]
Metrics you send are received by [carbon-cache](https://github.com/graphite-project/carbon), not graphite-web.

This is not an available feature of carbon-cache. "statsd" (there are a few similar implementations out there) can add these (as a counter) or calculate mean/median/99th-percentile (as a timer), before sending on to carbon-cache, but only for the current time period.
