### ISSUE TITLE
Non-integer thresholds for functions like maximumAbove etc.

### ISSUE THREAD

**Issue by PhilippWendler** [graphite-project/graphite-web#2511]
**I'm submitting a ...** 
- [x] bug report
- [ ] feature request

**Current behavior:**

Since Graphite 1.1.6 we get a lot of warnings in our Graphite log of the following form:
```
Received invalid parameters (Invalid integer value specified for function "maximumAbove" parameter "n"): maximumAbove ([TimeSeries...], 0.1)
```
This also occurs with `removeBelowValue` and probably all the other functions that take a threshold.

The query **still works** and has the expected behavior.

The reason for this seems to be that the parameter-validation logic checks for an integer, although these functions actually support a float as well. Note that in many cases a non-integer threshold is quite useful.

**Expected behavior:**
No warning should be logged for non-integer thresholds and the function should continue to work as it currently does. Probably the documentation should also be clarified and state that non-integer thresholds are supported (currently it does not say anything explicitly, but the [wording](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.maximumAbove) `constant n` might hint at integer-only thresholds).

**Steps to reproduce:**
Just call the `maximumAbove` function with a non-integer threshold.

**Related code:**
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L2930
(and similar for the other functions)

For completeness, we are accessing Graphite through Grafana. A full query looks like this for example: `maximumAbove(perSecond(collectd.$hostname.cgroup.*.counter.blkio_throttle_io_serviced_*), 0.1)`.

**Comment by deniszh** [comment]
IMO it should be `constant`, i.e. not a seriesList, and definitely float should be allowed.

**Comment by PhilippWendler** [comment]
Thanks for responding!

I am confused about your mention of `seriesList`, though. Are you mixing up the two parameters?

**Comment by deniszh** [comment]
No, I'm not. My point is `constant n` mean _number_, not _serieslist_ - not exclusively integer, floats also should be there.
