### ISSUE TITLE
[BUG] SVG rendering returns bytes object, leading to XML Parsing Error

### ISSUE THREAD

**Issue by dueringa** [graphite-project/graphite-web#2518]
**Describe the bug**
When attempting to render an SVG file, I get an "XML Parsing Error: not well-formed [...] Line Number 1, Column 2:" in Firefox.

```
b'<?xml version="1.0" encoding="UTF-8"?>\n ...
```
Note the b' in the beginning, it looks like a string representation of a bytes object is returned

**To Reproduce**
Enter the rendering URL https://example.com/render?&target=test.count&format=svg

**Expected behavior**
The requests succeeds with a valid SVG file.

**Screenshots**

**Environment (please complete the following information):**
 - Debian Buster
 - Graphite-web version 1.1.6
 - Python 3.7.3
 - Django version 2.2.7
 - graphite-web and Django installed via pip from pypi (pip install graphite-web) in a venv
 - run/started via uwsgi (also installed in venv), served by nginx

**Additional context**

uwsgi ini file:
```
[uwsgi]
processes = 1
socket = localhost:12222
virtualenv = /opt/graphite
chdir = /opt/graphite/conf
module = wsgi:application
```

```
# conf/wsgi.py 
import sys
import os

sys.path.append('/opt/graphite/webapp')

from graphite.wsgi import application
```

**Comment by earthgecko** [comment]
Experiencing the same thing.

**Comment by deniszh** [comment]
Yes, I reproduced it on latest release in docker. Not sure how to fix it though, looks like it's somewhere in Django. Maybe @piotr1212 knows?

**Comment by piotr1212** [comment]
Yep, already found the issue. Just figuring out what the best way is to fix this.

**Comment by earthgecko** [comment]
@piotr1212 thanks very much, that fix works :+1:
