### ISSUE TITLE
[Q] Undocumented use of Graphite POST Requests

### ISSUE THREAD

**Issue by SUL-sj** [graphite-project/graphite-web#2519]
I have a question regarding your use of the Graphite HTTP API with _POST_ as seen [here](https://github.com/graphite-project/graphite-web/blob/537b184a49ec94f5a0161738fa4898492e96c5cd/webapp/graphite/metrics/views.py#L56). The [Graphite HTTP API Documentation](https://graphite-api.readthedocs.io/en/latest/api.html) doesn't mention any use of _POST_ Requests - only _GET_. Is there a reference for this implementation?

**Comment by deniszh** [comment]
Hi @SUL-sj ,
I'm not sure if that line is enough for proper POST support for whole API. It's happened during migration from `request.REEQUEST` happened in https://github.com/graphite-project/graphite-web/commit/872de20cc99e427b6649de0be78d5906a2bfbe88.

**Comment by SUL-sj** [comment]
So if someone would implement an Graphite HTTP API in a software, _GET_ Requests would be the accurate way to be compliant? (meaning: the documentation is still up to date?)

**Comment by deniszh** [comment]
Yes, it is. All alternative Graphite API implementations use GET IIRC.

**Comment by SUL-sj** [comment]
Thank you for the fast responses - this answered my question!

**Comment by DanCech** [comment]
Actually that commit didn't change the behavior, it just replaced the old django `request.REQUEST` syntax (which is no longer supported) with an explicit merge of GET and POST parameters.  graphite-web has supported both GET and POST requests for many years, and the documentation should be updated if that isn't clear.
