### ISSUE TITLE
we need a "safe" divideSeriesLists that divides by name

### ISSUE THREAD

**Issue by Dieterbe** [graphite-project/graphite-web#2522]
related: #2429 

the problem with divideSeriesLists is that it divides list1[0] by list2[0], list1[1] by list2[1] and so on.

very commonly, the dividendlist and divisorlist have a specific name and should be matched up by name and divided by one another. This is problematic to do with divideSeriesLists because it is not aware of names. even if both lists are sorted, it's possible for example, for each one to miss one, in a different position, which results in dividing wrong pairs.

Similarly, when one misses a serie but the other doesn't the entire request fails.
it would be better to divide all the ones we can and report the other ones as MISSING with None values, similar to asPercent()

**Comment by DanCech** [comment]
Yes, it would make sense for `divideSeriesLists` to work roughly the same way as `asPercent` does, it's already more or less equivalent to `asPercent(list1, list2) | scale(0.01)` anyway.
