### ISSUE TITLE
whisper-resize.py files is missing in graphite 1.1.2 

### ISSUE THREAD

**Issue by panditb** [graphite-project/graphite-web#2524]
As per the documentation changing the rententions pattern in storage-schemas.conf will not affect for existing .wsp file ie mean existing metrics key ,
Changing this file will not affect already-created .wsp files. Use **whisper-resize.py** to change those.

But in this version i am not able to find the "whisper-resize.py" file, can you check on this

**Comment by deniszh** [comment]
Hi @panditb ,
It depends how your OS distribute packages. Try to find `whisper-resize` instead.

**Comment by panditb** [comment]
My linux version this 
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
```
I can see only these  files
```
# find . -name whispe*
./pip/repository/whisper-1.1.2.tar.gz
./graphite/webapp/graphite/readers/whisper.py
./graphite/webapp/graphite/readers/whisper.pyc
./graphite/storage/whisper
```

**Comment by deniszh** [comment]
That's strange. Maybe it was not included in 1.1.2 package? 
You can download it from https://github.com/graphite-project/whisper/tree/1.1.2/bin

**Comment by panditb** [comment]
Thanks !! is it good idea to copy this file and put in existing working graphite instance , is this file will not affect the existing metrics key retentions policy mentioned in storage-schemas.conf file

**Comment by deniszh** [comment]
If you copy only `whisper-resize.py` it should not affect anything.

**Comment by panditb** [comment]
Okay can i put this in the folder /opt/graphite/bin , i cant see folder /opt/graphite/whisper

**Comment by deniszh** [comment]
You can put in whatever directory which are in your PATH variable.
