### ISSUE TITLE
can not load images[BUG]

### ISSUE THREAD

**Issue by yananchen1989** [graphite-project/graphite-web#2527]
Hi, 

here is the version: graphite-web (0.9.12)  

After a while, grafana cannot display images based on data from graphite.

here is the error message:
any hints ? 

`&#10;<center>&#10;<h2>&#10;<p>Graphite encountered an unexpected error while handling your request.</p>&#10;<p>Please contact your site administrator if the problem persists.</p>&#10;</h2>&#10;<br>&#10;<div>&#10;&#10;</div>&#10;&#10;<div>&#10;<pre>Traceback (most recent call last):&#10;  File &#34;/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py&#34;, line 41, in inner&#10;    response = get_response(request)&#10;  File &#34;/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py&#34;, line 187, in _get_response&#10;    response = self.process_exception_by_middleware(e, request)&#10;  File &#34;/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py&#34;, line 185, in _get_response&#10;    response = wrapped_callback(request, *callback_args, **callback_kwargs)&#10;  File &#34;/opt/graphite/webapp/graphite/render/views.py&#34;, line 117, in renderView&#10;    data.extend(evaluateTarget(requestContext, targets))&#10;  File &#34;/opt/graphite/webapp/graphite/render/evaluator.py&#34;, line 15, in evaluateTarget&#10;    prefetchData(requestContext, pathExpressions)&#10;  File &#34;/opt/graphite/webapp/graphite/render/datalib.py&#34;, line 257, in prefetchData&#10;    for result in STORE.fetch(pathExpressions, startTime, endTime, now, requestContext):&#10;  File &#34;/opt/graphite/webapp/graphite/storage.py&#34;, line 179, in fetch&#10;    **'fetch for %s' % str(patterns))&#10;  File &#34;/opt/graphite/webapp/graphite/storage.py&#34;, line 121, in wait_jobs&#10;    raise Exception(message)&#10;Exception: Timed out after 30.000137s for fetch for [u'aliasByNode']&#10;&#10;</pre>&#10;</div>&#10;&#10;</center>&#10;**`

thanks a lot.

**Comment by deniszh** [comment]
Hi @yananchen1989 ,

Please publish your config (`webapp/graphite/local_settings.py`) somewhere.
