### ISSUE TITLE
[Q] Graphite events broken in Django 3 because of tagging which is eol

### ISSUE THREAD

**Issue by piotr1212** [graphite-project/graphite-web#2533]
Tests fail on Django3 for the Graphite-events component:

```
  File "/home/piotr/git/graphite-web/webapp/graphite/events/models.py", line 4, in <module>
    from tagging.models import Tag
  File "/home/piotr/git/graphite-web/.tox/py36-django30-pyparsing2/lib/python3.6/site-packages/tagging/models.py", line 7, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible
```

`python_2_unicode_compatible` is now only available through six. Problem here is that we do not import that method directly but through `django-tagging`. `django-tagging` is quite dead, the replacement seems to be `django-taggit`. Taggit uses different schemas which makes migrating for users a bit of a mess, see https://blog.birdhouse.org/2011/04/17/migrate-django-tagging-taggit/

I think there are several options to go from here:

1. Bundle `django-tagging` and patch it.
2. Migrate to `django-taggit`, write migration instructions.
3. Drop graphite-events, Grafana now has a built in annotations store.

I don't plan on implementing 2. What do you think?

**Comment by deniszh** [comment]
If it's only for events, I would say 3.

**Comment by piotr1212** [comment]
Yes, it is just for events. I have no clue how many people are actually using it.

Grafana does support the [Graphite events format](https://grafana.com/docs/grafana/latest/http_api/annotations/#create-annotation-in-graphite-format) so if I understand this correctly users will just have to change the endpoint.

**Comment by deniszh** [comment]
Well, data migration is also needed. Maybe we can fix it differently then...

**Comment by deniszh** [comment]
But we need to got to Django 3 anyway, so, in worst case I would say kill events.

**Comment by piotr1212** [comment]
I managed to monkeypatch the imports. We can use this for now and announce that events will be deprecated in the next release, we'll see how much backlash we get and we can eventually create a data migration script.
