### ISSUE TITLE
[Q] Search always returns "Nothing matched your query"

### ISSUE THREAD

**Issue by gerases** [graphite-project/graphite-web#2540]
Hi,

My new graphite setup is working quite well EXCEPT the search button. Whatever I enter, I get "Nothing matched your query". No errors in apache or wsgi logs.

Any ideas?

Thanks!!

**Comment by deniszh** [comment]
Sorry, search functionality is broken long time ago. Usually, people just
browsing metric tree.

**Comment by gerases** [comment]
Hi Denis,

In which version did it stop working?

We're using graphite-web-0.9.16 everywhere and the search is working everywhere except on the new cluster I set up. Can I increase logging level somewhere to see where it's failing?

Thanks!

**Comment by deniszh** [comment]
Ah, maybe I wrong. Never used that before. Please note that `/opt/graphite/bin/build-index.sh` exists and running periodically. This should update metric index (located somewhere in `/tmp/graphite-test-xxxx/index`)

**Comment by gerases** [comment]
Yep, found that by looking at `metrics/search.py`. It turns out that the index builder hard codes the whisper directory to `/var/lib/carbon/whisper`

```
...
WHISPER_DIR="/var/lib/carbon/whisper"
...
```

 In my case it's in a completely different location. I created a symlink from `/var/lib/carbon/whisper` to `ACTUAL_PATH` and it did the trick :)

I'm not sure if the newer version of that script is smarter and actually relates the directory to `local_settings.py` somehow.

Anyway, I'm glad I see why it was not working. On my other systems the default locations are used for whisper data and so the index is correctly built.
