### ISSUE TITLE
[Q] Install Graphite on Debian 10 on VMWare

### ISSUE THREAD

**Issue by KodaCHC** [graphite-project/graphite-web#2550]
Hi

I have set up a icinga2 installation on a debian Machine. Now for graphs I will use graphite.

So I have install all components from git, and resolved all dependencies from command
`python check-dependencies.py`

After I have resolved this, and I run again the command
`python check-dependencies.py`
I get the error 
Illegal instruction

I have try apt-get install.. before, but my graphite/graphite-web don't work

My way:
`apt-get update && apt-get dist-upgrade && apt-get autoremove
apt-get install libapache2-mod-wsgi python-pip python3-pip librrd-dev python-ldap python3-ldap python-cairo python3-cairo
update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
update-alternatives --install /usr/bin/python python /usr/bin/python3.7 2
python --version
pip install "django==2.2.10"
cd /opt/
git clone https://github.com/graphite-project/whisper.git
pushd whisper
python setup.py install
popd
git clone https://github.com/graphite-project/carbon.git
pushd carbon
python setup.py install 
popd
git clone https://github.com/graphite-project/ceres.git
pushd ceres
python setup.py install 
popd
git clone https://github.com/graphite-project/graphite-web.git
pushd /opt/graphite/conf
cp carbon.conf.example carbon.conf
cp storage-schemas.conf.example storage-schemas.conf
pip install pyhash python-memcached django-tagging
pip install txamqp rrdtool whitenoise cairocffi
pip install pyparsing  
python check-dependencies.py`

**Comment by deniszh** [comment]
Hi @KodaCHC ,

Could you please expand what "graphite/graphite-web don't work" mean?

**Comment by KodaCHC** [comment]
@deniszh: With the git installation, I get allways "illegal instructions" So I can't finish the installation
With apt-get (like https://www.christian-klemm.de/icingaweb2-graphite-modul/) with newes django I get apache error 500

**Comment by deniszh** [comment]
Unfortunately, I can't help with "illegal instructions" - probably something is wrong with your VM. At least, it's not related to Graphite itself.
Apt installation should be fine, probably no need to install django separately, 1.11 from python3-django should be sufficient. 
Also please note that you will need Apache module for Python 3 instead.
Maybe it's better to point you in my PR for Ubuntu 18.04 / python 3 support for Synthesize - https://github.com/obfuscurity/synthesize/pull/79, you can peek Apache config there.

**Comment by deniszh** [comment]
I.e. just try to `apt-get install graphite-web graphite-carbon libapache2-mod-wsgi-py3 python3-pip` continue with manual, skipping Django installation.

**Comment by KodaCHC** [comment]
I use Debian 10 on a normal VM (i have try 3 installation). I don't know if the virtualisation is the problem.

`apt-get install graphite-web graphite-carbon libapache2-mod-wsgi-py3 python3-pip`
I have try.  But I can't chose manual. He asked me for delete db if I remove and after this the installation is running.
After this, I change the SECRET_KEY, run `graphite-manage migrate `
After this I prepare apache2
`echo Listen 8000 >> /etc/apache2/ports.conf
cp /usr/share/graphite-web/apache2-graphite.conf /etc/apache2/sites-available/graphite.conf
sed -i.org -e "/VirtualHost/s/:80/:8000/" /etc/apache2/sites-available/graphite.conf
a2ensite graphite
service apache2 restart`

The result is a `Internal Server Error`
[Mon Feb 24 13:02:12.511082 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103] mod_wsgi (pid=7872): Failed to exec Python script file '/usr/share/graphite-web/graphite.wsgi'.
[Mon Feb 24 13:02:12.511173 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103] mod_wsgi (pid=7872): Exception occurred processing WSGI script '/usr/share/graphite-web/graphite.wsgi'.
[Mon Feb 24 13:02:12.513003 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103] Traceback (most recent call last):
[Mon Feb 24 13:02:12.513078 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/share/graphite-web/graphite.wsgi", line 14, in <module>
[Mon Feb 24 13:02:12.513087 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     application = get_wsgi_application()
[Mon Feb 24 13:02:12.513097 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Mon Feb 24 13:02:12.513103 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     django.setup(set_prefix=False)
[Mon Feb 24 13:02:12.513115 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3/dist-packages/django/__init__.py", line 27, in setup
[Mon Feb 24 13:02:12.513121 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     apps.populate(settings.INSTALLED_APPS)
[Mon Feb 24 13:02:12.513130 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 85, in populate
[Mon Feb 24 13:02:12.513136 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     app_config = AppConfig.create(entry)
[Mon Feb 24 13:02:12.513145 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3/dist-packages/django/apps/config.py", line 94, in create
[Mon Feb 24 13:02:12.513151 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     module = import_module(entry)
[Mon Feb 24 13:02:12.513164 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Mon Feb 24 13:02:12.513171 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     return _bootstrap._gcd_import(name[level:], package, level)
[Mon Feb 24 13:02:12.513180 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Mon Feb 24 13:02:12.513199 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Mon Feb 24 13:02:12.513208 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[Mon Feb 24 13:02:12.513218 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[Mon Feb 24 13:02:12.513227 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[Mon Feb 24 13:02:12.513236 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Mon Feb 24 13:02:12.513246 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3/dist-packages/graphite/functions/__init__.py", line 10, in <module>
[Mon Feb 24 13:02:12.513252 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     from graphite.logger import log
[Mon Feb 24 13:02:12.513261 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3/dist-packages/graphite/logger.py", line 106, in <module>
[Mon Feb 24 13:02:12.513268 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     log = GraphiteLogger() # import-shared logger instance
[Mon Feb 24 13:02:12.513277 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3/dist-packages/graphite/logger.py", line 39, in __init__
[Mon Feb 24 13:02:12.513283 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     level = logging.DEBUG if settings.DEBUG else logging.INFO,
[Mon Feb 24 13:02:12.513292 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3/dist-packages/graphite/logger.py", line 80, in _config_logger
[Mon Feb 24 13:02:12.513298 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     handler = FileHandler(log_file)
[Mon Feb 24 13:02:12.513307 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
[Mon Feb 24 13:02:12.513313 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     StreamHandler.__init__(self, self._open())
[Mon Feb 24 13:02:12.513322 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]   File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
[Mon Feb 24 13:02:12.513328 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103]     return open(self.baseFilename, self.mode, encoding=self.encoding)
[Mon Feb 24 13:02:12.513347 2020] [wsgi:error] [pid 7872] [remote 10.52.0.8:60103] PermissionError: [Errno 13] Permission denied: '/var/log/graphite/info.log'

**Comment by deniszh** [comment]
@KodaCHC : 
Well, at least this error is obvious: 
`PermissionError: [Errno 13] Permission denied: '/var/log/graphite/info.log'`
`/var/log/graphite/` directory should be writable by Apache user. Not sure which one on Debian now, maybe `www-data`

**Comment by KodaCHC** [comment]
Thank you. I don't have see this. I have solved it. But now i get an error in Browser

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/graphite/composer/views.py", line 27, in composer
    profile = getProfile(request)
  File "/usr/lib/python3/dist-packages/graphite/user_util.py", line 35, in getProfile
    return default_profile()
  File "/usr/lib/python3/dist-packages/graphite/user_util.py", line 51, in default_profile
    'password': '!'})
  File "/usr/lib/python3/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 500, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python3/dist-packages/django/contrib/auth/base_user.py", line 80, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python3/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python3/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: attempt to write a readonly database
```

**Comment by deniszh** [comment]
Similar issue - database by default is SQLite, so `graphite.db` should be writable by apache user.

**Comment by KodaCHC** [comment]
```
chown _graphite:_graphite /var/log/graphite/*
chown _graphite:_graphite /var/lib/graphite/graphite.db
```

Thats work. Thank you
