### ISSUE TITLE
Tame DeepSource check

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#2551]
Maybe it's better to switch it into permissive mode, or at least remove obvious / not used alerts. 
See https://deepsource.io/gh/graphite-project/graphite-web/settings/general

**Comment by piotr1212** [comment]
It claims that new issues are introduced in code which has not changed at all. I don't know whether this is some bug in deepsource or misconfiguration.

**Comment by deniszh** [comment]
Looks like a bug, but I'll check

<img width="635" alt="Screenshot 2020-02-25 at 20 54 38" src="https://user-images.githubusercontent.com/1227222/75282281-16e4c080-5811-11ea-831a-da8d892e2f86.png">

**Comment by piotr1212** [comment]
Strange, they don't seem to have a public bugracker. I've sent a mail to their support.

**Comment by piotr1212** [comment]
> Hi Piotr,
>
> Sorry that took a while. Thanks for reporting it. It was a bug from our end. We've fixed it and rolled it out to production - https://deepsource.io/gh/graphite-project/carbon/run/6b08a4d0-a281-4919-9fed-d01f45db6c57/python/
>
>We discovered one more edge case which we'll work on in a couple of days.
>
>
>Best,
>Jai

@deniszh You could try to turn it on again.

**Comment by deniszh** [comment]
Ok, thanks, @piotr1212, just did.
I'll try to review rules later.

**Comment by ploxiln** [comment]
I noticed that some of the stuff DeepSource finds is stuff the flake8 would find, if it wasn't disabled. One example is the 4-space indent checks - all disabled for flake8. Maybe that's not a great example, because there are thousands of lines with 2-space indent, so it is probably not worth re-enabling that one. But I've started some work on trying to find which flake8 checks could be more easily re-enabled in #2552

**Comment by deniszh** [comment]
I think main concern about DeepSource was related to bug mentioned above. But 'm alway preferring clean code to non-clean, so, much appreciated for your efforts, @ploxiln !

**Comment by piotr1212** [comment]
The Graphite codebase pre-dates flake8. There have been some attempts to get it flake8 compliant with use of autopep, but I guess no one ever had time to review 9000 line changes. see https://github.com/graphite-project/graphite-web/pull/1950 . You don't want to introduce some bugs. Changing all those lines also makes it harder to read git log history. 

Besides the downsides I would really like to see Graphite pep8 compliant. I think not being compliant can scare off potential contributors. If you could create smaller PR's with one issue at at time I will review it.
