### ISSUE TITLE
[BUG] Documentation indicates wrong function name `roundFunction()`

### ISSUE THREAD

**Issue by replay** [graphite-project/graphite-web#2573]
**Describe the bug**
The documentation lists a function called `roundFunction()`:
https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.roundFunction

**Expected behavior**

It should be `round()` instead of `roundFunction()`

**Screenshots**
![image](https://user-images.githubusercontent.com/195371/77111739-9af02980-6a06-11ea-85a9-f896df60b3b4.png)

**Additional context**
This happens because we use `sphinx` to auto-generate the documentation and the implemented function is named `roundFunction()` [here](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L1674).

Unfortunately we can't simply rename that function to `round`, because that's an existing function in Python. It might be possible to fix this with some sphinx-overrides, but I couldn't figure out how to make it work.

**Comment by DanCech** [comment]
There are a few other examples of this, in those cases we list the "short version" as an alias.

**Comment by replay** [comment]
Are you familiar with `sphinx`? I was trying to fix it by adding something like `.. autofunction:: round(seriesList, precision=None)` to the function docstring, but that doesn't seem to work. then i didn't want to spend more time on it

**Comment by replay** [comment]
If those sphinx overrides don't work I'm afraid we'll have to somehow do it by adding overrides in https://github.com/graphite-project/graphite-web/blob/master/docs/conf.py#L45 but that seems a bit ugly

**Comment by DanCech** [comment]
Or we just add roundFunction to the list of supported functions and note in the docs that `round()` is a valid alias for it, just like timeFunction and time

**Comment by replay** [comment]
Yeah, that would work. It just feels bad to let the inability to tell sphinx what we want to do dictate the behavior of the API.
