### ISSUE TITLE
Implement stale bot for closing old PRs and issues

### ISSUE THREAD

**Issue by deniszh** [graphite-project/graphite-web#2583]
There's so many old PRs and issues, which are mostly hanging there and that's it.
What team think about implenenting bot to closing it down?
Github provides such bot now, named "stale" - https://github.com/apps/stale
if it's a good idea, what should be defaults?
Sames as Github defaults - 60 days before warning and then waiting 7 more days before closing?

**Comment by DanCech** [comment]
Yeah, it would clear out all the ancient stuff. 👍

**Comment by cbowman0** [comment]
I'm ok with this.  We aren't clearing the giant old list, so something needs to be done.

**Comment by deniszh** [comment]
Just enabled bot, let's check will it pick old issues too.

**Comment by deniszh** [comment]
ooh, notification storm is coming, I would recommend to disable notifications

**Comment by deniszh** [comment]
Well, please note that even with disabling notifs you'll still get ones for own/commented issues/PRs...

**Comment by deniszh** [comment]
OK, bot had massive success, I would say. Btw, if you want to make bot not touch particular issue/PR - put 'pinned' label to it.
