### ISSUE TITLE
SmartSummarize alignTo parameter unclear

### ISSUE THREAD

**Issue by dancingmad** [graphite-project/graphite-web#2585]
"The alignToFrom boolean parameter has been replaced by alignTo and no longer has any effect. Alignment can be to years, months, weeks, days, hours, and minutes."

I have idea what the format for the alignTo is supposed to be, the only parameter I got to work was alignTo=None as in the example stated. A search on the web could not get me any results. Can anyone tell how to align to years, months, weeks, days, hours and minutes? (eg. alignTo=days, alignTo=1d, alignTo=1day,...)

**Comment by deniszh** [comment]
According to [code](https://github.com/graphite-project/graphite-web/blob/e6f216a074382ba427f613ba8b6013c6760716df/webapp/graphite/render/functions.py#L4974-L4995) if `alignTo` is not None first it calculates in which units it is (calling [getUnitString](https://github.com/graphite-project/graphite-web/blob/3ad279df5cb90b211953e39161df416e54a84948/webapp/graphite/render/attime.py#L192-L200)) - is it year, month, week, day, hout, minute or second.  Then function alignes startTime to corresponding unit.
And  [getUnitString](https://github.com/graphite-project/graphite-web/blob/3ad279df5cb90b211953e39161df416e54a84948/webapp/graphite/render/attime.py#L192-L200)  has quite simple logic - if string start with 's' then it's seconds, 'min' - minutes, 'h' - hours, etc - that's a same format as other time in Graphite.
So, `alignTo` accepts `None`, or Graphite time unit in string form - 's', 'min', 'h', 'd', 'w', 'mon', 'y'.
