### ISSUE TITLE
[Q] Unable to display graph data.

### ISSUE THREAD

**Issue by hugosxm** [graphite-project/graphite-web#2588]
Hi, sorry if posting this on the wrong place... But I'm pulling my hair on something. 

Long story short. I have a Shinken monitoring system sending metrics to a graphite docker image, the latest stable. I pulled graphiteapp/graphite-statsd five minutes ago, but i have this problem since maybe 1 month. After an update of the docker image. 

The problem is that graphite displays nothing if i try a simple graph on the graphite-webapp. It does not say "no data", but it show an empty graph. What is very strange : if i try to use grafana, grafana will display the dot of the timeseries wihout being able to connect each dot ?! 

I tried different image, i tried to send data manually to the graphite instance with a netcat... Always same problem... I even tried to install icinga2 because i'm planning to change our supervision system... Did the same thing... I'm lost here so i'm asking for help. 

Thanks by advance

**Comment by deniszh** [comment]
Sorry, @hugosxm, but it's not entirely clear what problem are you trying to solve. Maybe you can make couple of screenshots to explain what "if i try to use grafana, grafana will display the dot of the timeseries wihout being able to connect each dot ?" means?

**Comment by hugosxm** [comment]
@deniszh thanks for reading me, sorry it is a bit tricky to explain, i did some screenshots, english is not my first language btw ^^. I'll try to be more "verbose"

So i have my icinga2 and my shinken running and sending perfdata to graphite, same problem with BOTH supervision systems.
My graphite instance is a docker container, I pulled the latest stable image, "graphiteapp/graphite-statsd:latest", i hope this is the correct way to run graphite. 

My container logs seems correct, we can see metrics going in with no errors : 

`
24/04/2020 10:50:34 :: [tagdb] Tagging icinga2.docker-worker2_lan_971lafamille_com.services.geco_swap.geco_check_ncpa_swap.perfdata.used.value
24/04/2020 10:50:34 :: [tagdb] Tagged icinga2.docker-worker2_lan_971lafamille_com.services.geco_swap.geco_check_ncpa_swap.perfdata.used.value in 0.0176694393157959
24/04/2020 10:50:35 :: [tagdb] Tagging icinga2.icinga_lan_971lafamille_com.services.icinga.icinga.perfdata.graphitewriter_graphite_work_queue_items.value
24/04/2020 10:50:39 :: [listener] MetricLineReceiver connection with 127.0.0.1:43328 established
24/04/2020 10:50:39 :: [listener] MetricLineReceiver connection with 127.0.0.1:43328 closed cleanly
24/04/2020 10:50:39 :: [tagdb] Tagging stats.timers.view.graphite.tags.views.tagMultiSeries.POST.lower
24/04/2020 10:50:43 :: [tagdb] Tagged icinga2.icinga_lan_971lafamille_com.services.load.load.perfdata.load15.warn in 0.013565301895141602
24/04/2020 10:50:48 :: [tagdb] Tagging icinga2.icinga_lan_971lafamille_com.services.ping4.ping4.perfdata.rta.crit
24/04/2020 10:50:48 :: [tagdb] Tagged icinga2.icinga_lan_971lafamille_com.services.ping4.ping4.perfdata.rta.crit in 0.014507055282592773
24/04/2020 10:50:49 :: [listener] MetricLineReceiver connection with 127.0.0.1:43382 established
24/04/2020 10:51:03 :: [tagdb] Tagging icinga2.docker-manager_lan_971lafamille_com.services.geco_memory.geco_check_ncpa_memory.perfdata.free.crit
`

If i try to graph the carbon metrics to test my instance, it works : 

![graphite_carbon_capture](https://user-images.githubusercontent.com/23743455/80205708-5c641500-862b-11ea-9522-d62da257e4d5.PNG)

But if i try another metric comming from icinga, it shows nothing 

![graphite_capture](https://user-images.githubusercontent.com/23743455/80204937-122e6400-862a-11ea-9ee1-a7aaed7e7876.PNG)

And here is the strange thing, if you try the same metric in grafana, you can see that the metric is kind of here because it shows the DOTS ?! But you can not connect the dots between them... It is like the data is here but graphite-web and grafana are not able to draw line with it for some reason ?!

![grafana_capture](https://user-images.githubusercontent.com/23743455/80204935-1195cd80-862a-11ea-9d80-5c2c48e48c0b.PNG)


And i tried whisper-info on the metrics file, it says that metric points are here


`
/opt/graphite/bin # ./whisper-info.py /opt/graphite/storage/whisper/icinga2/ansible_lan_971lafamille_com/services/geco_cpu/geco_check_ncpa_cpu/perfdata/percent/value.wsp
aggregationMethod: average
maxRetention: 155520000
xFilesFactor: 0.30000001192092896
fileSize: 3240052

Archive 0
offset: 52
secondsPerPoint: 10
points: 2160
retention: 21600
size: 25920

Archive 1
offset: 25972
secondsPerPoint: 60
points: 8640
retention: 518400
size: 103680

Archive 2
offset: 129652
secondsPerPoint: 600
points: 259200
retention: 155520000
size: 3110400

/opt/graphite/bin #
`


I hope my explanation is better now, ask me everything you need !

**Comment by ploxiln** [comment]
I think your metric is too sparse for your first storage tier (archive 0). It looks like this data is being submitted  once per minute, but your first storage tier is 6 datapoints per minute, so only 1/6 of data-points are non-null. Because your xFilesFactor is 0.3, which is greater than 1/6, this data becomes all null when rolled-up to your second storage tier (archive 1). When looking at time periods longer than 21600 seconds, graphite-web skips the first storage tier and just uses the second storage tier, while I guess graphana might use both (but the dots are not connected because of the nulls in between).

**Comment by piotr1212** [comment]
Yes what @ploxiln says. Change your storage-schemas.conf to have the smallest interval 60s, then resize all .wsp files or simply delete them so they get recreated.

**Comment by hugosxm** [comment]
Thanks @ploxiln and @piotr1212 for that piece of knowledge that fixed my problem :) i'll close the issue, sorry i feel dumb for not found that, i guess my configuration volume in docker did not mount properly of something like that but the storage-schemas.conf was messed up...

Have a nice day !
