### ISSUE TITLE
[BUG] when there are so many events , graphite does not handle it well

### ISSUE THREAD

**Issue by mrtypn** [graphite-project/graphite-web#2595]
**Describe the bug**
We stored "events", "tags"  in mysql database , our system has about 1.5 million events and 10 million "tagging_taggeditem".  I usually got time out when querying the event data from timeout.

**To Reproduce**
This is what i see in mysql log:
SELECT `events_event`.`id`
        FROM `events_event`, `tagging_taggeditem`
        WHERE `tagging_taggeditem`.content_type_id = 12
          AND `tagging_taggeditem`.tag_id IN (2,3,4,3344,23,239)
          AND `events_event`.`id` = `tagging_taggeditem`.object_id
        GROUP BY `events_event`.`id`
        HAVING COUNT(`events_event`.`id`) = 6;

It takes about 2 minutes to complete, this will through the time out error.

**Expected behavior**
If we add an "AND when " in the query, it's much faster.
FROM `events_event`, `tagging_taggeditem`
        WHERE `tagging_taggeditem`.content_type_id = 12
          AND `tagging_taggeditem`.tag_id IN (2,3,4,3344,23,239)
          AND `events_event`.`id` = `tagging_taggeditem`.object_id
          **AND `events.event`.when>'2020-01-01' and  AND `events.event`.when<'2020-02-01'**
        GROUP BY `events_event`.`id`
        HAVING COUNT(`events_event`.`id`) = 6;

**Screenshots**

**Environment (please complete the following information):**
 Graphite 1.1.5

**Additional context**

**Comment by mrtypn** [comment]
After debugging the code, the problem comes from this function Event.tagged.with_all(tags) , going further you will see it's from /opt/graphite/lib/python3.7/site-packages/tagging/models.py with the function get_intersection_by_model(...)  , in that function you will see that there is a join operation between event_events and tagging_taggeditem , so when there are millions record that join will become a real issue.

I'm not a Python expert, so this is my quick fix.

/opt/graphite/storage/models.py


 def find_events(time_from=None, time_until=None, tags=None, set_operation=None):

        if tags is not None:
            if set_operation == 'union':
                query = Event.tagged.with_any(tags)
            elif set_operation == 'intersection':
                query = Event.tagged.with_intersection(tags)
            else:
#==============================================================================================
#My customize code
#==============================================================================================
                if(len(tags)>2):
                    from tagging.utils import get_tag_list
                    tags_list = (get_tag_list(tags))
                    tags_id=[]
                    for idx in tags_list:
                          tags_id.append(idx.pk)
                    if len(tags_id)==0:
                        return []
                    additional_where =""
                    if time_from is not None:
                        additional_where = "%s  and  `when` >= '%s' " % (additional_where, time_from)
                    if time_until is not None:
                        additional_where = "%s   and `when` <= '%s' " % (additional_where,time_until)
                    sql = """
    SELECT events_event.id
    FROM events_event, tagging_taggeditem
    WHERE tagging_taggeditem.content_type_id = 12
    AND tagging_taggeditem.tag_id IN (%s)
    AND events_event.id = tagging_taggeditem.object_id
    %s
    GROUP BY events_event.id
    HAVING COUNT(events_event.id) = %s;""" % ( ",".join(map(str,tags_id)),additional_where,len(tags_id))
                    event_query  = Event.objects.raw(sql)
                    event_ids=[]
                    for event_id in event_query:
                           event_ids.append(event_id.id)

                    sql = """
    SELECT * FROM events_event
    WHERE (events_event.id IN (%s) )
    """  % ",".join(map(str,event_ids))
                    return list(Event.objects.raw(sql))
                else:
#==============================================================================================
                    query = Event.tagged.with_all(tags)
        else:
            query = Event.objects.all()

        if time_from is not None:
            query = query.filter(when__gte=time_from)

        if time_until is not None:
            query = query.filter(when__lte=time_until)

        result = list(query.order_by("when"))
        return result

**Comment by deniszh** [comment]
Hi @mrtypn,
Thanks for your report! Yes, storing tags in database is sub-optimal, that's known issue - Redis works much faster. I'm not sure that your solution is generic enough to include it in the code.
I'll include it below for clarity. Thoughts, @DanCech @piotr1212 @ploxiln @cbowman0 ?
```python
 def find_events(time_from=None, time_until=None, tags=None, set_operation=None):

        if tags is not None:
            if set_operation == 'union':
                query = Event.tagged.with_any(tags)
            elif set_operation == 'intersection':
                query = Event.tagged.with_intersection(tags)
            else:
#==============================================================================================
#My customize code
#==============================================================================================
                if(len(tags)>2):
                    from tagging.utils import get_tag_list
                    tags_list = (get_tag_list(tags))
                    tags_id=[]
                    for idx in tags_list:
                          tags_id.append(idx.pk)
                    if len(tags_id)==0:
                        return []
                    additional_where =""
                    if time_from is not None:
                        additional_where = "%s  and  `when` >= '%s' " % (additional_where, time_from)
                    if time_until is not None:
                        additional_where = "%s   and `when` <= '%s' " % (additional_where,time_until)
                    sql = """
    SELECT events_event.id
    FROM events_event, tagging_taggeditem
    WHERE tagging_taggeditem.content_type_id = 12
    AND tagging_taggeditem.tag_id IN (%s)
    AND events_event.id = tagging_taggeditem.object_id
    %s
    GROUP BY events_event.id
    HAVING COUNT(events_event.id) = %s;""" % ( ",".join(map(str,tags_id)),additional_where,len(tags_id))
                    event_query  = Event.objects.raw(sql)
                    event_ids=[]
                    for event_id in event_query:
                           event_ids.append(event_id.id)

                    sql = """
    SELECT * FROM events_event
    WHERE (events_event.id IN (%s) )
    """  % ",".join(map(str,event_ids))
                    return list(Event.objects.raw(sql))
                else:
#==============================================================================================
                    query = Event.tagged.with_all(tags)
        else:
            query = Event.objects.all()

        if time_from is not None:
            query = query.filter(when__gte=time_from)

        if time_until is not None:
            query = query.filter(when__lte=time_until)

        result = list(query.order_by("when"))
        return result

```

**Comment by DanCech** [comment]
@deniszh this is talking about events, not series tagging.

Testing this locally I definitely see the `WHERE` clauses for `events_event.when` being added to the query.  Are you maybe running an old version of django or django tagging?

I do note that there is no index on the `when` column, it may be more efficient if we add an index on that column so that the database can filter more efficiently.

To have django print all queries for debugging you can add this to your local_settings.py:
```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    }
}
```

**Comment by mrtypn** [comment]
@DanCech  , 

The issue  is from this function `query = Event.tagged.with_all(tags)` in this function

`def find_events(time_from=None, time_until=None, tags=None, set_operation=None):`

That function does not use the date , it's in tagging package

**Comment by deniszh** [comment]
Riiight, sorry, I didn't check patch thoroughly and didn't understand it relates to different type of tags. 🤦
Not sure how to properly propagate date info to  `Event.tagged.with_all(tags)` though....

**Comment by DanCech** [comment]
@mrtypn that function executes a query against tagging_tag to get the tag ids, but it generates a QuerySet object for the main query, which subsequently has the filter added to it and then gets executed when it's cast to a list.  With query logging enabled I get queries like this:
```
(0.000) SELECT `tagging_tag`.`id`, `tagging_tag`.`name` FROM `tagging_tag` WHERE `tagging_tag`.`name` IN ('blah') ORDER BY `tagging_tag`.`name` ASC; args=(u'blah',)
```
and
```
(0.001) SELECT `events_event`.`id`, `events_event`.`when`, `events_event`.`what`, `events_event`.`data`, `events_event`.`tags` FROM `events_event` , `tagging_taggeditem` WHERE ((`tagging_taggeditem`.content_type_id = 8) AND (`tagging_taggeditem`.tag_id = 1) AND (`events_event`.`id` = `tagging_taggeditem`.object_id) AND `events_event`.`when` >= '1970-01-01 00:00:00' AND `events_event`.`when` <= '2020-05-04 13:49:13') ORDER BY `events_event`.`when` ASC; args=(8L, 1L, u'1970-01-01 00:00:00', u'2020-05-04 13:49:13')
```
It's possible that there's another path inside tagging that executes another intermediate query depending on the results of the first query, but I haven't gone digging.  If you could enable sql logging as above and share the results you get that might help understand what's going on.
