### ISSUE TITLE
how to find all metrics recursively in 1 http request?

### ISSUE THREAD

**Issue by Dieterbe** [graphite-project/graphite-web#26]
Hi,
I've been looking in webapp/graphite/metrics/views.py trying to find a way to get a listing of _all_ metrics in 1 request. (for example in json)
this doesn't seem to be possible yet. 
I'm a bit confused, it seems that there are multiple functions that do similar things, by different means.:
`find_view` finds metrics by using a Store object from webapp/graphite/storage.py, whereas `expand_view` does something similar, as does `tree_json` which uses another mechanism, and then there's `search` which I haven't figured quite out (it seems to use a textbased index. btw: interestingly on my testing machine the index file does not get created)

please advise how I should proceed.

**Comment by supre** [comment]
Is there a way to find out active metrics and not all metrics. We have a lot of metrics which we don't use anymore but they do appear in the list with /metrics/find?query=*. I only want to see the metrics that are being actively used right now.

**Comment by bmhatfield** [comment]
@supre - I have an alternate approach to this problem. On the Graphite server itself, I run some variation of this command: `sudo find /opt/graphite/storage/whisper -type f -name *.wsp -mtime +7 -ls -delete && sudo find /opt/graphite/storage/whisper/ -type d -empty -delete`, which will remove all metrics that have not been written to in the past week.

**Comment by keen99** [comment]
@supre http://graphite-api.readthedocs.io/en/latest/api.html#the-metrics-api suggests the `from` parameter, fwiw.
