### ISSUE TITLE
[Q]Is graphite tool displaying aggregate value in graph for longer date range?

### ISSUE THREAD

**Issue by Rock-sa** [graphite-project/graphite-web#2600]
I am plotting the graph for the status for which value would be either 0 or 1. Graph looks fine when seeing for small range like 30 min,5h, but when look the same graph for larger range like 7 days,1 week, graph looks different. Does it use aggregation? How does it work?

**Comment by ploxiln** [comment]
This is controlled by "carbon-cache":
https://github.com/graphite-project/carbon/blob/master/conf/storage-schemas.conf.example
https://github.com/graphite-project/carbon/blob/master/conf/storage-aggregation.conf.example
