### ISSUE TITLE
[BUG] Function linearRegressionAnalysis not found

### ISSUE THREAD

**Issue by mcbsd** [graphite-project/graphite-web#2601]
**Describe the bug**
Applying function linearRegressionAnalysis to series via GUI displays empty page.
When requesting the same via CLI, the response is:

`Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py&quot;, line 41, in inner
    response = get_response(request)
  File &quot;/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py&quot;, line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File &quot;/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py&quot;, line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File &quot;/opt/graphite/webapp/graphite/render/views.py&quot;, line 118, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 28, in evaluateTarget
    result = evaluateTokens(requestContext, target)
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 57, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 84, in evaluateTokens
    func = SeriesFunction(tokens.call.funcname)
  File &quot;/opt/graphite/webapp/graphite/functions/__init__.py&quot;, line 81, in SeriesFunction
    raise KeyError(&#39;Function &quot;%s&quot; not found&#39; % name)
KeyError: &#39;Function &quot;linearRegressionAnalysis&quot; not found&#39;`

**To Reproduce**
Apply function linearRegressionAnalysis to series.
curl -X GET  'http://server1/render?target=linearRegressionAnalysis(server2.disk.var.used_pct)&from=now-10min&format=json'

**Expected behavior**
To return data as expected by documentation

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS flavor: Redhat 7.8
 - Graphite-web version 1.1.5
 - Django/Python version django 1.8.7 python 2.7/3.6
 - Setup type: from source

**Additional context**
I have checked the source code directly on the system and subjected function is present in:
......graphite-web-1.1.5/webapp/graphite/render/functions.py
......graphite-web-1.1.5/build/lib/graphite/render/functions.py
Function linearRegression works fine

**Comment by piotr1212** [comment]
I think this is an internal only function and should not be listed in the documentation. Is there a specific reason that you are using linearRegressionAnalisys() instead of linearRegression()?

**Comment by mcbsd** [comment]
Hi,

thanks for such fast answer. I am using linearRegression already but I somehow expected that linearRegressionAnalisys would return parameters around slope of the line so it is then later easily used compared to working with direct datasets of the line.
But I didn't expect this to be internal function:) Now it's clear and I am going to close this.
