### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by throrin19** [graphite-project/graphite-web#2603]
**Describe the bug**
Randomly, my graphite server crash with many `MemoryError` exception without know what triggered this memory problem.

At one time, I have to restart manually the graphite server to make it works

**To Reproduce**

I don't know, I test all memoryError requests without any success of bug reproduction

**Expected behavior**

**Screenshots**

This is the metrics of graphite server on this Memory Error problem : 

![image](https://user-images.githubusercontent.com/1394778/82024714-7c1db480-9690-11ea-9d00-d866f60fec53.png)

**Environment (please complete the following information):**
 - OS flavor: Ubuntu with docker
 - Graphite-web version 1.1.5
 - Django/Python version 2.2.12/3.8.2
 - Setup type docker : https://github.com/graphite-project/docker-graphite-statsd

The server is running on AWS EC2 `c5.large`

**Additional context**

This is the exception output : 

```
020-05-14,16:39:43.556 :: Exception encountered in <POST http://graphite.nestle.nestle.production.aquassay.net/render>
Traceback (most recent call last):
  File "/opt/graphite/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 118, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 15, in evaluateTarget
    prefetchData(requestContext, pathExpressions)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 263, in prefetchData
    for result in STORE.fetch(pathExpressions, startTime, endTime, now, requestContext):
  File "/opt/graphite/webapp/graphite/storage.py", line 190, in fetch
    'fetch for %s' % str(patterns))
  File "/opt/graphite/webapp/graphite/storage.py", line 132, in wait_jobs
    raise Exception(message)
Exception: All requests failed for fetch for ['customer.company.place.point.conductivity_4', 'customer.company.place.point.turbidity_1', 'customer.company.place.point.volume_1'] (1)

fetch for ['customer.company.place.point.conductivity_4', 'customer.company.place.point.turbidity_1', 'customer.company.place.point.volume_1']: : Traceback (most recent call last):

  File "/opt/graphite/webapp/graphite/worker_pool/pool.py", line 43, in run
    self.result = self.func(*self.args, **self.kwargs)

  File "/opt/graphite/webapp/graphite/finders/utils.py", line 140, in fetch
    now=now, requestContext=requestContext

  File "/opt/graphite/webapp/graphite/node.py", line 30, in fetch
    result = self.reader.fetch(startTime, endTime, now, requestContext)

  File "/opt/graphite/webapp/graphite/readers/whisper.py", line 59, in fetch
    data = self.fetch_data(startTime, endTime, now=now)

  File "/opt/graphite/webapp/graphite/readers/whisper.py", line 55, in fetch_data
    return whisper.fetch(self.fs_path, startTime, endTime, now=now)

  File "/opt/graphite/lib/python3.7/site-packages/whisper.py", line 906, in fetch
    return file_fetch(fh, fromTime, untilTime, now, archiveToSelect)

  File "/opt/graphite/lib/python3.7/site-packages/whisper.py", line 959, in file_fetch
    return __archive_fetch(fh, archive, fromTime, untilTime)

  File "/opt/graphite/lib/python3.7/site-packages/whisper.py", line 1011, in __archive_fetch
    seriesString += fh.read(untilOffset - archive['offset'])

MemoryError
```

**Comment by deniszh** [comment]
One of your whisper files are too big to fit in Graphite werking process memory. How much memory do you provide for Graphite docker container?

**Comment by throrin19** [comment]
Oh it's possible, In my case, we have metrics over 10 years.

I don't set memory limit on the container or on Docker.

**Comment by deniszh** [comment]
So, it's 3.6GB. Not sure is if your whisper file that big, but error message say so.... Whisper taking 12 bytes per point, so, 4GB whisper file will contain around 360M points, it's around 10 years with second resolution, indeed.
Usually people using many archives and aggregation in whisper for storing such long intervals, but nothing (except your RAM) stops you from storing such archives.
You need or change your schema or give (much more) memory for your graphite server. Please note that 4GB need for _every_ file with such terrific data resolution.

**Comment by throrin19** [comment]
I use this retention for this specifics files : 

```
1m:1y,5m:4881d,15m:9398d,30m:13915d,1h:18432d,2h:22949d,6h:27466d,12h:31983d,1d:100y
```

Each file size is 53.15 Mo

**Comment by deniszh** [comment]
Hm, your schema looks bit odd to me, but indeed, it's around 4M datapoints and 50 MB in size.
Very strange.

**Comment by throrin19** [comment]
Can the problem occur if there are too many requests running at the same time?
In my case this is exactly what happens because of many graphics in grafana dashboard.

**Comment by deniszh** [comment]
Maybe, worth to try to give it more memory then.

**Comment by throrin19** [comment]
Thanks for your responses. I will try that. I come back if I encounter the problem again despite the increase of server memory.
