### ISSUE TITLE
/functions endpoint returns invalid JSON

### ISSUE THREAD

**Issue by shanson7** [graphite-project/graphite-web#2609]
**Describe the bug**
Upgrading from a rather old version of graphite to the latest provided by [graphite-mt](https://github.com/raintank/graphite-mt) (graphite version `7ebde4c60`).

Grafana started to fail to display certain functions like `movingWindow`. I think it's due to `Infinity` being returned as a number. This parses fine in python but a lot of other tools fail.

```
$ curl -s http://graphite-stage-nj.internal.com/functions | json_pp
malformed JSON string, neither array, object, number, string or atom, at character offset 52236 (before "Infinity, "type": "i...")
```

That position seems to be `{"default": Infinity,` for the interpolate function. `Infinity` shows up for keepLastValue as well.

**To Reproduce**
Try to parse the json returned from `/functions`

**Expected behavior**
Should parse as JSON

**Comment by ploxiln** [comment]
Hmm ... `Infinity` is accepted by the python json parser, and the c library json-c, and `Infinity` is valid  javascript ... but indeed, `Infinity` does not seem to be accepted nodejs or firefox using `JSON.parse()`, and it is technically not in the standard https://tools.ietf.org/html/rfc7159#section-6

Well, that's awkward.

**Comment by DanCech** [comment]
We do some "special" handling in the render output json to deal with that:
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/views.py#L242
```
  output = json.dumps(series_data, indent=(2 if requestOptions.get('pretty') else None)).replace('None,', 'null,').replace('NaN,', 'null,').replace('Infinity,', '1e9999,')
```

**Comment by schen1152** [comment]
hello, any updates/eta on the fix for this issue?

**Comment by deniszh** [comment]
Could someone check is this issue still relevant for latest Grafana and
latest Graphite versions? I’m currently AFK.
If still - maybe it can be fixed separately, without global rework of json
parser?

**Comment by ploxiln** [comment]
The root of the problem, still exists, is that graphite-web sometimes includes Infinity or Nan in data structures which it serializes to json (and the python stdlib json will allow that), but javascript `JSON.parse()` will reject that json, both in browsers and nodejs.

I have a somewhat hacky fix idea, which I didn't have time to test yet, at https://github.com/graphite-project/graphite-web/pull/2612 (and I'm abandoning #2610 as not critical and not the best way).
