### ISSUE TITLE
Graphite converts '/' to '.'

### ISSUE THREAD

**Issue by JAPerezSatQ6** [graphite-project/graphite-web#2611]
Hi,

I'm working on a personal NodeJS library that will send API metrics to Graphite. Currently I'm working with the npm package 'graphite-tcp' which creates a client that connects to my server. 

I'm sending this metric: 

`TS-Logger.test.ip-192-168-1-13.ec2.internal.REST./api/v1/cards./export.count `

But all the '/' get converted to dots once it gets to Graphite so it ends up being:

`TS-Logger.test.ip-192-168-1-13.ec2.internal.REST.api.v1.cards..export.count`

![image](https://user-images.githubusercontent.com/60617465/82848712-fd0b5600-9eb1-11ea-8044-40b19edd9616.png)

I was wondering if there are any workarounds or suggestions.

Thanks!

**Comment by piotr1212** [comment]
Not much you can do on Graphite side because the slashes collide with directories. Replace the slashes with underscores before sending.
