### ISSUE TITLE
[Q] How to use rewrite-rules.conf properly?

### ISSUE THREAD

**Issue by nikobearrr** [graphite-project/graphite-web#2617]
I am trying to rename a variable I receive from my stats. It looks like this: `server.server1.log.m1_rate`, so I would like to rename `m1_rate` to just `rate`. 
I read the information here: https://graphite.readthedocs.io/en/latest/config-carbon.html#rewrite-rules-conf as well as teh rewrite-rules.conf.example provided in the config.

So I created a `rewrite-rules.conf` and I added those lines:

```
[pre]
\.m1_rate = \.rate
m1_rate = rate
m1_rate$ = rate
.*\.m1_rate$ = \1.rate
.*m1_rate = \1rate
```

At some point I tried them 1 by 1, but none worked. if I go to https://regex101.com/ and test them with my test string I get a 100% match on all 5 different regex.

I have also enabled this in `carbon.conf`: `REWRITE_RULES = rewrite-rules.conf`

I can see my own `REWRITE_RULES = rewrite-rules.conf` is in the `/opt/graphite/conf` folder in the container, but the stats is not rewritten. 

Any idea what I am doing wrong?

Using graphite 1.1.7-2 in docker

**Comment by ploxiln** [comment]
Are you using `carbon-aggregator`? It's usually a separate service from `carbon-cache`, and is often not running in the most simple/bare setups (I usually don't run it). The aggregator is the service that uses `rewrite-rules.conf`. See https://graphite.readthedocs.io/en/latest/carbon-daemons.html#carbon-aggregator-py

**Comment by nikobearrr** [comment]
Hi @ploxiln, thanks for the suggestion. You were right - I had not setup carbon-aggregator.
