### ISSUE TITLE
[Q] is it possible to request a specific step with Raw output?

### ISSUE THREAD

**Issue by jranson** [graphite-project/graphite-web#2618]
Hi! It looks like when I query the same target for a range like `from=-1h` vs a range like `from=-24h`, Graphite will automatically select a step resolution in the results based on the overall width of the time range. While that is very convenient, what if I wanted to request a specific step (e.g., a 30s step for 24 hours of data), instead of whatever Graphite selects? I see that, with json output only, you can provide a `maxDataPoints` parameter to indirectly force a _big_ step, but am unable to find a way to predictably force a _tiny_ step, e.g., a high resolution output over a large period of time. Is there any way to control the step more directly/predictably as part of the query? We prefer to use the raw output format, but any format that allows this capability would work for our use case. thanks!

**Comment by DanCech** [comment]
the resolution of the response will by default be the highest resolution you have stored in your whisper files for the time period you're querying.  You can use summarize or smartSummarize to lower the resolution to a specified interval size, but if your underlying data set is at 1 minute intervals then asking for output at 10-second intervals doesn't make much sense.

**Comment by piotr1212** [comment]
Graphite gives the "tyniest" step available for the requested range.

**Comment by jranson** [comment]
Ah got it, so the difference I am seeing between the ranges is actually due to older data being rolled up and thus reducing the minimum resolution available to the entire range. From here I'll read through the docs to better understand this rollup behavior. Thanks very much for the fast responses!
