### ISSUE TITLE
[Q] KeyError at /metrics/find/ 'metric_path'

### ISSUE THREAD

**Issue by worapojc** [graphite-project/graphite-web#2621]
Hi,

I would like to ask about how to resolve the KeyError issue.

We have 3 DCs in Production environment; DC 1, DC 2 and DC 3.
DC 3 is a new build to replace DC 2. We have synced the data from DC 2 to DC 3.

Environment
DC 1 and DC 2: RHEL6, Graphite 0.9, Graphite Web 0.9.12
DC 3: RHEL7, Graphite 1.1.6, Graphite Web 0.9.12

**Previous**
The local_settings.py of DC 1 and DC2.
DC 1 and DC 2 members configured in _MEMCACHE_HOSTS_ and _CLUSTER_SERVERS_.

**Current** 
The local_settings.py of DC 1 and DC3.
DC 1 and DC 3 members configured in _MEMCACHE_HOSTS_ and _CLUSTER_SERVERS_. (Removed DC 2)

Then, I restarted Apache HTTPD service and I found this issue when I tried to expand the tree in Graphite Web and Grafana.

> Request Method: GET
> Request URL: http://localhost:8081/metrics/find/?_dc=1592222876079&query=*&format=treejson&contexts=1&path=&node=GraphiteTree
> Django Version: 1.4.1
> Python Executable: /usr/bin/python
> Python Version: 2.6.6
> ...
> Exception Type: KeyError at /metrics/find/
> Exception Value: 'metric_path'
> Request information:
> GET:
> node = u'GraphiteTree'
> format = u'treejson'
> contexts = u'1'
> _dc = u'1592220184285'
> path = u''
> query = u'*'
> 
> POST: No POST data
> 
> FILES: No FILES data

In DC3, it can expand the tree and read metrics from DC1 on Graphite Web. I've not tested in Grafana.

Could you please advise on this situation?

**Comment by piotr1212** [comment]
It is not clear to me what you are doing.

**Comment by worapojc** [comment]
I build the new DC (DC3) to replace DC2. DC3 can read local metrics and remote metrics DC1.
However, DC1 can read local metrics only. I've reconfigured local_settings.py on DC1 and executed syndb command but it doesn't work.

**Comment by piotr1212** [comment]
If I'm understanding correctly you try to query a graphite-web version 1.1.6 from a 0.9.12 version? I don't think that is ever tested, don't know if it is supposed to work.

**Comment by deniszh** [comment]
It's definitely not supported and will not work, unfortunately

**Comment by worapojc** [comment]
Thank you for the confirmation. I'll use the same version to fix the issue.
