### ISSUE TITLE
[BUG] Bug in Event-Tags

### ISSUE THREAD

**Issue by rplc** [graphite-project/graphite-web#2622]
I'm submitting events with several tags to graphite. If I want to retreive the events I cannot filter for the tags.
The bug occurs in the [event function](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.events) as well in the admin interface (http://you-graphite.com/events?from=-1d&tags=...).
In the graphite function I need to filter for "\*" tags to retrieve any data. As soon as I do not add a filter or any filter other than "\*" no data will be retrieved.
Similar problem occurs using the events route. As soon as I add the tags get param no events will be shown. If I omit the tag param all events are listet.

**To Reproduce**
Fire up the 1.1.7-2 tag of the docker image. Submit events with tags and try to search for events, using ```drawAsInfinite(events('someTagHere'))``` no data will be shown. If you use ```drawAsInfinite(events('*'))``` events appear.

Sadly I am not able to pin point the version that broke the event filter. I was a few versions behind before I upgraded to the 1.1.7-2 Docker image.

**Comment by deniszh** [comment]
Hi @rplc 

Could you please give me version where this code was working?

**Comment by rplc** [comment]
Hi,

I'm confused. I cannot reproduce the bug in a fresh started graphite container. So it seems to correlate with the number of events or anything went wrong in one of the previous updates?

Furthermore I found, that I can filter my events on the events route with the from **or** the tags get param. Either of them work. But combined they do not work.
So
http://your-graphite.com/events?tags=tag2 Returns data
http://your-graphite.com/events?from=-1d Returns data
http://your-graphite.com/events?from=-1d&tags=tag2 Returns no events

We have about 5000 events in our live database and 1000 in our test database. And the problem occurs in both of them.

**Comment by deniszh** [comment]
Maybe related to https://github.com/graphite-project/graphite-web/issues/2595 ?
That's not my area of expertise tbh
