### ISSUE TITLE
wrong group for IsNonNull & powSeries

### ISSUE THREAD

**Issue by zivillian** [graphite-project/graphite-web#2630]
IsNonNull is not combining multiple series of a wildcard into a single series, so this should be moved to group Transform.

https://github.com/graphite-project/graphite-web/blob/2f133192ed6c459dfa741c42c08d0627747df5ac/webapp/graphite/render/functions.py#L4572

**Comment by zivillian** [comment]
powSeries is combining two or more series into a single result so it should be moved to group Combine

https://github.com/graphite-project/graphite-web/blob/2f133192ed6c459dfa741c42c08d0627747df5ac/webapp/graphite/render/functions.py#L1522

**Comment by ploxiln** [comment]
looks like this was fixed and can be closed
