### ISSUE TITLE
[BUG] moving* is shifting data

### ISSUE THREAD

**Issue by zivillian** [graphite-project/graphite-web#2632]
**Describe the bug**
All moving* functions shift the data by one step into the future.

**To Reproduce**
Query the metric itself and additionally with moving* and a window size of 1.
```
/render?
target=carbon.agents.*.cpuUsage&
target=movingMax(carbon.agents.*.cpuUsage, 1)
```
**Expected behavior**
Both series should be equal.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6039253/91747758-07c73c80-ebbf-11ea-8597-07d63b0f8022.png)

**Environment (please complete the following information):**
 - OS flavor: Ubuntu
 - Graphite-web version 1.1.4

**Comment by deniszh** [comment]
Hi @zivillian,

Yes, I can reproduce it in latest Graphite, not only for moving* functions but also for e.g. `exponentialMovingAverage`.
I think it's coming from https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L1117
`https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L1117`
Not sure is it and how it can be fixed easily. @DanCech ?

**Comment by DanCech** [comment]
It could likely be changed by tweaking https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L1132 to move the new series' start time by one step, but I'm not sure what the implications of doing that would be.

**Comment by zivillian** [comment]
I guess the error is at https://github.com/graphite-project/graphite-web/blob/17a34e7966f7a46eded30c2362765c74eea899cb/webapp/graphite/render/functions.py#L1136-L1137

For a windowSize of 1 `series[i - windowPoints:i]` is actually using the previous datapoint `series[1 - 1:1]` which is `series[0:1]` including `series[0]` but excluding `series[1]` to calculate the first datapoint for the result. Since `series` includes one additional datapoint from the past, the past datapoint is used to calculate the first resulting datapoint.

**Comment by ploxiln** [comment]
I think that's a good way to think about it, but I think the problem nearer the line @deniszh pointed out:

```python
  if isinstance(windowSize, six.string_types):
    delta = parseTimeOffset(windowSize)
    previewSeconds = abs(delta.seconds + (delta.days * 86400))
  else:
    previewSeconds = max([s.step for s in seriesList]) * int(windowSize)

...

  newContext['startTime'] = requestContext['startTime'] -  timedelta(seconds=previewSeconds)
```

For a windowSize of `1` we don't want any history, we want only the current point. For a windowSize of `2`, we want just 1 previous point, and the current point, I think. It looks like the existing logic takes windowSize before, and not including, the current point.

So the simple case should be like:

```python
  else:
    previewSeconds = max([s.step for s in seriesList]) * (int(windowSize) - 1)
```

With that, I think the range logic that @zivillian pointed out works OK.

For the time-period-based windowSize, I guess it should somehow subtract one "step" from `previewSeconds`, but it's less obvious ...

**Comment by zivillian** [comment]
Ignoring the overhead of loading one additional unused datapoint a simple fix for both (relative and absolue windowSize) could be:

```diff

-    for i in range(windowPoints, len(series)):
+    for i in range(windowPoints + 1, len(series)):
      nonNull = [v for v in series[i - windowPoints:i] if v is not None]
```

**Comment by ploxiln** [comment]
Yeah, that's simple and seems like it will work, but the `endTime` of the overall series will then also be 1 step before what is expected by the query, I think ...

**Comment by zivillian** [comment]
But judging from the screenshot above, this would be correct.

**Comment by zivillian** [comment]
It's not solved, so it should not be closed.
