### ISSUE TITLE
[BUG] Fetch Timeout issue while creating build-index

### ISSUE THREAD

**Issue by AshishVerma7690** [graphite-project/graphite-web#2638]
**Describe the bug**
we are facing fetchtimeout  issue again and again while creating build-index.
We use grafana for our UI. 
 

**Expected behavior**
index should be created.

**Environment (please complete the following information):**
 OS flavor: Ubuntu
 Graphite-web version - 1.1.5
 Django/Python version - 2.0.13/Python3.6

**Comment by deniszh** [comment]
Hi @AshishVerma7690 ,
What is build-index and why do you need to create it?

**Comment by AshishVerma7690** [comment]
build-index : A tool to generate the search index file used by graphite web. 
While creating indexing I am getting error of fetchtimeout.  
I guess If I am using grafana for UI I don't need to create index files.

**Comment by AshishVerma7690** [comment]
@deniszh  any suggestions on this?

**Comment by deniszh** [comment]
@AshishVerma7690 : yes, you do not need build-index  tool if using Grafana. It's used only  in metric search in Graphite dashboard and it's not really scalable for big number of metrics.
