### ISSUE TITLE
How to get data into Graphite using plaintext protocol?[Q]

### ISSUE THREAD

**Issue by dinBo** [graphite-project/graphite-web#2642]
First of all, I’m new to Graphite, so sorry if this question has an obvious answer that I’m somehow missing.

So, I’ve set up Graphite and Grafana via Docker using the following instructions (The “Up and running in (almost) 5 minutes“ section): https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/. I’m using these instructions because I’ll be using both metrics gained from sitespeed.io and from a custom Node.js script.

I’m trying to send the data from Node.js script to Graphite using **plaintext protocol** (https://graphite.readthedocs.io/en/latest/feeding-carbon.html#the-plaintext-protocol). I’ve used the **’net’ library** (https://nodejs.org/api/net.html) to send the data via TCP:
<img width="961" alt="Pasted Graphic 8" src="https://user-images.githubusercontent.com/15899815/96442719-de647d80-120b-11eb-913a-330c69150efa.png">

When I run the script, this is what is logged:
<img width="589" alt="Pasted Graphic 9" src="https://user-images.githubusercontent.com/15899815/96443108-634f9700-120c-11eb-890f-60c2cb0f2bae.png">

And also, I’m **able to access it** in grafana:
<img width="696" alt="Pasted Graphic 10" src="https://user-images.githubusercontent.com/15899815/96443153-7cf0de80-120c-11eb-8a34-4422e557f03d.png">

The problem is that I’m **not able to see the data value** in Grafana, even when I explicitly give it the timestamp, it’s like it doesn’t reach it. Here’s the example for timestamp **1603104600000** (Date and time for GMT+2 zone: 2020-10-19 12:50:00 AM):
<img width="802" alt="Pasted Graphic 11" src="https://user-images.githubusercontent.com/15899815/96443187-8b3efa80-120c-11eb-84b4-e194d5ecacb0.png">

It’s not shown in the graph or table in Explore tab (look at the last entry in table):
<img width="1671" alt="Pasted Graphic 12" src="https://user-images.githubusercontent.com/15899815/96443408-d953fe00-120c-11eb-8340-8645e06a645e.png">

And in Query inspector it says it’s null for the given timestamp:
<img width="1671" alt="Pasted Graphic 13" src="https://user-images.githubusercontent.com/15899815/96443448-e53fc000-120c-11eb-8d70-a3bbc7344e10.png">

How can I get the data into graphite using plaintext protocol? Am I missing to add something when sending data to Graphite?

Thanks,
Bodin

**Comment by piotr1212** [comment]
I think you got a few zeros too much in your date.

**Comment by deniszh** [comment]
@dinBo : in Graphite timestamp is in seconds, not milliseconds or nanoseconds.

**Comment by JohanElmis** [comment]
@dinBo Have you been able to test with "lower" resolution on your time?
I used to tests data with some simple bash-command.
Not really a dice - as it gives 0-6 but something to relate to anyway. This send data every 10s, easy to tune for what your server/storage expects.

export PORT=2003
export SERVER="DNS or IP of your server"
while true; do echo "local.random.diceroll $(rand -M 6) `date +%s`" | nc -4 -q0 ${SERVER} ${PORT}; sleep 10; done
