### ISSUE TITLE
Push futur data for prediction into graphite [Q]

### ISSUE THREAD

**Issue by DariusMR** [graphite-project/graphite-web#2651]
Hi everyone,

I'm using graphite from a while and it's working well.

But today I tried to push predictions data to graphite to see abnormal behavoir of some measurements.

And everytime I want to push data with future timestamp, it's ignored. Do I have to change something in my retention policy ?

Thanks in advance !

**Comment by deniszh** [comment]
Hi @DariusMR,

Sorry, but future data is just not supported in Graphite (well, it's not supported in Whisper storage, maybe some alternative backends can do that).

**Comment by DariusMR** [comment]
okay ..
Want do you have in mind ? influxdb ? prometeus ?

**Comment by deniszh** [comment]
@DariusMR : Sorry, but I didn't test any alternative backend for support for future datapoints, just noted that limitation for Graphite lies in whisper storage / format.

**Comment by DariusMR** [comment]
😭

**Comment by deniszh** [comment]
InfluxDB has support for Graphite input, you can try it, together with https://github.com/InfluxGraph/influxgraph if you need Graphite functions support.

**Comment by Mathadon** [comment]
> .

@deniszh would I be complicated to add such support or is it simply a matter of removing the check on this line?
https://github.com/graphite-project/whisper/blob/60c8b9bab5dff6bdafca6880aafca5fcadc0aa77/whisper.py#L928
