### ISSUE TITLE
[Q] URL issues after upgrade and web server software change

### ISSUE THREAD

**Issue by justinclloyd** [graphite-project/graphite-web#2657]
I recently migrated two independent Graphite/Grafana servers (one on-prem and one in AWS) in order to upgrade the OS and Graphite versions, change from Apache to Nginx, and for more system resources. We have internal systems that make heavy use of direct links to metrics and with this upgrade the path seems to have dropped the "/graphite" part. For example:

https://graphite.example.com/graphite?width=586&height=308&target=carbon.agents.*.creates

does not work but 

https://graphite.example.com/?width=586&height=308&target=carbon.agents.*.creates

does work. Leaving in the "graphite" part of the path results in a Not Found page saying "The requested resource was not found on this server."

Also, certain URLs using braces for pattern matching now do not return data, though braces in general do work. So creating a graph with **carbon.agents.sea{,-*}.cache.size** works, showing a dropdown list of the matches, but then the URL is encoded to **carbon.agents.sea%7B%2C-*%7D.cache.size**, which gives no results in the graph.

**Old Server**
Ubuntu 16.04
graphite-carbon and graphite-web packages version 0.9.15 from Ubuntu repo
Apache 2.4.18
mod_wsgi 4.3.0
python-django 1.8.7 from Ubuntu repo

**New Server**
Ubuntu 20.04
carbon, whisper, and graphite-web version 1.2.0 from their graphite-project repos installed via pip3
Nginx 1.18.0 from Ubuntu repo
Gunicorn 20.0.4 installed via pip3
Django 3.0.11 installed via pip3

**Comment by deniszh** [comment]
Hi @justinclloyd ,

>with this upgrade the path seems to have dropped the "/graphite" part 

You need to uncomment URL_PREFIX in your `local_settings.py` and restart Gunicorn:
https://github.com/graphite-project/graphite-web/blob/9b7c761a4d49333cdee3d1eeb7049f6ffbd5529b/webapp/graphite/local_settings.py.example#L83-L84

>So creating a graph with carbon.agents.sea{,-*}.cache.size works, showing a dropdown list of the matches, but then the URL is encoded to carbon.agents.sea%7B%2C-*%7D.cache.size, which gives no results in the graph.

For that part I'm not sure what's going on, maybe something wrong with your web server config?
I can't reproduce on [latest release in Docker](https://github.com/graphite-project/docker-graphite-statsd) though -  braces working fine there. You can check Nginx config for Docker and compare - https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/etc/nginx/sites-enabled/graphite-statsd.conf

**Comment by deniszh** [comment]
You can try yourself, if you have Docker installed somewhere on desktop machine.
Run it first:
```
docker run -d\
 --name graphite\
 --restart=always\
 -p 80:80\
 -p 2003-2004:2003-2004\
 -p 2023-2024:2023-2024\
 -p 8125:8125/udp\
 -p 8126:8126\
 graphiteapp/graphite-statsd
```
then try to open 
http://localhost/render/?width=586&height=308&target=carbon.agents.*.cache.que{-,*}
I'm getting proper graph:
<img width="586" alt="Screenshot 2020-12-10 at 21 26 12" src="https://user-images.githubusercontent.com/1227222/101825838-7c026c00-3b2e-11eb-86c2-87d97f345de0.png">

**Comment by justinclloyd** [comment]
> Hi @justinclloyd ,
> 
> > with this upgrade the path seems to have dropped the "/graphite" part
> 
> You need to uncomment URL_PREFIX in your `local_settings.py` and restart Gunicorn:
> https://github.com/graphite-project/graphite-web/blob/9b7c761a4d49333cdee3d1eeb7049f6ffbd5529b/webapp/graphite/local_settings.py.example#L83-L84

I actually tried that and it broke Grafana, even when I updated the Graphite data source in Grafana. Perhaps there was another config somewhere that also needed updating in conjunction with this change. That said, that variable is not uncommented in my older Graphite system running 0.9.12 on Ubuntu 14.04, which _somehow_ works both with and without the **graphite** between the **/?**.

> 
> > So creating a graph with carbon.agents.sea{,-_}.cache.size works, showing a dropdown list of the matches, but then the URL is encoded to carbon.agents.sea%7B%2C-_%7D.cache.size, which gives no results in the graph.
> 
> For that part I'm not sure what's going on, maybe something wrong with your web server config?
> I can't reproduce on [latest release in Docker](https://github.com/graphite-project/docker-graphite-statsd) though - braces working fine there. You can check Nginx config for Docker and compare - https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/etc/nginx/sites-enabled/graphite-statsd.conf

I can test the Docker stuff but regarding the web server configuration, that's certainly a possibility but I've not found a smoking gun, either in the [nginx config](https://gist.github.com/justinclloyd/c2b7b53857fcb7fd6b288190cb6a97c4) or the [gunicorn service](https://gist.github.com/justinclloyd/40e93c044337843dc5ec6c451b61d159).

**Comment by deniszh** [comment]
> I actually tried that and it broke Grafana, even when I updated the Graphite data source in Grafana.

Well, in case of Grafana your graphs are not dependent on URL, just update datasource path and they should work.

> That said, that variable is not uncommented in my older Graphite system running 0.9.12 on Ubuntu 14.04, which somehow works both with and without the graphite between the /?.

Looks like it was some rewrite in old config, but it's hard to say without looking in old config, though. You can try something like
```
  location /graphite {
    rewrite ^/graphite/(.*) /$1 break;
    proxy_pass http://127.0.0.1:8080;
```

> I can test the Docker stuff but regarding the web server configuration, that's certainly a possibility but I've not found a smoking gun, either in the nginx config or the gunicorn service.

Both looks legit, sorry, no idea 🤷

**Comment by justinclloyd** [comment]
Thank you for the feedback, I'll consider the rewrite option as I continue troubleshooting.

For reference, here's another gist with the [old nginx and gunicorn configs](https://gist.github.com/justinclloyd/7d29da009c9d9d8e451453c4e32aa274).

**Comment by justinclloyd** [comment]
The rewrite rule appears to work, with a couple of slight modifications:
```
location /graphite {
    rewrite ^/graphite(.*) /$1 break;
    try_files $uri @graphite;
}
```
Interestingly, it works with or without `graphite` between the `/?` delimiters.
Wish I knew what about the application stack led to the need for this.
Now I just need to figure out why the `{,-*}` pattern matching syntax is not returning any data.

**Comment by justinclloyd** [comment]
Further testing is leading me to think that the URL parsing does not like empty strings in braces with commas separating values, e.g. `foo{,1}.bar` to match `foo.bar` or `foo.1bar`. Again, the dropdown list shows matching values, but then when actually applying the string, no values are returned.

**Comment by justinclloyd** [comment]
And I just noticed the two commits from a few days ago to fix braces expansion.
