### ISSUE TITLE
I'm having the same issue, but in my case I don't want to use alignToFrom (cause I want to specify a relative time, like from=-10d, instead of having to specify absolute time), yet I'd like to have Summarize to allign the date correctly to 00:00 and honor the time zone. I currently get +3 hours shift (as my timezone UTC+3) and summarize is aligned to 03:00.

### ISSUE THREAD

**Issue by zzzzzzzzlllllllll** [graphite-project/graphite-web#2663]
I'm having the same issue, but in my case I don't want to use alignToFrom (cause I want to specify a relative time, like from=-10d, instead of having to specify absolute time), yet I'd like to have Summarize to allign the date correctly to 00:00 and honor the time zone. I currently get +3 hours shift (as my timezone UTC+3) and summarize is aligned to 03:00.

Any workaround ?

_Originally posted by @zerthimon in https://github.com/graphite-project/graphite-web/issues/1207#issuecomment-125234039_

**Comment by deniszh** [comment]
According to [documentation](https://graphite.readthedocs.io/en/stable/functions.html#graphite.render.functions.smartSummarize) "The alignToFrom boolean parameter has been replaced by alignTo and no longer has any effect. Alignment can be to years, months, weeks, days, hours, and minutes." 
So, `smartSummarize(seriesList, intervalString, func='sum', alignTo='day')` should work fine with timezones.

**Comment by zzzzzzzzlllllllll** [comment]
alignTo did solve part of my problem 。 

When my intervalstring is minute level, Max and min in the aggregate result are not accurate. Causes my Y-axis interval to be abnormal

**Comment by zzzzzzzzlllllllll** [comment]
> alignTo did solve part of my problem 。
> 
> When my intervalstring is minute level, Max and min in the aggregate result are not accurate. Causes my Y-axis interval to be abnormal

intervalString = 1m    alignTo = day
