### ISSUE TITLE
[BUG] Stored XSS n flot functionailty

### ISSUE THREAD

**Issue by Ccihad** [graphite-project/graphite-web#2664]
**Describe the bug**
I found Stored XSS vuln on flot (/graphlot) function

**To Reproduce**
Before login, click flot tab or directly go <url/graphlot> put XSS payload on metric tab and press enter
payload exampla "><script>alert(1);</script>

**Expected behavior**
Can run javascript codes.

![resim](https://user-images.githubusercontent.com/24861779/103990655-a46b9d80-51a2-11eb-96a2-5f14bc3ff564.png)

**Comment by piotr1212** [comment]
Graphlot is removed from Graphite 6 years ago, see https://github.com/graphite-project/graphite-web/pull/918
