### ISSUE TITLE
[BUG] Can't switch versions in Graphite Docs 1.1.3 or older

### ISSUE THREAD

**Issue by daniel-dara** [graphite-project/graphite-web#2665]
**Describe the bug**
When viewing the online Graphite Documentation, the version switcher appears to be broken when viewing the docs for v1.1.3 or older.

**To Reproduce**
1. Navigate to the online Graphite Documentation (https://graphite.readthedocs.io/en/stable/).
2. Switch to any version older than 1.1.4 (for example, 1.1.3) by clicking the version drop down in the lower left corner.
3. Attempt to switch versions again. Clicking the version dropdown in the lower left corner does nothing.

**Expected behavior**
It is expected that clicking the version drop down in 1.1.3 or older behaves the same 1.1.4 and newer. That is, a list of versions appears that lets you click a different version.

**Screenshots**
N/A

**Environment:**
 - OS flavor: OSX 10.15.7
 - Browser: Tested in Chrome Version 87.0.4280.141 (Official Build) (x86_64) and Safari Version 14.0.2 (15610.3.7.1.10, 15610)
 - Graphite-web version: N/A
 - Django/Python version: N/A
 - Setup type: N/A

**Additional context**
The following error shows in the browser console when loading the docs home page with v1.1.3 or lower selected. It does not appear on v1.1.4 or newer, where the version selector works.
```
(index):381 Uncaught ReferenceError: SphinxRtdTheme is not defined
    at HTMLDocument.<anonymous> ((index):381)
    at f (jquery-2.0.3.min.js:23)
    at Object.fireWith [as resolveWith] (jquery-2.0.3.min.js:23)
    at Function.ready (jquery-2.0.3.min.js:22)
    at HTMLDocument.dt (jquery-2.0.3.min.js:22)
```

**Comment by deniszh** [comment]
Hello @daniel-dara,

Thanks for reporting. It's surprisingly hard to fix, btw. In current setup documentation is located in the same repo, and bound to same tags as graphite releases. So, when release happens documentation builds and that's it - you can't update tag in git, hence can't update  documentation for specific version.
Not sure how to fix it. We can put documentation in separate repo, create tags there and rebuild - but it's one time fix, it will not fix main issue. Maybe @obfuscurity have ideas?
/cc @DanCech @piotr1212 @ploxiln @cbowman0 @gwaldo

**Comment by daniel-dara** [comment]
Thanks for the reply. It's unfortunate to hear it's not an easy fix, but I know that's how it goes sometimes. I want to mention I just filed a second documentation bug that also relates to older versions of the docs that are missing some content.
https://github.com/graphite-project/graphite-web/issues/2667

Since it sounds like modifying old documentation versions is difficult you may want to consider addressing both at the same time.
