### ISSUE TITLE
[Q]Anti selection function of glob, support ?

### ISSUE THREAD

**Issue by zzzzzzzzlllllllll** [graphite-project/graphite-web#2668]
Is there a document on what features glob supports

**Comment by zzzzzzzzlllllllll** [comment]
Now look at the documentation and try

I only know how to use ’{test1,test2}‘

**Comment by deniszh** [comment]
Hi @zzzzzzzzlllllllll 

Current documentation about glob format located in description of `target` parameter of render API - https://graphite.readthedocs.io/en/stable/render_api.html#paths-and-wildcards
