### ISSUE TITLE
[Q] why is did tagging stop ~9 months ago?

### ISSUE THREAD

**Issue by schen2315** [graphite-project/graphite-web#2672]
Hello, the last tag is from ~9 months ago and stopped at 1.1.7. How come the repo stopped getting tagged. We use a project graphite-mt https://github.com/raintank/graphite-mt that is currently pulling an out of date version of graphite because the tag is not up to date.

**Comment by deniszh** [comment]
Hi @schen2315 ,

Are you missing some particular feature or bugfix?
We have no stable release schedule. Usually we're tagging new release when we decide it worth it - i.e. contains enough number of new features and bugfixes. Also, release is not just a "tag" - we have separate branches for releases - 1.1.x is last stable branch and backporting changes there from master. You also can use master, it's stable enough for production usage, although its stability can vary.
Also, Graphite-mt also have no releases, they just pointing some commits on [their fork](https://github.com/grafana/graphite-web), currently 7ebde4c60. It's totally not related to tags in this repo. You can reach graphite-mt maintainers and ask them to update it.

**Comment by deniszh** [comment]
But you're probably right - maybe it's time to cut 1.1.8, though
