### ISSUE TITLE
How to install graphite on Debian 10[Q]

### ISSUE THREAD

**Issue by SATadsl** [graphite-project/graphite-web#2674]
Please I really need your help I've tried everything to install Graphite on my Debian testing machine and it didn't work is there any recent document to do that ?! please I need your help

**Comment by piotr1212** [comment]
> I've tried everything

> it didn't work

What did you try and what didn't work? There is not much to say without specific information. wrt docs, see: https://graphite.readthedocs.io/en/stable/install.html#installing-graphite not perfect but should get you going.

**Comment by SATadsl** [comment]
Hey piotr 

I saw your posts this morning I really hope that you can help me with that 

like this error 

`/opt/graphite/lib/python3.7/site-packages/pip/_internal/commands/install.py:230: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
ERROR: Location-changing options found in --install-option: ['--prefix', '--install-lib'] from command line. This is unsupported, use pip-level options like --user, --prefix, --root, and --target instead.


I'm trying for 7 hours and it didn't work I don't have this much knowledge in Linux but I really hope I can fix it 

`

**Comment by deniszh** [comment]
Hi @SATadsl ,

If you don't have much knowledge in Linux I would really recommend for use to use Docker for installing Graphite - https://graphite.readthedocs.io/en/latest/install.html#docker
Graphite is complex Django application, it's not very easy to install it for unexperienced Linux user.
If you really want to proceed - try to apply fix from that link - https://github.com/graphite-project/graphite-web/issues/2640#issuecomment-709941958

**Comment by deniszh** [comment]
PS: You can use e.g. this link - https://github.com/graphite-project/graphite-web/issues/2640#issuecomment-709941958 - but with fix above - instead `pip install --upgrade pip wheel setuptools gunicorn whisper` use `pip uninstall virtualenv;
pip install virtualenv==16.7.10; pip install --upgrade gunicorn whisper`

**Comment by SATadsl** [comment]
Maybe my problem is that I'm using Debian 10 

When I tried to use pip 

-bash: pip: command not found

**Comment by deniszh** [comment]
@SATadsl : A, sorry, I posted wrong link. You need to follow some guide, e.g. this - https://community.icinga.com/t/a-distro-agnostic-guide-to-graphite-with-venv-examples-rhel8-debian10-ubuntu18/1424 but instead 
```
pip install --upgrade pip wheel setuptools gunicorn whisper
``` 
use 
```
pip uninstall virtualenv; pip install virtualenv==16.7.10; pip install --upgrade gunicorn whisper
```

**Comment by piotr1212** [comment]
> -bash: pip: command not found

`apt install python3-pip`
