### ISSUE TITLE
I gave up I can't install graphite using Debian 10[Q]

### ISSUE THREAD

**Issue by SATadsl** [graphite-project/graphite-web#2675]
Please now it's 2 days trying to install Graphite using Debian 10 I followed everything and I don't want to use Docker I don't know what to do !! I really need help I mean I can install it and then post here the errors that I have then please if you can help me ? I mean if you have the latest Manual to follow do you have an advice ?

**Comment by deniszh** [comment]
Hi @SATadsl ,
We're not supporting distro specific manuals, because it's quite hard to keep it in actual state.
But if you following e.g. this manual - https://community.icinga.com/t/a-distro-agnostic-guide-to-graphite-with-venv-examples-rhel8-debian10-ubuntu18/1424 (may 2020, fresh enough) - what exactly not working and on which step?

**Comment by SATadsl** [comment]
Thanks a lot for answer me for example when I try to execute this command 
`(graphite) $ pip install --upgrade pip wheel setuptools gunicorn whisper

I receive this message 

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for whisper
  Running setup.py clean for whisper
Failed to build whisper

I really hope that you can help me with that and by the way I'm following now what you just sent me 

`

**Comment by deniszh** [comment]
Then instead of 
```
pip install --upgrade pip wheel setuptools gunicorn whisper
```
run
```
pip uninstall virtualenv; pip install virtualenv==16.7.10; pip install --upgrade gunicorn whisper
```

**Comment by SATadsl** [comment]
I've reached this point and thanks a lot for helping me 

cp: cannot create regular file '/opt/graphite/webapp/graphite.wsgi': Permission denied

**Comment by SATadsl** [comment]
another question when I reached this 

$ emacs storage-schemas.conf
Let’s add our regex patterns for Icinga time series. The format for retentions should be relatively obvious.

[icinga-hosts]
pattern = ^icinga2\..*\.host\.
retentions = 5m:4w

[icinga-services]
pattern = ^icinga2\..*\.services\.
retentions = 5m:12w,15m:26w,30m:1y

[carbon]
pattern = ^carbon\.
retentions = 60:90d

[default]
pattern = .*


** SO I have to put these lines at the end of this file storage-schemas.conf ?


also a question 

(graphite) $ cp /opt/graphite/conf/graphite.wsgi.example /opt/graphite/webapp/graphite.wsgi

How can I reach this destination to execute  cp /opt/graphite/conf/graphite.wsgi.example /opt/graphite/webapp/graphite.wsgi ???

**Comment by deniszh** [comment]
I'm sorry, @SATadsl , but these questions are not related to Graphite. You need some basic Linux knowledge - how users and permission works, how to Linux/web-server etc works. I will try answer them below, but I wold recommend to ask some linux users nearby or in some websites (Reddit/Stackoverflow etc.)

>cp: cannot create regular file '/opt/graphite/webapp/graphite.wsgi': Permission denied

In manual above directory `/opt/graphite/webapp` should belong to `carbon` user, so, this command should work if you run it from carbon user (after `su - carbon`)

> ** SO I have to put these lines at the end of this file storage-schemas.conf ?

It depends what you trying to achieve. Manual above is for Icinga installation, so, it contains icinga metrics. Why do you need install Graphite in the first pace and why can't you use docker?
You can start with default schema, but I'm 99% sure that will not work as you expected, unfortunately.  

> How can I reach this destination to execute cp /opt/graphite/conf/graphite.wsgi.example /opt/graphite/webapp/graphite.wsgi ???

As I said above, this command need to run from `carbon` user, or `root`.
