### ISSUE TITLE
Unclear config-webapp documentation [Q]

### ISSUE THREAD

**Issue by Burathar** [graphite-project/graphite-web#2676]
Hi there,

I was trying to install graphite in a testing environment, and got stuck because of what might be unfinished/unclear documentation.
Regarding: https://graphite.readthedocs.io/en/stable/config-webapp.html
In this docpage, it is explained that there are 3 ways of exposing the webapp. Then those 3 methods are explained step by step. I was following the `nginx + gunicorn` method, and was confused why this didn't work, until I found out nginx was pointing to an unused (local) port. After reading more carefully the realisation dawned on me that gunicorn wasn't actually configured/started. 
At least to me, the docs page suggests that those steps are all that has to be done. It appears that this isn't so. Could this be improved, or at least pointed out on the page? I don't feel knowledgable enough to make a contribution myself, so I hope someone else could clear this up.

Thx!

**Comment by deniszh** [comment]
Hi @Burathar,

Yes, probably it was too specific. Ok, I quickly adopted Graphite-API docs - https://github.com/graphite-project/graphite-web/pull/2677

**Comment by Burathar** [comment]
Great! Thank you.

No action from me is required at this point, right? I guess a maintainer has to pick up the merge request?
If not, please let me know.

**Comment by deniszh** [comment]
Yes, will merge and rebuild docs, thank you
