### ISSUE TITLE
[BUG] Apache2 wsgi daemon crashes with SIGABRT (signal 6), double free or corruption (out)

### ISSUE THREAD

**Issue by enidvrenozaj** [graphite-project/graphite-web#2678]
Hi, 
I am running graphite-web on Debian 10 latest packages:

**Environment:**
 - OS flavor: Debian GNU/Linux 10 
 - Graphite-web version: graphite-web   1.1.4-3+deb10u1
 - Django/Python version: python3-django 1:1.11.29-1~deb10u1; python: 3.7.3-1
 - Setup type: from OS packages (apt install)

I do get quite often some apache2 wsgi daemon crashing with errors shown on graphite_web-error.log like below:

```

[Mon Feb 08 14:21:14.792876 2021] [wsgi:error] [pid 948:tid 140703680280320] [remote 127.0.0.1:45360] /usr/lib/python3/dist-packages/pyparsing.py:2681: FutureWarning: Possible nested set at position 1
[Mon Feb 08 14:21:14.792949 2021] [wsgi:error] [pid 948:tid 140703680280320] [remote 127.0.0.1:45360]   self.re = re.compile( self.reString )
[Mon Feb 08 16:22:14.761164 2021] [wsgi:error] [pid 11539:tid 140703680280320] [remote 127.0.0.1:45774] /usr/lib/python3/dist-packages/pyparsing.py:2681: FutureWarning: Possible nested set at position 1
[Mon Feb 08 16:22:14.761220 2021] [wsgi:error] [pid 11539:tid 140703680280320] [remote 127.0.0.1:45774]   self.re = re.compile( self.reString )
.....
...
[Mon Feb 08 23:07:14.495348 2021] [wsgi:info] [pid 16262:tid 140689088513792] [remote 127.0.0.1:47540] mod_wsgi (pid=16262, process='_graphite', application='myserver.localhost.localdomain|')
: Loading Python script file '/usr/share/graphite-web/graphite.wsgi'.
[Mon Feb 08 23:07:14.965401 2021] [wsgi:info] [pid 16074:tid 140689105299200] mod_wsgi (pid=16074): Daemon process idle inactivity timer expired, stopping process '_graphite'.
[Mon Feb 08 23:07:14.965685 2021] [wsgi:info] [pid 16074:tid 140689154397312] mod_wsgi (pid=16074): Shutdown requested '_graphite'.
[Mon Feb 08 23:07:14.966097 2021] [wsgi:info] [pid 16074:tid 140689154397312] mod_wsgi (pid=16074): Stopping process '_graphite'.
[Mon Feb 08 23:07:14.966124 2021] [wsgi:info] [pid 16074:tid 140689154397312] mod_wsgi (pid=16074): Destroying interpreters.
[Mon Feb 08 23:07:14.966143 2021] [wsgi:info] [pid 16074:tid 140689154397312] mod_wsgi (pid=16074): Destroy interpreter 'myserver.localhost.localdomain|'.
[Mon Feb 08 23:07:14.966329 2021] [wsgi:info] [pid 16074:tid 140689154397312] mod_wsgi (pid=16074): End interpreter 'myserver.localhost.localdomain|'.
double free or corruption (out)

```

This part of error is shown directly when the daemon process crashes:
```
double free or corruption (out)
```

Can you help solving this issue?

Thank you,
Enid

**Comment by deniszh** [comment]
Hi @enidvrenozaj 

Could you please put full error log somewhere? That part which you posted here not showing exact error. Thanks!

**Comment by enidvrenozaj** [comment]
Hi @deniszh 

Can you please tell me what log do you need? 
The only log I am seeing this error is from
/var/log/apache2/graphite-web_error.log 
and no entries other than the ones I sent do show anything related.
I can send the whole log if you want.

Also I see from audit.log the exact apace2 process that crashes with messages like:
```
type=ANOM_ABEND msg=audit(1612822035.036:472808): auid=4294967295 uid=109 gid=117 ses=4294967295 subj==unconfined pid=16074 comm="apache2" exe="/usr/sbin/apache2" sig=6 res=1
```

Thanks,
Enid

**Comment by deniszh** [comment]
@enidvrenozaj : I see 2 lines from Feb 08 16 o'clock and 5 lines from Feb 08 23 o'clock. For me its definitely not enough to understang what could be issue. Warnings from FutureWarning is not an error.

**Comment by enidvrenozaj** [comment]
Please find attached the whole graphite-web_error.log from yesterday where twice the crash happened on: 10:37 and 23:07
Thanks, 
[graphite-web_error.log.zip](https://github.com/graphite-project/graphite-web/files/5951753/graphite-web_error.log.zip)

**Comment by piotr1212** [comment]
Sometimes these kind of strange crashes happen when mod_wsgi and apache httpd versions don't match (ie when mod_wsgi is compiled against another httpd version). Check if you have latest httpd and mod_wsgi from debian repo's.

**Comment by enidvrenozaj** [comment]
@piotr1212 I do have the latest packages from Debian buster repositories
Apache: apache2 version 2.4.38-3+deb10u4
Wsgi: libapache2-mod-wsgi-py3 version 4.6.5-1

**Comment by enidvrenozaj** [comment]
Today the same crash happened again and although on LogLevel debug not much info is shown:

`[Thu Feb 11 14:44:14.485761 2021] [authz_core:debug] [pid 6832:tid 139802619913984] mod_authz_core.c(820): [client 127.0.0.1:34634] AH01626: authorization result of <RequireAny>: granted
[Thu Feb 11 14:44:14.485893 2021] [authz_core:debug] [pid 6832:tid 139802619913984] mod_authz_core.c(820): [client 127.0.0.1:34634] AH01626: authorization result of Require all granted: gran
ted
[Thu Feb 11 14:44:14.485903 2021] [authz_core:debug] [pid 6832:tid 139802619913984] mod_authz_core.c(820): [client 127.0.0.1:34634] AH01626: authorization result of <RequireAny>: granted
[Thu Feb 11 14:44:38.467495 2021] [wsgi:info] [pid 16738:tid 139802979899136] mod_wsgi (pid=16738): Daemon process idle inactivity timer expired, stopping process '_graphite'.
[Thu Feb 11 14:44:38.467798 2021] [wsgi:info] [pid 16738:tid 139803028997248] mod_wsgi (pid=16738): Shutdown requested '_graphite'.
[Thu Feb 11 14:44:38.468205 2021] [wsgi:info] [pid 16738:tid 139803028997248] mod_wsgi (pid=16738): Stopping process '_graphite'.
[Thu Feb 11 14:44:38.468227 2021] [wsgi:info] [pid 16738:tid 139803028997248] mod_wsgi (pid=16738): Destroying interpreters.
**[Thu Feb 11 14:44:38.468252 2021] [wsgi:debug] [pid 16738:tid 139802929542912] src/server/mod_wsgi.c(9052): mod_wsgi (pid=16738): Exiting thread 4 in daemon process '_graphite'.**
[Thu Feb 11 14:44:38.468265 2021] [wsgi:info] [pid 16738:tid 139803028997248] mod_wsgi (pid=16738): Destroy interpreter 'myserver.localhost.localdomain|'.
[Thu Feb 11 14:44:38.468272 2021] [wsgi:debug] [pid 16738:tid 139802963113728] src/server/mod_wsgi.c(9052): mod_wsgi (pid=16738): Exiting thread 0 in daemon process '_graphite'.
[Thu Feb 11 14:44:38.468268 2021] [wsgi:debug] [pid 16738:tid 139802937935616] src/server/mod_wsgi.c(9052): mod_wsgi (pid=16738): Exiting thread 3 in daemon process '_graphite'.
[Thu Feb 11 14:44:38.468361 2021] [wsgi:debug] [pid 16738:tid 139802946328320] src/server/mod_wsgi.c(9052): mod_wsgi (pid=16738): Exiting thread 2 in daemon process '_graphite'.
[Thu Feb 11 14:44:38.468609 2021] [wsgi:info] [pid 16738:tid 139803028997248] mod_wsgi (pid=16738): End interpreter 'myserver.localhost.localdomain|'.
**double free or corruption (out)**
[Thu Feb 11 14:44:39.181482 2021] [wsgi:info] [pid 17359:tid 139803028997248] mod_wsgi (pid=17359): Attach interpreter ''.
[Thu Feb 11 14:44:39.187673 2021] [wsgi:info] [pid 17359:tid 139803028997248] mod_wsgi (pid=17359, process='_graphite', application=''): Loading Python script file '/usr/share/graphite-web/graphite.wsgi'.
[Thu Feb 11 14:44:39.425259 2021] [wsgi:debug] [pid 17359:tid 139802963113728] src/server/mod_wsgi.c(9071): mod_wsgi (pid=17359): Started thread 0 in daemon process '_graphite'.
[Thu Feb 11 14:44:39.425271 2021] [wsgi:debug] [pid 17359:tid 139802954721024] src/server/mod_wsgi.c(9071): mod_wsgi (pid=17359): Started thread 1 in daemon process '_graphite'.
[Thu Feb 11 14:44:39.425275 2021] [wsgi:debug] [pid 17359:tid 139802946328320] src/server/mod_wsgi.c(9071): mod_wsgi (pid=17359): Started thread 2 in daemon process '_graphite'.
[Thu Feb 11 14:44:39.425291 2021] [wsgi:debug] [pid 17359:tid 139802937935616] src/server/mod_wsgi.c(9071): mod_wsgi (pid=17359): Started thread 3 in daemon process '_graphite'.
[Thu Feb 11 14:44:39.425313 2021] [wsgi:debug] [pid 17359:tid 139802929542912] src/server/mod_wsgi.c(9071): mod_wsgi (pid=17359): Started thread 4 in daemon process '_graphite'.
[Thu Feb 11 14:45:14.478233 2021] [authz_core:debug] [pid 6832:tid 139802645092096] mod_authz_core.c(820): [client 127.0.0.1:34636] AH01626: authorization result of Require all granted: granted
[Thu Feb 11 14:45:14.478298 2021] [authz_core:debug] [pid 6832:tid 139802645092096] mod_authz_core.c(820): [client 127.0.0.1:34636] AH01626: authorization result of <RequireAny>: granted
[Thu Feb 11 14:45:14.478429 2021] [authz_core:debug] [pid 6832:tid 139802645092096] mod_authz_core.c(820): [client 127.0.0.1:34636] AH01626: authorization result of Require all granted: granted
[Thu Feb 11 14:45:14.478464 2021] [authz_core:debug] [pid 6832:tid 139802645092096] mod_authz_core.c(820): [client 127.0.0.1:34636] AH01626: authorization result of <RequireAny>: granted
[Thu Feb 11 14:45:14.492377 2021] [wsgi:info] [pid 16988:tid 139802963113728] mod_wsgi (pid=16988): Create interpreter 'myserver.localhost.localdomain|'.
[Thu Feb 11 14:45:14.503700 2021] [wsgi:info] [pid 16988:tid 139802963113728] [remote 127.0.0.1:34636] mod_wsgi (pid=16988, process='_graphite', application='myserver.localhost.localdomain|'): Loading Python script file '/usr/share/graphite-web/graphite.wsgi'.`

**Comment by piotr1212** [comment]
I'm afraid the problem is in mod_wsgi, maybe try to report it there or try running in an alternative like Gunicorn or uWSGI.

**Comment by enidvrenozaj** [comment]
@piotr1212 I reported the issue also on mod_wsgi project.
Regarding running my environment on uWSGI of Gunicorn I couldn't find a specific documentation to run graphite-web on apache2 with those modules. I could find only nginx related configurations. I would prefer to run graphite-web on the default OS specific configurations.
Not sure how can I modify `/usr/share/graphite-web/graphite.wsgi` and other scripts to run in a different environment.

**Comment by piotr1212** [comment]
gunicorn and uwsgi work a bit different than mod_wsgi, the former are not modules but standalone services. 

If you want to run it with apache you basically configure apache as a generic reverse proxy with gunicorn/uwsgi as endpoint.

**Comment by enidvrenozaj** [comment]
Hi,
I applied this change here:

`WSGIApplicationGroup %{GLOBAL} to /etc/apache2/sites-enabled/graphite.conf`

which is mentioned in different threads:
```
https://stackoverflow.com/questions/49243892/double-free-or-corruption-prev-httpd
https://stackoverflow.com/questions/4236045/django-apache-mod-wsgi-hangs-on-importing-a-python-module-from-so-file
https://github.com/GrahamDumpleton/mod_wsgi/issues/81
https://github.com/getsentry/sentry-python/issues/789
```
and it has been live for almost a week and no crashes have happened until now. Normally the crash would appear everyday or at least every 2 days.
I will keep it monitoring for some days more and hope that it "solves" the issue.

Thanks

**Comment by enidvrenozaj** [comment]
Hi all, 
This is the feedback I got from mod_wsgi developers, maybe it is of interest also to graphite-web apache2 conf file.

>  I missed that you didn't have application-group option on WSGIScriptAlias and was only on WSGIImportScript. I didn't mention application group as thought you were doing it right. Turns out it wasn't, plus you were double loading your application causing excess memory usage.

What you should be using is:
```
        WSGIDaemonProcess _graphite processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120 user=_graphite group=_graphite

        WSGIScriptAlias / /usr/share/graphite-web/graphite.wsgi process-group=_graphite application-group=%{GLOBAL}
```
You don't need WSGIImportScript so long as specify both process-group and application-group on WSGIScriptAlias as doing that has same effect as WSGIImportScript in that will preload application.

So long as have both options on WSGIScriptAlias, you also don't need WSGIProcessGroup and WSGIApplicationGroup.

Opinions?

**Comment by deniszh** [comment]
Hi @enidvrenozaj ,

Example of Apache config in documentation is already contains that lines - https://graphite.readthedocs.io/en/latest/config-webapp.html#apache-mod-wsgi
But please note that Apache is complex software, which can be used in many ways and it's only one of the ways how you can run Graphite, that's why it's only _example_ of config and users' configuration can be different.

**Comment by enidvrenozaj** [comment]
Hi @deniszh 
Yes I am aware of the apache config which includes that line but as mentioned on the feedback from mod_wsgi developers those lines override each other and so may make the `WSGIApplicationGroup` directive not leading to possible crashes like the one I am experiencing. Also another point `WSGIImportScript` was unnecessary as it introduced also excess memory usage.
I know that apache config is just an example which can be used and modified according to needs but it would be nice to take into consideration this feedback if it makes sense to modify/improve the apache config file.

**Comment by enidvrenozaj** [comment]
The change on `/etc/apache2/sites-enabled/graphite.conf ` has been in place for more than 10 days now and I am not facing the crash any more.
You can find below the modified conf I am using at the moment:

```
<VirtualHost *:80>
        WSGIDaemonProcess _graphite processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120 user=_graphite group=_graphite
        WSGIScriptAlias / /usr/share/graphite-web/graphite.wsgi process-group=_graphite application-group=%{GLOBAL}
        Alias /content/ /usr/share/graphite-web/static/
        <Location "/content/">
                SetHandler None
        </Location>
        ErrorLog ${APACHE_LOG_DIR}/graphite-web_error.log
        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/graphite-web_access.log combined
</VirtualHost>
```

**Comment by enidvrenozaj** [comment]
Closing the issue since after the change I am not experiencing the crash any more.
