### ISSUE TITLE
How to upgrade Graphite from 1.1.4 to 1.1.7 ?[Q]

### ISSUE THREAD

**Issue by Jason-MK** [graphite-project/graphite-web#2685]
I was wondering how to upgrader Graphite from 1.1.4 to 1.1.7 because normally Graphite 1.1.4 and 1.1.7 are installed in different directories !! 

Thanks

**Comment by deniszh** [comment]
Hi @Jason-MK ,

It's not trivial to install Graphite in separate directory, I would not do that. Just install  whisper, carbon and graphite-web packages for 1.1.7 and restart carbon and graphite-web.

**Comment by Jason-MK** [comment]
Thanks deniszh but I have an issue I did install 1.1.4 which is 

Invalid theme 'default' when I click on dashboard 


Best Regards
