### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by n1bor** [graphite-project/graphite-web#2686]
**Describe the bug**
Running your docker image (graphiteapp/graphite-statsd 1d7b81067e37)
Just stopped collecting stats....

/var/log/carbon.log had this error - over and over and over...

carbon-cache (instance a) is already running with pid 51

Restarting did not fix it.

PID 51 was actually the crontabd process.

**Fix**

I just removed:
/opt/graphite/storage/carbon-cache-a.pid

Adding this as wasted a few hours before finding issue.
Think on restart these pid files should be removed to avoid in future.
Although no idea how it got in this state.
Was running fine for over 2 years with occasional restarts!

**Comment by deniszh** [comment]
Hi @n1bor ,

This is https://github.com/graphite-project/docker-graphite-statsd/issues/96, fixed in v1.1.5-11 released May 13, 2019
Please upgrade your docker image.

**Comment by n1bor** [comment]
Arh - thanks - had searched for the error string - but missed your fix.
