### ISSUE TITLE
[BUG] Long whisper files fail to render more than 7d of history

### ISSUE THREAD

**Issue by lachesis** [graphite-project/graphite-web#2688]
**Describe the bug**
I have some carbon/whisper files with many years of history. When I try to render more than 7 days worth of data from these metrics, I get back a graph with only one or two points towards the very end. Using whisper-dump.py, I am able to see all of my historical data is intact. My storage schemas are:
```
[default]
pattern = .*
retentions = 10s:7d,10m:60d,1h:5y,4h:10y
```

**To Reproduce**
1. Unzip the attached WSP file and provide it to Graphite in storage/stats/gauges/ups/load.wsp.
[load.wsp.zip](https://github.com/graphite-project/graphite-web/files/6223563/load.wsp.zip)
2. Hit the render API for 7 days. Note all points are intact.  http://localhost:3081/render?target=stats.gauges.ups.load&from=-7d&until=now&format=json
3. Hit the render API for 30 days. Note only one point is returned.  http://localhost:3081/render?target=stats.gauges.ups.load&from=-30d&until=now&format=json

**Expected behavior**
I'd expect to see data from all 30 days.

**Screenshots**
Screenshots of graph in Grafana, but I've minimized this problem to be occurring in graphite-web.
![2021-03-29-135526_2125x548_scrot](https://user-images.githubusercontent.com/347481/112878880-6f326580-9096-11eb-9490-40555413e7a6.png)
![2021-03-29-135516_2135x553_scrot](https://user-images.githubusercontent.com/347481/112878883-6f326580-9096-11eb-8b4d-98511dc7bb79.png)

**Environment (please complete the following information):**
 - OS flavor: alpine
 - Graphite-web version: 1.2.0-dev, latest master from today
 - Django/Python version: 2.7.15
 - Setup type: from sources, using kamon/docker-grafana-graphite built today

**Additional context**
This doesn't happen exactly the same way for every metric. Some other metrics include early data but no newer data.

**Comment by deniszh** [comment]
I can reproduce but I'm suspecting something is wrong with file itself. it contains 3 archives instead of 4 (10s:7d,10m:60d,1h:5y), whisper-dump shows data, and data looks valid. But whisper-fetch shows exactly same result as Graphite for second archive for some reason...
