### ISSUE TITLE
[Q] How to use linearRegression in grafana for forecasting

### ISSUE THREAD

**Issue by rschitz** [graphite-project/graphite-web#2690]
It looks like we can't use future date as "until" https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.linearRegression

Any suggestions?

**Comment by deniszh** [comment]
Could you please elaborate why not, @rschitz ? Future time is really not supported in whisper as storage format, but, theoretically functions can generate future datapoints.

**Comment by rschitz** [comment]
i tried several combinations for from/until but still the same result, i got points for the past but not the future:

![image](https://user-images.githubusercontent.com/8385646/113573621-c8f8d980-961a-11eb-8262-1e9825a25757.png)

**Comment by rldleblanc** [comment]
I too am running into this. I get a nice trend line, but can't extend it into the future past the whisper data. Maybe the function could be extended to take the trend line generated with startSourceAt and endSourceAt and provide startForecastAt and endForecastAt where it would generate the forecast data on the fly.

**Comment by deniszh** [comment]
TBH I puzzled with forecast finctions too. In general, Graphite do not support future datapoints, so, their usecase can be only quite limited, though...
