### ISSUE TITLE
[Q]LDAP setup for python3

### ISSUE THREAD

**Issue by mmueller101** [graphite-project/graphite-web#2702]
I have recently updated graphite-web to 1.1.8 from 0.9.x. Since LDAP has stopped working properly. I have python-ldap and openldap installed and local_settings.py is set up for it.  I am using python3. When I try and log in via graphite UI, it says user name and password aren't correct. LDAP was working before the upgrade of graphite-web. Is there something I'm missing? 

I have found that editing the ldapBackend.py file from 
- def authenticate(self, username=None, password=None):
to
+ def authenticate(self, **request**, username=None, password=None):
has fixed the issue. Am I missing something or is this file out of date?

**Comment by deniszh** [comment]
Hi @mmueller101 ,

I think it's related not to python3 / python-ldap or openldap but to Django itself.
2.x do not requre request - https://docs.djangoproject.com/en/2.2/ref/contrib/auth/#django.contrib.auth.backends.ModelBackend.authenticate
But 3.x is - https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#django.contrib.auth.backends.ModelBackend.authenticate

Need some work to support both.

**Comment by mmueller101** [comment]
Hey @deniszh ,

**Comment by mmueller101** [comment]
Hey @deniszh,

Thanks for taking a look at this.
