### ISSUE TITLE
[Q] Connect to a redis cluster

### ISSUE THREAD

**Issue by clalos2592** [graphite-project/graphite-web#2708]
Hello, 
Would it be possible to have multiple entries on **TAGDB_REDIS_HOST** (i.e.connect to a redis cluster)?
Thanks

**Comment by deniszh** [comment]
Hi @clalos2592 

according to https://github.com/graphite-project/graphite-web/blob/19f2155a8902f1dc075d4276d384409f1c006764/webapp/graphite/tags/redis.py#L31-L37 only host is accepted. I.e. some load-balancer will need in case of cluster.

**Comment by clalos2592** [comment]
Thanks @deniszh !
