### ISSUE TITLE
ImportError: No module named django.conf

### ISSUE THREAD

**Issue by obabs** [graphite-project/graphite-web#2709]
I am running Centos 7 and  trying to run graphite and grafana on python 2.7.5. I installed everything without issues until I tried running graphite-webpp .  I get the error message above .
Mon Jul 12 16:55:22.262417 2021] [:error] [pid 2450] mod_wsgi (pid=2450): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Mon Jul 12 16:55:22.262546 2021] [:error] [pid 2450] Traceback (most recent call last):
[Mon Jul 12 16:55:22.262590 2021] [:error] [pid 2450]   File "/opt/graphite/conf/graphite.wsgi", line 7, in <module>
[Mon Jul 12 16:55:22.262712 2021] [:error] [pid 2450]     from graphite.wsgi import application
[Mon Jul 12 16:55:22.262733 2021] [:error] [pid 2450]   File "/opt/graphite/webapp/graphite/wsgi.py", line 12, in <module>
[Mon Jul 12 16:55:22.262821 2021] [:error] [pid 2450]     from django.conf import settings
[Mon Jul 12 16:55:22.262919 2021] [:error] [pid 2450] ImportError: No module named django.conf
[Mon Jul 12 16:55:22.264109 2021] [:error] [pid 2453] mod_wsgi (pid=2453): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Mon Jul 12 16:55:22.264141 2021] [:error] [pid 2453] mod_wsgi (pid=2453): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Mon Jul 12 16:55:22.264163 2021] [:error] [pid 2453] Traceback (most recent call last):
[Mon Jul 12 16:55:22.264178 2021] [:error] [pid 2453]   File "/opt/graphite/conf/graphite.wsgi", line 7, in <module>
[Mon Jul 12 16:55:22.264237 2021] [:error] [pid 2453]     from graphite.wsgi import application
[Mon Jul 12 16:55:22.264248 2021] [:error] [pid 2453]   File "/opt/graphite/webapp/graphite/wsgi.py", line 12, in <module>
[Mon Jul 12 16:55:22.264291 2021] [:error] [pid 2453]     from django.conf import settings
[Mon Jul 12 16:55:22.264311 2021] [:error] [pid 2453] ImportError: No module named django.conf

Also this is my pip list 
(graphite) [olufemibabalola@graph7 conf]$ sudo -E PYTHONPATH=/opt/graphite/webapp /opt/graphite/bin/django-admin.py check --settings=graphite.settings
System check identified no issues (0 silenced).
(graphite) [olufemibabalola@graph7 conf]$ sudo -E pip list 
sudo: pip: command not found
(graphite) [olufemibabalola@graph7 conf]$  pip list 
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
attrs (21.2.0)
Automat (20.2.0)
cachetools (3.1.1)
cairocffi (0.8.0)
carbon (1.1.8)
cffi (1.14.6)
constantly (15.1.0)
Django (1.11.29)
django-tagging (0.4.6)
funcsigs (1.0.2)
gunicorn (19.10.0)
hyperlink (21.0.0)
idna (2.10)
incremental (21.3.0)
mock (3.0.5)
pip (9.0.1)
pycparser (2.20)
PyHamcrest (1.10.1)
pyparsing (2.4.7)
python-memcached (1.58)
pytz (2021.1)
scandir (1.10.0)
setuptools (28.8.0)
six (1.16.0)
Twisted (20.3.0)
txAMQP (0.8.0)
typing (3.10.0.0)
urllib3 (1.26.6)
wheel (0.29.0)
whisper (1.1.8)
whitenoise (4.1.4)
zope.interface (5.4.0)
You are using pip version 9.0.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by ploxiln** [comment]
Your version of Django is way too old. I suggest trying Django-2.2.x

(what version of graphite-web are you using, and how did you install it?)
