### ISSUE TITLE
Graphite db support for string data

### ISSUE THREAD

**Issue by mukeshhope** [graphite-project/graphite-web#2712]
Hi Team,

In my application, I am sending alot of data to Graphite database those values are numbers and that is working fine.
Now I want to send some values which are string and not number.
the question is : Does Graphite supports string data? As for as I understand from the documentation it looks like we can push only numerical data there.

**Comment by deniszh** [comment]
Hi @mukeshhope 

No, Graphite supports only numerical data.

**Comment by mukeshhope** [comment]
Hi Deniszh,

Thankyou so much for quick reply
