### ISSUE TITLE
INTERNALSERVER ERROR 500

### ISSUE THREAD

**Issue by Prasadevops0710** [graphite-project/graphite-web#2736]
<img width="700" alt="Screenshot 2022-02-28 at 12 15 32 PM" src="https://user-images.githubusercontent.com/97157679/155936825-75d09471-124c-4ccc-9a88-2ba3bf39cc7d.png">

**Comment by Prasadevops0710** [comment]
please help here @DanCech

**Comment by deniszh** [comment]
Hi @Prasadevops0710 

You need uncomment `FETCH_TIMEOUT` (and probably `FIND_TIMEOUT` also) in local_settings.py file and put some sane value there. Default is `6.0`, means 6 seconds, you can e.g. double it, so, put 12 seconds there.

**Comment by Prasadevops0710** [comment]
I've made changes in setting.py file now its working fine but in grafana the dashboard loading slowly it taking 10 sec to load dash board

<img width="756" alt="Screenshot 2022-03-07 at 12 17 06 PM" src="https://user-images.githubusercontent.com/97157679/156981762-a2d6243d-e68f-4e96-aefe-41cd0e60654a.png">

**Comment by Prasadevops0710** [comment]
please let me know can i change in localsetting.py also

**Comment by Prasadevops0710** [comment]
when am checking logs 2022-03-06,12:25:30.221 :: Failed CarbonLink query 'rtb-test.st.aggregated.accounts.54db32e4_4d94_41b5_8152_848cf8b1ab6b.9fb7e69e_f681_4071_b89c_8c11465c78a5.submitted'
Traceback (most recent call last):
  File "/data/graphite/webapp/graphite/readers/utils.py", line 110, in merge_with_carbonlink
    cached_datapoints = CarbonLink().query(metric)
  File "/data/graphite/webapp/graphite/carbonlink.py", line 97, in query
    results = self.send_request(request)
  File "/data/graphite/webapp/graphite/carbonlink.py", line 130, in send_request
    conn = self.get_connection(host)
  File "/data/graphite/webapp/graphite/carbonlink.py", line 87, in get_connection
    connection = socket.create_connection((server, port), self.timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

@deniszh

**Comment by deniszh** [comment]
@Prasadevops0710 

> please let me know can i change in localsetting.py also

If you changed settings.py that doesn't matter

> error: [Errno 111] Connection refused

what's in your `CARBONLINK_HOSTS` parameter? Do you use `carbon` or `go-carbon` ? Is in installed on same server?

**Comment by Prasadevops0710** [comment]
I’m using gocarbon

**Comment by Prasadevops0710** [comment]
Installed in same server

**Comment by Prasadevops0710** [comment]
<img width="663" alt="Screenshot 2022-03-08 at 11 17 03 PM" src="https://user-images.githubusercontent.com/97157679/157295653-248fd614-92ad-4efd-8477-84f0ae0adb74.png">

**Comment by Prasadevops0710** [comment]
some times some of panels showing no data but when I'm refreshing dashboard the panels are showing metrics <img width="1440" alt="Screenshot 2022-03-09 at 10 34 50 AM" src="https://user-images.githubusercontent.com/97157679/157376468-bf94a989-784e-453c-ba15-75955c5d659d.png">

**Comment by deniszh** [comment]
@Prasadevops0710 

Uncomment CARBONLINK_HOSTS in local_settings.py and make sure that 
carbonlink section is present in go-carbon.conf:
```
[carbonlink]
listen = "127.0.0.1:7002"
enabled = true
# Close inactive connections after "read-timeout"
read-timeout = "30s"
```

Also you can try to switch to carbonserver proto. Enable it in go-carbon.conf:
```
[carbonserver]
listen = "127.0.0.1:8080"
enabled = true
....
```
and then add
```
CLUSTER_SERVERS=["127.0.0.1:8080"]
```
to local_settings.py and restart both go-carbon and graphite-web.

**Comment by Prasadevops0710** [comment]
● go-carbon.service - Go-carbon
   Loaded: loaded (/etc/systemd/system/go-carbon.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2022-03-09 17:27:08 UTC; 4s ago
  Process: 20402 ExecStart=/bin/sh -c go-carbon -config /data/graphite/conf/go-carbon.conf (code=exited, status=1/FAILURE)
 Main PID: 20402 (code=exited, status=1/FAILURE)

Mar 09 17:27:08 ip-10-5-102-84 systemd[1]: go-carbon.service: Unit entered failed state.
Mar 09 17:27:08 ip-10-5-102-84 systemd[1]: go-carbon.service: Failed with result 'exit-code'.

**Comment by Prasadevops0710** [comment]
I've enabled carbon server and restarted go-carbon but its always in loaded state as above

**Comment by Prasadevops0710** [comment]
CorruptWhisperFile: Unable to read header (/data/graphite/storage/whisper/rtb-test/st/aggregated/accounts/54db32e4_4d94_41b5_8152_848cf8b1ab6b/9fb7e69e_f681_4071_b89c_8c11465c78a5/bidUnderDealFloor.wsp)
 18442	
 18443	2022-03-20,18:06:37.500 :: Exception encountered in <GET http://graphite-us.knorex-internal.com/render/?format=pickle&local=1&noCache=1&from=1647796304&until=1647799904&target=rtb-test.st.aggregated.accounts.54db32e4_4d94_41b5_8152_848cf8b1ab6b.9fb7e69e_f681_4071_b89c_8c11465c78a5.%2A&now=1647799904>
 18444	Traceback (most recent call last):
 18445	  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
 18446	    response = wrapped_callback(request, *callback_args, **callback_kwargs)
 18447	  File "/data/graphite/webapp/graphite/render/views.py", line 118, in renderView
 18448	    data.extend(evaluateTarget(requestContext, targets))
 18449	  File "/data/graphite/webapp/graphite/render/evaluator.py", line 15, in evaluateTarget
 18450	    prefetchData(requestContext, pathExpressions)
 18451	  File "/data/graphite/webapp/graphite/render/datalib.py", line 263, in prefetchData
 18452	    for result in STORE.fetch(pathExpressions, startTime, endTime, now, requestContext):
 18453	  File "/data/graphite/webapp/graphite/storage.py", line 190, in fetch
 18454	    'fetch for %s' % str(patterns))
 18455	  File "/data/graphite/webapp/graphite/storage.py", line 132, in wait_jobs
 18456	    raise Exception(message)
 18457	Exception: All requests failed for fetch for [u'rtb-test.st.aggregated.accounts.54db32e4_4d94_41b5_8152_848cf8b1ab6b.9fb7e69e_f681_4071_b89c_8c11465c78a5.*'] (1)
 18458	
 18459	fetch for [u'rtb-test.st.aggregated.accounts.54db32e4_4d94_41b5_8152_848cf8b1ab6b.9fb7e69e_f681_4071_b89c_8c11465c78a5.*']: Unable to read header (/data/graphite/storage/whisper/rtb-test/st/aggregated/accounts/54db32e4_4d94_41b5_8152_848cf8b1ab6b/9fb7e69e_f681_4071_b89c_8c11465c78a5/bidUnderDealFloor.wsp): Traceback (most recent call last):
 18460	
 18461	  File "/data/graphite/webapp/graphite/worker_pool/pool.py", line 43, in run
 18462	    self.result = self.func(*self.args, **self.kwargs)
 18463	
 18464	  File "/data/graphite/webapp/graphite/finders/utils.py", line 140, in fetch
 18465	    now=now, requestContext=requestContext
 18466	
 18467	  File "/data/graphite/webapp/graphite/node.py", line 30, in fetch
 18468	    result = self.reader.fetch(startTime, endTime, now, requestContext)
 18469	
 18470	  File "/data/graphite/webapp/graphite/readers/whisper.py", line 59, in fetch
 18471	    data = self.fetch_data(startTime, endTime, now=now)
 18472	
 18473	  File "/data/graphite/webapp/graphite/readers/whisper.py", line 55, in fetch_data
 18474	    return whisper.fetch(self.fs_path, startTime, endTime, now=now)
 18475	
 18476	  File "/usr/local/lib/python2.7/dist-packages/whisper-1.2.0-py2.7.egg/whisper.py", line 906, in fetch
 18477	    return file_fetch(fh, fromTime, untilTime, now, archiveToSelect)
 18478	
 18479	  File "/usr/local/lib/python2.7/dist-packages/whisper-1.2.0-py2.7.egg/whisper.py", line 910, in file_fetch
 18480	    header = __readHeader(fh)
 18481	
 18482	  File "/usr/local/lib/python2.7/dist-packages/whisper-1.2.0-py2.7.egg/whisper.py", line 290, in __readHeader
 18483	    raise CorruptWhisperFile("Unable to read header", fh.name)
 18484	
@deniszh can you help here

**Comment by deniszh** [comment]
@Prasadevops0710 : File `/data/graphite/storage/whisper/rtb-test/st/aggregated/accounts/54db32e4_4d94_41b5_8152_848cf8b1ab6b/9fb7e69e_f681_4071_b89c_8c11465c78a5/bidUnderDealFloor.wsp` is corrupted and can't be read. Please delete it.

**Comment by Prasadevops0710** [comment]
@deniszh  but it seems that there are so many corrupted file around 1000 can I delete all or is there any way to prevent that in future. thank you
