### ISSUE TITLE
WARNING: whisper module could not be loaded, whisper support disabled

### ISSUE THREAD

**Issue by Prasadevops0710** [graphite-project/graphite-web#2741]
@DanCech ● graphite-web.service - Graphite-web
     Loaded: loaded (/etc/systemd/system/graphite-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-03-31 19:14:51 UTC; 2s ago
   Main PID: 38857 (sh)
      Tasks: 6 (limit: 4624)
     Memory: 48.0M
     CGroup: /system.slice/graphite-web.service
             ├─38857 /bin/sh -c /usr/bin/gunicorn wsgi --workers=4 --bind=127.0.0.1:8080 --log-file=/var/log/gunicorn.log --preload --pythonpath=/data/graphite/webapp/graphite
             ├─38858 /usr/bin/python3 /usr/bin/gunicorn wsgi --workers=4 --bind=127.0.0.1:8080 --log-file=/var/log/gunicorn.log --preload --pythonpath=/data/graphite/webapp/graphite
             ├─38861 /usr/bin/python3 /usr/bin/gunicorn wsgi --workers=4 --bind=127.0.0.1:8080 --log-file=/var/log/gunicorn.log --preload --pythonpath=/data/graphite/webapp/graphite
             ├─38862 /usr/bin/python3 /usr/bin/gunicorn wsgi --workers=4 --bind=127.0.0.1:8080 --log-file=/var/log/gunicorn.log --preload --pythonpath=/data/graphite/webapp/graphite
             ├─38863 /usr/bin/python3 /usr/bin/gunicorn wsgi --workers=4 --bind=127.0.0.1:8080 --log-file=/var/log/gunicorn.log --preload --pythonpath=/data/graphite/webapp/graphite
             └─38864 /usr/bin/python3 /usr/bin/gunicorn wsgi --workers=4 --bind=127.0.0.1:8080 --log-file=/var/log/gunicorn.log --preload --pythonpath=/data/graphite/webapp/graphite

Mar 31 19:14:51 knx-rtb-graphite-eu systemd[1]: Started Graphite-web.
Mar 31 19:14:51 knx-rtb-graphite-eu sh[38858]: WARNING: whisper module could not be loaded, whisper support disabled

**Comment by deniszh** [comment]
Similar issue - https://github.com/graphite-project/whisper/issues/243
I.e. graphite-web can't find your whisper module for some reason.  It really depends how it was installed. How do you install Graphite python modules?

**Comment by Prasadevops0710** [comment]
@deniszh installed whsiper with pip
ubuntu@knx-rtb-graphite-eu:/data/graphite/conf$ pip show whisper
Name: whisper
Version: 1.1.8
Summary: Fixed size round-robin style database
Home-page: http://graphiteapp.org/
Author: Chris Davis
Author-email: chrismd@gmail.com
License: Apache Software License 2.0
Location: /home/ubuntu/.local/lib/python3.8/site-packages
Requires: six
Required-by:
