### ISSUE TITLE
[BUG] Metrics unavailable post Database migration

### ISSUE THREAD

**Issue by arnav0024** [graphite-project/graphite-web#2749]
Hi Team,
We are recently experiencing metrics unavailabilty post a particular date on our Graphite UI, During month of March we had migrated our ScyllaDB from an EKS cluster to a standalone ScyllaDB cluster setup. We are not able to visualize metrics stored in our DB post 8th of April. Wanted to understand what can be reason due to same.

Thanks and Regards

**Comment by deniszh** [comment]
Hi @arnav0024 

Sorry, could you please elaborate your question? Why ScyllaDB is part of your Graphite and what exactly you need from us?
