### ISSUE TITLE
Unable to run Graphite without root privlidges

### ISSUE THREAD

**Issue by jacksbarry** [graphite-project/graphite-web#2764]
We're trying to run graphite in an environment where we don't have root privileges.  This is a security constraint that we have.
We are using k8s and setting our readOnlyRootFileSystem to true which causes all the issues.

This can be reproduced by setting the readOnlyRootFileSystem to true when deploying to k8s.

We would expect Graphite to be able to run without root permissions.

Environment
Ubuntu 20.04.2 LTS (Focal Fossa)
Graphite 1.1.7-6

**Comment by deniszh** [comment]
Hi @jacksbarry 

This repo contains no docker image, so, I think you mean https://github.com/graphite-project/docker-graphite-statsd. But docker-graphite-statsd running all components in same image, so, contains init.d-like demon which starts other processes and kinda require super privileges.

We had [issue](https://github.com/graphite-project/docker-graphite-statsd/issues/104) about that, but as I said unfortunately image need to be split to run separate components of Graphite. I had no intention to spend time on that project, but we will accept PRs if you want to implement that.
