### ISSUE TITLE
holtWintersConfidenceArea not doing "predicted forecast deviations".

### ISSUE THREAD

**Issue by guismai** [graphite-project/graphite-web#2768]
Here is the definition of this function : 
holtWintersConfidenceArea(seriesList, delta=3, bootstrapInterval='7d', seasonality='1d')
Performs a Holt-Winters forecast using the series as input data and plots the area between the upper and lower bands of the **predicted forecast deviations**.

We try to get predicted forecast deviations with Graphite in a Grafana Dashboard with a time range from:"now-30d" and to:"now+30d", but nothing in future.   

HoltWinters*, linearRegression, etc... nothing in future.

What missing ?

**Comment by deniszh** [comment]
TBH I have no idea why all these forecast function exists, because Whisper do not support future datapoints, so, I suspecting Graphite also has problems with future data too. So, you can do predictions but only up to now, which IMO has quite limited use-case
