### ISSUE TITLE
[BUG]can not get window data in abs time  with render_api 

### ISSUE THREAD

**Issue by JiZhihan** [graphite-project/graphite-web#2769]
**Describe the bug**
In the reference of the render_api document，i can not get window data in abs time with format '&from=14:00_20220721&until=15:00_20220721'

document：https://graphite.readthedocs.io/en/latest/render_api.html

**To Reproduce**
send a get request:
https://carbonapi4pek02.pek01.in.zhihu.com/render?format=json&from=14:00_20220721&until=15:00_20220721&target=aliasByNode(summarize(sumSeries(feedrein.span.feed-root-web._all.client.topstory_recommend_get.root-core._all.preparer.request_time.percentile.95), '1d', 'avg', false), 8)

the response is 
strconv.ParseInt: parsing "04:00_20110501": invalid syntax

**Expected behavior**

**Screenshots**
<img width="877" alt="image" src="https://user-images.githubusercontent.com/56993966/180178152-986c36cf-d60a-45ed-95e0-98d59d63b962.png">

**Comment by deniszh** [comment]
URL "carbonapi..." suggesting that you're using [go-carbon/carbonapi](https://github.com/go-graphite/carbonapi) instead of graphite-web, probably you should ask in that repo. Although according to [doc](https://github.com/go-graphite/carbonapi/blob/main/COMPATIBILITY.md#uri-parameters) that should be compatible. Maybe try to quote it? 🤷

**Comment by JiZhihan** [comment]
> URL "carbonapi..." suggesting that you're using [go-carbon/carbonapi](https://github.com/go-graphite/carbonapi) instead of graphite-web, probably you should ask in that repo. Although according to [doc](https://github.com/go-graphite/carbonapi/blob/main/COMPATIBILITY.md#uri-parameters) that should be compatible. Maybe try to quote it or urlescape it? 🤷

it just change the domain...
i have used the timestamp to get what i need

http://carbonapi4pek02.pek01.in.zhihu.com/render?format=json&from=1658332800&until=1658396280&target=aliasByNode(summarize(sumSeries(feedrein
.span.feed-root-web._all.client.topstory_recommend_get.root-core._all.preparer.request_time.percentile.95),%20'1d',%20'avg',%20false),%208)

why  did not the official document mention this way..

**Comment by deniszh** [comment]
@JiZhihan : You probably do not understand my explanation. Your domain "carbonapi" suggest that you are not using graphite-web project. You're using [go-carbon/carbonapi](https://github.com/go-graphite/carbonapi) project, which is different project, implemented in go, which has own quirks and compatibility issues.

**Comment by JiZhihan** [comment]
> @JiZhihan : You probably do not understand my explanation. Your domain "carbonapi" suggest that you are not using graphite-web project. You're using [go-carbon/carbonapi](https://github.com/go-graphite/carbonapi) project, which is different project, implemented in go, which has own quirks and compatibility issues.

 i got you this time! thanks your explanation!
