### ISSUE TITLE
[Q]What is the holtWintersForecast of tomato prediction

### ISSUE THREAD

**Issue by zzzzzzzzlllllllll** [graphite-project/graphite-web#2773]
The functions document does not specify the logic of holtwwintersforecast

We want to use holtwisters to predict and cooperate with the alert to find abnormal fluctuations in time

Question 1：
Why is the bootstrapInterval set to 30d or 7d to get the same prediction results

I thought that the larger the bootstrap interval, the more accurate the prediction result, but in fact, the opposite is true

![image](https://user-images.githubusercontent.com/23024524/183373453-798bb950-0dca-48d3-93f1-84875b6c8143.png)

Question 2：

08-05 00:15 This time point is an exception example, and this case does not exist in historical data

But the Holt winters forecast also rose

At present, only holdwintersforecast (timeshift 7d) has some reference value

Besides this, what else can I do to forecast exception samples?

**Comment by deniszh** [comment]
Hi @zzzzzzzzlllllllll 

Unfortunately, for both questions I have no ready to use answers can only point you to the [code](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L3983-L4122). As you can see Graphite Holt Winters is opinionated implementation, so, here can be dragons.
For 2nd question is a bit easier - [as you can see in the code](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L4109-L4110) current implementation moving start point of bootstrap to the past  for required number of seconds, but it _do_not_reset_ end point, i.e. it includes all range into bootstrap. Theoretically, we can introduce new parameter to cut it at initial start point, so, that effect should gone.
