### ISSUE TITLE
[BUG] gt branch create not creating a new branch

### ISSUE THREAD

**Issue by shenders13** [graphite-project/graphite-web#2778]
**Describe the bug**

When I create a new branch with the Graphite CLI, I get an error:

```
ERROR: undefined is unknown to Graphite.
```

**To Reproduce**
1. I am on a feature branch
2. I make some local changes and stage them (green files in the screenshot below).
3. I try to create a new branch as per the [docs](https://docs.graphite.dev/guides/graphite-cli/creating-a-stack) i.e. `gt branch create -m "commit message here"` 
4. I run into the aformentioned error: `ERROR: undefined is unknown to Graphite.`

Here is a screenshot:

<img width="1691" alt="Screen Shot 2022-09-20 at 3 41 32 pm" src="https://user-images.githubusercontent.com/15011940/191377721-18eb8cb2-855d-4917-a077-4addae9f0217.png">

**Expected behavior**

A new branch is created.

**Environment (please complete the following information):**
 - OS flavor: macOS Monteray
 - Graphite-web version 0.20.10
 - Installed via homebrew.

**Comment by deniszh** [comment]
Hi @shenders13 

Sorry, wrong repo, you probably should open issue in https://github.com/withgraphite/graphite-cli instead.

Have a nice day!
