### ISSUE TITLE
[Q]Graphs not populating and I'm not sure why

### ISSUE THREAD

**Issue by itinneed2022** [graphite-project/graphite-web#2788]
Beginning at 9 am EST and ending around 12 pm EST, some metrics in the Graphite web-app do not update. There is zero commonality between the metrics that do not populate and the ones that do. I can check the carbon-cache logs and they are updating regularly. So carbon is updating. Same for the carbon-relay log. Following metricfire's blog I updated the carbon-hashing algorithm and reduced the memcached values but these changes made zero difference.

I'm not sure where to take the troubleshooting next. If the carbon daemons are working and the relay is working, it has to be the graphite-web right?

**Comment by deniszh** [comment]
Hi @itinneed2022 

Unfortunately, Graphite is quite complex software and I'm not sure that it's possible to give you interactive troubleshooting session over github issues. 
You can try to give us more information though  - more symptoms, configs, logs etc - maybe we can found there.

**Comment by itinneed2022** [comment]
@deniszh I'm looking for more of general advice on what to look at next. Something I noticed yesterday when I restart the graphite web and carbon services (cache and relay), I suddenly received an update on all the metrics that had not been showing data. Now, at 40 minutes past the hour (so 9:40, 10:40, 11:40 am etc), I'm getting an update across every lagging metric right up to the minute.

Is there a delay that's configured somewhere intentionally?
