### ISSUE TITLE
[Q] diffSeries on multiple series comparing to a single serie

### ISSUE THREAD

**Issue by nikobearrr** [graphite-project/graphite-web#2795]
I have 3 series which give me their timestamps in milliseconds:

```
#A: service.abc.timestamp
#B: service.xyz.timestamp
#C: ervice.mno.timestamp
```

and I would like to compare them with real time. I use

`#D: scale(time("now"), 1000)`

as a series to get the current time in milliseconds.

What I can do now is specify them 1 by 1 and and do a `diffSeries()`, e.g.

`diffSeries(#A, #D)` will give me the service `abc` vs current time.
`diffSeries(#B, #D)` will give me the service `xyz` vs current time.

What I would like to do, is do them on bulk. So for series #A I specify `service.*.timestamp` and then do `diffSeries(#A, #D)` and get the difference for any service that shows up.

I have tried the above, but that would not do it. As I understand it the `diffSeries()` compares 2 series and in the above case it combined the wildcard into 1.

My question is if what I would like is achievable and if yes how?

**Comment by deniszh** [comment]
You can try something like
```
applyByNode(service.*.timestamp,1,"diffSeries(%.timestamp,scale(time("now"), 1000))")
```
