### ISSUE TITLE
[BUG] Could not import graphite.local_settings, using defaults!

### ISSUE THREAD

**Issue by ichilton** [graphite-project/graphite-web#2811]
**Describe the bug**

I'm unable to get graphite-web to find local_settings.py. It's supposed to use: /etc/graphite/local_settings.py and /usr/lib/python3/dist-packages/graphite/settings.py does contain:

```
# Debian add etc/graphite into path
sys.path.append('/etc/graphite')
```
... but it's just unable to find it.

```
root@graphite:~# gunicorn graphite.wsgi --pythonpath=/usr/share/graphite-web --bind 127.0.0.1:8080
[2023-03-23 13:04:57 +0000] [466885] [INFO] Starting gunicorn 20.1.0
[2023-03-23 13:04:57 +0000] [466885] [INFO] Listening at: http://127.0.0.1:8080 (466885)
[2023-03-23 13:04:57 +0000] [466885] [INFO] Using worker: sync
[2023-03-23 13:04:57 +0000] [466886] [INFO] Booting worker with pid: 466886
Could not import graphite.local_settings, using defaults!
/usr/lib/python3/dist-packages/graphite/settings.py:359: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
```

I've spent a few hours poking around trying to work out why, but i've not as yet been able to get to the bottom of it.

It just seems not to be looking for it in the right place. It gives that warning whether it's there or not, i've tried dropping the example one in and just changing SECRET_KEY and tried putting symlinks in all kinds of paths where it might go looking for it, but nothing.

**To Reproduce**

- Install with `apt-get install graphite-web gunicorn`

- Edit /etc/graphite/local_settings.py and change SECRET_KEY

- Attempt to load with gunicorn: `gunicorn graphite.wsgi --pythonpath=/usr/share/graphite-web --bind 127.0.0.1:8080`.

**Expected behavior**

It should read /etc/graphite/local_settings.py and set the SECRET_KEY.

**Environment (please complete the following information):**
 - OS flavor: Debian 11 (bullseye)
 - Graphite-web version 1.1.8

```
root@graphite:~# dpkg -l |grep graphite
ii  graphite-carbon                1.1.7-1                        all          backend data caching and persistence daemon for Graphite
ii  graphite-web                   1.1.8-1.1~bpo11+1              all          Enterprise Scalable Realtime Graphing
```

 - Django/Python version [e.g. 1.11/2.7, 2.1/3.8 etc]

python3                        3.9.2-3
python3-django                 2:2.2.28-1~deb11u1

 - Setup type [e.g. pip, from sources, from OS packages etc]

OS packages.

**Comment by ichilton** [comment]
I can also re-produce this using when installing via PIP.

```
# export PYTHONPATH="/opt/graphite/lib/:/opt/graphite/webapp/"
# pip install --no-binary=:all: https://github.com/graphite-project/graphite-web/tarball/master
# cd /opt/graphite/conf ; ln -s /etc/graphite/local_settings.py
# /usr/bin/gunicorn wsgi --pythonpath=/opt/graphite/webapp/graphite --bind 127.0.0.1:8080
[2023-03-23 13:16:50 +0000] [467189] [INFO] Starting gunicorn 20.1.0
[2023-03-23 13:16:50 +0000] [467189] [INFO] Listening at: http://127.0.0.1:8080 (467189)
[2023-03-23 13:16:50 +0000] [467189] [INFO] Using worker: sync
[2023-03-23 13:16:50 +0000] [467190] [INFO] Booting worker with pid: 467190
Could not import graphite.local_settings, using defaults!
/opt/graphite/webapp/graphite/settings.py:360: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
```

**Comment by and1bm** [comment]
I guess this is related to https://bugs.debian.org/995461 where a fix is suggested: `os.environ.setdefault('GRAPHITE_SETTINGS_MODULE', 'local_settings')`
For me, this works so far.
