### ISSUE TITLE
[Q] How to find the version of an ancient installed graphite server

### ISSUE THREAD

**Issue by preetmyob** [graphite-project/graphite-web#2831]
I have inherited a really old graphite server that was installed about 8-10 years ago. I'm trying to work out which version of graphite this is.  We can access the main page, but we have no accounts or logins to the dashboard. 

What would be the best way to discover this by looking at the installed folders, please?

```
$ curl -sv http://localhost/metrics/find?query=carbon.*
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /metrics/find?query=carbon.* HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Wed, 06 Mar 2024 11:25:52 GMT
* Server Apache/2.4.7 (Ubuntu) is not blacklisted
< Server: Apache/2.4.7 (Ubuntu)
< Content-Length: 284
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /metrics/find was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at localhost Port 80</address>
</body></html>
* Connection #0 to host localhost left intact
```

**Comment by deniszh** [comment]
You can also try to call  `curl -sv http://localhost/version`

Or look for WEBAPP_VERSION in [webapp](https://github.com/graphite-project/graphite-web/tree/0ec7201c42ac2c14485c4c7eaab8a644082dc687/webapp)/[graphite](https://github.com/graphite-project/graphite-web/tree/0ec7201c42ac2c14485c4c7eaab8a644082dc687/webapp/graphite)/[settings.py](https://github.com/graphite-project/graphite-web/blob/0ec7201c42ac2c14485c4c7eaab8a644082dc687/webapp/graphite/settings.py#L31)

If it's < 1.2.0 - it's exact version. If 1.2.0-dev - it's installed from master and then it's hard to say.

**Comment by preetmyob** [comment]
> curl -sv http://localhost/version

This gives 404

> Or look for WEBAPP_VERSION in [webapp](https://github.com/graphite-project/graphite-web/tree/0ec7201c42ac2c14485c4c7eaab8a644082dc687/webapp)/[graphite](https://github.com/graphite-project/graphite-web/tree/0ec7201c42ac2c14485c4c7eaab8a644082dc687/webapp/graphite)/[settings.py](https://github.com/graphite-project/graphite-web/blob/0ec7201c42ac2c14485c4c7eaab8a644082dc687/webapp/graphite/settings.py#L31)
This is more promising:
` /opt/graphite/webapp/graphite/settings.py:29:WEBAPP_VERSION = '0.9.12'`

So it looks like this is 0.9.12. Would you agree?

**Comment by deniszh** [comment]
Yes, I would

**Comment by preetmyob** [comment]
Thank you
