### ISSUE TITLE
How to change the Graphite app’s auto-refresh feature to load a new graph every second.

### ISSUE THREAD

**Issue by gnemoug** [graphite-project/graphite-web#285]
By default, the app will only generate an updated graph every 60 seconds.How to change the Graphite app’s auto-refresh feature to load a new graph every second.

**Comment by Igor-Misic** [comment]
Hi everyone, 

did you try this with changing "change 'var interval = 60;' to 'var interval = 1;' in the function toggleAutoRefresh". 

I use graphite on ubuntu and my path is here:
/usr/share/graphite-web/static/js/composer_widgets.js

when I change something nothing has happened in graphite web. Do you know why?
