### ISSUE TITLE
Replace django-tagging with django-taggit

### ISSUE THREAD

**Issue by SEJeff** [graphite-project/graphite-web#326]
[Reasoning](http://www.davidfischer.name/2010/09/django-taggit-vs-django-tagging/)

[django-taggit](https://django-taggit.readthedocs.org/en/latest/) is easier to use from the admin for adding new tags and there is a sane migration path from django-tagging via some south magic.

**Comment by swills** [comment]
This needs to be addressed, django-tagging doesn't work with django 1.8 and is unmaintained, at least according to https://www.djangopackages.com/grids/g/tagging/

**Comment by obfuscurity** [comment]
@SEJeff is this relevant or can we close it out?
