### ISSUE TITLE
diffSeries doesn't handle constant

### ISSUE THREAD

**Issue by athoune** [graphite-project/graphite-web#415]
```
    &target=diffSeries(service.connections.total,5)
```

diffSeries works with two series, but crash with a constant.

Traceback (most recent call last):
  File &quot;/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 115, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File &quot;/opt/graphite/webapp/graphite/render/views.py&quot;, line 104, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 29, in evaluateTokens
    return func(requestContext, *args)
  File &quot;/opt/graphite/webapp/graphite/render/functions.py&quot;, line 229, in diffSeries
    (seriesList,start,end,step) = normalize(seriesLists)
  File &quot;/opt/graphite/webapp/graphite/render/functions.py&quot;, line 106, in normalize
    seriesList = reduce(lambda L1,L2: L1+L2,seriesLists)
  File &quot;/opt/graphite/webapp/graphite/render/functions.py&quot;, line 106, in &lt;lambda&gt;
    seriesList = reduce(lambda L1,L2: L1+L2,seriesLists)
TypeError: can only concatenate list (not &quot;int&quot;) to list

**Comment by g76r** [comment]
@piotr1212 
I think offset is viable in most cases.
Simple example: offset(my.metric,-1).
Or event diffSeries and then offset: offset(diffSeries(my.{a,b}.metrics),-1)
