### ISSUE TITLE
TypeError: 'NoneType' object is not iterable (graphite-web 9.12)

### ISSUE THREAD

**Issue by rev138** [graphite-project/graphite-web#427]
I was running into this error with certain graphs. The solution was to edit /opt/graphite/webapp/graphite/render/views.py

    if cachedData is not None:
      requestContext['data'] = data = cachedData
    else: # Have to actually retrieve the data now
      for target in requestOptions['targets']:
        t = time()
        seriesList = evaluateTarget(requestContext, target)
        log.rendering("Retrieval of %s took %.6f" % (target, time() - t))
        # added this conditional to avoid broken graphs
        if seriesList is not None:
                data.extend(seriesList)

**Comment by obfuscurity** [comment]
Fixed by #1341.
