### ISSUE TITLE
Inconsistent "divideSeries second argument must reference exactly 1 series"

### ISSUE THREAD

**Issue by LukaszStrzelecki** [graphite-project/graphite-web#450]
Hi,

Imagine you have "target=key.that.does.not.exist" - it outputs image with "No data" text or empty body if format=raw is set.

Imagine you have "target=divideSeries(key.that.does.not.exist, otherKey.that.does.not.exist)" - it returns 500 error with stacktrace etc (Exception Value:  divideSeries second argument must reference exactly 1 series)

Should it be unified? I would expect second returning empty image same way as the first one does.

Thanks,

**Comment by jpemberthy** [comment]
did you guys find out how to avoid this issue?

**Comment by chundongwang** [comment]
If you'd like a work around, here's mine.

I added a series full of zero to the possibly non-data series before sending it to `divideSeries()`. But `constantLine()` doesn't work as its frequency is too low. So I make two `identity()` of `"The.time.series"` and `diffSeries()` them to get a constant zero line with a lot of data points. And the perf of generating it should be fast as it doesn't have to pull anything from data source.

So at the end, it'd look like,
```
divideSeries(<your.data.series>, sumSeries(<your.nullable.data.series>, diffSeries(identity("The.time.series"),identity("The.time.series"))))
```

I know it's long but if you're generating it dynamically this wouldn't bother too much.

**Comment by craynic** [comment]
The solution provided by @chundongwang is great.
While the non-data series is not necessary.
This shouldd also work:
`divideSeries("some.series.*", sumSeries("another.series.*"))`
