### ISSUE TITLE
Break out docs into own repo

### ISSUE THREAD

**Issue by jblaine** [graphite-project/graphite-web#46]
I suggested this when the Great Github Move happened. I recall agreement that it was a good idea.

Either it got forgotten, is yet to be done but planned, or was decided not to be done.

This issue is for that.

**Comment by obfuscurity** [comment]
I'd also still love to see this happen. There are few docs experts among the core team so I'm not optimistic this will happen before 1.0.0, but I'm holding out hope for the next release after.

**Comment by piotr1212** [comment]
> the install fails (due to /opt/graphite not being writable).

https://github.com/graphite-project/graphite-web/pull/2409
