### ISSUE TITLE
Feature Request: pass absolute time-range for dashboards in the URL

### ISSUE THREAD

**Issue by dimovelev** [graphite-project/graphite-web#475]
Hi,

AFAIK it is currently not possible to set the time-range of a dashboard using just the URL. This would be a great feature as it would allow better integration in other tools. We, for example, run automated erformance tests (also on a nightly basis) and would like to integrate some links to graphite dashboards using the time-range when the performance test actually ran so that one can look at standard metrics (e.g. machine load, connection pool usages, garbage collection and so on) but also add additional metrics to the dashboard for adhoc analysis (this makes the render API a bad fit - we use it but it is not possible to easily add new metrics).

This feature should, IMHO, be pretty easy to implement for someone who knows the code a bit - and also doable for someone new.

How do you feel about it? Would you be interested if I contributed such a fix or do you already have plans for such a feature?

Cheers,
Dimo

PS. The request URL looks like this:
http://graphite/dashboard/?from=2013-10-24T08:30:00&until=2013-10-24T13:00:00#cpu - it opens the "cpu" dashboard and sets the absolute time range to the given values.

**Comment by qz267** [comment]
+1
