### ISSUE TITLE
Is sumSeries broken in master branch?

### ISSUE THREAD

**Issue by alexandreboisvert** [graphite-project/graphite-web#588]
Context: git clone on the master branch on 2014-01-15

In the Graphite web interface (Composer), if I select two data series and use the "Apply Function / Combine /Sum" menu, I get the blank image "No Data".

If a select 3 or more data series and use the sumSeries function on 2 of them, only the remaining data series will show. The two data series used in the sum disappeared.

Could somebody confirm this?

Thank you.

**Comment by cbowman0** [comment]
I cannot reproduce on `master`.
