### ISSUE TITLE
0.9.x: TypeError at /render/, fetch() takes at most 3 arguments (4 given)

### ISSUE THREAD

**Issue by yinyangxu** [graphite-project/graphite-web#597]
graphite-web fetch() arguments mismatch with whisper (both in version 0.9.x)

/opt/graphite/webapp/graphite/storage.py in fetch
  def getIntervals(self):
    start = time.time() - whisper.info(self.fs_path)['maxRetention']
    end = max( os.stat(self.fs_path).st_mtime, start )
    return [ (start, end) ]
  def fetch(self, startTime, endTime, now=None):
    return whisper.fetch(self.fs_path, startTime, endTime, now) 

whisper.py in fetch
698 def fetch(path,fromTime,untilTime=None):
...
710   fh = open(path,'rb')
711   return file_fetch(fh, fromTime, untilTime)

**Comment by contentfree** [comment]
If it helps someone in the future: I had mod_python26 installed instead of mod_python27 and therefore the stuff I'd installed with pip (for 2.7) wasn't working (though I apparently had enough vestiges of previous attempts that graphite got to the point captured in this issue).
