### ISSUE TITLE
aliasByNode behaves incorrectly with non-alphanumeric characters

### ISSUE THREAD

**Issue by kaathewise** [graphite-project/graphite-web#604]
Due to quite precise regex in `aliasByNode` function:

``` python
metric_pieces = re.search('(?:.*\()?(?P<name>[-\w*\.]+)?:,|\)?.*)?',series.name).groups()[0].split('.')
```

It fails to split series names with non-alphanumeric characters, for example `local.random:dice.roll` produces `('local', 'random')`. Although as far as I understand, `:` symbol goes smoothly in other parts of graphite.

In particular, adjacent function `aliasByMetric` does no special processing before split.

Unfortunately no evident solution for this problem has come to my mind so far.

**Comment by jimbydamonk** [comment]
I just hit this today. Everything works fine when I don't use aliasbynode with graphite-web-0.9.12-5.el6.noarch. As soon as I try the alias it gets truncated.

**Comment by w4tt** [comment]
Same here with an `@` character in the metric name.

**Comment by obfuscurity** [comment]
Happy to consider patches to the regex but it should include a test too.

**Comment by w4tt** [comment]
I've never developed in Python but I've checked it out. I'm wondering what's the use here for the regex ? The `aliasByMetric` function doesn't use a regex at all (it splits on ".").

When I do the same in `aliasByNode`, it fixes my problem (and probably the other's problem too).

Do you think it's a correct solution?

**Comment by phillijw** [comment]
```
aliasByNode(movingAverage(sumSeries(stats_counts.lp.prod.msp0wlnpp00{6,7,9}.pf1.request),25), 3) //This returns msp0wlnpp00
aliasByNode(movingAverage(sumSeries(stats_counts.lp.prod.msp0wlnpp00{6,7,9}.pf1.request),25), 4) //This crashed
```

Both of these seem incorrect behavior
