### ISSUE TITLE
graphite memcached integration does not work with django 1.5

### ISSUE THREAD

**Issue by msn** [graphite-project/graphite-web#612]
In settings.py, we have the following:

if MEMCACHE_HOSTS:
  CACHE_BACKEND = 'memcached://' + ';'.join(MEMCACHE_HOSTS) + ('/?timeout=%d' % DEFAULT_CACHE_DURATION)

However, CACHE_BACKEND was deprecated in django 1.3 and dropped in django 1.5 (https://docs.djangoproject.com/en/1.5/internals/deprecation/).

My fix was to roll back django to version 1.4 in my graphite python virtualenv.

I'd suggest the release notes recommend a version of django >=1.3 (since check-dependencies.py now requires this) and <=1.4 until support for memcache against django 1.5 is added?

Thanks!

**Comment by gsaray101** [comment]
in order for this to work, python client memecahced needs to be installed, right?

**Comment by gsaray101** [comment]
hi,

I installed memcached and python-memchace module. Inserted these lines to my local_settings.py file:

CACHE_MIDDLEWARE_SECONDS = 60
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': [
                '127.0.0.1:11211'
            ]
        }
}

When I click on a big node on graphite, it is timing out, not able to exapand the node. Any idease what might cause that, how could I increase the timeout value?
