### ISSUE TITLE
graphite-web install via pip doesn't show up in "pip freeze"

### ISSUE THREAD

**Issue by bahamat** [graphite-project/graphite-web#651]
This appears to be the same issue as [issue 86](https://github.com/graphite-project/carbon/issues/86) of carbon.

Same issue here, when using a configuration management system (e.g., CFEngine, Salt) the system can't properly detect that graphite-web is installed and tries to install it on every run.

**Comment by obfuscurity** [comment]
This is definitely causing problems with pip in `0.9.13-pre1`. We need to fix this for the upcoming release.

**Comment by brutasse** [comment]
@obfuscurity fixing this is just a matter of removing the `/opt/graphite` prefix in `setup.cfg`. But it's a big backwards-incompatible change and messes all paths in graphite's settings. Last time we talked about this, the conclusion was to keep the prefix in 0.9 and make a possibly breaking change in 0.10 to end up with a more common directory layout.

**Comment by deniszh** [comment]
:+1: what @brutasse said - I also see no way how it could be fixed in 0.9.13 w/o breaking many things. Maybe fixing it in 1.0-dev is much better idea?

**Comment by obfuscurity** [comment]
Yes, I remember that now. I guess at the time I didn't realize the extent of the breakage associated with keeping things the same for 0.9.13. AIUI there's no way to install via PyPI for this release.

**Comment by obfuscurity** [comment]
The installation docs now formally instruct the user to set `PYTHONPATH` before installing via pip. Fixed in https://github.com/graphite-project/graphite-web/commit/1904348a6adbdf3eecb0c31442285fe759061f13.
