### ISSUE TITLE
Dashboard authentication is not working ?

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/graphite-web#681]
I'm trying to improve access control by uncommenting dashboard auth settings in /opt/graphite/webapp/graphite/local_settings.py

```
###############################
# Authorization for Dashboard #
###############################
DASHBOARD_REQUIRE_AUTHENTICATION = True
DASHBOARD_REQUIRE_EDIT_GROUP = 'dashboard-editors-group'
DASHBOARD_REQUIRE_PERMISSIONS = True
```

I'm working with the embedded authentication ( using mysql as de database backend), and any authentication related log is written on the /opt/graphite/storage/log/webapp/*.log files.

What is what I'm doing wrong ?

**Comment by changbl** [comment]
I am seeing the same issue: Graphite-web dashboard authentication simply does NOT work. Every user which can access the dashboard via a web browser can modify/save dashboard without the need to login.

OS: Ubuntu 14.04
Graphite-web: 0.9.12

**Comment by galdreiman** [comment]
Is there any solution for this issue?
I really like Graphite and want to use it, but I cannot allow access to my systems data without authentication.

**Comment by deniszh** [comment]
You can use some external dashboard with authorization (e.g. Grafana http://grafana.org ) and limit Graphite access only from that Grafana host (localhost, if installing Grafana on the same host as Graphite)
