### ISSUE TITLE
Graphite Integration with TSDB

### ISSUE THREAD

**Issue by kds119** [graphite-project/graphite-web#693]
Hi,

Currently graphite does not support integration with TSDB. It uses the whisper database which is not as scalable as TSDB.  

We at Ebay have developed a solution for integrating Graphite with TSDB. Is it something the developer community at graphite would be willing to review ?

Thanks,
Kamaldeep Singh,
Ebay

**Comment by kenny-freeman** [comment]
+1 for opentsdb support

hmm.. thread seems to have died off?

Am looking at Bosun for alerting and haven't seen a carbon protocol compatible ingestion daemon for opentsb yet. That could be the next spare time project..

**Comment by grinapo** [comment]
Pity. I would have tried Apache [Kudu](http://kudu.apache.org/) which does have an OpenTSDB compatible [interface](https://github.com/danburkert/kudu-ts) but it seems **this** project has been missing in action. There is no good-looking opensource distributed backends around (and InfluxDB has been split to undistributed and paid), apart from the quite overcomplex hadoop based ones, and kudu looked like a pretty simple one. Unfortunately its interface isn't popular -- yet.
