### ISSUE TITLE
smartSummarize align to week/month

### ISSUE THREAD

**Issue by shakefu** [graphite-project/graphite-web#743]
I was wondering if there's a way to get smartSummarize to consistently align to week or month?

**Comment by toni-moreno** [comment]
Hi @shakefu I would like to test your code if you can do a PR . And perhaps I could help you. I need also this feature and I think could be really interesting.

Thanks a lot !!

**Comment by shakefu** [comment]
Right on. I'll try to get a PR put together in the near future.
