### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by chhantyal** [graphite-project/graphite-web#750]

**Comment by mscuthbert** [comment]
My guess is that's what the OP is suggesting (well, probably a hybrid, .six-based version).  After `supervisor`, carbon/graphite is now the second most used Python package not to support Py3 [and two of the next three either have a perfect Py2/3 drop-in replacement (PyMYSQL for MySQL-Python) or is a backport of a Py3 library].  It would be a wonderful thing to be able to use in Py3 if any of the developers are interested.

**Comment by stanjer** [comment]
Are there any problems with porting it to python3 (except work needs to be done by someone)?

**Comment by deniszh** [comment]
@stanjer : "except the work" - no, I don't think so.
But please note that we should stay to be compatible with 2.7 too,  so, it should be dual compatible.

**Comment by takluyver** [comment]
If anyone is looking to work on this, [modernize](https://pypi.python.org/pypi/modernize) and [future](https://pypi.python.org/pypi/future) are two tools that can automate a lot of the porting work - like 2to3, but they aim to keep compatibility with Python 2 as well.

Modernize is generally the more conservative of the two, and it will insert use of the well-known [six](http://six.readthedocs.io/) compatibility library. Future's `futurize` tool makes the code more like idiomatic Python 3, using its companion `future` library to make it work on Python 2.

**Comment by piotr1212** [comment]
@takluyver While I was working on porting carbon https://github.com/graphite-project/carbon/pull/656 it turned out a lot more complicated than to just run some automated tools. Issues which you'll run into: str<->unicode mess, functions returning different types, missing testcases, imported libraries which are not py3 compatible yet.

**Comment by takluyver** [comment]
Yup, the tools can help with the straightforward syntax changes, like changing `print x` to `print(x)`, but figuring out the changes to the data model still needs human work. I'm all too familiar with those issues ;-). But the job is much more tractable with the tools to help than doing it all manually.

**Comment by takluyver** [comment]
Attempted in #2139 .

**Comment by cclauss** [comment]
Is this issue closed?

**Comment by deniszh** [comment]
I think yes.

**Comment by codeasashu** [comment]
What the heck? Why is the issue closed?

**Comment by deniszh** [comment]
Because Graphite in general currently Python 3 compatible. If you have some
specific issue - please open specific issue.
