### ISSUE TITLE
graph rendering slows down exponentially with number of data-points -> O(n²)

### ISSUE THREAD

**Issue by powo** [graphite-project/graphite-web#770]
I'm having a metric collected every second and being stored with following aggregation:

``` [everything_1s7d_5min3mon]
pattern = .*\.1s\..*
retentions = 1:604800,300:26784
```

I noted that rendering graphs for e.g 7days is extremely slow (~49s) and when I changed the time-span between 1day and 7days i noted that the rendering time is exponentially increasing.

When selecting e.g 2weeks, it's ways faster, because the aggregated data is used.

First, I'm wondering why graphite is using the 1s resolution data for rendering a 500px wide graph, because would be much more reasonable to use the aggregated data therefore, but that's not the issue for me now. 

My bigger problem is the "exponential slowness".

I've put a lot of timing-logging into the rendering(glyph.py) stuff and it turned out that every iteration over the timeseries itself is causing the problem. I think the reason therefore is in the `TimeSeries` Class in `datalib.py`:

``` python
def __consolidatingGenerator(self, gen):
    buf = []
    for x in gen:                             # <<--- outer loop
      buf.append(x)
      if len(buf) == self.valuesPerPoint:
        while None in buf: buf.remove(None)
        if buf:
          yield self.__consolidate(buf)
          buf = []
        else:
          yield None
    while None in buf: buf.remove(None)
    if buf: yield self.__consolidate(buf)
    else: yield None
    raise StopIteration


  def __consolidate(self, values):
    usable = [v for v in values if v is not None]  # <<--- inner loop
    if not usable: return None
    if self.consolidationFunc == 'sum':
      return sum(usable)                           # <<--- inner loop
    if self.consolidationFunc == 'average':
      return float(sum(usable)) / len(usable)      # <<--- inner loop
    raise Exception, "Invalid consolidation function!"

```

For my case I had a `valuesPerPoint` of >1000 and there is a lot of potential to optimise in this two methods (in terms of performance, eventually loosing elegant/clean code)

**Comment by BErelentless** [comment]
hello
have you been able to finally speedu you rendering graph?
