### ISSUE TITLE
Graphlot broken due to missing flot.time plugin

### ISSUE THREAD

**Issue by pakal** [graphite-project/graphite-web#789]
Hello, I just installed graphite-web (0.9.12+debian-3)  on ubuntu 14.04, via apt-get.

All seems to work fine in main interfaces, but when I go to graphlot interface (from menu, or from a main page chart), the chart is empty, and firefox console displays "Error: Time mode requires the flot.time plugin.".

Wouldn't there be an incompatibility of jquery/flot packages in graphlot ?

**Comment by pavel-odintsov** [comment]
@darkstar thanks so much! Your advice helped me :)
