### ISSUE TITLE
json with `Infinity` values is invalid

### ISSUE THREAD

**Issue by alexdean** [graphite-project/graphite-web#813]
When I make a request like `http://mygraphite.com/render/?target=some.metric.name&format=json`, I expect to get valid JSON.

I sometimes get invalid JSON containing `Infinity` values.

``` json
[{"target": "some.metric.name", "datapoints": [[Infinity, 1407296460], [Infinity, 1407296520], [Infinity, 1407296580]]}]
```

Not sure what the correct output should be. Maybe `null`?

**Comment by torkelo** [comment]
@obfuscurity its not something I can patch as I use the native json parsers built into browsers.

**Comment by syepes** [comment]
Does there exist any kind workaround?

**Comment by obfuscurity** [comment]
Workaround? No.

I think @drawks was on the right track before. I'd prefer a name like `strictJson` but otherwise agree with his suggestions. Anyone volunteering to submit this change? :tongue:

**Comment by brutasse** [comment]
Do we know if 3rd party dashboard actually rely on that? I'd be more in favor of fixing the issue. Most dashboards using `format=json` being javascript-based [citation needed], we'd better make sure `JSON.parse` works with the returned data :)

I'd translate +inf to 1e9999, -inf to -1e9999 and nan to `null`.

**Comment by falkenbt** [comment]
Ping :)
This is hitting us as well since the codahale metrics library initialized values with -infinity, so graphs containing metrics that never got any update in the viewed timeframe will always break, which is not pretty.
