### ISSUE TITLE
aliasByMetric - Minor labeling bug in 0.9.x

### ISSUE THREAD

**Issue by syepes** [graphite-project/graphite-web#862]
Hello,

I have just found this minor aliasByMetric display bug, git 0.9.x branch of 22/08/2014
aliasByMetric:
![90050a0c-2710-11e4-9f06-ecf2ed814180](https://cloud.githubusercontent.com/assets/333081/4013624/527c1a76-2a18-11e4-8c72-457b28105657.jpg)

[Grafana issue #712](https://github.com/grafana/grafana/issues/712)

Best regards,
Sebastian

**Comment by toni-moreno** [comment]
Hi @obfuscurity this error is still happening on current master branch . where did you merge this fix?

Thank you very much

**Comment by obfuscurity** [comment]
https://github.com/graphite-project/graphite-web/commit/8edd64895fb0932c98274de37b8a3201a80d4e35

**Comment by toni-moreno** [comment]
I 

This commit doesn't fix a .

aliasByMetric(averageSeries(some.series.*.metric))

the result is still "metric)".
