### ISSUE TITLE
Test coverage for 0.10

### ISSUE THREAD

**Issue by obfuscurity** [graphite-project/graphite-web#863]
Now that we have a decent setup for testing with `tox` and TravisCI, we should look at filling in the missing coverage of tests, particularly in `render/functions.py`. Consider this an umbrella issue for tracking any missing tests.

/cc @brutasse @esc @SEJeff

**Comment by JeanFred** [comment]
We now have https://codecov.io/github/graphite-project/graphite-web so I’m closing this.

We may want to add more bells & whistles (like posting on PRs etc.) but that can come later.
