### ISSUE TITLE
Binary packaging for distros

### ISSUE THREAD

**Issue by obfuscurity** [graphite-project/graphite-web#864]
The project has been pretty slack in the past about making sure the binary packages work properly and are supported across the most popular versions. I don't think we need to go crazy, but it would be nice to set some goals, achieve them in `master`, and then backport the necessary bits for `0.9.x`.

Here's a shopping list of the distro versions I'd like to see us support. If I'm crazy or there are dependency issues (i.e. Python or Django), let's talk about that here.
- Fedora 20
- CentOS 5
- CentOS 6
- CentOS 7
- Ubuntu 14.04 LTS
- Ubuntu 12.04 LTS
- Debian 6
- Debian 7

/cc @thorrsson @bmhatfield @robbkidd @mzupan @mckern @rwoolley, who have all volunteered to help with packaging or have worked on Graphite packaging in the past.

/cc @brutasse @SEJeff @bitprophet 

P.S. This issue is currently only open in graphite-web, but obviously we'll need to consider carbon, whisper and ceres as well.

**Comment by obfuscurity** [comment]
Can anyone take a look at https://github.com/graphite-project/carbon/issues/355 with me?

**Comment by damm** [comment]
Any reason you can't Omnibus Graphite? there's only really a few targets and trying to address many versions will only complicate life.

**Comment by SEJeff** [comment]
Not a fan of omnibus, I'd rather be a good upstream and work with distributions to get our software included in their repos, and make it easy for our users to install on the various distros with somewhat reasonable native support. Omnibus encourages curl ...| sh, which makes me a very sad Keanu.

**Comment by sebito91** [comment]
I'm actually a member of the fedora-admin community and have been touting
Graphite and collectd for Fedora 22. We are currently working to add
graphite to the existing metrics collection backend (currently using
RRDTool) so I'm happy to help with that arm.

**Comment by obfuscurity** [comment]
@sebito91 That would be great, and now's the time to pitch in. Per https://github.com/graphite-project/carbon/issues/355, it seems that our build tarball is missing some distro stuff. Admittedly, I built it on a Mac, but I'm surprised that would matter. We can't very well make multiple tarballs available, one per distro/platform, for a single release (for PyPI).

**Comment by sebito91** [comment]
Happy
          to start looking at the issue.
          
          Quick update, mentioned pacakaging graphite-web for release
          during the Fedora-admin meeting this week and the team is
          stoked. They're keen to start testing it out on the
          infrastructure servers as soon as we can get it ready!
      Sebastian Borza
---------------
PGP: EDC2 BF61 4B91 14F2 AAB4  06C9 3744 7F3F E411 0D3E
      On 1/12/15 11:25 PM, Jason Dixon wrote:
    
    
      @sebito91 That would be great, and
        now's the time to pitch in. Per graphite-project/carbon#355,
        it seems that our build tarball is missing some distro stuff.
        Admittedly, I built it on a Mac, but I'm surprised that would
        matter. We can't very well make multiple tarballs available, one
        per distro/platform, for a single release (for PyPI).
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by obfuscurity** [comment]
@sebito91 Awesome.

**Comment by ArturGajowy** [comment]
Any chance to have 1.0.2 RPMs for centos anytime soon?

**Comment by piotr1212** [comment]
@ArturGajowy Do you mean 1.0.2 in EPEL 7 repository? For that to work Django will need to be updated first.

**Comment by ArturGajowy** [comment]
Does this mean "just forget it, the python world uses pip"?

**Comment by piotr1212** [comment]
@ArturGajowy I'm still not really sure which packages you are referring to.

**Comment by ArturGajowy** [comment]
`graphite-web`, `carbon`, `whisper`

I tried installing from pip, but got this:

![screen shot 2017-08-22 at 18 12 28](https://user-images.githubusercontent.com/460141/29816689-5f69703c-8cb5-11e7-8455-883b601d1311.png)

**Comment by piotr1212** [comment]
> I tried installing from pip, but got this:

I'm quite sure pip does not install in `/usr/lib/python2.7/site-packages/graphite` by default. Make sure to remove old installations.
