### ISSUE TITLE
Default database directory broken for dev setup

### ISSUE THREAD

**Issue by andrewbaxter** [graphite-project/graphite-web#933]
GRAPHITE_ROOT is defined based on the location of settings.py, but DATABASES hardcodes the database location to '/opt/graphite/storage'.  I don't have much experience setting up Graphite, but I couldn't setup the database or run the webserver due to permissions errors (following the directions here: https://graphite.readthedocs.org/en/latest/development.html).

Maybe something like this, which worked for me?
```diff
diff --git a/webapp/graphite/settings.py b/webapp/graphite/settings.py
index 59a1ee8..b60de7d 100644
--- a/webapp/graphite/settings.py
+++ b/webapp/graphite/settings.py
@@ -123,7 +123,7 @@ DASHBOARD_REQUIRE_EDIT_GROUP = None
 
 DATABASES = {
   'default': {
-    'NAME': '/opt/graphite/storage/graphite.db',
+    'NAME': join(STORAGE_DIR, 'graphite.db'),
     'ENGINE': 'django.db.backends.sqlite3',
     'USER': '',
     'PASSWORD': '',
```

**Comment by obfuscurity** [comment]
Fixed in https://github.com/graphite-project/graphite-web/pull/937.
