### ISSUE TITLE
Wildcard based operations

### ISSUE THREAD

**Issue by SITZ** [graphite-project/graphite-web#966]
Does graphite support wildcard based `difference`, `multiplication`, `divide` and other operations which take a series list right now?

Say, I have metrics in this format: `A.B.C.D`
where `A`, `B`, `C`, `D` all are variable

I want to multiply or divide all metrics `*.B.C1.*` and `*.B.C2.*` matching their names in place of `*` one-on-one fixing only the nodes at `B` and `C` position.
Is it possible to do this?

**Comment by andreparodi** [comment]
I'm facing this problem as well. 

Looking at the code i can see a simple fix would be to:
- check dividend and divisor are same length
- loop from 0 to length
- calculate dividend[i]/divisor[i]

I am thinking of creating a new function for this and submit it. Would that make sens? What would be a good name? divideSeriesMulti?

**Comment by SEJeff** [comment]
If you create a new function, just please add tests

**Comment by jruere** [comment]
[applyByNode](https://graphite.readthedocs.io/en/1.1.5/functions.html#graphite.render.functions.applyByNode) is the function for this, right?
