### ISSUE TITLE
Graphite-web can make use of graphite-api's multi_fetch

### ISSUE THREAD

**Issue by Civil** [graphite-project/graphite-web#967]
At least in 0.10.*

It's very useful for different databases like "Cassandra", "InfluxDB" and so on.

Changes seems to be pretty simple and shouldn't break any of existing functional:
https://github.com/brutasse/graphite-api/commit/c4b8445662ae36220074359ec64864b54a7c7767 + mine PR: https://github.com/brutasse/graphite-api/pull/55 which adds support of fetching multiple data for multiple targets.

This is really handy for databases that supports that.

**Comment by AndreevDm** [comment]
Hi. Any news here?

**Comment by linar-jether** [comment]
+1 for this issue, when querying many nodes just the latency of many `fetch()` calls can be very expensive (when using custom finders).
