### ISSUE TITLE
Make render functions pluggable/modularized

### ISSUE THREAD

**Issue by drawks** [graphite-project/graphite-web#988]
Render functions should be refactored to allow for plugging in additional "site-local" functions. This should be implemented in such a way that user can add entire functions or groups of functions that would extend the current capabilities of graphite-web OR override the existing functions with different versions which may provide better performance or slightly different implementation details which are more suitable to a user's needs.

We should for example support a user dropping a file into a directory which defines a group of functions which implement some seasonal statistical analysis which would otherwise be unsuitable for general inclusion.  Or a user should be able to drop in functions which reimplement some of the current core rendering functions but use numpy for optimized performance.

**Comment by DanCech** [comment]
This was implemented in #2146
